---
permalink: audit/audit-log-file-rotation.html 
sidebar: sidebar 
keywords: storagegrid, audit, log file, audit.log, audit.log file, rotation, save, autosave, auto save, auto-save 
summary: 監査ログ ファイルは、管理ノードの /var/local/audit/export/ ディレクトリに保存されます。アクティブな監査ログ ファイルの名前は audit.log です。 
---
= 監査ログファイルのローテーション
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRIDが*管理ノード/ローカルノード*または*管理ノードと外部Syslogサーバー*用に構成されている場合、監査ログファイルは管理ノードの `/var/local/audit/export/`ディレクトリ。アクティブな監査ログファイルの名前は `audit.log`。


NOTE: 必要に応じて、監査ログの送信先を変更し、監査情報を外部の syslog サーバーに送信することもできます。外部 Syslog サーバーが構成されている場合、監査レコードのローカル ログは引き続き生成され、保存されます。。 link:../monitor/configure-audit-messages.html["監査メッセージと外部syslogサーバの設定"] 。

アクティブなファイルが1日に1回 `audit.log`保存され、新しい `audit.log`ファイルが開始されます。保存されたファイルの名前は、の形式で保存された日時を示します `_yyyy-mm-dd.txt_`。1日に複数の監査ログが作成される場合は、ファイル名にファイルが保存された日付に番号が付加された形式でファイル名に使用され `_yyyy-mm-dd.txt.n_`ます。たとえば、 `2018-04-15.txt`2018年4月15日に作成されて保存された最初のログファイルと2番目のログファイルは、と `2018-04-15.txt.1`です。

1日後、保存されたファイルは圧縮され、名前が変更され、形式は次のようになります。 `_yyyy-mm-dd.txt.gz_` 、元の日付が保持されます。時間が経つにつれて、監査ログに割り当てられた管理ノードのストレージが消費されます。スクリプトは監査ログのスペース消費を監視し、必要に応じてログファイルを削除して、 `/var/local/audit/export/`ディレクトリ。監査ログは作成日に基づいて削除されます。最も古いログが最初に削除されます。次のファイルでスクリプトのアクションを監視できます。 `/var/local/log/manage-audit.log` 。

この例は、アクティブファイル、前日のファイル(`2018-04-15.txt`）、および前日の圧縮ファイルを示して `audit.log`(`2018-04-14.txt.gz`います。

[listing]
----
audit.log
2018-04-15.txt
2018-04-14.txt.gz
----