---
permalink: audit/cbrb-object-receive-begin.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, CBRB, Object Receive Begin 
summary: 通常のシステム運用中は、データへのアクセスおよびデータのレプリケートと保持が行われる際に、異なるノード間でコンテンツブロックが継続的に転送されます。このメッセージは、あるノードから別のノードへのコンテンツブロックの転送が開始したときに転送先のエンティティによって生成されます。 
---
= CBRB ：オブジェクト受信が開始されました
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通常のシステム運用中は、データへのアクセスおよびデータのレプリケートと保持が行われる際に、異なるノード間でコンテンツブロックが継続的に転送されます。このメッセージは、あるノードから別のノードへのコンテンツブロックの転送が開始したときに転送先のエンティティによって生成されます。

[cols="1a,1a,4a"]
|===
| コード | フィールド | 製品説明 


 a| 
CNID
 a| 
接続識別子
 a| 
ノード間のセッション / 接続の一意の識別子。



 a| 
CBID
 a| 
Content Block Identifier の略
 a| 
転送されるコンテンツブロックの一意の識別子。



 a| 
CTDR
 a| 
転送方向（ Transfer Direction ）
 a| 
CBID 転送がプッシュで開始されたかプルで開始されたかを示します。

PUSH ：転送処理は送信側エンティティによって要求されました。

PULL ：転送処理は受信側エンティティによって要求されました。



 a| 
CTSR
 a| 
ソースエンティティ
 a| 
CBID 転送のソース（送信側）のノード ID 。



 a| 
CTD
 a| 
デスティネーションエンティティ
 a| 
CBID 転送のデスティネーション（受信側）のノード ID 。



 a| 
CTSS
 a| 
開始シーケンスカウント（ Start Sequence Count ）
 a| 
最初のシーケンスカウントが要求されたことを示します。成功すると、このシーケンスカウントから転送が開始されます。



 a| 
CTES
 a| 
想定される終了シーケンス数
 a| 
最後に要求されたシーケンスカウントを示します。成功すると、このシーケンスカウントを受信したときに転送が完了したとみなされます。



 a| 
RSLT
 a| 
転送開始ステータス
 a| 
転送が開始された時点のステータス：

SUCS ：転送が開始されました。

|===
この監査メッセージは、 Content Block Identifier で識別されたとおりに単一のコンテンツでノード間のデータ転送処理が開始されたことを意味します。この処理では、「 Start Sequence Count 」から「 Expected End Sequence Count 」までのデータが要求されます。送信側と受信側のノードは、ノード ID によって識別されます。この情報を使用すると、システムのデータフローを追跡できます。ストレージ監査メッセージと組み合わせて使用すると、レプリカ数を検証できます。
