---
permalink: audit/cbse-object-send-end.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, CBSE, Object Send End 
summary: このメッセージは、あるノードから別のノードへのコンテンツブロックの転送が完了したときに転送元のエンティティによって生成されます。 
---
= CBSE ：オブジェクト送信終了
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このメッセージは、あるノードから別のノードへのコンテンツブロックの転送が完了したときに転送元のエンティティによって生成されます。

[cols="1a,1a,4a"]
|===
| コード | フィールド | 製品説明 


 a| 
CNID
 a| 
接続識別子
 a| 
ノード間のセッション / 接続の一意の識別子。



 a| 
CBID
 a| 
Content Block Identifier の略
 a| 
転送されるコンテンツブロックの一意の識別子。



 a| 
CTDR
 a| 
転送方向（ Transfer Direction ）
 a| 
CBID 転送がプッシュで開始されたかプルで開始されたかを示します。

PUSH ：転送処理は送信側エンティティによって要求されました。

PULL ：転送処理は受信側エンティティによって要求されました。



 a| 
CTSR
 a| 
ソースエンティティ
 a| 
CBID 転送のソース（送信側）のノード ID 。



 a| 
CTD
 a| 
デスティネーションエンティティ
 a| 
CBID 転送のデスティネーション（受信側）のノード ID 。



 a| 
CTSS
 a| 
開始シーケンスカウント（ Start Sequence Count ）
 a| 
転送が開始されたシーケンスカウントを示します。



 a| 
CTA
 a| 
実際の終了シーケンス数
 a| 
転送に成功した最後のシーケンスカウントを示します。実際の終了シーケンスカウントが開始シーケンスカウントと同じで、転送結果が成功しなかった場合、データは交換されませんでした。



 a| 
RSLT
 a| 
転送結果
 a| 
（送信側エンティティから見た）転送処理の結果：

SUCS ：転送が正常に完了しました。要求されたすべてのシーケンスカウントが送信されました。

CONL ：転送中に接続が失われました

CTMO ：接続の確立中または転送中に接続がタイムアウトしました

UNRE ：デスティネーションノード ID に到達できません

CRPT：破損したデータまたは無効なデータの受信が原因で転送が終了しました

|===
この監査メッセージは、ノード間のデータ転送処理が完了したことを意味します。転送結果が成功した場合は、「 Start Sequence Count 」から「 Actual End Sequence Count 」にデータが転送されます。送信側と受信側のノードは、ノード ID によって識別されます。この情報を使用すると、システムのデータフローを追跡し、エラーを検出、集計、分析できます。ストレージ監査メッセージと組み合わせれば、レプリカ数の検証にも使用できます。
