---
permalink: audit/common-elements-in-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, messages, message, common elements, AMID, ANID, ASES, ASQN, ATID, ATIM, ATYP, AVER, RSLT 
summary: すべての監査メッセージには、共通の要素が含まれています。 
---
= 監査メッセージの共通要素
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
すべての監査メッセージには、共通の要素が含まれています。

[cols="1a,1a,4a"]
|===
| コード | タイプ | 製品説明 


 a| 
AMid
 a| 
FC32
 a| 
Module ID：メッセージを生成したモジュールIDの4文字の識別子。これは、監査メッセージが生成されたコードセグメントを示します。



 a| 
ANID
 a| 
UI32
 a| 
Node ID ：メッセージを生成したサービスに割り当てられたグリッドノード ID 。各サービスには、 StorageGRID システムの設定およびインストール時に一意の識別子が割り当てられます。このIDは変更できません。



 a| 
ASES
 a| 
UI64
 a| 
Audit Session Identifier ：以前のリリースでは、この要素はサービスの開始後に監査システムが初期化された時間を示していました。この時間値は、オペレーティングシステムのエポック（1970年1月1日00：00：00 UTC）からのマイクロ秒数で測定されました。

* 注： * この要素は廃止され、監査メッセージには表示されなくなりました。



 a| 
ASQN
 a| 
UI64
 a| 
Sequence Count ：以前のリリースでは、このカウンタはグリッドノード（ ANID ）上で監査メッセージが生成されるたびに増分し、サービスの再起動時にゼロにリセットされていました。

* 注： * この要素は廃止され、監査メッセージには表示されなくなりました。



 a| 
ATID
 a| 
UI64
 a| 
Trace ID ： 1 つのイベントによってトリガーされた一連のメッセージで共有される識別子。



 a| 
ATIM
 a| 
UI64
 a| 
Timestamp：監査メッセージをトリガーしたイベントが生成された時刻。オペレーティングシステムのエポック（1970年1月1日00：00：00 UTC）からのマイクロ秒数で測定されます。タイムスタンプをローカルの日時に変換するためのツールは、ほとんどがミリ秒に基づいています。

ログに記録されたタイムスタンプの丸めや切り捨てが必要な場合があります。ファイル内の監査メッセージの先頭に表示される判読可能な時刻 `audit.log`は、ISO 8601形式のATIM属性です。日付と時刻は、で表され `_YYYY-MMDDTHH:MM:SS.UUUUUU_`ます。 `T`は、日付の時間セグメントの先頭を示すリテラル文字列です。 `_UUUUUU_`はマイクロ秒です。



 a| 
ATYP
 a| 
FC32
 a| 
Event Type：ログに記録されるイベントの4文字の識別子。これは、メッセージの「ペイロード」コンテンツ、つまり含まれる属性を管理します。



 a| 
ビーバー
 a| 
UI32
 a| 
Version ：監査メッセージのバージョン。StorageGRID ソフトウェアのバージョンアップに伴い、新しいバージョンのサービスによって新しい機能が監査レポートに組み込まれる可能性があります。このフィールドは、旧バージョンのサービスのメッセージを処理できるよう、 AMS サービスにおける下位互換性を可能にします。



 a| 
RSLT
 a| 
FC32
 a| 
Result ：イベント、プロセス、またはトランザクションの結果。該当しないメッセージの場合は、誤ってフィルタリングされないように SUCS ではなく NONE が使用されます。

|===