---
permalink: audit/etaf-security-authentication-failed.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, ETAF, Security Authentication Failed 
summary: このメッセージは、 Transport Layer Security \ （ TLS\ ）を使用した接続試行が失敗した場合に生成されます。 
---
= ETAF ：セキュリティ認証に失敗しました
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このメッセージは、 Transport Layer Security （ TLS ）を使用した接続試行が失敗した場合に生成されます。

[cols="1a,1a,4a"]
|===
| コード | フィールド | 製品説明 


 a| 
CNID
 a| 
接続識別子
 a| 
認証が失敗した TCP / IP 接続の一意のシステム識別子。



 a| 
RUID
 a| 
ユーザ ID
 a| 
リモートユーザの ID を表すサービスに依存する識別子。



 a| 
RSLT
 a| 
理由コード
 a| 
失敗の理由：

SCNI ：セキュアな接続を確立できませんでした。

CERM ：証明書がありません。

CERT ：証明書が無効です。

CERE ：証明書が期限切れです。

CERR ：証明書が取り消されています。

CSGN ：証明書の署名が無効です。

CSGU ：証明書の署名者が不明です。

UCRM ：ユーザクレデンシャルがありません。

UCRI ：ユーザクレデンシャルが無効です。

UCRU ：ユーザのクレデンシャルが拒否されました。

TOUT ：認証がタイムアウトしました。

|===
TLS を使用するセキュアなサービスへの接続が確立されると、サービスに組み込まれている TLS プロファイルおよびその他のロジックを使用してリモートエンティティのクレデンシャルが検証されます。無効、想定外、許可されていない証明書またはクレデンシャルが原因でこの認証が失敗すると、監査メッセージがログに記録されます。これにより、不正アクセスやその他のセキュリティ関連の接続問題を照会できます。

このメッセージは、リモートエンティティの設定が正しくない場合や、無効または許可されていないクレデンシャルをシステムに提示しようとした場合に生成されることがあります。この監査メッセージを監視して、システムへの不正なアクセス試行を検出する必要があります。
