---
permalink: audit/gted-grid-task-ended.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, GTED, Grid Task Ended 
summary: この監査メッセージは、 CMN サービスが指定されたグリッドタスクの処理を完了し、タスクを Historical テーブルに移動したことを示します。結果が SUCS 、 ABRT 、 ROLF のいずれかである場合は、対応する Grid Task Started 監査メッセージも生成されます。それ以外の結果は、このグリッドタスクの処理が開始されなかったことを示します。 
---
= GTED ： Grid タスクが終了しました
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この監査メッセージは、 CMN サービスが指定されたグリッドタスクの処理を完了し、タスクを Historical テーブルに移動したことを示します。結果が SUCS 、 ABRT 、 ROLF のいずれかである場合は、対応する Grid Task Started 監査メッセージも生成されます。それ以外の結果は、このグリッドタスクの処理が開始されなかったことを示します。

[cols="1a,1a,4a"]
|===
| コード | フィールド | 製品説明 


 a| 
TSID
 a| 
タスクID
 a| 
このフィールドは、生成されたグリッドタスクを一意に識別します。また、グリッドタスクをライフサイクル全体にわたって管理できます。

* 注： * タスク ID は、グリッドタスクが送信された時点ではなく、生成された時点で割り当てられます。特定のグリッドタスクを複数回送信することができます。この場合、送信済み、開始、および終了の監査メッセージを一意にリンクするためのタスク ID フィールドでは不十分です。



 a| 
RSLT
 a| 
結果
 a| 
グリッドタスクの最終ステータス：

* SUCS ：グリッドタスクが正常に完了しました。
* ABRT：グリッドタスクはロールバックエラーなしで終了しました。
* Rolf：グリッドタスクは終了し、ロールバックプロセスを完了できませんでした。
* CANC ：グリッドタスクは開始前にユーザによってキャンセルされました。
* EXPR ：グリッドタスクは開始前に期限切れとなりました。
* IVLD ：グリッドタスクは無効でした。
* AUTH ：グリッドタスクは許可されていませんでした。
* DUPL ：グリッドタスクは重複として拒否されました。


|===