---
permalink: audit/idel-ilm-initiated-delete.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, IDEL, ILM Initiated Delete 
summary: このメッセージは、 ILM によってオブジェクトを削除する処理が開始された場合に生成されます。 
---
= IDEL ： ILM Initiated Delete
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このメッセージは、 ILM によってオブジェクトを削除する処理が開始された場合に生成されます。

IDEL メッセージは、次のいずれかの状況で生成されます。

* * 準拠 S3 バケット内のオブジェクト * ：このメッセージは、保持期間が経過したために ILM によってオブジェクトの自動削除処理が開始された場合に生成されます（自動削除設定が有効になっていて、リーガルホールドがオフの場合）。
* *非準拠S3バケット内のオブジェクトの場合*。このメッセージは、現在オブジェクトに適用されている配置手順がアクティブなILMポリシーにないためにオブジェクトを削除する処理がILMによって開始された場合に生成されます。


[cols="1a,1a,4a"]
|===
| コード | フィールド | 製品説明 


 a| 
CBID
 a| 
Content Block Identifier の略
 a| 
オブジェクトの CBID 。



 a| 
CMPA
 a| 
準拠：自動削除
 a| 
準拠 S3 バケット内のオブジェクトのみが対象。0 （ false ）または 1 （ true ）。バケットがリーガルホールドの対象である場合を除き、保持期間の終了時に準拠オブジェクトを自動的に削除するかどうかを示します。



 a| 
テンプレート
 a| 
コンプライアンス：リーガルホールド
 a| 
準拠 S3 バケット内のオブジェクトのみが対象。0 （ false ）または 1 （ true ）。バケットが現在リーガルホールドの対象であるかどうかを示します。



 a| 
CMPR
 a| 
準拠：保持期間
 a| 
準拠 S3 バケット内のオブジェクトのみが対象。オブジェクトの保持期間の長さ（分）。



 a| 
CTME
 a| 
準拠：取り込み時間
 a| 
準拠 S3 バケット内のオブジェクトのみが対象。オブジェクトの取り込み時間。この値に保持期間を分単位で追加することで、オブジェクトをバケットから削除できるタイミングを判断できます。



 a| 
dmrk
 a| 
マーカーバージョン ID を削除します
 a| 
バージョン管理されたバケットからオブジェクトを削除するときに作成された削除マーカーのバージョン ID 。バケットに対する処理では、このフィールドは指定されません。



 a| 
CSIZ
 a| 
コンテンツのサイズ
 a| 
オブジェクトのサイズ（バイト）。



 a| 
LOCS
 a| 
場所
 a| 
StorageGRID システム内のオブジェクトデータの格納場所。オブジェクトに場所がない場合（削除されている場合など）、 LOCS の値は "" です。

CLEC：イレイジャーコーディングオブジェクトの場合、オブジェクトのデータに適用されているイレイジャーコーディングプロファイルIDとイレイジャーコーディンググループID。

CLDI ：レプリケートされたオブジェクトの場合、オブジェクトの場所の LDR ノード ID とボリューム ID 。

CLNL ：オブジェクトデータがアーカイブされている場合は、オブジェクトの場所の ARC ノード ID 。



 a| 
パス
 a| 
S3バケット/キー
 a| 
S3バケット名とS3キー名。



 a| 
RSLT
 a| 
結果
 a| 
ILM 処理の結果。

SUCS ： ILM 処理が成功しました。



 a| 
ルール
 a| 
ルールラベル（ Rules Label ）
 a| 
* 保持期間が経過したために準拠 S3 バケット内のオブジェクトが自動的に削除されている場合、このフィールドは空白になります。
* 現在オブジェクトに適用される配置手順がないためにオブジェクトが削除されている場合、このフィールドには、オブジェクトに適用された最後の ILM ルールの判読可能なラベルが表示されます。




 a| 
SgRP
 a| 
サイト（グループ）
 a| 
オブジェクトが存在する場合は、指定したサイトで削除されています。このサイトは、オブジェクトが取り込まれたサイトではありません。



 a| 
UUID
 a| 
Universally Unique Identifier の略
 a| 
StorageGRID システム内でのオブジェクトの識別子。



 a| 
VSID
 a| 
バージョン ID
 a| 
削除されたオブジェクトの特定のバージョンのバージョン ID 。バージョン管理に対応していないバケット内のバケットおよびオブジェクトに対する処理には、このフィールドは含まれません。

|===