---
permalink: audit/lkdm-leaked-object-cleanup.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, LKDM, Leaked Object Cleanup 
summary:  
---
= LKDM:リークオブジェクトのクリーンアップ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このメッセージは、リークしたチャンクがクリーンアップまたは削除された場合に生成されます。チャンクは、レプリケートオブジェクトまたはイレイジャーコーディングオブジェクトの一部です。

[cols="1a,1a,4a"]
|===
| コード | フィールド | 製品説明 


 a| 
CLOC
 a| 
チャンクの場所
 a| 
削除されたリークされたチャンクのファイルパス。



 a| 
CTYP
 a| 
チャンクタイプ
 a| 
チャンクのタイプ：

`ec: Erasure-coded object chunk`

`repl: Replicated object chunk`



 a| 
LTYP
 a| 
リークタイプ
 a| 
次の5種類の漏れが検出されます。

`object_leaked: Object doesn’t exist in the grid`

`location_leaked: Object exists in the grid, but found location doesn’t belong to object`

`mup_seg_leaked: Multipart upload was stopped or not completed, and the segment/part was left out`

`segment_leaked: Parent UUID/CBID (associated container object) is valid but doesn't contain this segment`

`no_parent: Container object is deleted, but object segment was left out and not deleted`



 a| 
CTIM
 a| 
チャンクの作成時間
 a| 
リークされたチャンクが作成された時刻。



 a| 
UUID
 a| 
Universally Unique Identifier の略
 a| 
チャンクが属するオブジェクトの識別子。



 a| 
CBID
 a| 
Content Block Identifier の略
 a| 
リークされたチャンクが属するオブジェクトのCBID。



 a| 
CSIZ
 a| 
コンテンツのサイズ
 a| 
チャンクのサイズ（バイト）。

|===