---
permalink: audit/orlm-object-rules-met.html 
sidebar: sidebar 
keywords: audit message, ORLM, Object Rules Met, ilm rule 
summary: このメッセージは、 ILM ルールで指定されたとおりにオブジェクトが格納およびコピーされた場合に生成されます。 
---
= ORLM ：オブジェクトルールが満たされています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このメッセージは、 ILM ルールで指定されたとおりにオブジェクトが格納およびコピーされた場合に生成されます。


NOTE: ORLM メッセージは、ポリシー内の別のルールで高度なフィルタ「オブジェクトサイズ」が使用されている場合に、オブジェクトがデフォルトの Make 2 Copies ルールによって格納されたときには生成されません。

[cols="1a,1a,4a"]
|===
| コード | フィールド | 製品説明 


 a| 
bUID
 a| 
バケットヘッダー
 a| 
バケット ID フィールド。内部処理に使用されます。STAT が PRGD の場合にのみ表示されます。



 a| 
CBID
 a| 
Content Block Identifier の略
 a| 
オブジェクトの CBID 。



 a| 
CSIZ
 a| 
コンテンツのサイズ
 a| 
オブジェクトのサイズ（バイト）。



 a| 
LOCS
 a| 
場所
 a| 
StorageGRID システム内のオブジェクトデータの格納場所。オブジェクトに場所がない場合（削除されている場合など）、 LOCS の値は "" です。

CLEC：イレイジャーコーディングオブジェクトの場合、オブジェクトのデータに適用されているイレイジャーコーディングプロファイルIDとイレイジャーコーディンググループID。

CLDI ：レプリケートされたオブジェクトの場合、オブジェクトの場所の LDR ノード ID とボリューム ID 。

CLNL ：オブジェクトデータがアーカイブされている場合は、オブジェクトの場所の ARC ノード ID 。



 a| 
パス
 a| 
S3バケット/キー
 a| 
S3バケット名とS3キー名。



 a| 
RSLT
 a| 
結果
 a| 
ILM 処理の結果。

SUCS ： ILM 処理が成功しました。



 a| 
ルール
 a| 
ルールラベル（ Rules Label ）
 a| 
このオブジェクトに適用されている ILM ルールの判読可能なラベル。



 a| 
SEGC
 a| 
コンテナUUID
 a| 
セグメント化されたオブジェクトのコンテナのUUID。この値は、オブジェクトがセグメント化されている場合にのみ使用できます。



 a| 
SGCB
 a| 
コンテナCBID
 a| 
セグメント化されたオブジェクトのコンテナのCBID。この値はセグメント化されたオブジェクトとマルチパートオブジェクトに対してのみ使用できます。



 a| 
統計
 a| 
ステータス
 a| 
ILM 処理のステータス。

DONE ：オブジェクトに対する ILM 処理が完了しました。

DFER ： ILM によって再評価されるようオブジェクトがマークされました。

PRGD ：オブジェクトが StorageGRID システムから削除されました。

NLOC ：オブジェクトデータを StorageGRID システムで検出できなくなります。このステータスは、オブジェクトデータのすべてのコピーが欠落または破損していることを示している可能性があります。



 a| 
UUID
 a| 
Universally Unique Identifier の略
 a| 
StorageGRID システム内でのオブジェクトの識別子。



 a| 
VSID
 a| 
バージョン ID
 a| 
バージョン管理されたバケットで作成された新しいオブジェクトのバージョン ID 。バージョン管理に対応していないバケット内のバケットおよびオブジェクトに対する処理には、このフィールドは含まれません。

|===
ORLM監査メッセージは、1つのオブジェクトに対して複数回発行できます。たとえば、次のいずれかのイベントが発生するたびに発行されます。

* オブジェクトが対応する ILM ルールを無期限に満たしたとき。
* オブジェクトが対応する ILM ルールを一時的に満たしたとき。
* オブジェクトが ILM ルールによって削除されたとき。
* バックグラウンド検証プロセスにより、レプリケートされたオブジェクトデータのコピーが破損していることが検出されたとき。StorageGRID システムは、破損したオブジェクトを交換するために ILM 評価を実行します。


.関連情報
* link:object-ingest-transactions.html["オブジェクトの取り込みトランザクション"]
* link:object-delete-transactions.html["オブジェクトの削除トランザクション"]

