---
permalink: audit/s3-select-request.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, S3SL, S3 Select request 
summary: このメッセージは、ユーザがS3 Selectジョブを開始したことを示します。 
---
= S3SL：S3 Select要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このメッセージは、S3 Select要求がクライアントに返されたあとに完了を記録します。S3SLメッセージには、エラーメッセージとエラーコードの詳細を含めることができます。要求は成功しなかった可能性があります。

[cols="1a,1a,4a"]
|===
| コード | フィールド | 製品説明 


 a| 
BYSC
 a| 
スキャンされたバイト数
 a| 
ストレージノードからスキャン（受信）されたバイト数。

オブジェクトが圧縮されている場合、BYSCとBYPRは異なる可能性があります。オブジェクトが圧縮されている場合、BYSCは圧縮されたバイト数を持ち、BYPRは解凍後のバイト数になります。



 a| 
BYPR
 a| 
処理されたバイト数
 a| 
処理されたバイト数。S3 Selectジョブで実際に処理または処理された「スキャンされたバイト数」のバイト数を示します。



 a| 
BYRT
 a| 
返されたバイト数
 a| 
S3 Selectジョブがクライアントに返されたバイト数。



 a| 
レポート
 a| 
処理されたレコード
 a| 
S3 Selectジョブがストレージノードから受信したレコードまたは行の数。



 a| 
RERT
 a| 
レコードが返されました
 a| 
S3 Selectジョブがクライアントに返されたレコードまたは行の数。



 a| 
JOFI
 a| 
ジョブは終了しました
 a| 
S3 Selectジョブの処理が完了したかどうかを示します。これがfalseの場合、ジョブは完了しませんでした。エラーフィールドにはデータが含まれている可能性があります。クライアントに結果が一部しか表示されていない場合や、結果がまったく表示されない場合があります。



 a| 
リード
 a| 
Request ID
 a| 
S3 Select要求の識別子。



 a| 
EXTM
 a| 
実行時間
 a| 
S3 Selectジョブが完了するまでにかかった時間（秒）。



 a| 
ERMG
 a| 
エラーメッセージ
 a| 
S3 Selectジョブが生成されたことを示すエラーメッセージ。



 a| 
アーティ
 a| 
エラータイプ
 a| 
S3 Selectジョブが生成したエラータイプ。



 a| 
エルスト
 a| 
スタックトレースエラー
 a| 
S3 Selectジョブが生成したエラーStacktrace。



 a| 
S3BK
 a| 
S3バケット
 a| 
S3 バケット名。



 a| 
S3AK
 a| 
S3 アクセスキー ID （要求の送信者）
 a| 
要求を送信したユーザのS3アクセスキーID。



 a| 
S3AI
 a| 
S3 テナントアカウント ID （要求の送信者）
 a| 
要求を送信したユーザのテナントアカウント ID 。



 a| 
S3KY
 a| 
S3 キー
 a| 
バケット名を除く S3 キーの名前。

|===