---
permalink: audit/sdel-s3-delete.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SDEL, S3 DELETE 
summary: S3 クライアントが DELETE トランザクションを実行すると、指定したオブジェクトまたはバケットを削除する要求が送信されます。このメッセージは、トランザクションが成功した場合にサーバによって出力されます。 
---
= SDEL ： S3 DELETE
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3クライアントがDELETEトランザクションを実行すると、指定したオブジェクトまたはバケットを削除する要求、またはバケット/オブジェクトサブリソースを削除する要求が送信されます。このメッセージは、トランザクションが成功した場合にサーバによって出力されます。

[cols="1a,1a,4a"]
|===
| コード | フィールド | 製品説明 


 a| 
CBID
 a| 
Content Block Identifier の略
 a| 
要求されたコンテンツブロックの一意の識別子。CBID が不明な場合、このフィールドは 0 に設定されます。バケットに対する処理では、このフィールドは指定されません。



 a| 
CNCH
 a| 
整合性制御ヘッダー
 a| 
要求に Consistency-Control HTTP 要求ヘッダーが存在する場合は、その値。



 a| 
CNID
 a| 
接続識別子
 a| 
TCP / IP 接続の一意のシステム識別子。



 a| 
CSIZ
 a| 
コンテンツサイズ（ Content Size ）
 a| 
削除されたオブジェクトのサイズ（バイト単位）。バケットに対する処理では、このフィールドは指定されません。



 a| 
dmrk
 a| 
マーカーバージョン ID を削除します
 a| 
バージョン管理されたバケットからオブジェクトを削除するときに作成された削除マーカーのバージョン ID 。バケットに対する処理では、このフィールドは指定されません。



 a| 
GFID
 a| 
グリッドフェデレーション接続ID
 a| 
グリッド間レプリケーションの削除要求に関連付けられたグリッドフェデレーション接続の接続ID。デスティネーショングリッドの監査ログにのみ含まれます。



 a| 
gfsaだ
 a| 
GridフェデレーションのソースアカウントID
 a| 
グリッド間レプリケーションの削除要求を行うソースグリッド上のテナントのアカウントID。デスティネーショングリッドの監査ログにのみ含まれます。



 a| 
HTRH
 a| 
HTTP 要求ヘッダー
 a| 
設定時に選択した、ログに記録される HTTP 要求ヘッダーの名前と値のリスト。

 `X-Forwarded-For`は、要求に含まれていて、値が要求の送信元IPアドレス（SAIP監査フィールド）と異なる場合に自動的に追加されます `X-Forwarded-For`。

`x-amz-bypass-governance-retention`は、要求に含まれている場合は自動的に追加されます。



 a| 
MTME
 a| 
最終変更時刻
 a| 
オブジェクトが最後に変更された日時を示す Unix タイムスタンプ（マイクロ秒）。



 a| 
RSLT
 a| 
結果コード
 a| 
DELETEトランザクションの結果。常に次の結果になります。

SUCS ：成功しました



 a| 
S3AI
 a| 
S3 テナントアカウント ID （要求の送信者）
 a| 
要求を送信したユーザのテナントアカウント ID 。空の値は匿名アクセスであることを示します。



 a| 
S3AK
 a| 
S3 アクセスキー ID （要求の送信者）
 a| 
要求を送信したユーザのハッシュ済み S3 アクセスキー ID 。空の値は匿名アクセスであることを示します。



 a| 
S3BK
 a| 
S3 バケット
 a| 
S3 バケット名。



 a| 
S3KY
 a| 
S3 キー
 a| 
バケット名を除く S3 キーの名前。バケットに対する処理では、このフィールドは指定されません。



 a| 
S3SR
 a| 
S3 サブリソース
 a| 
必要に応じて、処理対象のバケットまたはオブジェクトサブリソース。



 a| 
SACC
 a| 
S3 テナントアカウント名（要求の送信者）
 a| 
要求を送信したユーザのテナントアカウントの名前。匿名の要求の場合は空です。



 a| 
saip
 a| 
IP アドレス（要求送信者）
 a| 
要求を送信したクライアントアプリケーションの IP アドレス。



 a| 
SBAC
 a| 
S3 テナントアカウント名（バケット所有者）
 a| 
バケット所有者のテナントアカウント名。クロスアカウントアクセスまたは匿名アクセスの識別に使用します。



 a| 
SBAI
 a| 
S3 テナントアカウント ID （バケット所有者）
 a| 
ターゲットバケットの所有者のテナントアカウント ID 。クロスアカウントアクセスまたは匿名アクセスの識別に使用します。



 a| 
SgRP
 a| 
サイト（グループ）
 a| 
オブジェクトが存在する場合は、指定したサイトで削除されています。このサイトは、オブジェクトが取り込まれたサイトではありません。



 a| 
サスペンション
 a| 
S3 ユーザの URN （要求の送信者）
 a| 
要求を送信しているユーザのテナントアカウント ID とユーザ名。ローカルユーザまたは LDAP ユーザです。例： `urn:sgws:identity::03393893651506583485:root`

匿名の要求の場合は空です。



 a| 
時間
 a| 
時間
 a| 
要求の合計処理時間（マイクロ秒）。



 a| 
TLIP
 a| 
信頼できるロードバランサの IP アドレス
 a| 
要求が信頼できるレイヤ 7 ロードバランサによってルーティングされた場合は、ロードバランサの IP アドレス。



 a| 
UUDM
 a| 
削除マーカーのUniversally Unique Identifier（汎用一意識別子）
 a| 
削除マーカーの識別子。監査ログメッセージでは、UUDMまたはUUIDのいずれかを指定します。UUDMはオブジェクトの削除要求によって作成された削除マーカー、UUIDはオブジェクトを示します。



 a| 
UUID
 a| 
Universally Unique Identifier の略
 a| 
StorageGRID システム内でのオブジェクトの識別子。



 a| 
VSID
 a| 
バージョン ID
 a| 
削除されたオブジェクトの特定のバージョンのバージョン ID 。バージョン管理に対応していないバケット内のバケットおよびオブジェクトに対する処理には、このフィールドは含まれません。

|===