---
permalink: audit/shea-s3-head.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SHEA, S3 HEAD 
summary: S3 クライアントが HEAD トランザクションを実行すると、オブジェクトまたはバケットの存在をチェックし、オブジェクトに関するメタデータを読み出す要求が送信されます。このメッセージは、トランザクションが成功した場合にサーバによって出力されます。 
---
= Shea ： S3 ヘッド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 クライアントが HEAD トランザクションを実行すると、オブジェクトまたはバケットの存在をチェックし、オブジェクトに関するメタデータを読み出す要求が送信されます。このメッセージは、トランザクションが成功した場合にサーバによって出力されます。

[cols="1a,1a,4a"]
|===
| コード | フィールド | 製品説明 


 a| 
CBID
 a| 
Content Block Identifier の略
 a| 
要求されたコンテンツブロックの一意の識別子。CBID が不明な場合、このフィールドは 0 に設定されます。バケットに対する処理では、このフィールドは指定されません。



 a| 
CNID
 a| 
接続識別子
 a| 
TCP / IP 接続の一意のシステム識別子。



 a| 
CSIZ
 a| 
コンテンツサイズ（ Content Size ）
 a| 
チェックしたオブジェクトのサイズ（バイト単位）。バケットに対する処理では、このフィールドは指定されません。



 a| 
HTRH
 a| 
HTTP 要求ヘッダー
 a| 
設定時に選択した、ログに記録される HTTP 要求ヘッダーの名前と値のリスト。

 `X-Forwarded-For`は、要求に含まれていて、値が要求の送信元IPアドレス（SAIP監査フィールド）と異なる場合に自動的に追加されます `X-Forwarded-For`。



 a| 
RSLT
 a| 
結果コード
 a| 
GETトランザクションの結果。常に次の結果になります。

SUCS ：成功しました



 a| 
S3AI
 a| 
S3 テナントアカウント ID （要求の送信者）
 a| 
要求を送信したユーザのテナントアカウント ID 。空の値は匿名アクセスであることを示します。



 a| 
S3AK
 a| 
S3 アクセスキー ID （要求の送信者）
 a| 
要求を送信したユーザのハッシュ済み S3 アクセスキー ID 。空の値は匿名アクセスであることを示します。



 a| 
S3BK
 a| 
S3 バケット
 a| 
S3 バケット名。



 a| 
S3KY
 a| 
S3 キー
 a| 
バケット名を除く S3 キーの名前。バケットに対する処理では、このフィールドは指定されません。



 a| 
SACC
 a| 
S3 テナントアカウント名（要求の送信者）
 a| 
要求を送信したユーザのテナントアカウントの名前。匿名の要求の場合は空です。



 a| 
saip
 a| 
IP アドレス（要求送信者）
 a| 
要求を送信したクライアントアプリケーションの IP アドレス。



 a| 
SBAC
 a| 
S3 テナントアカウント名（バケット所有者）
 a| 
バケット所有者のテナントアカウント名。クロスアカウントアクセスまたは匿名アクセスの識別に使用します。



 a| 
SBAI
 a| 
S3 テナントアカウント ID （バケット所有者）
 a| 
ターゲットバケットの所有者のテナントアカウント ID 。クロスアカウントアクセスまたは匿名アクセスの識別に使用します。



 a| 
サスペンション
 a| 
S3 ユーザの URN （要求の送信者）
 a| 
要求を送信しているユーザのテナントアカウント ID とユーザ名。ローカルユーザまたは LDAP ユーザです。例： `urn:sgws:identity::03393893651506583485:root`

匿名の要求の場合は空です。



 a| 
時間
 a| 
時間
 a| 
要求の合計処理時間（マイクロ秒）。



 a| 
TLIP
 a| 
信頼できるロードバランサの IP アドレス
 a| 
要求が信頼できるレイヤ 7 ロードバランサによってルーティングされた場合は、ロードバランサの IP アドレス。



 a| 
UUID
 a| 
Universally Unique Identifier の略
 a| 
StorageGRID システム内でのオブジェクトの識別子。



 a| 
VSID
 a| 
バージョン ID
 a| 
要求されたオブジェクトの特定のバージョンのバージョン ID 。バージョン管理に対応していないバケット内のバケットおよびオブジェクトに対する処理には、このフィールドは含まれません。

|===