---
permalink: audit/sput-s3-put.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SPUT, S3 PUT 
summary: S3 クライアントが PUT トランザクションを実行すると、新しいオブジェクトまたはバケットを作成する要求が送信されます。このメッセージは、トランザクションが成功した場合にサーバによって出力されます。 
---
= SPUT ： S3 PUT
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3クライアントがPUTトランザクションを実行すると、新しいオブジェクトまたはバケットを作成する要求、またはバケット/オブジェクトサブリソースを削除する要求が送信されます。このメッセージは、トランザクションが成功した場合にサーバによって出力されます。

[cols="1a,1a,4a"]
|===
| コード | フィールド | 製品説明 


 a| 
CBID
 a| 
Content Block Identifier の略
 a| 
要求されたコンテンツブロックの一意の識別子。CBID が不明な場合、このフィールドは 0 に設定されます。バケットに対する処理では、このフィールドは指定されません。



 a| 
CMP
 a| 
コンプライアンス設定
 a| 
バケットの作成時に使用された準拠設定（要求に存在する場合）（最初の1024文字に切り詰められます）。



 a| 
CNCH
 a| 
整合性制御ヘッダー
 a| 
要求に Consistency-Control HTTP 要求ヘッダーが存在する場合は、その値。



 a| 
CNID
 a| 
接続識別子
 a| 
TCP / IP 接続の一意のシステム識別子。



 a| 
CSIZ
 a| 
コンテンツサイズ（ Content Size ）
 a| 
読み出されたオブジェクトのサイズ（バイト単位）。バケットに対する処理では、このフィールドは指定されません。



 a| 
GFID
 a| 
グリッドフェデレーション接続ID
 a| 
グリッド間レプリケーションPUT要求に関連付けられたグリッドフェデレーション接続の接続ID。デスティネーショングリッドの監査ログにのみ含まれます。



 a| 
gfsaだ
 a| 
GridフェデレーションのソースアカウントID
 a| 
グリッド間レプリケーションPUT要求を行うソースグリッド上のテナントのアカウントID。デスティネーショングリッドの監査ログにのみ含まれます。



 a| 
HTRH
 a| 
HTTP 要求ヘッダー
 a| 
設定時に選択した、ログに記録される HTTP 要求ヘッダーの名前と値のリスト。

 `X-Forwarded-For`は、要求に含まれていて、値が要求の送信元IPアドレス（SAIP監査フィールド）と異なる場合に自動的に追加されます `X-Forwarded-For`。

`x-amz-bypass-governance-retention`は、要求に含まれている場合は自動的に追加されます。



 a| 
LKEN
 a| 
オブジェクトロックが有効になりました
 a| 
要求ヘッダーの値 `x-amz-bucket-object-lock-enabled`（要求に含まれている場合）。



 a| 
LKLH
 a| 
オブジェクトロックリーガルホールド
 a| 
要求ヘッダーの値 `x-amz-object-lock-legal-hold`（PutObject要求に存在する場合）。



 a| 
LKMD
 a| 
オブジェクトロック保持モード
 a| 
要求ヘッダーの値 `x-amz-object-lock-mode`（PutObject要求に存在する場合）。



 a| 
LKRU
 a| 
オブジェクトロック終了日まで保持
 a| 
要求ヘッダーの値 `x-amz-object-lock-retain-until-date`（PutObject要求に存在する場合）。値は、オブジェクトが取り込まれた日から100年以内に制限されます。



 a| 
MTME
 a| 
最終変更時刻
 a| 
オブジェクトが最後に変更された日時を示す Unix タイムスタンプ（マイクロ秒）。



 a| 
RSLT
 a| 
結果コード
 a| 
PUTトランザクションの結果。常に次の結果になります。

SUCS ：成功しました



 a| 
S3AI
 a| 
S3 テナントアカウント ID （要求の送信者）
 a| 
要求を送信したユーザのテナントアカウント ID 。空の値は匿名アクセスであることを示します。



 a| 
S3AK
 a| 
S3 アクセスキー ID （要求の送信者）
 a| 
要求を送信したユーザのハッシュ済み S3 アクセスキー ID 。空の値は匿名アクセスであることを示します。



 a| 
S3BK
 a| 
S3 バケット
 a| 
S3 バケット名。



 a| 
S3KY
 a| 
S3 キー
 a| 
バケット名を除く S3 キーの名前。バケットに対する処理では、このフィールドは指定されません。



 a| 
S3SR
 a| 
S3 サブリソース
 a| 
必要に応じて、処理対象のバケットまたはオブジェクトサブリソース。



 a| 
SACC
 a| 
S3 テナントアカウント名（要求の送信者）
 a| 
要求を送信したユーザのテナントアカウントの名前。匿名の要求の場合は空です。



 a| 
saip
 a| 
IP アドレス（要求送信者）
 a| 
要求を送信したクライアントアプリケーションの IP アドレス。



 a| 
SBAC
 a| 
S3 テナントアカウント名（バケット所有者）
 a| 
バケット所有者のテナントアカウント名。クロスアカウントアクセスまたは匿名アクセスの識別に使用します。



 a| 
SBAI
 a| 
S3 テナントアカウント ID （バケット所有者）
 a| 
ターゲットバケットの所有者のテナントアカウント ID 。クロスアカウントアクセスまたは匿名アクセスの識別に使用します。



 a| 
SRCF
 a| 
サブリソースの設定
 a| 
新しいサブリソース設定（最初の 1024 文字に切り詰められます）。



 a| 
サスペンション
 a| 
S3 ユーザの URN （要求の送信者）
 a| 
要求を送信しているユーザのテナントアカウント ID とユーザ名。ローカルユーザまたは LDAP ユーザです。例： `urn:sgws:identity::03393893651506583485:root`

匿名の要求の場合は空です。



 a| 
時間
 a| 
時間
 a| 
要求の合計処理時間（マイクロ秒）。



 a| 
TLIP
 a| 
信頼できるロードバランサの IP アドレス
 a| 
要求が信頼できるレイヤ 7 ロードバランサによってルーティングされた場合は、ロードバランサの IP アドレス。



 a| 
ULID
 a| 
ID をアップロードします
 a| 
CompleteMultipartUpload処理のSPUTメッセージにのみ含まれます。すべてのパーツがアップロードされ、アセンブルされたことを示します。



 a| 
UUID
 a| 
Universally Unique Identifier の略
 a| 
StorageGRID システム内でのオブジェクトの識別子。



 a| 
VSID
 a| 
バージョン ID
 a| 
バージョン管理されたバケットで作成された新しいオブジェクトのバージョン ID 。バージョン管理に対応していないバケット内のバケットおよびオブジェクトに対する処理には、このフィールドは含まれません。



 a| 
VSST
 a| 
バージョン管理の状態
 a| 
バケットの新しいバージョン管理状態。「enabled」または「suspended」の2つの状態が使用されます。オブジェクトに対する処理には、このフィールドは含まれません。

|===