---
permalink: audit/svrf-object-store-verify-fail.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SVRF, Object Store Verify Fail 
summary: このメッセージは、コンテンツブロックが検証プロセスに失敗したときに生成されます。レプリケートされたオブジェクトデータがディスクに対して読み書きされるたびに、要求元ユーザに送信されるデータがシステムにもともと取り込まれたデータと同一であることを確認するために複数の検証チェックと整合性チェックが実行されます。これらのチェックのいずれかが失敗した場合、破損したレプリケートオブジェクトデータは再び読み出されないように自動的に隔離されます。 
---
= SVRF ：オブジェクトストアの検証に失敗しました
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このメッセージは、コンテンツブロックが検証プロセスに失敗したときに生成されます。レプリケートされたオブジェクトデータがディスクに対して読み書きされるたびに、要求元ユーザに送信されるデータがシステムにもともと取り込まれたデータと同一であることを確認するために複数の検証チェックと整合性チェックが実行されます。これらのチェックのいずれかが失敗した場合、破損したレプリケートオブジェクトデータは再び読み出されないように自動的に隔離されます。

[cols="1a,1a,4a"]
|===
| コード | フィールド | 製品説明 


 a| 
CBID
 a| 
Content Block Identifier の略
 a| 
検証に失敗したコンテンツブロックの一意の識別子。



 a| 
RSLT
 a| 
結果コード
 a| 
検証失敗のタイプ：

CRCF ：巡回冗長検査（ CRC ）が失敗しました。

HMAC ：ハッシュベースのメッセージ認証コード（ HMAC ）チェックが失敗しました。

EHSH ：暗号化されたコンテンツハッシュが想定外です。

PHSH ：元のコンテンツハッシュが想定外です。

SEQC ：ディスク上のデータシーケンスが正しくありません。

PERR ：ディスクファイルの構造が無効です。

DERR ：ディスクエラーです。

FNAM ：ファイル名が無効です。

|===

NOTE: このメッセージは注意深く監視する必要があります。コンテンツ検証の失敗は、ハードウェア障害の兆候を示している可能性があります。

メッセージをトリガーした処理を確認するには、 AMID （ Module ID ）フィールドの値を参照してください。たとえば、 SVFY はバックグラウンド検証である Storage Verifier モジュールによってメッセージが生成されたことを示し、 STOR はコンテンツの読み出しによってメッセージがトリガーされたことを示します。
