---
permalink: audit/whea-swift-head.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, WHEA, Swift HEAD 
summary: Swift クライアントが HEAD トランザクションを実行すると、アカウント、コンテナ、またはオブジェクトの存在をチェックし、関連するメタデータを読み出す要求が送信されます。このメッセージは、トランザクションが成功した場合にサーバによって出力されます。 
---
= WHEA ： Swift ヘッド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Swift クライアントが HEAD トランザクションを実行すると、アカウント、コンテナ、またはオブジェクトの存在をチェックし、関連するメタデータを読み出す要求が送信されます。このメッセージは、トランザクションが成功した場合にサーバによって出力されます。

[cols="1a,1a,4a"]
|===
| コード | フィールド | 製品説明 


 a| 
CBID
 a| 
Content Block Identifier の略
 a| 
要求されたコンテンツブロックの一意の識別子。CBID が不明な場合、このフィールドは 0 に設定されます。アカウントおよびコンテナに関する操作には、このフィールドは含まれません。



 a| 
CSIZ
 a| 
コンテンツサイズ（ Content Size ）
 a| 
読み出されたオブジェクトのサイズ（バイト単位）。アカウントおよびコンテナに関する操作には、このフィールドは含まれません。



 a| 
HTRH
 a| 
HTTP 要求ヘッダー
 a| 
設定時に選択した、ログに記録される HTTP 要求ヘッダーの名前と値のリスト。

 `X-Forwarded-For`は、要求に含まれていて、値が要求の送信元IPアドレス（SAIP監査フィールド）と異なる場合に自動的に追加されます `X-Forwarded-For`。



 a| 
RSLT
 a| 
結果コード
 a| 
HEADトランザクションの結果。常に次の結果になります。

SUCS ：成功しました



 a| 
saip
 a| 
要求元クライアントの IP アドレス
 a| 
要求を送信したクライアントアプリケーションの IP アドレス。



 a| 
時間
 a| 
時間
 a| 
要求の合計処理時間（マイクロ秒）。



 a| 
TLIP
 a| 
信頼できるロードバランサの IP アドレス
 a| 
要求が信頼できるレイヤ 7 ロードバランサによってルーティングされた場合は、ロードバランサの IP アドレス。



 a| 
UUID
 a| 
Universally Unique Identifier の略
 a| 
StorageGRID システム内でのオブジェクトの識別子。



 a| 
WACC
 a| 
Swift アカウント ID
 a| 
StorageGRID システムによって指定された一意のアカウント ID 。



 a| 
WCON
 a| 
Swift コンテナ
 a| 
Swift コンテナ名。アカウントの操作には、このフィールドは含まれません。



 a| 
WOBJ
 a| 
Swift オブジェクト
 a| 
Swift オブジェクトの識別子。アカウントおよびコンテナに関する操作には、このフィールドは含まれません。



 a| 
WUSR
 a| 
Swift アカウントユーザ
 a| 
トランザクションを実行するクライアントを一意に識別する Swift アカウントのユーザ名。

|===