---
permalink: swnodes/automating-installation-linux.html 
sidebar: sidebar 
keywords: how to automate linux installation 
summary: StorageGRIDホスト サービスの Linux インストールとグリッド ノードの構成を自動化できます。 
---
= インストールを自動化する（Linux）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID ホストサービスのインストールおよびグリッドノードの設定を自動化することができます。

.タスクの内容

NOTE: 「Linux」は、RHEL、Ubuntu、または Debian のデプロイメントを指します。サポートされているバージョンのリストについては、 https://imt.netapp.com/matrix/#welcome["NetApp Interoperability Matrix Tool（IMT）"^] 。

導入を自動化すると、次のいずれかの場合に役立ちます。

* 物理ホストや仮想ホストの導入と設定に Ansible 、 Puppet 、 Chef などの標準のオーケストレーションフレームワークをすでに使用している場合。
* 複数の StorageGRID インスタンスを導入する場合。
* 大規模で複雑な StorageGRID インスタンスを導入する場合。


StorageGRID ホストサービスはパッケージによってインストールされ、構成ファイルによって制御されます。次のいずれかの方法で構成ファイルを作成できます。

* link:creating-node-configuration-files.html["構成ファイルを作成します"]手動インストール中に対話的に実行します。
* 構成ファイルを事前に準備し（またはプログラム化して）、この資料で説明するように、標準のオーケストレーションフレームワークを使用した自動インストールを可能にします。
+
StorageGRIDには、StorageGRIDアプライアンスとStorageGRIDシステム全体（「グリッド」）の設定を自動化するためのPythonスクリプトがオプションで用意されています。これらのスクリプトを直接使用することも、スクリプトを調べて、独自に開発したグリッド内導入ツールや設定ツールの使用方法を学ぶこともできlink:overview-of-installation-rest-api.html["StorageGRID インストール REST API"]ます。





== StorageGRID ホストサービスのインストールと設定を自動化する

StorageGRID ホストサービスのインストールは、 Ansible 、 Puppet 、 Chef 、 Fabric 、 SaltStack などの標準のオーケストレーションフレームワークを使用して自動化できます。

StorageGRIDホスト サービスは、DEB (Ubuntu または Debian) または RPM (RHEL) にパッケージ化されており、自動インストールを有効にするために事前に (またはプログラムによって) 準備できる構成ファイルによって駆動されます。すでに標準のオーケストレーション フレームワークを使用して Linux デプロイメントをインストールおよび構成している場合は、プレイブックまたはレシピにStorageGRIDを追加するのは簡単です。

ホストの準備と仮想グリッドノードの導入の手順をすべて自動化することができます。



=== サンプルの Ansible のロールとプレイブック

サンプルのAnsibleのロールとプレイブックは、インストールアーカイブのフォルダにあります `/extras`。Ansibleプレイブックは、ロールでホストを準備してStorageGRIDをターゲットサーバにインストールする方法を示しています `storagegrid`。必要に応じて、ロールまたはプレイブックをカスタマイズできます。


NOTE: サンプルのプレイブックには、 StorageGRID ホストサービスを開始する前にネットワークデバイスを作成するために必要な手順は含まれていません。これらの手順は、最終的な確認と使用の前に追加してください。

[role="tabbed-block"]
====
.RHEL
--
RHELの場合、提供されているインストールタスクは `storagegrid`役割の例を使用する `ansible.builtin.dnf`ローカル RPM ファイルまたはリモート Yum リポジトリからインストールを実行するモジュール。モジュールが利用できないかサポートされていない場合は、次のファイル内の適切なAnsibleタスクを編集して、 `yum`または `ansible.builtin.yum`モジュール:

* `roles/storagegrid/tasks/rhel_install_from_repo.yml`
* `roles/storagegrid/tasks/rhel_install_from_local.yml`


--
.Ubuntu または Debian
--
UbuntuまたはDebianの場合、提供されているインストールタスクは `storagegrid`役割の例を使用する `ansible.builtin.apt`ローカル DEB ファイルまたはリモート apt リポジトリからインストールを実行するモジュール。モジュールが利用できないかサポートされていない場合は、次のファイル内の適切なAnsibleタスクを編集して、 `ansible.builtin.apt`モジュール:

* `roles/storagegrid/tasks/deb_install_from_repo.yml`
* `roles/storagegrid/tasks/deb_install_from_local.yml`


--
====


== StorageGRID の設定を自動化

グリッドノードを導入したら、 StorageGRID システムの設定を自動化できます。

.開始する前に
* インストールアーカイブにある次のファイルの場所を確認しておきます。
+
[cols="1a,1a"]
|===
| ファイル名 | 製品説明 


| configure-storagegrid.py  a| 
設定を自動化するための Python スクリプト



| storagegrid-sample.json を設定します  a| 
スクリプトで使用する構成ファイルの例



| storagegrid-bank.json を設定する  a| 
スクリプトで使用する空の構成ファイルです

|===
* 構成ファイルを作成しておき `configure-storagegrid.json`ます。このファイルを作成するには(`configure-storagegrid.sample.json`、サンプル構成ファイル）または空の構成ファイル）(`configure-storagegrid.blank.json`を変更します。



CAUTION: 変更したファイルのパスワードセクションから管理パスワードとプロビジョニングパスフレーズを保存します。 `configure-storagegrid.json`構成ファイルを安全な場所に保管します。これらのパスワードは、インストール、拡張、およびメンテナンスの手順に必要です。変更したファイルもバックアップする必要があります `configure-storagegrid.json`構成ファイルを作成して安全な場所に保存します。

.タスクの内容
Pythonスクリプトと `configure-storagegrid.json`構成ファイルを使用して、StorageGRIDシステムの設定を自動化できます `configure-storagegrid.py`。


NOTE: また、 Grid Manager またはインストール API を使用してシステムを設定することもできます。

.手順
. Python スクリプトを実行するために使用する Linux マシンにログインします。
. インストールアーカイブを展開したディレクトリに移動します。
+
例：

+
[listing]
----
cd StorageGRID-Webscale-version/platform
----
+
 `platform`は `rpms`、または `vsphere`です `debs`。

. Python スクリプトを実行し、作成した構成ファイルを使用します。
+
例：

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.結果
設定プロセス中にリカバリパッケージ `.zip`ファイルが生成され、インストールおよび設定プロセスを実行するディレクトリにダウンロードされます。グリッドノードで障害が発生した場合に StorageGRID システムをリカバリできるようにするために、リカバリパッケージファイルをバックアップする必要があります。たとえば、バックアップされたセキュアなネットワーク上の場所や、安全なクラウドストレージ上の場所にコピーします。


CAUTION: リカバリパッケージファイルには StorageGRID システムからデータを取得するための暗号キーとパスワードが含まれているため、安全に保管する必要があります。

ランダムパスワードを生成するように指定した場合は、ファイルを開き `Passwords.txt`、StorageGRIDシステムへのアクセスに必要なパスワードを探します。

[listing]
----
######################################################################
##### The StorageGRID "Recovery Package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
StorageGRID システムがインストールおよび設定されると、確認メッセージが表示されます。

[listing]
----
StorageGRID has been configured and installed.
----