---
permalink: swnodes/how-grid-nodes-discover-primary-admin-node.html 
sidebar: sidebar 
keywords: how grid nodes discover the primary Admin Node 
summary: グリッドノードは、設定や管理のためにプライマリ管理ノードと通信します。各グリッドノードがグリッドネットワーク上のプライマリ管理ノードの IP アドレスを認識している必要があります。 
---
= グリッドノードによるプライマリ管理ノードの検出
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッドノードは、設定や管理のためにプライマリ管理ノードと通信します。各グリッドノードがグリッドネットワーク上のプライマリ管理ノードの IP アドレスを認識している必要があります。

グリッドノードからプライマリ管理ノードにアクセスできるようにするために、ノードを導入する際に次のいずれかを実行します。

* ADMIN_IP パラメータを使用して、プライマリ管理ノードの IP アドレスを手動で入力します。
* ADMIN_IP パラメータを省略して、グリッドノードで自動的に値が検出されるようにします。自動検出は、グリッドネットワークで DHCP を使用してプライマリ管理ノードに IP アドレスを割り当てる場合に特に便利です。


プライマリ管理ノードの自動検出は、マルチキャストドメインネームシステム（mDNS）を使用して実行されます。プライマリ管理ノードは、最初に起動されるときに、 mDNS を使用してそのノードの IP アドレスを公開します。同じサブネット上の他のノードは、この IP アドレスを自動的に照会して取得します。ただし、通常、マルチキャストIPトラフィックはサブネット間でルーティングできないため、他のサブネット上のノードはプライマリ管理ノードのIPアドレスを直接取得できません。

[NOTE]
====
自動検出を使用する場合：

* プライマリ管理ノードが直接接続されていないサブネットの少なくとも 1 つのグリッドノードで、 ADMIN_IP 設定を指定する必要があります。このグリッドノードがプライマリ管理ノードの IP アドレスを公開することで、サブネット上の他のノードが mDNS を使用して IP アドレスを検出できるようになります。
* ネットワークインフラがサブネット内のマルチキャスト IP トラフィックの転送をサポートしていることを確認します。


====