---
permalink: swnodes/installing-linux.html 
sidebar: sidebar 
keywords: how to install Linux 
summary: すべての Linux グリッド ホストにStorageGRIDをインストールする必要があります。サポートされているバージョンの一覧については、 NetApp相互運用性マトリックス ツールを使用してください。 
---
= Linux をインストールします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
すべての Linux グリッド ホストにStorageGRIDをインストールする必要があります。サポートされているバージョンの一覧については、 NetApp相互運用性マトリックス ツールを使用してください。

.開始する前に
お使いのオペレーティングシステムが、以下に示すStorageGRIDのカーネルバージョンの最小要件を満たしていることを確認してください。コマンドを使用し `uname -r`てオペレーティングシステムのカーネルバージョンを確認するか、OSベンダーに問い合わせてください。


NOTE: 「Linux」は、RHEL、Ubuntu、または Debian のデプロイメントを指します。サポートされているバージョンのリストについては、 https://imt.netapp.com/matrix/#welcome["NetApp Interoperability Matrix Tool（IMT）"^] 。

[role="tabbed-block"]
====
.RHEL
--
[cols="1a,2a,2a"]
|===
| RHELバージョン | 最小カーネルバージョン | カーネルパッケージ名 


 a| 
8.8（廃止）
 a| 
4.18.0～477.10.1.el8_8.x86_64
 a| 
kernel-4.18.0-477.10.1.el8_8.x86_64



 a| 
8.10
 a| 
4.18.0-553.el8_10.x86_64
 a| 
kernel-4.18.0-553.el8_10.x86_64



 a| 
9.0（廃止）
 a| 
5.14.0～70.22.1.el9_0.x86_64
 a| 
kernel-5.14.0-70.22.1.el9_0.x86_64



 a| 
9.2（廃止）
 a| 
5.14.0～284.11.1.el9_2.x86_64
 a| 
カーネル-5.14.0-284.11.1.el9_2.x86_64



 a| 
9.4
 a| 
5.14.0～427.18.1.el9_4.x86_64
 a| 
カーネル-5.14.0-427.18.1.el9_4.x86_64



 a| 
9.6
 a| 
5.14.0-570.18.1.el9_6.x86_64
 a| 
カーネル-5.14.0-570.18.1.el9_6.x86_64

|===
--
.Ubuntu
--
*注:* Ubuntuバージョン18.04および20.04のサポートは廃止され、今後のリリースで削除される予定です。

[cols="1a,2a,3a"]
|===
| Ubuntuバージョン | 最小カーネルバージョン | カーネルパッケージ名 


 a| 
22.04.1
 a| 
5.15.0-47-汎用
 a| 
linux-image-5.15.0-47-generic/jammy-updates、jammy-security、現在は5.15.0-47.51



 a| 
24.04
 a| 
6.8.0-31-汎用
 a| 
linux-image-6.8.0-31-generic/noble、現在は6.8.0-31.31

|===
--
.Debian
--
*注意:* Debianバージョン11のサポートは非推奨となり、今後のリリースで削除される予定です。

[cols="1a,2a,2a"]
|===
| Debianバージョン | 最小カーネルバージョン | カーネルパッケージ名 


 a| 
11（廃止）
 a| 
5.10.0-18-amd64
 a| 
linux-image-5.10.0-18-amd64/stable、現在は5.10.150-1



 a| 
12
 a| 
6.1.0-9-amd64
 a| 
linux-image-6.1.0-9-amd64/stable、現在は6.1.27-1

|===
--
====
.手順
. ディストリビュータの指示または標準の手順 に従って、すべての物理グリッドホストまたは仮想グリッドホストに Linux をインストールします。
+

NOTE: グラフィカルデスクトップ環境をインストールしないでください。

+
** RHEL をインストールするときに標準の Linux インストーラーを使用している場合は、「コンピューティング ノード」ソフトウェア構成 (使用可能な場合) または「最小インストール」ベース環境を選択します。
** Ubuntu をインストールするときは、*標準システムユーティリティ*を選択する必要があります。 Ubuntu ホストへの ssh アクセスを有効にするには、*OpenSSH サーバー* を選択することをお勧めします。その他のオプションはすべてオフのままにできます。


. RHEL の Extras チャネルを含むすべてのホストがパッケージ リポジトリにアクセスできることを確認します。
. スワップが有効になっている場合：
+
.. 次のコマンドを実行します。 `$ sudo swapoff --all`
.. からすべてのスワップエントリを削除し `/etc/fstab`て、設定を維持します。
+

NOTE: スワップを完全に無効にできないと、パフォーマンスが大幅に低下する可能性があります




