---
permalink: swnodes/overview-of-installation-rest-api.html 
sidebar: sidebar 
keywords: installation REST API 
summary: StorageGRID には、インストールタスクを実行するための StorageGRID インストール API が用意されています。 
---
= StorageGRID インストール REST API について学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID には、インストールタスクを実行するための StorageGRID インストール API が用意されています。

API のドキュメントは、 Swagger オープンソース API プラットフォームで提供されています。Swagger では、ユーザインターフェイスを使用してパラメータやオプションを変更した場合の API の動作を確認しながら、 API の開発を進めることができます。このドキュメントは、標準的なWebテクノロジとJSONデータ形式に精通していることを前提としています。


CAUTION: APIドキュメントWebページで実行するAPI処理はすべてライブ処理です。設定データやその他のデータを誤って作成、更新、または削除しないように注意してください。

各 REST API コマンドは、 API の URL 、 HTTP アクション、必須またはオプションの URL パラメータ、および想定される API 応答で構成されます。



[[storagegrid-installation-api]]
== StorageGRID インストール API

StorageGRID インストールAPIは、StorageGRID システムを最初に設定するとき、およびプライマリ管理ノードのリカバリを実行する必要がある場合にのみ使用できます。インストール API には、 Grid Manager から HTTPS 経由でアクセスできます。

APIドキュメントにアクセスするには、プライマリ管理ノードでインストールWebページに移動し、メニューバーから*[ヘルプ]*>*[APIドキュメント]*を選択します。

StorageGRID インストール API には次のセクションがあります。

* *config*：製品のリリースおよびAPIのバージョンに関連する操作。製品のリリースバージョンと、そのリリースでサポートされているAPIの主要バージョンを一覧表示できます。
* *grid*：グリッドレベルの設定操作。グリッドの詳細、Grid Network のサブネット、グリッドのパスワード、NTP および DNS サーバーの IP アドレスなど、グリッドの設定を取得および更新できます。
* *nodes*: ノードレベルの設定操作。グリッドノードの一覧を取得したり、グリッドノードを削除したり、グリッドノードを設定したり、グリッドノードを表示したり、グリッドノードの設定をリセットしたりできます。
* *provision*: プロビジョニング操作。プロビジョニング操作を開始し、プロビジョニング操作のステータスを確認できます。
* *リカバリ*：プライマリ管理ノードのリカバリ操作。情報のリセット、リカバリパッケージのアップロード、リカバリの開始、およびリカバリ操作のステータスの確認が可能です。
* *recovery-package*：リカバリパッケージをダウンロードするための操作。
* *サイト*：サイトレベルの設定操作。サイトの作成、表示、削除、および変更が可能です。
* *temporary-password*: インストール中に mgmt-api を保護するための一時パスワードに対する操作。

