---
permalink: upgrade/changes-to-grid-management-api.html 
sidebar: sidebar 
keywords: grid management api, api, api version, swagger, rest api, usageCacheDuration 
summary: StorageGRID 12.0 は、Grid Management API バージョン 4 を使用します。バージョン 4 ではバージョン 3 は廃止されますが、バージョン 1、2、および 3 は引き続きサポートされます。 
---
= Grid 管理 API に対する変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.0 は、Grid Management API バージョン 4 を使用します。バージョン 4 ではバージョン 3 は廃止されますが、バージョン 1、2、および 3 は引き続きサポートされます。


NOTE: StorageGRID 12.0 では管理 API の廃止バージョンを引き続き使用できますが、これらのバージョンの API のサポートはStorageGRIDの将来のリリースでは削除されます。  StorageGRID 12.0にアップグレードした後、廃止されたAPIを非アクティブ化するには、 `PUT /grid/config/management` API。

詳細については、を参照してくださいlink:../admin/using-grid-management-api.html["グリッド管理 API を使用します"]。



== ブランチバケットの新しいエンドポイント

以下のエンドポイントが追加されました。link:../tenant/what-is-branch-bucket.html["ブランチバケットを管理する"] :

`GET /org/containers/{branchBucketName}/branch`

`PUT /org/containers/{branchBucketName}/branch`



== Move ADC の新しいプライベート エンドポイント

以下のプライベートエンドポイントが追加されました。link:../maintain/move-adc-service.html["ADCサービスを移動する"]同じサイト内の 1 つのストレージ ノードから別のストレージ ノードへ:

`/private/move-adc`

`/private/move-adc/start`

`/private/move-adc/retry`



== データ専用ノードへの変換用の新しいプライベート エンドポイント

以下のプライベートエンドポイントが追加されました。link:../maintain/convert-to-data-only-node.html["1つまたは複数の結合ストレージノードを変換する"] ADC サービスを含まないノードをデータ専用ノードに移行します。

`/private/convert-to-data-only-node`

`/private/convert-to-data-only-node/start`

`/private/convert-to-data-only-node/retry`
