---
permalink: upgrade/checking-systems-condition-before-upgrading-software.html 
sidebar: sidebar 
keywords: upgrade, grid tasks, firewall, ports 
summary: StorageGRIDシステムをアップグレードする前に、システムがアップグレードに対応できる状態であることを確認します。システムが正常に動作し、すべてのグリッドノードが動作していることを確認します。 
---
= システムの状態を確認します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRIDシステムをアップグレードする前に、システムがアップグレードに対応できる状態であることを確認します。システムが正常に動作し、すべてのグリッドノードが動作していることを確認します。

.手順
. を使用してGrid Managerにサインインしlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]ます。
. アクティブなアラートがないかを確認し、ある場合は解決します。
. 競合するグリッドタスクがアクティブまたは保留中でないことを確認します。
+
.. サポート * > * ツール * > * グリッドトポロジ * を選択します。
.. _site * > * _primary Admin Node_* > * CMN * > * Grid Tasks * > * Configuration * を選択します。
+
情報ライフサイクル管理評価（ ILME ）タスクは、ソフトウェアのアップグレードと同時に実行できる唯一のグリッドタスクです。

.. 他のグリッドタスクがアクティブまたは保留中の場合は、それらが終了するまで、またはロックが解放されるまで待ちます。
+

NOTE: タスクが終了しない、またはロックが解放されない場合は、テクニカルサポートにお問い合わせください。



. アップグレード前に、およびをlink:../network/external-communications.html["外部との通信"]参照してlink:../network/internal-grid-node-communications.html["内部でのグリッドノードの通信"]、StorageGRID 11.9に必要なすべてのポートが開いていることを確認してください。
+

NOTE: StorageGRID 12.0にアップグレードする場合、追加のポートは必要ありません。


