---
permalink: upgrade/estimating-time-to-complete-upgrade.html 
sidebar: sidebar 
keywords: upgrade, time estimate, duration, cassandra upgrade 
summary: アップグレードにかかる時間に基づいて、アップグレードのタイミングを検討してください。アップグレードの各段階で実行できる処理と実行できない処理に注意してください。 
---
= アップグレードが完了するまでの推定時間
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アップグレードにかかる時間に基づいて、アップグレードのタイミングを検討してください。アップグレードの各段階で実行できる処理と実行できない処理に注意してください。

.タスクの内容
StorageGRID のアップグレード完了までに必要な時間は、クライアントの負荷やハードウェアのパフォーマンスなどのさまざまな要因によって異なります。

次の表に、アップグレードの主なタスクをまとめ、各タスクに必要なおおよその時間を示します。表に続いて、システムのアップグレード時間を見積もる手順を記載します。

[cols="1a,2a,2a,4a"]
|===
| アップグレードタスク | 製品説明 | おおよその所要時間です | このタスクの実行中です 


 a| 
事前確認を実行してプライマリ管理ノードをアップグレードする
 a| 
アップグレードの事前確認が実行され、プライマリ管理ノードが停止、アップグレード、および再起動されます。
 a| 
30分~1時間（サービスアプライアンスノードの所要時間が最も長い）

今回は未解決の事前確認エラーが増加します。
 a| 
プライマリ管理ノードにはアクセスできません。接続エラーが報告される場合がありますが、これは無視してかまいません。

アップグレードを開始する前にアップグレードの事前確認を実行すると、スケジュールされたアップグレードメンテナンス時間前にエラーを解決できます。



 a| 
アップグレードサービスを開始します
 a| 
ソフトウェアファイルが配布され、アップグレードサービスが開始されます。
 a| 
グリッドノードあたり3分
 a| 



 a| 
他のグリッドノードをアップグレードします
 a| 
他のすべてのグリッドノードのソフトウェアは、ノードを承認した順序でアップグレードされます。1つの管理ノードまたはゲートウェイノードを1つのストレージノードと同時にアップグレードします。
 a| 
ノードあたり 15~1 時間。アプライアンスノードで最も時間が必要です

*注*：アプライアンスノードの場合、StorageGRID アプライアンスインストーラは自動的に最新リリースに更新されます。
 a| 
* グリッド設定を変更しないでください。
* 監査レベルの設定は変更しないでください。
* ILM設定を更新しないでください。
* ホットフィックス、運用停止、拡張など、他のメンテナンス手順を実行することはできません。


*注*：リカバリを実行する必要がある場合は、テクニカルサポートにお問い合わせください。



 a| 
機能を有効にします
 a| 
新しいバージョンの新機能が有効になります。
 a| 
5 分未満
 a| 
* グリッド設定を変更しないでください。
* 監査レベルの設定は変更しないでください。
* ILM設定を更新しないでください。
* 別のメンテナンス手順 を実行することはできません。




 a| 
データベースをアップグレードします
 a| 
アップグレードプロセスによって各ノードがチェックされ、 Cassandra データベースの更新が不要であることが確認されます。
 a| 
ノードあたり 10 秒、またはグリッド全体で数分
 a| 
StorageGRID 11.8から11.9へのアップグレードでは、Cassandraデータベースをアップグレードする必要はありませんが、各ストレージノードでCassandraサービスが停止して再起動されます。

StorageGRID の今後の機能リリースでは、 Cassandra データベースの更新処理が完了するまでに数日かかることがあります。



 a| 
最終アップグレード手順
 a| 
一時ファイルが削除され、新しいリリースへのアップグレードが完了します。
 a| 
5分
 a| 
最後のアップグレード手順*タスクが完了したら、すべてのメンテナンス手順を実行できます。

|===
.手順
. すべてのグリッドノードをアップグレードするために必要な推定時間。
+
.. StorageGRID システムのノード数に 1 時間を掛けます。
+
原則として、アプライアンスノードのアップグレードにはソフトウェアベースのノードよりも時間がかかります。

.. この時間に、ファイルのダウンロード、事前確認検証の実行、および最終アップグレード手順の完了に必要な時間として1時間を加算します `.upgrade`。


. Linux ノードがある場合は、 RPM パッケージまたは DEB パッケージをダウンロードしてインストールするために必要な時間として、各ノードに 15 分を追加します。
. 手順 1 および 2 の結果を追加して、アップグレードの合計推定時間を計算します。




== 例：StorageGRID 11.9へのアップグレードの予測時間

システムにグリッドノードが 14 個あり、そのうち 8 個が Linux ノードであるとします。

. 14 に 1 時間を掛けます。
. ダウンロード、事前確認、および最終手順に 1 時間を足します。
+
すべてのノードのアップグレードにかかる推定時間は15時間です。

. Linux ノードに RPM パッケージまたは DEB パッケージをインストールする時間を、 8 に 15 分 / ノードを掛けます。
+
この手順の推定時間は 2 時間です。

. 値をまとめて追加します。
+
StorageGRID 11.9.0へのシステムのアップグレードが完了するまでに最大17時間かかります。




NOTE: 必要に応じて、複数のセッションでグリッドノードのサブセットを承認することで、メンテナンス時間をより短い時間に分割できます。たとえば、1つのセッションでサイトAのノードをアップグレードしてから、以降のセッションでサイトBのノードをアップグレードすることができます。アップグレードを複数のセッションで実行する場合は、すべてのノードがアップグレードされるまで新しい機能の使用を開始できないことに注意してください。
