---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: アップグレード時にStorageGRIDシステムがどのような影響を受けるかについて説明します。 
---
= アップグレード中にシステムが受ける影響
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アップグレード時にStorageGRIDシステムがどのような影響を受けるかについて説明します。



== アップグレードが完了するまで外部SSHアクセスは許可されます

アップグレード中は外部 SSH アクセスが許可されます。アップグレードが完了すると、外部 SSH アクセスはデフォルトでブロックされます。アップグレード後、*グリッドマネージャ* > *セキュリティ設定*ページにある*SSHブロック*タブを使用して、link:../admin/manage-external-ssh-access.html["外部SSHアクセスを管理する"] 。グリッド ノード間の SSH アクセスは影響を受けません。



== StorageGRIDのアップグレードは無停止

StorageGRID システムは、アップグレードプロセス中もクライアントアプリケーションからデータを取り込み、読み出すことができます。同じタイプのすべてのノード（ストレージノードなど）のアップグレードを承認すると、ノードが一度に1つずつ停止されるため、すべてのグリッドノードまたは特定のタイプのすべてのグリッドノードが使用できなくなる時間はありません。

継続的な可用性を確保するには、各オブジェクトの複数のコピーを格納するように指定するルールをILMポリシーに含めるようにしてください。また、すべての外部S3クライアントが次のいずれかに要求を送信するように設定されていることを確認する必要があります。

* ハイアベイラビリティ（HA）グループの仮想IPアドレス
* 高可用性を備えたサードパーティ製ロードバランサ
* 各クライアントに複数のゲートウェイノードが必要
* クライアントごとに複数のストレージノード




== クライアントアプリケーションが短時間中断される可能性があります

StorageGRIDシステムは、アップグレードプロセス中もクライアントアプリケーションからデータを取り込み、読み出すことができます。ただし、アップグレード中に個 々 のゲートウェイノードまたはストレージノードでサービスの再開が必要になった場合は、それらのノードへのクライアント接続が一時的に中断されることがあります。接続はアップグレードプロセスの完了後にリストアされ、個 々 のノードのサービスが再開されます。

接続の中断が短時間でも許容されない場合は、アップグレードを適用するためにダウンタイムのスケジュールが必要になることがあります。特定のノードが更新されるタイミングをスケジュールするには、選択的な承認を使用できます。


NOTE: 複数のゲートウェイとハイアベイラビリティ（HA）グループを使用して、アップグレードプロセス中の自動フェイルオーバーを実現できます。の手順を参照してくださいlink:../admin/configure-high-availability-group.html["ハイアベイラビリティグループを設定する"]。



== 混合バージョンのノードがあるグリッドではバックグラウンド修復は実行されません

グリッドに混合バージョンのノードが含まれている場合、アップグレード中にバックグラウンド修復は実行されません。サイトの停止中に発生した不整合は、アップグレードが完了するまで修復されません。



== アプライアンスファームウェアがアップグレードされている

StorageGRID 12.0 のアップグレード中:

* すべてのStorageGRIDアプライアンス ノードは、 StorageGRIDアプライアンス インストーラ ファームウェア バージョン 12.0 に自動的にアップグレードされます。
* SG6060 および SGF6024 アプライアンスは、BIOS ファームウェア バージョン 3B08.EX およびBMCファームウェア バージョン 4.01.07 に自動的にアップグレードされます。
* SG100 および SG1000 アプライアンスは、BIOS ファームウェア バージョン 3B13.EC およびBMCファームウェア バージョン 4.75.07 に自動的にアップグレードされます。
* SGF6112、SG6160、SG110、および SG1100 アプライアンスは、BIOS ファームウェア バージョン 3A14.QD およびBMCファームウェア バージョン 3.19.07 に自動的にアップグレードされます。




== ILMポリシーはステータスに応じて処理が異なります。

* アップグレード後もアクティブポリシーは変わりません。
* アップグレード時に保持されるのは、最新の10個の履歴ポリシーだけです。
* ドラフトポリシーがある場合は、アップグレード時に削除されます。




== アラートがトリガーされる可能性があります

アラートは、サービスの開始と停止、および StorageGRID システムを複数バージョンが混在した環境で使用している場合（一部のグリッドノードで以前のバージョンを実行し、その他のノードはより新しいバージョンにアップグレードしている場合）にトリガーされることがあります。アップグレードの完了後にその他のアラートがトリガーされることがあります。

たとえば、サービスが停止すると「*ノードと通信できません*」というアラートが表示されたり、一部のノードがStorageGRID 12.0 にアップグレードされたが他のノードではまだStorageGRID 11.9 が実行されている場合は「*Cassandra 通信エラー*」というアラートが表示されることがあります。通常、アップグレードが完了するとこれらのアラートは消えます。

StorageGRID 12.0 へのアップグレード中にストレージ ノードが停止すると、*ILM 配置が不可能* というアラートがトリガーされる可能性があります。このアラートは、アップグレードの完了後も 1 日間表示され続ける可能性があります。

アップグレードが完了したら、Grid Managerダッシュボードで*[最近解決されたアラート]*または*[現在のアラート]*を選択して、アップグレード関連のアラートを確認できます。



== 設定の変更は制限されています


NOTE: このリストは、 StorageGRID 11.9 からStorageGRID 12.0 へのアップグレードに特に適用されます。別のStorageGRIDリリースにアップグレードする場合は、そのリリースのアップグレード手順に記載されている制限された変更のリストを参照してください。

[ 新しい機能を有効にする *] タスクが完了するまで :

* グリッド設定を変更しないでください。
* 新しい機能を有効または無効にしないでください。
* ILM設定を更新しないでください。ILM の動作が不安定になり、正常に動作しない場合があります。
* ホットフィックスの適用やグリッドノードのリカバリは行わないでください。
+

NOTE: アップグレード中にノードのリカバリが必要な場合は、テクニカルサポートにお問い合わせください。

* StorageGRID 12.0 にアップグレードしている間は、HA グループ、VLAN インターフェイス、またはロード バランサ エンドポイントを管理しないでください。
* StorageGRID 12.0 へのアップグレードが完了するまで、HA グループを削除しないでください。他の HA グループ内の仮想 IP アドレスにアクセスできなくなる可能性があります。


[* Final Upgrade Steps * （最終アップグレード手順 * ） ] タスクが完了するまで：

* 拡張手順 を実行しないでください。
* 運用停止手順 は実行しないでください。

