---
permalink: upgrade/linux-installing-rpm-or-deb-package-on-all-hosts.html 
sidebar: sidebar 
keywords: upgrade, linux, rpm, deb, 
summary: LinuxホストにStorageGRIDノードが導入されている場合は、アップグレードを開始する前に、これらの各ホストにRPMパッケージまたはDEBパッケージを追加でインストールしてください。 
---
= Linux：すべてのホストにRPMパッケージまたはDEBパッケージをダウンロードしてインストールします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
LinuxホストにStorageGRIDノードが導入されている場合は、アップグレードを開始する前に、これらの各ホストにRPMパッケージまたはDEBパッケージを追加でダウンロードしてインストールします。



== アップグレードファイル、Linuxファイル、ホットフィックスファイルをダウンロードします

Grid ManagerからStorageGRID のアップグレードを実行すると、最初の手順として、アップグレードアーカイブと必要なホットフィックスをダウンロードするように求められます。ただし、Linuxホストをアップグレードするためにファイルをダウンロードする必要がある場合は、必要なファイルをすべて事前にダウンロードすることで時間を節約できます。

.手順
. に進みます https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetAppのダウンロード：StorageGRID"^]。
. 最新のリリースをダウンロードするボタンを選択するか、ドロップダウンメニューから別のバージョンを選択して、「 * Go * 」を選択します。
+
StorageGRID ソフトウェアのバージョンの形式は、 11._x.y_. です。StorageGRID ホットフィックスの形式は、 11._x.y.z _ です。

. ネットアップアカウントのユーザ名とパスワードを使用してサインインします。
. 「Caution/MustRead」という通知が表示された場合は、ホットフィックス番号をメモし、チェックボックスをオンにします。
. エンドユーザライセンス契約（EULA）を読み、チェックボックスをオンにして*[同意して続行]*を選択します。
+
選択したバージョンのダウンロードページが表示されます。このページには3つの列があります。

. 2列目（* Upgrade StorageGRID *）から、次の2つのファイルをダウンロードします。
+
** 最新リリースのアップグレードアーカイブ（VMware、SG1000、またはSG100プライマリ管理ノード*のセクションにあるファイル）。このファイルはアップグレードを実行するまでは必要ありませんが、今すぐダウンロードすると時間を節約できます。
** または `.zip`形式のRPMまたはDEBアーカイブ `.tgz`。サービスラップトップでWindowsを実行している場合は、ファイルを選択し `.zip`ます。
+
*** Red Hat Enterprise Linux++
`StorageGRID-Webscale-_version_-RPM-_uniqueID_.zip`
`StorageGRID-Webscale-_version_-RPM-_uniqueID_.tgz`
*** UbuntuまたはDebian++
`StorageGRID-Webscale-_version_-DEB-_uniqueID_.zip`
`StorageGRID-Webscale-_version_-DEB-_uniqueID_.tgz`




. 必要なホットフィックスが原因で「注意」/「必ずお読みください」の通知に同意する必要がある場合は、ホットフィックスをダウンロードしてください。
+
.. に戻ります https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetAppのダウンロード：StorageGRID"^]。
.. ドロップダウンからホットフィックス番号を選択します。
.. 注意事項とEULAに再度同意します。
.. ホットフィックスとそのREADMEをダウンロードして保存します。
+
アップグレードを開始すると、StorageGRID の[Upgrade]ページでホットフィックスファイルをアップロードするように求められます。







== すべてのLinuxホストにアーカイブをインストールします

StorageGRID ソフトウェアをアップグレードする前に、次の手順を実行します。

.手順
. インストールファイルから RPM パッケージまたは DEB パッケージを展開します。
. すべての Linux ホストに RPM パッケージまたは DEB パッケージをインストールします。
+
インストール手順のStorageGRID ホストサービスのインストール手順を参照してください。

+
** link:../rhel/installing-storagegrid-webscale-host-service.html["Red Hat Enterprise Linux：StorageGRIDホストサービスのインストール"]
** link:../ubuntu/installing-storagegrid-webscale-host-services.html["UbuntuまたはDebian：StorageGRID ホストサービスをインストールします"]


+
新しいパッケージは追加のパッケージとしてインストールされます。





== 以前のバージョンのインストールアーカイブを削除

Linuxホストのスペースを解放するには、不要になった以前のバージョンのStorageGRIDのインストールアーカイブを削除します。

.手順
. 古いStorageGRIDインストールアーカイブを削除します。


[role="tabbed-block"]
====
.Red Hat
--
. インストールされているStorageGRIDパッケージのリストを取得します。 `dnf list | grep -i storagegrid`
+
例：

+
[listing]
----
[root@rhel-example ~]# dnf list | grep -i storagegrid
StorageGRID-Webscale-Images-11-6-0.x86_64 11.6.0-20220210.0232.8d56cfe @System
StorageGRID-Webscale-Images-11-7-0.x86_64 11.7.0-20230424.2238.1a2cf8c @System
StorageGRID-Webscale-Images-11-8-0.x86_64 11.8.0-20240131.0139.e3e0c87 @System
StorageGRID-Webscale-Images-11-9-0.x86_64 11.9.0-20240826.1753.4aeeb70 @System
StorageGRID-Webscale-Service-11-6-0.x86_64 11.6.0-20220210.0232.8d56cfe @System
StorageGRID-Webscale-Service-11-7-0.x86_64 11.7.0-20230424.2238.1a2cf8c @System
StorageGRID-Webscale-Service-11-8-0.x86_64 11.8.0-20240131.0139.e3e0c87 @System
StorageGRID-Webscale-Service-11-9-0.x86_64 11.9.0-20240826.1753.4aeeb70 @System
[root@rhel-example ~]#
----
. 以前のStorageGRIDパッケージを削除します。 `dnf remove _images-package_ _service-package_`
+

CAUTION: 現在実行しているStorageGRIDのバージョン、またはアップグレード先のStorageGRIDのバージョンのインストールアーカイブは削除しないでください。

+
表示される警告は無視してかまいません。これらのファイルは、新しいStorageGRIDパッケージをインストールするときに置き換えられたファイルを参照します。

+
例：

+
[listing]
----
[root@rhel-example ~]# dnf remove StorageGRID-Webscale-Images-11-6-0.x86_64 StorageGRID-Webscale-Service-11-6-0.x86_64
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Dependencies resolved.
============================================================================
Package            Architecture      Version           Repository  Size
============================================================================
Removing:
StorageGRID-Webscale-Images-11-6-0 x86_64 11.6.0-20220210.0232.8d56cfe @System 2.7 G
StorageGRID-Webscale-Service-11-6-0 x86_64 11.6.0-20220210.0232.8d56cfe @System 7.5 M

Transaction Summary
============================================================================
Remove 2 Packages

Freed space: 2.8 G
Is this ok [y/N]: y
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing: 1/1
  Running scriptlet: StorageGRID-Webscale-Service-11-6-0-11.6.0-20220210.0232.8d56cfe.x86_64  1/2
  Erasing: StorageGRID-Webscale-Service-11-6-0-11.6.0-20220210.0232.8d56cfe.x86_64  1/2
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/strategy/ipv6.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/strategy/ipv4.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/strategy/eui64.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/strategy/eui48.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/strategy/__init__.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/ip/sets.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/ip/rfc1924.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/ip/nmap.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/ip/iana.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/ip/glob.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/ip/__init__.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/fbsocket.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/eui/ieee.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/eui/__init__.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/core.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/contrib/subnet_splitter.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/contrib/__init__.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/compat.pyc: remove failed: No such file or directory
warning: file /usr/lib64/python2.7/site-packages/netapp/storagegrid/vendor/latest/netaddr/__init__.pyc: remove failed: No such file or directory

  Erasing: StorageGRID-Webscale-Images-11-6-0-11.6.0-20220210.0232.8d56cfe.x86_64   2/2
  Verifying: StorageGRID-Webscale-Images-11-6-0-11.6.0-20220210.0232.8d56cfe.x86_64  1/2
  Verifying: StorageGRID-Webscale-Service-11-6-0-11.6.0-20220210.0232.8d56cfe.x86_64  2/2
Installed products updated.

Removed:
  StorageGRID-Webscale-Images-11-6-0-11.6.0-20220210.0232.8d56cfe.x86_64
  StorageGRID-Webscale-Service-11-6-0-11.6.0-20220210.0232.8d56cfe.x86_64

Complete!
[root@rhel-example ~]#
----


--
.Ubuntu と Debian
--
. インストールされているStorageGRIDパッケージのリストを取得します。 `dpkg -l | grep storagegrid`
+
例：

+
[listing]
----
root@debian-example:~# dpkg -l | grep storagegrid
ii  storagegrid-webscale-images-11-6-0  11.6.0-20220210.0232.8d56cfe amd64 StorageGRID Webscale docker images for 11.6.0
ii  storagegrid-webscale-images-11-7-0  11.7.0-20230424.2238.1a2cf8c.dev-signed amd64 StorageGRID Webscale docker images for 11.7.0
ii  storagegrid-webscale-images-11-8-0  11.8.0-20240131.0139.e3e0c87 amd64 StorageGRID Webscale docker images for 11.8.0
ii  storagegrid-webscale-images-11-9-0  11.9.0-20240826.1753.4aeeb70 amd64 StorageGRID Webscale docker images for 11.9.0
ii  storagegrid-webscale-service-11-6-0 11.6.0-20220210.0232.8d56cfe amd64 StorageGRID Webscale host services for 11.6.0
ii  storagegrid-webscale-service-11-7-0 11.7.0-20230424.2238.1a2cf8c amd64 StorageGRID Webscale host services for 11.7.0
ii  storagegrid-webscale-service-11-8-0 11.8.0-20240131.0139.e3e0c87 amd64 StorageGRID Webscale host services for 11.8.0
ii  storagegrid-webscale-service-11-9-0 11.9.0-20240826.1753.4aeeb70 amd64 StorageGRID Webscale host services for 11.9.0
root@debian-example:~#
----
. 以前のStorageGRIDパッケージを削除します。 `dpkg -r _images-package_ _service-package_`
+

CAUTION: 現在実行しているStorageGRIDのバージョン、またはアップグレード先のStorageGRIDのバージョンのインストールアーカイブは削除しないでください。

+
例：

+
[listing]
----
root@debian-example:~# dpkg -r storagegrid-webscale-service-11-6-0 storagegrid-webscale-images-11-6-0
(Reading database ... 38190 files and directories currently installed.)
Removing storagegrid-webscale-service-11-6-0 (11.6.0-20220210.0232.8d56cfe) ...
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
dpkg: warning: while removing storagegrid-webscale-service-11-6-0, directory '/usr/lib/python2.7/dist-packages/netapp/storagegrid/vendor/latest' not empty so not removed
Removing storagegrid-webscale-images-11-6-0 (11.6.0-20220210.0232.8d56cfe) ...
root@debian-example:~#
----


--
====
. StorageGRIDコンテナイメージを削除します。


[role="tabbed-block"]
====
.Docker
--
. インストールされているコンテナイメージのリストをキャプチャします。 `docker images`
+
例：

+
[listing]
----
[root@docker-example ~]# docker images
REPOSITORY           TAG            IMAGE ID       CREATED         SIZE
storagegrid-11.9.0   Admin_Node     610f2595bcb4   2 days ago      2.77GB
storagegrid-11.9.0   Storage_Node   7f73d33eb880   2 days ago      2.65GB
storagegrid-11.9.0   API_Gateway    2f0bb79526e9   2 days ago      1.82GB
storagegrid-11.8.0   Storage_Node   7125480de71b   7 months ago    2.54GB
storagegrid-11.8.0   Admin_Node     404e9f1bd173   7 months ago    2.63GB
storagegrid-11.8.0   Archive_Node   c3294a29697c   7 months ago    2.39GB
storagegrid-11.8.0   API_Gateway    1f88f24b9098   7 months ago    1.74GB
storagegrid-11.7.0   Storage_Node   1655350eff6f   16 months ago   2.51GB
storagegrid-11.7.0   Admin_Node     872258dd0dc8   16 months ago   2.48GB
storagegrid-11.7.0   Archive_Node   121e7c8b6d3b   16 months ago   2.41GB
storagegrid-11.7.0   API_Gateway    5b7a26e382de   16 months ago   1.77GB
storagegrid-11.6.0   Admin_Node     ee39f71a73e1   2 years ago     2.38GB
storagegrid-11.6.0   Storage_Node   f5ef895dcad0   2 years ago     2.08GB
storagegrid-11.6.0   Archive_Node   5782de552db0   2 years ago     1.95GB
storagegrid-11.6.0   API_Gateway    cb480ed37eea   2 years ago     1.35GB
[root@docker-example ~]#
----
. 以前のバージョンのStorageGRIDのコンテナイメージを削除します。 `docker rmi _image id_`
+

CAUTION: 現在実行しているStorageGRIDのバージョン、またはアップグレード先のStorageGRIDのバージョンのコンテナイメージは削除しないでください。

+
例：

+
[listing]
----
[root@docker-example ~]# docker rmi cb480ed37eea
Untagged: storagegrid-11.6.0:API_Gateway
Deleted: sha256:cb480ed37eea0ae9cf3522de1dadfbff0075010d89c1c0a2337a3178051ddf02
Deleted: sha256:5f269aabf15c32c1fe6f36329c304b6c6ecb563d973794b9b59e8e5ab8cccafa
Deleted: sha256:47c2b2c295a77b312b8db69db58a02d8e09e929e121352bec713fa12dae66bde
[root@docker-example ~]#
----


--
.ポドマン
--
. インストールされているコンテナイメージのリストをキャプチャします。 `podman images`
+
例：

+
[listing]
----
[root@podman-example ~]# podman images
REPOSITORY                    TAG           IMAGE ID      CREATED        SIZE
localhost/storagegrid-11.8.0  Storage_Node  7125480de71b  7 months ago   2.57 GB
localhost/storagegrid-11.8.0  Admin_Node    404e9f1bd173  7 months ago   2.67 GB
localhost/storagegrid-11.8.0  Archive_Node  c3294a29697c  7 months ago   2.42 GB
localhost/storagegrid-11.8.0  API_Gateway   1f88f24b9098  7 months ago   1.77 GB
localhost/storagegrid-11.7.0  Storage_Node  1655350eff6f  16 months ago  2.54 GB
localhost/storagegrid-11.7.0  Admin_Node    872258dd0dc8  16 months ago  2.51 GB
localhost/storagegrid-11.7.0  Archive_Node  121e7c8b6d3b  16 months ago  2.44 GB
localhost/storagegrid-11.7.0  API_Gateway   5b7a26e382de  16 months ago  1.8 GB
localhost/storagegrid-11.6.0  Admin_Node    ee39f71a73e1  2 years ago    2.42 GB
localhost/storagegrid-11.6.0  Storage_Node  f5ef895dcad0  2 years ago    2.11 GB
localhost/storagegrid-11.6.0  Archive_Node  5782de552db0  2 years ago    1.98 GB
localhost/storagegrid-11.6.0  API_Gateway   cb480ed37eea  2 years ago    1.38 GB
[root@podman-example ~]#
----
. 以前のバージョンのStorageGRIDのコンテナイメージを削除します。 `podman rmi _image id_`
+

CAUTION: 現在実行しているStorageGRIDのバージョン、またはアップグレード先のStorageGRIDのバージョンのコンテナイメージは削除しないでください。

+
例：

+
[listing]
----
[root@podman-example ~]# podman rmi f5ef895dcad0
Untagged: localhost/storagegrid-11.6.0:Storage_Node
Deleted: f5ef895dcad0d78d0fd21a07dd132d7c7f65f45d80ee7205a4d615494e44cbb7
[root@podman-example ~]#
----


--
====