---
permalink: upgrade/performing-upgrade.html 
sidebar: sidebar 
keywords: upgrade, how to perform a software upgrade 
summary: StorageGRID 11.9にアップグレードして、そのリリースの最新のホットフィックスを同時に適用することができます。StorageGRID のアップグレードページには、推奨されるアップグレードパスと、正しいダウンロードページへの直接リンクが記載されています。 
---
= アップグレードを実行する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11.9にアップグレードして、そのリリースの最新のホットフィックスを同時に適用することができます。StorageGRID のアップグレードページには、推奨されるアップグレードパスと、正しいダウンロードページへの直接リンクが記載されています。

.開始する前に
すべての考慮事項を確認し、計画と準備の手順をすべて完了しておきます。



== StorageGRID のアップグレードページにアクセスします

最初の手順として、グリッドマネージャのStorageGRID の[Upgrade]ページにアクセスします。

.手順
. を使用してGrid Managerにサインインしlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]ます。
. 「 * maintenance * > * System * > * Software update * 」を選択します。
. StorageGRID のアップグレードタイルで、*アップグレード*を選択します。




== ファイルを選択

StorageGRIDの[アップグレード]ページの更新パスには、StorageGRIDの最新リリースにアップグレードするためにインストールする必要があるメジャーバージョン（11.9.0など）とホットフィックス（11.9.0.1など）が表示されます。推奨されるバージョンとホットフィックスを記載された順序でインストールする必要があります。


TIP: 更新パスが表示されない場合は、ブラウザがNetAppサポートサイトにアクセスできないか、AutoSupportページの*[ソフトウェアの更新を確認する]*チェックボックス（* support *>* Tools *>* AutoSupport *>* Settings *）が無効になっている可能性があります。

.手順
. [ファイルの選択]ステップで、更新パスを確認します。
. [Download files]セクションで、各*[Download]*リンクを選択して、NetApp Support Site から必要なファイルをダウンロードします。
+
更新パスが表示されない場合は、に移動して https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetAppのダウンロード：StorageGRID"^]新しいバージョンまたはホットフィックスが利用可能かどうかを確認し、必要なファイルをダウンロードします。

+

NOTE: すべてのLinuxホストにRPMパッケージまたはDEBパッケージをダウンロードしてインストールする必要がある場合は、StorageGRID のアップグレードファイルとホットフィックスファイルが更新パスにすでにリストされている可能性があります。

. [参照]*を選択して、バージョンアップグレードファイルをStorageGRIDにアップロードします。 `NetApp_StorageGRID_11.9.0_Software_uniqueID.upgrade`
+
アップロードと検証の処理が完了すると、ファイル名の横に緑色のチェックマークが表示されます。

. ホットフィックスファイルをダウンロードした場合は、*[参照]*を選択してそのファイルをアップロードします。ホットフィックスはバージョンのアップグレード時に自動的に適用されます。
. 「 * Continue * 」を選択します。




== 事前確認を実行

事前確認を実行すると、グリッドのアップグレードを開始する前にアップグレードの問題を検出して解決できます。

.手順
. [Run prechecks]*ステップで、最初にグリッドのプロビジョニングパスフレーズを入力します。
. [ リカバリパッケージのダウンロード ] を選択します。
+
プライマリ管理ノードをアップグレードする前に、リカバリパッケージファイルの現在のコピーをダウンロードする必要があります。リカバリパッケージファイルは、障害が発生した場合にシステムをリストアするために使用します。

. ファイルをダウンロードしたら、ファイルを含むコンテンツにアクセスできることを確認します `Passwords.txt`。
. ダウンロードしたファイルを(`.zip`2つの安全で安全な別の場所にコピーします。
+

CAUTION: リカバリパッケージファイルには StorageGRID システムからデータを取得するための暗号キーとパスワードが含まれているため、安全に保管する必要があります。

. [事前確認を実行]*を選択し、事前確認が完了するまで待ちます。
. 報告された各事前確認の詳細を確認し、報告されたエラーを解決します。StorageGRID 11.9リリースのを参照してください https://kb.netapp.com/hybrid/StorageGRID/Maintenance/StorageGRID_11.9_software_upgrade_resolution_guide["StorageGRID ソフトウェアアップグレード解決ガイド"^]。
+
システムをアップグレードする前に、precheck_errors_をすべて解決する必要があります。ただし、アップグレード前にprecheck_warnings_に対処する必要はありません。

+

CAUTION: カスタムのファイアウォールポートが開いている場合は、事前確認の実行中に通知されます。アップグレードを続行する前に、テクニカルサポートに連絡する必要があります。

. 報告された問題を解決するために設定を変更した場合は、*[事前確認を実行]*をもう一度選択して、更新された結果を取得します。
+
すべてのエラーが解決されると、アップグレードを開始するように求められます。





== プライマリ管理ノードのアップグレードを開始し、アップグレードを開始します

アップグレードを開始すると、アップグレードの事前確認が再度実行され、プライマリ管理ノードが自動的にアップグレードされます。アップグレードのこの部分には最大30分かかることがあります。


NOTE: プライマリ管理ノードのアップグレード中は、他のGrid Managerページにはアクセスできません。監査ログも使用できなくなります。

.手順
. [アップグレードの開始]*を選択します。
+
Grid Managerに一時的にアクセスできなくなることを通知する警告が表示されます。

. [OK]*を選択して警告を確認し、アップグレードを開始します。
. アップグレードの事前確認が実行され、プライマリ管理ノードがアップグレードされるまで待ちます。
+

NOTE: 事前確認でエラーが報告された場合は、それらを解決し、*[アップグレードの開始]*をもう一度選択します。

+
オンラインで準備が完了している別の管理ノードがグリッドにある場合は、そのノードを使用してプライマリ管理ノードのステータスを監視できます。プライマリ管理ノードをアップグレードしたらすぐに、他のグリッドノードを承認できます。

. 必要に応じて*[続行]*を選択して*[他のノードのアップグレード]*ステップにアクセスします。




== 他のノードをアップグレードする

すべてのグリッドノードをアップグレードする必要がありますが、複数のアップグレードセッションを実行してアップグレードの順序をカスタマイズすることができます。たとえば、1つのセッションでサイトAのノードをアップグレードしてから、以降のセッションでサイトBのノードをアップグレードすることができます。アップグレードを複数のセッションで実行する場合は、すべてのノードがアップグレードされるまで新しい機能の使用を開始できないことに注意してください。

ノードのアップグレード順序が重要な場合は、ノードまたはノードグループを 1 つずつ承認し、各ノードでアップグレードが完了するまで待ってから、次のノードまたはノードグループを承認します。


NOTE: グリッドノードでアップグレードを開始すると、そのノードのサービスは停止します。グリッドノードはあとでリブートされます。ノードと通信しているクライアントアプリケーションのサービスの中断を回避するために、ノードを停止およびリブートする準備ができていることを確認できないかぎり、ノードのアップグレードを承認しないでください。必要に応じて、メンテナンス時間をスケジュールするか、お客様に通知します。

.手順
. [他のノードをアップグレード]*手順については、概要を確認します。概要には、アップグレード全体の開始時刻と各メジャーアップグレードタスクのステータスが表示されます。
+
** *アップグレードサービスの開始*は、最初のアップグレードタスクです。このタスクでは、ソフトウェアファイルがグリッドノードに配信され、各ノードでアップグレードサービスが開始されます。
** アップグレードサービスの開始*タスクが完了すると、*他のグリッドノードをアップグレード*タスクが開始され、リカバリパッケージの新しいコピーをダウンロードするように求められます。


. プロンプトが表示されたら、プロビジョニングパスフレーズを入力し、リカバリパッケージの新しいコピーをダウンロードします。
+

CAUTION: プライマリ管理ノードをアップグレードしたら、リカバリパッケージファイルの新しいコピーをダウンロードする必要があります。リカバリパッケージファイルは、障害が発生した場合にシステムをリストアするために使用します。

. 各タイプのノードのステータステーブルを確認します。非プライマリ管理ノード、ゲートウェイノード、ストレージノードのテーブルが用意されています。
+
グリッドノードは、テーブルが最初に表示された時点で次のいずれかの段階になります。

+
** アップグレードを開梱しています
** ダウンロード中
** 承認待ちです


. [[approval-step]]アップグレードするグリッドノードを選択する準備ができたら（または選択したノードの承認を取り消す必要がある場合）、次の手順に従います。
+
[cols="1a,1a"]
|===
| タスク | 指示 


 a| 
特定のサイトのすべてのノードなど、承認する特定のノードを検索します
 a| 
[検索]フィールドに検索文字列を入力します



 a| 
アップグレードするノードをすべて選択します
 a| 
[すべてのノードを承認]*を選択します



 a| 
アップグレードの対象として同じタイプのノードをすべて選択する（[All Storage Nodes]など）
 a| 
ノードタイプの*[すべて承認]*ボタンを選択します

同じタイプの複数のノードを承認すると、ノードは一度に 1 つずつアップグレードされます。



 a| 
アップグレードする個 々 のノードを選択します
 a| 
ノードの*[承認]*ボタンを選択します



 a| 
選択したすべてのノードでアップグレードを延期します
 a| 
[すべてのノードを承認しない]*を選択します



 a| 
同じタイプの選択したすべてのノードでアップグレードを延期します
 a| 
ノードタイプの*[すべて未承認]*ボタンを選択します



 a| 
個 々 のノードでアップグレードを延期します
 a| 
ノードの*[未承認]*ボタンを選択します

|===
. 承認されたノードが次のアップグレード段階に進むまで待ちます。
+
** 承認され、アップグレードを待機しています
** サービスを停止しています
+

NOTE: [ステージ]が*[サービスの停止中]*になっているノードを削除することはできません。[未承認]ボタンは無効になっています。

** コンテナを停止しています
** Dockerイメージをクリーンアップしています
** ベースOSパッケージをアップグレードしています
+

NOTE: アプライアンスノードがこの段階になると、アプライアンスのStorageGRID アプライアンスインストーラソフトウェアが更新されます。この自動プロセスにより、 StorageGRID アプライアンスインストーラのバージョンが StorageGRID ソフトウェアのバージョンと常に同期された状態になります。

** リブートしています
+

NOTE: 一部のアプライアンスモデルでは、ファームウェアとBIOSをアップグレードするために複数回リブートすることがあります。

** リブート後に手順を実行しています
** サービスを開始しています
** 完了


. すべてのグリッドノードがアップグレードされるまで、必要な回数だけを繰り返し<<approval-step,承認ステップ>>ます。




== アップグレードを完了する

すべてのグリッドノードのアップグレードステージが完了すると、*[他のグリッドノードをアップグレード]*タスクが[完了]と表示されます。残りのアップグレードタスクはバックグラウンドで自動的に実行されます。

.手順
. 機能の有効化*タスクが完了すると（すぐに実行されます）、アップグレード後のStorageGRIDバージョンでの使用を開始できますlink:whats-new.html["新機能"]。
. [データベースのアップグレード]タスクでは、各ノードがチェックされ、Cassandraデータベースを更新する必要がないことが確認されます。
+

NOTE: StorageGRID 11.8から11.9へのアップグレードでは、Cassandraデータベースをアップグレードする必要はありませんが、各ストレージノードでCassandraサービスが停止して再起動されます。StorageGRID の今後の機能リリースでは、 Cassandra データベースの更新処理が完了するまでに数日かかることがあります。

. データベースのアップグレード*タスクが完了したら、*最終アップグレード手順*が完了するまで数分待ちます。
. 最後のアップグレード手順*が完了すると、アップグレードが完了します。最初のステップである*ファイルの選択*が緑色の成功バナーで再表示されます。
. グリッドの動作が正常に戻っていることを確認します。
+
.. サービスが正常に動作していること、および予期しないアラートが発生していないことを確認してください。
.. StorageGRID システムへのクライアント接続が想定どおり動作していることを確認する。



