---
permalink: upgrade/troubleshooting-upgrade-issues.html 
sidebar: sidebar 
keywords: upgrade, troubleshoot, troubleshooting, errors, upgrade precheck 
summary: アップグレードの実行時に問題が発生した場合は、問題 を自分で解決できることがあります。問題 を解決できない場合は、できるだけ多くの情報を収集し、テクニカルサポートにお問い合わせください。 
---
= アップグレードの問題をトラブルシューティングする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アップグレードの実行時に問題が発生した場合は、問題 を自分で解決できることがあります。問題 を解決できない場合は、できるだけ多くの情報を収集し、テクニカルサポートにお問い合わせください。



== アップグレードが完了しない

次のセクションでは、アップグレードが部分的に失敗した場合のリカバリ方法について説明します。



=== アップグレードの事前確認エラー

問題を検出して解決するために、実際のアップグレードを開始する前にアップグレードの事前確認を手動で実行できます。事前確認で報告されるほとんどのエラーには、問題 の解決方法が表示されます。



=== プロビジョニングに失敗しました

自動プロビジョニングプロセスが失敗する場合は、テクニカルサポートにお問い合わせください。



=== グリッドノードがクラッシュするか起動しない

アップグレードプロセス中にグリッドノードがクラッシュする、またはアップグレードの終了後に正常に起動しない場合は、テクニカルサポートに調査を依頼して、根本的な問題を修正してください。



=== データの取り込みまたは読み出しが中断される

グリッドノードをアップグレードしていないときにデータの取り込みまたは読み出しが予期せず中断される場合は、テクニカルサポートにお問い合わせください。



=== データベースのアップグレードエラーです

データベースのアップグレードがエラーで失敗した場合は、アップグレードを再試行します。それでも失敗する場合は、テクニカルサポートにお問い合わせください。

.関連情報
link:checking-systems-condition-before-upgrading-software.html["ソフトウェアのアップグレード前のシステム状態の確認"]



== ユーザインターフェイスに関する問題

アップグレードの実行中または実行後に、Grid ManagerまたはTenant Managerで問題が発生する可能性があります。



=== Grid Managerのアップグレード中に複数のエラーメッセージが表示される

プライマリ管理ノードのアップグレード中にブラウザをリフレッシュしたり、別のGrid Managerページに移動したりすると、「503：Service unavailable」および「Problem connecting to the server」というメッセージが複数表示されることがあります。これらのメッセージは無視してかまいません。ノードがアップグレードされるとすぐに表示されなくなります。

アップグレードを開始してから1時間以上経過してもこれらのメッセージが表示される場合は、何らかの原因でプライマリ管理ノードをアップグレードできなかった可能性があります。問題 を自分で解決できない場合は、テクニカルサポートにお問い合わせください。



=== Web インターフェイスが想定どおりに応答しません

StorageGRID ソフトウェアのアップグレード後に Grid Manager またはテナントマネージャが想定どおりに応答しない場合がある。

Web インターフェイスで問題が発生した場合：

* を使用していることを確認しlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]ます。
+

NOTE: 通常、ブラウザサポートは StorageGRID リリースごとに変更されます。

* Web ブラウザのキャッシュをクリアします。
+
キャッシュをクリアすると、以前のバージョンの StorageGRID ソフトウェアで使用されていた古いリソースが削除され、ユーザインターフェイスが再び正しく動作するようになります。手順については、 Web ブラウザのドキュメントを参照してください。





== 「Docker image availability check」エラーメッセージ

アップグレードプロセスを開始しようとすると、「The following issues were identified by the Docker image availability check validation suite」というエラーメッセージが表示されることがあります。アップグレードを完了する前に、すべての問題を解決する必要があります。

見つかった問題の解決に必要な変更内容がわからない場合は、テクニカルサポートにお問い合わせください。

[cols="1a,1a,1a"]
|===
| メッセージ | 原因 | 解決策 


 a| 
アップグレードバージョンを特定できません。アップグレードバージョン情報ファイルが `{file_path}`想定される形式と一致しませんでした。
 a| 
アップグレードパッケージが破損しています。
 a| 
アップグレードパッケージを再度アップロードしてやり直してください。問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
アップグレードバージョン情報ファイル `{file_path}`が見つかりませんでした。アップグレードバージョンを特定できません。
 a| 
アップグレードパッケージが破損しています。
 a| 
アップグレードパッケージを再度アップロードしてやり直してください。問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
に現在インストールされているリリースバージョンを特定できません `{node_name}`。
 a| 
ノード上の重要なファイルが破損しています。
 a| 
テクニカルサポートにお問い合わせください。



 a| 
のバージョンをリストしようとしているときに接続エラーが発生しました `{node_name}`
 a| 
ノードがオフラインであるか、接続が中断されました。
 a| 
すべてのノードがオンラインで、プライマリ管理ノードからアクセスできることを確認して、操作をやり直します。



 a| 
ノードのホスト `{node_name}`にStorageGRIDイメージがロードされていませ `{upgrade_version}`ん。アップグレードを続行するには、イメージとサービスがホストにインストールされている必要があります。
 a| 
ノードを実行しているホストにアップグレード用の RPM パッケージまたは DEB パッケージがインストールされていないか、イメージのインポートがまだ終了していません。

* 注：このエラーは、 Linux でコンテナとして実行されている環境 ノードのみに該当します。
 a| 
RPM パッケージまたは DEB パッケージが、ノードが実行されているすべての Linux ホストにインストールされていることを確認します。サービスとイメージファイルの両方について、バージョンが正しいことを確認します。数分待ってから再試行してください。

を参照して link:../upgrade/linux-installing-rpm-or-deb-package-on-all-hosts.html["Linux ：すべてのホストに RPM パッケージまたは DEB パッケージをインストールします"]



 a| 
ノードチェック中のエラー `{node_name}`
 a| 
予期しないエラーが発生しました。
 a| 
数分待ってから再試行してください。



 a| 
事前確認の実行中に不明なエラーが発生しました。 `{error_string}`
 a| 
予期しないエラーが発生しました。
 a| 
数分待ってから再試行してください。

|===