---
permalink: upgrade/verifying-installed-version-of-storagegrid.html 
sidebar: sidebar 
keywords: storagegrid, version, current version, previous version 
summary: アップグレードを開始する前に、以前のバージョンのStorageGRIDに最新のホットフィックスが適用されていることを確認してください。 
---
= インストールされている StorageGRID のバージョンを確認します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アップグレードを開始する前に、以前のバージョンのStorageGRIDに最新のホットフィックスが適用されていることを確認してください。

.タスクの内容
StorageGRID 12.0 にアップグレードする前に、グリッドにStorageGRID 11.9.0.8 以降がインストールされている必要があります。現在、以前のバージョンのStorageGRIDを使用している場合は、グリッドの現在のバージョンが少なくともStorageGRID 11.9.0.8 になるまで、以前のすべてのアップグレード ファイルと最新のホットフィックスをインストールする必要があります (強く推奨)。

にアップグレードパスの1つを示します<<example-upgrade-path,例>>。


CAUTION: NetApp、次のバージョンにアップグレードする前に、各StorageGRIDバージョンに最新の修正プログラムを適用し、インストールする新しいバージョンごとに最新の修正プログラムを適用することを強くお勧めします。場合によっては、データ損失のリスクを回避するために修正プログラムを適用する必要があります。参照 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetAppのダウンロード：StorageGRID"^]詳細については、各修正プログラムのリリース ノートを参照してください。



== インストールされたバージョンを確認する

.手順
. を使用してGrid Managerにサインインしlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]ます。
. Grid Manager の上部から * ヘルプ * > * バージョン情報 * を選択します。
. *バージョン* が 11.9.0.8 以降であることを確認します。
. *バージョン*が11.9.0.8以降でない場合は、 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetAppのダウンロード：StorageGRID"^]必要なアップグレードおよび修正プログラム ファイルをダウンロードします。
. link:../upgrade/index.html["アップグレードの手順に従ってください"]ダウンロードしたリリースごとに。link:../maintain/storagegrid-hotfix-procedure.html["最新の修正プログラムを適用する"]各リリースごとに（強く推奨）。


次のアップグレード例を参照してください。



== [[example-upgrade-path]]例: StorageGRIDバージョン 11.8 から 12.0 にアップグレード

次の例は、 StorageGRID 12.0 へのアップグレードの準備として、 StorageGRIDバージョン 11.8 からバージョン 11.9 にアップグレードする手順を示しています。

次の順序でソフトウェアをダウンロードしてインストールし、システムをアップグレードする準備をします。

. StorageGRID 11.8.0メジャーリリースにアップグレードします。
. 最新のStorageGRID 11.8.0._y_hotfixを適用します。
. StorageGRID 11.9.0 メジャー リリースにアップグレードします。
. StorageGRID 11.9.0.8 以降の修正プログラムを適用します。

