---
permalink: upgrade/whats-new.html 
sidebar: sidebar 
keywords: what is new in StorageGRID 12.0 
summary: このリリースのStorageGRID では、次の機能変更が導入されています。 
---
= StorageGRID 12.0の新機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このリリースのStorageGRID では、次の機能変更が導入されています。



== S3オブジェクトロックを使用したグリッド間レプリケーション

S3オブジェクトロックが有効なバケット間のグリッド間レプリケーションを設定できます。を参照してください link:../admin/grid-federation-what-is-cross-grid-replication.html#cgr-with-ol["S3オブジェクトロックを使用したグリッド間レプリケーション"]。

NetAppでは、この機能をStorageGRID 12.0のソースバケットとデスティネーションバケットの間でのみ使用することを推奨しています。ただし、この機能は、S3オブジェクトロックが無効なStorageGRID 11.9ソースバケットと、S3オブジェクトロックが有効なStorageGRID 12.0デスティネーションバケットの間でサポートされます。



== セキュリティ



=== ディスク上の暗号化されたパスワードのセキュリティ強化

SHA512パスワードハッシュのハッシュラウンド数が大幅に増加したなど、パスワードセキュリティが向上しました。



== S3バケット



=== 分岐バケット

S3バケットを使用できるようになりましlink:../tenant/manage-branch-bucket-html["ブランチバケットの作成"]た。ブランチバケットは、特定の時点で存在していたS3バケットオブジェクトへのアクセスを提供します。ブランチバケットはバックアップと同じではありません。



== ユーザインターフェイス



=== ダークテーマ

ダークテーマとシステムテーマの設定は、Grid ManagerとTenant Managerの[User]メニューで使用できます。



== Grid Managerの機能拡張



=== リージョンの機能拡張の設定

Grid Managerの[Regions]ページに*[Default region]*タブが追加されました。このタブを使用して、S3バケットに定義されているデフォルトのリージョンを変更できます。link:../ilm/configuring-regions-optional-and-s3-only.html["詳細"]です。
