---
permalink: ubuntu/cpu-and-ram-requirements.html 
sidebar: sidebar 
keywords: cpu, ram, cpu cores 
summary: StorageGRID ソフトウェアをインストールする前に、ハードウェアの確認と設定を行って、 StorageGRID システムをサポートできる状態にしておきます。 
---
= CPUオヨビRAMノヨウケン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID ソフトウェアをインストールする前に、ハードウェアの確認と設定を行って、 StorageGRID システムをサポートできる状態にしておきます。

各 StorageGRID ノードに必要な最小リソースは次のとおりです。

* CPU コア：ノードあたり 8 個
* RAM：使用可能なRAMの合計容量と、システムで実行されているStorageGRID以外のソフトウェアの容量によって異なります。
+
** 通常、ノードあたり24GB以上、システムRAMの合計より2~16GB少ない
** 約5、000個のバケットを格納するテナントごとに64GB以上




ソフトウェアベースのメタデータのみのノードリソースは、既存のストレージノードリソースと一致している必要があります。例：

* 既存のStorageGRIDサイトでSG6000またはSG6100アプライアンスを使用している場合は、ソフトウェアベースのメタデータのみのノードが次の最小要件を満たしている必要があります。
+
** 128GBのRAM
** 8コアCPU
** 8TB SSDまたはCassandraデータベース用同等のストレージ（rangedb/0）


* 既存のStorageGRIDサイトで、24GBのRAM、8コアCPU、3TBまたは4TBのメタデータストレージを搭載した仮想ストレージノードを使用している場合は、ソフトウェアベースのメタデータ専用ノードで同様のリソース（24GBのRAM、8コアCPU、4TBのメタデータストレージ（rangedb/0）を使用する必要があります。


新しいStorageGRIDサイトを追加するときは、新しいサイトの総メタデータ容量が少なくとも既存のStorageGRIDサイトと一致し、新しいサイトのリソースが既存のStorageGRIDサイトのストレージノードと一致している必要があります。

それぞれの物理ホストまたは仮想ホストで実行する StorageGRID ノードの数が、利用可能な CPU コアや物理 RAM を超えないようにしてください。ホストがStorageGRID 専用でない場合（非推奨）は、他のアプリケーションのリソース要件を考慮してください。


CAUTION: CPU とメモリの使用状況を定期的に監視して、ワークロードに継続的に対応できるようにします。たとえば、仮想ストレージノードの RAM 割り当てと CPU 割り当てを 2 倍にすると、 StorageGRID アプライアンスノードの場合と同様のリソースが提供されます。また、ノードあたりのメタデータの量が 500GB を超える場合は、ノードあたりの RAM を 48GB 以上に増やすことを検討してください。オブジェクトメタデータストレージの管理、Metadata Reserved Space設定の拡張、およびCPUとメモリの使用状況の監視についてはlink:../admin/index.html["管理"]、、link:../monitor/index.html["監視"]およびlink:../upgrade/index.html["アップグレード"]StorageGRIDの手順を参照してください。

基盤となる物理ホストでハイパースレッディングが有効である場合は、ノードあたり 8 個の仮想コア（ 4 個の物理コア）で構成できます。基盤となる物理ホストでハイパースレッディングが有効でない場合は、ノードあたり 8 個の物理コアを用意する必要があります。

仮想マシンをホストとして使用する場合、 VM のサイズと数を制御可能であれば、 StorageGRID ノードごとに 1 つの VM を使用し、それに応じて VM のサイズを設定する必要があります。

本番環境では、複数のストレージノードを同じ物理ストレージハードウェアまたは仮想ホストで実行しないでください。単一の StorageGRID 環境の各ストレージノードをそれぞれ独自の分離された障害ドメインに配置するようにします。単一のハードウェア障害が単一のストレージノードにしか影響しないようにすることで、オブジェクトデータの耐久性と可用性を最大限に高めることができます。

も参照してくださいlink:storage-and-performance-requirements.html["ストレージとパフォーマンスの要件"]。
