---
permalink: ubuntu/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: how to download ubuntu or debian installation files 
summary: StorageGRID インストールアーカイブをダウンロードし、必要なファイルを展開する必要があります。必要に応じて、インストールパッケージ内のファイルを手動で検証できます。 
---
= StorageGRID インストールファイルをダウンロードして展開します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID インストールアーカイブをダウンロードし、必要なファイルを展開する必要があります。必要に応じて、インストールパッケージ内のファイルを手動で検証できます。

.手順
. に進みます https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["ネットアップの StorageGRID ダウンロードページ"^]。
. 最新のリリースをダウンロードするボタンを選択するか、ドロップダウンメニューから別のバージョンを選択して、「 * Go * 」を選択します。
. ネットアップアカウントのユーザ名とパスワードを使用してサインインします。
. Caution/MustRead文が表示された場合は'その文を読み'チェックボックスをオンにします
+

CAUTION: StorageGRID リリースのインストール後に、必要な修正プログラムを適用する必要があります。詳細については、link:../maintain/storagegrid-hotfix-procedure.html["リカバリとメンテナンスの手順の Hotfix 手順"]

. [End User License Agreement]を読み、チェックボックスをオンにして、*[Accept & Continue]*を選択します。
. [Install StorageGRID *]列で、UbuntuまたはDebianの.tgzまたは.zipインストールアーカイブを選択します。
+

NOTE: サービスラップトップでWindowsを実行している場合は、ファイルを選択し `.zip`ます。

. インストールアーカイブを保存します。
. [[ubuntu-download-verification-package]]インストールアーカイブを検証する必要がある場合は、次の手順を実行します。
+
.. StorageGRIDコード署名検証パッケージをダウンロードします。このパッケージのファイル名はの形式を使用し `StorageGRID_<version-number>_Code_Signature_Verification_Package.tar.gz`ます。 `<version-number>`はStorageGRIDソフトウェアのバージョンです。
.. 手順~を実行しlink:../ubuntu/download-files-verify.html["インストールファイルを手動で検証する"]ます。


. インストールアーカイブからファイルを展開します。
. 必要なファイルを選択します。
+
必要なファイルは、計画したグリッドトポロジおよびStorageGRIDシステムの導入方法によって異なります。

+

NOTE: 次の表に示すパスは、展開されたインストールアーカイブによってインストールされた最上位ディレクトリに対する相対パスです。



[cols="1a,1a"]
|===
| パスとファイル名 | 製品説明 


| ./debs/README  a| 
StorageGRID ダウンロードファイルに含まれているすべてのファイルについて説明するテキストファイル。



| ./debs/NLF000000.txt  a| 
テスト環境やコンセプトの実証環境に使用できる、非本番環境のNetAppライセンスファイル。



| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
Ubuntu ホストまたは Debian ホストに StorageGRID ノードイメージをインストールするための DEB パッケージ。



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
ファイルのMD5チェックサム `/debs/storagegrid-webscale-images-version-SHA.deb`。



| ./debs/storagegrid-webscale-service-version-SHA.deb  a| 
Ubuntu ホストまたは Debian ホストに StorageGRID ホストサービスをインストールするための DEB パッケージ。



| 導入スクリプトツール | 製品説明 


| ./debs/configure-storagegrid.py  a| 
StorageGRID システムの設定を自動化するための Python スクリプト。



| ./debs/configure-sga.py  a| 
StorageGRID アプライアンスの設定を自動化するための Python スクリプト。



| ./debs/storagegrid-ssoauth.py  a| 
シングルサインオンが有効な場合にグリッド管理 API にサインインするために使用できる Python スクリプトの例。このスクリプトは、Pingフェデレーション統合にも使用できます。



| ./debs/configure -storagegrid-sample.json という形式で指定します  a| 
スクリプトで使用する構成ファイルの例 `configure-storagegrid.py`。



| ./debs/configure -storagegrid-bank.json という形式で実行します  a| 
スクリプトで使用する空の構成ファイル `configure-storagegrid.py`。



| ./debs/extras /Ansible を実行します  a| 
StorageGRID コンテナ導入用の Ubuntu ホストまたは Debian ホストを設定するためのサンプルの Ansible のロールとプレイブック。必要に応じて、ロールまたはプレイブックをカスタマイズできます。



| ./debs/ storagegrid-ssoauth-azure.py  a| 
Active DirectoryまたはPingフェデレーションを使用してシングルサインオン（SSO）が有効になっている場合にグリッド管理APIにサインインするために使用できるPythonスクリプトの例。



| ./debs/storagegrid-ssoauth-azure.js  a| 
関連するPythonスクリプトによって呼び出され、AzureとのSSO対話を実行するヘルパースクリプト `storagegrid-ssoauth-azure.py`。



| ./debs/extra/api-schemas  a| 
StorageGRID の API スキーマ

*注*：アップグレードを実行する前に、これらのスキーマを使用して、アップグレード互換性テスト用の非本番環境のStorageGRID 環境がない場合、StorageGRID 管理APIを使用するように記述したコードが新しいStorageGRID リリースと互換性があることを確認できます。

|===