---
permalink: ubuntu/installing-storagegrid-webscale-host-services.html 
sidebar: sidebar 
keywords: how to install StorageGRID host services 
summary: StorageGRID ホストサービスをインストールするには、 StorageGRID DEB パッケージを使用します。 
---
= StorageGRID ホストサービスをインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID ホストサービスをインストールするには、 StorageGRID DEB パッケージを使用します。

.タスクの内容
以下の手順では、 DEB パッケージからホストサービスをインストールする方法について説明します。また、インストールアーカイブに含まれている APT リポジトリメタデータを使用して、 DEB パッケージをリモートでインストールすることもできます。使用している Linux オペレーティングシステムの APT リポジトリに関する手順を参照してください。

.手順
. 各ホストに StorageGRID DEB パッケージをコピーするか、共有ストレージに置きます。
+
たとえば、次の手順のコマンド例を使用できるように、これらのコマンドをディレクトリに配置し `/tmp`ます。

. 各ホストに root アカウントまたは sudo 権限を持つアカウントでログインし、次のコマンドを実行します。
+
最初にパッケージをインストールし、 `service`次にパッケージをインストールする必要があり `images`ます。パッケージを以外のディレクトリに配置した `/tmp`場合は、使用したパスを反映するようにコマンドを変更します。

+
[listing]
----
sudo dpkg --install /tmp/storagegrid-webscale-images-version-SHA.deb
----
+
[listing]
----
sudo dpkg --install /tmp/storagegrid-webscale-service-version-SHA.deb
----
+

NOTE: StorageGRID パッケージをインストールするには、 Python 2.7 がインストールされている必要があります。 `sudo dpkg --install /tmp/storagegrid-webscale-images-version-SHA.deb`完了するまでコマンドは失敗します。


