---
permalink: ubuntu/required-materials.html 
sidebar: sidebar 
keywords: installation materials ubuntu debian 
summary: StorageGRIDをインストールする前に、必要な情報や資料を収集して準備します。 
---
= 必要な情報と資料
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRIDをインストールする前に、必要な情報や資料を収集して準備します。



== 必要な情報

ネットワーク計画:: 各StorageGRIDノードに接続するネットワーク。StorageGRIDは、トラフィックの分離、セキュリティ、および管理上の利便性のために、複数のネットワークをサポートしています。
+
--
StorageGRIDを参照してくださいlink:../network/index.html["ネットワークのガイドライン"]。

--
ネットワーク情報:: 各グリッドノードに割り当てるIPアドレス、およびDNSサーバとNTPサーバのIPアドレス。
グリッドノードヨウノサーバ:: 導入予定の StorageGRID ノードの数とタイプに応じて、それらをサポートできる十分なリソースを備えた一連のサーバ（物理、仮想、またはその両方）を特定します。
+
--

NOTE: StorageGRID 環境でStorageGRID アプライアンス（ハードウェア）ストレージノードを使用しない場合は、バッテリバックアップ式書き込みキャッシュ（BBWC）を備えたハードウェアRAIDストレージを使用する必要があります。StorageGRID は、Virtual Storage Area Network（VSAN;仮想ストレージエリアネットワーク）、ソフトウェアRAID、またはRAID保護なしの使用をサポートしていません。

--
ノード移行（必要な場合）:: link:node-container-migration-requirements.html["ノード移行の要件"]物理ホストでサービスを中断せずに定期的なメンテナンスを実行する場合は、を参照してください。
関連情報:: https://imt.netapp.com/matrix/#welcome["NetApp Interoperability Matrix Tool"^]




== 前提要件

NetApp StorageGRID ライセンス:: デジタル署名された有効なNetAppライセンスが必要です。



NOTE: StorageGRIDのインストールアーカイブには、グリッドのテストとコンセプトの実証に使用できる非本番環境のライセンスが含まれています。

StorageGRID インストールアーカイブ:: link:downloading-and-extracting-storagegrid-installation-files.html["StorageGRIDインストールアーカイブをダウンロードしてファイルを展開する"]です。
サービスラップトップ:: StorageGRID システムは、サービスラップトップを介してインストールされます。
+
--
サービスラップトップには次のものが必要です。

* ネットワークポート
* SSH クライアント（ PuTTY など）
* link:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]


--
StorageGRID のドキュメント::
+
--
* link:../release-notes/index.html["リリースノート"]
* link:../admin/index.html["StorageGRID の管理手順"]


--

