---
permalink: ubuntu/software-requirements.html 
sidebar: sidebar 
keywords: software requirements 
summary: 仮想マシンを使用して、あらゆるタイプのStorageGRIDノードをホストできます。グリッドノードごとに仮想マシンが1つ必要です。 
---
= UbuntuおよびDebianのソフトウェア要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
仮想マシンを使用して、あらゆるタイプのStorageGRIDノードをホストできます。グリッドノードごとに仮想マシンが1つ必要です。

UbuntuまたはDebianにStorageGRIDをインストールするには、サードパーティのソフトウェアパッケージをインストールする必要があります。一部のサポートされているLinuxディストリビューションには、デフォルトでこれらのパッケージが含まれていません。StorageGRIDのインストールがテストされているソフトウェアパッケージのバージョンには、このページに記載されているバージョンも含まれます。

これらのパッケージのいずれかを必要とするLinuxディストリビューションおよびコンテナランタイムインストールオプションを選択し、それらがLinuxディストリビューションによって自動的にインストールされない場合は、プロバイダまたはLinuxディストリビューションのサポートベンダーから入手可能な場合は、ここに記載されているいずれかのバージョンをインストールします。それ以外の場合は、ベンダーが提供しているデフォルトのパッケージバージョンを使用します。

すべてのインストールオプションには、PodmanまたはDockerのいずれかが必要です。両方のパッケージをインストールしないでください。インストールオプションに必要なパッケージのみをインストールします。


NOTE: ソフトウェアのみの環境のコンテナエンジンとしてのDockerのサポートは廃止されました。Dockerは、今後のリリースで別のコンテナエンジンに置き換えられる予定です。



== テスト対象のPythonバージョン

* 3.5.2-2
* 3.6.8-2
* 3.6.8-38
* 3.6.9-1
* 3.7.3-1
* 3.8.10-0
* 3.9.2-1
* 3.9.10-2
* 3.9.16-1
* 3.10.6-1
* 3.11.2-6




== テスト済みのPodmanバージョン

* 3.2.3-0
* 3.4.4 + DS1
* 4.1.1-7
* 4.2.0-11
* 4.3.1 + DS1-8 + B1
* 4.4.1-8
* 4.4.1-12




== テスト済みのDockerバージョン


IMPORTANT: Dockerのサポートは廃止され、今後のリリースで削除される予定です。

* Docker - CE 20.10.7
* Docker - CE 20.10.20-3
* Docker - CE 23.0.6-1
* Docker - CE 24.0.2-1
* Docker - CE 24.0.4-1
* Docker - CE 24.0.5-1
* Docker - CE 24.0.7-1
* 1.5-2

