---
permalink: harden/index.html 
sidebar: sidebar 
keywords: StorageGRID, hardening guidelines, system, security 
summary: システムのセキュリティ強化とは、 StorageGRID システムからできるだけ多くのセキュリティリスクを排除するプロセスです。 
---
= StorageGRID のシステム強化について学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
システムのセキュリティ強化とは、 StorageGRID システムからできるだけ多くのセキュリティリスクを排除するプロセスです。

StorageGRIDをインストールして設定する際には、機密性、整合性、可用性に関する所定のセキュリティ目標を達成するために、これらのガイドラインを使用してください。

システム強化については、すでに業界標準のベスト プラクティスを使用しているはずです。たとえば、 StorageGRIDには強力なパスワードを使用し、HTTP ではなく HTTPS を使用し、可能な場合は証明書ベースの認証を有効にします。これらのベスト プラクティスには、物理​​的なアクセスを制限するとともに、物理的なデータ センターとサポート インフラストラクチャを保護する物理的および環境的なセキュリティが含まれている必要があります。また、事業および地域に適用される規制基準および推奨事項も参照する必要があります。

StorageGRIDはに準拠してい https://security.netapp.com/policy/["NetApp Vulnerability Handling Policyの略"^]ます。報告された脆弱性は、製品セキュリティインシデント対応プロセスに従って検証および解決されます。

StorageGRIDシステムのセキュリティを強化する場合は、次の点を考慮してください。

* * 3つのStorageGRIDネットワークのうち、実装したネットワークはどれですか*。すべての StorageGRID システムでグリッドネットワークを使用する必要がありますが、管理ネットワーク、クライアントネットワーク、またはその両方を使用することもできます。ネットワークごとにセキュリティに関する考慮事項が異なります。
* * StorageGRIDシステムの個 々 のノードに使用するプラットフォームのタイプ*。StorageGRID ノードは、 VMware 仮想マシン、 Linux ホスト上のコンテナエンジン、または専用のハードウェアアプライアンスとして導入できます。プラットフォームのタイプごとに、強化に関するベストプラクティスがあります。
* *テナントアカウントの信頼度*。テナントアカウントを信頼しないサービスプロバイダである場合は、信頼できる社内テナントのみを使用した場合とはセキュリティ上の問題が異なります。
* *セキュリティ要件と規則*組織は次のとおりです。特定の規制や企業の要件に準拠しなければならない場合があります。

