---
permalink: network/external-communications.html 
sidebar: sidebar 
keywords: storagegrid, network port, external communications, ports, TCP, UDP, client communications 
summary: クライアントは、コンテンツの取り込みと読み出しを行うためにグリッドノードと通信する必要があります。使用するポートは、選択したオブジェクトストレージプロトコルによって異なります。これらのポートはクライアントからアクセスできる必要があります。 
---
= 外部との通信
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クライアントは、コンテンツの取り込みと読み出しを行うためにグリッドノードと通信する必要があります。使用するポートは、選択したオブジェクトストレージプロトコルによって異なります。これらのポートはクライアントからアクセスできる必要があります。



== ポートへのアクセスを制限します

エンタープライズネットワークポリシーによっていずれかのポートへのアクセスが制限されている場合は、次のいずれかを実行できます。

* ユーザ定義ポートでのアクセスを許可する場合に使用しlink:../admin/configuring-load-balancer-endpoints.html["ロードバランサエンドポイント"]ます。
* ノード導入時にポートを再マッピングします。ただし、ロードバランサエンドポイントを再マッピングしないでください。StorageGRIDノードのポートの再マッピングに関する情報を参照してください。
+
** link:../rhel/creating-node-configuration-files.html#port-remap-keys["Red Hat Enterprise LinuxでのStorageGRIDのポート再マッピングキー"]
** link:../ubuntu/creating-node-configuration-files.html#port-remap-keys["UbuntuまたはDebianでのStorageGRIDのポート再マッピングキー"]
** link:../vmware/deploying-storagegrid-node-as-virtual-machine.html#vmware-remap-ports["VMwareテノStorageGRIDノホオトノサイマツヒンク"]
** https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/optional-remapping-network-ports-for-appliance.html["オプション：アプライアンスのネットワークポートの再マッピング"^]






== 外部との通信に使用するポート

次の表に、ノードに着信するトラフィックに使用されるポートを示します。


NOTE: このリストには、として設定されている可能性のあるポートは含まれませlink:../admin/configuring-load-balancer-endpoints.html["ロードバランサエンドポイント"]ん。

[cols="1a,1a,1a,1a,1a,4a"]
|===
| ポート | tcp または udp です | プロトコル | 開始 | 宛先 | 詳細 


 a| 
22
 a| 
TCP
 a| 
SSH
 a| 
サービスラップトップ
 a| 
すべてのノード
 a| 
コンソールの手順を実行するには、 SSH アクセスまたはコンソールアクセスが必要です。必要に応じて、 22 の代わりにポート 2022 を使用できます。



 a| 
25
 a| 
TCP
 a| 
SMTP
 a| 
管理ノード
 a| 
E メールサーバ
 a| 
アラートおよび E メールベースの AutoSupport に使用されます。Email Servers ページを使用して、デフォルトのポート設定である 25 を上書きできます。



 a| 
53
 a| 
TCP / UDP
 a| 
DNS
 a| 
すべてのノード
 a| 
DNSサーバ
 a| 
DNSに使用されます。



 a| 
67
 a| 
UDP
 a| 
DHCP
 a| 
すべてのノード
 a| 
DHCPサービス
 a| 
必要に応じて、 DHCP ベースのネットワーク設定のサポートに使用します。dhclient サービスは、静的に設定されたグリッドに対しては実行されません。



 a| 
68
 a| 
UDP
 a| 
DHCP
 a| 
DHCPサービス
 a| 
すべてのノード
 a| 
必要に応じて、 DHCP ベースのネットワーク設定のサポートに使用します。dhclient サービスは、静的 IP アドレスを使用するグリッドに対しては実行されません。



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
ブラウザ
 a| 
管理ノード
 a| 
ポート 80 は、管理ノードのユーザインターフェイス用のポート 443 にリダイレクトされます。



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
ブラウザ
 a| 
アプライアンス
 a| 
ポート 80 は、 StorageGRID アプライアンスインストーラ用のポート 8443 にリダイレクトされます。



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
ADC を採用するストレージノード
 a| 
AWS
 a| 
AWSまたはHTTPを使用するその他の外部サービスに送信されるプラットフォームサービスメッセージに使用されます。エンドポイントの作成時に、テナントがデフォルトの HTTP ポート設定である 80 を上書きできる。



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
ストレージノード
 a| 
AWS
 a| 
HTTPを使用するAWSターゲットに送信されるCloud Storage Pools要求。クラウドストレージプールの設定時に、グリッド管理者がデフォルトの HTTP ポート設定である 80 を上書きできます。



 a| 
123
 a| 
UDP
 a| 
NTP
 a| 
プライマリ NTP ノード
 a| 
外部 NTP
 a| 
ネットワークタイムプロトコルサービス。プライマリ NTP ソースとして選択されたノードは、クロックの時間と外部 NTP の時間ソースとの同期も行います。



 a| 
161
 a| 
TCP / UDP
 a| 
SNMP
 a| 
SNMPクライアント
 a| 
すべてのノード
 a| 
SNMP ポーリングに使用します。すべてのノードは基本情報を提供し、管理ノードもアラートデータを提供します。設定時のデフォルトの UDP ポートは 161 です。

* 注：このポートは必須です。 SNMP が設定されている場合にのみノードファイアウォールで開かれます。SNMP を使用する場合は、代替ポートを設定できます。

* 注： StorageGRID での SNMP の使用については、ネットアップの営業担当者にお問い合わせください。



 a| 
162
 a| 
TCP / UDP
 a| 
SNMP 通知
 a| 
すべてのノード
 a| 
通知の送信先
 a| 
アウトバウンド SNMP 通知およびトラップのデフォルトの UDP ポートは 162 です。

* 注：このポートは、 SNMP が有効で通知の送信先が設定されている場合にのみ必要です。SNMP を使用する場合は、代替ポートを設定できます。

* 注： StorageGRID での SNMP の使用については、ネットアップの営業担当者にお問い合わせください。



 a| 
389
 a| 
TCP / UDP
 a| 
LDAP
 a| 
ADC を採用するストレージノード
 a| 
Active Directory / LDAP
 a| 
アイデンティティフェデレーション用の Active Directory または LDAP サーバに接続するために使用します。



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
ブラウザ
 a| 
管理ノード
 a| 
Grid Manager と Tenant Manager にアクセスするために Web ブラウザと管理 API クライアントで使用します。

*注*：Grid Managerポート443または8443を閉じると、ブロックされたポートに現在接続しているユーザ（ユーザを含む）は、ユーザのIPアドレスが特権アドレスリストに追加されていないかぎりGrid Managerにアクセスできなくなります。特権IPアドレスを設定するには、を参照してくださいlink:../admin/configure-firewall-controls.html["ファイアウォールコントロールを設定します"]。



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
管理ノード
 a| 
Active Directory
 a| 
シングルサインオン（ SSO ）が有効な場合に、 Active Directory に接続する管理ノードで使用します。



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
ADC を採用するストレージノード
 a| 
AWS
 a| 
AWSまたはHTTPSを使用するその他の外部サービスに送信されるプラットフォームサービスメッセージに使用されます。エンドポイントの作成時に、テナントがデフォルトの HTTP ポート設定である 443 を上書きできる。



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
ストレージノード
 a| 
AWS
 a| 
HTTPSを使用するAWSターゲットに送信されるCloud Storage Pools要求。クラウドストレージプールの設定時に、グリッド管理者がデフォルトの HTTPS ポート設定である 443 を上書きできます。



 a| 
2022
 a| 
TCP
 a| 
SSH
 a| 
サービスラップトップ
 a| 
すべてのノード
 a| 
コンソールの手順を実行するには、 SSH アクセスまたはコンソールアクセスが必要です。必要に応じて、 2022 の代わりにポート 22 を使用できます。



 a| 
5353
 a| 
UDP
 a| 
mDNS
 a| 
すべてのノード
 a| 
すべてのノード
 a| 
フルグリッドIPの変更、およびインストール、拡張、リカバリ時のプライマリ管理ノードの検出に使用するマルチキャストDNS（mDNS）サービスを提供します。



 a| 
5696
 a| 
TCP
 a| 
KMIP
 a| 
アプライアンス
 a| 
KMS
 a| 
ノードの暗号化用に設定されたアプライアンスから Key Management Server （ KMS ）へのキー管理 Interoperability Protocol （ KMIP ）の外部トラフィック（ StorageGRID アプライアンスインストーラの KMS 構成のページで別のポートを指定している場合を除く）。



 a| 
8022
 a| 
TCP
 a| 
SSH
 a| 
サービスラップトップ
 a| 
すべてのノード
 a| 
ポート 8022 で SSH を使用すると、サポートとトラブルシューティング用に、アプライアンスと仮想ノードプラットフォーム上のベースのオペレーティングシステムへのアクセスが許可されます。このポートは Linux ベース（ベアメタル）ノードには使用されず、グリッドノード間または通常運用時にアクセス可能である必要はありません。



 a| 
8443
 a| 
TCP
 a| 
HTTPS
 a| 
ブラウザ
 a| 
管理ノード
 a| 
オプション。Grid Manager にアクセスするために Web ブラウザと管理 API クライアントで使用されます。を使用して、 Grid Manager と Tenant Manager の通信を分離できます。

*注*：Grid Managerポート443または8443を閉じると、ブロックされたポートに現在接続しているユーザ（ユーザを含む）は、ユーザのIPアドレスが特権アドレスリストに追加されていないかぎりGrid Managerにアクセスできなくなります。特権IPアドレスを設定するには、を参照してくださいlink:../admin/configure-firewall-controls.html["ファイアウォールコントロールを設定します"]。



 a| 
9022
 a| 
TCP
 a| 
SSH
 a| 
サービスラップトップ
 a| 
アプライアンス
 a| 
サポートとトラブルシューティングのために、構成前モードでの StorageGRID アプライアンスへのアクセスを許可します。このポートは、グリッドノード間で、または通常運用時にアクセス可能である必要はありません。



 a| 
9091
 a| 
TCP
 a| 
HTTPS
 a| 
外部の Grafana サービス
 a| 
管理ノード
 a| 
外部の Grafana サービスが StorageGRID Prometheus サービスへのセキュアなアクセスに使用します。

* 注：このポートは、証明書ベースの Prometheus アクセスが有効になっている場合にのみ必要です。



 a| 
9092
 a| 
TCP
 a| 
カフカ
 a| 
ADC を採用するストレージノード
 a| 
Kafkaクラスタ
 a| 
Kafkaクラスタに送信されるプラットフォームサービスメッセージに使用されます。テナントは、エンドポイントの作成時にデフォルトのKafkaポート設定（9092）を上書きできます。



 a| 
9443
 a| 
TCP
 a| 
HTTPS
 a| 
ブラウザ
 a| 
管理ノード
 a| 
オプション。Tenant Manager にアクセスするために Web ブラウザと管理 API クライアントで使用します。を使用して、 Grid Manager と Tenant Manager の通信を分離できます。



 a| 
18082
 a| 
TCP
 a| 
HTTPS
 a| 
S3 クライアント
 a| 
ストレージノード
 a| 
ストレージノードへのS3クライアントトラフィックの直接転送（HTTPS）。



 a| 
18083
 a| 
TCP
 a| 
HTTPS
 a| 
Swift クライアント
 a| 
ストレージノード
 a| 
ストレージノードへのSwiftクライアントトラフィック（HTTPS）。



 a| 
18084
 a| 
TCP
 a| 
HTTP
 a| 
S3 クライアント
 a| 
ストレージノード
 a| 
ストレージノードへのS3クライアントトラフィックの直接転送（HTTP）。



 a| 
18085
 a| 
TCP
 a| 
HTTP
 a| 
Swift クライアント
 a| 
ストレージノード
 a| 
ストレージノードへのSwiftクライアントトラフィック（HTTP）。



 a| 
23000-23999
 a| 
TCP
 a| 
HTTPS
 a| 
グリッド間レプリケーションのソースグリッド上のすべてのノード
 a| 
グリッド間レプリケーション用のデスティネーショングリッド上の管理ノードとゲートウェイノード
 a| 
この範囲のポートはグリッドフェデレーション接続用に予約されています。特定の接続の両方のグリッドが同じポートを使用します。

|===