---
permalink: network/internal-grid-node-communications.html 
sidebar: sidebar 
keywords: storagegrid, network port, internal communications, ports, TCP, UDP, grid communications, port 
summary: StorageGRID の内部ファイアウォールは、ポート 22 、 80 、 123 、 443 を除き、グリッドネットワーク上の特定のポートへの受信接続のみを許可します（外部通信に関する情報を参照）。ロードバランサエンドポイントで定義されたポートにも接続が許可されます。 
---
= 内部でのグリッドノードの通信
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID の内部ファイアウォールは、グリッドネットワーク上の特定のポートへの受信接続を許可します。ロードバランサエンドポイントで定義されたポートにも接続が許可されます。


NOTE: グリッドノード間で Internet Control Message Protocol （ ICMP ）トラフィックを有効にすることを推奨します。ICMPトラフィックを許可すると、グリッドノードに到達できない場合のフェイルオーバーパフォーマンスが向上します。

StorageGRID では、 ICMP と表に記載されているポートに加えて、 Virtual Router Redundancy Protocol （ VRRP; 仮想ルータ冗長プロトコル）を使用します。VRRP は、 IP プロトコル番号 112 を使用するインターネットプロトコルです。StorageGRID は、ユニキャストモードでのみ VRRP を使用します。VRRPが必要なのは、が設定されている場合だけlink:../admin/managing-high-availability-groups.html["ハイアベイラビリティグループ"]です。



== Linux ベースのノードについてはガイドラインを参照してください

エンタープライズ ネットワーク ポリシーによってこれらのポートへのアクセスが制限されている場合は、デプロイメント構成パラメータを使用してデプロイメント時にポートを再マップできます。ポートの再マッピングとデプロイメント構成パラメータの詳細については、以下を参照してください。link:../swnodes/index.html["ソフトウェアベースのノードにStorageGRIDをインストールする"] 。


NOTE: ポート再マッピングのサポートは非推奨であり、将来のリリースでは削除される予定です。再マップされたポートを削除するには、link:../maintain/removing-port-remaps-on-bare-metal-hosts.html["ベアメタルホストでのポートの再マッピングを削除します"] 。



== VMware ベースのノードについてのガイドラインを参照してください

次のポートは、 VMware ネットワーク外部のファイアウォール制限を定義する必要がある場合にのみ設定してください。

エンタープライズ ネットワーク ポリシーによってこれらのポートへのアクセスが制限されている場合は、VMware vSphere Web Client を使用してノードを展開するときにポートを再マップするか、グリッド ノードの展開を自動化するときに構成ファイル設定を使用できます。ポートの再マッピングとデプロイメント構成パラメータの詳細については、link:../swnodes/index.html["VMware にStorageGRIDをインストールする"] 。


NOTE: ポート再マッピングのサポートは非推奨であり、将来のリリースでは削除される予定です。再マップされたポートを削除するには、link:../maintain/removing-port-remaps-on-bare-metal-hosts.html["ベアメタルホストでのポートの再マッピングを削除します"] 。



== アプライアンスノードのガイドライン

これらのいずれかのポートへのアクセスがエンタープライズネットワークポリシーで制限されている場合は、 StorageGRID アプライアンスインストーラを使用してポートを再マッピングできます。を参照してください https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/optional-remapping-network-ports-for-appliance.html["オプション：アプライアンスのネットワークポートの再マッピング"^]


NOTE: ポート再マッピングのサポートは非推奨であり、将来のリリースでは削除される予定です。再マップされたポートを削除するには、link:../maintain/removing-port-remaps.html["StorageGRIDアプライアンスのポート再マップを削除します"] 。



== StorageGRID の内部ポート

[cols="1a,1a,1a,1a,4a"]
|===
| ポート | tcp または udp です | 開始 | 宛先 | 詳細 


 a| 
22
 a| 
TCP
 a| 
プライマリ管理ノード
 a| 
すべてのノード
 a| 
メンテナンス手順では、プライマリ管理ノードがポート 22 で SSH を使用して他のすべてのノードと通信できる必要があります。他のノードからの SSH トラフィックの許可は任意です。



 a| 
80
 a| 
TCP
 a| 
アプライアンス
 a| 
プライマリ管理ノード
 a| 
StorageGRID アプライアンスが、インストールを開始する目的でプライマリ管理ノードと通信するために使用します。



 a| 
123
 a| 
UDP
 a| 
すべてのノード
 a| 
すべてのノード
 a| 
ネットワークタイムプロトコルサービス。すべてのノードは、 NTP を使用して他のすべてのノードと時間を同期します。



 a| 
443
 a| 
TCP
 a| 
すべてのノード
 a| 
プライマリ管理ノード
 a| 
インストールおよびその他のメンテナンス手順の実行中に、プライマリ管理ノードにステータスを通知するために使用します。



 a| 
1055
 a| 
TCP
 a| 
すべてのノード
 a| 
プライマリ管理ノード
 a| 
インストール、拡張、リカバリ、およびその他のメンテナンス手順用の内部トラフィック。



 a| 
1139
 a| 
TCP
 a| 
ストレージノード
 a| 
ストレージノード
 a| 
ストレージノード間の内部トラフィック。



 a| 
1501
 a| 
TCP
 a| 
すべてのノード
 a| 
ADC を採用するストレージノード
 a| 
レポート、監査、および設定の内部トラフィック。



 a| 
1502
 a| 
TCP
 a| 
すべてのノード
 a| 
ストレージノード
 a| 
S3 関連の内部トラフィック。



 a| 
1504
 a| 
TCP
 a| 
すべてのノード
 a| 
管理ノード
 a| 
NMS サービスのレポートおよび設定の内部トラフィック。



 a| 
1505
 a| 
TCP
 a| 
すべてのノード
 a| 
管理ノード
 a| 
AMS サービスの内部トラフィック。



 a| 
1506
 a| 
TCP
 a| 
すべてのノード
 a| 
すべてのノード
 a| 
サーバステータスの内部トラフィック。



 a| 
1507
 a| 
TCP
 a| 
すべてのノード
 a| 
ゲートウェイノード
 a| 
ロードバランサの内部トラフィック。



 a| 
1508
 a| 
TCP
 a| 
すべてのノード
 a| 
プライマリ管理ノード
 a| 
設定管理の内部トラフィック。



 a| 
1511
 a| 
TCP
 a| 
すべてのノード
 a| 
ストレージノード
 a| 
メタデータの内部トラフィック。



 a| 
7001
 a| 
TCP
 a| 
ストレージノード
 a| 
ストレージノード
 a| 
Cassandra TLS ノード間クラスタ通信。



 a| 
7443
 a| 
TCP
 a| 
すべてのノード
 a| 
プライマリ管理ノード
 a| 
インストール、拡張、リカバリ、その他のメンテナンス手順、およびエラーレポート用の内部トラフィック。



 a| 
8011
 a| 
TCP
 a| 
すべてのノード
 a| 
プライマリ管理ノード
 a| 
インストール、拡張、リカバリ、およびその他のメンテナンス手順用の内部トラフィック。



 a| 
8443
 a| 
TCP
 a| 
プライマリ管理ノード
 a| 
アプライアンスノード
 a| 
メンテナンスモードの手順 に関連する内部トラフィック。



 a| 
9042
 a| 
TCP
 a| 
ストレージノード
 a| 
ストレージノード
 a| 
Cassandra クライアントポート。



 a| 
9999
 a| 
TCP
 a| 
すべてのノード
 a| 
すべてのノード
 a| 
複数のサービスの内部トラフィック。メンテナンス手順、指標、およびネットワークの更新が含まれます。



 a| 
10226
 a| 
TCP
 a| 
ストレージノード
 a| 
プライマリ管理ノード
 a| 
StorageGRIDアプライアンスで、EシリーズSANtricity System Managerからプライマリ管理ノードにAutoSupportパッケージを転送するために使用されます。



 a| 
10342
 a| 
TCP
 a| 
すべてのノード
 a| 
プライマリ管理ノード
 a| 
インストール、拡張、リカバリ、およびその他のメンテナンス手順用の内部トラフィック。



 a| 
18000
 a| 
TCP
 a| 
管理 / ストレージノード
 a| 
ADC を採用するストレージノード
 a| 
アカウントサービスの内部トラフィック。



 a| 
18001
 a| 
TCP
 a| 
管理 / ストレージノード
 a| 
ADC を採用するストレージノード
 a| 
アイデンティティフェデレーションの内部トラフィック。



 a| 
18002
 a| 
TCP
 a| 
管理 / ストレージノード
 a| 
ストレージノード
 a| 
オブジェクトプロトコルに関連する内部 API トラフィック。



 a| 
18003
 a| 
TCP
 a| 
管理 / ストレージノード
 a| 
ADC を採用するストレージノード
 a| 
プラットフォームサービスの内部トラフィック。



 a| 
18017
 a| 
TCP
 a| 
管理 / ストレージノード
 a| 
ストレージノード
 a| 
クラウドストレージプールの Data Mover サービスの内部トラフィック。



 a| 
18019
 a| 
TCP
 a| 
ストレージノード
 a| 
ストレージノード
 a| 
イレイジャーコーディング用のチャンクサービスの内部トラフィック。



 a| 
18082
 a| 
TCP
 a| 
管理 / ストレージノード
 a| 
ストレージノード
 a| 
S3 関連の内部トラフィック。



 a| 
18086
 a| 
TCP
 a| 
すべてのグリッドノード
 a| 
すべてのストレージノード
 a| 
LDRサービスに関連する内部トラフィック。



 a| 
18200
 a| 
TCP
 a| 
管理 / ストレージノード
 a| 
ストレージノード
 a| 
クライアント要求に関する追加の統計。



 a| 
19000
 a| 
TCP
 a| 
管理 / ストレージノード
 a| 
ADC を採用するストレージノード
 a| 
Keystone サービスの内部トラフィック。

|===
.関連情報
link:external-communications.html["外部との通信"]
