---
permalink: network/linux-deployments.html 
sidebar: sidebar 
keywords: linux network, container engine, red hat enterprise linux network, rhel network, ubuntu network 
summary: 効率性、信頼性、セキュリティのために、 StorageGRID システムはコンテナエンジンの集合として Linux 上で動作します。StorageGRID システムでは、コンテナエンジン関連のネットワーク構成は必要ありません。 
---
= Linux の導入
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
効率性、信頼性、セキュリティのために、 StorageGRID システムはコンテナエンジンの集合として Linux 上で動作します。StorageGRID システムでは、コンテナエンジン関連のネットワーク構成は必要ありません。

コンテナネットワークインターフェイスには、 VLAN ペアや仮想イーサネット（ veth ）ペアなどの非ボンドデバイスを使用します。このデバイスをノード構成ファイルのネットワークインターフェイスとして指定してください。


CAUTION: ボンドデバイスやブリッジデバイスをコンテナネットワークインターフェイスとして直接使用しないでください。このようにすると、 macvlan を使用してコンテナネームスペース内のボンドデバイスとブリッジデバイスを使用するカーネル問題 が原因でノードの起動が妨げられる可能性があります。

参照link:../swnodes/index.html["インストール手順"]。



== コンテナエンジン導入用のホストネットワーク構成

コンテナエンジンプラットフォームで StorageGRID の導入を開始する前に、各ノードで使用するネットワーク（グリッド、管理、クライアント）を決めます。各ノードのネットワークインターフェイスが正しい仮想または物理ホストインターフェイスに設定されていること、および各ネットワークに十分な帯域幅があることを確認してください。



=== 物理ホスト

物理ホストを使用してグリッドノードをサポートする場合は、次の手順を実行します。

* すべてのホストで各ノードインターフェイスに同じホストインターフェイスを使用していることを確認します。この方法により、ホストの構成が簡易化され、将来のノードの移行にも対応できます
* 物理ホスト自体の IP アドレスを取得します。
+

NOTE: ホスト上の物理インターフェイスは、ホスト自体と、ホスト上で実行されている 1 つ以上のノードで使用できます。このインターフェイスを使用するホストまたはノードには、一意の IP アドレスを割り当てる必要があります。ホストとノードでIPアドレスを共有することはできません。

* ホストに必要なポートを開きます。
* StorageGRID で VLAN インターフェイスを使用する場合は、必要な VLAN へのアクセスを提供するトランクインターフェイスがホストに 1 つ以上必要です。これらのインターフェイスは、 eth0 、 eth2 、または追加のインターフェイスとしてノードコンテナに渡すことができます。トランクインターフェイスまたはアクセスインターフェイスを追加するには、次の項を参照してください。
+
** *Linux (ノードをインストールする前)*:link:../swnodes/creating-node-configuration-files.html["ノード構成ファイルを作成"]
** *Linux (ノードのインストール後)*:link:../maintain/linux-adding-trunk-or-access-interfaces-to-node.html["ノードにトランクまたはアクセスインターフェースを追加する"]





NOTE: 「Linux」は、RHEL、Ubuntu、または Debian のデプロイメントを指します。サポートされているバージョンのリストについては、 https://imt.netapp.com/matrix/#welcome["NetApp Interoperability Matrix Tool（IMT）"^] 。



=== 最小帯域幅の推奨値

次の表に、StorageGRID ノードのタイプとネットワークのタイプごとに推奨される最小LAN帯域幅を示します。それぞれの物理ホストまたは仮想ホストについて、そのホストで実行する StorageGRID ノードの総数とタイプに応じて、アグリゲートの最小帯域幅要件を満たすように十分なネットワーク帯域幅を確保する必要があります。

[cols="1a,1a,1a,1a"]
|===
| ノードのタイプ 3+| ネットワークのタイプ 


 a| 
 a| 
グリッド
 a| 
管理者
 a| 
クライアント



 a| 
 a| 
*最小LAN帯域幅*



 a| 
管理者
 a| 
10Gbps
 a| 
1Gbps
 a| 
1Gbps



 a| 
ゲートウェイ
 a| 
10Gbps
 a| 
1Gbps
 a| 
10Gbps



 a| 
ストレージ
 a| 
10Gbps
 a| 
1Gbps
 a| 
10Gbps



 a| 
アーカイブする
 a| 
10Gbps
 a| 
1Gbps
 a| 
10Gbps

|===

NOTE: この表には、共有ストレージへのアクセスに必要な SAN の帯域幅は含まれていません。イーサネット経由（ iSCSI または FCoE ）でアクセスする共有ストレージを使用する場合は、各ホストで物理インターフェイスを別途プロビジョニングして十分な SAN の帯域幅を確保する必要があります。ボトルネックにならないように、各ホストの SAN の帯域幅として、そのホストで実行されるすべてのストレージノードの総ネットワーク帯域幅とほぼ同じ帯域幅を確保します。

上記の表を参照して、それぞれのホストに最小限必要なネットワークインターフェイスの数を確認します。これは、そのホストで実行する StorageGRID ノードの数とタイプで決まります。

たとえば、単一のホストで管理ノード、ゲートウェイノード、およびストレージノードを 1 つずつ実行するには、次の手順を実行します。

* 管理ノードにグリッドネットワークと管理ネットワークを接続する（必要な帯域幅： 10 + 1 = 11Gbps ）
* ゲートウェイノードにグリッドネットワークとクライアントネットワークを接続する（必要な帯域幅： 10 + 10 = 20Gbps ）
* ストレージノードにグリッドネットワークを接続する（必要な帯域幅： 10Gbps ）


このシナリオでは、少なくとも 11+20+10=41 Gbps のネットワーク帯域幅を提供する必要があります。 2 つの 40Gbps インターフェイスまたは 5 つの 10Gbps インターフェイスで対応できます。これらは潜在的にトランクに集約され、ホストを含む物理データセンターに対してローカルなグリッド、管理、およびクライアントのサブネットを伝送する 3 つ以上の VLAN によって共有されます。

StorageGRIDの導入準備として、 StorageGRIDクラスタ内のホスト上の物理リソースとネットワークリソースを構成するための推奨方法については、以下を参照してください。link:../swnodes/configuring-host-network.html["ホストネットワークを設定する"] 。
