---
permalink: network/network-specific-requirements.html 
sidebar: sidebar 
keywords: network-specific requirements, network specific requirements, network requirements 
summary: 各 StorageGRID ネットワークタイプの要件に従ってください。 
---
= ネットワーク固有の要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
各 StorageGRID ネットワークタイプの要件に従ってください。



== ネットワークゲートウェイおよびルータ

* 設定する場合、特定のネットワークのゲートウェイは、そのネットワークのサブネット内になければなりません。
* 静的アドレス指定を使用してインターフェイスを設定する場合は、 0.0.0.0 以外のゲートウェイアドレスを指定する必要があります。
* ゲートウェイがない場合は、ゲートウェイアドレスをネットワークインターフェイスのIPアドレスに設定することを推奨します。




== サブネット


NOTE: 各ネットワークは、ノード上の他のネットワークと重複しない、専用のサブネットに接続する必要があります。

導入時に、 Grid Manager によって次の制限事項が適用されます。これらの情報は、導入前のネットワーク計画に役立ちます。

* ネットワークIPアドレスのサブネットマスクを255.255.255.254または255.255.255.255（CIDR表記では/31または/32）にすることはできません。
* ネットワークインターフェイスのIPアドレスとサブネットマスク（CIDR）によって定義されたサブネットは、同じノードに設定されている他のインターフェイスのサブネットと重複することはできません。
* 各ノードのグリッドネットワークサブネットを GNSL に含める必要があります。
* 管理ネットワークサブネットは、グリッドネットワークサブネット、クライアントネットワークサブネット、またはGNSLのサブネットと重複することはできません。
* AESL内のサブネットは、GNSL内のどのサブネットとも重複できません。
* クライアントネットワークサブネットは、グリッドネットワークサブネット、管理ネットワークサブネット、GNSLのサブネット、またはAESLのサブネットと重複することはできません。




== グリッドネットワーク

* 導入時に、各グリッドノードがグリッドネットワークに接続され、ノード導入時に指定したネットワーク設定を使用してプライマリ管理ノードと通信できる必要があります。
* 通常のグリッド運用中は、各グリッドノードがグリッドネットワークを介して他のすべてのグリッドノードと通信できる必要があります。
+

NOTE: グリッドネットワークは、各ノード間で直接ルーティングできる必要があります。ノード間の Network Address Translation （ NAT ；ネットワークアドレス変換）はサポートされていません。

* グリッドネットワークが複数のサブネットで構成されている場合は、グリッドネットワークサブネットリスト（ GNSL ）に追加します。GNSL のサブネットごとに、すべてのノードにスタティックルートが作成されます。
* グリッドネットワークインターフェイスが VLAN インターフェイスをサポートするトランクとして設定されている場合は、トランクのネイティブ VLAN をグリッドネットワークトラフィックに使用する VLAN にする必要があります。すべてのグリッドノードに、トランクのネイティブ VLAN 経由でアクセスできる必要があります。




== 管理ネットワーク

管理ネットワークはオプションです。管理ネットワークを設定する場合は、次の要件およびガイドラインに従ってください。

管理ネットワークの一般的な用途には、管理接続、AutoSupport 、KMSのほか、重要なサーバ（グリッドネットワークまたはクライアントネットワーク経由で接続されていない場合）への接続があります。


NOTE: 必要なネットワークサービスおよびクライアントにアクセス可能であれば、管理ネットワークおよび AESL は各ノードで一意にすることができます。


NOTE: 外部サブネットからのインバウンド接続を有効にするには、管理ネットワークに少なくとも 1 つのサブネットを定義する必要があります。AESL に含まれる各サブネットの静的ルートがノードごとに自動的に生成されます。



== クライアントネットワーク

クライアントネットワークはオプションです。クライアントネットワークを設定する場合は、次の考慮事項に注意してください。

* クライアントネットワークは、S3クライアントからのトラフィックをサポートするように設計されています。設定すると、クライアントネットワークゲートウェイがノードのデフォルトゲートウェイになります。
* クライアントネットワークを使用する場合は、明示的に設定されたロードバランサエンドポイントでのみインバウンドクライアントトラフィックを受け入れることで、悪意のある攻撃から StorageGRID を保護できます。を参照して link:../admin/configuring-load-balancer-endpoints.html["ロードバランサエンドポイントを設定する"]
* クライアントネットワークインターフェイスが VLAN インターフェイスをサポートするトランクとして設定されている場合は、クライアントネットワークインターフェイス（ eth2 ）の設定が必要かどうかを検討してください。設定されている場合、クライアントネットワークトラフィックは、スイッチで設定されたトランクネイティブ VLAN を経由します。


.関連情報
link:../maintain/changing-nodes-network-configuration.html["ノードのネットワーク設定の変更"]
