---
permalink: network/networking-requirements-and-guidelines.html 
sidebar: sidebar 
keywords: storagegrid, networking requirements, network requirements, nat 
summary: 計画した StorageGRID ネットワーク設計を、現在のネットワークインフラと構成がサポートできることを確認する必要があります。 
---
= StorageGRID のネットワーク要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
計画した StorageGRID ネットワーク設計を、現在のネットワークインフラと構成がサポートできることを確認する必要があります。



== 一般的なネットワーク要件

すべての StorageGRID 環境で次の接続がサポートされている必要があります。

これらの接続は、ネットワークトポロジの例に示すように、グリッドネットワーク、管理ネットワーク、クライアントネットワーク、またはこれらのネットワークの組み合わせを介して発生します。

* * 管理接続 * ：通常は SSH 経由で、管理者からノードへのインバウンド接続。Grid Manager 、テナントマネージャ、および StorageGRID アプライアンスインストーラへの Web ブラウザアクセス
* * NTPサーバ接続*：インバウンドUDP応答を受信するアウトバウンドUDP接続。
+
プライマリ管理ノードが、少なくとも 1 つの NTP サーバにアクセスできる必要があります。

* * DNSサーバ接続*：インバウンドUDP応答を受信するアウトバウンドUDP接続。
* *LDAP/Active Directory サーバ接続 *: ストレージノード上のアイデンティティサービスからのアウトバウンド TCP 接続。
* * AutoSupport *：管理ノードからまたはお客様が設定したプロキシへのアウトバウンドTCP接続 `support.netapp.com`。
* * 外部キー管理サーバ * ：ノード暗号化が有効な各アプライアンスノードからのアウトバウンド TCP 接続。
* S3クライアントからのインバウンドTCP接続。
* CloudMirror レプリケーションやクラウドストレージプールなどの StorageGRID プラットフォームサービスからのアウトバウンド要求。


StorageGRID がデフォルトのルーティングルールを使用してプロビジョニングされたNTPサーバまたはDNSサーバにアクセスできない場合は、DNSサーバとNTPサーバのIPアドレスが指定されているかぎり、すべてのネットワーク（グリッド、管理、クライアント）の接続が自動的に試行されます。NTP サーバまたは DNS サーバにネットワーク経由でアクセスできる場合は、 StorageGRID によって追加のルーティングルールが自動的に作成され、以降のすべてのネットワーク接続試行に使用されるようになります。


TIP: これらの自動検出されたホストルートは使用できますが、通常は、自動検出が失敗した場合に接続を確保するために、 DNS ルートと NTP ルートを手動で設定する必要があります。

導入時にオプションの管理ネットワークとクライアントネットワークを設定する準備ができていない場合は、設定手順でグリッドノードを承認するときにそれらのネットワークを設定できます。また、インストール後にIP変更ツールを使用してこれらのネットワークを設定することもできます（を参照）link:../maintain/configuring-ip-addresses.html["IP アドレスを設定する"]。

VLANインターフェイス経由では、S3クライアント接続とSSH、Grid Manager、およびTenant Managerの管理接続のみがサポートされます。NTP 、 DNS 、 LDAP 、 AutoSupport 、 KMS サーバなどへのアウトバウンド接続 クライアント、管理、またはグリッドネットワークのインターフェイスを直接経由する必要があります。インターフェイスが VLAN インターフェイスをサポートするトランクとして設定されている場合、このトラフィックはスイッチで設定されたインターフェイスのネイティブ VLAN を経由します。



== 複数サイト用の WAN （ Wide Area Network ）

複数のサイトで StorageGRID システムを設定する場合は、クライアントトラフィックを考慮する前に、サイト間の WAN 接続の各方向の帯域幅が 25 Mbit/ 秒以上である必要があります。サイト間、ノードまたはサイトの拡張、ノードのリカバリ、その他の処理や構成のデータレプリケーションやイレイジャーコーディングでは、追加の帯域幅が必要になります。

WAN帯域幅の実際の最小要件は、クライアントアクティビティとILM保護方式によって異なります。最小WAN帯域幅要件の見積もりについては、ネットアッププロフェッショナルサービスのコンサルタントにお問い合わせください。



== 管理ノードとゲートウェイノードの接続

管理ノードは、開いているインターネット上のノードなど、信頼されていないクライアントから常に保護する必要があります。グリッドネットワーク上、管理ネットワーク上、またはクライアントネットワーク上のどの管理ノードにも、信頼されていないクライアントがアクセスできないようにする必要があります。

ハイアベイラビリティグループに追加する管理ノードとゲートウェイノードには静的 IP アドレスを設定する必要があります。詳細については、を参照してください link:../admin/managing-high-availability-groups.html["ハイアベイラビリティグループを管理します"]。



== ネットワークアドレス変換（ NAT ）の使用

グリッドノード間またはStorageGRID サイト間のグリッドネットワークでは、Network Address Translation（NAT；ネットワークアドレス変換）を使用しないでください。グリッドネットワークにプライベート IPv4 アドレスを使用する場合は、使用するアドレスに各サイトのすべてのグリッドノードから直接ルーティングできる必要があります。ただし、必要に応じて、ゲートウェイノードにパブリック IP アドレスを指定するなど、外部クライアントとグリッドノードの間で NAT を使用できます。NAT を使用してパブリックネットワークセグメントをブリッジする方法は、グリッド内のすべてのノードに対して透過的なトンネリングアプリケーションを採用する場合、つまりグリッドノードがパブリック IP アドレスを認識する必要がない場合にのみサポートされます。
