---
permalink: network/storagegrid-network-types.html 
sidebar: sidebar 
keywords: network types, grid traffic, admin traffic, client traffic, grid network, admin network, client network 
summary: StorageGRID システムのグリッドノードは、グリッドトラフィック、管理トラフィック、およびクライアントトラフィックを処理します。この 3 種類のトラフィックを管理し、制御とセキュリティを提供するには、ネットワークを適切に設定する必要があります。 
---
= StorageGRID のネットワークタイプ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システムのグリッドノードは、 _ グリッドトラフィック _ 、 _ 管理トラフィック _ 、および _ クライアントトラフィック _ を処理します。この 3 種類のトラフィックを管理し、制御とセキュリティを提供するには、ネットワークを適切に設定する必要があります。



== トラフィックタイプ

[cols="1a,4a,2a"]
|===
| トラフィックタイプ | 製品説明 | ネットワークの種類 


 a| 
グリッドトラフィック
 a| 
グリッド内のすべてのノードの間で伝送される、内部 StorageGRID トラフィック。このネットワークを介して、すべてのグリッドノードが他のすべてのグリッドノードと通信できる必要があります。
 a| 
グリッドネットワーク（必須）



 a| 
管理トラフィック
 a| 
システムの管理とメンテナンスに使用されるトラフィック。
 a| 
管理ネットワーク（オプション）、<<オプションの VLAN ネットワーク,VLAN ネットワーク（オプション）>>



 a| 
クライアントトラフィック
 a| 
外部クライアントアプリケーションとグリッドの間で伝送されるトラフィック（S3クライアントからのすべてのオブジェクトストレージ要求を含む）。
 a| 
クライアントネットワーク（オプション）<<オプションの VLAN ネットワーク,VLAN ネットワーク（オプション）>>

|===
ネットワークは次の方法で設定できます。

* Grid ネットワークのみ
* グリッドネットワークと管理ネットワーク
* グリッドネットワークとクライアントネットワーク
* グリッドネットワーク、管理ネットワーク、クライアントネットワーク


グリッドネットワークは必須であり、すべてのグリッドトラフィックを管理できます。管理ネットワークとクライアントネットワークは、インストール時に追加することも、あとで追加して要件の変化に対応することもできます。管理ネットワークとクライアントネットワークはオプションですが、これらのネットワークを使用して管理トラフィックとクライアントトラフィックを処理する場合は、グリッドネットワークを分離してセキュリティを確保することができます。

内部ポートには、グリッドネットワーク経由でのみアクセスできます。外部ポートには、すべてのタイプのネットワークからアクセスできます。この柔軟性により、 StorageGRID 展開の設計と、スイッチおよびファイアウォールでの外部 IP およびポートフィルタリングの設定に複数のオプションを使用できます。およびを参照してくださいlink:../network/internal-grid-node-communications.html["内部でのグリッドノードの通信"]link:../network/external-communications.html["外部との通信"]。



== ネットワークインターフェイス

StorageGRID ノードは、次の特定のインターフェイスを使用して各ネットワークに接続されます。

[cols="1a,1a"]
|===
| ネットワーク | インターフェイス名 


 a| 
グリッドネットワーク（必須）
 a| 
eth0



 a| 
管理ネットワーク（オプション）
 a| 
eth1



 a| 
クライアントネットワーク（オプション）
 a| 
eth2

|===
仮想ポートまたは物理ポートをノードネットワークインターフェースにマッピングする方法の詳細については、以下を参照してください。link:../swnodes/index.html["ソフトウェアベースのノードにStorageGRIDをインストールする"] 。

.アプライアンスノード
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/hardware-description-sg6100.html["SG6160ストレージアプライアンス"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/hardware-description-sg6100.html["SGF6112ストレージアプライアンス"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/hardware-description-sg6000.html["SG6000ストレージアプライアンス"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/hardware-description-sg5800.html["SG5800ストレージアプライアンス"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/hardware-description-sg5700.html["SG5700ストレージアプライアンス"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/hardware-description-sg110-and-1100.html["SG110およびSG1100サービスアプライアンス"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/hardware-description-sg100-and-1000.html["SG100およびSG1000サービス アプライアンス"^]




=== 各ノードのネットワーク情報

ノードで有効にするネットワークごとに、次の項目を設定する必要があります。

* IPアドレス
* サブネットマスク
* ゲートウェイのIPアドレス


各グリッドノードの 3 つのネットワークのそれぞれについて、 IP アドレス / マスク / ゲートウェイの組み合わせを 1 つだけ設定できます。ネットワークにゲートウェイを設定しない場合は、IPアドレスをゲートウェイアドレスとして使用する必要があります。



=== ハイアベイラビリティグループ

ハイアベイラビリティ（ HA ）グループは、グリッドネットワークまたはクライアントネットワークのインターフェイスに仮想 IP （ VIP ）アドレスを追加する機能を提供します。詳細については、を参照してください link:../admin/managing-high-availability-groups.html["ハイアベイラビリティグループを管理します"]。



== グリッドネットワーク

グリッドネットワークは必須です。このネットワークは、すべての内部 StorageGRID トラフィックに使用されます。グリッドネットワークは、グリッド内のすべてのノード間、すべてのサイトおよびサブネットを接続します。グリッドネットワーク上のすべてのノードが他のすべてのノードと通信できる必要があります。グリッドネットワークは複数のサブネットで構成できます。NTP などの重要なグリッドサービスを含むネットワークも、グリッドサブネットとして追加できます。


NOTE: StorageGRID では、ノード間の Network Address Translation （ NAT; ネットワークアドレス変換）はサポートされません。

管理ネットワークとクライアントネットワークが設定されている場合でも、グリッドネットワークはすべての管理トラフィックとすべてのクライアントトラフィックに使用できます。ノードにクライアントネットワークが設定されていないかぎり、グリッドネットワークゲートウェイがノードのデフォルトゲートウェイになります。


CAUTION: グリッドネットワークを設定するときは、オープンなインターネット上のネットワークなど、信頼されていないクライアントからネットワークが保護されていることを確認する必要があります。

グリッドネットワークゲートウェイに関する次の要件と詳細に注意してください。

* グリッドサブネットが複数ある場合は、グリッドネットワークゲートウェイを設定する必要があります。
* グリッドの設定が完了するまでは、グリッドネットワークゲートウェイがノードのデフォルトゲートウェイになります。
* グローバルなグリッドネットワークサブネットリストで設定されているすべてのサブネットへの静的ルートが、すべてのノードに対して自動的に生成されます。
* クライアントネットワークを追加すると、グリッドの設定が完了した時点で、デフォルトゲートウェイがグリッドネットワークのゲートウェイからクライアントネットワークゲートウェイに切り替わります。




== 管理ネットワーク

管理ネットワークはオプションです。このオプションを設定すると、システムの管理トラフィックやメンテナンストラフィックに使用できます。管理ネットワークは通常はプライベートネットワークであり、ノード間でルーティング可能にする必要はありません。

管理ネットワークを有効にするグリッドノードを選択できます。

管理ネットワークを使用する場合、管理トラフィックとメンテナンストラフィックがグリッドネットワークを経由する必要はありません。管理ネットワークの一般的な用途は次のとおりです。

* Grid Manager および Tenant Manager のユーザインターフェイスにアクセスします。
* NTP サーバ、 DNS サーバ、外部キー管理サーバ（ KMS ）、 Lightweight Directory Access Protocol （ LDAP ）サーバなどの重要なサービスへのアクセス
* 管理ノード上の監査ログへのアクセス。
* 保守とサポートのための Secure Shell Protocol （ SSH ）アクセス。


管理ネットワークが内部のグリッドトラフィックに使用されることはありません。管理ネットワークゲートウェイが提供され、管理ネットワークが複数の外部サブネットと通信できるようになります。ただし、管理ネットワークゲートウェイがノードのデフォルトゲートウェイとして使用されることはありません。

管理ネットワークゲートウェイに関する次の要件および詳細事項に注意してください。

* 管理ネットワークサブネットの外部から接続を行う場合や複数の管理ネットワークサブネットを設定する場合は、管理ネットワークゲートウェイが必要です。
* ノードの管理ネットワークサブネットリストで設定されているサブネットごとに静的ルートが作成されます。




== クライアントネットワーク

クライアントネットワークはオプションです。設定すると、S3などのクライアントアプリケーションにグリッドサービスへのアクセスを提供するために使用されます。外部リソース（クラウドストレージプールや StorageGRID CloudMirror レプリケーションサービスなど）から StorageGRID データにアクセスできるようにする場合は、外部リソースもクライアントネットワークを使用できます。グリッドノードは、クライアントネットワークゲートウェイ経由で到達できるすべてのサブネットと通信できます。

クライアントネットワークを有効にするグリッドノードを選択できます。すべてのノードが同じクライアントネットワーク上にある必要はなく、クライアントネットワーク経由で相互に通信することはありません。クライアントネットワークは、グリッドのインストールが完了するまで動作状態になりません。

セキュリティを強化するために、ノードのクライアントネットワークインターフェイスを信頼されていないものと指定し、クライアントネットワークで許可される接続をより厳しく制限できます。ノードのクライアントネットワークインターフェイスが信頼されていない場合、このインターフェイスは CloudMirror レプリケーションで使用される接続などのアウトバウンド接続を受け入れますが、ロードバランサエンドポイントとして明示的に設定されているポートのインバウンド接続だけを受け入れます。およびを参照してくださいlink:../admin/manage-firewall-controls.html["ファイアウォールコントロールを管理します"]link:../admin/configuring-load-balancer-endpoints.html["ロードバランサエンドポイントを設定する"]。

クライアントネットワークを使用する場合、クライアントトラフィックがグリッドネットワークを経由する必要はありません。グリッドネットワークトラフィックは、ルーティングされないセキュアなネットワークに分離できます。クライアントネットワークでは、多くの場合、次のノードタイプが設定されます。

* ゲートウェイノード（これらのノードがStorageGRIDロードバランササービスへのアクセスとグリッドへのS3クライアントアクセスを提供するため）。
* ストレージノード：S3プロトコル、クラウドストレージプール、CloudMirrorレプリケーションサービスへのアクセスを提供します。
* 管理ノード：テナントユーザが管理ネットワークを使用せずにTenant Managerに接続できるようにするため。


クライアントネットワークゲートウェイについては、次の点に注意してください。

* クライアントネットワークを設定する場合は、クライアントネットワークゲートウェイが必要です。
* グリッドの設定が完了すると、クライアントネットワークのゲートウェイがグリッドノードのデフォルトルートになります。




== オプションの VLAN ネットワーク

必要に応じて、クライアントトラフィックおよび一部のタイプの管理トラフィックに、仮想 LAN （ VLAN ）ネットワークを使用できます。ただし、グリッドトラフィックではVLANインターフェイスを使用できません。ノード間の内部 StorageGRID トラフィックは、常に eth0 でグリッドネットワークを使用する必要があります。

VLAN の使用をサポートするには、 1 つのノード上の 1 つ以上のインターフェイスをスイッチでトランクインターフェイスとして設定する必要があります。グリッドネットワークインターフェイス（eth0）またはクライアントネットワークインターフェイス（eth2）をトランクとして設定するか、ノードにトランクインターフェイスを追加できます。

eth0 がトランクとして設定されている場合、グリッドネットワークトラフィックはスイッチで設定されたトランクのネイティブインターフェイスを経由します。同様に、 eth2 がトランクとして設定されていて、クライアントネットワークも同じノード上で構成されている場合、クライアントネットワークはスイッチ上で構成されているトランクポートのネイティブ VLAN を使用します。

VLAN ネットワークでは、 SSH 、 Grid Manager 、または Tenant Manager のトラフィックに使用するなどのインバウンド管理トラフィックのみがサポートされます。NTP 、 DNS 、 LDAP 、 KMS 、クラウドストレージプールなどのアウトバウンドトラフィックは、 VLAN ネットワーク経由ではサポートされません。


NOTE: VLAN インターフェイスは管理ノードとゲートウェイノードにのみ追加できます。ストレージノードへのクライアントアクセスまたは管理アクセスにVLANインターフェイスを使用することはできません。

手順とガイドラインについては、を参照してくださいlink:../admin/configure-vlan-interfaces.html["VLAN インターフェイスを設定します"]。

VLAN インターフェイスは HA グループでのみ使用され、アクティブノード上の VIP アドレスに割り当てられます。手順とガイドラインについては、を参照してくださいlink:../admin/managing-high-availability-groups.html["ハイアベイラビリティグループを管理します"]。
