---
permalink: network/subnet-requirements.html 
sidebar: sidebar 
keywords: network subnets 
summary: ネットワークサブネットについては、次の要件およびガイドラインに従ってください。 
---
= サブネットの要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ネットワークサブネットについては、次の要件およびガイドラインに従ってください。


NOTE: 各ネットワークは、ノード上の他のネットワークと重複しない、専用のサブネットに接続する必要があります。

導入時に、 Grid Manager によって次の制限事項が適用されます。これらの情報は、導入前のネットワーク計画に役立ちます。

* ネットワークIPアドレスのサブネットマスクを255.255.255.254または255.255.255.255（CIDR表記では/31または/32）にすることはできません。
* ネットワークインターフェイスのIPアドレスとサブネットマスク（CIDR）によって定義されたサブネットは、同じノードに設定されている他のインターフェイスのサブネットと重複することはできません。
* どのノードのグリッド ネットワーク、管理ネットワーク、またはクライアント ネットワークにも、次の IPv4 アドレスを含むサブネットを使用しないでください。
+
** 192,168,130,101
** 192,168,131,101
** 192,168,130,102
** 192,168,131,102
** 198.51.100.2
** 198.51.100.4


+
たとえば、どのノードのグリッド ネットワーク、管理ネットワーク、またはクライアント ネットワークにも次のサブネット範囲を使用しないでください。

+
** 192.168.130.0/24 は、このサブネット範囲に IP アドレス 192.168.130.101 と 192.168.130.102 が含まれているためです。
** 192.168.131.0/24 は、このサブネット範囲に IP アドレス 192.168.131.101 と 192.168.131.102 が含まれているためです。
** 198.51.100.0/24 は、このサブネット範囲に IP アドレス 198.51.100.2 と 198.51.100.4 が含まれているためです。


* 各ノードのグリッドネットワークサブネットを GNSL に含める必要があります。
* 管理ネットワークサブネットは、グリッドネットワークサブネット、クライアントネットワークサブネット、またはGNSLのサブネットと重複することはできません。
* AESL内のサブネットは、GNSL内のどのサブネットとも重複できません。
* クライアントネットワークサブネットは、グリッドネットワークサブネット、管理ネットワークサブネット、GNSLのサブネット、またはAESLのサブネットと重複することはできません。

