= ノード構成ファイルの場所
:allow-uri-read: 




== ノード構成ファイルの場所

各StorageGRIDノードの構成ファイルを、そのノードを実行するホストのディレクトリに配置し `/etc/storagegrid/nodes`ます。たとえば、HostAで管理ノード、ゲートウェイノード、およびストレージノードを1つずつ実行する場合は、3つのノード構成ファイルをHostAのに配置する必要があります `/etc/storagegrid/nodes`。

構成ファイルは、 vim や nano などのテキストエディタを使用して各ホストで直接作成することも、別の場所で作成して各ホストに移動することもできます。



== ノード構成ファイルの命名

構成ファイルの名前は、の形式はです `node-name.conf`。はノードに割り当てる名前です。 `node-name`この名前は StorageGRID インストーラに表示され、ノード移行などのノードのメンテナンス処理で使用されます。

ノード名は次のルールに従って付ける必要があります。

* 一意でなければなりません
* 1 文字目はアルファベットにする必要があります
* A~Z と a~z のアルファベットを使用できます
* 0~9 の数字を使用できます
* 1 つまたは複数のハイフン（ - ）を含めることができます。
* 拡張子は含めず、32文字以下にする必要があります。 `.conf`


これらの命名規則に従わない内のファイルは、 `/etc/storagegrid/nodes`ホストサービスによって解析されません。

グリッドでマルチサイトトポロジを使用する場合の一般的なノード名は次のようになります。

`site-nodetype-nodenumber.conf`

たとえば、データセンター1の最初の管理ノードにを使用し、 `dc2-sn3.conf`データセンター2の3番目のストレージノードにを使用できます `dc1-adm1.conf`。ただし、すべてのノード名がルールに従っていれば、別の名前にしてもかまいません。



== ノード構成ファイルの内容

構成ファイルには、1行に1つのキーと1つの値を持つキーと値のペアが含まれています。キーと値のペアごとに、次のルールに従ってください。

* キーと値は等号で区切る必要があり(`=`ます）、およびオプションの空白文字で区切る必要があります。
* キーにスペースを含めることはできません。
* 値にはスペースを含めることができます。
* 先頭または末尾の空白は無視されます。


次の表に、サポートされているすべてのキーの値を示します。各キーには、次のいずれかの指定があります。

* *必須*：すべてのノードまたは指定したノードタイプに必須
* *ベストプラクティス*：オプション（推奨されますが）
* *オプション*：すべてのノードでオプション




=== 管理ネットワークキー



==== ADMIN_IP を指定します

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
このノードが属するグリッドのプライマリ管理ノードのグリッドネットワークの IPv4 アドレス。GRID_NETWORK_IP で指定した値を Node_type=VM_Admin_Node および ADMIN_NETWORK_role = Primary のグリッドノードに使用します。このパラメータを省略すると、 mDNS を使用してプライマリ管理ノードの検出が試行されます。

link:how-grid-nodes-discover-primary-admin-node.html["グリッドノードによるプライマリ管理ノードの検出"]

* 注 * ：この値は無視されます。また、プライマリ管理ノードでは禁止される場合があります。
 a| 
ベストプラクティス

|===


==== ADMIN_NETWORK_CONFIG

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
DHCP 、 STATIC 、または DISABLED
 a| 
オプション

|===


==== ADMIN_NETWORK_ESL

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
このノードが管理ネットワークゲートウェイを使用して通信するサブネット（CIDR表記）をカンマで区切ったリスト。

例： `172.16.0.0/21,172.17.0.0/21`
 a| 
オプション

|===


==== ADMIN_NETWORK_GATEWAY

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
このノードのローカルの管理ネットワークゲートウェイの IPv4 アドレス。ADMIN_NETWORK_IP および ADMIN_NETWORK_MASK で定義されるサブネットに属している必要があります。この値は、 DHCP によって設定されたネットワークでは無視されます。

例：

`1.1.1.1`

`10.224.4.81`
 a| 
を指定した場合は必須 `ADMIN_NETWORK_ESL`です。それ以外の場合はオプション。

|===


==== ADMIN_NETWORK_IP

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
このノードの管理ネットワークにおける IPv4 アドレス。このキーが必要なのは、ADMIN_NETWORK_CONFIG = STATICの場合だけです。それ以外の値の場合は指定しないでください。

例：

`1.1.1.1`

`10.224.4.81`
 a| 
ADMIN_NETWORK_CONFIG = STATICの場合に必要です。

それ以外の場合はオプション。

|===


==== ADMIN_NETWORK_MAC

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
コンテナ内の管理ネットワークインターフェイスの MAC アドレス。

このフィールドはオプションです。省略すると、 MAC アドレスが自動的に生成されます。

6 つの 16 進数値をコロンで区切って指定する必要があります。

例： `b2:9c:02:c2:27:10`
 a| 
オプション

|===


==== ADMIN_NETWORK_MASK

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
このノードの管理ネットワークにおける IPv4 ネットマスク。ADMIN_NETWORK_CONFIG = STATICの場合はこのキーを指定します。それ以外の値の場合は指定しないでください。

例：

`255.255.255.0`

`255.255.248.0`
 a| 
ADMIN_NETWORK_IPを指定し、ADMIN_NETWORK_CONFIG = STATICの場合は必須です。

それ以外の場合はオプション。

|===


==== ADMIN_NETWORK_MTU を指定します

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
このノードの管理ネットワークでの最大伝送ユニット（ MTU ）。ADMIN_NETWORK_CONFIG = DHCPの場合は指定しないでください。この値を指定する場合、 1280 ～ 9216 の範囲で指定する必要があります。省略すると、 1500 が使用されます。

ジャンボフレームを使用する場合は、 MTU を 9000 などのジャンボフレームに適した値に設定します。それ以外の場合は、デフォルト値のままにします。

* 重要 * ：ネットワークの MTU 値は、ノードが接続されているスイッチポートに設定された値と一致する必要があります。そうしないと、ネットワークパフォーマンスの問題やパケット損失が発生する可能性があります。

例：

`1500`

`8192`
 a| 
オプション

|===


==== ADMIN_NETWORK_TARGET

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
StorageGRID ノードで管理ネットワークのアクセスに使用するホストデバイスの名前。ネットワークインターフェイス名のみがサポートされています。通常、 GRID_NETWORK_TARGET または CLIENT_NETWORK _TARGET に指定したインターフェイス名とは別のインターフェイス名を使用します。

*注*：ボンドデバイスやブリッジデバイスをネットワークターゲットとして使用しないでください。ボンドデバイスの上に VLAN （または他の仮想インターフェイス）を設定するか、ブリッジと仮想イーサネット（ veth ）のペアを使用します。

* ベストプラクティス * ：管理ネットワークの IP アドレスは、このノードで最初は使用しない場合でも値を指定します。そうすることで、ホストでノードの設定を再度行わなくても、管理ネットワークの IP アドレスをあとから追加することができます。

例：

`bond0.1002`

`ens256`
 a| 
ベストプラクティス

|===


==== ADMIN_NETWORK_TARGET タイプ

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
interface（サポートされている値はこれだけです）
 a| 
オプション

|===


==== ADMIN_NETWORK_TARGET _TYPE_interface_clone_MAC

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
正しいか間違っているか

StorageGRID コンテナで管理ネットワークのホストターゲットインターフェイスの MAC アドレスを使用するには、キーを「 true 」に設定して原因 に設定します。

* ベストプラクティス：プロミスキャスモードが必要なネットワークでは、「 ADMIN_NETWORK_TARGET_TYPE_interface_clone_MAC 」キーを使用してください。

MAC クローニングの詳細については、次の URL を参照してください

* link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MACアドレスのクローニングに関する考慮事項と推奨事項（Red Hat Enterprise Linux）"]
* link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC アドレスのクローニングに関する考慮事項と推奨事項（ Ubuntu または Debian ）"]

 a| 
ベストプラクティス

|===


==== ADMIN_NETWORK_ROLE

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
プライマリまたは非プライマリ

このキーが必要なのは、NODE_TYPE = VM_ADMIN_Nodeの場合のみです。それ以外のタイプのノードの場合は指定しないでください。
 a| 
NODE_TYPE = VM_Admin_Nodeの場合は必須

それ以外の場合はオプション。

|===


=== ブロックデバイスキー



==== BLOBK_DEVICE_AUDIT_logs

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
このノードで監査ログの永続的なストレージに使用するブロックデバイススペシャルファイルのパスと名前。

例：

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-audit-logs`
 a| 
NODE_TYPE = VM_Admin_Nodeのノードに必要です。他のノードタイプの場合は指定しないでください。

|===


==== block_device_rangedb_nnn

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
このノードでオブジェクトの永続的なストレージに使用するブロックデバイススペシャルファイルのパスと名前。このキーが必要なのは、NODE_TYPE = VM_Storage_Nodeのノードだけです。それ以外のタイプのノードの場合は指定しないでください。

BLOCK_DEVICE_RANGEDB_000のみが必須で、それ以外は省略可能です。BLOCK_DEVICE_RANGEDB_000に指定するブロックデバイスは4TB以上である必要があります。それ以外は4TB未満でもかまいません。

隙間を空けてはいけません。BLOCK_DEVICE_RANGEDB_005を指定する場合は、BLOCK_DEVICE_RANGEDB_004も指定されている必要があります。

* 注 * ：既存の環境との互換性を確保するため、アップグレードされたノードでは 2 桁のキーがサポートされています。

例：

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-rangedb-000`
 a| 
必須：

BLOCK_DEVICE_RANGEDB_000

オプション：

BLOCK_DEVICE_RANGEDB_001

BLOCK_DEVICE_RANGEDB_002

BLOCK_DEVICE_RANGEDB_003

BLOCK_DEVICE_RANGEDB_004

BLOCK_DEVICE_RANGEDB_005

BLOCK_DEVICE_RANGEDB_006

BLOCK_DEVICE_RANGEDB_007

BLOCK_DEVICE_RANGEDB_008

BLOCK_DEVICE_RANGEDB_009

BLOCK_DEVICE_RANGEDB_010

BLOCK_DEVICE_RANGEDB_011

BLOCK_DEVICE_RANGEDB_012

BLOCK_DEVICE_RANGEDB_013

BLOCK_DEVICE_RANGEDB_014

BLOCK_DEVICE_RANGEDB_015

|===


==== BLOBK_DEVICE_tables

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
このノードでデータベーステーブルの永続的なストレージに使用するブロックデバイススペシャルファイルのパスと名前。このキーが必要なのは、NODE_TYPE = VM_ADMIN_Nodeのノードだけです。それ以外のタイプのノードの場合は指定しないでください。

例：

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-tables`
 a| 
必須

|===


==== BLOBK_DEVICE_VAR_LOCAL です

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
このノードの永続的ストレージに使用するブロックデバイススペシャルファイルのパスと名前 `/var/local`。

例：

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-var-local`
 a| 
必須

|===


=== クライアントネットワークキー



==== CLIENT_NETWORK_CONFIG

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
DHCP 、 STATIC 、または DISABLED
 a| 
オプション

|===


==== CLIENT_NETWORK_GATEWAY

[cols="4a,2a"]
|===


 a| 
値
 a| 
名称



 a| 
このノードのローカルのクライアントネットワークゲートウェイの IPv4 アドレス。 CLIENT_NETWORK_IP および CLIENT_NETWORK_MASK で定義されるサブネットに属している必要があります。この値は、 DHCP によって設定されたネットワークでは無視されます。

例：

`1.1.1.1`

`10.224.4.81`
 a| 
オプション

|===


==== CLIENT_NETWORK_IP

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
このノードのクライアントネットワークにおける IPv4 アドレス。

このキーが必要なのは、CLIENT_NETWORK_CONFIG = STATICの場合だけです。それ以外の値の場合は指定しないでください。

例：

`1.1.1.1`

`10.224.4.81`
 a| 
client_network_config = staticの場合に必要

それ以外の場合はオプション。

|===


==== CLIENT_NETWORK_MAC

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
コンテナ内のクライアントネットワークインターフェイスの MAC アドレス。

このフィールドはオプションです。省略すると、 MAC アドレスが自動的に生成されます。

6 つの 16 進数値をコロンで区切って指定する必要があります。

例： `b2:9c:02:c2:27:20`
 a| 
オプション

|===


==== CLIENT_NETWORK_MASK

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
このノードのクライアントネットワークにおける IPv4 ネットマスク。

CLIENT_NETWORK_CONFIG = STATICの場合にこのキーを指定します。他の値の場合は指定しないでください。

例：

`255.255.255.0`

`255.255.248.0`
 a| 
CLIENT_NETWORK_IPを指定し、CLIENT_NETWORK_CONFIG = STATICの場合は必須

それ以外の場合はオプション。

|===


==== CLIENT_NETWORK_MTU

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
このノードのクライアントネットワークでの最大伝送ユニット（ MTU ）。CLIENT_NETWORK_CONFIG = DHCPの場合は指定しないでください。この値を指定する場合、 1280 ～ 9216 の範囲で指定する必要があります。省略すると、 1500 が使用されます。

ジャンボフレームを使用する場合は、 MTU を 9000 などのジャンボフレームに適した値に設定します。それ以外の場合は、デフォルト値のままにします。

* 重要 * ：ネットワークの MTU 値は、ノードが接続されているスイッチポートに設定された値と一致する必要があります。そうしないと、ネットワークパフォーマンスの問題やパケット損失が発生する可能性があります。

例：

`1500`

`8192`
 a| 
オプション

|===


==== client_network_target です

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
StorageGRID ノードでクライアントネットワークのアクセスに使用するホストデバイスの名前。ネットワークインターフェイス名のみがサポートされています。通常、 GRID_NETWORK_TARGET または ADMIN_NETWORK_TARGET に指定したインターフェイス名とは別のインターフェイス名を使用します。

*注*：ボンドデバイスやブリッジデバイスをネットワークターゲットとして使用しないでください。ボンドデバイスの上に VLAN （または他の仮想インターフェイス）を設定するか、ブリッジと仮想イーサネット（ veth ）のペアを使用します。

* ベストプラクティス： * クライアントネットワークの IP アドレスは、このノードで最初は使用しない場合でも値を指定してください。そうすることで、ホストでノードの設定を再度行わなくても、クライアントネットワークの IP アドレスをあとから追加することができます。

例：

`bond0.1003`

`ens423`
 a| 
ベストプラクティス

|===


==== client_network_target_type

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
interface（サポートされている値のみ）
 a| 
オプション

|===


==== client_network_target_type _interface_clone_MAC

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
正しいか間違っているか

クライアントネットワークでホストターゲットインターフェイスの MAC アドレスを使用するには、キーを「 true 」に設定して StorageGRID コンテナを原因 します。

* ベストプラクティス：プロミスキャスモードが必要なネットワークでは、 client_network_target_type _interface_clone_MAC キーを使用してください。

MAC クローニングの詳細については、次の URL を参照してください

* link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MACアドレスのクローニングに関する考慮事項と推奨事項（Red Hat Enterprise Linux）"]
* link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC アドレスのクローニングに関する考慮事項と推奨事項（ Ubuntu または Debian ）"]

 a| 
ベストプラクティス

|===


=== グリッドネットワークキー



==== GRID_NETWORK_CONFIG

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
STATIC または DHCP

指定しない場合のデフォルトはstaticです。
 a| 
ベストプラクティス

|===


==== GRID_NETWORK_GATEWAY

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
このノードのローカルのグリッドネットワークゲートウェイの IPv4 アドレス。 GRID_NETWORK_IP および GRID_NETWORK_MASK で定義されるサブネットに属している必要があります。この値は、 DHCP によって設定されたネットワークでは無視されます。

グリッドネットワークのサブネットが 1 つだけでゲートウェイがない場合は、サブネットの標準のゲートウェイアドレス（ X.Y.Z.1 ）か、このノードの GRID_NETWORK_IP の値を使用します。このどちらかの値にしておけば、以降にグリッドネットワークを拡張するときに処理が簡単になります。
 a| 
必須

|===


==== GRID_NETWORK_IP

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
このノードのグリッドネットワークにおける IPv4 アドレス。このキーが必要なのは、GRID_NETWORK_CONFIG = STATICの場合のみです。それ以外の値の場合は指定しないでください。

例：

`1.1.1.1`

`10.224.4.81`
 a| 
GRID_NETWORK_CONFIG = STATICの場合は必須

それ以外の場合はオプション。

|===


==== GRID_NETWORK_MAC

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
コンテナ内のグリッドネットワークインターフェイスの MAC アドレス。

6 つの 16 進数値をコロンで区切って指定する必要があります。

例： `b2:9c:02:c2:27:30`
 a| 
オプション

省略すると、 MAC アドレスが自動的に生成されます。

|===


==== GRID_NETWORK_MASK

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
このノードのグリッドネットワークにおける IPv4 ネットマスク。GRID_NETWORK_CONFIG = STATICの場合はこのキーを指定します。それ以外の値の場合は指定しないでください。

例：

`255.255.255.0`

`255.255.248.0`
 a| 
GRID_NETWORK_IPを指定し、GRID_NETWORK_CONFIG = STATICを指定した場合に必要です。

それ以外の場合はオプション。

|===


==== GRID_NETWORK_MTU

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
このノードのグリッドネットワークでの最大伝送ユニット（ MTU ）。GRID_NETWORK_CONFIG = DHCPの場合は指定しないでください。この値を指定する場合、 1280 ～ 9216 の範囲で指定する必要があります。省略すると、 1500 が使用されます。

ジャンボフレームを使用する場合は、 MTU を 9000 などのジャンボフレームに適した値に設定します。それ以外の場合は、デフォルト値のままにします。

* 重要 * ：ネットワークの MTU 値は、ノードが接続されているスイッチポートに設定された値と一致する必要があります。そうしないと、ネットワークパフォーマンスの問題やパケット損失が発生する可能性があります。

* 重要 * ：ネットワークパフォーマンスを最大限に高めるには、すべてのノードのグリッドネットワークインターフェイスで MTU 値がほぼ同じになるように設定する必要があります。個々のノードのグリッドネットワークの MTU 設定に大きな違いがある場合は、 * Grid Network MTU mismatch * アラートがトリガーされます。MTU値はすべてのネットワークタイプで同じである必要はありません。

例：

`1500`

`8192`
 a| 
オプション

|===


==== GRID_NETWORK_TARGET

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
StorageGRID ノードでグリッドネットワークのアクセスに使用するホストデバイスの名前。ネットワークインターフェイス名のみがサポートされています。通常、 ADMIN_NETWORK_TARGET または ADMIN_NETWORK_TARGET に指定したインターフェイス名とは別のインターフェイス名を使用します。

*注*：ボンドデバイスやブリッジデバイスをネットワークターゲットとして使用しないでください。ボンドデバイスの上に VLAN （または他の仮想インターフェイス）を設定するか、ブリッジと仮想イーサネット（ veth ）のペアを使用します。

例：

`bond0.1001`

`ens192`
 a| 
必須

|===


==== GRID_NETWORK_TARGET タイプ

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
interface（サポートされている値はこれだけです）
 a| 
オプション

|===


==== GRID_NETWORK_TARGET _TYPE_interface_clone_MAC

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
正しいか間違っているか

グリッドネットワーク上のホストターゲットインターフェイスの MAC アドレスを使用するには、キーの値を「 true 」に設定して StorageGRID コンテナを原因 に設定します。

* ベストプラクティス：プロミスキャスモードが必要なネットワークでは、 GRID_NETWORK_TARGET _TYPE_interface_clone_MAC キーを使用してください。

MAC クローニングの詳細については、次の URL を参照してください

* link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MACアドレスのクローニングに関する考慮事項と推奨事項（Red Hat Enterprise Linux）"]
* link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC アドレスのクローニングに関する考慮事項と推奨事項（ Ubuntu または Debian ）"]

 a| 
ベストプラクティス

|===


=== インストールパスワードキー（一時）



==== custom_temporary_password_hash

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
プライマリ管理ノードの場合は、インストール時にStorageGRIDインストールAPIのデフォルトの一時パスワードを設定します。

*注*：インストールパスワードはプライマリ管理ノードにのみ設定します。別のタイプのノードでパスワードを設定しようとすると、ノード構成ファイルの検証に失敗します。

この値を設定しても、インストールが完了しても効果はありません。

このキーを省略すると、デフォルトでは一時パスワードは設定されません。または、StorageGRIDインストールAPIを使用して一時パスワードを設定することもできます。

8文字以上32文字以下のパスワードの形式のSHA-512パスワードハッシュで `$6$<salt>$<password hash>`ある必要があります `crypt()`。

このハッシュは、SHA-512モードのコマンドなどのCLIツールを使用して生成できます `openssl passwd`。
 a| 
ベストプラクティス

|===


=== interfacesキー



==== interface_target_nnnn

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
このノードに追加するインターフェイスの名前とオプションの概要 。各ノードに複数のインターフェイスを追加できます。

_nnnn_には、追加する各interface_targetエントリに一意の番号を指定します。

値には、ベアメタルホスト上の物理インターフェイスの名前を指定します。その後、必要に応じて、カンマを追加してインターフェイスの概要 を指定します。このインターフェイスは、 VLAN インターフェイスのページと HA グループのページに表示されます。

例： `INTERFACE_TARGET_0001=ens256, Trunk`

トランクインターフェイスを追加する場合は、 StorageGRID で VLAN インターフェイスを設定する必要があります。アクセスインターフェイスを追加する場合は、そのインターフェイスをHAグループに直接追加できます。VLANインターフェイスを設定する必要はありません。
 a| 
オプション

|===


=== 最大RAMキー



==== MAXIMUM_RAM

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
このノードに使用を許可する RAM の最大容量。このキーを省略した場合、ノードでメモリは制限されません。本番用のノードについて設定するときは、システム RAM の合計容量よりも 24GB 以上、 16~32GB 以上小さい値を指定してください。

* 注 * ： RAM 値は、ノードの実際のメタデータ用リザーブスペースに影響します。を参照してくださいlink:../admin/managing-object-metadata-storage.html["Metadata Reserved Spaceとは何かの概要"]。

このフィールドの形式はです `_numberunit_`。 `_unit_`には、、 `k`、 `m`、または `g`を指定できます `b`。

例：

`24g`

`38654705664b`

* 注：このオプションを使用する場合は、 memory cgroups のカーネルサポートを有効にする必要があります。
 a| 
オプション

|===


=== ノードタイプキー



==== Node_type のように指定します

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
ノードのタイプ：

* VM_Admin_Nodeの略
* VM_Storage_Nodeの略
* VM_Archive_Nodeの略
* VM_API_Gateway

 a| 
必須

|===


==== ストレージタイプ

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
ストレージノードに含まれるオブジェクトのタイプを定義。詳細については、を参照してください link:../primer/what-storage-node-is.html#types-of-storage-nodes["ストレージノードのタイプ"]。このキーが必要なのは、NODE_TYPE = VM_Storage_Nodeのノードだけです。それ以外のタイプのノードの場合は指定しないでください。ストレージタイプ：

* 組み合わせ（ Combined ）
* データ
* メタデータ


*注*：storage_typeを指定しない場合、ストレージノードタイプはデフォルトで組み合わせ（データとメタデータ）に設定されます。
 a| 
オプション

|===


=== ポートの再マッピングキー



==== PORT_REMAP を参照してください

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
ノードが内部でのグリッドノードの通信または外部との通信に使用するポートを再マッピングします。ポートの再マッピングが必要になるのは、またはの説明に従って、StorageGRIDで使用される1つ以上のポートがエンタープライズネットワークポリシーによって制限されている場合です。link:../network/internal-grid-node-communications.html["内部でのグリッドノードの通信"]link:../network/external-communications.html["外部との通信"]

*重要*：ロードバランサエンドポイントの設定に使用する予定のポートを再マッピングしないでください。

* 注： PORT_REMAP のみを設定すると、指定したマッピングがインバウンド通信とアウトバウンド通信の両方に使用されます。PORT_REMAP_INBOUND を併せて指定した場合は、 PORT_REMAP がアウトバウンド通信のみに適用されます。

使用される形式は、 `_network type_/_protocol_/_default port used by grid node_/_new port_`です。 `_network type_`はgrid、admin、またはclient、 `_protocol_`はtcpまたはudpです。

例： `PORT_REMAP = client/tcp/18082/443`

カンマで区切ったリストを使用して複数のポートを再マッピングすることもできます。

例： `PORT_REMAP = client/tcp/18082/443, client/tcp/18083/80`
 a| 
オプション

|===


==== PORT_REMAP_INBOUND

[cols="4a,2a"]
|===
| 値 | 名称 


 a| 
指定したポートのインバウンド通信を再マッピングします。PORT_REMAP_INBOUNDを指定し、PORT_REMAPに値を指定しなかった場合、ポートのアウトバウンド通信は変更されません。

*重要*：ロードバランサエンドポイントの設定に使用する予定のポートを再マッピングしないでください。

使用される形式は、 `_network type_/_protocol_/_remapped port_/_default port used by grid node_`です。 `_network type_`はgrid、admin、またはclient、 `_protocol_`はtcpまたはudpです。

例： `PORT_REMAP_INBOUND = grid/tcp/3022/22`

カンマで区切った複数のインバウンドポートを再マッピングすることもできます。

例： `PORT_REMAP_INBOUND = grid/tcp/3022/22, admin/tcp/3022/22`
 a| 
オプション

|===