= 
:allow-uri-read: 


[role="tabbed-block"]
====
.レプリケートデータ
--
* レプリケートされた修復の完了率を推定するには、repair-dataコマンドにオプションを追加し `show-replicated-repair-status`ます。
+
`repair-data show-replicated-repair-status`

* 修理が完了しているかどうかを確認するには、次
+
.. ノードを選択 * > * _ 修復中のストレージノード _ * > * ILM * を選択します。
.. 「評価」セクションの属性を確認します。修理が完了すると、 *Awaiting - All * 属性は 0 個のオブジェクトを示します。


* 修理を詳細に監視するには、次の手順を実行します。
+
.. [* nodes （ノード） ] を選択します
.. *_grid name_*>*ilm * を選択します。
.. ILMキューのグラフにカーソルを合わせて、* Scan rate（objects/sec）*属性の値を確認します。これは、グリッド内のオブジェクトがスキャンされてILMのキューに登録される速度です。
.. [ILM Queue]セクションで、次の属性を確認します。
+
*** * Scan Period - Estimated *：ILMによるすべてのオブジェクトのフルスキャンが完了するまでの推定時間。
+
フルスキャンを実行しても、ILMがすべてのオブジェクトに適用されたことが保証されるわけではありません。

*** * Repairs Attempted *：レプリケートデータに対して試行されたオブジェクト修復処理の総数。この数は、ストレージノードがハイリスクオブジェクトの修復を試みるたびに増分します。グリッドがビジー状態になった場合は、リスクの高い ILM の修復が優先されます。
+
修復後にレプリケーションに失敗した場合は、同じオブジェクトの修復で再び増分される可能性があります。+これらの属性は、ストレージノードのボリュームリカバリの進捗状況を監視する場合に役立ちます。修復の試行回数が増えなくなり、フルスキャンが完了している場合は、修復が完了している可能性があります。



.. または、との `storagegrid_ilm_repairs_attempted`Prometheusクエリを送信します `storagegrid_ilm_scan_period_estimated_minutes`。




--
.イレイジャーコーディング（EC）データ
--
イレイジャーコーディングデータの修復を監視し、失敗した可能性のある要求を再試行するには、次の手順を実行します。

. イレイジャーコーディングデータの修復ステータスを確認します。
+
** サポート * > * Tools * > * Metrics * を選択して、現在のジョブの完了までの推定時間と完了率を表示します。次に、 Grafana のセクションで * EC Overview * を選択します。グリッド EC ジョブの完了予想時間 * ダッシュボードと * グリッド EC ジョブの完了率 * ダッシュボードを確認します。
** 特定の処理のステータスを表示するには、次のコマンドを使用し `repair-data`ます。
+
`repair-data show-ec-repair-status --repair-id repair ID`

** すべての修復処理を表示するには、次のコマンドを使用します
+
`repair-data show-ec-repair-status`

+
出力には、以前に実行されていた修復と現在実行中の修復の情報などが表示され `repair ID`ます。



. 失敗した修復処理が出力された場合は、オプションを使用し `--repair-id`て修復を再試行します。
+
次のコマンドは、修復ID 6949309319275667690を使用して、障害が発生したノードの修復を再試行します。

+
`repair-data start-ec-node-repair --repair-id 6949309319275667690`

+
次のコマンドは、修復ID 6949309319275667690を使用して、障害が発生したボリュームの修復を再試行します。

+
`repair-data start-ec-volume-repair --repair-id 6949309319275667690`



--
====