= ストレージノードのホスト名を探します
:allow-uri-read: 




== ストレージノードのホスト名を探します

. プライマリ管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_primary_Admin_Node_IP_`
.. ファイルに記載されているパスワードを入力し `Passwords.txt`ます。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. ファイルに記載されているパスワードを入力し `Passwords.txt`ます。
+
rootとしてログインすると、プロンプトがからに `#`変わります `$`。



. ファイルを使用して `/etc/hosts`、リストアしたストレージボリュームのストレージノードのホスト名を確認します。グリッド内のすべてのノードのリストを表示するには、次のコマンドを入力します。 `cat /etc/hosts`




== すべてのボリュームで障害が発生した場合はデータを修復します

すべてのストレージボリュームで障害が発生した場合は、ノード全体を修復します。レプリケートデータ、イレイジャーコーディング（ EC ）データ、またはその両方を使用するかどうかに応じて、 * レプリケートデータ * 、 * イレイジャーコーディング（ EC ）データ * 、またはその両方の手順を実行します。

一部のボリュームだけで障害が発生した場合は、に進みます<<一部のボリュームのみで障害が発生した場合はデータを修復します>>。


NOTE: 複数のノードに対して同時に処理を実行することはできません `repair-data`。複数のノードをリカバリする場合は、テクニカルサポートにお問い合わせください。

[role="tabbed-block"]
====
.レプリケートデータ
--
グリッドにレプリケートデータが含まれている場合は、コマンドにオプションを指定して `--nodes`使用し `repair-data start-replicated-node-repair`、ストレージノード全体を修復します。 `--nodes`はホスト名（システム名）です。

次のコマンドは、 SG-DC-SN3 というストレージノードにあるレプリケートデータを修復します。

`repair-data start-replicated-node-repair --nodes SG-DC-SN3`


NOTE: オブジェクトデータのリストア時に、StorageGRID システムがレプリケートされたオブジェクトデータを見つけられない場合は、* Objects lost *アラートがトリガーされます。システム全体のストレージノードでアラートがトリガーされることがあります。損失の原因 と、リカバリが可能かどうかを確認する必要があります。を参照して link:../troubleshoot/investigating-lost-objects.html["損失オブジェクトを調査する"]

--
.イレイジャーコーディング（EC）データ
--
グリッドにイレイジャーコーディングデータがある場合は、コマンドでオプションを指定して `--nodes`使用し `repair-data start-ec-node-repair`、ストレージノード全体を修復します。 `--nodes`はホスト名（システム名）です。

次のコマンドは、 SG-DC-SN3 というストレージノードにあるイレイジャーコーディングデータを修復します。

`repair-data start-ec-node-repair --nodes SG-DC-SN3`

この処理を識別する `repair_data`一意のが返され `repair ID`ます。処理の進捗状況と結果を追跡する場合に `repair_data`使用し `repair ID`ます。リカバリプロセスが完了しても、それ以外のフィードバックは返されません。

イレイジャーコーディングデータの修復は、一部のストレージノードがオフライン状態で開始できます。修復はすべてのノードが使用可能になったあとに完了します。

--
====


== 一部のボリュームのみで障害が発生した場合はデータを修復します

一部のボリュームだけで障害が発生した場合は、影響を受けたボリュームを修復します。レプリケートデータ、イレイジャーコーディング（ EC ）データ、またはその両方を使用するかどうかに応じて、 * レプリケートデータ * 、 * イレイジャーコーディング（ EC ）データ * 、またはその両方の手順を実行します。

すべてのボリュームで障害が発生した場合は、に進みます<<すべてのボリュームで障害が発生した場合はデータを修復します>>。

ボリューム ID を 16 進数で入力します。たとえば、 `0000`は最初のボリューム、 `000F`は16番目のボリュームです。1つのボリューム、一連のボリューム、または連続していない複数のボリュームを指定できます。

すべてのボリュームが同じストレージノードにある必要があります。複数のストレージノードのボリュームをリストアする必要がある場合は、テクニカルサポートにお問い合わせください。

[role="tabbed-block"]
====
.レプリケートデータ
--
グリッドにレプリケートデータがある場合は、 `start-replicated-volume-repair`コマンドでオプションを指定し `--nodes`てノードを特定します（ `--nodes`はノードのホスト名）。次に、次の例に示すように、または `--volume-range`オプションを追加し `--volumes`ます。

*単一ボリューム*：このコマンドは、SG-DC-SN3というストレージノード上のボリュームにレプリケートデータをリストアし `0002`ます。

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volumes 0002`

*ボリュームの範囲*：このコマンドは、SG-DC-SN3というストレージノードのに `0009`含まれるすべてのボリュームにレプリケートデータをリストアし `0003`ます。

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volume-range 0003,0009`

*複数のボリュームが連続していません*：このコマンドは、レプリケートされたデータをボリューム、および `0005` `0008`SG-DC-SN3というストレージノードにリストアし `0001`ます。

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volumes 0001,0005,0008`


NOTE: オブジェクトデータのリストア時に、StorageGRID システムがレプリケートされたオブジェクトデータを見つけられない場合は、* Objects lost *アラートがトリガーされます。システム全体のストレージノードでアラートがトリガーされることがあります。アラートの概要 と推奨される対処方法をメモして、損失の原因 を特定し、リカバリが可能かどうかを判断します。

--
.イレイジャーコーディング（EC）データ
--
グリッドにイレイジャーコーディングデータがある場合は、コマンドにオプションを指定し `--nodes`て実行し `start-ec-volume-repair`ます（ `--nodes`はノードのホスト名）。次に、次の例に示すように、または `--volume-range`オプションを追加し `--volumes`ます。

*単一ボリューム*：このコマンドは、SG-DC-SN3というストレージノードのボリュームにイレイジャーコーディングデータをリストアし `0007`ます。

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volumes 0007`

*ボリュームの範囲*：このコマンドは、 `0006`SG-DC-SN3というストレージノードの範囲内のすべてのボリュームにイレイジャーコーディングデータをリストアします `0004`。

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volume-range 0004,0006`

*複数のボリュームが連続していません*：このコマンドは、イレイジャーコーディングデータをボリューム、および `000C` `000E`SG-DC-SN3というストレージノードにリストアし `000A`ます。

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volumes 000A,000C,000E`

 `repair-data`この処理を識別する `repair_data`一意のが返され `repair ID`ます。処理の進捗状況と結果を追跡する場合に `repair_data`使用し `repair ID`ます。リカバリプロセスが完了しても、それ以外のフィードバックは返されません。


NOTE: イレイジャーコーディングデータの修復は、一部のストレージノードがオフライン状態で開始できます。修復はすべてのノードが使用可能になったあとに完了します。

--
====