= S3 オブジェクトのロックとは何ですか？
:allow-uri-read: 




== S3 オブジェクトのロックとは何ですか？

StorageGRID S3 オブジェクトロック機能は、 Amazon Simple Storage Service （ Amazon S3 ）での S3 オブジェクトロックに相当するオブジェクト保護解決策 です。

StorageGRIDシステムでS3オブジェクトロックのグローバル設定が有効になっている場合、S3テナントアカウントはS3オブジェクトロックを有効にしても有効にしなくてもバケットを作成できます。バケットでS3オブジェクトロックが有効になっている場合は、バケットのバージョン管理が必要であり、自動的に有効になります。

* S3オブジェクトロック*が設定されていないバケットには、保持設定が指定されていないオブジェクトのみを含めることができます。保持設定は取り込まれたオブジェクトには適用されません。

* S3 Object Lock *が設定されたバケットには、S3クライアントアプリケーションで保持設定の有無に関係なくオブジェクトを含めることができます。取り込まれた一部のオブジェクトには保持設定が設定されます。

* S3オブジェクトロックでデフォルトの保持が設定されたバケット*では、保持設定を指定したオブジェクトをアップロードし、保持設定を指定せずに新しいオブジェクトをアップロードできます。保持設定がオブジェクトレベルで設定されていないため、新しいオブジェクトではデフォルト設定が使用されます。

デフォルトの保持が設定されている場合、新しく取り込まれたすべてのオブジェクトに保持設定が適用されます。オブジェクト保持設定のない既存のオブジェクトは影響を受けません。



=== 保持モード

StorageGRID S3オブジェクトロック機能は、2つの保持モードをサポートしており、さまざまなレベルの保護をオブジェクトに適用できます。これらのモードは、Amazon S3の保持モードに相当します。

* コンプライアンスモードの場合：
+
** retain-until-dateに達するまで、オブジェクトを削除できません。
** オブジェクトのretain-until-dateは増やすことはできますが、減らすことはできません。
** オブジェクトのretain-until-dateは、その日付に達するまで削除できません。


* ガバナンスモードの場合：
+
** 特別な権限を持つユーザは、要求でバイパスヘッダーを使用して、特定の保持設定を変更できます。
** これらのユーザは、retain-until-dateに達する前にオブジェクトバージョンを削除できます。
** これらのユーザは、オブジェクトのretain-until-dateを増減、または削除できます。






=== オブジェクトバージョンの保持設定

S3オブジェクトロックを有効にしてバケットを作成した場合、ユーザはS3クライアントアプリケーションを使用して、バケットに追加される各オブジェクトに次の保持設定を必要に応じて指定できます。

* *保持モード*：コンプライアンスまたはガバナンスのいずれか。
* * Retain-until-date *：オブジェクトバージョンのretain-until-dateが将来の日付の場合、オブジェクトは読み出すことはできますが、削除することはできません。
* * リーガルホールド * ：オブジェクトバージョンにリーガルホールドを適用すると、そのオブジェクトがただちにロックされます。たとえば、調査または法的紛争に関連するオブジェクトにリーガルホールドを設定する必要がある場合があります。リーガルホールドには有効期限はありませんが、明示的に削除されるまで保持されます。リーガルホールドは、それまでの保持期間とは関係ありません。
+

NOTE: オブジェクトがリーガルホールドの対象である場合、保持モードに関係なく、誰もオブジェクトを削除できません。

+
オブジェクト設定の詳細については、を参照してくださいlink:../s3/use-s3-api-for-s3-object-lock.html["S3 REST APIを使用してS3オブジェクトロックを設定します"]。





=== バケットのデフォルトの保持設定

S3オブジェクトロックを有効にしてバケットを作成した場合は、必要に応じて次のバケットのデフォルト設定を指定できます。

* *デフォルトの保持モード*：コンプライアンスまたはガバナンスのいずれか。
* *デフォルトの保持期間*：このバケットに追加された新しいオブジェクトバージョンを、追加された日から保持する期間。


デフォルトのバケット設定は、独自の保持設定がない新しいオブジェクトにのみ適用されます。これらのデフォルト設定を追加または変更しても、既存のバケットオブジェクトには影響しません。

およびを参照してくださいlink:../tenant/creating-s3-bucket.html["S3 バケットを作成します。"]link:../tenant/update-default-retention-settings.html["S3オブジェクトロックのデフォルトの保持期間を更新します"]。
