---
permalink: tenant/changing-bucket-versioning.html 
sidebar: sidebar 
keywords: how to change bucket versioning, disabled versioning, enabled versioning, suspended versioning 
summary: S3テナントを使用している場合は、S3バケットのバージョン管理状態を変更できます。 
---
= バケットのオブジェクトのバージョン管理を変更する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3テナントを使用している場合は、S3バケットのバージョン管理状態を変更できます。

.開始する前に
* を使用してTenant Managerにサインインしておきlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]ます。
* が設定されたユーザグループに属しているlink:tenant-management-permissions.html["すべてのバケットまたはRoot Access権限を管理します"]必要があります。これらの権限は、グループまたはバケットポリシーの権限の設定よりも優先されます。
* 必要な数のストレージノードとサイトが使用可能であることを確認しておきます。どのサイトでも複数のストレージノードを使用できない場合やサイトを使用できない場合は、それらの設定を変更できない可能性があります。


.タスクの内容
バケットでオブジェクトのバージョン管理を有効または一時停止することができます。バケットのバージョン管理を有効にすると、バージョン管理されていない状態に戻ることはできません。ただし、バケットのバージョン管理は一時停止できます。

* 無効 : バージョン管理は一度も有効になっていません
* 有効：バージョン管理が有効になっています
* 中断：バージョン管理は以前有効になっていて、中断されています


詳細については、次を参照してください。

* link:../s3/object-versioning.html["オブジェクトのバージョン管理"]
* link:../ilm/example-4-ilm-rules-and-policy-for-s3-versioned-objects.html["S3 バージョン管理オブジェクトの ILM ルールとポリシー（例 4 ）"]
* link:../ilm/how-objects-are-deleted.html["オブジェクトの削除方法"]


.手順
. ダッシュボードで* View Buckets *を選択するか、* storage（S3）*>* Buckets *を選択します。
. 表からバケット名を選択します。
+
バケットの詳細ページが表示されます。

. [Bucket options]*タブで、*[Object versioning]*アコーディオンを選択します。
. このバケット内のオブジェクトのバージョン管理の状態を選択します。
+
グリッド間レプリケーションに使用されるバケットでは、オブジェクトのバージョン管理を有効にしておく必要があります。S3 オブジェクトのロックまたはレガシーのコンプライアンスが有効になっている場合、 * オブジェクトのバージョン管理 * オプションは無効になります。

+
[cols="1a,3a"]
|===
| オプション | 製品説明 


 a| 
バージョン管理を有効にする
 a| 
このバケット内の各オブジェクトのすべてのバージョンを格納する場合は、オブジェクトのバージョン管理を有効にします。そのあと、必要に応じて以前のバージョンのオブジェクトを読み出すことができます。

バケットにすでに含まれていたオブジェクトは、ユーザによる変更時にバージョン管理されます。



 a| 
バージョン管理を一時停止
 a| 
新しいオブジェクトバージョンを作成しない場合は、オブジェクトのバージョン管理を一時停止します。既存のオブジェクトバージョンは引き続き取得できます。

|===
. 「変更を保存」を選択します。

