---
permalink: tenant/configuring-cloudmirror-replication.html 
sidebar: sidebar 
keywords: how to configure CloudMirror replication, replication xml 
summary: バケットのCloudMirrorレプリケーションを有効にするには、バケットのレプリケーション設定XMLを作成し、Tenant Managerを使用してそのXMLをバケットに適用します。 
---
= CloudMirror レプリケーションを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バケットに対してCloudMirrorレプリケーションを有効にするには、有効なバケットレプリケーション設定XMLを作成して適用します。

.開始する前に
* テナントアカウントのプラットフォームサービスがStorageGRID 管理者によって有効にされている。
* レプリケーションソースとして機能するバケットがすでに作成されている。
* CloudMirrorレプリケーションのデスティネーションとして使用するエンドポイントがすでに存在し、そのURNが必要です。
* が設定されたユーザグループに属しているlink:tenant-management-permissions.html["すべてのバケットまたはRoot Access権限を管理します"]必要があります。これらの権限は、 Tenant Manager を使用してバケットを設定する際にグループポリシーまたはバケットポリシーの権限設定よりも優先されます。


.タスクの内容
CloudMirror レプリケーションでは、ソースバケットからエンドポイントで指定されたデスティネーションバケットにオブジェクトがコピーされます。

バケットレプリケーションとその設定方法の一般的な情報については、を参照してください https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication.html["Amazon Simple Storage Service（S3）のドキュメント：「オブジェクトのレプリケート"^]。StorageGRIDでのGetBucketReplication、DeleteBucketReplication、およびPutBucketReplicationの実装方法については、を参照してくださいlink:../s3/operations-on-buckets.html["バケットの処理"]。


NOTE: CloudMirrorレプリケーションには、クロスグリッドレプリケーション機能と重要な類似点と相違点があります。詳細については、を参照してくださいlink:../admin/grid-federation-compare-cgr-to-cloudmirror.html["グリッド間レプリケーションとCloudMirrorレプリケーションを比較してください"]。

CloudMirrorレプリケーションを設定する場合は、次の要件と特性に注意してください。

* 有効なバケットレプリケーション設定XMLを作成して適用する場合は、各デスティネーションにS3バケットエンドポイントのURNを使用する必要があります。
* S3 オブジェクトロックが有効なソースバケットまたはデスティネーションバケットでは、レプリケーションはサポートされません。
* オブジェクトを含むバケットでCloudMirrorレプリケーションを有効にすると、バケットに追加された新しいオブジェクトがレプリケートされますが、バケット内の既存のオブジェクトはレプリケートされません。レプリケーションをトリガーするには、既存のオブジェクトを更新する必要があります。
* レプリケーション設定 XML でストレージクラスを指定した場合は、デスティネーション S3 エンドポイントに対して処理を実行する際に StorageGRID でそのクラスが使用されます。指定したストレージクラスは、デスティネーションエンドポイントでもサポートされている必要があります。デスティネーションシステムのベンダーからの推奨事項がある場合は、それに準拠してください。


.手順
. ソースバケットのレプリケーションを有効にします。
+
** S3 レプリケーション API で指定されているように、レプリケーションを有効にするために必要なレプリケーション設定 XML をテキストエディタで作成します。
** XML を設定する場合は、次の点に
+
*** StorageGRID では、 V1 のレプリケーション設定のみがサポートされます。これは、StorageGRIDがルールに要素を使用することをサポートして `Filter`おらず、オブジェクトバージョンの削除に関するV1の規則に従います。詳細については、レプリケーション設定に関する Amazon のドキュメントを参照してください。
*** デスティネーションとして S3 バケットエンドポイントの URN を使用してください。
*** 必要に応じて要素を追加し `<StorageClass>`、次のいずれかを指定します。
+
****  `STANDARD`：デフォルトのストレージクラス。オブジェクトをアップロードするときにストレージクラスを指定しない場合は、 `STANDARD`ストレージクラスが使用されます。
**** `STANDARD_IA`:(標準-アクセス頻度が低い)アクセス頻度は低いものの、必要に応じて高速アクセスが必要なデータには、このストレージクラスを使用します。
**** `REDUCED_REDUNDANCY`：このストレージクラスは、重要でない、再現可能なデータに使用し、ストレージクラスよりも冗長性が低いデータを格納する場合に使用します `STANDARD`。


*** 設定XMLでを指定すると、 `Role`無視されます。この値は StorageGRID では使用されません。
+
[listing]
----
<ReplicationConfiguration>
    <Role></Role>
    <Rule>
        <Status>Enabled</Status>
        <Prefix>2020</Prefix>
        <Destination>
           <Bucket>urn:sgws:s3:::2017-records</Bucket>
           <StorageClass>STANDARD</StorageClass>
         </Destination>
     </Rule>
</ReplicationConfiguration>
----




. ダッシュボードで* View Buckets *を選択するか、* storage（S3）*>* Buckets *を選択します。
. ソースバケットの名前を選択します。
+
バケットの詳細ページが表示されます。

. プラットフォームサービス * > * レプリケーション * を選択します。
. [レプリケーションを有効にする]*チェックボックスを選択します。
. レプリケーション設定 XML をテキストボックスに貼り付け、 * 変更を保存 * を選択します。
+

NOTE: StorageGRID 管理者がグリッドマネージャまたはグリッド管理 API を使用して各テナントアカウントのプラットフォームサービスを有効にしておく必要があります。設定 XML の保存時にエラーが発生した場合は、 StorageGRID 管理者にお問い合わせください。

. レプリケーションが正しく設定されていることを確認します。
+
.. レプリケーション設定で指定されたレプリケーションの要件を満たすオブジェクトをソースバケットに追加します。
+
前述の例では、プレフィックス「2020」に一致するオブジェクトがレプリケートされます。

.. オブジェクトがデスティネーションバケットにレプリケートされたことを確認します。
+
サイズの小さいオブジェクトについては、レプリケーションの所要時間が短くなります。





.関連情報
link:creating-platform-services-endpoint.html["プラットフォームサービスエンドポイントを作成します"]
