---
permalink: tenant/configuring-cross-origin-resource-sharing-cors.html 
sidebar: sidebar 
keywords: how to configure cross-origin resource sharing, cors 
summary: S3バケットとバケット内のオブジェクトに他のドメインにあるWebアプリケーションからアクセスできるようにするには、そのバケットにCross-Origin Resource Sharing \（CORS\）を設定します。 
---
= Cross-Origin Resource Sharing （ CORS ）の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3バケットとバケット内のオブジェクトに他のドメインにあるWebアプリケーションからアクセスできるようにするには、そのバケットにCross-Origin Resource Sharing（CORS）を設定します。

.開始する前に
* を使用してTenant Managerにサインインしておきlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]ます。
* GET CORS設定要求の場合は、を持つユーザグループに属していlink:tenant-management-permissions.html["Manage All BucketsまたはView All Buckets権限"]ます。これらの権限は、グループまたはバケットポリシーの権限の設定よりも優先されます。
* PUT CORS設定要求の場合、ユーザはを持つユーザグループに属していlink:tenant-management-permissions.html["Manage All Buckets権限"]ます。この権限は、グループポリシーまたはバケットポリシーの権限設定よりも優先されます。
* ではlink:tenant-management-permissions.html["rootアクセス権限"]、すべてのCORS設定要求にアクセスできます。


.タスクの内容
Cross-Origin Resource Sharing （ CORS ）は、あるドメインのクライアント Web アプリケーションが別のドメインのリソースにアクセスできるようにするセキュリティ機能です。たとえば、という名前のS3バケットを使用してグラフィックを格納するとし `Images`ます。バケットのCORSを設定すると `Images`、そのバケット内のイメージをWebサイトに表示できるように `+http://www.example.com+`なります。



== バケットのCORSを有効にします

.手順
. テキストエディタを使用して、必要なXMLを作成します。次の例は、 S3 バケットの CORS を有効にするために使用される XML を示しています。具体的には：
+
** すべてのドメインがバケットにGET要求を送信できるようにする
** ドメインがGET、POST、およびDELETE要求の送信のみを許可する `+http://www.example.com+`
** すべての要求ヘッダーを許可
+
[listing]
----
<CORSConfiguration
    xmlns="http://s3.amazonaws.com/doc/2020-10-22/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
    <CORSRule>
        <AllowedOrigin>http://www.example.com</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>DELETE</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
----
+
CORS設定XMLの詳細については、を参照してください http://docs.aws.amazon.com/AmazonS3/latest/dev/Welcome.html["Amazon Web Services（AWS）ドキュメント：「Amazon Simple Storage Service User Guide」"^]。



. ダッシュボードで* View Buckets *を選択するか、* storage（S3）*>* Buckets *を選択します。
. 表からバケット名を選択します。
+
バケットの詳細ページが表示されます。

. [Bucket access]タブで、[Cross-Origin Resource Sharing（CORS）]*アコーディオンを選択します。
. [Enable CORS]チェックボックスをオンにします。
. CORS設定XMLをテキストボックスに貼り付けます。
. 「変更を保存」を選択します。




== CORS設定を変更します

.手順
. テキストボックスのCORS設定XMLを更新するか、* Clear *を選択してやり直します。
. 「変更を保存」を選択します。




== CORS設定を無効にします

.手順
. [Enable CORS]チェックボックスをオフにします。
. 「変更を保存」を選択します。

