---
permalink: tenant/configuring-platform-services-endpoints.html 
sidebar: sidebar 
keywords: how to configure platform services endpoint 
summary: バケットのプラットフォームサービスを設定する前に、少なくとも 1 つのエンドポイントをプラットフォームサービスのデスティネーションとして設定する必要があります。 
---
= プラットフォームサービスエンドポイントを設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バケットのプラットフォームサービスを設定する前に、少なくとも 1 つのエンドポイントをプラットフォームサービスのデスティネーションとして設定する必要があります。

プラットフォームサービスへのアクセスは、 StorageGRID 管理者がテナント単位で有効にします。プラットフォームサービスエンドポイントを作成または使用するには、ストレージノードが外部のエンドポイントリソースにアクセスできるようネットワークが設定されているグリッドで、Manage EndpointsまたはRoot Access権限を持つテナントユーザである必要があります。1つのテナントに対して設定できるプラットフォームサービスエンドポイントは最大500個です。詳細については、 StorageGRID 管理者にお問い合わせください。



== プラットフォームサービスエンドポイントとは何ですか。

プラットフォームサービスエンドポイントは、StorageGRIDが外部のデスティネーションにアクセスするために必要な情報を指定します。

たとえば、StorageGRID バケットからAmazon S3バケットにオブジェクトをレプリケートする場合は、StorageGRID がAmazonのデスティネーションバケットにアクセスするために必要な情報とクレデンシャルを含むプラットフォームサービスエンドポイントを作成します。

プラットフォームサービスのタイプごとに独自のエンドポイントが必要なため、使用する各プラットフォームサービスについて少なくとも 1 つのエンドポイントを設定する必要があります。プラットフォームサービスエンドポイントの定義が完了したら、サービスを有効にするための設定 XML でエンドポイントの URN をデスティネーションとして指定します。

同じエンドポイントを複数のソースバケットのデスティネーションとして使用できます。たとえば、複数のバケット間で検索を実行できるように、複数のソースバケットが同じ検索統合エンドポイントにオブジェクトメタデータを送信するように設定できます。複数のエンドポイントをターゲットとして使用するようにソースバケットを設定することもできます。これにより、オブジェクトの作成に関する通知をあるAmazon Simple Notification Service（Amazon SNS）トピックに送信したり、オブジェクトの削除に関する通知を別のAmazon SNSトピックに送信したりできます。



== CloudMirror レプリケーション用のエンドポイント

StorageGRID は、 S3 バケットを表すレプリケーションエンドポイントをサポートします。このバケットは、 Amazon Web Services 、同一またはリモートの StorageGRID 環境、あるいは別のサービスでホストされている可能性があります。



== 通知用のエンドポイント

StorageGRIDは、Amazon SNSおよびKafkaエンドポイントをサポートしています。Simple Queue Service（SQS）またはAWS Lambdaエンドポイントはサポートされていません。

Kafkaエンドポイントでは、相互TLSはサポートされていません。その結果、Kafkaブローカー設定でをに設定し `required`た場合 `ssl.client.auth`、Kafkaエンドポイント設定の問題が発生する可能性があります。



== 検索統合サービスのエンドポイント

StorageGRID は、 Elasticsearch クラスタを表す検索統合エンドポイントをサポートします。Elasticsearchクラスタは、ローカルデータセンターに配置することも、AWSクラウドなどの別の場所でホストすることもできます。

検索統合エンドポイントは、 Elasticsearch の特定のインデックスとタイプを参照します。StorageGRID でエンドポイントを作成する前に、 Elasticsearch でインデックスを作成しておく必要があります。作成していない場合、エンドポイントの作成に失敗します。エンドポイントを作成する前にタイプを作成する必要はありません。StorageGRID は、オブジェクトメタデータをエンドポイントに送信するときに必要に応じてタイプを作成します。

.関連情報
link:../admin/index.html["StorageGRID の管理"]
