---
permalink: tenant/considerations-for-platform-services.html 
sidebar: sidebar 
keywords: considerations for using platform services 
summary: プラットフォームサービスを実装する前に、これらのサービスの使用に関する概要と考慮事項を確認してください。 
---
= プラットフォームサービスの概要と考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プラットフォームサービスを実装する前に、これらのサービスの使用に関する概要と考慮事項を確認してください。

S3の詳細については、を参照してくださいlink:../s3/index.html["S3 REST APIを使用する"]。



== プラットフォームサービスの概要

StorageGRID プラットフォームサービスでは、イベント通知やS3オブジェクトとオブジェクトメタデータのコピーを外部のデスティネーションに送信できるため、ハイブリッドクラウド戦略の実装に役立ちます。

通常、プラットフォームサービスのターゲットは StorageGRID 環境の外部にあるため、プラットフォームサービスを使用することで外部ストレージリソース、通知サービス、検索または分析サービスの機能と柔軟性をデータに対して利用できます。

単一の S3 バケットに対して複数のプラットフォームサービスを組み合わせて設定できます。たとえば、StorageGRID S3バケットでとのlink:../tenant/understanding-notifications-for-buckets.html["通知"]両方を設定して、特定のオブジェクトをAmazon Simple Storage Service（S3）にミラーリングし、同時に各オブジェクトに関する通知をサードパーティの監視アプリケーションに送信してAWSの費用を追跡できますlink:../tenant/understanding-cloudmirror-replication-service.html["CloudMirrorサービス"]。


TIP: プラットフォームサービスの使用は、 StorageGRID 管理者がグリッドマネージャまたはグリッド管理 API を使用してテナントアカウントごとに有効にする必要があります。



== プラットフォームサービスの設定方法

プラットフォームサービスは、またはを使用して設定した外部エンドポイントと通信しlink:configuring-platform-services-endpoints.html["テナントマネージャ"]link:understanding-tenant-management-api.html["テナント管理 API"]ます。各エンドポイントは外部のデスティネーション（StorageGRID S3バケット、Amazon Web Servicesバケット、Amazon SNSトピック、ローカルやAWSなどでホストされるElasticsearchクラスタなど）です。

外部エンドポイントを作成したら、バケットにXML設定を追加してプラットフォームサービスを有効にできます。XML 設定は、バケットが処理を実行するオブジェクト、実行する処理、およびサービスに使用するエンドポイントを特定します。

設定するプラットフォームサービスごとに XML 設定を追加する必要があります。例：

* キーがで始まるすべてのオブジェクト `/images`をAmazon S3バケットにレプリケートする場合は、ソースバケットにレプリケーション設定を追加する必要があります。
* これらのオブジェクトがバケットに格納されたときに通知も送信するには、通知設定を追加する必要があります。
* これらのオブジェクトのメタデータのインデックスを作成する場合は、検索統合の実装に使用するメタデータ通知設定を追加する必要があります。


設定 XML の形式は、 StorageGRID プラットフォームサービスの実装に使用する S3 REST API に従います。

[cols="1a,2a,1a"]
|===
| プラットフォームサービス | S3 REST API | を参照してください 


 a| 
CloudMirror レプリケーション
 a| 
* GetBucketReplicationの略
* PutBucketReplicationの略

 a| 
* link:configuring-cloudmirror-replication.html["CloudMirror レプリケーション"]
* link:../s3/operations-on-buckets.html["バケットの処理"]




 a| 
通知
 a| 
* GetBucketNotificationConfigurationを参照してください
* PutBucketNotificationConfigurationの略

 a| 
* link:configuring-event-notifications.html["通知"]
* link:../s3/operations-on-buckets.html["バケットの処理"]




 a| 
検索統合
 a| 
* GET Bucket metadata notification configuration のコマンドです
* PUT Bucket metadata notification configuration のコマンドです

 a| 
* link:configuring-search-integration-service.html["検索統合"]
* link:../s3/custom-operations-on-buckets.html["StorageGRIDのカスタム処理"]


|===


== プラットフォームサービスの使用に関する考慮事項

[cols="1a,3a"]
|===
| 考慮事項 | 詳細 


 a| 
デスティネーションエンドポイントの監視
 a| 
各デスティネーションエンドポイントの可用性を監視する必要があります。長時間にわたってデスティネーションエンドポイントへの接続が失われ、要求のバックログが大量に発生している場合、 StorageGRID に対する以降のクライアント要求（ PUT 要求など）は失敗します。エンドポイントがアクセス可能になったら、失敗した要求を再試行する必要があります。



 a| 
デスティネーションエンドポイントのスロットル
 a| 
要求が送信されるペースがデスティネーションエンドポイントで要求を受信できるペースを超えると、 StorageGRID ソフトウェアはバケットの受信 S3 要求を調整する場合があります。スロットルは、デスティネーションエンドポイントへの送信を待機している要求のバックログが生じている場合にのみ発生します。

明らかな影響は、受信 S3 要求の実行時間が長くなることだけです。パフォーマンスが大幅に低下していることが検出されるようになった場合は、取り込み速度を下げるか、容量の大きいエンドポイントを使用する必要があります。要求のバックログが増え続けると、クライアント S3 処理（ PUT 要求など）が失敗します。

通常、 CloudMirror 要求には、検索統合やイベント通知の要求よりも多くのデータ転送が含まれるため、デスティネーションエンドポイントのパフォーマンスによる影響を受ける可能性が高くなります。



 a| 
順序保証
 a| 
StorageGRID では、 1 つのサイト内のオブジェクトに対する処理の順序が保証されます。あるオブジェクトに対するすべての処理が同じサイト内で実行されるかぎり、最終的なオブジェクトの（レプリケーションの）状態は常に StorageGRID の状態と同じになります。

StorageGRID は、 StorageGRID サイト間で処理が行われる場合、最善の順序で要求を処理しようと試みます。たとえば、最初にサイト A にオブジェクトを書き込んだあと、サイト B で同じオブジェクトを上書きした場合、 CloudMirror によって最終的にデスティネーションバケットにレプリケートされるオブジェクトが新しいほうのオブジェクトであるとはかぎりません。



 a| 
ILM ベースのオブジェクト削除
 a| 
AWS CRRとAmazon Simple Notification Serviceの削除動作と一致するように、StorageGRID ILMルールに基づいてソースバケット内のオブジェクトが削除された場合、CloudMirror要求とイベント通知要求は送信されません。たとえば、 ILM ルールによって 14 日後にオブジェクトが削除された場合、 CloudMirror 要求やイベント通知要求は送信されません。

一方、 ILM に基づいてオブジェクトが削除された場合、検索統合要求は送信されます。



 a| 
Kafkaエンドポイントの使用
 a| 
Kafkaエンドポイントでは、相互TLSはサポートされていません。その結果、Kafkaブローカー設定でをに設定し `required`た場合 `ssl.client.auth`、Kafkaエンドポイント設定の問題が発生する可能性があります。

Kafkaエンドポイントの認証では、次の認証タイプが使用されます。これらのタイプは、Amazon SNSなどの他のエンドポイントの認証に使用されるタイプとは異なり、ユーザ名とパスワードのクレデンシャルが必要です。

* SASL/プレーン
* SASL/SCRAM-SHA-256
* SASL/SCRAM-SHA-512


*注：*構成済みのストレージプロキシ設定は、Kafkaプラットフォームサービスエンドポイントには適用されません。

|===


== CloudMirror レプリケーションサービスの使用に関する考慮事項

[cols="1a,3a"]
|===
| 考慮事項 | 詳細 


 a| 
レプリケーションのステータス
 a| 
StorageGRIDはヘッダーをサポートしていません `x-amz-replication-status`。



 a| 
オブジェクトのサイズ
 a| 
CloudMirror レプリケーションサービスでデスティネーションバケットにレプリケートできるオブジェクトの最大サイズは 5TiB で、 maximum_supported_object サイズと同じです。

*注*：1回のPutObject処理の最大推奨サイズは5GiB（5、368、709、120バイト）です。5GB より大きいオブジェクトがある場合は、マルチパートアップロードを使用してください。



 a| 
バケットのバージョン管理とバージョン ID
 a| 
StorageGRID でソース S3 バケットのバージョン管理を有効にした場合、デスティネーションバケットのバージョン管理も有効にする必要があります。

バージョン管理を使用している場合、 S3 プロトコルの制限事項により、デスティネーションバケットのオブジェクトバージョンの処理はベストエフォートベースで行われ、 CloudMirror サービスによる保証はありません。

*注*：StorageGRID のソースバケットのバージョンIDは、デスティネーションバケットのバージョンIDとは関係ありません。



 a| 
オブジェクトバージョンのタグ付け
 a| 
S3プロトコルの制限により、バージョンIDを提供するPutObjectTagging要求やDeleteObjectTagging要求はCloudMirrorサービスではレプリケートされません。ソースとデスティネーションのバージョンIDは関連付けられていないため、特定のバージョンIDへのタグの更新を確実にレプリケートする方法はありません。

一方、CloudMirrorサービスでは、バージョンIDを指定しないPutObjectTagging要求またはDeleteObjectTagging要求はレプリケートされません。これらの要求は、最新のキー（バケットがバージョン管理されている場合は最新のバージョン）のタグを更新します。（タグの更新ではなく）タグを使用した通常の取り込みもレプリケートされます。



 a| 
マルチパートアップロードと `ETag`値
 a| 
マルチパートアップロードを使用してアップロードされたオブジェクトをミラーリングした場合、 CloudMirror サービスではパートが保持されません。その結果 `ETag`、ミラーリングされたオブジェクトの値は、元のオブジェクトの値とは異なり `ETag`ます。



 a| 
SSE-C （ユーザ指定のキーによるサーバ側の暗号化）で暗号化されたオブジェクト
 a| 
CloudMirrorサービスでは、SSE-Cで暗号化されたオブジェクトはサポートされていません。CloudMirrorレプリケーションのソースバケットにオブジェクトを取り込む際に、要求にSSE-C要求ヘッダーが含まれていると処理が失敗します。



 a| 
S3 オブジェクトのロックが有効になっているバケット
 a| 
S3 オブジェクトロックが有効なソースバケットまたはデスティネーションバケットでは、レプリケーションはサポートされません。

|===