---
permalink: tenant/creating-your-own-s3-access-keys.html 
sidebar: sidebar 
keywords: how to create your own S3 access key 
summary: S3 テナントを使用している場合は、適切な権限があれば、自分の S3 アクセスキーを作成できます。バケットとオブジェクトにアクセスするには、アクセスキーが必要です。 
---
= 独自の S3 アクセスキーを作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 テナントを使用している場合は、適切な権限があれば、自分の S3 アクセスキーを作成できます。バケットとオブジェクトにアクセスするには、アクセスキーが必要です。

.開始する前に
* を使用してTenant Managerにサインインしておきlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]ます。
* が設定されたユーザグループに属しているlink:tenant-management-permissions.html["自分のS3クレデンシャルまたはRoot Access権限を管理します"]必要があります。


.タスクの内容
テナントアカウントのバケットを作成および管理できる S3 アクセスキーを 1 つ以上作成できます。新しいアクセスキーを作成したら、新しいアクセスキー ID とシークレットアクセスキーでアプリケーションを更新します。セキュリティのため、必要以上のキーを作成しないで、使用していないキーを削除してください。キーが 1 つしかなく、有効期限が近づいている場合は、古いキーが期限切れになる前に新しいキーを作成してから、古いキーを削除します。

各キーには、特定の有効期限または有効期限を設定できません。有効期限については、次のガイドラインに従ってください。

* キーの有効期限を設定して、アクセスを特定の期間に制限します。短い有効期限を設定すると、アクセスキー ID とシークレットアクセスキーが誤って公開されるリスクを低減できます。期限切れのキーは自動的に削除されます。
* 環境のセキュリティリスクが低く、新しいキーを定期的に作成する必要がない場合は、キーの有効期限を設定する必要はありません。あとで新しいキーを作成する場合は、古いキーを手動で削除します。



CAUTION: アカウントに属する S3 バケットとオブジェクトには、 Tenant Manager でアカウントに表示されるアクセスキー ID とシークレットアクセスキーを使用してアクセスできます。このため、アクセスキーはパスワードと同じように保護する必要があります。定期的にアクセスキーをローテーションし、使用されていないキーはアカウントから削除します。また、他のユーザとはアクセスキーを共有しないでください。

.手順
. 「 * storage （ S3 ） * > * My access keys * 」を選択します。
+
[ マイアクセスキー ] ページが表示され、既存のアクセスキーが一覧表示されます。

. 「 * キーの作成 * 」を選択します。
. 次のいずれかを実行します。
+
** 有効期限を設定しない * を選択して、有効期限が切れないキーを作成します。（デフォルト）
** [ 有効期限の設定 *] を選択し、有効期限の日付と時刻を設定します。
+

NOTE: 有効期限は、現在の日付から最大5年間です。有効期限は、現在の時刻から少なくとも1分後に設定できます。



. [ アクセスキーの作成 *] を選択します。
+
Download access key （アクセスキーのダウンロード）ダイアログボックスが表示され、アクセスキー ID とシークレットアクセスキーが一覧表示されます。

. アクセスキー ID とシークレットアクセスキーを安全な場所にコピーするか、「 * Download.csv * 」を選択してアクセスキー ID とシークレットアクセスキーを含むスプレッドシートファイルを保存します。
+

CAUTION: この情報をコピーまたはダウンロードするまで、このダイアログボックスを閉じないでください。ダイアログボックスを閉じた後は、キーをコピーまたはダウンロードすることはできません。

. [ 完了 ] を選択します。
+
新しいキーは [ マイアクセスキー ] ページに表示されます。

. テナントアカウントに* Use grid federation connection *権限がある場合は、必要に応じてテナント管理APIを使用して、ソースグリッドのテナントからデスティネーショングリッドのテナントにS3アクセスキーを手動でクローニングします。を参照して link:grid-federation-clone-keys-with-api.html["APIを使用してS3アクセスキーをクローニングします"]

