---
permalink: tenant/creating-platform-services-endpoint.html 
sidebar: sidebar 
keywords: how to create platform services endpoint 
summary: プラットフォームサービスを有効にする前に、正しいタイプのエンドポイントを少なくとも 1 つ作成しておく必要があります。 
---
= プラットフォームサービスエンドポイントを作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プラットフォームサービスを有効にする前に、正しいタイプのエンドポイントを少なくとも 1 つ作成しておく必要があります。

.開始する前に
* を使用してTenant Managerにサインインしておきlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]ます。
* テナントアカウントのプラットフォームサービスがStorageGRID 管理者によって有効にされている。
* が設定されたユーザグループに属しているlink:tenant-management-permissions.html["エンドポイントまたはRoot Access権限を管理します"]必要があります。
* プラットフォーム サービス エンドポイントによって参照されるリソースが作成されました。
+
** CloudMirror レプリケーション： S3 バケット
** イベント通知: Amazon Simple Notification Service (Amazon SNS) トピック、Kafka トピック、または Webhook エンドポイント
** 検索通知: 宛先クラスターがインデックスを自動的に作成するように構成されていない場合は、Elasticsearch インデックス。


* デスティネーションリソースに関する情報を確認しておきます。
+
** Uniform Resource Identifier （ URI ）のホストとポート
+

NOTE: StorageGRID システムでホストされているバケットを CloudMirror レプリケーションのエンドポイントとして使用する場合は、グリッド管理者に問い合わせて入力が必要な値を決定してください。

** Unique Resource Name （ URN ）
+
link:specifying-urn-for-platform-services-endpoint.html["プラットフォームサービスのエンドポイントの URN を指定してください"]

** 認証クレデンシャル（必要な場合）：
+
[role="tabbed-block"]
====
.検索統合エンドポイント
--
検索統合エンドポイントには、次のクレデンシャルを使用できます。

*** Access Key ：アクセスキー ID とシークレットアクセスキー
*** 基本 HTTP 認証：ユーザ名とパスワード


--
.CloudMirrorレプリケーションエンドポイント
--
CloudMirrorレプリケーションエンドポイントの場合は、次のクレデンシャルを使用できます。

*** Access Key ：アクセスキー ID とシークレットアクセスキー
*** CAP （ C2S Access Portal ）：一時的なクレデンシャル URL 、サーバ証明書とクライアント証明書、クライアントキー、およびオプションのクライアント秘密鍵パスフレーズ。


--
.Amazon SNSエンドポイント
--
Amazon SNSエンドポイントの場合は、次のクレデンシャルを使用できます。

*** Access Key ：アクセスキー ID とシークレットアクセスキー


--
.Kafkaエンドポイント
--
Kafkaエンドポイントの場合は、次のクレデンシャルを使用できます。

*** SASL/plain：ユーザ名とパスワード
*** SASL/SCRAM-SHA-256：ユーザ名とパスワード
*** SASL/SCRAM-SHA-512：ユーザ名とパスワード


--
====
** セキュリティ証明書（証明書の検証が必要な場合）


* Elasticsearchセキュリティ機能が有効になっている場合は、接続テスト用のmonitor cluster権限と、ドキュメント更新用のwrite index権限、またはindex権限とdelete index権限の両方があります。


.手順
. ストレージ（ S3 ） * > * プラットフォームサービスのエンドポイント * を選択します。プラットフォームサービスエンドポイントページが表示されます。
. [ * エンドポイントの作成 * ] を選択します。
. エンドポイントとその目的を簡単に説明する表示名を入力します。
+
エンドポイントがサポートするプラットフォーム サービスのタイプは、エンドポイント ページにリストされるときにエンドポイント名の横に表示されるため、名前にその情報を含める必要はありません。

. [* URI*] フィールドに、エンドポイントの Unique Resource Identifier （ URI ）を指定します。
+
--
次のいずれかの形式を使用します。

[listing]
----
https://host:port
http://host:port
----
ポートを指定しない場合は、次のデフォルトポートが使用されます。

** HTTPS URIにはポート443、HTTP URIにはポート80（ほとんどのエンドポイント）
** HTTPSおよびHTTP URI用のポート9092（Kafkaエンドポイントのみ）


--
+
たとえば、 StorageGRID でホストされているバケットの URI は次のようになります。

+
[listing]
----
https://s3.example.com:10443
----
+
この例のは `s3.example.com`StorageGRIDハイアベイラビリティ（HA）グループの仮想IP（VIP）のDNSエントリ、 `10443`はロードバランサエンドポイントで定義されたポートです。

+

NOTE: 単一点障害（Single Point of Failure）を回避するために、可能なかぎりロードバランシングノードのHAグループに接続する必要があります。

+
同様に、 AWS でホストされているバケットの URI は次のようになります。

+
[listing]
----
https://s3-aws-region.amazonaws.com
----
+

NOTE: エンドポイントがCloudMirrorレプリケーションサービスに使用される場合は、URIにバケット名を含めないでください。バケット名は「 * URN * 」フィールドに含める必要があります。

. エンドポイントの Unique Resource Name （ URN ）を入力します。
+

NOTE: エンドポイントの作成後にエンドポイントのURNを変更することはできません。

. 「 * Continue * 」を選択します。
. [認証タイプ]*の値を選択します。
+

NOTE: Webhookエンドポイントの認証が必要な場合は、Mutual Transport Layer Security（mTLS）を設定します。<<verify-certs,ステップ9>> 。

+
[role="tabbed-block"]
====
.検索統合エンドポイント
--
検索統合エンドポイントのクレデンシャルを入力またはアップロードします。

指定するクレデンシャルには、デスティネーションリソースに対する書き込み権限が必要です。

[cols="1a,2a,2a"]
|===
| 認証タイプ | 製品説明 | クレデンシャル 


 a| 
匿名
 a| 
デスティネーションへの匿名アクセスを許可します。セキュリティが無効になっているエンドポイントでのみ機能します。
 a| 
認証なし。



 a| 
アクセスキー
 a| 
AWS 形式のクレデンシャルを使用してデスティネーションとの接続を認証します。
 a| 
** アクセスキーID
** シークレットアクセスキー




 a| 
基本 HTTP
 a| 
ユーザ名とパスワードを使用して、デスティネーションへの接続を認証します。
 a| 
** ユーザ名
** パスワード


|===
--
.CloudMirrorレプリケーションエンドポイント
--
CloudMirrorレプリケーションエンドポイントのクレデンシャルを入力またはアップロードします。

指定するクレデンシャルには、デスティネーションリソースに対する書き込み権限が必要です。

[cols="1a,2a,2a"]
|===
| 認証タイプ | 製品説明 | クレデンシャル 


 a| 
匿名
 a| 
デスティネーションへの匿名アクセスを許可します。セキュリティが無効になっているエンドポイントでのみ機能します。
 a| 
認証なし。



 a| 
アクセスキー
 a| 
AWS 形式のクレデンシャルを使用してデスティネーションとの接続を認証します。
 a| 
** アクセスキーID
** シークレットアクセスキー




 a| 
CAP （ C2S Access Portal ）
 a| 
証明書とキーを使用してデスティネーションへの接続を認証します。
 a| 
** 一時的な資格情報 URL
** サーバ CA 証明書（ PEM ファイルのアップロード）
** クライアント証明書（ PEM ファイルのアップロード）
** クライアント秘密鍵（ PEM ファイルのアップロード、 OpenSSL 暗号化形式、または暗号化されていない秘密鍵形式）
** クライアント秘密鍵のパスフレーズ（オプション）


|===
--
.Amazon SNSエンドポイント
--
Amazon SNSエンドポイントのクレデンシャルを入力またはアップロードします。

指定するクレデンシャルには、デスティネーションリソースに対する書き込み権限が必要です。

[cols="1a,2a,2a"]
|===
| 認証タイプ | 製品説明 | クレデンシャル 


 a| 
匿名
 a| 
デスティネーションへの匿名アクセスを許可します。セキュリティが無効になっているエンドポイントでのみ機能します。
 a| 
認証なし。



 a| 
アクセスキー
 a| 
AWS 形式のクレデンシャルを使用してデスティネーションとの接続を認証します。
 a| 
** アクセスキーID
** シークレットアクセスキー


|===
--
.Kafkaエンドポイント
--
Kafkaエンドポイントのクレデンシャルを入力またはアップロードします。

指定するクレデンシャルには、デスティネーションリソースに対する書き込み権限が必要です。

[cols="1a,2a,2a"]
|===
| 認証タイプ | 製品説明 | クレデンシャル 


 a| 
匿名
 a| 
デスティネーションへの匿名アクセスを許可します。セキュリティが無効になっているエンドポイントでのみ機能します。
 a| 
認証なし。



 a| 
SASL/プレーン
 a| 
プレーンテキストのユーザ名とパスワードを使用して、宛先への接続を認証します。
 a| 
** ユーザ名
** パスワード




 a| 
SASL/SCRAM-SHA-256
 a| 
チャレンジ応答プロトコルとSHA-256ハッシュを使用してユーザ名とパスワードを使用し、宛先への接続を認証します。
 a| 
** ユーザ名
** パスワード




 a| 
SASL/SCRAM-SHA-512
 a| 
チャレンジ応答プロトコルとSHA-512ハッシュを使用してユーザ名とパスワードを使用し、宛先への接続を認証します。
 a| 
** ユーザ名
** パスワード


|===
ユーザ名とパスワードがKafkaクラスタから取得した委任トークンから取得されたものである場合は、* Use delegation taken authentication *を選択します。

--
====
. 「 * Continue * 」を選択します。
. [[verify-certs]]エンドポイントへの TLS 接続を検証する方法を選択するには、[証明書の検証] のラジオ ボタンを選択します。
+
[role="tabbed-block"]
====
.ほとんどのエンドポイント
--
検索統合、CloudMirror レプリケーション、Amazon SNS、または Kafka エンドポイントの TLS 接続を確認します。

[cols="1a,2a"]
|===
| 証明書検証のタイプ | 製品説明 


 a| 
TLS
 a| 
エンドポイント リソースへの TLS 接続のサーバー証明書を検証します。



 a| 
無効
 a| 
証明書の検証は無効です。このオプションは安全ではありません。



 a| 
カスタム CA 証明書を使用する
 a| 
カスタム CA 証明書は、エンドポイントに接続するときにサーバーの ID を確認するために使用されます。



 a| 
オペレーティングシステムの CA 証明書を使用します
 a| 
オペレーティングシステムにインストールされているデフォルトの Grid CA 証明書を使用して接続を保護します。

|===
--
.Webhookエンドポイントのみ
--
Webhook エンドポイントの TLS 接続を確認します。

[cols="1a,2a"]
|===
| 証明書検証のタイプ | 製品説明 


 a| 
TLS
 a| 
エンドポイント リソースへの TLS 接続のサーバー証明書を検証します。



 a| 
mTLS
 a| 
エンドポイント リソースへの相互 TLS 接続のクライアント証明書とサーバー証明書を検証します。



 a| 
無効
 a| 
証明書の検証は無効です。このオプションは安全ではありません。



 a| 
カスタム CA 証明書を使用する
 a| 
カスタム CA 証明書は、エンドポイントに接続するときにサーバーの ID を確認するために使用されます。

|===
*mTLS* を選択すると、これらのオプションが利用可能になります。

[cols="1a,2a"]
|===
| 証明書検証のタイプ | 製品説明 


 a| 
サーバー証明書を検証しない
 a| 
サーバー証明書の検証を無効にします。つまり、サーバーの ID は検証されません。このオプションは安全ではありません。



 a| 
クライアント証明書
 a| 
クライアント証明書は、エンドポイントに接続するときにクライアントの ID を確認するために使用されます。



 a| 
クライアントの秘密鍵
 a| 
クライアント証明書の秘密キー。暗号化する場合は、従来の形式 PKCS #1 を使用する必要があります (PKCS #8 形式はサポートされていません)。



 a| 
クライアントの秘密鍵のパスフレーズ
 a| 
クライアントの秘密鍵を復号化するためのパスフレーズ。秘密鍵が暗号化されていない場合は空白のままにします。

|===
--
====
. [ * テストとエンドポイントの作成 * ] を選択します。
+
** 指定したクレデンシャルを使用してエンドポイントにアクセスできた場合は、成功を伝えるメッセージが表示されます。エンドポイントへの接続は、各サイトの 1 つのノードから検証されます。
** エンドポイントの検証が失敗した場合は、エラーメッセージが表示されます。エラーを修正するためにエンドポイントを変更する必要がある場合は、 * エンドポイントの詳細に戻る * を選択して情報を更新します。次に、「 * Test 」を選択し、エンドポイントを作成します。 *
+

NOTE: テナントアカウントでプラットフォームサービスが有効になっていないと、エンドポイントの作成が失敗します。StorageGRID 管理者にお問い合わせください。





エンドポイントの設定が完了したら、その URN を使用してプラットフォームサービスを設定できます。

.関連情報
* link:specifying-urn-for-platform-services-endpoint.html["プラットフォームサービスのエンドポイントの URN を指定してください"]
* link:configuring-cloudmirror-replication.html["CloudMirror レプリケーションを設定します"]
* link:configuring-event-notifications.html["イベント通知の設定"]
* link:configuring-search-integration-service.html["検索統合サービスを設定する"]

