---
permalink: tenant/creating-s3-bucket.html 
sidebar: sidebar 
keywords: how to create S3 bucket 
summary: Tenant Manager を使用して、オブジェクトデータ用の S3 バケットを作成できます。 
---
= S3 バケットを作成します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tenant Manager を使用して、オブジェクトデータ用の S3 バケットを作成できます。

.開始する前に
* を使用してTenant Managerにサインインしておきlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]ます。
* [Root access]または[Manage all buckets]が設定されたユーザグループに属している必要link:tenant-management-permissions.html["アクセス権"]があります。これらの権限は、グループまたはバケットポリシーの権限の設定よりも優先されます。
+

NOTE: バケットまたはオブジェクトのS3オブジェクトロックプロパティを設定または変更する権限は、から付与できますlink:../s3/bucket-and-group-access-policies.html["バケットポリシーまたはグループポリシー"]。

* バケットでS3オブジェクトロックを有効にする場合は、グリッド管理者がStorageGRID システムに対してグローバルなS3オブジェクトロック設定を有効にし、S3オブジェクトロックのバケットとオブジェクトの要件を確認しておく必要があります。
* 各テナントに5、000バケットがある場合は、グリッド内の各ストレージノードに64GB以上のRAMが搭載されます。
+

NOTE: 各グリッドには、を含む最大100,000個のバケットを含めることlink:../tenant/manage-branch-buckets.html["分岐バケット"]ができます。





== ウィザードにアクセスします

.手順
. ダッシュボードで* View Buckets *を選択するか、* storage（S3）*>* Buckets *を選択します。
. [ * バケットの作成 * ] を選択します。




== 詳細を入力します

.手順
. バケットの詳細を入力します。
+
[cols="1a,3a"]
|===
| フィールド | 製品説明 


 a| 
バケット名
 a| 
次のルールを満たすバケットの名前。

** StorageGRID システム全体で（テナントアカウント内だけではなく）一意である必要があります。
** DNS に準拠している必要があります。
** 3文字以上63文字以下にする必要があります。
** 各ラベルの先頭と末尾の文字は小文字のアルファベットか数字にする必要があり、使用できる文字は小文字のアルファベット、数字、ハイフンのみです。
** 仮想ホスト形式の要求にピリオドを含めることはできません。ピリオドを使用すると、サーバワイルドカード証明書の検証で原因 の問題が発生します。


詳細については、を参照して https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html["バケットの命名規則に関する Amazon Web Services （ AWS ）のドキュメント"^]ください。

*注*：バケットの作成後にバケット名を変更することはできません。



 a| 
地域
 a| 
バケットのリージョン。

StorageGRID 管理者が利用可能なリージョンを管理します。バケットのリージョンは、オブジェクトに適用されるデータ保護ポリシーに影響する可能性があります。デフォルトでは、すべてのバケットがリージョンに作成され `us-east-1`ます。

*注*：バケットの作成後にリージョンを変更することはできません。

|===
. 「 * Continue * 」を選択します。




== 設定の管理

.手順
. 必要に応じて、バケットのオブジェクトのバージョン管理を有効にします。
+
このバケット内の各オブジェクトのすべてのバージョンを格納する場合は、オブジェクトのバージョン管理を有効にします。そのあと、必要に応じて以前のバージョンのオブジェクトを読み出すことができます。

+
次の場合、オブジェクトのバージョン管理を有効にする必要があります。

+
** バケットはグリッド間レプリケーションに使用されます。
** このバケットからを作成しlink:../tenant/manage-branch-buckets.html["分岐バケット"]ます。


. S3オブジェクトロックのグローバル設定が有効になっている場合は、必要に応じて、バケットのS3オブジェクトロックを有効にして、Write-Once-Read-Many（WORM）モデルを使用してオブジェクトを格納します。
+
バケットのS3オブジェクトロックは、一定の規制要件を満たすためにオブジェクトを一定期間保持する必要がある場合にのみ有効にしてください。S3オブジェクトロックは永続的な設定で、オブジェクトの削除や上書きを一定期間または無期限に防ぐことができます。

+

CAUTION: バケットでS3オブジェクトロックの設定を有効にしたあとに無効にすることはできません。このバケットには、適切な権限を持つユーザがオブジェクトを追加して変更できないようにすることができます。これらのオブジェクトやバケット自体を削除できない場合があります。

+
バケットで S3 オブジェクトのロックを有効にすると、バケットのバージョン管理が自動的に有効になります。

. [S3オブジェクトロックを有効にする]*を選択した場合は、必要に応じてこのバケットに対して*デフォルトの保持*を有効にします。
+

NOTE: グリッド管理者は、に対する権限をユーザに付与する必要がありますlink:../tenant/using-s3-object-lock.html["S3オブジェクトロックの特定の機能を使用する"]。

+
default retention *を有効にすると、バケットに追加された新しいオブジェクトが自動的に削除または上書きされなくなります。デフォルトの保持*設定は、独自の保持期間を持つオブジェクトには適用されません。

+
.. default retention *が有効になっている場合は、バケットの* default retention mode *を指定します。
+
[cols="1a,2a"]
|===
| デフォルトの保持モード | 製品説明 


 a| 
ガバナンス
 a| 
*** 権限を持つユーザ `s3:BypassGovernanceRetention`は、要求ヘッダーを使用して保持設定を省略でき `x-amz-bypass-governance-retention: true`ます。
*** これらのユーザは、retain-until-dateに達する前にオブジェクトバージョンを削除できます。
*** これらのユーザは、オブジェクトのretain-until-dateを増減、または削除できます。




 a| 
コンプライアンス
 a| 
*** retain-until-dateに達するまで、オブジェクトを削除できません。
*** オブジェクトのretain-until-dateは増やすことはできますが、減らすことはできません。
*** オブジェクトのretain-until-dateは、その日付に達するまで削除できません。


*注*：グリッド管理者が準拠モードの使用を許可する必要があります。

|===
.. default retention *が有効になっている場合は、バケットの* default retention period *を指定します。
+
Default retention period *は、このバケットに追加された新しいオブジェクトを取り込んだ時点から保持する期間です。グリッド管理者が設定したテナントの最大保持期間以下の値を指定します。

+
A_maximum_retention periodは、グリッド管理者がテナントを作成するときに設定されます。指定できる値は1~100年です。_default_retention periodを設定する場合、最大保持期間に設定された値を超えることはできません。必要に応じて、最大保持期間を増減するようにグリッド管理者に依頼します。



. [[capacity-limit]]必要に応じて、*[容量制限を有効にする]*を選択し、値を入力して容量の単位を選択します。
+
容量制限は、このバケットのオブジェクトに使用できる最大容量です。この値は、物理容量（ディスク上のサイズ）ではなく、論理容量（オブジェクトサイズ）を表します。

+
制限が設定されていない場合、このバケットの容量は無制限です。詳細については、を参照してください link:../tenant/understanding-tenant-manager-dashboard.html#bucket-capacity-usage["ヨウリヨウセイケンシヨウ"] 。

. [[object-count-limit]]オプションで[Enable object count limit]*を選択し、1以上1,000,000,000,000,000,000以下の整数を入力します。
+
オブジェクト数制限は、このバケットに含めることができるオブジェクトの最大数です。この値は論理量（オブジェクト数）を表します。制限が設定されていない場合、オブジェクト数は無制限になります。

. [ * バケットの作成 * ] を選択します。
+
バケットが作成され、バケットページのテーブルに追加されます。

. 必要に応じて、*[Go to bucket details page]*を選択しlink:viewing-s3-bucket-details.html["バケットの詳細を表示します"]て追加の設定を実行します。


必要に応じて行うこともできlink:../tenant/manage-branch-buckets.html["ブランチバケットの作成"]ます。
