---
permalink: tenant/creating-groups-for-swift-tenant.html 
sidebar: sidebar 
keywords: how to create Swift tenant groups 
summary: Swift テナントアカウントに対するアクセス権限を管理するには、フェデレーテッドグループをインポートするか、ローカルグループを作成します。Swift テナントアカウントのコンテナとオブジェクトを管理するには、少なくとも 1 つのグループが Swift 管理者権限を持っている必要があります。 
---
= Swift テナント用のグループを作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Swift テナントアカウントに対するアクセス権限を管理するには、フェデレーテッドグループをインポートするか、ローカルグループを作成します。Swift テナントアカウントのコンテナとオブジェクトを管理するには、少なくとも 1 つのグループが Swift 管理者権限を持っている必要があります。


NOTE: Swiftクライアントアプリケーションのサポートは廃止され、今後のリリースで削除される予定です。

.開始する前に
* を使用してTenant Managerにサインインしておきlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]ます。
* が設定されたユーザグループに属しているlink:tenant-management-permissions.html["rootアクセス権限"]必要があります。
* フェデレーテッドグループをインポートする場合はlink:using-identity-federation.html["アイデンティティフェデレーションが設定された"]、そのフェデレーテッドグループが設定済みのアイデンティティソースにすでに存在している必要があります。




== グループ作成ウィザードにアクセスします

.手順
最初に、グループ作成ウィザードにアクセスします。

. * access management * > * Groups * を選択します。
. 「 * グループを作成 * 」を選択します。




== グループタイプを選択します

ローカルグループを作成するか、フェデレーテッドグループをインポートできます。

.手順
. [ ローカルグループ *] タブを選択してローカルグループを作成するか、または [ フェデレーショングループ *] タブを選択して、以前に設定したアイデンティティソースからグループをインポートします。
+
StorageGRID システムでシングルサインオン（ SSO ）が有効になっている場合、ローカルグループに属するユーザは Tenant Manager にサインインできません。ただし、クライアントアプリケーションを使用して、グループの権限に基づいてテナントのリソースを管理することはできます。

. グループの名前を入力します。
+
** * ローカルグループ * ：表示名と一意の名前の両方を入力します。表示名はあとで編集できます。
** * フェデレーショングループ * ：一意の名前を入力します。Active Directoryの場合、一意の名前は属性に関連付けられた名前です `sAMAccountName`。OpenLDAPの場合、一意の名前は属性に関連付けられた名前です `uid`。


. 「 * Continue * 」を選択します。




== グループの権限を管理します

グループ権限は、ユーザがTenant Managerおよびテナント管理APIで実行できるタスクを制御します。

.手順
. [アクセスモード]*で、次のいずれかを選択します。
+
** * Read-write *（デフォルト）：ユーザはTenant Managerにサインインしてテナント設定を管理できます。
** * 読み取り専用 * ：ユーザーは設定と機能のみを表示できます。Tenant Managerまたはテナント管理APIでは、変更を加えたり処理を実行したりすることはできません。ローカルの読み取り専用ユーザは自分のパスワードを変更できます。
+

NOTE: ユーザが複数のグループに属していて、いずれかのグループが読み取り専用に設定されている場合、選択したすべての設定と機能に読み取り専用でアクセスできます。



. グループユーザがTenant Managerまたはテナント管理APIにサインインする必要がある場合は、* Root access *チェックボックスを選択します。
. 「 * Continue * 」を選択します。




== Swiftグループポリシーを設定します

Swiftユーザは、Swift REST APIに認証してコンテナを作成し、オブジェクトを取り込むための管理者権限が必要です。

. グループユーザがSwift REST APIを使用してコンテナとオブジェクトを管理する必要がある場合は、* Swift administrator *チェックボックスをオンにします。
. ローカルグループを作成する場合は、「 * Continue * 」を選択します。フェデレーテッドグループを作成する場合は、 * Create group * および * Finish * を選択します。




== ユーザの追加（ローカルグループのみ）

ユーザを追加せずにグループを保存することも、必要に応じて既存のローカルユーザを追加することもできます。

.手順
. 必要に応じて、このグループに対して 1 人以上のローカルユーザを選択します。
+
ローカルユーザをまだ作成していない場合は、[ユーザ]ページでこのグループをユーザに追加できます。を参照して link:../tenant/managing-local-users.html["ローカルユーザを管理します"]

. [ グループの作成 *] と [ 完了 *] を選択します。
+
作成したグループがグループのリストに表示されます。


