---
permalink: tenant/deleting-another-users-s3-access-keys.html 
sidebar: sidebar 
keywords: how to delete access key for other user 
summary: S3 テナントを使用していて、適切な権限を持っている場合は、別のユーザの S3 アクセスキーを削除できます。アクセスキーを削除すると、テナントアカウント内のオブジェクトとバケットにそのアクセスキーでアクセスできなくなります。 
---
= 別のユーザの S3 アクセスキーを削除します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 テナントを使用している場合は、適切な権限があれば、別のユーザの S3 アクセスキーを削除できます。アクセスキーを削除すると、テナントアカウント内のオブジェクトとバケットにそのアクセスキーでアクセスできなくなります。

.開始する前に
* を使用してTenant Managerにサインインしておきlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]ます。
* あなたはを持っていますlink:tenant-management-permissions.html["rootアクセス権限"]。



CAUTION: ユーザに属する S3 バケットとオブジェクトには、 Tenant Manager でそのユーザに対して表示されるアクセスキー ID とシークレットアクセスキーを使用してアクセスできます。このため、アクセスキーはパスワードと同じように保護する必要があります。定期的にアクセスキーをローテーションし、使用されていないキーはアカウントから削除します。また、他のユーザとはアクセスキーを共有しないでください。

.手順
. *アクセス管理* > *ユーザー*を選択します。
. [Users]ページで、管理するS3アクセスキーを所有するユーザを選択します。
. [ユーザの詳細]ページで*[アクセスキー]*を選択し、削除する各アクセスキーのチェックボックスをオンにします。
. * アクション * > * 選択したキーを削除 * を選択します。
. 確認ダイアログボックスで、* Delete key *を選択します。
+
ページの右上に確認メッセージが表示されます。


