---
permalink: tenant/enabling-or-disabling-last-access-time-updates.html 
sidebar: sidebar 
keywords: how to enable or disable last access time updates 
summary: グリッド管理者が StorageGRID システムの情報ライフサイクル管理（ ILM ）ルールを作成する場合、オブジェクトを別の格納場所に移動するかどうかを決定する際にオブジェクトの最終アクセス日時を使用するように指定できます。S3 テナントを使用している場合は、 S3 バケット内のオブジェクトに対して最終アクセス日時の更新を有効にすることで、このようなルールを活用できます。 
---
= 最終アクセス日時の更新を有効または無効にします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッド管理者が StorageGRID システムの情報ライフサイクル管理（ ILM ）ルールを作成する際に、オブジェクトを別の格納場所に移動するかどうかを決定する際にオブジェクトの最終アクセス日時を使用するように指定できます。S3 テナントを使用している場合は、 S3 バケット内のオブジェクトに対して最終アクセス日時の更新を有効にすることで、このようなルールを活用できます。

以下の手順は、[最終アクセス時間]*オプションを高度なフィルタまたは参照時間として使用するILMルールを少なくとも1つ含むStorageGRID システムにのみ該当します。StorageGRID システムにこのようなルールが含まれていない場合は、この手順を無視してかまいません。詳細は、を参照してください link:../ilm/using-last-access-time-in-ilm-rules.html["ILMルールで最終アクセス時間を使用"] 。

.開始する前に
* を使用してTenant Managerにサインインしておきlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]ます。
* が設定されたユーザグループに属しているlink:tenant-management-permissions.html["すべてのバケットまたはRoot Access権限を管理します"]必要があります。これらの権限は、グループまたはバケットポリシーの権限の設定よりも優先されます。


.タスクの内容
*最終アクセス時間*は、ILMルールの* Reference time *配置手順で使用できるオプションの1つです。ルールの[Reference time]を[Last access time]に設定すると、オブジェクトが最後に読み出された（読み取りまたは表示された）日時に基づいてオブジェクトを特定の格納場所に配置するようにグリッド管理者が指定できます。

たとえば、最近表示したオブジェクトを高速ストレージに保持するには、次のように指定した ILM ルールを作成できます。

* 過去 1 カ月間に読み出されたオブジェクトは、ローカルストレージノードに保持する。
* 過去 1 カ月間に読み出されなかったオブジェクトは、オフサイトの場所に移動する。


デフォルトでは、最終アクセス時間の更新は無効です。StorageGRID システムに*最終アクセス時間*オプションを使用するILMルールが含まれている場合に、このバケット内のオブジェクトにこのオプションを適用するには、そのルールで指定されたS3バケットに対して最終アクセス時間の更新を有効にする必要があります。


CAUTION: オブジェクトが読み出されるときに最終アクセス日時を更新すると、特に小さなオブジェクトについては StorageGRID のパフォーマンスが低下する可能性があります。

最終アクセス時間の更新では、オブジェクトが読み出されるたびに StorageGRID で以下の追加手順が実行されるため、パフォーマンスが低下します。

* 新しいタイムスタンプでオブジェクトを更新します
* 現在の ILM ルールとポリシーに照らしてオブジェクトが再評価されるように、 ILM キューにオブジェクトを追加します


次の表に、最終アクセス時間が有効または無効な場合のバケット内のすべてのオブジェクトに適用される動作をまとめます。

[cols="1a,1a,1a,1a,1a"]
|===


.2+| 要求のタイプ 2+| 最終アクセス時間が無効な場合の動作（デフォルト） 2+| 最終アクセス時間が有効な場合の動作 


| 最終アクセス時間の更新 | ILM 評価キューへのオブジェクトの追加 | 最終アクセス時間の更新 | ILM 評価キューへのオブジェクトの追加 


 a| 
HEAD処理の実行時にオブジェクトのメタデータを読み出す要求
 a| 
いいえ
 a| 
いいえ
 a| 
いいえ
 a| 
いいえ



 a| 
オブジェクト、そのアクセス制御リスト、またはメタデータの読み出し要求
 a| 
いいえ
 a| 
いいえ
 a| 
はい
 a| 
はい



 a| 
オブジェクトメタデータの更新要求
 a| 
はい
 a| 
はい
 a| 
はい
 a| 
はい



 a| 
オブジェクトまたはオブジェクトバージョンのリスト要求
 a| 
いいえ
 a| 
いいえ
 a| 
いいえ
 a| 
いいえ



 a| 
バケット間でのオブジェクトのコピー要求
 a| 
* ソースコピーに対しては、「いいえ」と指定します
* デスティネーションコピーについては、はい

 a| 
* ソースコピーに対しては、「いいえ」と指定します
* デスティネーションコピーについては、はい

 a| 
* ソースコピーについては、はい
* デスティネーションコピーについては、はい

 a| 
* ソースコピーについては、はい
* デスティネーションコピーについては、はい




 a| 
マルチパートアップロードの完了要求
 a| 
はい、アセンブルされたオブジェクトの場合
 a| 
はい、アセンブルされたオブジェクトの場合
 a| 
はい、アセンブルされたオブジェクトの場合
 a| 
はい、アセンブルされたオブジェクトの場合

|===
.手順
. ダッシュボードで* View Buckets *を選択するか、* storage（S3）*>* Buckets *を選択します。
. 表からバケット名を選択します。
+
バケットの詳細ページが表示されます。

. [Bucket options]タブで、[Last access time updates]*アコーディオンを選択します。
. 最終アクセス時間の更新を有効または無効にします。
. 「変更を保存」を選択します。

