---
permalink: tenant/ilm-policy-tags.html 
sidebar: sidebar 
keywords: how to assign ilm policy tag to bucket 
summary: オブジェクトストレージ要件に基づいてバケットに割り当てるILMポリシータグを選択します。 
---
= ILMポリシータグをバケットに適用する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
オブジェクトストレージ要件に基づいて、バケットに適用するILMポリシータグを選択します。

ILMポリシーは、オブジェクトデータの格納場所と一定期間後に削除するかどうかを制御します。グリッド管理者は、複数のアクティブポリシーを使用している場合に、ILMポリシーを作成してILMポリシータグに割り当てます。


NOTE: バケットのポリシータグは頻繁に再割り当てしないでください。そうしないと、パフォーマンスの問題が発生する可能性があり

.開始する前に
* を使用してTenant Managerにサインインしておきlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]ます。
* が設定されたユーザグループに属しているlink:tenant-management-permissions.html["rootアクセス、Manage All Buckets、View All Buckets権限"]必要があります。これらの権限は、グループポリシーまたはバケットポリシーの権限設定よりも優先されます。


.手順
. ダッシュボードで* View Buckets *を選択するか、* storage（S3）*>* Buckets *を選択します。
+
[Buckets]ページが表示されます。必要に応じて、任意の列で情報をソートしたり、リストを前後にページ移動したりできます。

. ILMポリシータグを割り当てるバケットの名前を選択します。
+
すでにタグが割り当てられているバケットに対するILMポリシータグの割り当てを変更することもできます。

+

NOTE: 「オブジェクト数」と「使用済みスペース」の値が概算値として表示されます。これらの推定値は、取り込みのタイミング、ネットワーク接続、ノードのステータスによって左右されます。バケットでバージョン管理が有効になっている場合は、削除したオブジェクトのバージョンがオブジェクト数に含まれます。

. [Bucket options]タブで、ILMポリシータグのアコーディオンを展開します。このアコーディオンは、グリッド管理者がカスタムポリシータグの使用を有効にしている場合にのみ表示されます。
. 各ポリシータグの概要を読んで、バケットに適用するタグを特定します。
+

CAUTION: バケットのILMポリシータグを変更すると、バケット内のすべてのオブジェクトのILMによる再評価がトリガーされます。新しいポリシーで一定期間オブジェクトが保持されると、古いオブジェクトは削除されます。

. バケットに割り当てるタグのラジオボタンを選択します。
. 「変更を保存」を選択します。ILMポリシーのタグ名のキーと値を使用して、バケットに新しいS3バケットタグが設定され `NTAP-SG-ILM-BUCKET-TAG`ます。
+

CAUTION: S3アプリケーションが誤って新しいバケットタグを上書きまたは削除しないようにしてください。バケットに新しいTagSetを適用するときにこのタグを省略すると、バケット内のオブジェクトはデフォルトのILMポリシーに照らして評価されます。

+

CAUTION: ILMポリシータグの設定と変更には、ILMポリシータグが検証されるTenant Manager APIまたはTenant Manager APIのみを使用します。S3 PutBucketTagging APIやS3 DeleteBucketTagging APIを使用してILMポリシータグを変更しないで `NTAP-SG-ILM-BUCKET-TAG`ください。

+

NOTE: バケットに割り当てられているポリシータグを変更すると、新しいILMポリシーを使用してオブジェクトが再評価される間、一時的にパフォーマンスに影響します。


