---
permalink: tenant/index.html 
sidebar: sidebar 
keywords: use tenant account 
summary: テナントアカウントでは、 Simple Storage Service （ S3 ） REST API または Swift REST API を使用して、 StorageGRID システムでオブジェクトの格納や読み出しを行うことができます。 
---
= テナントアカウントを使用する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
テナントアカウントでは、 Simple Storage Service （ S3 ） REST API または Swift REST API を使用して、 StorageGRID システムでオブジェクトの格納や読み出しを行うことができます。



== テナントアカウントとは何ですか？

各テナントアカウントには、フェデレーテッド / ローカルグループ、ユーザ、 S3 バケットまたは Swift コンテナ、オブジェクトがあります。

テナントアカウントを使用すると、格納されているオブジェクトをエンティティごとに分離できます。たとえば、次のようなユースケースでは複数のテナントアカウントを使用できます。

* * エンタープライズのユースケース： StorageGRID システムがエンタープライズ内で使用されている場合は、組織の部門ごとにグリッドのオブジェクトストレージを分けることができます。たとえば、マーケティング部門、カスタマーサポート部門、人事部門などのテナントアカウントが存在する場合があります。
+

NOTE: S3 クライアントプロトコルを使用する場合は、 S3 バケットとバケットポリシーを使用してエンタープライズ内の部門間でオブジェクトを分離することもできます。個別のテナントアカウントを作成する必要はありません。詳細については、を実装する手順を参照してくださいlink:../s3/bucket-and-group-access-policies.html["S3バケットとバケットポリシー"]。

* * サービスプロバイダのユースケース： * StorageGRID システムがサービスプロバイダによって使用されている場合は、ストレージをリースするエンティティごとにグリッドのオブジェクトストレージを分けることができます。たとえば、会社 A 、会社 B 、会社 C などのテナントアカウントを作成できます。




== テナントアカウントを作成する方法

テナントアカウントは、によって作成されlink:../admin/managing-tenants.html["グリッドマネージャを使用した StorageGRID のグリッド管理者"]ます。グリッド管理者は、テナントアカウントを作成する際に次の項目を指定します。

* テナント名、クライアントタイプ（S3）、オプションのストレージクォータなどの基本情報。
* テナントアカウントに対する権限（テナントアカウントがS3プラットフォームサービスを使用できるか、独自のアイデンティティソースを設定できるか、S3 Selectを使用できるか、グリッドフェデレーション接続を使用できるかなど）。
* テナントの初期ルートアクセス（StorageGRID システムがローカルグループとユーザ、アイデンティティフェデレーション、シングルサインオン（SSO）のいずれを使用しているかに基づく）。


また、 S3 テナントアカウントが規制要件に準拠する必要がある場合は、グリッド管理者が StorageGRID システムに対して S3 オブジェクトロック設定を有効にすることができます。S3 オブジェクトのロックを有効にすると、すべての S3 テナントアカウントで準拠バケットを作成、管理できます。



=== S3 テナントを設定する

のあとlink:../admin/creating-tenant-account.html["S3 テナントアカウントが作成されます"]、Tenant Managerにアクセスして次のタスクを実行できます。

* アイデンティティフェデレーションを設定する（グリッドとアイデンティティソースを共有する場合を除く）
* グループとユーザを管理します
* アカウントのクローン作成とグリッド間レプリケーションにグリッドフェデレーションを使用します
* S3 アクセスキーを管理します
* S3バケットを作成、管理します
* S3プラットフォームサービスを使用する
* S3 Select を使用する
* ストレージの使用状況を監視



TIP: S3バケットはTenant Managerを使用して作成および管理できますが、オブジェクトの取り込みと管理にはまたはをlink:use-s3-console.html["S3コンソール"]使用する必要がありますlink:../s3/index.html["S3 クライアント"]。
