---
permalink: tenant/manage-branch-buckets.html 
sidebar: sidebar 
keywords: how to create branch bucket 
summary: テナント マネージャを使用して、ブランチ バケットの詳細を作成および表示します。 
---
= ブランチバケットを管理する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
テナント マネージャを使用して、ブランチ バケットの詳細を作成および表示します。

.開始する前に
* テナントマネージャーにサインインするには、link:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"] 。
* ルートアクセス権を持つユーザーグループに属しているか、link:tenant-management-permissions.html["Manage All Buckets権限"] 。これらの権限は、グループまたはバケット ポリシーの権限設定をオーバーライドします。
* ブランチを作成したいベースバケットにはlink:../tenant/changing-bucket-versioning.html["バージョン管理が有効"]。
* あなたはベース バケットの所有者です。


.タスクの内容
ブランチ バケットについては次の情報に注意してください。

* バケットまたはオブジェクトのS3オブジェクトロックプロパティを設定する権限は、link:../s3/use-access-policies.html["バケットポリシーまたはグループポリシー"] 。
* ベース バケットのバージョン管理を一時停止すると、ベース バケットの内容はブランチ バケットに表示されなくなります。



CAUTION: ブランチ バケットを設定して作成した後は、設定を変更することはできません。



== ブランチバケットを作成する

.手順
. ダッシュボードで* View Buckets *を選択するか、* storage（S3）*>* Buckets *を選択します。
. ブランチを作成するバケット (「ベース バケット」) を選択します。
. バケットの詳細ページで、*ブランチ* > *ブランチ バケットの作成*を選択します。
+
ベース バケットでバージョン管理が有効になっていない場合、*ブランチ バケットの作成* ボタンは無効になります。





== 詳細を入力します

.手順
. ブランチ バケットの詳細を入力します。
+
[cols="1a,3a"]
|===
| フィールド | 製品説明 


 a| 
ブランチバケット名
 a| 
次の規則に準拠するブランチ バケットの名前:

** StorageGRID システム全体で（テナントアカウント内だけではなく）一意である必要があります。
** DNS に準拠している必要があります。
** 3文字以上63文字以下にする必要があります。
** 各ラベルの先頭と末尾の文字は小文字のアルファベットか数字にする必要があり、使用できる文字は小文字のアルファベット、数字、ハイフンのみです。
** 仮想ホスト形式の要求にピリオドを含めることはできません。ピリオドを使用すると、サーバワイルドカード証明書の検証で原因 の問題が発生します。


詳細については、を参照して https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html["バケットの命名規則に関する Amazon Web Services （ AWS ）のドキュメント"^]ください。

*注意*: ブランチ バケットを作成した後は、名前を変更することはできません。



 a| 
リージョン（ブランチバケットでは変更できません）
 a| 
ブランチ バケットのリージョン。

ブランチ バケットのリージョンはベース バケットのリージョンと一致する必要があるため、このフィールドはブランチ バケットでは無効になります。



 a| 
時間の前に
 a| 
ベース バケットに作成されたオブジェクト バージョンがブランチ バケットからアクセス可能になるまでのカットオフ時間。ブランチ バケットは、[Before] よりも前に作成されたオブジェクト バージョンへのアクセスを提供します。

「Before time」は経過した日付と時刻でなければなりません。将来の日付は指定できません。



 a| 
ブランチバケットタイプ
 a| 
** *読み取り/書き込み*: ブランチ バケット内のオブジェクトまたはオブジェクト バージョンを追加または削除できます。
** *読み取り専用*: ブランチ バケット内のオブジェクトを変更することはできません。


*注*: ブランチ バケットが空の場合にのみ、ブランチ バケット タイプを読み取り専用に設定できます。既存のブランチ バケットのタイプが読み取り/書き込みに設定されていて、まだ書き込んでいない場合は、タイプを読み取り専用に変更できます。

|===
. 「 * Continue * 」を選択します。




== オブジェクト設定を管理する（オプション）

ブランチ バケットのオブジェクト設定は、ベース バケット内のオブジェクト バージョンには影響しません。

.手順
. グローバル S3 オブジェクト ロック設定が有効になっている場合は、オプションでブランチ バケットの S3 オブジェクト ロックを有効にします。  S3 オブジェクトロックを有効にするには、ブランチバケットが読み取り/書き込みバケットである必要があります。
+
特定の規制要件を満たすためなど、オブジェクトを一定期間保持する必要がある場合にのみ、ブランチバケットの S3 オブジェクトロックを有効にします。  S3 オブジェクト ロックは、一定期間または無期限にオブジェクトが削除または上書きされるのを防ぐのに役立つ永続的な設定です。

+

CAUTION: バケットに対して S3 オブジェクトロック設定を有効にすると、無効にすることはできません。適切な権限を持つユーザーは誰でも、変更できないオブジェクトをブランチ バケットに追加できます。これらのオブジェクトまたはブランチ バケット自体を削除できない可能性があります。

. *S3 オブジェクトロックを有効にする* を選択した場合は、オプションでブランチバケットの *デフォルトの保持期間* を有効にします。
+

NOTE: グリッド管理者は、に対する権限をユーザに付与する必要がありますlink:../tenant/using-s3-object-lock.html["S3オブジェクトロックの特定の機能を使用する"]。

+
*デフォルトの保持* が有効になっている場合、ブランチ バケットに追加された新しいオブジェクトは、削除または上書きされないように自動的に保護されます。  *デフォルトの保持期間*設定は、独自の保持期間を持つオブジェクトには適用されません。

+
.. *デフォルトの保持*が有効になっている場合は、ブランチ バケットの *デフォルトの保持モード* を指定します。
+
[cols="1a,2a"]
|===
| デフォルトの保持モード | 製品説明 


 a| 
ガバナンス
 a| 
*** 権限を持つユーザ `s3:BypassGovernanceRetention`は、要求ヘッダーを使用して保持設定を省略でき `x-amz-bypass-governance-retention: true`ます。
*** これらのユーザは、retain-until-dateに達する前にオブジェクトバージョンを削除できます。
*** これらのユーザは、オブジェクトのretain-until-dateを増減、または削除できます。




 a| 
コンプライアンス
 a| 
*** retain-until-dateに達するまで、オブジェクトを削除できません。
*** オブジェクトのretain-until-dateは増やすことはできますが、減らすことはできません。
*** オブジェクトのretain-until-dateは、その日付に達するまで削除できません。


*注*：グリッド管理者が準拠モードの使用を許可する必要があります。

|===
.. *デフォルトの保持*が有効になっている場合は、ブランチ バケットの *デフォルトの保持期間* を指定します。
+
*デフォルトの保持期間* は、ブランチ バケットに追加された新しいオブジェクトが取り込まれた時点から保持される期間を示します。グリッド管理者によって設定されたテナントの最大保持期間以下の値を指定します。

+
A_maximum_retention periodは、グリッド管理者がテナントを作成するときに設定されます。指定できる値は1~100年です。_default_retention periodを設定する場合、最大保持期間に設定された値を超えることはできません。必要に応じて、最大保持期間を増減するようにグリッド管理者に依頼します。



. 必要に応じて、「容量制限を有効にする」を選択します。
+
容量制限は、ブランチ バケットに使用できる最大容量です。この値は物理的な量 (ディスク上のサイズ) ではなく、論理的な量 (オブジェクトのサイズ) を表します。

+
制限が設定されていない場合、ブランチ バケットの容量は無制限になります。参照link:../tenant/understanding-tenant-manager-dashboard.html#bucket-capacity-usage["ヨウリヨウセイケンシヨウ"]詳細についてはこちらをご覧ください。

+

NOTE: この設定は、ブランチ バケットに直接取り込まれたオブジェクトにのみ適用され、ブランチ バケットを介してベース バケットから表示されるオブジェクトには適用されません。

. 必要に応じて、「オブジェクト数の制限を有効にする」を選択します。
+
オブジェクト数の制限は、ブランチ バケットに含めることができるオブジェクトの最大数です。この値は論理量 (オブジェクト数) を表します。制限が設定されていない場合、オブジェクト数は無制限になります。

+

NOTE: この設定は、ブランチ バケットに直接取り込まれたオブジェクトにのみ適用され、ブランチ バケットを介してベース バケットから表示されるオブジェクトには適用されません。

. [ * バケットの作成 * ] を選択します。
+
ブランチ バケットが作成され、[バケット] ページのテーブルに追加されます。

. オプションで*バケットの詳細ページに移動*を選択してlink:viewing-s3-bucket-details.html["ブランチバケットの詳細を表示する"]追加の構成を実行します。
+
バケットの詳細ページでは、読み取り専用バケットの場合、オブジェクトの変更に関連する一部の構成オプションが無効になっています。


