---
permalink: tenant/manage-branch-buckets.html 
sidebar: sidebar 
keywords: how to create branch bucket 
summary: ブランチバケットは、バケット内に存在していたオブジェクトへのアクセスを提供します（ただし、そのオブジェクトがバケット内に存在している場合）。Tenant Managerを使用して、ブランチバケットを作成および表示します。 
---
= ブランチバケットの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ブランチバケットは、バケット内に存在していたオブジェクトへのアクセスを提供します（ただし、そのオブジェクトがバケット内に存在している場合）。Tenant Managerを使用して、ブランチバケットを作成および表示します。

ブランチバケットは、保護されたデータへのアクセスを提供しますが、バックアップとしては機能しません。データを引き続き保護するには、ベースバケットで次の機能を使用してください。

* link:../tenant/using-s3-object-lock.html["S3 オブジェクトのロック"]
* link:../admin/grid-federation-what-is-cross-grid-replication.html["グリッド間レプリケーション"]ベースバケット用
* link:../tenant/manage-bucket-policy.html["バケットポリシー"]バージョン管理されたバケットで古いオブジェクトバージョンをクリーンアップ


.タスクの内容
既存のバケットからブランチバケットを作成します。ブランチバケットを作成すると、そのバケットが作成された元のバケットがベースバケットと呼ばれます。また、別のブランチバケットからブランチバケットを作成することもできます。ベースバケットで処理を実行する場合、ブランチバケットの結果は、作成した処理とブランチバケットのタイプによって異なります。

ブランチバケットを使用して破損したオブジェクトを削除するには、破損が発生する前の時点からブランチバケットを作成し、破損したオブジェクトを含むベースバケットではなくブランチバケットをアプリケーションに指定します。


CAUTION: ブランチバケットはバックアップとしては機能しませんが、保護されたデータへのアクセスを提供します。データを保護するには、またはlink:../admin/grid-federation-what-is-cross-grid-replication.html["グリッド間レプリケーション"]を引き続き使用する必要がありlink:../ilm/managing-objects-with-s3-object-lock.html["S3 オブジェクトのロック"]ます。

ブランチバケットでは、グリッド間レプリケーションはサポートされていません。

.開始する前に
* を使用してTenant Managerにサインインしておきlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]ます。
* [Root access]または[Manage all buckets]が設定されたユーザグループに属している必要link:tenant-management-permissions.html["アクセス権"]があります。これらの権限は、グループまたはバケットポリシーの権限の設定よりも優先されます。
* 分岐の作成元となるベースバケットは、を持っていlink:../tenant/changing-bucket-versioning.html["バージョン管理が有効"]ます。
* あなたはベースバケットの所有者です。
+

NOTE: バケットまたはオブジェクトのS3オブジェクトロックプロパティを設定または変更する権限は、から付与できますlink:../s3/bucket-and-group-access-policies.html["バケットポリシーまたはグループポリシー"]。





== ブランチバケットを作成

.手順
. ダッシュボードで* View Buckets *を選択するか、* storage（S3）*>* Buckets *を選択します。
. ブランチの作成元となるバケット（「ベースバケット」）を選択します。
. バケットの詳細ページで、* branches *>* Create branch bucket *を選択します。
+
ベースバケットでバージョン管理が有効になっていない場合、* Create branch bucket *ボタンは無効になります。





== 詳細を入力します

.手順
. ブランチバケットの詳細を入力します。
+
[cols="1a,3a"]
|===
| フィールド | 製品説明 


 a| 
ブランチバケット名
 a| 
次のルールに準拠するブランチバケットの名前。

** StorageGRID システム全体で（テナントアカウント内だけではなく）一意である必要があります。
** DNS に準拠している必要があります。
** 3文字以上63文字以下にする必要があります。
** 各ラベルの先頭と末尾の文字は小文字のアルファベットか数字にする必要があり、使用できる文字は小文字のアルファベット、数字、ハイフンのみです。
** 仮想ホスト形式の要求にピリオドを含めることはできません。ピリオドを使用すると、サーバワイルドカード証明書の検証で原因 の問題が発生します。


詳細については、を参照して https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html["バケットの命名規則に関する Amazon Web Services （ AWS ）のドキュメント"^]ください。

*注*:ブランチバケットの作成後に名前を変更することはできません。



 a| 
リージョン（ブランチバケットでは変更できません）
 a| 
ブランチバケットのリージョン。

ブランチバケットのリージョンがベースバケットのリージョンと一致している必要があるため、このフィールドはブランチバケットでは無効になります。



 a| 
時間の前
 a| 
ベースバケットに作成されたオブジェクトバージョンがブランチバケットからアクセスできるようにするためのカットオフ時間。Branchバケットを使用すると、以前に作成されたオブジェクトバージョンにアクセスできます。



 a| 
分岐バケットタイプ
 a| 
** * Read-Write *：ブランチバケットのオブジェクトまたはオブジェクトバージョンを追加または削除できます。
** *読み取り専用*：ブランチバケット内のオブジェクトは変更できません。


|===
. 「 * Continue * 」を選択します。




== 設定の管理

ブランチバケットの設定は、ベースバケット内のオブジェクトバージョンには影響しません。

.手順
. グローバルなS3 Object Lock設定が有効になっている場合は、必要に応じてブランチバケットのS3 Object Lockを有効にします。S3 Object Lockを有効にするには、ブランチバケットが読み書き可能バケットである必要があります。
+
ブランチバケットのS3オブジェクトロックは、特定の規制要件を満たすためにオブジェクトを一定期間保持する必要がある場合にのみ有効にしてください。S3オブジェクトロックは永続的な設定で、オブジェクトの削除や上書きを一定期間または無期限に防ぐことができます。

+

CAUTION: バケットでS3オブジェクトロックの設定を有効にしたあとに無効にすることはできません。適切な権限を持つユーザは、変更できないオブジェクトをブランチバケットに追加できます。これらのオブジェクトやブランチバケット自体を削除できない場合があります。

. [Enable S3 Object Lock]*を選択した場合は、必要に応じてブランチバケットの* Default retention *を有効にします。
+

NOTE: グリッド管理者は、に対する権限をユーザに付与する必要がありますlink:../tenant/using-s3-object-lock.html["S3オブジェクトロックの特定の機能を使用する"]。

+
default retention *を有効にすると、ブランチバケットに追加された新しいオブジェクトが自動的に削除または上書きされなくなります。デフォルトの保持*設定は、独自の保持期間を持つオブジェクトには適用されません。

+
.. * default retention *が有効になっている場合は、ブランチバケットに* default retention mode *を指定します。
+
[cols="1a,2a"]
|===
| デフォルトの保持モード | 製品説明 


 a| 
ガバナンス
 a| 
*** 権限を持つユーザ `s3:BypassGovernanceRetention`は、要求ヘッダーを使用して保持設定を省略でき `x-amz-bypass-governance-retention: true`ます。
*** これらのユーザは、retain-until-dateに達する前にオブジェクトバージョンを削除できます。
*** これらのユーザは、オブジェクトのretain-until-dateを増減、または削除できます。




 a| 
コンプライアンス
 a| 
*** retain-until-dateに達するまで、オブジェクトを削除できません。
*** オブジェクトのretain-until-dateは増やすことはできますが、減らすことはできません。
*** オブジェクトのretain-until-dateは、その日付に達するまで削除できません。


*注*：グリッド管理者が準拠モードの使用を許可する必要があります。

|===
.. default retention *が有効になっている場合は、ブランチバケットの* default retention period *を指定します。
+
Default retention period *は、ブランチバケットに追加された新しいオブジェクトを取り込んだ時点から保持する期間を示します。グリッド管理者が設定したテナントの最大保持期間以下の値を指定します。

+
A_maximum_retention periodは、グリッド管理者がテナントを作成するときに設定されます。指定できる値は1~100年です。_default_retention periodを設定する場合、最大保持期間に設定された値を超えることはできません。必要に応じて、最大保持期間を増減するようにグリッド管理者に依頼します。



. [[capacity-limit]]必要に応じて、*[容量制限を有効にする]*を選択します。
+
容量制限は、ブランチバケットで使用可能な最大容量です。この値は、物理容量（ディスク上のサイズ）ではなく、論理容量（オブジェクトサイズ）を表します。

+
制限が設定されていない場合、ブランチバケットの容量は無制限になります。詳細については、を参照してください link:../tenant/understanding-tenant-manager-dashboard.html#bucket-capacity-usage["ヨウリヨウセイケンシヨウ"] 。

+

NOTE: この設定は、ブランチバケットに直接取り込まれたオブジェクトにのみ適用され、ベースバケットからブランチバケットを介して表示されるオブジェクトには適用されません。

. 必要に応じて、*[オブジェクト数制限を有効にする]*を選択します。
+
オブジェクト数制限は、ブランチバケットに含めることができるオブジェクトの最大数です。この値は論理量（オブジェクト数）を表します。制限が設定されていない場合、オブジェクト数は無制限になります。

+

NOTE: この設定は、ブランチバケットに直接取り込まれたオブジェクトにのみ適用され、ベースバケットからブランチバケットを介して表示されるオブジェクトには適用されません。

. [ * バケットの作成 * ] を選択します。
+
ブランチバケットが作成され、[Buckets]ページのテーブルに追加されます。

. 必要に応じて、*[Go to bucket details page]*を選択しlink:viewing-s3-bucket-details.html["ブランチバケットの詳細を表示"]て追加の設定を実行します。
+
[Bucket details]ページで、オブジェクトの変更に関連する一部の設定オプションが読み取り専用バケットで無効になっています。


