---
permalink: tenant/tenant-management-permissions.html 
sidebar: sidebar 
keywords: tenant management permissions 
summary: テナントグループを作成する前に、そのグループに割り当てる権限を検討してください。テナント管理権限は、 Tenant Manager またはテナント管理 API を使用してユーザが実行できるタスクを決定します。ユーザは 1 つ以上のグループに属することができます。権限は、ユーザが複数のグループに属している場合に累積されます。 
---
= テナント管理権限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
テナントグループを作成する前に、そのグループに割り当てる権限を検討してください。テナント管理権限は、 Tenant Manager またはテナント管理 API を使用してユーザが実行できるタスクを決定します。ユーザは 1 つ以上のグループに属することができます。権限は、ユーザが複数のグループに属している場合に累積されます。

Tenant Manager にサインインするには、またはテナント管理 API を使用するには、少なくとも 1 つの権限が割り当てられたグループにユーザが属している必要があります。サインインできるすべてのユーザは、次のタスクを実行できます。

* ダッシュボードを表示します
* 自分のパスワードを変更する（ローカルユーザの場合）


すべての権限について、グループのアクセスモード設定によって、ユーザが設定を変更して処理を実行できるかどうか、またはユーザが関連する設定と機能のみを表示できるかどうかが決まります。


NOTE: ユーザが複数のグループに属していて、いずれかのグループが読み取り専用に設定されている場合、選択したすべての設定と機能に読み取り専用でアクセスできます。

グループには次の権限を割り当てることができます。

[cols="1a,3a,3a"]
|===
| 権限 | 製品説明 | 詳細 


 a| 
ルートアクセス
 a| 
Tenant Manager とテナント管理 API へのフルアクセスを提供します。
 a| 



 a| 
自分のS3クレデンシャルを管理します
 a| 
ユーザに自分の S3 アクセスキーの作成および削除を許可します。
 a| 
この権限がないユーザには、* storage（S3）*>* My S3 access keys *メニューオプションが表示されません。



 a| 
すべてのバケットを表示
 a| 
ユーザーがすべてのバケットとバケット構成を表示できるようにします。
 a| 
View All Buckets権限またはManage All Buckets権限がないユーザには、* Buckets *メニューオプションは表示されません。

この権限は、すべてのバケットの管理権限に置き換えられます。これは、S3 クライアントまたは S3 コンソールで使用される S3 バケットまたはグループ ポリシーには影響しません。



 a| 
すべてのバケットを管理
 a| 
ユーザーがテナント マネージャーとテナント管理 API を使用して、S3 バケットまたはグループ ポリシーに関係なく、S3 バケットを作成および削除したり、テナント アカウント内のすべての S3 バケットの設定を管理したりできるようにします。
 a| 
View All Buckets権限またはManage All Buckets権限がないユーザには、* Buckets *メニューオプションは表示されません。

この権限は、「すべてのバケットを表示」権限よりも優先されます。これは、S3 クライアントまたは S3 コンソールで使用される S3 バケットまたはグループ ポリシーには影響しません。



 a| 
エンドポイントを管理します
 a| 
ユーザに、テナントマネージャまたはテナント管理APIを使用して、StorageGRID プラットフォームサービスのデスティネーションとして使用するプラットフォームサービスエンドポイントを作成または編集することを許可します。
 a| 
この権限がないユーザーには、*プラットフォームサービスエンドポイント*メニューオプションは表示されません。



 a| 
S3コンソールタブを使用
 a| 
View All Buckets権限またはManage All Buckets権限と組み合わせると、ユーザはバケットの詳細ページにあるS3 Consoleタブでオブジェクトの表示と管理を行うことができます。
 a| 

|===