---
permalink: tenant/tenant-management-permissions.html 
sidebar: sidebar 
keywords: tenant management permissions 
summary: テナントグループを作成する前に、そのグループに割り当てる権限を検討してください。テナント管理権限は、 Tenant Manager またはテナント管理 API を使用してユーザが実行できるタスクを決定します。ユーザは 1 つ以上のグループに属することができます。権限は、ユーザが複数のグループに属している場合に累積されます。 
---
= テナント管理権限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
テナントグループを作成する前に、そのグループに割り当てる権限を検討してください。テナント管理権限は、 Tenant Manager またはテナント管理 API を使用してユーザが実行できるタスクを決定します。ユーザは 1 つ以上のグループに属することができます。権限は、ユーザが複数のグループに属している場合に累積されます。

Tenant Manager にサインインするには、またはテナント管理 API を使用するには、少なくとも 1 つの権限が割り当てられたグループにユーザが属している必要があります。サインインできるすべてのユーザは、次のタスクを実行できます。

* ダッシュボードを表示します
* 自分のパスワードを変更する（ローカルユーザの場合）


すべての権限について、グループのアクセスモード設定によって、ユーザが設定を変更して処理を実行できるかどうか、またはユーザが関連する設定と機能のみを表示できるかどうかが決まります。


NOTE: ユーザが複数のグループに属していて、いずれかのグループが読み取り専用に設定されている場合、選択したすべての設定と機能に読み取り専用でアクセスできます。

グループには次の権限を割り当てることができます。S3 テナントと Swift テナントではグループの権限が異なるので注意してください。

[cols="1a,3a,3a"]
|===
| 権限 | 製品説明 | 詳細 


 a| 
ルートアクセス
 a| 
Tenant Manager とテナント管理 API へのフルアクセスを提供します。
 a| 
Swiftユーザがテナントアカウントにサインインするには、Root Access権限が必要です。



 a| 
管理者
 a| 
Swift テナントのみ。このテナントアカウントの Swift コンテナとオブジェクトへのフルアクセスを提供します
 a| 
SwiftユーザがSwift REST APIを使用して処理を実行するには、Swift Administrator権限が必要です。



 a| 
自分のS3クレデンシャルを管理します
 a| 
ユーザに自分の S3 アクセスキーの作成および削除を許可します。
 a| 
この権限がないユーザには、* storage（S3）*>* My S3 access keys *メニューオプションが表示されません。



 a| 
すべてのバケットを表示
 a| 
* S3テナント*：すべてのバケットとバケットの設定を表示できます。

* Swiftテナント*：Swiftユーザに、テナント管理APIを使用してすべてのコンテナとコンテナ設定を表示することを許可します。
 a| 
View All Buckets権限またはManage All Buckets権限がないユーザには、* Buckets *メニューオプションは表示されません。

この権限は、Manage All Buckets権限よりも優先されます。S3クライアントまたはS3コンソールで使用されるS3バケットポリシーやグループポリシーには影響しません。

この権限をSwiftグループに割り当てるには、テナント管理APIを使用する必要があります。Tenant Managerを使用してSwiftグループにこの権限を割り当てることはできません。



 a| 
すべてのバケットを管理
 a| 
* S3テナント*：S3のバケットまたはグループポリシーに関係なく、テナントマネージャとテナント管理APIを使用してS3バケットを作成および削除し、テナントアカウント内のすべてのS3バケットの設定を管理することをユーザに許可します。

* Swiftテナント*：Swiftユーザにテナント管理APIを使用してSwiftコンテナの整合性を制御することを許可します。
 a| 
View All Buckets権限またはManage All Buckets権限がないユーザには、* Buckets *メニューオプションは表示されません。

この権限は、View All Buckets権限よりも優先されます。S3クライアントまたはS3コンソールで使用されるS3バケットポリシーやグループポリシーには影響しません。

この権限をSwiftグループに割り当てるには、テナント管理APIを使用する必要があります。Tenant Managerを使用してSwiftグループにこの権限を割り当てることはできません。



 a| 
エンドポイントを管理します
 a| 
ユーザに、テナントマネージャまたはテナント管理APIを使用して、StorageGRID プラットフォームサービスのデスティネーションとして使用するプラットフォームサービスエンドポイントを作成または編集することを許可します。
 a| 
この権限がないユーザーには、*プラットフォームサービスエンドポイント*メニューオプションは表示されません。



 a| 
S3コンソールタブを使用
 a| 
View All Buckets権限またはManage All Buckets権限と組み合わせると、ユーザはバケットの詳細ページにあるS3 Consoleタブでオブジェクトの表示と管理を行うことができます。
 a| 

|===