---
permalink: tenant/understanding-cloudmirror-replication-service.html 
sidebar: sidebar 
keywords: cloudmirror replication 
summary: StorageGRID で、ある S3 バケットに追加されたオブジェクトを指定して 1 つ以上のデスティネーションバケットにレプリケートする必要がある場合は、そのバケットに対して CloudMirror レプリケーションを有効にすることができます。 
---
= CloudMirrorレプリケーションサービスについて理解する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3バケットに追加されたオブジェクトを指定して1つ以上の外部のデスティネーションバケットにStorageGRIDでレプリケートする場合は、あるS3バケットに対してCloudMirrorレプリケーションを有効にすることができます。

たとえば、 CloudMirror レプリケーションを使用して特定の顧客レコードを Amazon S3 にミラーリングし、 AWS サービスを利用してデータを分析することができます。


NOTE: ソースバケットで S3 オブジェクトのロックが有効になっている場合、 CloudMirror レプリケーションはサポートされません。



== CloudMirrorとILM

CloudMirrorレプリケーションは、グリッドのアクティブなILMポリシーとは独立して動作します。CloudMirror サービスは、ソースバケットに格納された時点でオブジェクトをレプリケートし、できるだけ早くデスティネーションバケットに配信します。レプリケートオブジェクトの配信は、オブジェクトの取り込みが成功したときにトリガーされます。



== CloudMirrorとグリッド間レプリケーション

CloudMirrorレプリケーションには、クロスグリッドレプリケーション機能と重要な類似点と相違点があります。を参照してください link:../admin/grid-federation-compare-cgr-to-cloudmirror.html["グリッド間レプリケーションとCloudMirrorレプリケーションを比較してください"]。



== CloudMirrorおよびS3バケット

通常、 CloudMirror レプリケーションは外部の S3 バケットをデスティネーションとして使用するように設定します。ただし、他の StorageGRID 環境や任意の S3 互換サービスを使用するようにレプリケーションを設定することもできます。

既存のバケット:: 既存のバケットに対してCloudMirrorレプリケーションを有効にすると、そのバケットに追加された新しいオブジェクトのみがレプリケートされます。バケット内の既存のオブジェクトはレプリケートされません。既存のオブジェクトのレプリケーションを強制的に実行するには、オブジェクトのコピーを実行して既存のオブジェクトのメタデータを更新します。
+
--

NOTE: CloudMirrorレプリケーションを使用してオブジェクトをAmazon S3デスティネーションにコピーする場合は、Amazon S3で各PUT要求ヘッダー内のユーザ定義メタデータのサイズが2KBに制限されることに注意してください。オブジェクトのユーザ定義メタデータが 2KB を超える場合、そのオブジェクトはレプリケートされません。

--
複数のデスティネーションバケット:: 1つのバケット内のオブジェクトを複数のデスティネーションバケットにレプリケートするには、レプリケーション設定XMLで各ルールのデスティネーションを指定します。オブジェクトを複数のバケットに同時にレプリケートすることはできません。
バージョン管理に対応している/していないバケット:: バージョン管理に対応しているバケットとそうでないバケットでCloudMirrorレプリケーションを設定できます。デスティネーションバケットは、バージョン管理に対応している場合としていない場合があります。バージョン管理に対応しているバケットとしていないバケットを組み合わせて使用することができます。たとえば、バージョン管理に対応しているバケットをバージョン管理に対応していないソースバケットのデスティネーションとして指定することも、その逆を指定することもできます。また、バージョン管理に対応していないバケット間でもレプリケートできます。




== 削除、レプリケーションループ、およびイベント

削除の動作:: は、Amazon S3サービスのCross-Region Replication（CRR；クロスリージョンレプリケーション）の削除動作と同じです。ソースバケット内のオブジェクトを削除しても、デスティネーションのレプリケートオブジェクトは削除されません。ソースとデスティネーションの両方のバケットがバージョン管理に対応している場合は、削除マーカーがレプリケートされます。デスティネーションバケットがバージョン管理に対応していない場合、ソースバケット内のオブジェクトを削除しても削除マーカーはデスティネーションバケットにレプリケートされず、デスティネーションオブジェクトも削除されません。
レプリケーションループからの保護:: StorageGRIDは、デスティネーションバケットにレプリケートされたオブジェクトを「レプリカ」としてマークします。デスティネーションStorageGRIDバケットはレプリカとしてマークされたオブジェクトを再びレプリケートしないため、誤ってレプリケーションがループすることはありません。このレプリカマーキングはStorageGRIDの内部機能であり、Amazon S3バケットをデスティネーションとして使用するときにAWS CRRを使用することを妨げません。
+
--

NOTE: レプリカをマークするために使用されるカスタムヘッダーはです `x-ntap-sg-replica`。このマーキングは ' カスケード・ミラーを防止しますStorageGRID では、2つのグリッド間の双方向CloudMirrorがサポートされます。

--
デスティネーションバケットのイベント:: デスティネーションバケット内のイベントは一意であることや順序が保証されるわけではありません。確実に配信することを目的とした処理の結果として、ソースオブジェクトの同一のコピーが複数デスティネーションに配信されることがあります。まれに、複数の異なる StorageGRID サイトから同じオブジェクトが同時に更新された場合、デスティネーションバケットでの処理の順序がソースバケットでのイベントの順序と一致しないことがあります。

