---
permalink: tenant/use-s3-console.html 
sidebar: sidebar 
keywords: how to use s3 console 
summary: S3コンソールを使用して、S3バケット内のオブジェクトを表示および管理できます。 
---
= S3コンソールを使用
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3コンソールを使用して、S3バケット内のオブジェクトを表示および管理できます。

S3コンソールでは、次の操作を実行できます。

* アップロード、ダウンロード、名前変更、コピー、移動、 オブジェクトの削除
* オブジェクトバージョンの表示、リバート、ダウンロード、削除
* プレフィックスでオブジェクトを検索
* オブジェクトタグを管理します
* オブジェクトのメタデータを表示します
* 表示、作成、名前変更、コピー、移動、 フォルダの削除


[NOTE]
====
S3コンソールでは、最も一般的なケースのユーザエクスペリエンスが向上しています。すべての状況において、CLIやAPIの処理に代わるものではありません。

S3コンソールを使用すると処理に時間がかかりすぎる場合（分や時間など）は、次の点を考慮してください。

* 選択したオブジェクトの数を減らす
* グラフィカルでない方法（APIまたはCLI）を使用したデータへのアクセス


====
.開始する前に
* を使用してTenant Managerにサインインしておきlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]ます。
* オブジェクトを管理する場合は、Root Access権限のあるユーザグループに属している必要があります。または、Use S3 Console Tab権限とView All Buckets権限またはManage All Buckets権限のいずれかのユーザグループに属している必要があります。を参照して link:tenant-management-permissions.html["テナント管理権限"]
* ユーザーに対して S3 グループまたはバケット ポリシーが設定されています。見るlink:../s3/use-access-policies.html["バケットとグループのアクセスポリシーを使用"] 。
* ユーザのアクセスキー ID とシークレットアクセスキーを確認しておきます。必要に応じて、この情報を含むファイルが作成され `.csv`ます。を参照してくださいlink:creating-your-own-s3-access-keys.html["アクセスキーの作成手順"]。


.手順
. *ストレージ* > *バケット* > *_バケット名_* を選択します。
. [S3][Console]タブを選択します。
. アクセスキーIDとシークレットアクセスキーをフィールドに貼り付けます。それ以外の場合は、*アクセスキーのアップロード*を選択してファイルを選択し `.csv`ます。
. 「サインイン」を選択します。
. バケットオブジェクトのテーブルが表示されます。必要に応じてオブジェクトを管理できます。


.追加情報
* *接頭辞で検索*：接頭辞検索機能は、現在のフォルダに対して特定の単語で始まるオブジェクトのみを検索します。検索には、他の場所でその単語を含むオブジェクトは含まれません。このルールは、フォルダ内のオブジェクトも環境します。たとえば、を検索する `folder1/folder2/somefile-`と、フォルダ内にあり、で始まる `somefile-`オブジェクトが返され `folder1/folder2/`ます。
* *ドラッグアンドドロップ*:コンピューターのファイルマネージャからS3コンソールにファイルをドラッグアンドドロップできます。ただし、フォルダをアップロードすることはできません。
* *フォルダの操作*:フォルダを移動、コピー、または名前変更すると、フォルダ内のすべてのオブジェクトが一度に1つずつ更新されるため、時間がかかる場合があります。
* *バケットのバージョン管理が無効な場合の完全削除*：バージョン管理が無効なバケット内のオブジェクトを上書きまたは削除すると、処理は永続的に実行されます。を参照して link:changing-bucket-versioning.html["バケットのオブジェクトのバージョン管理を変更する"]

