---
permalink: tenant/using-storagegrid-tenant-account.html 
sidebar: sidebar 
keywords: how to use tenant account 
summary: テナントアカウントを使用すると、Simple Storage Service（S3 \）REST APIを使用して、StorageGRIDシステムでオブジェクトの格納や読み出しを行うことができます。 
---
= StorageGRID テナントアカウントを使用する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
テナントアカウントを使用すると、Simple Storage Service（S3）REST APIを使用して、StorageGRIDシステム内のオブジェクトの格納と読み出しを行うことができます。

各テナントアカウントには、フェデレーテッド/ローカルグループ、ユーザ、S3バケット、オブジェクトがあります。


TIP: このバージョンのドキュメントサイトからSwiftの詳細が削除されました。を参照してください https://docs.netapp.com/us-en/storagegrid-118/tenant/using-storagegrid-tenant-account.html["StorageGRID 11.8：StorageGRIDテナントアカウントを使用"^]

必要に応じて、テナントアカウントを使用して、格納されているオブジェクトをエンティティごとに分離できます。たとえば、次のようなユースケースでは複数のテナントアカウントを使用できます。

* * エンタープライズのユースケース： StorageGRID システムがエンタープライズ内で使用されている場合は、組織の部門ごとにグリッドのオブジェクトストレージを分けることができます。たとえば、マーケティング部門、カスタマーサポート部門、人事部門などのテナントアカウントが存在する場合があります。
+

NOTE: S3 クライアント プロトコルを使用する場合は、S3 バケットとバケット ポリシーを使用して、企業内の部門間でオブジェクトを分離することもできます。個別のテナント アカウントを作成する必要はありません。実装手順を参照link:../s3/use-access-policies.html["S3バケットとバケットポリシー"]詳細についてはこちらをご覧ください。

* * サービスプロバイダのユースケース： * StorageGRID システムがサービスプロバイダによって使用されている場合は、ストレージをリースするエンティティごとにグリッドのオブジェクトストレージを分けることができます。たとえば、会社 A 、会社 B 、会社 C などのテナントアカウントを作成できます。




== テナントアカウントを作成する

テナントアカウントは、 StorageGRID のグリッド管理者がグリッドマネージャを使用して作成します。グリッド管理者は、テナントアカウントを作成する際に次の情報を指定します。

* テナントの表示名（テナントのアカウントIDは自動的に割り当てられ、変更できません）。
* テナントアカウントでS3プロトコルとSwiftプロトコルのどちらを使用するか。
* S3 テナントアカウントの場合：テナントアカウントにプラットフォームサービスの使用を許可するかどうか。プラットフォームサービスの使用が許可されている場合は、グリッドがその使用をサポートするように設定されている必要があります。
* 必要に応じて、テナントアカウントのストレージクォータ -- テナントのオブジェクトで使用可能な最大ギガバイト数、テラバイト数、ペタバイト数。テナントのストレージクォータは、物理容量（ディスクのサイズ）ではなく、論理容量（オブジェクトのサイズ）を表します。
* StorageGRID システムでアイデンティティフェデレーションが有効になっている場合は、テナントアカウントを設定するための Root アクセス権限が割り当てられているフェデレーテッドグループ。
* StorageGRID システムでシングルサインオン（ SSO ）が使用されていない場合は、テナントアカウントが独自のアイデンティティソースを使用するか、グリッドのアイデンティティソースを共有するか、およびテナントのローカル root ユーザの初期パスワード。


また、 S3 テナントアカウントが規制要件に準拠する必要がある場合は、グリッド管理者が StorageGRID システムに対して S3 オブジェクトロック設定を有効にすることができます。S3 オブジェクトのロックを有効にすると、すべての S3 テナントアカウントで準拠バケットを作成、管理できます。



== S3 テナントを設定する

S3 テナントアカウントが作成されたら、 Tenant Manager にアクセスして次のタスクを実行できます。

* アイデンティティフェデレーションの設定（グリッドとアイデンティティソースを共有する場合を除く）、またはローカルグループおよびユーザの作成
* S3 アクセスキーの管理
* 準拠バケットを含む S3 バケットを作成、管理します
* プラットフォームサービスの使用（有効な場合）
* ストレージ使用状況を監視しています



TIP: Tenant Manager を使用して S3 バケットを作成および管理できますが、オブジェクトを取り込んで管理するには、 S3 アクセスキーを取得し、 S3 REST API を使用する必要があります。

.関連情報
* link:../admin/index.html["StorageGRID の管理"]
* link:../s3/index.html["S3 REST APIを使用する"]

