---
permalink: tenant/viewing-s3-bucket-details.html 
sidebar: sidebar 
keywords: how to view bucket details 
summary: テナントアカウント内のバケットを表示できます。 
---
= バケットの詳細を表示します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
テナントアカウント内のバケットを表示できます。

.開始する前に
* を使用してTenant Managerにサインインしておきlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]ます。
* が設定されたユーザグループに属しているlink:tenant-management-permissions.html["rootアクセス、Manage All Buckets、View All Buckets権限"]必要があります。これらの権限は、グループポリシーまたはバケットポリシーの権限設定よりも優先されます。


.手順
. ダッシュボードで* View Buckets *を選択するか、* storage（S3）*>* Buckets *を選択します。
+
[Buckets]ページが表示されます。

. 各バケットの概要テーブルを確認します。
+
必要に応じて、任意の列で情報をソートしたり、リストを前後にページ移動したりできます。

+

NOTE: 表示される[Object Count]、[Space Used]、および[Usage]の値は推定値です。これらの推定値は、取り込みのタイミング、ネットワーク接続、ノードのステータスによって左右されます。バケットでバージョン管理が有効になっている場合は、削除したオブジェクトのバージョンがオブジェクト数に含まれます。

+
名前:: バケットの一意の名前。変更することはできません。
有効な機能:: バケットで有効になっている機能のリスト。
S3 オブジェクトのロック:: バケットでS3オブジェクトロックが有効になっているかどうか。
+
--
この列は、グリッドでS3オブジェクトロックが有効になっている場合にのみ表示されます。この列には、古い準拠バケットの情報も表示されます。

--
地域:: バケットのリージョン。変更できません。この列はデフォルトでは非表示になっています。
オブジェクト数:: このバケット内のオブジェクトの数。バケットでバージョン管理が有効になっている場合は、最新でないオブジェクトバージョンがこの値に含まれます。
+
--
オブジェクトが追加または削除されたときに、この値がすぐに更新されないことがあります。

--
使用済みスペース:: バケット内のすべてのオブジェクトの論理サイズ。論理サイズには、レプリケートコピーやイレイジャーコーディングコピー、またはオブジェクトメタデータに必要な実際のスペースは含まれていません。
+
--
この値の更新には最大10分かかることがあります。

--
使用法:: バケットの容量制限に対して使用されている割合（設定されている場合）。
+
--
使用量の値は内部の見積もりに基づいており、場合によっては超過する可能性があります。たとえば、StorageGRIDはテナントがオブジェクトのアップロードを開始すると容量制限をチェックし（設定されている場合）、テナントが容量制限を超えた場合はこのバケットへの新しい取り込みを拒否します。ただし、StorageGRIDでは、容量制限を超えたかどうかを判断する際に、現在のアップロードのサイズは考慮されません。オブジェクトが削除されると、容量制限の使用量が再計算されるまで、テナントが新しいオブジェクトをこのバケットにアップロードできなくなることがあります。計算には10分以上かかることがあります。

この値は論理サイズを示し、オブジェクトとそのメタデータの格納に必要な物理サイズではありません。

--
容量:: バケットの容量制限（設定されている場合）。
作成日:: バケットが作成された日時。この列はデフォルトでは非表示になっています。


. 特定のバケットの詳細を表示するには、テーブルでバケット名を選択します。
+
.. Webページの上部にある概要情報を表示して、バケットの詳細（リージョンやオブジェクト数など）を確認します。
.. 容量制限の使用状況とオブジェクト数制限の使用状況を示すバーを確認します。使用率が100%または100%に近い場合は、制限値を増やすか、一部のオブジェクトを削除することを検討してください。
.. 必要に応じて、*[Delete objects in bucket]*および*[Delete bucket]*を選択します。
+
[CAUTION]
====
これらの各オプションを選択する際に表示される注意事項に細心の注意を払ってください。詳細については、以下を参照してください。

*** link:deleting-s3-bucket-objects.html["バケット内のすべてのオブジェクトを削除する"]
*** link:deleting-s3-bucket.html["バケットを削除する"]（バケットは空にする必要があります）


====
.. 必要に応じて、各タブでバケットの設定を表示または変更します。
+
*** * S3コンソール*：バケットのオブジェクトを表示します。詳細については、を参照してください link:use-s3-console.html["S3コンソールを使用"]。
*** *バケットオプション*：オプション設定を表示または変更します。S3オブジェクトロックなどの一部の設定は、バケットの作成後に変更できません。
+
**** link:manage-bucket-consistency.html["バケットの整合性の管理"]
**** link:enabling-or-disabling-last-access-time-updates.html["最終アクセス時間の更新"]
**** link:../tenant/creating-s3-bucket.html#capacity-limit["容量制限"]
**** link:../tenant/creating-s3-bucket.html#object-count-limit["オブジェクト数の制限"]
**** link:changing-bucket-versioning.html["オブジェクトのバージョン管理"]
**** link:using-s3-object-lock.html["S3 オブジェクトのロック"]
**** link:update-default-retention-settings.html["デフォルトのバケット保持"]
**** link:grid-federation-manage-cross-grid-replication.html["グリッド間レプリケーションを管理します"]（テナントに許可されている場合）


*** *プラットフォームサービス*：link:considerations-for-platform-services.html["プラットフォームサービスを管理します"]（テナントで許可されている場合）
*** *バケットアクセス*：オプション設定を表示または変更します。特定のアクセス権限が必要です。
+
**** 他のドメインにあるWebアプリケーションからバケットとバケット内のオブジェクトにアクセスできるようにを設定しますlink:configuring-cross-origin-resource-sharing-for-buckets-and-objects.html["バケットとオブジェクトのCORS"]。
**** link:../tenant/manage-bucket-policy.html["ユーザアクセスの制御"]（S3バケットとそのバケット内のオブジェクト）。


*** *ブランチ*:バケットのブランチバケットのリストを表示します。link:../tenant/manage-branch-buckets.html["新しいブランチバケットを作成するか、ブランチバケットを管理します。"]です。





