---
permalink: vmware/automating-grid-node-deployment-in-vmware-vsphere.html 
sidebar: sidebar 
keywords: how to automate installation 
summary: VMware OVF Toolを使用すると、グリッドノードの導入を自動化できます。StorageGRID の設定を自動化することもできます。 
---
= インストールの自動化（ VMware ）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware OVF Toolを使用すると、グリッドノードの導入を自動化できます。StorageGRID の設定を自動化することもできます。



== グリッドノードの導入を自動化

VMware OVF Toolを使用すると、グリッドノードの導入を自動化できます。

.開始する前に
* Bash 3.2 以降が搭載された Linux / UNIX システムにアクセスできるようにしておきます。
* VMware vSphereとvCenterを使用している場合
* VMware OVF Tool 4.1 をインストールし、正しく設定しておきます。
* OVFツールを使用してVMware vSphereにアクセスするためのユーザ名とパスワードを確認しておきます。
* OVFファイルからVMを導入して電源をオンにするための十分な権限と、VMに接続するための追加ボリュームを作成するための権限が必要です。詳細については、のドキュメントを参照してください `ovftool`。
* StorageGRID 仮想マシンを導入する vSphere 内の場所の仮想インフラ（ VI ） URL を確認しておきます。この URL は通常、 vApp またはリソースプールです。例： `vi://vcenter.example.com/vi/sgws`
+

NOTE: この値は、VMwareユーティリティを使用して確認でき `ovftool`ます（詳細についてはのドキュメントを参照してください `ovftool`）。

+

NOTE: vApp に導入する場合、初回は仮想マシンが自動的に起動されないため、手動で電源をオンにする必要があります。

* 導入構成ファイルに必要なすべての情報を収集しておきます。詳細は、を参照してくださいlink:collecting-information-about-your-deployment-environment.html["導入環境に関する情報を収集します"]。
* VMware 用インストールアーカイブに含まれている次のファイルに StorageGRID からアクセスできるようにしておきます。


[cols="1a,1a"]
|===
| ファイル名 | 製品説明 


| NetApp-SG-version-sha.vmdk  a| 
グリッドノード仮想マシンを作成するためのテンプレートとして使用される仮想マシンディスクファイル。

*注：*このファイルは、ファイルおよび `.mf`ファイルと同じフォルダにある必要があります `.ovf`。



| vsphere-primary-admin.ovf vsphere-primary-admin.mf  a| 
(`.mf`プライマリ管理ノードを導入するためのOpen Virtualization Formatテンプレートファイル）(`.ovf`とマニフェストファイル



| vsphere-non-primary-admin.ovf vsphere-non-primary-admin.mf  a| 
テンプレートファイル(`.ovf`）とマニフェストファイル(`.mf`）。非プライマリ管理ノードを導入するためのものです。



| vsphere-gateway.ovf vsphere-gateway.mf  a| 
テンプレートファイル(`.ovf`）とマニフェストファイル(`.mf`）を使用してゲートウェイノードを導入します。



| vsphere-storage.ovf vsphere-storage.mf  a| 
(`.mf`仮想マシンベースのストレージノードを導入するためのテンプレートファイル(`.ovf`とマニフェストファイル）



| deploy-vsphere-ovftool.sh  a| 
仮想グリッドノードの導入を自動化するための Bash シェルスクリプト。



| deploy-vsphere-ovftool-sample.ini  a| 
スクリプトで使用する構成ファイルの例を示します `deploy-vsphere-ovftool.sh`。

|===


=== 導入環境に応じた構成ファイルを定義します

StorageGRIDの仮想グリッドノードを導入するために必要な情報を構成ファイルで指定します。このファイルは、Bashスクリプトで使用され `deploy-vsphere-ovftool.sh`ます。サンプル構成ファイルを変更して、ファイルを最初から作成する必要がないようにすることができます。

.手順
. サンプルコンフィギュレーションファイルのコピーを作成し(`deploy-vsphere-ovftool.sample.ini`ます）。新しいファイルをという名前でと同じディレクトリに `deploy-vsphere-ovftool.sh`保存します `deploy-vsphere-ovftool.ini`。
.  `deploy-vsphere-ovftool.ini`を開きます。
. VMware 仮想グリッドノードを導入するために必要なすべての情報を入力します。
+
詳細は、を参照してください<<configuration-file-settings,構成ファイルの設定>>。

. 必要な情報をすべて入力して確認したら、ファイルを保存して閉じます。




=== 構成ファイルの設定

 `deploy-vsphere-ovftool.ini`構成ファイルには、仮想グリッドノードの導入に必要な設定が含まれています。

構成ファイルでは、最初にグローバルパラメータがリストされ、そのあとにノード名で定義されるセクションにノード固有のパラメータがリストされます。ファイルの使用状況：

* _Global parameters_ は、すべてのグリッドノードに適用されます。
* _Node-specific parameters_override グローバルパラメータ。




==== グローバルパラメータ

グローバルパラメータは、個々のセクションの設定で上書きされないかぎり、すべてのグリッドノードに適用されます。複数のノードに適用するパラメータをグローバルパラメータセクションに配置し、個々のノードのセクションで必要に応じてこれらの設定を上書きします。

* * OVFTOOL_ARGUMENTS * ： OVFTOOL_ARGUMENTS をグローバル設定として指定するか、または特定のノードに個別に引数を適用できます。例：
+
[listing, subs="specialcharacters,quotes"]
----
OVFTOOL_ARGUMENTS = --powerOn --noSSLVerify --diskMode=eagerZeroedThick --datastore='_datastore_name_'
----
+
オプションと `--overwrite`オプションを使用して、既存の仮想マシンをシャットダウンして交換できます `--powerOffTarget`。

+

CAUTION: ノードを別々のデータストアに導入し、 OVFTOOL_ARGUMENTS をグローバルに指定するのではなくノードごとに指定する必要があります。

* * source *：StorageGRID仮想マシンテンプレート(`.vmdk`ファイルと個 々 のグリッドノードのファイル `.ovf`と `.mf`ファイルのパス。デフォルトでは現在のディレクトリに設定されます。
+
[listing, subs="specialcharacters,quotes"]
----
SOURCE = /downloads/StorageGRID-Webscale-_version_/vsphere
----
* * target * ： StorageGRID の導入先となる VMware vSphere 仮想インフラ（ vi ）の URL 。例：
+
[listing]
----
TARGET = vi://vcenter.example.com/vm/sgws
----
* * GRID_NETWORK_CONFIG * ：静的または DHCP のいずれかの IP アドレスの取得に使用される方法。デフォルトはSTATICです。全ノードまたはほとんどのノードが IP アドレスの取得に同じ方法を使用する場合は、ここでその方法を指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
GRID_NETWORK_CONFIG = STATIC
----
* * GRID_NETWORK_TARGET * ：グリッドネットワークに使用される既存の VMware ネットワークの名前。全ノードまたはほとんどのノードが同じネットワーク名を使用する場合は、ここでその名前を指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
GRID_NETWORK_TARGET = SG Admin Network
----
* * GRID_NETWORK_MASK * ：グリッドネットワークのネットワークマスク。全ノードまたはほとんどのノードが同じネットワークマスクを使用する場合は、ここでそのネットワークマスクを指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
GRID_NETWORK_MASK = 255.255.255.0
----
* * GRID_NETWORK_GATEWAY * ：グリッドネットワークのネットワークゲートウェイ。全ノードまたはほとんどのノードが同じネットワークゲートウェイを使用する場合は、ここでそのネットワークゲートウェイを指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
GRID_NETWORK_GATEWAY = 10.1.0.1
----
* * GRID_NETWORK_MTU * ：オプション。グリッドネットワークでの最大伝送ユニット（ MTU ）です。この値を指定する場合、 1280 ～ 9216 の範囲で指定する必要があります。例：
+
[listing]
----
GRID_NETWORK_MTU = 9000
----
+
省略すると、 1400 が使用されます。

+
ジャンボフレームを使用する場合は、 MTU を 9000 などのジャンボフレームに適した値に設定します。それ以外の場合は、デフォルト値のままにします。

+

NOTE: ネットワークのMTU値は、ノードの接続先であるvSphereの仮想スイッチポートに設定されている値と同じである必要があります。そうしないと、ネットワークパフォーマンスの問題やパケット損失が発生する可能性があります。

+

NOTE: ネットワークのパフォーマンスを最大限に高めるには、すべてのノードのグリッドネットワークインターフェイスで MTU 値がほぼ同じになるように設定する必要があります。個々のノードのグリッドネットワークの MTU 設定に大きな違いがある場合は、 * Grid Network MTU mismatch * アラートがトリガーされます。MTU値はすべてのネットワークタイプで同じである必要はありません。

* * ADMIN_NETWORK_CONFIG * ： IP アドレスの取得に使用された方法。無効、静的、または DHCP のいずれかです。デフォルトはdisabledです。全ノードまたはほとんどのノードが IP アドレスの取得に同じ方法を使用する場合は、ここでその方法を指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
ADMIN_NETWORK_CONFIG = STATIC
----
* * ADMIN_NETWORK_TARGET * ：管理ネットワークに使用する既存の VMware ネットワークの名前。この設定は、管理ネットワークが無効になっていない場合に必要となります。全ノードまたはほとんどのノードが同じネットワーク名を使用する場合は、ここでその名前を指定できます。グリッドネットワークとは異なり、すべてのノードを同じ管理ネットワークに接続する必要はありません。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
ADMIN_NETWORK_TARGET = SG Admin Network
----
* * ADMIN_NETWORK_MASK * ：管理ネットワークのネットワークマスク。この設定は、静的 IP アドレスを使用する場合に必要となります。全ノードまたはほとんどのノードが同じネットワークマスクを使用する場合は、ここでそのネットワークマスクを指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
ADMIN_NETWORK_MASK = 255.255.255.0
----
* * ADMIN_NETWORK_GATEWAY * ：管理ネットワークのネットワークゲートウェイ。この設定は、 IP アドレスを静的に指定し、かつ ADMIN_NETWORK_ESL 設定で外部サブネットを指定する場合に必要となります（つまり、ADMIN_NETWORK_ESLが空の場合は必要ありません）。全ノードまたはほとんどのノードが同じネットワークゲートウェイを使用する場合は、ここでそのネットワークゲートウェイを指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
ADMIN_NETWORK_GATEWAY = 10.3.0.1
----
* * ADMIN_NETWORK_ESL * ：管理ネットワークの外部サブネットリスト（ルート）。 CIDR ルートのデスティネーションをカンマで区切ったリストとして指定します。全ノードまたはほとんどのノードが同じ外部サブネットリストを使用する場合は、ここでそのリストを指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
ADMIN_NETWORK_ESL = 172.16.0.0/21,172.17.0.0/21
----
* * ADMIN_NETWORK_MTU * ：オプション。管理ネットワークでの最大伝送ユニット（ MTU ）です。ADMIN_NETWORK_CONFIG = DHCPの場合は指定しないでください。この値を指定する場合、 1280 ～ 9216 の範囲で指定する必要があります。省略すると、 1400 が使用されます。ジャンボフレームを使用する場合は、 MTU を 9000 などのジャンボフレームに適した値に設定します。それ以外の場合は、デフォルト値のままにします。全ノードまたはほとんどのノードが管理ネットワークに同じ MTU を使用する場合は、ここでその MTU を指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
ADMIN_NETWORK_MTU = 8192
----
* * CLIENT_NETWORK_CONFIG * ： IP アドレスの取得に使用する方法。無効、静的、または DHCP のいずれかになります。デフォルトはdisabledです。全ノードまたはほとんどのノードが IP アドレスの取得に同じ方法を使用する場合は、ここでその方法を指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
CLIENT_NETWORK_CONFIG = STATIC
----
* * client_network_target * ：クライアントネットワークに使用する既存の VMware ネットワークの名前。この設定は、クライアントネットワークが無効になっていない場合に必要となります。全ノードまたはほとんどのノードが同じネットワーク名を使用する場合は、ここでその名前を指定できます。グリッドネットワークとは異なり、すべてのノードを同じクライアントネットワークに接続する必要はありません。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
CLIENT_NETWORK_TARGET = SG Client Network
----
* * CLIENT_NETWORK_MASK * ：クライアントネットワークのネットワークマスク。この設定は、静的 IP アドレスを使用する場合に必要となります。全ノードまたはほとんどのノードが同じネットワークマスクを使用する場合は、ここでそのネットワークマスクを指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
CLIENT_NETWORK_MASK = 255.255.255.0
----
* * client_network_gateway * ：クライアントネットワークのネットワークゲートウェイ。この設定は、静的 IP アドレスを使用する場合に必要となります。全ノードまたはほとんどのノードが同じネットワークゲートウェイを使用する場合は、ここでそのネットワークゲートウェイを指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
CLIENT_NETWORK_GATEWAY = 10.4.0.1
----
* * CLIENT_NETWORK_MTU * ：オプション。クライアントネットワークでの最大伝送ユニット（ MTU ）です。CLIENT_NETWORK_CONFIG = DHCPの場合は指定しないでください。この値を指定する場合、 1280 ～ 9216 の範囲で指定する必要があります。省略すると、 1400 が使用されます。ジャンボフレームを使用する場合は、 MTU を 9000 などのジャンボフレームに適した値に設定します。それ以外の場合は、デフォルト値のままにします。全ノードまたはほとんどのノードがクライアントネットワークに同じ MTU を使用する場合は、ここでその MTU を指定できます。その後、個々のノードで別々の設定を指定してグローバル設定を上書きできます。例：
+
[listing]
----
CLIENT_NETWORK_MTU = 8192
----
* * PORT_REMAP * ：ノードが内部でのグリッドノードの通信または外部との通信に使用するポートを再マッピングします。StorageGRID で使用される 1 つ以上のポートがエンタープライズネットワークポリシーによって制限される場合は、ポートの再マッピングが必要です。StorageGRIDで使用されるポートのリストについては、の内部でのグリッドノードの通信と外部との通信を参照してくださいlink:../network/index.html["ネットワークのガイドライン"]。
+

NOTE: ロードバランサエンドポイントの設定に使用する予定のポートは再マッピングしないでください。

+

NOTE: PORT_REMAP のみを設定すると、指定したマッピングがインバウンド通信とアウトバウンド通信の両方に使用されます。PORT_REMAP_INBOUND を併せて指定した場合は、 PORT_REMAP がアウトバウンド通信のみに適用されます。

+
使用される形式は、です `_network type/protocol/default port used by grid node/new port_`。ネットワークタイプはgrid、admin、またはclient、protocolはtcpまたはudpです。

+
例：

+
[listing]
----
PORT_REMAP = client/tcp/18082/443
----
+
この例の設定だけを使用した場合は、グリッドノードのインバウンド通信とアウトバウンド通信の両方が、ポート 18082 からポート 443 へと対称的にマッピングされます。この例の設定を PORT_REMAP_INBOUND とともに使用した場合は、アウトバウンド通信がポート 18082 からポート 443 にマッピングされます。

+
カンマで区切ったリストを使用して複数のポートを再マッピングすることもできます。

+
例：

+
[listing]
----
PORT_REMAP = client/tcp/18082/443, client/tcp/18083/80
----
* * port_remap_inbound * ：指定したポートのインバウンド通信を再マッピングします。PORT_REMAP_INBOUNDを指定し、PORT_REMAPに値を指定しなかった場合、ポートのアウトバウンド通信は変更されません。
+

NOTE: ロードバランサエンドポイントの設定に使用する予定のポートは再マッピングしないでください。

+
使用される形式は、です `_network type_/_protocol/_default port used by grid node_/_new port_`。ネットワークタイプはgrid、admin、またはclient、protocolはtcpまたはudpです。

+
例：

+
[listing]
----
PORT_REMAP_INBOUND = client/tcp/443/18082
----
+
次の例は、ポート 443 に送信されたトラフィックを内部ファイアウォールを通過させ、グリッドノードが S3 要求をリスンしているポート 18082 に転送します。

+
カンマで区切った複数のインバウンドポートを再マッピングすることもできます。

+
例：

+
[listing]
----
PORT_REMAP_INBOUND = grid/tcp/3022/22, admin/tcp/3022/22
----
* * temporary_password_type *：ノードがグリッドに参加する前に、VMコンソールやStorageGRIDインストールAPIにアクセスする場合、またはSSHを使用してアクセスする場合に使用する一時インストールパスワードのタイプ。
+

TIP: すべてのノードまたはほとんどのノードで同じタイプの一時インストールパスワードを使用する場合は、グローバルパラメータセクションでタイプを指定します。その後、必要に応じて個 々 のノードに別の設定を使用します。たとえば、*[カスタムパスワードを使用]*をグローバルに選択した場合は、* custom_temporary_password =<password>*を使用して各ノードのパスワードを設定できます。

+
* temporary_password_type *には、次のいずれかを指定できます。

+
** *ノード名を使用*：ノード名は一時的なインストールパスワードとして使用され、VMコンソール、StorageGRIDインストールAPI、およびSSHへのアクセスを提供します。
** *パスワードを無効にする*:一時的なインストールパスワードは使用されません。インストールの問題をデバッグするためにVMにアクセスする必要がある場合は、を参照してくださいlink:troubleshooting-installation-issues.html["インストールに関する問題のトラブルシューティング"]。
** *カスタムパスワードを使用*：* custom_temporary_password =<password>*で指定した値は、一時的なインストールパスワードとして使用され、VMコンソール、StorageGRIDインストールAPI、およびSSHへのアクセスを提供します。
+

TIP: 必要に応じて、* temporary_password_type *パラメータを省略し、* custom_temporary_password=<password>*のみを指定できます。



* * custom_temporary_password =<password>*オプション。インストール時にVMコンソール、StorageGRIDインストールAPI、およびSSHにアクセスする際に使用する一時パスワード。TEMPORARY_PASSWORD_TYPE *が* Use node name *または* Disable password *に設定されている場合は無視されます。




==== ノード固有のパラメータ

構成ファイルには、各ノード専用のセクションがあります。各ノードには次の設定が必要です。

* セクションヘッドでは、 Grid Manager に表示されるノード名を定義します。この値を無視するには、ノードに対してオプションの node_name パラメータを指定します。
* * NODE_TYPE *：VM_Admin_Node、VM_Storage_Node、またはVM_API_Gateway_Node
* * storage_type *：組み合わせたデータ、またはメタデータ。（オプション）ストレージノードのこのパラメータは、データとメタデータの組み合わせが指定されていない場合はデフォルトで設定されます。詳細については、を参照してください link:../primer/what-storage-node-is.html#types-of-storage-nodes["ストレージノードのタイプ"]。
* * GRID_NETWORK_IP * ：グリッドネットワークでのノードの IP アドレス。
* * ADMIN_NETWORK_IP * ：管理ネットワークでのノードの IP アドレス。ノードが管理ネットワークに接続され、かつ ADMIN_NETWORK_CONFIG が STATIC に設定されている場合にのみ必要です。
* * client_network_ip * ：クライアントネットワーク上のノードの IP アドレス。ノードがクライアントネットワークに接続され、かつノードの CLIENT_NETWORK_CONFIG が STATIC に設定されている場合にのみ必要です。
* * ADMIN_IP * ：グリッドネットワークでのプライマリ管理ノードの IP アドレス。プライマリ管理ノードの GRID_NETWORK_IP で指定した値を使用します。このパラメータを省略すると、ノードは mDNS を使用してプライマリ管理ノードの IP を検出しようとします。詳細については、を参照してください link:how-grid-nodes-discover-primary-admin-node.html["グリッドノードによるプライマリ管理ノードの検出"]。
+

NOTE: プライマリ管理ノードでは ADMIN_IP パラメータが無視されます。

* グローバルに設定されていないすべてのパラメータ。たとえば、ノードが管理ネットワークに接続されていて、 ADMIN_NETWORK_NETWORK パラメータをグローバルに指定していない場合は、ノードに対してそれらのパラメータを指定する必要があります。


.プライマリ管理ノード
プライマリ管理ノードには次の設定を追加する必要があります。

* * node_type * ： VM_Admin_Node
* * Admin_role * ：プライマリ


次のエントリ例は、プライマリ管理ノードが 3 つのネットワークすべてに接続される場合を示しています。

[listing]
----
[DC1-ADM1]
  ADMIN_ROLE = Primary
  NODE_TYPE = VM_Admin_Node
  TEMPORARY_PASSWORD_TYPE = Use custom password
  CUSTOM_TEMPORARY_PASSWORD = Passw0rd

  GRID_NETWORK_IP = 10.1.0.2
  ADMIN_NETWORK_IP = 10.3.0.2
  CLIENT_NETWORK_IP = 10.4.0.2
----
プライマリ管理ノードにオプションで追加できる設定は次のとおりです。

* * DISK * ：デフォルトでは、管理ノードに対して監査用とデータベース用の 2 つの 200GB ハードディスクが追加で割り当てられます。DISK パラメータを使用して、この容量を増やすことができます。例：
+
[listing]
----
DISK = INSTANCES=2, CAPACITY=300
----



NOTE: 管理ノードの場合は、 INSTANCES を必ず 2 にする必要があります。

.ストレージノード
ストレージノードには次の設定を追加する必要があります。

* * node_name * ： VM_Storage_Node
+
次のエントリ例は、ストレージノードがグリッドネットワークと管理ネットワークに接続され、クライアントネットワークに接続されない場合を示しています。このノードでは、 ADMIN_IP 設定を使用してグリッドネットワークでのプライマリ管理ノードの IP アドレスを指定しています。

+
[listing]
----
[DC1-S1]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.0.3
  ADMIN_NETWORK_IP = 10.3.0.3

  ADMIN_IP = 10.1.0.2
----
+
2 番目のエントリ例は、ストレージノードがクライアントネットワークに接続される場合を示しています。ここでは、 S3 クライアントアプリケーションがストレージノードへのアクセスに使用できるポートが、ユーザのエンタープライズネットワークポリシーによって 80 または 443 に制限されています。この例の構成ファイルでは、 PORT_REMAP を使用して、ストレージノードがポート 443 で S3 メッセージを送受信できるようにしています。

+
[listing]
----
[DC2-S1]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.1.3
  CLIENT_NETWORK_IP = 10.4.1.3
  PORT_REMAP = client/tcp/18082/443

  ADMIN_IP = 10.1.0.2
----
+
最後の例では、 ssh トラフィックに対してポート 22 からポート 3022 への対称的な再マッピングが作成されますが、インバウンドとアウトバウンドの両方のトラフィックに明示的に値が設定されます。

+
[listing]
----
[DC1-S3]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.1.3

  PORT_REMAP = grid/tcp/22/3022
  PORT_REMAP_INBOUND = grid/tcp/3022/22

  ADMIN_IP = 10.1.0.2
----


ストレージノードにオプションで追加できる設定は次のとおりです。

* * DISK * ：デフォルトでは、ストレージノードに対して RangeDB 用に 3 つの 4TB ディスクが割り当てられます。DISK パラメータを使用して、この容量を増やすことができます。例：
+
[listing]
----
DISK = INSTANCES=16, CAPACITY=4096
----
* * storage_type *：すべての新しいストレージノードは、オブジェクトデータとメタデータの両方を格納するようにデフォルトで設定されます（_combined_storage Node）。storage_typeパラメータを使用して、データまたはメタデータのみを格納するようにストレージノードのタイプを変更できます。例：
+
[listing]
----
STORAGE_TYPE = data
----


.ゲートウェイノード
ゲートウェイノードには次の設定を追加する必要があります。

* * node_name * ： VM_API_Gateway


次のエントリ例は、ゲートウェイノードが 3 つのネットワークすべてに接続される場合を示しています。この例では、構成ファイルのグローバルセクションでクライアントネットワークのパラメータが指定されていないため、ノードに対してそれらのパラメータを指定する必要があります。

[listing]
----
[DC1-G1]
  NODE_TYPE = VM_API_Gateway

  GRID_NETWORK_IP = 10.1.0.5
  ADMIN_NETWORK_IP = 10.3.0.5

  CLIENT_NETWORK_CONFIG = STATIC
  CLIENT_NETWORK_TARGET = SG Client Network
  CLIENT_NETWORK_MASK = 255.255.255.0
  CLIENT_NETWORK_GATEWAY = 10.4.0.1
  CLIENT_NETWORK_IP = 10.4.0.5

  ADMIN_IP = 10.1.0.2
----
.非プライマリ管理ノード
非プライマリ管理ノードには次の設定を追加する必要があります。

* * node_type * ： VM_Admin_Node
* * Admin_role * ：非プライマリ


次のエントリ例は、非プライマリ管理ノードがクライアントネットワークに接続されない場合を示しています。

[listing]
----
[DC2-ADM1]
  ADMIN_ROLE = Non-Primary
  NODE_TYPE = VM_Admin_Node

  GRID_NETWORK_TARGET = SG Grid Network
  GRID_NETWORK_IP = 10.1.0.6
  ADMIN_NETWORK_IP = 10.3.0.6

  ADMIN_IP = 10.1.0.2
----
非プライマリ管理ノードにオプションで追加できる設定は次のとおりです。

* * DISK * ：デフォルトでは、管理ノードに対して監査用とデータベース用の 2 つの 200GB ハードディスクが追加で割り当てられます。DISK パラメータを使用して、この容量を増やすことができます。例：
+
[listing]
----
DISK = INSTANCES=2, CAPACITY=300
----



NOTE: 管理ノードの場合は、 INSTANCES を必ず 2 にする必要があります。



== Bash スクリプトを実行します

VMware vSphereへのStorageGRIDノードの導入を自動化するために、Bashスクリプトと変更したdeploy-vsphere-ovftool.ini構成ファイルを使用できます `deploy-vsphere-ovftool.sh`。

.開始する前に
環境に対応した deploy-vsphere-ovftool.ini 構成ファイルを作成しておきます。

Bashスクリプトのヘルプを使用するには、helpコマンドを入力し(`-h/--help`ます）。例：

[listing]
----
./deploy-vsphere-ovftool.sh -h
----
または

[listing]
----
./deploy-vsphere-ovftool.sh --help
----
.手順
. Bash スクリプトの実行に使用する Linux マシンにログインします。
. インストールアーカイブを展開したディレクトリに移動します。
+
例：

+
[listing]
----
cd StorageGRID-Webscale-version/vsphere
----
. グリッドノードをすべて導入する場合は、使用する環境に適したオプションを指定して Bash スクリプトを実行します。
+
例：

+
[listing]
----
./deploy-vsphere-ovftool.sh --username=user --password=pwd ./deploy-vsphere-ovftool.ini
----
. エラーのために導入できなかったグリッドノードがある場合は、エラーを解決し、そのノードだけを対象に Bash スクリプトを再実行します。
+
例：

+
[listing]
----
./deploy-vsphere-ovftool.sh --username=user --password=pwd --single-node="DC1-S3" ./deploy-vsphere-ovftool.ini
----


各ノードのステータスが「PASSED」になると、導入は完了です。

[listing]
----
Deployment Summary
+-----------------------------+----------+----------------------+
| node                        | attempts | status               |
+-----------------------------+----------+----------------------+
| DC1-ADM1                    |        1 | Passed               |
| DC1-G1                      |        1 | Passed               |
| DC1-S1                      |        1 | Passed               |
| DC1-S2                      |        1 | Passed               |
| DC1-S3                      |        1 | Passed               |
+-----------------------------+----------+----------------------+
----


== StorageGRID の設定を自動化

グリッドノードを導入したら、 StorageGRID システムの設定を自動化できます。

.開始する前に
* インストールアーカイブにある次のファイルの場所を確認しておきます。
+
[cols="1a,1a"]
|===
| ファイル名 | 製品説明 


| configure-storagegrid.py  a| 
設定を自動化するための Python スクリプト



| storagegrid-sample.json を設定します  a| 
スクリプトで使用する構成ファイルの例



| storagegrid-bank.json を設定する  a| 
スクリプトで使用する空の構成ファイルです

|===
* 構成ファイルを作成しておき `configure-storagegrid.json`ます。このファイルを作成するには(`configure-storagegrid.sample.json`、サンプル構成ファイル）または空の構成ファイル）(`configure-storagegrid.blank.json`を変更します。



CAUTION: 変更した構成ファイルの[Passwords]セクションにある管理パスワードとプロビジョニングパスフレーズを、安全な場所に保存し `configure-storagegrid.json`ます。インストール、拡張、メンテナンスの手順で必要になります。また、変更した構成ファイルをバックアップし、安全な場所に保存する必要があります `configure-storagegrid.json`。

.タスクの内容
Pythonスクリプトと `configure-storagegrid.json`グリッド構成ファイルを使用して、StorageGRIDシステムの設定を自動化できます `configure-storagegrid.py`。

+注：Grid ManagerまたはインストールAPIを使用してシステムを設定することもできます。

.手順
. Python スクリプトを実行するために使用する Linux マシンにログインします。
. インストールアーカイブを展開したディレクトリに移動します。
+
例：

+
[listing]
----
cd StorageGRID-Webscale-version/platform
----
+
 `platform`は、debs、rpm、またはvsphereです。

. Python スクリプトを実行し、作成した構成ファイルを使用します。
+
例：

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.結果
設定プロセス中にリカバリパッケージ `.zip`ファイルが生成され、インストールおよび設定プロセスを実行するディレクトリにダウンロードされます。グリッドノードで障害が発生した場合にStorageGRIDシステムをリカバリできるように、リカバリパッケージファイルをバックアップする必要があります。たとえば、バックアップされたセキュアなネットワーク上の場所や、安全なクラウドストレージ上の場所にコピーします。


CAUTION: リカバリパッケージファイルにはStorageGRID システムからデータを取得するための暗号キーとパスワードが含まれているため、安全に保管する必要があります。

ランダムパスワードを生成するように指定した場合は、ファイルを開き `Passwords.txt`、StorageGRIDシステムへのアクセスに必要なパスワードを探します。

[listing]
----
######################################################################
##### The StorageGRID "Recovery Package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
StorageGRID システムがインストールおよび設定されると、確認メッセージが表示されます。

[listing]
----
StorageGRID has been configured and installed.
----
.関連情報
* link:navigating-to-grid-manager.html["Grid Manager に移動します"]
* link:overview-of-installation-rest-api.html["インストールREST API"]

