---
permalink: vmware/collecting-information-about-your-deployment-environment.html 
sidebar: sidebar 
keywords: how to collect information about your deployment environment 
summary: グリッドノードを導入する前に、ネットワーク設定と VMware 環境に関する情報を収集する必要があります。 
---
= 導入環境に関する情報を収集します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッドノードを導入する前に、ネットワーク設定と VMware 環境に関する情報を収集する必要があります。


NOTE: 一部のノードだけを先にインストールしてから、一部のノードだけをインストールするよりも、すべてのノードを 1 つのインストールする方が効率的です。



== VMware の情報

導入環境にアクセスし、 VMware 環境に関する情報、グリッドネットワーク、管理ネットワーク、クライアントネットワーク用に作成されたネットワークに関する情報、およびストレージノードで使用する予定のストレージボリュームタイプに関する情報を収集する必要があります。

VMware 環境に関する次の情報を収集する必要があります。

* 導入を完了するための適切な権限を持つ VMware vSphere アカウントのユーザ名とパスワード。
* 各StorageGRIDノード仮想マシンのホスト、データストア、およびネットワーク構成の情報。



NOTE: VMware のライブ vMotion を使用すると仮想マシンのクロック時間が急に進むため、この機能はどのタイプのグリッドノードでもサポートされていません。まれにではありますが、クロック時間が不正確だとデータや設定の更新が失われることがあります。



== グリッドネットワークの情報

StorageGRID グリッドネットワーク（必須）用に作成された VMware ネットワークに関する次の情報を収集する必要があります。

* ネットワーク名。
* 静的または DHCP のいずれかの IP アドレスの割り当てに使用する方法。
+
** 静的 IP アドレスを使用する場合は、各グリッドノードのネットワークに関する必須の詳細情報（ IP アドレス、ゲートウェイ、ネットワークマスク）。
** DHCPを使用している場合は、グリッドネットワークでのプライマリ管理ノードのIPアドレス。詳細については、を参照してください link:how-grid-nodes-discover-primary-admin-node.html["グリッドノードによるプライマリ管理ノードの検出"] 。






== 管理ネットワークの情報

ノードがオプションの StorageGRID 管理ネットワークに接続される場合は、このネットワーク用に作成された VMware ネットワークに関する次の情報を収集する必要があります。

* ネットワーク名。
* 静的または DHCP のいずれかの IP アドレスの割り当てに使用する方法。
+
** 静的 IP アドレスを使用する場合は、各グリッドノードのネットワークに関する必須の詳細情報（ IP アドレス、ゲートウェイ、ネットワークマスク）。
** DHCPを使用している場合は、グリッドネットワークでのプライマリ管理ノードのIPアドレス。詳細については、を参照してください link:how-grid-nodes-discover-primary-admin-node.html["グリッドノードによるプライマリ管理ノードの検出"] 。


* 管理ネットワークの外部サブネットリスト（ ESL ）。




== クライアントネットワークの情報

ノードがオプションの StorageGRID クライアントネットワークに接続される場合は、このネットワーク用に作成された VMware ネットワークに関する次の情報を収集する必要があります。

* ネットワーク名。
* 静的または DHCP のいずれかの IP アドレスの割り当てに使用する方法。
* 静的 IP アドレスを使用する場合は、各グリッドノードのネットワークに関する必須の詳細情報（ IP アドレス、ゲートウェイ、ネットワークマスク）。




== 追加のインターフェイスに関する情報

ノードのインストール後に、 vCenter で VM にトランクインターフェイスまたはアクセスインターフェイスを追加することもできます。たとえば、管理ノードまたはゲートウェイノードにトランクインターフェイスを追加して、 VLAN インターフェイスを使用して複数のアプリケーションまたはテナントに属するトラフィックを分離できます。または、ハイアベイラビリティ（ HA ）グループで使用するアクセスインターフェイスを追加することもできます。

追加したインターフェイスは、 VLAN インターフェイスのページおよび Grid Manager の HA グループのページに表示されます。

* トランクインターフェイスを追加する場合は、新しい親インターフェイスごとに 1 つ以上の VLAN インターフェイスを設定します。を参照して link:../admin/configure-vlan-interfaces.html["VLAN インターフェイスを設定します"]
* アクセスインターフェイスを追加した場合は、 HA グループに直接追加する必要があります。を参照して link:../admin/configure-high-availability-group.html["ハイアベイラビリティグループを設定する"]




== 仮想ストレージノードのストレージボリューム

仮想マシンベースのストレージノードに関する次の情報を収集する必要があります。

* 追加するストレージボリューム（ストレージLUN）の数とサイズ。を参照してください。link:storage-and-performance-requirements.html["ストレージとパフォーマンスの要件"]




== グリッドの設定情報

グリッドを設定するための情報を収集する必要があります。

* Grid ライセンス
* Network Time Protocol （ NTP ；ネットワークタイムプロトコル）サーバの IP アドレス
* DNSサーバのIPアドレス

