---
permalink: vmware/deploying-storagegrid-node-as-virtual-machine.html 
sidebar: sidebar 
keywords: how to deploy grid nodes in vsphere or vsphere web client, port, remap, port remap 
summary: VMware vSphere Web Client を使用して、各グリッドノードを仮想マシンとして導入します。導入時に、各グリッドノードが作成されて、 1 つ以上の StorageGRID ネットワークに接続されます。 
---
= StorageGRID ノードを仮想マシンとして導入
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere Web Client を使用して、各グリッドノードを仮想マシンとして導入します。導入時に、各グリッドノードが作成されて、 1 つ以上の StorageGRID ネットワークに接続されます。

StorageGRIDアプライアンスストレージノードを導入する必要がある場合は、を参照してください https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/deploying-appliance-storage-node.html["アプライアンスストレージノードを導入する"^]。

必要に応じて、ノードポートを再マッピングしたり、ノードの CPU やメモリの設定を増やしたりして、電源をオンにすることができます。

.開始する前に
* 方法を確認しlink:index.html["設置を計画して準備"]、ソフトウェア、CPUとRAM、ストレージとパフォーマンスの要件を把握しておく必要があります。
* VMware vSphere ハイパーバイザーについて理解し、この環境で仮想マシンの導入を経験している必要があります。
+

NOTE: この `open-vm-tools`パッケージは、VMware Toolsに似たオープンソースの実装であり、StorageGRID仮想マシンに含まれています。VMware Toolsを手動でインストールする必要はありません。

* VMware 用の正しいバージョンの StorageGRID インストールアーカイブをダウンロードして展開しておきます。
+

CAUTION: 拡張またはリカバリ処理の一環として新しいノードを導入する場合は、グリッドで現在実行されているバージョンの StorageGRID を使用する必要があります。

* StorageGRID仮想マシンディスク(`.vmdk`）ファイルが必要です。


[listing, subs="specialcharacters,quotes"]
----
NetApp-_SG-version_-SHA.vmdk
----
* 導入するグリッドノードのタイプごとにファイルと `.mf`ファイルを用意しておき `.ovf`ます。
+
[cols="1a,1a"]
|===
| ファイル名 | 製品説明 


| vsphere-primary-admin.ovf vsphere-primary-admin.mf  a| 
プライマリ管理ノードのテンプレートファイルとマニフェストファイル。



| vsphere-non-primary-admin.ovf vsphere-non-primary-admin.mf  a| 
非プライマリ管理ノードのテンプレートファイルとマニフェストファイル。



| vsphere-storage.ovf vsphere-storage.mf  a| 
ストレージノードのテンプレートファイルとマニフェストファイル。



| vsphere-gateway.ovf vsphere-gateway.mf  a| 
ゲートウェイノードのテンプレートファイルとマニフェストファイル。

|===
*  `.vdmk`、 `.ovf`、および `.mf`のファイルはすべて同じディレクトリにあります。
* 障害ドメインを最小限に抑えるための計画が必要です。たとえば、すべてのゲートウェイノードを単一のvSphere ESXiホストに導入することは避けてください。
+

CAUTION: 本番環境では、1台の仮想マシンで複数のストレージノードを実行しないでください。許容できない障害ドメインの問題が発生する場合は、同じESXiホストで複数の仮想マシンを実行しないでください。

* 拡張またはリカバリ処理でノードを導入する場合は、またはが必要link:../expand/index.html["StorageGRID システムの拡張手順"]link:../maintain/index.html["リカバリとメンテナンスの手順"]です。
* NetApp ONTAP システムからストレージが割り当てられた仮想マシンとしてStorageGRID ノードを導入する場合は、ボリュームでFabricPool 階層化ポリシーが有効になっていないことを確認しておきます。たとえば、StorageGRIDノードがVMwareホストで仮想マシンとして実行されている場合は、そのノードのデータストアを作成するボリュームでFabricPool階層化ポリシーが有効になっていないことを確認してください。StorageGRIDノードで使用するボリュームでFabricPool階層化を無効にすると、トラブルシューティングとストレージの処理が簡単になります。
+

NOTE: FabricPoolを使用して、StorageGRIDに関連するデータをStorageGRID自体に階層化しないでください。StorageGRIDデータをStorageGRIDに階層化すると、トラブルシューティングや運用が複雑になります。



.タスクの内容
最初に VMware ノードを導入するとき、拡張時に新しい VMware ノードを追加するとき、またはリカバリ処理の一環として VMware ノードを交換するときは、次の手順に従います。手順に記載されている場合を除き、ノードの導入手順は、管理ノード、ストレージノード、ゲートウェイノードを含むすべてのタイプのノードで同じです。

新しい StorageGRID システムを設置する場合は、次の手順を実行します。

* ノードは任意の順序で導入できます。
* 各仮想マシンがグリッドネットワーク経由でプライマリ管理ノードに接続できることを確認する必要があります。
* グリッドを設定する前に、すべてのグリッドノードを導入する必要があります。


拡張またはリカバリ処理を実行する場合は、次の手順を実行します。

* 新しい仮想マシンがグリッドネットワーク経由で他のすべてのノードに接続できることを確認する必要があります。


ノードのポートを再マッピングする必要がある場合は、ポートの再マッピングの設定が完了するまで新しいノードの電源をオンにしないでください。

.手順
. vCenter を使用して OVF テンプレートを導入
+
URL を指定する場合は、次のファイルを含むフォルダを指定します。それ以外の場合は、ローカルディレクトリから各ファイルを選択します。

+
[listing, subs="specialcharacters,quotes"]
----
NetApp-_SG-version_-SHA.vmdk
vsphere-_node_.ovf
vsphere-_node_.mf
----
+
たとえば、導入する最初のノードがこのファイルに含まれている場合は、次のファイルを使用して StorageGRID システムのプライマリ管理ノードを導入します。

+
[listing, subs="specialcharacters,quotes"]
----
NetApp-_SG-version_-SHA.vmdk
vsphere-primary-admin.ovf
vsphere-primary-admin.mf
----
. 仮想マシンの名前を指定します。
+
標準的には、仮想マシンとグリッドノードに同じ名前を使用します。

. 仮想マシンを適切な vApp またはリソースプールに配置します。
. プライマリ管理ノードを導入する場合は、エンドユーザライセンス契約を読んで同意します。
+
vCenter のバージョンによっては、使用する手順の順序は、エンドユーザライセンス契約を承諾し、仮想マシンの名前を指定し、データストアを選択する場合とで異なります。

. 仮想マシンのストレージを選択します。
+
リカバリ処理の一環としてノードを導入する場合は、の手順に従って、<<step_recovery_storage,ストレージリカバリ手順>>新しい仮想ディスクの追加、障害が発生したグリッドノードからの仮想ハードディスクの再接続、またはその両方を行います。

+
ストレージノードを導入する際は、ストレージボリュームを 3 個以上使用し、各ストレージボリュームのサイズを 4TB 以上にします。ボリューム 0 に少なくとも 4TB 割り当てる必要があります。

+

NOTE: ストレージノードの .ovf ファイルは、ストレージ用の複数の VMDK を定義します。これらの VMDK がストレージ要件を満たしていない場合は、ノードの電源を入れる前に、それらの VMDK を削除し、ストレージに適切な VMDK または RDM を割り当てる必要があります。VMware 環境で一般に使用され、管理も容易であるのは VMDK ですが、大きなオブジェクトサイズ（たとえば 100MB 超）を使用するワークロードのパフォーマンスは RDM の方が高くなります。

+

NOTE: 一部の StorageGRID 環境では、一般的な仮想ワークロードよりも大容量のアクティブなストレージボリュームを使用する場合があります。パフォーマンスを最適化するために、などの一部のハイパーバイザーパラメータの調整が必要になる場合があります `MaxAddressableSpaceTB`。パフォーマンスが低下する場合は、仮想化のサポートリソースに問い合わせて、ワークロード固有の構成調整によって環境がメリットを受けるかどうかを確認してください。

. ネットワークを選択します。
+
各ソースネットワークのデスティネーションネットワークを選択して、ノードで使用する StorageGRID ネットワークを決定します。

+
** グリッドネットワークは必須です。vSphere 環境でデスティネーションネットワークを選択する必要があります。+グリッドネットワークは、すべての内部StorageGRIDトラフィックに使用されます。グリッド内のすべてのノードが、すべてのサイトとサブネットにわたって接続されます。グリッドネットワーク上のすべてのノードが他のすべてのノードと通信できる必要があります。
** 管理ネットワークを使用する場合は、 vSphere 環境で別のデスティネーションネットワークを選択します。管理ネットワークを使用しない場合は、グリッドネットワークに対して選択したデスティネーションと同じデスティネーションを選択します。
** クライアントネットワークを使用する場合は、 vSphere 環境で別のデスティネーションネットワークを選択します。クライアントネットワークを使用しない場合は、グリッドネットワークに対して選択したデスティネーションと同じデスティネーションを選択します。
** 管理ネットワークまたはクライアントネットワークを使用する場合は、ノードが同じ管理ネットワークまたはクライアントネットワーク上にある必要はありません。


. [テンプレートのカスタマイズ]*で、必要なStorageGRIDノードプロパティを構成します。
+
.. ノード名 * を入力します。
+

NOTE: グリッドノードをリカバリする場合は、リカバリするノードの名前を入力する必要があります。

.. 新しいノードがグリッドに追加される前にVMコンソールまたはStorageGRIDインストールAPIにアクセスしたり、SSHを使用したりできるように、*[Temporary installation password]*ドロップダウンを使用して一時的なインストールパスワードを指定します。
+

NOTE: 一時インストールパスワードは、ノードのインストール時にのみ使用されます。グリッドに追加されたノードにlink:../admin/change-node-console-password.html["ノードのコンソールパスワード"]は、リカバリパッケージのファイルに含まれているを使用してアクセスできます。 `Passwords.txt`

+
*** *ノード名を使用*：*ノード名*フィールドに入力した値は、一時的なインストールパスワードとして使用されます。
*** *カスタムパスワードを使用*：カスタムパスワードを一時的なインストールパスワードとして使用します。
*** *パスワードを無効にする*:一時的なインストールパスワードは使用されません。インストールの問題をデバッグするためにVMにアクセスする必要がある場合は、を参照してくださいlink:troubleshooting-installation-issues.html["インストールに関する問題のトラブルシューティング"]。


.. *カスタムパスワードを使用*を選択した場合は、*カスタムパスワード*フィールドで使用する一時インストールパスワードを指定します。
.. * グリッドネットワーク（ eth0 ） * セクションで、 * グリッドネットワーク IP 設定 * に静的または DHCP を選択します。
+
*** 静的を選択した場合は、 * グリッドネットワーク IP * 、 * グリッドネットワークマスク * 、 * グリッドネットワークゲートウェイ * 、 * グリッドネットワーク MTU * を入力します。
*** DHCP を選択した場合は、 * グリッドネットワーク IP * 、 * グリッドネットワークマスク * 、 * グリッドネットワークゲートウェイ * が自動的に割り当てられます。


.. 「 * Primary Admin IP * 」フィールドに、グリッドネットワークのプライマリ管理ノードの IP アドレスを入力します。
+

NOTE: この手順は、導入するノードがプライマリ管理ノードの場合は必要ありません。

+
プライマリ管理ノードの IP アドレスを省略すると、プライマリ管理ノードまたは ADMIN_IP が設定された少なくとも 1 つのグリッドノードが同じサブネットにある場合は、 IP アドレスが自動的に検出されます。ただし、ここでプライマリ管理ノードの IP アドレスを設定することを推奨します。

.. 「 * Admin Network （ eth1 ） * 」セクションで、「 * Admin network IP configuration * 」に対して「 static 」、「 dhcp 」、または「 disabled 」を選択します。
+
*** 管理ネットワークを使用しない場合は、[DISABLED]を選択し、[Admin Network IP]に「* 0.0.0.0 *」と入力します。他のフィールドは空白のままにすることができます。
*** 静的を選択した場合は、 * 管理ネットワーク IP * 、 * 管理ネットワークマスク * 、 * 管理ネットワークゲートウェイ * 、 * 管理ネットワーク MTU * を入力します。
*** 静的を選択した場合は、 * 管理ネットワークの外部サブネットリスト * を入力します。ゲートウェイも設定する必要があります。
*** DHCP を選択した場合は、 * 管理ネットワーク IP * 、 * 管理ネットワークマスク * 、および * 管理ネットワークゲートウェイ * が自動的に割り当てられます。


.. クライアントネットワーク（ eth2 ） * セクションで、 * クライアントネットワーク IP 構成 * の静的、 DHCP 、または無効を選択します。
+
*** クライアントネットワークを使用しない場合は、[DISABLED]を選択し、[Client Network IP]に「* 0.0.0.0 *」と入力します。他のフィールドは空白のままにすることができます。
*** 静的を選択した場合は、 * クライアントネットワーク IP * 、 * クライアントネットワークマスク * 、 * クライアントネットワークゲートウェイ * 、および * クライアントネットワーク MTU * を入力します。
*** DHCP を選択した場合は、 * クライアントネットワーク IP * 、 * クライアントネットワークマスク * 、および * クライアントネットワークゲートウェイ * が自動的に割り当てられます。




. 仮想マシンの設定を確認し、必要な変更を行います。
. 完了する準備ができたら、 [ 完了 ] を選択して仮想マシンのアップロードを開始します。
. [[step_recovery_storage] - リカバリ処理の一環としてこのノードを導入し、フルノードリカバリではない場合は、導入の完了後に次の手順を実行します。
+
.. 仮想マシンを右クリックし、 * 設定の編集 * を選択します。
.. ストレージに指定されている各デフォルト仮想ハードディスクを選択し、 * 削除 * を選択します。
.. データリカバリの状況に応じて、ストレージ要件に従って新しい仮想ディスクを追加し、以前に削除した障害グリッドノードから保存した仮想ハードディスクを再接続するか、またはその両方を実行します。
+
次の重要なガイドラインに注意してください。

+
*** 新しいディスクを追加する場合は、ノードのリカバリ前に使用していたものと同じタイプのストレージデバイスを使用する必要があります。
*** ストレージノードの .ovf ファイルは、ストレージ用の複数の VMDK を定義します。これらの VMDK がストレージ要件を満たしていない場合は、ノードの電源を入れる前に、それらの VMDK を削除し、ストレージに適切な VMDK または RDM を割り当てる必要があります。VMware 環境で一般に使用され、管理も容易であるのは VMDK ですが、大きなオブジェクトサイズ（たとえば 100MB 超）を使用するワークロードのパフォーマンスは RDM の方が高くなります。




. [[vmware-remap-ports]]このノードで使用するポートを再マッピングする必要がある場合は、次の手順を実行します。
+
ポートの再マッピングが必要となるのは、 StorageGRID で使用される 1 つ以上のポートへのアクセスがエンタープライズネットワークポリシーによって制限される場合です。StorageGRIDで使用されるポートについては、を参照してくださいlink:../network/index.html["ネットワークのガイドライン"]。

+

NOTE: ロードバランサエンドポイントで使用されるポートは再マッピングしないでください。

+
.. 新しい VM を選択します。
.. [ 構成 ] タブで、 [ * 設定 * > * vApp オプション * ] を選択します。vapp Options * の場所は、 vCenter のバージョンによって異なります。
.. プロパティ * テーブルで、 PORT_REMAP_INBOUND および PORT_REMAP を確認します。
.. ポートのインバウンド通信とアウトバウンド通信の両方を対称的にマッピングするには、 * PORT_REMAP * を選択します。
+

NOTE: PORT_REMAP のみを設定すると、インバウンド通信とアウトバウンド通信の両方で環境 を指定したマッピングが適用されます。PORT_REMAP_INBOUND を併せて指定した場合は、 PORT_REMAP がアウトバウンド通信のみに適用されます。

+
... 「 * 値の設定 * 」を選択します。
... ポートマッピングを入力します。
+
`<network type>/<protocol>/<default port used by grid node>/<new port>`

+
`<network type>`はgrid、admin、またはclientで、 `<protocol>`はtcpまたはudpです。

+
たとえば、 ssh トラフィックをポート 22 からポート 3022 に再マッピングするには、次のように入力します。

+
`client/tcp/22/3022`

+
カンマで区切ったリストを使用して複数のポートを再マッピングできます。

+
例：

+
`client/tcp/18082/443, client/tcp/18083/80`

... 「* OK *」を選択します。


.. ノードへのインバウンド通信に使用するポートを指定するには、 * port_remap_inbound * を選択します。
+

NOTE: PORT_REMAP_INBOUNDを指定し、PORT_REMAPに値を指定しなかった場合、ポートのアウトバウンド通信は変更されません。

+
... 「 * 値の設定 * 」を選択します。
... ポートマッピングを入力します。
+
`<network type>/<protocol>/<remapped inbound port>/<default inbound port used by grid node>`

+
`<network type>`はgrid、admin、またはclientで、 `<protocol>`はtcpまたはudpです。

+
たとえば、ポート 3022 に送信されるインバウンドの SSH トラフィックを再マッピングしてグリッドノードがポート 22 で受信するようにするには、次のように入力します。

+
`client/tcp/3022/22`

+
カンマで区切った複数のインバウンドポートを再マッピングできます。

+
例：

+
`grid/tcp/3022/22, admin/tcp/3022/22`

... 「 * OK 」を選択します




. ノードの CPU またはメモリをデフォルトの設定から増やす場合は、次の手順を実行します。
+
.. 仮想マシンを右クリックし、 * 設定の編集 * を選択します。
.. CPU の数またはメモリの容量を必要に応じて変更します。
+
[ メモリ予約 * ] を、仮想マシンに割り当てられた * メモリ * と同じサイズに設定します。

.. 「* OK *」を選択します。


. 仮想マシンの電源をオンにします。


.終了後
このノードを拡張またはリカバリ用手順 の一部として導入した場合は、その手順に戻って手順 を完了します。
