---
permalink: vmware/overview-of-installation-rest-api.html 
sidebar: sidebar 
keywords: installation REST API 
summary: StorageGRID には、インストールタスクを実行するための StorageGRID インストール API が用意されています。 
---
= インストールREST API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID には、インストールタスクを実行するための StorageGRID インストール API が用意されています。

API のドキュメントは、 Swagger オープンソース API プラットフォームで提供されています。Swagger では、ユーザインターフェイスを使用してパラメータやオプションを変更した場合の API の動作を確認しながら、 API の開発を進めることができます。このドキュメントは、標準的なWebテクノロジとJSONデータ形式に精通していることを前提としています。


CAUTION: APIドキュメントWebページで実行するAPI処理はすべてライブ処理です。設定データやその他のデータを誤って作成、更新、または削除しないように注意してください。

各 REST API コマンドは、 API の URL 、 HTTP アクション、必須またはオプションの URL パラメータ、および想定される API 応答で構成されます。



== StorageGRID インストール API

StorageGRID インストールAPIは、StorageGRID システムを最初に設定するとき、およびプライマリ管理ノードのリカバリを実行する必要がある場合にのみ使用できます。インストール API には、 Grid Manager から HTTPS 経由でアクセスできます。

APIドキュメントにアクセスするには、プライマリ管理ノードでインストールWebページに移動し、メニューバーから*[ヘルプ]*>*[APIドキュメント]*を選択します。

StorageGRID インストール API には次のセクションがあります。

* *config *-- API の製品リリースとバージョンに関連する操作。製品リリースバージョンおよびそのリリースでサポートされる API のメジャーバージョンを一覧表示できます。
* * grid * -- グリッドレベルの設定操作。グリッドの詳細、グリッドネットワークのサブネット、グリッドパスワード、 NTP および DNS サーバの IP アドレスなど、グリッド設定を取得および更新できます。
* *nodes * -- ノードレベルの設定操作。グリッドノードのリストを取得できるほか、グリッドノードの削除、設定、表示、およびグリッドノードの設定のリセットを行うことができます。
* *provision * -- プロビジョニング操作。プロビジョニング処理を開始し、プロビジョニング処理のステータスを表示できます。
* * recovery * - プライマリ管理ノードのリカバリ処理。情報のリセット、リカバリパッケージのアップロード、リカバリの開始、およびリカバリ処理のステータスの表示を行うことができます。
* * recovery-package *--リカバリパッケージをダウンロードする処理。
* *sites * -- サイトレベルの設定操作。サイトを作成、表示、削除、および変更できます。
* * temporary-password *--インストール中にmgmt-apiを保護するための一時パスワードに対する操作。

