---
permalink: vmware/troubleshooting-installation-issues.html 
sidebar: sidebar 
keywords: how to troubleshoot installation issues 
summary: StorageGRID システムのインストール中に問題が発生した場合は、インストールログファイルにアクセスできます。 
---
= インストールに関する問題のトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システムのインストール中に問題が発生した場合は、インストールログファイルにアクセスできます。

次のファイルは、テクニカルサポートが問題の解決に必要とする場合があるメインのインストールログファイルです。

* `/var/local/log/install.log`（すべてのグリッドノードに存在）
* `/var/local/log/gdu-server.log`（プライマリ管理ノードにあります）


.関連情報
ログファイルへのアクセス方法については、を参照してくださいlink:../monitor/logs-files-reference.html["ログファイル参照"]。

サポートが必要な場合は、にお問い合わせください https://mysupport.netapp.com/site/global/dashboard["NetAppサポート"^]。



== 仮想マシンのリソースリザベーションの調整が必要です

OVF ファイルでは、各グリッドノードが十分な RAM と CPU を確保して効率よく動作できるようにするためのリソースリザベーションが設定されています。これらのOVFファイルをVMwareに導入して仮想マシンを作成し、事前定義された数のリソースを使用できない場合、仮想マシンは起動しません。

.タスクの内容
VM ホストに各グリッドノード用の十分なリソースがあることがわかっている場合は、各仮想マシンに割り当てられているリソースを手動で調整し、仮想マシンの起動を試みます。

.手順
. VMware vSphere ハイパーバイザーのクライアントツリーで、起動されていない仮想マシンを選択します。
. 仮想マシンを右クリックし、 * 設定の編集 * を選択します。
. [ 仮想マシンのプロパティ ] ウィンドウで、 [ * リソース * ] タブを選択します。
. 仮想マシンに割り当てられているリソースを調整します。
+
.. [*CPU*] を選択し、 [ 予約 ] スライダを使用して、この仮想マシン用に予約されている MHz を調整します。
.. [* Memory] を選択し、 [Reservation （予約） ] スライダを使用してこの仮想マシン用に予約されている MB を調整します。


. [OK]*をクリックします。
. 必要に応じて、同じ VM ホストでホストされている他の仮想マシンに対して同じ手順を繰り返します。




== 一時インストールパスワードが無効になりました

VMwareノードを導入するときに、必要に応じて一時的なインストールパスワードを指定できます。新しいノードがグリッドに追加される前にVMコンソールにアクセスするかSSHを使用するには、このパスワードが必要です。

一時インストールパスワードを無効にした場合は、インストールの問題をデバッグするために追加の手順を実行する必要があります。

次のいずれかを実行できます。

* コンソールにアクセスしたり、SSHを使用してインストールの問題をデバッグできるように、VMを再導入します。ただし、一時的なインストールパスワードを指定してください。
* vCenterを使用してパスワードを設定します。
+
.. VMの電源をオフにします。
.. [VM]*に移動し、*[設定]*タブを選択して*[vApp Options]*を選択します。
.. 設定する一時インストールパスワードのタイプを指定します。
+
*** カスタム一時パスワードを設定するには、* custom_temporary_password *を選択します。
*** ノード名を一時パスワードとして使用する場合は、* temporary_password_type *を選択します。


.. 「 * 値の設定 * 」を選択します。
.. 一時パスワードを設定します。
+
*** custom_temporary_password *をカスタムのパスワード値に変更します。
*** temporary_password_type *を* use node name *の値で更新します。


.. VMを再起動して新しいパスワードを適用します。



