---
permalink: rhel/automating-installation.html 
sidebar: sidebar 
keywords: how to automate red hat linux installation 
summary: StorageGRID ホストサービスのインストールおよびグリッドノードの設定を自動化することができます。 
---
= Red Hat Enterprise LinuxへのStorageGRIDインストールの自動化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID ホストサービスのインストールおよびグリッドノードの設定を自動化することができます。

導入を自動化すると、次のいずれかの場合に役立ちます。

* 物理ホストや仮想ホストの導入と設定に Ansible 、 Puppet 、 Chef などの標準のオーケストレーションフレームワークをすでに使用している場合。
* 複数の StorageGRID インスタンスを導入する場合。
* 大規模で複雑な StorageGRID インスタンスを導入する場合。


StorageGRID ホストサービスはパッケージによってインストールされ、構成ファイルによって制御されます。次のいずれかの方法で構成ファイルを作成できます。

* link:creating-node-configuration-files.html["構成ファイルを作成します"]手動インストール中に対話的に実行します。
* 構成ファイルを事前に準備し（またはプログラム化して）、この資料で説明するように、標準のオーケストレーションフレームワークを使用した自動インストールを可能にします。
+
StorageGRIDには、StorageGRIDアプライアンスとStorageGRIDシステム全体（「グリッド」）の設定を自動化するためのPythonスクリプトがオプションで用意されています。これらのスクリプトを直接使用することも、スクリプトを調べて、独自に開発したグリッド内導入ツールや設定ツールの使用方法を学ぶこともできlink:overview-of-installation-rest-api.html["StorageGRID インストール REST API"]ます。





== StorageGRID ホストサービスのインストールと設定を自動化する

StorageGRID ホストサービスのインストールは、 Ansible 、 Puppet 、 Chef 、 Fabric 、 SaltStack などの標準のオーケストレーションフレームワークを使用して自動化できます。

StorageGRID ホストサービスは RPM 形式でパッケージ化されており、あらかじめ構成ファイルを用意して（またはプログラム化して）おくことで自動インストールが可能です。すでにRHELのインストールと設定に標準的なオーケストレーションフレームワークを使用している場合は、プレイブックやレシピにStorageGRIDを追加する方が簡単です。

インストールアーカイブに付属のフォルダにあるサンプルのAnsibleのロールとプレイブックを参照してください `/extras`。Ansibleプレイブックは、ロールでホストを準備してStorageGRIDをターゲットサーバにインストールする方法を示しています `storagegrid`。必要に応じて、ロールまたはプレイブックをカスタマイズできます。


NOTE: サンプルのプレイブックには、 StorageGRID ホストサービスを開始する前にネットワークデバイスを作成するために必要な手順は含まれていません。これらの手順は、最終的な確認と使用の前に追加してください。

ホストの準備と仮想グリッドノードの導入の手順をすべて自動化することができます。



=== サンプルの Ansible のロールとプレイブック

サンプルのAnsibleのロールとプレイブックは、インストールアーカイブのフォルダにあります `/extras`。Ansibleプレイブックは、ロールでホストを準備してStorageGRIDをターゲットサーバにインストールする方法を示しています `storagegrid`。必要に応じて、ロールまたはプレイブックをカスタマイズできます。

指定されたロール例のインストールタスクで `storagegrid`は、モジュールを使用して `ansible.builtin.dnf`、ローカルRPMファイルまたはリモートYumリポジトリからインストールを実行します。モジュールが使用できない場合やサポートされていない場合は、または `ansible.builtin.yum`モジュールを使用するために、次のファイルで適切なAnsibleタスクを編集する必要が `yum`あります。

* `roles/storagegrid/tasks/rhel_install_from_repo.yml`
* `roles/storagegrid/tasks/rhel_install_from_local.yml`




== StorageGRID の設定を自動化

グリッドノードを導入したら、 StorageGRID システムの設定を自動化できます。

.開始する前に
* インストールアーカイブにある次のファイルの場所を確認しておきます。
+
[cols="1a,1a"]
|===
| ファイル名 | 製品説明 


| configure-storagegrid.py  a| 
設定を自動化するための Python スクリプト



| storagegrid-sample.json を設定します  a| 
スクリプトで使用する構成ファイルの例



| storagegrid-bank.json を設定する  a| 
スクリプトで使用する空の構成ファイルです

|===
* 構成ファイルを作成しておき `configure-storagegrid.json`ます。このファイルを作成するには(`configure-storagegrid.sample.json`、サンプル構成ファイル）または空の構成ファイル）(`configure-storagegrid.blank.json`を変更します。


.タスクの内容
Pythonスクリプトと `configure-storagegrid.json`構成ファイルを使用して、StorageGRIDシステムの設定を自動化できます `configure-storagegrid.py`。


NOTE: また、 Grid Manager またはインストール API を使用してシステムを設定することもできます。

.手順
. Python スクリプトを実行するために使用する Linux マシンにログインします。
. インストールアーカイブを展開したディレクトリに移動します。
+
例：

+
[listing]
----
cd StorageGRID-Webscale-version/platform
----
+
 `platform`は `rpms`、または `vsphere`です `debs`。

. Python スクリプトを実行し、作成した構成ファイルを使用します。
+
例：

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.結果
設定プロセス中にリカバリパッケージ `.zip`ファイルが生成され、インストールおよび設定プロセスを実行するディレクトリにダウンロードされます。グリッドノードで障害が発生した場合に StorageGRID システムをリカバリできるようにするために、リカバリパッケージファイルをバックアップする必要があります。たとえば、バックアップされたセキュアなネットワーク上の場所や、安全なクラウドストレージ上の場所にコピーします。


CAUTION: リカバリパッケージファイルには StorageGRID システムからデータを取得するための暗号キーとパスワードが含まれているため、安全に保管する必要があります。

ランダムパスワードを生成するように指定した場合は、ファイルを開き `Passwords.txt`、StorageGRIDシステムへのアクセスに必要なパスワードを探します。

[listing]
----
######################################################################
##### The StorageGRID "Recovery Package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
StorageGRID システムがインストールおよび設定されると、確認メッセージが表示されます。

[listing]
----
StorageGRID has been configured and installed.
----
.関連情報
link:overview-of-installation-rest-api.html["インストールREST API"]
