---
permalink: rhel/configuring-docker-storage-volume.html 
sidebar: sidebar 
keywords: how to configure container engine storage volume, Docker, Podman 
summary: コンテナエンジン（ Docker または Podman ）をインストールする前に、ストレージボリュームをフォーマットしてマウントする必要があります。 
---
= コンテナエンジンのストレージボリュームを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コンテナエンジン（ Docker または Podman ）をインストールする前に、ストレージボリュームをフォーマットしてマウントする必要があります。


NOTE: ソフトウェアのみの環境のコンテナエンジンとしてのDockerのサポートは廃止されました。Dockerは、今後のリリースで別のコンテナエンジンに置き換えられる予定です。

.タスクの内容
DockerまたはPodmanのストレージボリュームにローカルストレージを使用する予定で、Dockerおよび `/var/lib/containers`Podmanを含むホストパーティションに十分なスペースがある場合は、これらの手順を省略できます `/var/lib/docker`。


NOTE: Podman は、 Red Hat Enterprise Linux （ RHEL ）でのみサポートされます。

.手順
. コンテナエンジンのストレージボリュームにファイルシステムを作成します。
+
[listing]
----
sudo mkfs.ext4 container-engine-storage-volume-device
----
. コンテナエンジンのストレージボリュームをマウントします。
+
** Docker の場合：
+
[listing]
----
sudo mkdir -p /var/lib/docker
sudo mount container-storage-volume-device /var/lib/docker
----
** Podman の場合：
+
[listing]
----
sudo mkdir -p /var/lib/containers
sudo mount container-storage-volume-device /var/lib/containers
----


. container-storage-volume-device のエントリを /etc/fstab に追加します。
+
これにより、ホストのリブート後にストレージボリュームが自動的に再マウントされます。





== Docker をインストールする

StorageGRID システムは、コンテナの集合として Red Hat Enterprise Linux 上で実行されます。Docker コンテナエンジンを使用することを選択した場合は、次の手順に従って Docker をインストールします。それ以外の場合は、<<Podman をインストールします,Podman をインストールします>>

.手順
. 使用している Linux ディストリビューションの手順に従って Docker をインストールします。
+

NOTE: Docker が Linux ディストリビューションに含まれていない場合は、 Docker の Web サイトからダウンロードできます。

. 次の 2 つのコマンドを実行して、 Docker が有効化され、起動されたことを確認します。
+
[listing]
----
sudo systemctl enable docker
----
+
[listing]
----
sudo systemctl start docker
----
. 次のコマンドを入力して、必要なバージョンの Docker がインストールされたことを確認します。
+
[listing]
----
sudo docker version
----
+
クライアントとサーバのバージョンは1.11.0以降である必要があります。





== Podman をインストールします

StorageGRID システムは、コンテナの集合として Red Hat Enterprise Linux 上で実行されます。Podman コンテナエンジンの使用を選択した場合は、次の手順に従って Podman をインストールします。それ以外の場合は、<<Docker をインストールする,Docker をインストールする>>


NOTE: Podman は、 Red Hat Enterprise Linux （ RHEL ）でのみサポートされます。

.手順
. 使用している Linux ディストリビューションの手順に従って、 Podman および Podman-Docker をインストールします。
+

NOTE: また、 Podman をインストールする際には、 Podman-Docker パッケージもインストールする必要があります。

. 次のように入力して、必要なバージョンの Podman および Podman-Docker がインストールされていることを確認します。
+
[listing]
----
sudo docker version
----
+

NOTE: Podman-Docker パッケージでは、 Docker コマンドを使用できます。

+
クライアントとサーバのバージョンは3.2.3以降である必要があります。

+
[listing]
----
Version: 3.2.3
API Version: 3.2.3
Go Version: go1.15.7
Built: Tue Jul 27 03:29:39 2021
OS/Arch: linux/amd64
----

