---
permalink: rhel/installing-linux.html 
sidebar: sidebar 
keywords: how to install on red hat linux 
summary: StorageGRIDは、すべてのRed Hat Enterprise Linuxグリッドホストにインストールする必要があります。サポートされているバージョンの一覧については、NetApp Interoperability Matrix Toolを参照してください。 
---
= Linux をインストールします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRIDは、すべてのRed Hat Enterprise Linuxグリッドホストにインストールする必要があります。サポートされているバージョンの一覧については、NetApp Interoperability Matrix Toolを参照してください。

.開始する前に
お使いのオペレーティングシステムが、以下に示すStorageGRIDのカーネルバージョンの最小要件を満たしていることを確認してください。コマンドを使用し `uname -r`てオペレーティングシステムのカーネルバージョンを確認するか、OSベンダーに問い合わせてください。

[cols="1a,2a,2a"]
|===
| Red Hat Enterprise Linuxのバージョン | 最小カーネルバージョン | カーネルパッケージ名 


 a| 
8.8（廃止）
 a| 
4.18.0～477.10.1.el8_8.x86_64
 a| 
kernel-4.18.0-477.10.1.el8_8.x86_64



 a| 
8.10
 a| 
4.18.0-553.el8_10.x86_64
 a| 
kernel-4.18.0-553.el8_10.x86_64



 a| 
9.0（廃止）
 a| 
5.14.0～70.22.1.el9_0.x86_64
 a| 
kernel-5.14.0-70.22.1.el9_0.x86_64



 a| 
9.2（廃止）
 a| 
5.14.0～284.11.1.el9_2.x86_64
 a| 
カーネル-5.14.0-284.11.1.el9_2.x86_64



 a| 
9.4
 a| 
5.14.0～427.18.1.el9_4.x86_64
 a| 
カーネル-5.14.0-427.18.1.el9_4.x86_64

|===
.手順
. ディストリビュータの指示または標準の手順 に従って、すべての物理グリッドホストまたは仮想グリッドホストに Linux をインストールします。
+

NOTE: 標準のLinuxインストーラを使用する場合は、「コンピューティングノード」のソフトウェア設定（可能な場合）または「最小限のインストール」ベース環境を選択します。グラフィカルデスクトップ環境はインストールしないでください。

. Extras チャネルを含むすべてのホストがパッケージリポジトリにアクセスできることを確認します。
+
これらの追加パッケージは、このインストール手順 の後半で必要になる場合があります。

. スワップが有効になっている場合：
+
.. 次のコマンドを実行します。 `$ sudo swapoff --all`
.. からすべてのスワップエントリを削除し `/etc/fstab`て、設定を維持します。


+

NOTE: スワップを完全に無効にできないと、パフォーマンスが大幅に低下する可能性があります


