---
permalink: admin/admin-group-permissions.html 
sidebar: sidebar 
keywords: admin group permissions 
summary: 管理者ユーザグループを作成する場合は、 Grid Manager の特定の機能へのアクセスを制御する権限を 1 つ以上選択します。その後、作成した 1 つ以上の管理者グループに各ユーザを割り当てて、ユーザが実行できるタスクを決定できます。 
---
= 管理者グループの権限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理者ユーザグループを作成する場合は、 Grid Manager の特定の機能へのアクセスを制御する権限を 1 つ以上選択します。その後、作成した 1 つ以上の管理者グループに各ユーザを割り当てて、ユーザが実行できるタスクを決定できます。

各グループに 1 つ以上の権限を割り当てる必要があります。そうしないと、そのグループに属するユーザは Grid Manager またはグリッド管理 API にサインインできません。

デフォルトでは、少なくとも 1 つの権限が割り当てられたグループに属するユーザは次のタスクを実行できます。

* Grid Manager にサインインします
* ダッシュボードを表示します
* ノードページを表示します
* 現在のアラートと解決済みのアラートを表示します
* 自分のパスワードを変更する（ローカルユーザのみ）
* [Configuration]ページと[Maintenance]ページに表示される特定の情報を確認します




== 権限とアクセスモードの相互作用

すべての権限について、グループの * アクセスモード * 設定は、ユーザーが設定を変更して操作を実行できるかどうか、または関連する設定と機能のみを表示できるかどうかを決定します。ユーザーが複数のグループに属していて、いずれかのグループが * 読み取り専用 * に設定されている場合、ユーザーは選択したすべての設定と機能に読み取り専用でアクセスできます。

以降のセクションでは、管理者グループの作成時または編集時に割り当てることができる権限について説明します。明示的に言及されていない機能には、 * Root Access * 権限が必要です。



== ルートアクセス

この権限は、すべてのグリッド管理機能へのアクセスを許可します。



== テナントの root パスワードを変更する

この権限は、テナントページの * root パスワードの変更 * オプションへのアクセスを許可し、テナントのローカル root ユーザのパスワードを変更できるユーザを制御することを可能にします。この権限は、 S3 キーのインポート機能が有効になっている場合に S3 キーの移行にも使用されます。この権限がないユーザには、* rootパスワードの変更*オプションが表示されません。


NOTE: Change root password * オプションが含まれている tenants ページへのアクセスを許可するには、 * Tenant accounts * 権限を割り当てます。



== Grid トポロジページの設定

この権限では、サポート * > * ツール * > * グリッドトポロジ * ページの構成タブにアクセスできます。


NOTE: Gridトポロジページは廃止され、今後のリリースで削除される予定です。



== ILM

この権限は、次の * ILM * メニュー・オプションへのアクセスを提供します。

* ルール
* ポリシー
* ポリシータグ
* ストレージプール
* ストレージグレード
* 地域
* オブジェクトメタデータの検索



NOTE: ストレージグレードを管理するには、ユーザに * Other Grid Configuration * 権限と * Grid Topology Page Configuration * 権限が必要です。



== メンテナンス

これらのオプションを使用するには、 Maintenance 権限が必要です。

* * 設定 * > * アクセス制御 * ：
+
** Grid のパスワード


* * 設定 * > * ネットワーク * ：
+
** S3エンドポイントのドメイン名


* * メンテナンス * > * タスク * ：
+
** 運用停止
** 拡張
** オブジェクトの存在チェック
** リカバリ


* * メンテナンス * > * システム * ：
+
** リカバリパッケージ
** ソフトウェアの更新


* * サポート * > * ツール * ：
+
** ログ




Maintenance権限がないユーザは、次のページを表示できますが、編集はできません。

* * メンテナンス * > * ネットワーク * ：
+
** DNSサーバ
** グリッドネットワーク
** NTPサーバ


* * メンテナンス * > * システム * ：
+
** ライセンス


* * 設定 * > * ネットワーク * ：
+
** S3エンドポイントのドメイン名


* * 設定 * > * セキュリティ * ：
+
** 証明書


* * コンフィグレーション * > * モニタリング * ：
+
** 監査と syslog サーバ






== アラートの管理

この権限では、アラートを管理するためのオプションにアクセスできます。サイレンス、アラート通知、アラートルールを管理するには、この権限が必要です。



== 指標クエリ

この権限により、次の項目にアクセスできます。

* *サポート*>*ツール*>*メトリクス*ページ
* グリッド管理APIの*[Metrics]*セクションを使用したカスタムのPrometheus指標クエリ
* Grid Managerの指標を含むダッシュボードカード




== オブジェクトメタデータの検索

この権限は、 * ILM * > * Object metadata lookup * ページへのアクセスを提供します。



== その他のグリッド設定

この権限で、追加のグリッド設定オプションにアクセスできます。


TIP: これらの追加オプションを表示するには、ユーザに * Grid トポロジページの設定 * 権限が必要です。

* * ILM * ：
+
** ストレージグレード


* * コンフィグレーション * > * システム * ：
* *サポート*>*その他*：
+
** リンクコスト






== ストレージアプライアンス管理者

この権限により、次のことが可能

* Grid Managerを使用して、ストレージアプライアンス上のEシリーズSANtricity System Managerにアクセスする。
* これらの処理をサポートするアプライアンスの[Manage Drives]タブで、トラブルシューティングとメンテナンスのタスクを実行する機能。




== テナントアカウント

この権限により、次のことが可能になります。

* [Tenants]ページにアクセスします。このページで、テナントアカウントを作成、編集、削除できます
* 既存のトラフィック分類ポリシーを表示します
* テナントの詳細を含むGrid Managerのダッシュボードカードを表示します

