---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: グリッド内の各ノードにはノードコンソールのパスワードが設定されており、このパスワードを使用してノードにログインします。デフォルトでは、各ノードには一意のパスワードが設定されます。各パスワードを新しい一意のパスワードに変更することも、グローバルパスワードを使用するように各ノードのパスワードを変更することもできます。パスワードはリカバリパッケージに格納されます。 
---
= ノードのコンソールパスワードを変更します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッド内の各ノードにはノードコンソールのパスワードが設定されており、このパスワードを使用してノードにログインします。デフォルトでは、各ノードには一意のパスワードが設定されます。各パスワードを新しい一意のパスワードに変更することも、グローバルパスワードを使用するように各ノードのパスワードを変更することもできます。パスワードはリカバリパッケージに格納されます。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたはを持っていますlink:admin-group-permissions.html["Maintenance権限またはRoot Access権限"]。
* 現在のプロビジョニングパスフレーズを用意します。


.タスクの内容
ノードのコンソールパスワードは、SSHを使用して「admin」としてノードにログインする場合、またはVM /物理コンソール接続でrootユーザにログインする場合に使用します。ノードコンソールのパスワードは、次のいずれかのオプションを使用して変更できます。

* 各ノードにランダムなパスワードを自動的に適用する
* 1つのグローバルパスワードを指定してすべてのノードに適用
* 1つ以上のノードに一意のパスワードを指定して適用する


パスワードは、リカバリパッケージ内の更新されたファイルに格納され `Passwords.txt`ます。パスワードは、ファイルの[Password]列に一覧表示されます。


NOTE: ノード間の通信に使用されるSSHキーのは、link:../admin/change-ssh-access-passwords.html["SSHアクセスパスワード"]ノードのコンソールパスワードとは別のものです。この手順では、SSHアクセスパスワードは変更されません。



== ウィザードにアクセスします

.手順
. * 設定 * > * アクセス制御 * > * Grid パスワード * を選択します。
. [ノードコンソールパスワードの変更]*で、*[変更する]*を選択します。




== [[download-current]]現在のリカバリパッケージをダウンロードします

ノードコンソールのパスワードを変更する前に、現在のリカバリパッケージをダウンロードします。いずれかのノードでパスワードの変更プロセスが失敗した場合は、このファイルのパスワードを使用できます。

.手順
. グリッドのプロビジョニングパスフレーズを入力します。
. [ リカバリパッケージのダウンロード ] を選択します。
. リカバリパッケージファイル(`.zip`を2つの安全でセキュアな場所にコピーします。
+

CAUTION: リカバリパッケージファイルにはStorageGRID システムからデータを取得するための暗号キーとパスワードが含まれているため、安全に保管する必要があります。

. 「 * Continue * 」を選択します。




== 新しいパスワードの入力

. 使用するパスワード変更方法を選択します。
+
** *自動*：StorageGRIDは、すべてのノードに新しいランダムコンソールパスワードを自動的に割り当てます。
** *カスタム*：コンソールパスワードを指定します。




[role="tabbed-block"]
====
.自動
--
. 「 * Continue * 」を選択します。


--
.カスタム
--
. 次のいずれかを選択します。
+
** *グローバルコンソールパスワード*：すべてのノードに同じコンソールパスワードを適用します。
** *一意のコンソールパスワード*：1つ以上のノードに別のパスワードを適用します。


. [グローバルコンソールパスワード]*を選択した場合は、すべてのノードに使用するパスワードを入力します。
. [一意のコンソールパスワード]*を選択した場合は、1つ以上のノードに対して一意のパスワードを入力します。
. 「 * Continue * 」を選択します。


--
====


== パスワードの変更を完了します。

. 確認ダイアログが表示されたら、StorageGRIDでノードコンソールのパスワードの変更を開始する準備ができている場合は*[はい]*を選択します。
+

NOTE: このプロセスは開始後にキャンセルすることはできません。

+
StorageGRIDは、新しいパスワードを含む新しいリカバリパッケージを生成します。

. 新しいリカバリパッケージの準備ができたら、*[新しいリカバリパッケージのダウンロード]*を選択してリカバリパッケージを保存します。
. ファイルを開き `.zip`ます。
. の内容にアクセスできることを確認します。これには、ノードコンソールの新しいパスワードが含まれています。ファイルも含ま `Passwords.txt`れます。
. 新しいリカバリパッケージファイル(`.zip`）を2つの安全でセキュアな場所にコピーします。
+

CAUTION: 古いリカバリパッケージを上書きしないでください。

+
リカバリファイルには、StorageGRIDシステムからデータを取得するための暗号キーとパスワードが含まれているため、安全に保管する必要があります。

. 新しいリカバリパッケージをダウンロードして内容を確認したことを示すチェックボックスを選択します。
. 「 * Continue * 」を選択します。
+
StorageGRIDによって、各ノードのパスワードが更新されます。

+
更新プロセス中にエラーが発生した場合は、進捗バーにパスワードの変更に失敗したノードの数が表示されます。パスワードを変更できなかったノードに対して、処理が自動的に再試行されます。プロセスが終了してもパスワードが変更されていないノードがある場合は、「 * Retry * 」ボタンが表示されます。

. 1 つ以上のノードでパスワードの更新に失敗した場合：
+
.. 表に表示されたエラーメッセージを確認します。
.. 問題を解決します。
.. [* Retry* ] を選択します。
+

NOTE: 再試行すると、前回のパスワード変更で失敗したノード上のノードコンソールパスワードのみが変更されます。



. 進捗バーに更新が残っていないことが示されたら、*[完了]*を選択します。
. すべてのノードのノードコンソールパスワードを変更したら、を削除し<<download-current,最初にダウンロードしたリカバリパッケージ>>ます。

