---
permalink: admin/change-ssh-access-passwords.html 
sidebar: sidebar 
keywords: ssh access keys, change ssh access keys 
summary: 管理ノードのSSHアクセスパスワードを変更すると、グリッド内の各ノードの一意の内部SSHキーセットも更新されます。プライマリ管理ノードは、これらのSSHキーを使用して、セキュアなパスワードレス認証を使用してノードにアクセスします。 
---
= 管理ノードのSSHアクセスパスワードの変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理ノードのSSHアクセスパスワードを変更すると、グリッド内の各ノードの一意の内部SSHキーセットも更新されます。プライマリ管理ノードは、これらのSSHキーを使用して、セキュアなパスワードレス認証を使用してノードにアクセスします。

SSHキーを使用して、VMまたは物理コンソール接続でノードに、またはrootユーザとしてログインし `admin`ます。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたはを持っていますlink:admin-group-permissions.html["Maintenance権限またはRoot Access権限"]。
* 現在のプロビジョニングパスフレーズを用意します。


.タスクの内容
管理ノードの新しいアクセスパスワードと各ノードの新しい内部キーは、 `Passwords.txt`リカバリ パッケージ内のファイル。キーはそのファイルの「パスワード」列にリストされています。

ノード間の通信に使用する SSH キー用に、個別の SSH アクセスパスワードがあります。これらはこの手順では変更されません。



== ウィザードにアクセスします

.手順
. *構成* > *アクセス制御* > *グリッド パスワード* を選択します。
. [SSHキーの変更]*で、*変更する*を選択します。




== [[download-current]]現在のリカバリパッケージをダウンロードします

SSH アクセス キーを変更する前に、現在のリカバリ パッケージをダウンロードしてください。いずれかのノードでキー変更プロセスが失敗した場合は、このファイル内のキーを使用できます。

.手順
. グリッドのプロビジョニングパスフレーズを入力します。
. [ リカバリパッケージのダウンロード ] を選択します。
. リカバリパッケージファイルをコピーする(`.zip`) を 2 つの安全でセキュリティ保護された別の場所に保管します。
+

CAUTION: リカバリ パッケージ ファイルには、 StorageGRIDシステムからデータを取得するために使用できる暗号化キーとパスワードが含まれているため、セキュリティで保護する必要があります。

. 「 * Continue * 」を選択します。
. 確認ダイアログが表示されたら、SSHアクセスキーの変更を開始する準備ができている場合は*[はい]*を選択します。
+

CAUTION: このプロセスは開始後にキャンセルすることはできません。





== SSHアクセスキーの変更

SSH アクセス キーの変更プロセスが開始されると、新しいキーを含む新しい回復パッケージが生成されます。その後、各ノードでキーが更新されます。

.手順
. 新しい回復パッケージが生成されるまで待ちます。これには数分かかる場合があります。
. 新しいリカバリパッケージのダウンロードボタンが有効になったら、*新しいリカバリパッケージのダウンロード*を選択し、新しいリカバリパッケージファイルを保存します。(`.zip` ) を 2 つの安全でセキュリティ保護された別の場所に保管します。
. ダウンロードが完了したら、次の手順を実行
+
.. ファイルを開き `.zip`ます。
.. 新しいSSHアクセスキーを含むファイルなどのコンテンツにアクセスできることを確認します `Passwords.txt`。
.. 新しいリカバリパッケージファイルをコピーします(`.zip`) を 2 つの安全でセキュリティ保護された別の場所に保管します。
+

CAUTION: 古いリカバリ パッケージを上書きしないでください。

+
リカバリ パッケージ ファイルには、 StorageGRIDシステムからデータを取得するために使用できる暗号化キーとパスワードが含まれているため、セキュリティで保護する必要があります。



. 各ノードでキーが更新されるまで待ちます。更新には数分かかることがあります。
+
すべてのノードでキーを変更すると、成功を示す緑色のバナーが表示されます。

+
更新プロセス中にエラーが発生した場合は、バナーメッセージにキーが変更されなかったノードの数が表示されます。キーの変更に失敗したノードでは、プロセスが自動的に再試行されます。一部のノードでキーが変更されていない状態でプロセスが終了すると、* Retry *ボタンが表示されます。

+
1つ以上のノードでキーの更新に失敗した場合：

+
.. 表に表示されたエラーメッセージを確認します。
.. 問題を解決します。
.. [* Retry* ] を選択します。
+
再試行すると、前回のキー変更で失敗したノードのSSHアクセスキーだけが変更されます。



. すべてのノードのSSHアクセスキーが変更されたら、<<download-current,最初にダウンロードしたリカバリパッケージ>> 。
. 必要に応じて、[メンテナンス] > [システム] > [回復パッケージ] を選択して、新しい回復パッケージの追加コピーをダウンロードします。

