---
permalink: admin/changing-browser-session-timeout-interface.html 
sidebar: sidebar 
keywords: security, browser inactivity timeout, management API stack track 
summary: インターフェイスのセキュリティ設定では、ユーザが指定した時間以上非アクティブであった場合にサインアウトするかどうか、およびスタックトレースをAPIエラー応答に含めるかどうかを制御できます。 
---
= インターフェイスセキュリティ設定の変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
インターフェイスのセキュリティ設定では、ユーザが指定した時間以上非アクティブであった場合にサインアウトするかどうか、およびスタックトレースをAPIエラー応答に含めるかどうかを制御できます。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* そうだな link:admin-group-permissions.html["rootアクセス権限"]


.タスクの内容
[セキュリティ設定]ページには、*ブラウザの非アクティブタイムアウト*と*管理APIスタックトレース*の設定が含まれています。

ブラウザの非アクティブタイムアウト:: ユーザのブラウザが非アクティブになってからサインアウトされるまでの時間を示します。デフォルトは15分です。
+
--
ブラウザの非アクティブ時のタイムアウトは、次の方法でも制御されます。

* システムセキュリティ用の、個別の設定不可能な StorageGRID タイマー。各ユーザの認証トークンは、ユーザがサインインしてから16時間後に期限切れになります。ユーザの認証が期限切れになると、ブラウザの非アクティブタイムアウトが無効になっていたり、ブラウザのタイムアウト値に達していない場合でも、そのユーザは自動的にサインアウトされます。トークンを更新するには、再度サインインする必要があります。
* アイデンティティプロバイダのタイムアウト設定（StorageGRID でシングルサインオン（SSO）が有効になっている場合）。
+
SSO が有効になっていて、ユーザーのブラウザがタイムアウトした場合、ユーザーは SSO 資格情報を再入力してStorageGRID に再度アクセスする必要があります。見るlink:how-sso-works.html["SSOの動作"] 。



--
管理APIスタックトレース:: Grid ManagerおよびTenant Manager APIのエラー応答でスタックトレースを返すかどうかを制御します。
+
--
このオプションはデフォルトでは無効になっていますが、テスト環境では有効にすることもできます。一般に、本番環境では、APIエラーが発生したときに内部ソフトウェアの詳細が表示されないように、スタックトレースは無効のままにしておく必要があります。

--


.手順
. *構成* > *セキュリティ* > *セキュリティ設定*を選択します。
. [インターフェイス]*タブを選択します。
. ブラウザ非アクティブタイムアウトの設定を変更するには、次の手順を実行します。
+
.. アコーディオンを展開します。
.. タイムアウト期間を変更するには、60秒から7日間の値を指定します。デフォルトのタイムアウトは15分です。
.. この機能を無効にするには、チェックボックスをオフにします。
.. [ 保存（ Save ） ] を選択します。
+
新しい設定は、現在サインインしているユーザーには影響しません。新しいタイムアウト設定を有効にするには、再度サインインするか、ブラウザを更新する必要があります。



. 管理APIスタックトレースの設定を変更するには、次の手順を実行します。
+
.. アコーディオンを展開します。
.. Grid ManagerおよびTenant Manager APIのエラー応答でスタックトレースを返す場合は、チェックボックスを選択します。
+

CAUTION: APIエラーが発生したときに内部ソフトウェアの詳細が表示されないように、本番環境ではスタックトレースを無効のままにします。

.. [ 保存（ Save ） ] を選択します。



