---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: グリッド内の各ノードにはノード コンソール パスワードがあり、これを使用してノードにログインします。デフォルトでは、各ノードには一意のパスワードがあります。各パスワードを新しい一意のパスワードに変更することも、すべてのノードのパスワードを変更してグローバル パスワードを使用することもできます。パスワードはリカバリ パッケージに保存されます。 
---
= ノードのコンソールパスワードを変更します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッド内の各ノードにはノード コンソール パスワードがあり、これを使用してノードにログインします。デフォルトでは、各ノードには一意のパスワードがあります。各パスワードを新しい一意のパスワードに変更することも、すべてのノードのパスワードを変更してグローバル パスワードを使用することもできます。パスワードはリカバリ パッケージに保存されます。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたはを持っていますlink:admin-group-permissions.html["Maintenance権限またはRoot Access権限"]。
* 現在のプロビジョニングパスフレーズを用意します。


.タスクの内容
ノード コンソール パスワードは、SSH を使用して「admin」としてノードにログインするか、VM/物理コンソール接続で root ユーザーとしてログインするために使用します。次のいずれかのオプションを使用して、ノード コンソールのパスワードを変更できます。

* 各ノードにランダムなパスワードを自動的に適用する
* すべてのノードに1つのグローバルパスワードを指定して適用する
* 1 つ以上のノードに一意のパスワードを指定して適用します


パスワードは更新された `Passwords.txt`リカバリ パッケージ内のファイル。パスワードはファイル内の「パスワード」列にリストされます。


NOTE: そのlink:../admin/change-ssh-access-passwords.html["SSHアクセスパスワード"]ノード間の通信に使用される SSH キーは、ノード コンソールのパスワードとは別です。この手順では、SSH アクセス パスワードは変更されません。



== ウィザードにアクセスします

.手順
. *構成* > *アクセス制御* > *グリッド パスワード* を選択します。
. [ノードコンソールパスワードの変更]*で、*[変更する]*を選択します。




== [[download-current]]現在のリカバリパッケージをダウンロードします

ノード コンソールのパスワードを変更する前に、現在のリカバリ パッケージをダウンロードしてください。いずれかのノードでパスワード変更プロセスが失敗した場合は、このファイル内のパスワードを使用できます。

.手順
. グリッドのプロビジョニングパスフレーズを入力します。
. [ リカバリパッケージのダウンロード ] を選択します。
. リカバリパッケージファイルをコピーする(`.zip`) を 2 つの安全でセキュリティ保護された別の場所に保管します。
+

CAUTION: リカバリ パッケージ ファイルには、 StorageGRIDシステムからデータを取得するために使用できる暗号化キーとパスワードが含まれているため、セキュリティで保護する必要があります。

. 「 * Continue * 」を選択します。




== 新しいパスワードを入力してください

. 使用するパスワード変更方法を選択します。
+
** *自動*: StorageGRID は、すべてのノードに新しいランダムなコンソール パスワードを自動的に割り当てます。
** *カスタム*: コンソールのパスワードを入力します。




[role="tabbed-block"]
====
.自動
--
. 「 * Continue * 」を選択します。


--
.カスタム
--
. 次のいずれかを選択します。
+
** *グローバル コンソール パスワード*: すべてのノードに同じコンソール パスワードを適用します。
** *一意のコンソール パスワード*: 1 つ以上のノードに異なるパスワードを適用します。


. *グローバル コンソール パスワード* を選択した場合は、すべてのノードに使用するパスワードを入力します。
. *一意のコンソール パスワード* を選択した場合は、1 つ以上のノードに対して一意のパスワードを入力します。
. 「 * Continue * 」を選択します。


--
====


== パスワードの変更を完了する

. 確認ダイアログが表示されたら、 StorageGRIDがノード コンソールのパスワードの変更を開始する準備ができたら、[*はい*] を選択します。
+

NOTE: このプロセスは開始後にキャンセルすることはできません。

+
StorageGRID は、新しいパスワードを含む新しいリカバリ パッケージを生成します。

. 新しいリカバリ パッケージの準備ができたら、[新しいリカバリ パッケージをダウンロード] を選択し、リカバリ パッケージを保存します。
. ファイルを開き `.zip`ます。
. の内容にアクセスできることを確認します。これには、ノードコンソールの新しいパスワードが含まれています。ファイルも含ま `Passwords.txt`れます。
. 新しいリカバリパッケージファイルをコピーします(`.zip`) を 2 つの安全でセキュリティ保護された別の場所に保管します。
+

CAUTION: 古いリカバリ パッケージを上書きしないでください。

+
リカバリ ファイルには、 StorageGRIDシステムからデータを取得するために使用できる暗号化キーとパスワードが含まれているため、セキュリティで保護する必要があります。

. 新しいリカバリ パッケージをダウンロードし、その内容を確認したことを示すには、チェックボックスを選択します。
. 「 * Continue * 」を選択します。
+
StorageGRID は各ノードのパスワードを更新します。

+
更新プロセス中にエラーが発生した場合、進行状況バーにパスワードの変更に失敗したノードの数が表示されます。システムは、パスワードの変更に失敗したノードに対してプロセスを自動的に再試行します。一部のノードでパスワードが変更されていない状態でプロセスが終了した場合は、[再試行] ボタンが表示されます。

. 1 つ以上のノードでパスワードの更新に失敗した場合：
+
.. 表に表示されたエラーメッセージを確認します。
.. 問題を解決します。
.. [* Retry* ] を選択します。
+

NOTE: 再試行すると、前回のパスワード変更で失敗したノード上のノードコンソールパスワードのみが変更されます。



. 進行状況バーに残りの更新がないことが示されたら、[完了] を選択します。
. すべてのノードのノードコンソールのパスワードが変更されたら、<<download-current,最初にダウンロードしたリカバリパッケージ>> 。

