---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: グリッド内の各ノードには、一意のノードコンソールパスワードが設定されています。このパスワードを使用してノードにログインする必要があります。グリッド内の各ノードのノードコンソールパスワードを変更するには、次の手順を実行します。パスワードはリカバリパッケージに保存されます。 
---
= ノードのコンソールパスワードを変更します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッド内の各ノードには、一意のノードコンソールパスワードが設定されています。このパスワードを使用してノードにログインする必要があります。次の手順に従って、グリッド内のノードごとに一意のノードコンソールパスワードを変更します。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたはを持っていますlink:admin-group-permissions.html["Maintenance権限またはRoot Access権限"]。
* 現在のプロビジョニングパスフレーズを用意します。


.タスクの内容
ノードのコンソールパスワードを使用して、SSHを使用してノードに「admin」としてログインするか、VM /物理コンソール接続でrootユーザにログインします。ノードコンソールパスワードの変更プロセスでは、グリッド内の各ノードに対して新しいパスワードが作成され、更新されたファイルにリカバリパッケージに格納され `Passwords.txt`ます。パスワードは、 Passwords.txt ファイルの Password 列に表示されます。


NOTE: ノード間の通信に使用する SSH キー用に、個別の SSH アクセスパスワードがあります。SSHアクセスパスワードは、この手順 では変更されません。



== ウィザードにアクセスします

.手順
. * 設定 * > * アクセス制御 * > * Grid パスワード * を選択します。
. [ノードコンソールパスワードの変更]*で、*[変更する]*を選択します。




== プロビジョニングパスフレーズを入力します

.手順
. グリッドのプロビジョニングパスフレーズを入力します。
. 「 * Continue * 」を選択します。




== [[download-current]]現在のリカバリパッケージをダウンロードします

ノードコンソールのパスワードを変更する前に、現在のリカバリパッケージをダウンロードしてください。いずれかのノードでパスワードの変更プロセスが失敗した場合は、このファイルのパスワードを使用できます。

.手順
. [ リカバリパッケージのダウンロード ] を選択します。
. リカバリパッケージファイル(`.zip`を2つの安全でセキュアな場所にコピーします。
+

CAUTION: リカバリパッケージファイルには StorageGRID システムからデータを取得するための暗号キーとパスワードが含まれているため、安全に保管する必要があります。

. 「 * Continue * 」を選択します。
. 確認ダイアログが表示されたら、ノードコンソールのパスワードの変更を開始する準備ができている場合は*[はい]*を選択します。
+
このプロセスは開始後にキャンセルすることはできません。





== ノードのコンソールパスワードを変更します

ノードのコンソールパスワードのプロセスが開始されると、新しいパスワードを含む新しいリカバリパッケージが生成されます。その後、各ノードでパスワードが更新されます。

.手順
. 新しいリカバリパッケージが生成されるまで待ちます。これには数分かかることがあります。
. [ 新しいリカバリパッケージのダウンロード ] を選択します。
. ダウンロードが完了したら、次の手順を実行
+
.. ファイルを開き `.zip`ます。
.. の内容にアクセスできることを確認します。これには、ノードコンソールの新しいパスワードが含まれています。ファイルも含ま `Passwords.txt`れます。
.. 新しいリカバリパッケージファイル(`.zip`を2つの安全でセキュアな場所にコピーします。
+

CAUTION: 古いリカバリパッケージを上書きしないでください。

+
リカバリパッケージファイルには StorageGRID システムからデータを取得するための暗号キーとパスワードが含まれているため、安全に保管する必要があります。



. 新しいリカバリパッケージをダウンロードして内容を確認したことを示すチェックボックスを選択します。
. [ノードコンソールパスワードの変更]*を選択し、すべてのノードが新しいパスワードで更新されるまで待ちます。この処理には数分かかることがあります。
+
すべてのノードでパスワードを変更した場合は、成功を示す緑のバナーが表示されます。次の手順に進みます。

+
更新プロセスでエラーが発生した場合は、バナーメッセージにパスワードを変更できなかったノードの数が表示されます。パスワードを変更できなかったノードに対して、処理が自動的に再試行されます。プロセスが終了してもパスワードが変更されていないノードがある場合は、「 * Retry * 」ボタンが表示されます。

+
1 つ以上のノードでパスワードの更新に失敗した場合：

+
.. 表に表示されたエラーメッセージを確認します。
.. 問題を解決します。
.. [* Retry* ] を選択します。
+

NOTE: 再試行すると、前回のパスワード変更で失敗したノード上のノードコンソールパスワードのみが変更されます。



. すべてのノードのノードコンソールパスワードを変更したら、を削除し<<download-current,最初にダウンロードしたリカバリパッケージ>>ます。
. 必要に応じて、 * Recovery パッケージ * リンクを使用して、新しいリカバリパッケージの追加コピーをダウンロードできます。

