---
permalink: admin/changing-network-options-object-encryption.html 
sidebar: sidebar 
keywords: enable http, storage node connections 
summary: ネットワークとオブジェクトのセキュリティを設定して、格納オブジェクトの暗号化、特定のS3要求の防止、ストレージノードへのクライアント接続でHTTPSではなくHTTPを使用できるようにすることができます。 
---
= ネットワークとオブジェクトのセキュリティを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ネットワークとオブジェクトのセキュリティを設定して、格納オブジェクトの暗号化、特定のS3要求の防止、ストレージノードへのクライアント接続でHTTPSではなくHTTPを使用できるようにすることができます。



== 格納オブジェクトの暗号化

格納オブジェクトの暗号化を使用すると、S3経由で取り込まれたすべてのオブジェクトデータを暗号化できます。デフォルトでは、格納オブジェクトは暗号化されませんが、AES‐128またはAES‐256暗号化アルゴリズムを使用してオブジェクトを暗号化することができます。この設定を有効にすると、新たに取り込まれたすべてのオブジェクトが暗号化されますが、既存の格納オブジェクトに対する変更はありません。暗号化を無効にすると、現在暗号化されているオブジェクトは暗号化されたままですが、新しく取り込まれたオブジェクトは暗号化されません

格納オブジェクトの暗号化設定は、バケットレベルまたはオブジェクトレベルの暗号化で暗号化されていないS3オブジェクトにのみ適用されます。

StorageGRID暗号化方式の詳細については、を参照してくださいlink:../admin/reviewing-storagegrid-encryption-methods.html["StorageGRID の暗号化方式を確認します"]。



== クライアントの変更を防止します

[Prevent client modification]は、システム全体の設定です。[Prevent client modification *]オプションを選択すると、次の要求が拒否されます。



=== S3 REST API

* DeleteBucketヨウキユウ
* 既存オブジェクトのデータ、ユーザ定義メタデータ、または S3 オブジェクトのタグを変更するすべての要求




== ストレージノード接続用のHTTPを有効にします

デフォルトでは、クライアントアプリケーションは、ストレージノードへの直接接続にHTTPSネットワークプロトコルを使用します。非本番環境のグリッドのテストなどの目的で、これらの接続に対して HTTP を有効にすることもできます。

ストレージノード接続にHTTPを使用するのは、S3クライアントからストレージノードへのHTTP接続を直接確立する必要がある場合のみです。HTTPS接続のみを使用するクライアントや、ロードバランササービスに接続するクライアント（HTTPまたはHTTPSを使用できるため）には、このオプションを使用する必要はありませんlink:../admin/configuring-load-balancer-endpoints.html["各ロードバランサエンドポイントを設定します"]。

S3クライアントがHTTPまたはHTTPSを使用してストレージノードに接続するときに使用するポートについては、を参照してくださいlink:summary-ip-addresses-and-ports-for-client-connections.html["Summary ：クライアント接続の IP アドレスとポート"]。



== オプションを選択します

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* Root Access 権限が割り当てられている。


.手順
. *構成* > *セキュリティ* > *セキュリティ設定*を選択します。
. [ネットワークとオブジェクト]タブを選択します。
. 格納オブジェクトを暗号化しない場合は*なし*（デフォルト）設定を使用し、格納オブジェクトを暗号化する場合は* AES-128 *または* AES-256 *を選択します。
. 必要に応じて、[Prevent client modification]*を選択し、S3クライアントが特定の要求を実行しないようにします。
+

NOTE: この設定を変更すると、新しい設定が適用されるまで約 1 分かかります。設定した値は、パフォーマンスと拡張用にキャッシュされます。

. 必要に応じて、クライアントがストレージノードに直接接続し、HTTP接続を使用する場合は、*[ストレージノード接続用のHTTPを有効にする]*を選択します。
+

NOTE: 要求が暗号化されずに送信されるため、本番環境のグリッドで HTTP を有効にする場合は注意してください。

. [ 保存（ Save ） ] を選択します。

