---
permalink: admin/configure-sso-oidc.html 
sidebar: sidebar 
keywords: use sandbox mode for sso, how to test single sign-on 
summary: OIDC の SSO 設定ウィザードに従ってサンドボックスモードに入り、すべての StorageGRID ユーザーに対して有効にする前に、シングル サインオン（SSO）の設定とテストを行うことができます。SSO を有効にした後、必要に応じてサンドボックスモードに戻り、設定を変更したり再テストしたりできます。 
---
= OIDC を使用して StorageGRID で SSO を設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OpenID Connect (OIDC) の SSO 設定ウィザードに従い、サンドボックスモードに入って設定とテストを行います。すべての StorageGRID ユーザーに対してシングル サインオン（SSO）を有効にする前に、設定とテストを実施してください。SSO を有効にした後、必要に応じてサンドボックスモードに戻り、設定を変更したり再テストしたりできます。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたはを持っていますlink:admin-group-permissions.html["rootアクセス権限"]。
* StorageGRID システムの SSO ID プロバイダーで OIDC クライアントを設定しました。
* StorageGRID システムにlink:using-identity-federation.html["アイデンティティフェデレーションが設定された"]があります。




[[step-1-provide-identity-provider-details]]
== ステップ1：IDプロバイダーの詳細を入力する

ウィザードにアクセスし、「IDプロバイダーの詳細を入力する」ページの各項目を入力します。

.手順
. SSO設定を構成するウィザードにアクセスします。
+
.. *構成* > *アクセス制御* > *シングル サインオン* を選択します。シングル サインオン ページが表示されます。
+

NOTE: [SSO 設定の構成] ボタンが無効になっている場合は、ID プロバイダーをフェデレーション ID ソースとして構成していることを確認します。。 link:requirements-for-sso.html["シングルサインオンの要件と考慮事項"] 。

.. *SSO設定の構成*を選択します。  「ID プロバイダーの詳細を提供する」ページが表示されます。


. *プロトコル* で *OIDC* を選択します。
. ドロップダウンリストから * SSO タイプ * を選択します。
. StorageGRID 要求への応答としてアイデンティティプロバイダが SSO 設定情報を送信するときに、接続の保護に使用する TLS 証明書を指定します。
+
** * オペレーティング・システムの CA 証明書を使用 * ：オペレーティング・システムにインストールされているデフォルトの CA 証明書を使用して、接続を保護します。
** * カスタム CA 証明書を使用 * ：カスタム CA 証明書を使用して接続を保護します。
+
この設定を選択した場合：

+
... CA証明書の場所を参照します。
... CA証明書ファイルをアップロードします。


** *TLS を使用しない*：接続を保護するために TLS 証明書を使用しません。
+

CAUTION: CA証明書を変更した場合は、すぐにlink:../maintain/starting-or-restarting-service.html["管理ノードでmgmt-apiサービスを再起動します。"]Grid ManagerでSSOが成功するかどうかをテストします。



. *続行*を選択します。  「証明書利用者識別子の提供」ページが表示されます。




[[enter-sandbox-modestep-2-enter-client-information]]
== [[enter-sandbox-mode]]ステップ2：クライアント情報を入力する

ウィザードの「クライアント情報の入力」ステップで、各項目を入力してください。

.手順
. StorageGRID の *依拠当事者識別子* を指定します。この値は、各 OIDC 構成に使用する名前を制御します。
+
** たとえば、グリッドに管理ノードが1つしかなく、今後管理ノードを追加する予定がない場合は、または `StorageGRID`と入力し `SG`ます。
** グリッドに複数の管理ノードが含まれている場合は、識別子に文字列 `[HOSTNAME]`を含めてください。例： `SG-[HOSTNAME]`。この文字列を含めると、グリッド内の各管理ノードのホスト名に基づいて、そのノードの OIDC 構成を示すテーブルが作成されます。
+

NOTE: StorageGRIDシステムの管理ノードに対してOIDCを設定する必要があります。これにより、ユーザーはどの管理ノードにも安全にサインインおよびサインアウトできるようになります。すべての管理ノードで同じOIDC構成を使用することも（推奨）、各管理ノードに異なるOIDC構成を設定することもできます。



. 各依拠当事者識別子について、*クライアントID*、*クライアントシークレット*、および*OpenIDエンドポイントURL*を入力してください。
. *保存してサンドボックスモードに入る*を選択します。




[[step-3-test-configuration]]
== ステップ3：テスト構成

サンドボックスモードに入ると、選択したSSOタイプの構成を完了してテストできます。

サンドボックスモードを使用すると、設定のやり取りを簡単に実行し、SSOを有効にする前にすべての設定をテストできます。StorageGRIDは、必要に応じてサンドボックスモードを維持できます。ただし、サインインできるのはフェデレーションユーザーとローカルユーザーのみです。

.手順
. 「SSO の構成」ページで、ウィザードの「構成のテスト」手順のリンクを見つけます。
+
URL は、 [ * フェデレーションサービス名 * （ * Federation service name * ） ] フィールドに入力した値から取得されます。

. [[select-link]]リンクを選択するか、URLをコピーして新しいタブに貼り付けて、IDプロバイダーのサインオンページにアクセスしてください。
. [[enter-credentials]]フェデレーションユーザー名とパスワードを入力してください。
+
** SSOのサインインとログアウトが正常に完了すると、緑色のバナーが表示されます。
** SSO 処理が失敗すると、エラーメッセージが表示されます。問題 を修正し、ブラウザのクッキーを消去してやり直してください。


. ウィザードの手順に従って、グリッド内の各管理ノードのテスト構成ページにアクセスしてください。
. 手順 <<select-link,2>> および <<enter-credentials,3>> を繰り返して、各管理ノードの SSO 接続を確認します。




[[enable-sso-oidcstep-4-enable-single-sign-on]]
== [[enable-sso-oidc]]ステップ4：シングル サインオンを有効にする

各管理ノードへのサインインにSSOを使用できることを確認したら、StorageGRIDシステム全体でSSOを有効にできます。


TIP: SSOが有効になっている場合、すべてのユーザーは、グリッドマネージャ、テナントマネージャ、グリッド管理API、およびテナント管理APIにアクセスするためにSSOを使用する必要があります。ローカルユーザーはStorageGRIDにアクセスできなくなります。StorageGRIDは、サポートされているすべてのSSOプロバイダーに対応した認証スクリプトの例を提供していません。

.手順
. SSO 構成ウィザードのテスト構成手順で、*SSO を有効にする* を選択します。
. 警告メッセージを確認し、*SSO を有効にする*を選択します。
+
シングル サインオンが有効になりました。シングル サインオン ページが表示され、先ほど構成した SSO の詳細が表示されます。

. 設定を編集するには、[*編集*] を選択します。
. シングル サインオンを無効にするには、*無効にする*を選択してください。



TIP: Azure ポータルを使用しており、Entra ID にアクセスするために使用するのと同じコンピューターからStorageGRID にアクセスする場合は、Azure ポータル ユーザーが承認されたStorageGRIDユーザー ( StorageGRIDにインポートされたフェデレーション グループ内のユーザー) であることを確認するか、 StorageGRIDにサインインする前に Azure ポータルからログアウトしてください。
