---
permalink: admin/configure-sso.html 
sidebar: sidebar 
keywords: use sandbox mode for sso, how to test single sign-on 
summary: SSOの設定ウィザードに従ってサンドボックスモードに切り替えてシングルサインオン（SSO\）を設定およびテストしてから、すべてのStorageGRIDユーザに対してシングルサインオン（SSO\）を有効にすることができます。SSOを有効にしたあと、構成の変更や再テストが必要になったときにサンドボックスモードに戻ることができます。 
---
= SSOの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSOの設定ウィザードに従ってサンドボックスモードに切り替えてシングルサインオン（SSO）を設定およびテストしてから、すべてのStorageGRIDユーザに対してSSOを有効にすることができます。SSOを有効にしたあと、構成を変更または再テストする必要がある場合はサンドボックスモードに戻ることができます。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたはを持っていますlink:admin-group-permissions.html["rootアクセス権限"]。
* StorageGRID システムにアイデンティティフェデレーションを設定しておきます。
* アイデンティティフェデレーション* LDAPサービスタイプ*では、使用するSSOアイデンティティプロバイダに基づいて[Active Directory]または[Entra ID]のいずれかを選択しました。
+
[cols="1a,1a"]
|===
| LDAP サービスタイプが設定されました | SSO アイデンティティプロバイダのオプション 


 a| 
Active Directory フェデレーションサービス（ AD FS ）
 a| 
** Active Directory
** エントラID
** PingFederate




 a| 
エントラID
 a| 
エントラID

|===


.タスクの内容
SSO が有効な場合、ユーザが管理ノードにサインインしようとすると、 StorageGRID から SSO アイデンティティプロバイダに認証要求が送信されます。次に、 SSO アイデンティティプロバイダは、認証要求が成功したかどうかを示す認証応答を StorageGRID に返します。成功した要求の場合：

* Active Directory または PingFederate からの応答には、ユーザの Universally Unique Identifier （ UUID ）が含まれています。
* Entra IDからの応答には、ユーザプリンシパル名（UPN）が含まれます。


StorageGRID（サービスプロバイダー）とSSO IDプロバイダーがユーザー認証要求について安全に通信できるようにするには、次のタスクを実行します。

. StorageGRIDで設定を行います。
. SSOアイデンティティプロバイダのソフトウェアを使用して、管理ノードごとに証明書利用者信頼（AD FS）、エンタープライズアプリケーション（Entra ID）、またはサービスプロバイダ（PingFederate）を作成します。
. StorageGRIDに戻り、SSOを有効にします。


サンドボックスモードでは、 SSO を有効にする前に、この手順を簡単に実行し、すべての設定をテストできます。サンドボックスモードを使用している場合、ユーザーはSSOを使用してサインインできません。



== ウィザードにアクセスします

.手順
. [ * 設定 * > * アクセス制御 * > * シングルサインオン * ] を選択します。Single Sign-Onページが表示されます。
+

NOTE: [Configure SSO settings]ボタンが無効になっている場合は、アイデンティティプロバイダをフェデレーテッドアイデンティティソースとして設定していることを確認します。を参照してください link:requirements-for-sso.html["シングルサインオンの要件と考慮事項"]。

. [SSO設定の構成]*を選択します。[Provide Identity Provider details]ページが表示されます。




== アイデンティティプロバイダの詳細を指定する

.手順
. ドロップダウンリストから * SSO タイプ * を選択します。
. SSOタイプとしてActive Directoryを選択した場合は、アイデンティティプロバイダの*フェデレーションサービス名*を、Active Directoryフェデレーションサービス（AD FS）に表示されるとおりに入力します。
+

NOTE: フェデレーションサービス名を確認するには、 Windows Server Manager に移動します。[ ツール *>*AD FS 管理 *] を選択します。[ アクション ] メニューから、 [ * フェデレーションサービスのプロパティの編集 * ] を選択します。フェデレーションサービス名が 2 番目のフィールドに表示されます。

. StorageGRID 要求への応答としてアイデンティティプロバイダが SSO 設定情報を送信するときに、接続の保護に使用する TLS 証明書を指定します。
+
** * オペレーティング・システムの CA 証明書を使用 * ：オペレーティング・システムにインストールされているデフォルトの CA 証明書を使用して、接続を保護します。
** * カスタム CA 証明書を使用 * ：カスタム CA 証明書を使用して接続を保護します。
+
この設定を選択した場合は、カスタム証明書のテキストをコピーし、 * CA 証明書 * テキストボックスに貼り付けます。

** * Do not use TLS* ： TLS 証明書を使用して接続を保護しないでください。
+

CAUTION: CA証明書を変更した場合は、すぐにlink:../maintain/starting-or-restarting-service.html["管理ノードでmgmt-apiサービスを再起動します。"]Grid ManagerでSSOが成功するかどうかをテストします。



. 「 * Continue * 」を選択します。[証明書利用者IDの指定]ページが表示されます。




== [[enter-sandbox-mode]]証明書利用者IDを指定します

. 選択したSSOタイプに基づいて、[Provide relying party identifier]ページのフィールドに値を入力します。
+
[role="tabbed-block"]
====
.Active Directory
--
.. StorageGRIDの*証明書利用者ID *を指定します。この値は、 AD FS の各証明書利用者信頼に使用する名前を制御します。
+
*** たとえば、グリッドに管理ノードが1つしかなく、今後管理ノードを追加する予定がない場合は、または `StorageGRID`と入力し `SG`ます。
*** グリッドに複数の管理ノードが含まれている場合は、識別子に文字列を含め `[HOSTNAME]`ます。たとえば、 `SG-[HOSTNAME]`です。この文字列を含めると、グリッド内の各管理ノードの証明書利用者IDがノードのホスト名に基づいて表に表示されます。
+

NOTE: 証明書利用者信頼は StorageGRID システム内の管理ノードごとに作成する必要があります。管理ノードごとに証明書利用者信頼を作成することで、ユーザは管理ノードに対して安全にサインイン / サインアウトすることができます。



.. [保存]を選択してサンドボックスモードに切り替えます*。


--
.エントラID
--
.. [ エンタープライズアプリケーション ] セクションで、 StorageGRID のエンタープライズアプリケーション名 * を指定します。この値は、Entra IDで各エンタープライズアプリケーションに使用する名前を制御します。
+
*** たとえば、グリッドに管理ノードが1つしかなく、今後管理ノードを追加する予定がない場合は、または `StorageGRID`と入力し `SG`ます。
*** グリッドに複数の管理ノードが含まれている場合は、識別子に文字列を含め `[HOSTNAME]`ます。たとえば、 `SG-[HOSTNAME]`です。この文字列を含めると、ノードのホスト名に基づいて、システム内の各管理ノードのエンタープライズアプリケーション名が表に表示されます。
+

NOTE: StorageGRID システムで管理ノードごとにエンタープライズアプリケーションを作成する必要があります。管理ノードごとにエンタープライズアプリケーションを用意することで、ユーザはどの管理ノードに対しても安全にサインイン / サインアウトすることができます。



.. 表に記載されている管理ノードごとにエンタープライズアプリケーションを作成するには、の手順に従いlink:../admin/creating-enterprise-application-entra-id.html["Entra IDでのエンタープライズアプリケーションの作成"]ます。
.. Entra IDから、各エンタープライズアプリケーションのフェデレーションメタデータURLをコピーします。次に、この URL を StorageGRID の対応する * フェデレーションメタデータ URL* フィールドに貼り付けます。
.. すべての管理ノードのフェデレーションメタデータURLをコピーして貼り付けたら、*[保存]を選択してサンドボックスモードに切り替えます*。


--
.PingFederate
--
.. Service Provider （ SP ；サービスプロバイダ）セクションで、 StorageGRID の * SP 接続 ID * を指定します。この値は、 PingFederate の各 SP 接続に使用する名前を制御します。
+
*** たとえば、グリッドに管理ノードが1つしかなく、今後管理ノードを追加する予定がない場合は、または `StorageGRID`と入力し `SG`ます。
*** グリッドに複数の管理ノードが含まれている場合は、識別子に文字列を含め `[HOSTNAME]`ます。たとえば、 `SG-[HOSTNAME]`です。この文字列を含めると、システム内の各管理ノードのSP接続IDがノードのホスト名に基づいて表に表示されます。
+

NOTE: StorageGRID システムで管理ノードごとに SP 接続を作成する必要があります。管理ノードごとに SP 接続を確立することで、ユーザは管理ノードに対して安全にサインイン / サインアウトすることができます。



.. 各管理ノードのフェデレーションメタデータの URL を * Federation metadata url * フィールドで指定します。
+
次の形式を使用します。

+
[listing]
----
https://<Federation Service Name>:<port>/pf/federation_metadata.ping?PartnerSpId=<SP Connection ID>
----
.. [保存]を選択してサンドボックスモードに切り替えます*。


--
====




== 証明書利用者信頼、エンタープライズアプリケーション、または SP 接続を設定する

構成を保存してサンドボックスモードに切り替えたら、選択したSSOタイプの構成を完了してテストできます。

StorageGRID は、必要に応じてサンドボックスモードのままにすることができます。ただし、でサインインできるのは、フェデレーテッドユーザとローカルユーザだけです。

[role="tabbed-block"]
====
.Active Directory
--
.手順
. Active Directory フェデレーションサービス（ AD FS ）に移動します。
. [SSOの設定]ページの表に表示された各証明書利用者IDを使用して、StorageGRIDの証明書利用者信頼を1つ以上作成します。
+
次の表に示す管理ノードごとに信頼を 1 つ作成する必要があります。

+
手順については、を参照してくださいlink:../admin/creating-relying-party-trusts-in-ad-fs.html["AD FS に証明書利用者信頼を作成します"]。



--
.エントラID
--
.手順
. 現在サインインしている管理ノードのシングルサインオンページから、 SAML メタデータをダウンロードして保存するボタンを選択します。
. グリッド内の他の管理ノードについて、上記の手順を繰り返します。
+
.. ノードにサインインします。
.. [ * 設定 * > * アクセス制御 * > * シングルサインオン * ] を選択します。
.. そのノードの SAML メタデータをダウンロードして保存します。


. Azureポータルに移動します。
. の手順に従って、link:../admin/creating-enterprise-application-entra-id.html["Entra IDでのエンタープライズアプリケーションの作成"]各管理ノードのSAMLメタデータファイルを対応するEntra IDエンタープライズアプリケーションにアップロードします。


--
.PingFederate
--
.手順
. 現在サインインしている管理ノードのシングルサインオンページから、 SAML メタデータをダウンロードして保存するボタンを選択します。
. グリッド内の他の管理ノードについて、上記の手順を繰り返します。
+
.. ノードにサインインします。
.. [ * 設定 * > * アクセス制御 * > * シングルサインオン * ] を選択します。
.. そのノードの SAML メタデータをダウンロードして保存します。


. 「 PingFederate 」に移動します。
. link:../admin/creating-sp-connection-ping.html["StorageGRID 用に 1 つ以上の SP 接続を作成します"]です。各管理ノードのSP接続ID（[Configure SSO]ページの表を参照）と、その管理ノード用にダウンロードしたSAMLメタデータを使用します。
+
次の表に示す管理ノードごとに 1 つの SP 接続を作成する必要があります。



--
====


== [[test-sso]]設定のテスト

StorageGRIDシステム全体でシングルサインオンの使用を適用する前に、各管理ノードに対してシングルサインオンとシングルログアウトが正しく設定されていることを確認してください。

[role="tabbed-block"]
====
.Active Directory
--
.手順
. [Configure SSO]ページで、ウィザードの[Test configuration]ステップのリンクを探します。
+
URL は、 [ * フェデレーションサービス名 * （ * Federation service name * ） ] フィールドに入力した値から取得されます。

. リンクを選択するか、 URL をコピーしてブラウザに貼り付け、アイデンティティプロバイダのサインオンページにアクセスします。
. SSO を使用して StorageGRID にサインインできることを確認するには、 * 次のいずれかのサイトにサインイン * を選択し、プライマリ管理ノードの証明書利用者 ID を選択して * サインイン * を選択します。
. フェデレーテッドユーザのユーザ名とパスワードを入力します。
+
** SSO サインインおよびログアウト処理が成功すると、成功のメッセージが表示されます。
** SSO 処理が失敗すると、エラーメッセージが表示されます。問題 を修正し、ブラウザのクッキーを消去してやり直してください。


. 同じ手順を繰り返して、グリッド内の管理ノードごとに SSO 接続を確認します。


--
.エントラID
--
.手順
. Azure ポータルのシングルサインオンページに移動します。
. [ このアプリケーションをテストする *] を選択します。
. フェデレーテッドユーザのクレデンシャルを入力します。
+
** SSO サインインおよびログアウト処理が成功すると、成功のメッセージが表示されます。
** SSO 処理が失敗すると、エラーメッセージが表示されます。問題 を修正し、ブラウザのクッキーを消去してやり直してください。


. 同じ手順を繰り返して、グリッド内の管理ノードごとに SSO 接続を確認します。


--
.PingFederate
--
.手順
. [Configure SSO]ページで、[Sandbox mode]メッセージの最初のリンクを選択します。
+
一度に 1 つのリンクを選択してテストします。

. フェデレーテッドユーザのクレデンシャルを入力します。
+
** SSO サインインおよびログアウト処理が成功すると、成功のメッセージが表示されます。
** SSO 処理が失敗すると、エラーメッセージが表示されます。問題 を修正し、ブラウザのクッキーを消去してやり直してください。


. 次のリンクを選択して、グリッド内の各管理ノードの SSO 接続を確認します。
+
「ページの有効期限が切れました」というメッセージが表示された場合は、ブラウザで「 * 戻る * 」ボタンを選択し、クレデンシャルを再送信してください。



--
====


== シングルサインオンを有効にします

SSO を使用して各管理ノードにサインインできることを確認したら、 StorageGRID システム全体で SSO を有効にできます。


TIP: SSO が有効になっている場合は、すべてのユーザが SSO を使用して Grid Manager 、テナントマネージャ、グリッド管理 API 、およびテナント管理 API にアクセスする必要があります。ローカルユーザは StorageGRID にアクセスできなくなります。

.手順
. SSOの設定ウィザードのTest configurationステップで、* Enable SSO *を選択します。
. 警告メッセージを確認し、* SSOを有効にする*を選択します。
+
シングルサインオンが有効になりました。[Single Sign-on]ページが表示され、設定したSSOの詳細が表示されます。

. 構成を編集するには、*[編集]*を選択します。
. シングルサインオンを無効にするには、*[SSOの無効化]*を選択します。



TIP: Azureポータルを使用していて、Entra IDへのアクセスに使用するコンピュータからStorageGRIDにアクセスする場合は、Azure portalユーザも承認されたStorageGRIDユーザ（StorageGRIDにインポートされたフェデレーテッドグループのユーザ、またはAzure portalからログアウトしたユーザ）であることを確認してから、StorageGRIDにサインインします。
