---
permalink: admin/configuring-storage-proxy-settings.html 
sidebar: sidebar 
keywords: storage proxy, non-transparent proxy, platform service endpoint 
summary: プラットフォームサービスまたはクラウドストレージプールを使用している場合は、ストレージノードと外部の S3 エンドポイントの間に非透過型プロキシを設定できます。たとえば、インターネット上のエンドポイントなどの外部エンドポイントへプラットフォームサービスメッセージを送信する場合などには、非透過型プロキシが必要です。 
---
= ストレージプロキシの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プラットフォームサービスまたはクラウドストレージプールを使用している場合は、ストレージノードと外部の S3 エンドポイントの間に非透過型プロキシを設定できます。たとえば、インターネット上のエンドポイントなどの外部エンドポイントへプラットフォームサービスメッセージを送信する場合などには、非透過型プロキシが必要です。


NOTE: 設定されているストレージプロキシ設定は、Kafkaプラットフォームサービスエンドポイントには適用されません。

.開始する前に
* そうだな link:admin-group-permissions.html["特定のアクセス権限"]
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。


.タスクの内容
設定できるストレージプロキシは1つです。

.手順
. [ * 設定 * > * セキュリティ * > * プロキシ設定 * ] を選択します。
. [ストレージ]*タブで、*[ストレージプロキシを有効にする]*チェックボックスをオンにします。
. ストレージプロキシのプロトコルを選択します。
. プロキシサーバのホスト名または IP アドレスを入力します。
. 必要に応じて、プロキシサーバへの接続に使用するポートを入力します。
+
プロトコルのデフォルトポート（HTTPの場合は80、SOCKS5の場合は1080）を使用する場合は、このフィールドを空白のままにします。

. [ 保存（ Save ） ] を選択します。
+
ストレージプロキシが保存されたら、プラットフォームサービスまたはクラウドストレージプールの新しいエンドポイントを設定およびテストできます。

+

NOTE: プロキシの変更が有効になるまでに最大 10 分かかることがあります。

. プロキシサーバの設定をチェックして、 StorageGRID からのプラットフォームサービス関連メッセージがブロックされないようにします。
. ストレージプロキシを無効にする必要がある場合は、チェックボックスをオフにして*[保存]*を選択します。

