---
permalink: admin/controlling-storagegrid-access.html 
sidebar: sidebar 
keywords: administrator access, single sign on, sso, users, groups, client certificates, passwords, passphrase 
summary: StorageGRID にアクセスできるユーザ、およびユーザが実行できるタスクを制御するには、グループとユーザを作成またはインポートし、各グループに権限を割り当てます。必要に応じて、シングルサインオン \ （ SSO \ ）を有効にしたり、クライアント証明書を作成したり、グリッドのパスワードを変更したりできます。 
---
= StorageGRID アクセスを制御します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID にアクセスできるユーザ、およびユーザが実行できるタスクを制御するには、グループとユーザを作成またはインポートし、各グループに権限を割り当てます。必要に応じて、シングルサインオン（ SSO ）を有効にしたり、クライアント証明書を作成したり、グリッドのパスワードを変更したりできます。



== Grid Manager へのアクセスを制御

Grid Manager およびグリッド管理 API にアクセスできるユーザを指定するには、アイデンティティフェデレーションサービスからグループとユーザをインポートするか、またはローカルのグループおよびユーザを設定します。

を使用するlink:using-identity-federation.html["アイデンティティフェデレーション"]と、セットアップがlink:managing-admin-groups.html["グループ"] link:managing-users.html["ユーザ"]高速化され、使い慣れたクレデンシャルを使用してStorageGRIDにサインインできます。Active Directory 、 OpenLDAP 、または Oracle Directory Server を使用する場合は、アイデンティティフェデレーションを設定できます。


NOTE: 別の LDAP v3 サービスを使用する場合は、テクニカルサポートにお問い合わせください。

各ユーザが実行できるタスクを指定するには、グループごとに異なるを割り当てlink:admin-group-permissions.html["権限"]ます。たとえば、あるグループのユーザには ILM ルールを管理する権限を、別のグループのユーザにはメンテナンスタスクを実行する権限を与えることができます。システムにアクセスするには、ユーザが少なくとも 1 つのグループに属している必要があります。

必要に応じて、グループを読み取り専用に設定することができます。読み取り専用グループのユーザは、設定と機能のみを表示できます。Grid Managerまたはグリッド管理APIでは、変更を加えたり処理を実行したりすることはできません。



== シングルサインオンを有効にします

StorageGRIDシステムは、Security Assertion Markup Language 2.0 (SAML 2.0) 標準を使用したシングル サインオン (SSO) をサポートしています。お先にどうぞlink:how-sso-works.html["SSOを設定して有効にします"]すべてのユーザーは、グリッド マネージャー、テナント マネージャー、グリッド管理 API、またはテナント管理 API にアクセスする前に、外部 ID プロバイダーによって認証される必要があります。ローカル ユーザーはStorageGRIDにサインインできません。



== プロビジョニングパスフレーズを変更します

プロビジョニング パスフレーズは、多くのインストールおよびメンテナンス手順、およびStorageGRIDリカバリ パッケージのダウンロードに必要です。パスフレーズは、 StorageGRIDシステムのグリッド トポロジ情報と暗号化キーのバックアップをダウンロードする場合にも必要です。あなたはできるlink:changing-provisioning-passphrase.html["パスフレーズを変更します"]必要に応じて。



== ノードのコンソールパスワードを変更します

グリッド内の各ノードにはノード コンソール パスワードがあり、SSH を使用して「admin」としてノードにログインするか、VM/物理コンソール接続で root ユーザーとしてログインする必要があります。必要に応じて、link:change-node-console-password.html["ノードのコンソールパスワードを変更します"]各ノードに対して。
