---
permalink: admin/creating-traffic-classification-policies.html 
sidebar: sidebar 
keywords: traffic classification, network traffic, traffic limits, policy 
summary: バケット、テナント、 IP サブネット、またはロードバランサエンドポイントごとにネットワークトラフィックを監視し、必要に応じて制限する場合は、トラフィック分類ポリシーを作成します。必要に応じて、帯域幅、同時要求数、または要求速度に基づいてポリシーの制限を設定できます。 
---
= トラフィック分類ポリシーを作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バケット、バケット正規表現、CIDR、ロードバランサエンドポイント、またはテナントごとにネットワークトラフィックを監視し、必要に応じて制限する場合は、トラフィック分類ポリシーを作成できます。必要に応じて、帯域幅、同時要求数、または要求速度に基づいてポリシーの制限を設定できます。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたはを持っていますlink:admin-group-permissions.html["rootアクセス権限"]。
* 照合するロードバランサエンドポイントを作成しておきます。
* 該当するテナントを作成しておきます。


.手順
. *構成* > *ネットワーク* > *トラフィック分類*を選択します。
. 「 * Create * 」を選択します。
. ポリシーの名前と概要 （オプション）を入力し、* Continue *を選択します。
+
たとえば、このトラフィック分類ポリシー環境 の内容と制限する内容を説明します。

. ポリシーに一致するルールを1つ以上作成するには、*[ルールの追加]*を選択し、以下の詳細を指定します。作成するポリシーには、一致するルールが少なくとも1つ必要です。「 * Continue * 」を選択します。
+
[cols="1a,3a"]
|===
| フィールド | 製品説明 


 a| 
タイプ
 a| 
一致するルール環境 のトラフィックのタイプを選択します。トラフィックタイプには、バケット、バケットの正規表現、CIDR、ロードバランサエンドポイント、テナントがあります。



 a| 
一致値
 a| 
選択したタイプに一致する値を入力します。

** Bucket：バケット名を1つ以上入力します。
** Bucket regex：バケット名のセットに一致する正規表現を1つ以上入力します。
+
正規表現は固定されていません。^anchorを使用してバケット名の先頭に一致させ、$anchorを使用して名前の末尾に一致させます。正規表現マッチングでは、PCRE（Perl互換正規表現）構文のサブセットがサポートされます。

** CIDR：CIDR表記で、目的のサブネットに一致するIPv4サブネットを1つ以上入力します。
** Load balancer endpoint：エンドポイント名を選択します。これは、で定義したロードバランサエンドポイントですlink:../admin/configuring-load-balancer-endpoints.html["ロードバランサエンドポイントを設定する"]。
** Tenant：一致するテナントはアクセスキーIDを使用します。要求にアクセスキーID（匿名アクセスなど）が含まれていない場合は、テナントを特定するためにアクセスされるバケットの所有権が使用されます。




 a| 
逆一致
 a| 
定義した[Type]および[Match Value]と一致するすべてのネットワークトラフィック_except_trafficを照合する場合は、*[Inverse Match]*チェックボックスをオンにします。それ以外の場合は'チェックボックスをオフのままにします

たとえば、このポリシーをいずれかのロードバランサエンドポイントを除くすべてのロードバランサエンドポイントに適用する場合は、除外するロードバランサエンドポイントを指定し、*[逆一致]*を選択します。

少なくとも 1 つが逆マッチャーである複数のマッチャーを含むポリシーの場合、すべてのリクエストに一致するポリシーを作成しないように注意してください。

|===
. 必要に応じて、*[制限の追加]*を選択し、以下の詳細を選択して1つ以上の制限を追加し、ルールに一致するネットワークトラフィックを制御します。
+

NOTE: StorageGRID では、制限を追加しなくても指標が収集されるため、トラフィックの傾向を把握できます。

+
[cols="1a,3a"]
|===
| フィールド | 製品説明 


 a| 
タイプ
 a| 
ルールに一致するネットワークトラフィックに適用する制限のタイプ。たとえば、帯域幅や要求レートを制限できます。

*注*：ポリシーを作成して、総帯域幅を制限したり、要求ごとの帯域幅を制限したりできます。ただし、StorageGRID では、両方のタイプの帯域幅を同時に制限することはできません。集約帯域幅が使用されている場合、要求ごとの帯域幅は使用できません。逆に、要求ごとの帯域幅が使用されている場合、集約帯域幅は使用できません。総帯域幅を制限すると、制限のないトラフィックのパフォーマンスがさらに若干低下する可能性があります。

帯域幅の制限については、設定された制限のタイプに最も一致するポリシーが StorageGRID によって適用されます。たとえば、トラフィックを一方向のみに制限するポリシーがある場合、帯域幅制限が設定されている他のポリシーと一致するトラフィックがあっても、反対方向のトラフィックは無制限になります。StorageGRID では、帯域幅制限に対して次の順序で「最適な」一致が実装されます。

** 正確な IP アドレス（ /32 マスク）
** 正確なバケット名
** バケットの正規表現
** テナント
** エンドポイント
** 正確でない CIDR の一致（ /32 ではない）
** 逆一致




 a| 
環境
 a| 
これにより、環境 クライアントの読み取り要求（GETまたはHEAD）と書き込み要求（PUT、POST、DELETE）のどちらを制限するか。



 a| 
値
 a| 
選択した単位に基づいて、ネットワークトラフィックが制限される値。たとえば、このルールに一致するネットワークトラフィックが10MiB/sを超えないようにするには、「10」と入力して[MiB/s」を選択します

*注*：単位の設定に応じて、使用可能な単位は2進数（GiBなど）または10進数（GBなど）のいずれかになります。単位の設定を変更するには、Grid Managerの右上にあるユーザードロップダウンを選択し、*ユーザー設定*を選択します。



 a| 
単位
 a| 
入力した値を表す単位。

|===
+
たとえば、SLA 層に 4 GB/秒の帯域幅制限を作成する場合は、4 GB/秒の GET/HEAD と 4 GB/秒の PUT/POST/DELETE の 2 つの集約帯域幅制限を作成します。

. 「 * Continue * 」を選択します。
. トラフィック分類ポリシーを読んで確認します。前へ*ボタンを使用して前に戻り、必要に応じて変更を行います。ポリシーに問題がなければ、*[保存して続行]*を選択します。
+
S3クライアントトラフィックがトラフィック分類ポリシーに従って処理されるようになりました。



.終了後
link:viewing-network-traffic-metrics.html["ネットワークトラフィックの指標を表示します"]ポリシーが想定どおりのトラフィック制限を適用していることを確認します。
