---
permalink: admin/creating-enterprise-application-entra-id.html 
sidebar: sidebar 
keywords: enterprise application, entra id, single sign on, sso 
summary: Entra IDは、システム内の管理ノードごとにエンタープライズアプリケーションを作成する場合に使用します。 
---
= Entra IDでのエンタープライズアプリケーションの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Entra IDは、システム内の管理ノードごとにエンタープライズアプリケーションを作成する場合に使用します。

.開始する前に
* StorageGRIDのシングルサインオンの設定を開始し、SSOタイプとして*エントラID *を選択しました。
* Grid Managerにありますlink:../admin/configure-sso.html#enter-sandbox-mode["サンドボックスモードに入りました"]。
* システム内の管理ノードごとに * Enterprise アプリケーション名 * を用意しておきます。これらの値は、[Configure SSO]ページの[Admin Node details]テーブルからコピーできます。
+

NOTE: StorageGRID システムで管理ノードごとにエンタープライズアプリケーションを作成する必要があります。管理ノードごとにエンタープライズアプリケーションを用意することで、ユーザはどの管理ノードに対しても安全にサインイン / サインアウトすることができます。

* Entra IDでエンタープライズアプリケーションを作成した経験があります。
* アクティブなサブスクリプションを持つ Azure アカウントが必要です。
* Entra IDアカウントには、グローバル管理者、クラウドアプリケーション管理者、アプリケーション管理者、またはサービスプリンシパルの所有者のいずれかのロールが割り当てられている必要があります。




== アクセスエントラID

.手順
. にログインし https://portal.azure.com["Azure ポータル"^]ます。
. に移動します https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade["エントラID"^]。
. を選択します https://portal.azure.com/#blade/Microsoft_AAD_IAM/StartboardApplicationsMenuBlade/Overview/menuId/["エンタープライズアプリケーション"^]。




== エンタープライズアプリケーションを作成し、 StorageGRID SSO 設定を保存します

StorageGRIDでエントラIDのSSO設定を保存するには、エントラIDを使用して各管理ノード用のエンタープライズアプリケーションを作成する必要があります。エントラIDからフェデレーションメタデータURLをコピーし、SSOの設定ページの対応する*フェデレーションメタデータURL *フィールドに貼り付けます。

.手順
. 管理ノードごとに次の手順を繰り返します。
+
.. Entra ID Enterpriseアプリケーションペインで、*新規アプリケーション*を選択します。
.. 「 * 独自のアプリケーションを作成する * 」を選択します。
.. [Configure SSO]ページの管理ノードの詳細テーブルからコピーした*エンタープライズアプリケーション名*を入力します。
.. ギャラリー ( ギャラリー以外 ) で見つからない他のアプリケーションを統合 * ラジオボタンを選択したままにします。
.. 「 * Create * 」を選択します。
.. 2 の * Get started * リンクを選択します。シングルサインオン * ボックスを設定するか、左マージンの * シングルサインオン * リンクを選択します。
.. [* SAML * ] ボックスを選択します。
.. 「 * アプリフェデレーションメタデータ URL * 」をコピーします。この URL は「 * ステップ 3 SAML 署名証明書 * 」にあります。
.. SSOの設定ページに移動し、使用した*エンタープライズアプリケーション名*に対応する*フェデレーションメタデータURL *フィールドにURLを貼り付けます。


. 各管理ノードにフェデレーションメタデータURLを貼り付け、SSO設定に必要なその他の変更をすべて加えたら、[Configure SSO]ページで*[Save]*を選択します。




== 管理ノードごとに SAML メタデータをダウンロードします

SSO 設定を保存したら、 StorageGRID システム内の管理ノードごとに SAML メタデータファイルをダウンロードできます。

.手順
. 管理ノードごとに上記の手順を繰り返します。
+
.. 管理ノードから StorageGRID にサインインします。
.. [ * 設定 * > * アクセス制御 * > * シングルサインオン * ] を選択します。
.. ボタンを選択して、その管理ノードの SAML メタデータをダウンロードします。
.. Entra IDにアップロードするファイルを保存します。






== SAML メタデータを各エンタープライズアプリケーションにアップロードする

StorageGRID管理ノードごとにSAMLメタデータファイルをダウンロードしたら、[Entra ID]で次の手順を実行します。

.手順
. Azure ポータルに戻ります。
. エンタープライズアプリケーションごとに、次の手順を繰り返します。
+

NOTE: 以前にリストに追加したアプリケーションを表示するには、 [ エンタープライズアプリケーション ] ページの更新が必要な場合があります。

+
.. エンタープライズアプリケーションのプロパティページに移動します。
.. [Assignment Required*] を [*No*] に設定します（個別に割り当てを設定する場合を除く）。
.. シングルサインオンページに移動します。
.. SAML の設定を完了します。
.. メタデータファイルのアップロードボタンを選択し、対応する管理ノード用にダウンロードした SAML メタデータファイルを選択します。
.. ファイルがロードされたら、「 * 保存」を選択し、「 * X * 」を選択してパネルを閉じます。SAML を使用してシングルサインオンを設定するページに戻ります。


. link:../admin/configure-sso.html#test-sso["各アプリケーションをテストする"]です。

