---
permalink: admin/creating-enterprise-application-entra-id.html 
sidebar: sidebar 
keywords: enterprise application, entra id, single sign on, sso 
summary: Entra ID を使用して、システム内の各管理ノードに対してエンタープライズ アプリケーションを作成します。 
---
= Entra IDでエンタープライズアプリケーションを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Entra ID を使用して、システム内の各管理ノードに対してエンタープライズ アプリケーションを作成します。

.開始する前に
* StorageGRIDのシングル サインオンの構成を開始し、SSO タイプとして *Entra ID* を選択しました。
* あなたが持っているlink:../admin/configure-sso.html#enter-sandbox-mode["サンドボックスモードに入りました"]グリッド マネージャーで。
* システム内の各管理ノードには *エンタープライズ アプリケーション名* があります。これらの値は、「SSO の構成」ページの管理ノードの詳細テーブルからコピーできます。
+

NOTE: StorageGRID システムで管理ノードごとにエンタープライズアプリケーションを作成する必要があります。管理ノードごとにエンタープライズアプリケーションを用意することで、ユーザはどの管理ノードに対しても安全にサインイン / サインアウトすることができます。

* Entra ID でエンタープライズ アプリケーションを作成した経験があります。
* 有効なサブスクリプションを持つ Entra ID アカウントをお持ちです。
* Entra ID アカウントには、グローバル管理者、クラウド アプリケーション管理者、アプリケーション管理者、またはサービス プリンシパルの所有者のいずれかのロールがあります。




== アクセスエントラID

.手順
. にログインし https://portal.azure.com["Azure ポータル"^]ます。
. 移動先 https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade["エントラID"^]。
. を選択します https://portal.azure.com/#blade/Microsoft_AAD_IAM/StartboardApplicationsMenuBlade/Overview/menuId/["エンタープライズアプリケーション"^]。




== エンタープライズアプリケーションを作成し、 StorageGRID SSO 設定を保存します

Entra ID の SSO 構成をStorageGRIDに保存するには、Entra ID を使用して各管理ノードのエンタープライズ アプリケーションを作成する必要があります。  Entra ID からフェデレーション メタデータ URL をコピーし、[SSO の構成] ページの対応する *フェデレーション メタデータ URL* フィールドに貼り付けます。

.手順
. 管理ノードごとに次の手順を繰り返します。
+
.. Entra ID Enterprise アプリケーション ペインで、*新しいアプリケーション* を選択します。
.. 「 * 独自のアプリケーションを作成する * 」を選択します。
.. 名前には、[SSO の構成] ページの管理ノードの詳細テーブルからコピーした *エンタープライズ アプリケーション名* を入力します。
.. ギャラリー ( ギャラリー以外 ) で見つからない他のアプリケーションを統合 * ラジオボタンを選択したままにします。
.. 「 * Create * 」を選択します。
.. 2 の * Get started * リンクを選択します。シングルサインオン * ボックスを設定するか、左マージンの * シングルサインオン * リンクを選択します。
.. [* SAML * ] ボックスを選択します。
.. 「 * アプリフェデレーションメタデータ URL * 」をコピーします。この URL は「 * ステップ 3 SAML 署名証明書 * 」にあります。
.. [SSO の構成] ページに移動し、使用した *エンタープライズ アプリケーション名* に対応する *フェデレーション メタデータ URL* フィールドに URL を貼り付けます。


. 各管理ノードのフェデレーション メタデータ URL を貼り付け、SSO 構成に必要なその他の変更をすべて行った後、[SSO の構成] ページで [*保存*] を選択します。




== 管理ノードごとに SAML メタデータをダウンロードします

SSO 設定を保存したら、 StorageGRID システム内の管理ノードごとに SAML メタデータファイルをダウンロードできます。

.手順
. 管理ノードごとに上記の手順を繰り返します。
+
.. 管理ノードから StorageGRID にサインインします。
.. *構成* > *アクセス制御* > *シングル サインオン* を選択します。
.. ボタンを選択して、その管理ノードの SAML メタデータをダウンロードします。
.. Entra ID にアップロードするファイルを保存します。






== SAML メタデータを各エンタープライズアプリケーションにアップロードする

各StorageGRID管理ノードの SAML メタデータ ファイルをダウンロードした後、Entra ID で次の手順を実行します。

.手順
. Azure ポータルに戻ります。
. エンタープライズアプリケーションごとに、次の手順を繰り返します。
+

NOTE: 以前にリストに追加したアプリケーションを表示するには、 [ エンタープライズアプリケーション ] ページの更新が必要な場合があります。

+
.. エンタープライズアプリケーションのプロパティページに移動します。
.. [Assignment Required*] を [*No*] に設定します（個別に割り当てを設定する場合を除く）。
.. シングルサインオンページに移動します。
.. SAML の設定を完了します。
.. メタデータファイルのアップロードボタンを選択し、対応する管理ノード用にダウンロードした SAML メタデータファイルを選択します。
.. ファイルがロードされたら、「 * 保存」を選択し、「 * X * 」を選択してパネルを閉じます。SAML を使用してシングルサインオンを設定するページに戻ります。


. link:../admin/configure-sso.html#test-sso["各アプリケーションをテストする"] 。

