---
permalink: admin/creating-enterprise-application-azure.html 
sidebar: sidebar 
keywords: enterprise application, azure ad, single sign on, sso 
summary: Azure AD を使用して、システム内の管理ノードごとにエンタープライズアプリケーションを作成します。 
---
= Azure AD でエンタープライズアプリケーションを作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Azure AD を使用して、システム内の管理ノードごとにエンタープライズアプリケーションを作成します。

.開始する前に
* StorageGRID 用のシングルサインオンの設定を開始し、 SSO タイプとして「 * Azure* 」を選択しました。
* * Grid Manager のシングルサインオンページでサンドボックスモード * が選択されています。を参照して link:../admin/using-sandbox-mode.html["サンドボックスモードを使用する"]
* システム内の管理ノードごとに * Enterprise アプリケーション名 * を用意しておきます。これらの値は、 StorageGRID のシングルサインオンページの管理ノードの詳細テーブルからコピーできます。
+

NOTE: StorageGRID システムで管理ノードごとにエンタープライズアプリケーションを作成する必要があります。管理ノードごとにエンタープライズアプリケーションを用意することで、ユーザはどの管理ノードに対しても安全にサインイン / サインアウトすることができます。

* Azure Active Directory でエンタープライズアプリケーションを作成した経験がある。
* アクティブなサブスクリプションを持つ Azure アカウントが必要です。
* Azure アカウントに、グローバル管理者、クラウドアプリケーション管理者、アプリケーション管理者、サービスプリンシパルの所有者のいずれかのロールが割り当てられている。




== Azure AD にアクセスします

.手順
. にログインし https://portal.azure.com["Azure ポータル"^]ます。
. に移動します https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade["Azure Active Directory の略"^]。
. を選択します https://portal.azure.com/#blade/Microsoft_AAD_IAM/StartboardApplicationsMenuBlade/Overview/menuId/["エンタープライズアプリケーション"^]。




== エンタープライズアプリケーションを作成し、 StorageGRID SSO 設定を保存します

AzureのSSO設定をStorageGRID に保存するには、Azureを使用して管理ノードごとにエンタープライズアプリケーションを作成する必要があります。フェデレーションメタデータの URL を Azure からコピーし、 StorageGRID のシングルサインオンページの対応する * フェデレーションメタデータの URL * フィールドに貼り付けます。

.手順
. 管理ノードごとに次の手順を繰り返します。
+
.. Azure Enterprise アプリケーションペインで、 * 新規アプリケーション * を選択します。
.. 「 * 独自のアプリケーションを作成する * 」を選択します。
.. 名前には、 StorageGRID のシングルサインオンページの管理ノード詳細テーブルからコピーした * エンタープライズアプリケーション名 * を入力します。
.. ギャラリー ( ギャラリー以外 ) で見つからない他のアプリケーションを統合 * ラジオボタンを選択したままにします。
.. 「 * Create * 」を選択します。
.. 2 の * Get started * リンクを選択します。シングルサインオン * ボックスを設定するか、左マージンの * シングルサインオン * リンクを選択します。
.. [* SAML * ] ボックスを選択します。
.. 「 * アプリフェデレーションメタデータ URL * 」をコピーします。この URL は「 * ステップ 3 SAML 署名証明書 * 」にあります。
.. StorageGRID シングルサインオンページに移動し、使用した * エンタープライズアプリケーション名 * に対応する * フェデレーションメタデータ URL* フィールドに URL を貼り付けます。


. 各管理ノードのフェデレーションメタデータ URL を貼り付け、 SSO 設定に必要なその他の変更をすべて行ったら、 StorageGRID のシングルサインオンページで「 * 保存」を選択します。




== 管理ノードごとに SAML メタデータをダウンロードします

SSO 設定を保存したら、 StorageGRID システム内の管理ノードごとに SAML メタデータファイルをダウンロードできます。

.手順
. 管理ノードごとに上記の手順を繰り返します。
+
.. 管理ノードから StorageGRID にサインインします。
.. [ * 設定 * > * アクセス制御 * > * シングルサインオン * ] を選択します。
.. ボタンを選択して、その管理ノードの SAML メタデータをダウンロードします。
.. Azure AD にアップロードするファイルを保存します。






== SAML メタデータを各エンタープライズアプリケーションにアップロードする

StorageGRID 管理ノードごとに SAML メタデータファイルをダウンロードしたら、 Azure AD で次の手順を実行します。

.手順
. Azure ポータルに戻ります。
. エンタープライズアプリケーションごとに、次の手順を繰り返します。
+

NOTE: 以前にリストに追加したアプリケーションを表示するには、 [ エンタープライズアプリケーション ] ページの更新が必要な場合があります。

+
.. エンタープライズアプリケーションのプロパティページに移動します。
.. [Assignment Required*] を [*No*] に設定します（個別に割り当てを設定する場合を除く）。
.. シングルサインオンページに移動します。
.. SAML の設定を完了します。
.. メタデータファイルのアップロードボタンを選択し、対応する管理ノード用にダウンロードした SAML メタデータファイルを選択します。
.. ファイルがロードされたら、「 * 保存」を選択し、「 * X * 」を選択してパネルを閉じます。SAML を使用してシングルサインオンを設定するページに戻ります。


. 各アプリケーションをテストするには、の手順に従いlink:../admin/using-sandbox-mode.html["サンドボックスモードを使用する"]ます。

