---
permalink: admin/deactivate-features-from-api.html 
sidebar: sidebar 
keywords: deactivate features from api 
summary: グリッド管理 API を使用すると、 StorageGRID システムの特定の機能を完全に非アクティブ化できます。機能を非アクティブ化すると、その機能に関連するタスクを実行する権限をユーザに割り当てることができなくなります。 
---
= API で機能を非アクティブ化します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッド管理 API を使用すると、 StorageGRID システムの特定の機能を完全に非アクティブ化できます。機能を非アクティブ化すると、その機能に関連するタスクを実行する権限をユーザに割り当てることができなくなります。

.タスクの内容
非活動化されたフィーチャーシステムを使用すると、 StorageGRID システムの特定のフィーチャーへのアクセスを禁止できます。機能の非アクティブ化は、 root ユーザまたは * Root Access * 権限を持つ管理者グループに属するユーザがその機能を使用できないようにする唯一の方法です。

この機能がどのように役立つかを理解するために、次のシナリオを検討してください。

_Company A は、テナントアカウントを作成して StorageGRID システムのストレージ容量をリースするサービスプロバイダです。容量をリースしている顧客のオブジェクトのセキュリティを保護するために、 A 社では、アカウントの導入後に自社の従業員がテナントアカウントにアクセスできないようにしたいと考えています。 _

_ 企業 A は、グリッド管理 API で Deactivate Features システムを使用することで、この目的を達成できます。Grid Manager（UIとAPIの両方）で「Change tenant root password」機能を完全に非アクティブ化することで、A社の管理者ユーザ（rootユーザおよび* Root access *権限を持つグループに属するユーザを含む）がテナントアカウントのrootユーザのパスワードを変更できないようにします。_

.手順
. Swagger のグリッド管理 API のドキュメントにアクセスします。を参照して link:using-grid-management-api.html["グリッド管理 API を使用します"]
. Deactivate Features エンドポイントを探します。
. テナントの root パスワードの変更などの機能を非アクティブ化するには、次のような本文を API に送信します。
+
`{ "grid": {"changeTenantRootPassword": true} }`

+
要求が完了すると、テナントの root パスワードの変更機能が無効になります。Change tenant root password *管理権限はユーザインターフェイスに表示されなくなり、テナントのrootパスワードを変更しようとするAPI要求は「403 Forbidden」で失敗します。





== 非アクティブ化した機能を再アクティブ

デフォルトでは、グリッド管理 API を使用して、非アクティブ化した機能を再アクティブ化できます。ただし、非アクティブ化された機能が再アクティブ化されないようにするには、 * activateFeatures * 機能自体を非アクティブ化します。


CAUTION: *activateFeatures*機能を再度有効にすることはできません。この機能を非アクティブ化すると、非アクティブ化した他の機能を永続的に再アクティブ化できなくなることに注意してください。失われた機能をリストアするには、テクニカルサポートにお問い合わせください。

.手順
. Swagger のグリッド管理 API のドキュメントにアクセスします。
. Deactivate Features エンドポイントを探します。
. すべての機能を再アクティブ化するには、次のような本文を API に送信します。
+
`{ "grid": null }`

+
この要求が完了すると、テナントの root パスワード変更機能を含むすべての機能が再アクティブ化されます。ユーザに * Root access * 権限または * Change tenant root password * 管理権限が割り当てられている場合、テナントの root パスワードを変更する API 要求はすべてユーザインターフェイスに表示され、テナントの root パスワードを変更する API 要求は成功します。




TIP: 前述の例は、 _all_deactivated 機能を再アクティブ化します。非アクティブ化したままにする必要がある他の機能が非アクティブ化されている場合は、 PUT 要求でそれらを明示的に指定する必要があります。たとえば、Change tenant root password機能を再アクティブ化し、引き続きstorageadmin管理権限を非アクティブ化するには、次のPUT要求を送信します。+
`{ "grid": {"storageAdmin": true} }`
