---
permalink: admin/grid-federation-compare-cgr-to-cloudmirror.html 
sidebar: sidebar 
keywords: cross-grid replication, cloudmirror replication 
summary: グリッドフェデレーションの使用を開始したら、グリッド間レプリケーションとStorageGRID CloudMirrorレプリケーションサービスの類似点と相違点を確認してください。 
---
= グリッド間レプリケーションとCloudMirrorレプリケーションを比較してください
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッドフェデレーションの使用を開始する際に、との類似点と相違点を確認してlink:grid-federation-what-is-cross-grid-replication.html["グリッド間レプリケーション"]link:../tenant/understanding-cloudmirror-replication-service.html["StorageGRID CloudMirror レプリケーションサービス"]ください。

[cols="1a,3a,3a"]
|===
|  | グリッド間レプリケーション | CloudMirror レプリケーションサービス 


 a| 
主な目的は何ですか？
 a| 
1つのStorageGRID システムがディザスタリカバリシステムとして機能します。バケット内のオブジェクトは、グリッド間で一方向または両方向にレプリケートできます。
 a| 
テナントで、StorageGRID （ソース）内のバケットから外部のS3バケット（デスティネーション）にオブジェクトを自動的にレプリケートできます。

CloudMirror レプリケーションでは、独立した S3 インフラにオブジェクトの独立したコピーが作成されます。この独立したコピーはバックアップとしては使用されませんが、多くの場合、クラウドでさらに処理されます。



 a| 
セットアップ方法は？
 a| 
. 2つのグリッド間のグリッドフェデレーション接続を設定します。
. 新しいテナントアカウントを追加します。このアカウントは自動的にもう一方のグリッドにクローニングされます。
. 新しいテナントグループとユーザを追加します。これらもクローンとして作成されます。
. 各グリッドに対応するバケットを作成し、一方向または両方向でグリッド間レプリケーションを実行できるようにします。

 a| 
. テナントユーザは、Tenant ManagerまたはS3 APIを使用してCloudMirrorエンドポイント（IPアドレス、クレデンシャルなど）を定義することによってCloudMirrorレプリケーションを設定します。
. そのテナントアカウントが所有するバケットは、CloudMirrorエンドポイントを指すように設定できます。




 a| 
設定は誰が担当しますか？
 a| 
* グリッド管理者が接続とテナントを設定します。
* テナントユーザは、グループ、ユーザ、キー、およびバケットを設定します。

 a| 
通常はテナントユーザです。



 a| 
デスティネーションは何ですか？
 a| 
グリッドフェデレーション接続内のもう一方のStorageGRID システム上の、対応する同一のS3バケット。
 a| 
* 互換性のある任意のS3インフラ（Amazon S3を含む）。
* Google Cloud Platform（GCP）




 a| 
オブジェクトのバージョン管理は必要ですか。
 a| 
はい。ソースバケットとデスティネーションバケットの両方でオブジェクトのバージョン管理を有効にする必要があります。
 a| 
いいえ。CloudMirrorレプリケーションでは、ソースとデスティネーションの両方で、バージョン管理に対応していないバケットとバージョン管理に対応していないバケットを任意に組み合わせて使用できます。



 a| 
オブジェクトをデスティネーションに移動する原因は何ですか？
 a| 
オブジェクトは、グリッド間レプリケーションが有効になっているバケットに追加されると自動的にレプリケートされます。
 a| 
CloudMirrorエンドポイントが設定されたバケットにオブジェクトが追加されると、オブジェクトが自動的にレプリケートされます。CloudMirrorエンドポイントを設定する前にソースバケットに存在していたオブジェクトは、変更しないかぎりレプリケートされません。



 a| 
オブジェクトのレプリケート方法
 a| 
グリッド間レプリケーションでバージョン管理オブジェクトが作成され、バージョンIDがソースバケットからデスティネーションバケットにレプリケートされます。これにより、両方のグリッドでバージョンの順序を維持できます。
 a| 
CloudMirrorレプリケーションではバージョン管理が有効なバケットは必要ないため、CloudMirrorではサイト内のキーの順序のみを維持できます。別のサイトにあるオブジェクトへの要求の順序が維持される保証はありません。



 a| 
オブジェクトをレプリケートできない場合はどうなりますか。
 a| 
オブジェクトは、メタデータストレージの制限に従ってレプリケーションのキューに登録されます。
 a| 
オブジェクトは、プラットフォームサービスの制限に従ってレプリケーションのキューに登録されます（を参照link:manage-platform-services-for-tenants.html["プラットフォームサービスの使用に関する推奨事項"]）。



 a| 
オブジェクトのシステムメタデータはレプリケートされているか？
 a| 
はい。オブジェクトが他のグリッドにレプリケートされると、そのシステムメタデータもレプリケートされます。メタデータは両方のグリッドで同一になります。
 a| 
いいえ。オブジェクトが外部バケットにレプリケートされると、そのシステムメタデータが更新されます。メタデータは場所によって異なり、取り込み時間や独立したS3インフラの動作によって異なります。



 a| 
オブジェクトの読み出し方法
 a| 
アプリケーションは、いずれかのグリッドのバケットに要求することで、オブジェクトを読み出すことができます。
 a| 
アプリケーションは、StorageGRID またはS3デスティネーションに要求を行うことで、オブジェクトの読み出しや読み取りを行うことができます。たとえば、 CloudMirror レプリケーションを使用してパートナー組織にオブジェクトをミラーリングするとします。パートナーは、独自のアプリケーションを使用して、 S3 デスティネーションからオブジェクトを直接読み取ったり更新したりできます。StorageGRID を使用する必要はありません。



 a| 
オブジェクトが削除された場合の動作
 a| 
* バージョンIDを含む削除要求は、デスティネーショングリッドにレプリケートされません。
* バージョンIDが含まれていない削除要求では、ソースバケットに削除マーカーが追加され、必要に応じてデスティネーショングリッドにレプリケートできます。
* グリッド間レプリケーションが一方向のみに設定されている場合は、ソースに影響を与えずにデスティネーションバケット内のオブジェクトを削除できます。

 a| 
結果は、ソースバケットとデスティネーションバケットのバージョン管理状態によって異なります（同じである必要はありません）。

* 両方のバケットがバージョン管理に対応している場合は、削除要求によって両方の場所に削除マーカーが追加されます。
* ソースバケットのみがバージョン管理に対応している場合、削除要求ではソースに削除マーカーが追加されますが、デスティネーションには追加されません。
* どちらのバケットもバージョン管理に対応していない場合、削除要求によってソースからはオブジェクトが削除されますが、デスティネーションからは削除されません。


同様に、デスティネーションバケット内のオブジェクトもソースに影響を与えることなく削除できます。

|===