---
permalink: admin/how-ha-groups-are-used.html 
sidebar: sidebar 
keywords: ha groups, high availability group 
summary: ハイアベイラビリティ（ HA ）グループを使用すると、オブジェクトデータ用および管理用に StorageGRID への可用性の高い接続を提供できます。 
---
= HA グループの用途
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ハイアベイラビリティ（ HA ）グループを使用すると、オブジェクトデータ用および管理用に StorageGRID への可用性の高い接続を提供できます。

* HA グループは、 Grid Manager または Tenant Manager への可用性の高い管理接続を提供します。
* HAグループは、S3クライアントに可用性の高いデータ接続を提供できます。
* インターフェイスが 1 つしかない HA グループでは、多数の VIP アドレスを指定したり、 IPv6 アドレスを明示的に設定したりできます。


HA グループは、グループに含まれるすべてのノードが同じサービスを提供する場合にのみ高可用性を提供できます。HA グループを作成するときは、必要なサービスを提供するタイプのノードからインターフェイスを追加してください。

* * 管理ノード * ：ロードバランササービスが含まれ、 Grid Manager またはテナントマネージャへのアクセスを有効にします。
* *ゲートウェイノード*：ロードバランササービスが含まれます。


[cols="1a,2a"]
|===
| HA グループの目的 | このタイプのノードを HA グループに追加します 


 a| 
Grid Manager へのアクセス
 a| 
* プライマリ管理ノード（ * プライマリ * ）
* 非プライマリ管理ノード


* 注： * プライマリ管理ノードがプライマリインターフェイスである必要があります。一部のメンテナンス手順は、プライマリ管理ノードでしか実行できません。



 a| 
Tenant Manager のみにアクセスします
 a| 
* プライマリ管理ノードまたは非プライマリ管理ノード




 a| 
S3クライアントアクセス--ロードバランササービス
 a| 
* 管理ノード
* ゲートウェイノード




 a| 
S3クライアントアクセスlink:../admin/manage-s3-select-for-tenant-accounts.html["S3 選択"]
 a| 
* サービスアプライアンス
* VMware ベースのソフトウェアノード


* 注： S3 Select を使用する場合は HA グループを推奨しますが、必須ではありません。

|===


== Grid Manager または Tenant Manager で HA グループを使用する場合の制限事項

Grid Manager サービスまたは Tenant Manager サービスに障害が発生した場合は、 HA グループのフェイルオーバーはトリガーされません。

フェイルオーバーの発生時に Grid Manager または Tenant Manager にサインインしている場合はサインアウトされるため、再度サインインしてタスクを再開する必要があります。

プライマリ管理ノードを使用できないと、一部のメンテナンス手順を実行できません。フェイルオーバー中は、 Grid Manager を使用して StorageGRID システムを監視できます。
