---
permalink: admin/kms-managing.html 
sidebar: sidebar 
keywords: manage kms, manage key management server, view kms, view key management server, edit kms, edit key management server, view encrypted nodes, remove kms, remove key management server 
summary: キー管理サーバ（KMS\）の管理には、詳細の表示と編集、証明書の管理、暗号化されたノードの表示、不要になったKMSの削除が含まれます。 
---
= KMSの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
キー管理サーバ（KMS）の管理には、詳細の表示と編集、証明書の管理、暗号化されたノードの表示、不要になったKMSの削除が含まれます。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたはを持っていますlink:admin-group-permissions.html["必要なアクセス権限"]。




== KMS の詳細を確認します

キーの詳細、サーバ証明書とクライアント証明書の現在のステータスなど、StorageGRIDシステム内の各キー管理サーバ（KMS）に関する情報を表示できます。

.手順
. 設定 * > * セキュリティ * > * キー管理サーバ * を選択します。
+
[Key management server]ページに次の情報が表示されます。

+
** [Configuration details]タブには、設定済みのキー管理サーバが表示されます。
** [Encrypted nodes]タブには、ノード暗号化が有効になっているノードが表示されます。


. 特定のKMSの詳細を表示し、そのKMSに対して操作を実行するには、KMSの名前を選択します。KMSの詳細ページには、次の情報が表示されます。
+
[cols="1a,3a"]
|===
| フィールド | 製品説明 


 a| 
のキーを管理します
 a| 
KMS に関連付けられている StorageGRID サイト。

このフィールドには、特定の StorageGRID サイトの名前、または別の KMS （デフォルト KMS ）で管理されていないサイト * が表示されます



 a| 
ホスト名
 a| 
KMS の完全修飾ドメイン名または IP アドレス。

2 台のキー管理サーバからなるクラスタがある場合は、両方のサーバの完全修飾ドメイン名または IP アドレスが表示されます。クラスタに複数のキー管理サーバがある場合は、最初の KMS の完全修飾ドメイン名または IP アドレスと、クラスタ内の追加のキー管理サーバの数が表示されます。

例 `10.10.10.10 and 10.10.10.11`：または `10.10.10.10 and 2 others`。

クラスタ内のすべてのホスト名を表示するには、KMSを選択して*[編集]*または*[アクション]*>*[編集]*を選択します。

|===
. KMSの詳細ページでタブを選択すると、次の情報が表示されます。
+
[cols="1a,1a,3a"]
|===
| タブ | フィールド | 製品説明 


 a| 
主な詳細
 a| 
キー名
 a| 
KMS 内の StorageGRID クライアントのキーエイリアス。



 a| 
キー UID
 a| 
キーの最新バージョンの一意の識別子。



 a| 
最終更新日
 a| 
キーの最新バージョンの日付と時刻。



 a| 
サーバ証明書
 a| 
メタデータ
 a| 
証明書のメタデータ（シリアル番号、有効期限の日時、証明書PEMなど）。



 a| 
証明書PEM
 a| 
証明書のPEM（Privacy Enhanced Mail）ファイルの内容。



 a| 
クライアント証明書
 a| 
メタデータ
 a| 
証明書のメタデータ（シリアル番号、有効期限の日時、証明書PEMなど）。



 a| 
証明書PEM
 a| 
証明書のPEM（Privacy Enhanced Mail）ファイルの内容。

|===
. [[Rotate-key]]組織のセキュリティ対策で必要に応じて、*[Rotate key]*を選択するか、KMSソフトウェアを使用してキーの新しいバージョンを作成します。
+
キーのローテーションが成功すると、[Key UID]フィールドと[Last modified]フィールドが更新されます。

+
[CAUTION]
====
KMSソフトウェアを使用して暗号化キーをローテーションする場合は、最後に使用したバージョンのキーから新しいバージョンの同じキーにローテーションします。完全に別のキーに回転しないでください。

KMS のキー名 ( エイリアス ) を変更して、キーの回転を試みないでください。StorageGRID では、以前に使用されていたすべてのキーバージョン（および今後使用するすべてのバージョン）に、同じキーエイリアスを使用して KMS からアクセスできることが必要です。設定されている KMS のキーエイリアスを変更すると、 StorageGRID がデータを復号化できなくなる可能性があります。

====




== 証明書の管理

サーバ証明書またはクライアント証明書の問題に迅速に対処します。可能であれば、有効期限が切れる前に証明書を交換してください。


CAUTION: データアクセスを維持するために、証明書の問題はできるだけ早く対処する必要があります。

.手順
. 設定 * > * セキュリティ * > * キー管理サーバ * を選択します。
. 表で、KMSごとの証明書有効期限の値を確認します。
. 任意のKMSの証明書の有効期限が不明な場合は、30分ほど待ってからWebブラウザを更新してください。
. [証明書の有効期限]列に証明書の有効期限が切れているか有効期限に近づいていることが示されている場合は、KMSを選択してKMSの詳細ページに移動します。
+
.. [サーバ証明書]*を選択し、[有効期限]フィールドの値を確認します。
.. 証明書を置き換えるには、*[証明書の編集]*を選択して新しい証明書をアップロードします。
.. これらのサブステップを繰り返し、サーバー証明書ではなく*クライアント証明書*を選択します。


. 「* kms CA certificate expiration *」、「* kms client certificate expiration *」、「* kms server certificate expiration *」の各アラートがトリガーされたら、各アラートの概要 をメモして推奨される対処方法を実行します。
+
証明書の有効期限の更新がStorageGRIDで取得されるまでに30分ほどかかることがあります。現在の値を確認するには、Webブラウザをリフレッシュしてください。




NOTE: 「* Server certificate status is unknown *」というステータスが表示される場合は、クライアント証明書を必要とせずに、KMSでサーバ証明書の取得が許可されていることを確認してください。



== 暗号化されたノードを表示する

StorageGRID システムでノード暗号化 * 設定が有効になっているアプライアンスノードに関する情報を表示できます。

.手順
. 設定 * > * セキュリティ * > * キー管理サーバ * を選択します。
+
[Key Management Server] ページが表示されます。Configuration Details タブには、設定済みのすべてのキー管理サーバが表示されます。

. ページの上部で、*[暗号化されたノード]*タブを選択します。
+
[Encrypted nodes]タブには、*[Node Encryption]*設定が有効になっているStorageGRID システム内のアプライアンスノードが表示されます。

. 各アプライアンスノードについて、表の情報を確認します。
+
[cols="1a,3a"]
|===
| 列 | 製品説明 


 a| 
ノード名
 a| 
アプライアンスノードの名前。



 a| 
ノードタイプ
 a| 
ノードのタイプ。 Storage 、 Admin 、または Gateway 。



 a| 
サイト
 a| 
ノードがインストールされている StorageGRID サイトの名前。



 a| 
KMS名
 a| 
ノードに使用される KMS の説明的な名前。

KMSがリストされていない場合は、[Configuration details]タブを選択してKMSを追加します。

link:kms-adding.html["キー管理サーバ（ KMS ）を追加する"]



 a| 
キー UID
 a| 
アプライアンスノードでデータの暗号化と復号化に使用する暗号化キーの一意の ID 。キーUID全体を表示するには、テキストを選択します。

ダッシュ（ - - ）は、キー UID が不明であることを示します。アプライアンスノードと KMS 間の接続問題 が原因である可能性があります。



 a| 
ステータス
 a| 
KMS とアプライアンスノード間の接続のステータス。ノードが接続されている場合は、タイムスタンプが 30 分ごとに更新されます。KMS の設定変更後に接続ステータスが更新されるまで数分かかることがあります。

*注：*新しい値を表示するには、Webブラウザを更新してください。

|===
. ステータス列に KMS 問題 と表示されている場合は、問題 にすぐに対処してください。
+
通常の KMS 操作中、ステータスは * KMS * に接続されます。ノードがグリッドから切断されると、ノードの接続状態が（意図的に停止しているか不明である）と表示されます。

+
その他のステータスメッセージは、同じ名前の StorageGRID アラートに対応します。

+
** KMS の設定をロードできませんでした
** KMS 接続エラー
** KMS 暗号化キー名が見つかりません
** KMS 暗号化キーのローテーションに失敗しました
** KMS キーでアプライアンスボリュームを復号化できませんでした
** KMS は設定されていません


+
これらのアラートに対して推奨される対処方法を実行します。




CAUTION: 問題が発生した場合は、データを完全に保護するために、すぐに対処する必要があります。



== KMSの編集

証明書の有効期限が近づいている場合など、キー管理サーバの設定の編集が必要になることがあります。

.開始する前に
* KMS用に選択したサイトを更新する場合は、を確認しておきlink:kms-considerations-for-changing-for-site.html["サイトの KMS を変更する際の考慮事項"]ます。
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたはを持っていますlink:admin-group-permissions.html["rootアクセス権限"]。


.手順
. 設定 * > * セキュリティ * > * キー管理サーバ * を選択します。
+
[Key management server]ページが表示され、設定済みのすべてのキー管理サーバが表示されます。

. 編集するKMSを選択し、*[アクション]*>*[編集]*を選択します。
+
テーブルでKMS名を選択し、KMS詳細ページで*編集*を選択して、KMSを編集することもできます。

. 必要に応じて、キー管理サーバの編集ウィザードの*ステップ1（KMSの詳細）*で詳細を更新します。
+
[cols="1a,3a"]
|===
| フィールド | 製品説明 


 a| 
KMS名
 a| 
この KMS を特定するのに役立つわかりやすい名前。1~64 文字で指定する必要があります。



 a| 
キー名
 a| 
KMS 内の StorageGRID クライアントの正確なキーエイリアス。1~255 文字で指定する必要があります。

キー名の編集が必要になることはほとんどありません。たとえば、エイリアスの名前が KMS で変更された場合や、以前のキーのすべてのバージョンが新しいエイリアスのバージョン履歴にコピーされている場合は、キー名を編集する必要があります。



 a| 
のキーを管理します
 a| 
サイト固有のKMSを編集していて、まだデフォルトKMSを持っていない場合は、オプションで*[別のKMSで管理されていないサイト(デフォルトKMS)]*を選択します。このオプションを選択すると、サイト固有のKMSがデフォルトのKMSに変換されます。これは、専用のKMSを持たないすべてのサイトと、拡張で追加されたすべてのサイトに適用されます。

*注:*サイト固有のKMSを編集している場合、別のサイトを選択することはできません。デフォルトのKMSを編集している場合、特定のサイトを選択することはできません。



 a| 
ポート
 a| 
KMS サーバが Key Management Interoperability Protocol （ KMIP ）の通信に使用するポート。デフォルトでは、 KMIP 標準ポートである 5696 が使用されます。



 a| 
ホスト名
 a| 
KMS の完全修飾ドメイン名または IP アドレス。

*注：*サーバ証明書のSubject Alternative Name（SAN）フィールドには、ここに入力するFQDNまたはIPアドレスが含まれている必要があります。そうしないと、 StorageGRID は KMS クラスタ内のすべてのサーバに接続できなくなります。

|===
. KMSクラスタを構成する場合は、*[別のホスト名を追加]*を選択して、クラスタ内の各サーバのホスト名を追加します。
. 「 * Continue * 」を選択します。
+
[キー管理サーバの編集]ウィザードの手順2（サーバ証明書のアップロード）が表示されます。

. サーバー証明書を置き換える必要がある場合は、 * 参照 * を選択して新しいファイルをアップロードします。
. 「 * Continue * 」を選択します。
+
[Edit a Key Management Server]ウィザードの手順3（クライアント証明書のアップロード）が表示されます。

. クライアント証明書とクライアント証明書の秘密鍵を置き換える必要がある場合は、 * 参照 * を選択して新しいファイルをアップロードします。
. [テストして保存]*を選択します。
+
キー管理サーバと影響を受けるサイトのすべてのノード暗号化アプライアンスノードの間の接続をテストします。すべてのノード接続が有効で、 KMS に正しいキーがある場合は、キー管理サーバが Key Management Server ページの表に追加されます。

. エラーメッセージが表示された場合は、メッセージの詳細を確認し、「 * OK * 」を選択します。
+
たとえば、この KMS 用に選択したサイトが別の KMS によってすでに管理されている場合や、接続テストに失敗した場合は、「 422 ： Unprocessable Entity 」というエラーが表示されます。

. 接続エラーを解決する前に現在の設定を保存する必要がある場合は、*[強制保存]*を選択します。
+

CAUTION: [Force save]*を選択すると、KMSの構成が保存されますが、各アプライアンスからそのKMSへの外部接続はテストされません。構成を含む問題 がある場合、該当するサイトでノード暗号化が有効になっているアプライアンスノードをリブートできない可能性があります。問題が解決するまでデータにアクセスできなくなる可能性があります。

+
KMS の設定が保存されます。

. 確認の警告を確認し、設定を強制的に保存する場合は、「 * OK 」を選択します。
+
KMS構成は保存されますが、KMSへの接続はテストされません。





== キー管理サーバ（ KMS ）を削除する

場合によっては、キー管理サーバの削除が必要になることがあります。たとえば、サイトの運用を停止した場合は、サイト固有の KMS を削除できます。

.開始する前に
* を確認しておきますlink:kms-considerations-and-requirements.html["キー管理サーバを使用する際の考慮事項と要件"]。
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたはを持っていますlink:admin-group-permissions.html["rootアクセス権限"]。


.タスクの内容
KMS は以下の場合に削除できます。

* サイトの運用が停止された場合や、ノードの暗号化が有効なアプライアンスノードがサイトに含まれていない場合は、サイト固有の KMS を削除できます。
* ノード暗号化が有効なアプライアンスノードがあるサイトごとにサイト固有の KMS がすでに存在する場合は、デフォルトの KMS を削除できます。


.手順
. 設定 * > * セキュリティ * > * キー管理サーバ * を選択します。
+
[Key management server]ページが表示され、設定済みのすべてのキー管理サーバが表示されます。

. 削除するKMSを選択し、*[アクション]*>*[削除]*を選択します。
+
テーブルでKMS名を選択し、KMS詳細ページで* Remove *を選択して、KMSを削除することもできます。

. 次の条件に該当することを確認します。
+
** アプライアンスノードでノード暗号化が有効になっていないサイトのサイト固有のKMSを削除する場合。
** デフォルトのKMSを削除しようとしていますが、ノード暗号化を使用して各サイトにサイト固有のKMSがすでに存在しています。


. 「 * はい * 」を選択します。
+
KMS の設定は削除されます。


