---
permalink: admin/managing-traffic-classification-policies.html 
sidebar: sidebar 
keywords: QoS, quality of service, traffic classification, best practices, limit traffic, monitor traffic 
summary: トラフィック分類ポリシーを使用すると、さまざまなタイプのネットワークトラフィックを識別および監視できます。これらのポリシーは、トラフィックの制限と監視に役立ち、Quality of Service（QoS；サービス品質）サービスを強化できます。 
---
= トラフィック分類ポリシーとは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
トラフィック分類ポリシーを使用すると、さまざまなタイプのネットワークトラフィックを識別および監視できます。これらのポリシーは、トラフィックの制限と監視に役立ち、Quality of Service（QoS；サービス品質）サービスを強化できます。

トラフィック分類ポリシーは、ゲートウェイノードおよび管理ノードの StorageGRID ロードバランササービス上のエンドポイントに適用されます。トラフィック分類ポリシーを作成するには、ロードバランサエンドポイントを作成しておく必要があります。



== 一致ルール

各トラフィック分類ポリシーには、次のエンティティに関連するネットワークトラフィックを識別する 1 つ以上の一致ルールが含まれています。

* バケット
* サブネット
* テナント
* ロードバランサエンドポイント


StorageGRID は、ルールの目的に応じて、ポリシー内のルールに一致するトラフィックを監視します。ポリシーのルールに一致するトラフィックは、そのポリシーによって処理されます。逆に、指定されたエンティティを除くすべてのトラフィックを照合するルールを設定できます。



== トラフィック制限

必要に応じて、次の制限タイプをポリシーに追加できます。

* 総帯域幅
* 要求ごとの帯域幅
* 同時要求
* リクエスト率


制限値はロードバランサごとに適用されます。複数のロードバランサに同時にトラフィックが分散されている場合、合計最大速度は指定した速度制限の倍数になります。


NOTE: ポリシーを作成して、アグリゲートの帯域幅を制限したり、要求ごとの帯域幅を制限したりできます。ただし、StorageGRID では、両方のタイプの帯域幅を同時に制限することはできません。総帯域幅を制限すると、制限のないトラフィックのパフォーマンスがさらに若干低下する可能性があります。

集約または要求ごとの帯域幅制限の場合、要求は、設定したレートでストリームインまたはアウトされます。StorageGRID では 1 つの速度しか適用できないため、最も特定のポリシーがマッチするのはマッチャーのタイプです。要求によって消費された帯域幅は、集約帯域幅制限ポリシーを含む他のあまり具体的でない一致ポリシーにはカウントされません。それ以外のすべての制限タイプでは、クライアント要求は 250 ミリ秒遅延し、一致するポリシー制限を超える要求に対しては 503 スローダウン応答を受信します。

Grid Manager では、トラフィックチャートを表示して、ポリシーが想定したトラフィック制限を適用していることを確認できます。



== SLA でトラフィック分類ポリシーを使用する

トラフィック分類ポリシーを容量制限およびデータ保護とともに使用して、容量、データ保護、およびパフォーマンスに固有のサービスレベル契約（ SLA ）を適用できます。

次の例は、 SLA の 3 つの階層を示しています。トラフィック分類ポリシーを作成して、各 SLA 層のパフォーマンス目標を達成できます。

[cols="1a,1a,1a,1a,1a"]
|===
| サービスレベル階層 | 容量 | データ保護 | 許容される最大パフォーマンス | コスト 


 a| 
Gold
 a| 
1 PB のストレージを使用できます
 a| 
3コピーILMルール
 a| 
25 、 000 要求 / 秒

5GB/秒（40Gbps）の帯域幅
 a| 
$$/ 月



 a| 
シルバー
 a| 
250TBのストレージを許可
 a| 
2コピーILMルール
 a| 
10K要求/秒

1.25GB/秒（10Gbps）の帯域幅
 a| 
$/ 月



 a| 
ブロンズ
 a| 
100TBのストレージを許可
 a| 
2コピーILMルール
 a| 
5、000リクエスト/秒

1GB/秒（8Gbps）の帯域幅
 a| 
月あたりのコスト

|===