---
permalink: admin/managing-full-storage-nodes.html 
sidebar: sidebar 
keywords: storage node is full 
summary: ストレージノードの容量が上限に達した場合は、新しいストレージを追加して StorageGRID システムを拡張する必要があります。ストレージボリュームの追加、ストレージ拡張シェルフの追加、ストレージノードの追加の 3 つのオプションがあります。 
---
= ストレージノードがいっぱいになったときの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージノードの容量が上限に達した場合は、新しいストレージを追加して StorageGRID システムを拡張する必要があります。ストレージボリュームの追加、ストレージ拡張シェルフの追加、ストレージノードの追加の 3 つのオプションがあります。



== ストレージボリュームを追加します

各ストレージノードは最大数のストレージボリュームをサポートします。定義されている最大値はプラットフォームによって異なります。ストレージノードのストレージボリュームが最大数より少ない場合は、ボリュームを追加して容量を増やすことができます。の手順を参照してくださいlink:../expand/index.html["StorageGRID システムの拡張"]。



== ストレージ拡張シェルフを追加する

一部のStorageGRIDアプライアンスストレージノード（SG6060やSG6160など）では、追加のストレージシェルフをサポートできます。拡張機能が最大容量まで拡張されていない StorageGRID アプライアンスがある場合は、ストレージシェルフを追加して容量を増やすことができます。の手順を参照してくださいlink:../expand/index.html["StorageGRID システムの拡張"]。



== ストレージノードを追加します

ストレージノードを追加してストレージ容量を増やすことができます。ストレージを追加する場合は、現在アクティブな ILM ルールと容量の要件について慎重に検討する必要があります。の手順を参照してくださいlink:../expand/index.html["StorageGRID システムの拡張"]。
