---
permalink: admin/manage-platform-services-for-tenants.html 
sidebar: sidebar 
keywords: platform service, cloudmirror replication, event notification, search integration service 
summary: プラットフォームサービスには、 CloudMirror レプリケーション、イベント通知、および検索統合サービスがあります。 
---
= プラットフォームサービスとは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プラットフォームサービスには、 CloudMirror レプリケーション、イベント通知、および検索統合サービスがあります。

S3 テナントアカウントでプラットフォームサービスを有効にする場合は、テナントがそのサービスの使用に必要な外部リソースにアクセスできるようにグリッドを設定する必要があります。

プラットフォームサービスはサポートされていませんlink:../tenant/what-is-branch-bucket.html["ブランチバケット"]。



== CloudMirror レプリケーション

StorageGRID CloudMirrorレプリケーションサービスは、StorageGRIDバケットから指定された外部のデスティネーションに特定のオブジェクトをミラーリングするために使用します。

たとえば、 CloudMirror レプリケーションを使用して特定の顧客レコードを Amazon S3 にミラーリングし、 AWS サービスを利用してデータを分析することができます。

CloudMirrorレプリケーションには、クロスグリッドレプリケーション機能と重要な類似点と相違点がいくつかあります。詳細については、を参照してくださいlink:../admin/grid-federation-compare-cgr-to-cloudmirror.html["グリッド間レプリケーションとCloudMirrorレプリケーションを比較してください"]。


NOTE: ソースバケットで S3 オブジェクトロックが有効になっている場合、CloudMirror レプリケーションはサポートされません。



== 通知

バケットごとのイベント通知は、オブジェクトに対して実行された特定のアクションに関する通知を、指定された外部 Kafka クラスター、Webhook エンドポイント、または Amazon Simple Notification Service に送信するために使用されます。

たとえば、バケットに追加された各オブジェクトについてアラートが管理者に送信されるように設定できます。この場合、オブジェクトは重大なシステムイベントに関連付けられているログファイルです。


NOTE: S3 オブジェクトのロックが有効になっているバケットでイベント通知を設定することはできますが、オブジェクトの S3 オブジェクトロックメタデータ（ Retain Until Date および Legal Hold のステータスを含む）は通知メッセージに含まれません。



== 検索統合サービス

検索統合サービスは、外部サービスを使用してメタデータを検索または分析できるように、指定されたElasticsearchインデックスにS3オブジェクトメタデータを送信するために使用されます。

たとえば、リモートの Elasticsearch サービスに S3 オブジェクトメタデータを送信するようにバケットを設定できます。次に、 Elasticsearch を使用してバケット間で検索を実行し、オブジェクトメタデータのパターンに対して高度な分析を実行できます。


NOTE: S3 オブジェクトロックが有効なバケットでは Elasticsearch 統合を設定できますが、オブジェクトの S3 オブジェクトロックメタデータ（ Retain Until Date および Legal Hold のステータスを含む）は通知メッセージに含まれません。

プラットフォームサービスを使用すると、テナントで、外部ストレージリソース、通知サービス、データの検索または分析サービスを利用できるようになります。通常、プラットフォームサービスのターゲットは StorageGRID 環境の外部にあるため、テナントにこれらのサービスの使用を許可するかどうかを決める必要があります。この方法を使用する場合は、テナントアカウントを作成または編集するときにプラットフォームサービスの使用を有効にする必要があります。テナントで生成されたプラットフォームサービスのメッセージが宛先に届くようにネットワークを設定する必要もあります。



== プラットフォームサービスの使用に関する推奨事項

プラットフォームサービスを使用する前に、次の推奨事項を確認してください。

* StorageGRID システムの S3 バケットで、バージョン管理と CloudMirror レプリケーションの両方が有効になっている場合は、デスティネーションエンドポイントでも S3 バケットのバージョン管理を有効にします。これにより、 CloudMirror レプリケーションでエンドポイントに同様のオブジェクトバージョンを生成できます。
* CloudMirror のレプリケーション、通知、検索統合を必要とする S3 要求ではアクティブなテナントが 100 個を超えないようにします。アクティブなテナントが 100 を超えると、 S3 クライアントのパフォーマンスが低下する可能性があります。
* 完了できないエンドポイントへの要求は、最大50万件の要求にキューイングされます。この制限はアクティブなテナント間で均等に共有されます。新規テナントは、新規に作成されたテナントに不当なペナルティが課されないように、一時的にこの50万を超えることができます。


.関連情報
* link:../tenant/what-platform-services-are.html["プラットフォームサービスを管理します"]
* link:configuring-storage-proxy-settings.html["ストレージプロキシを設定します"]
* link:../monitor/index.html["StorageGRID を監視します"]

