---
permalink: admin/networking-and-ports-for-platform-services.html 
sidebar: sidebar 
keywords: platform services, ports for platform services, 443, 80 
summary: S3 テナントにプラットフォームサービスの使用を許可する場合は、プラットフォームサービスのメッセージがデスティネーションに配信されるようにグリッドのネットワークを設定する必要があります。 
---
= プラットフォームサービス用のネットワークとポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 テナントにプラットフォームサービスの使用を許可する場合は、プラットフォームサービスのメッセージがデスティネーションに配信されるようにグリッドのネットワークを設定する必要があります。

テナントアカウントを作成または更新する際に、 S3 テナントアカウントのプラットフォームサービスを有効にできます。プラットフォームサービスが有効になっている場合、テナントは、その S3 バケットからの CloudMirror レプリケーション、イベント通知、または検索統合のメッセージのデスティネーションとして機能するエンドポイントを作成できます。これらのプラットフォームサービスメッセージは、 ADC サービスを実行しているストレージノードからデスティネーションエンドポイントに送信されます。

たとえば、テナントは次のタイプのデスティネーションエンドポイントを設定できます。

* ローカルでホストされる Elasticsearch クラスタ
* Amazon Simple Notification Serviceメッセージの受信をサポートするローカルアプリケーション
* ローカルでホストされるKafkaクラスタ
* StorageGRID の同じインスタンス上または別のインスタンス上の、ローカルにホストされる S3 バケット
* Amazon Web Services 上のエンドポイントなどの外部エンドポイント。


プラットフォームサービスメッセージが確実に配信されるように、 ADC ストレージノードが含まれるネットワークを設定する必要があります。デスティネーションエンドポイントへのプラットフォームサービスメッセージの送信に、次のポートを使用できることを確認する必要があります。

デフォルトでは、プラットフォームサービスメッセージは次のポートで送信されます。

* *80*: httpで始まるエンドポイントURIの場合(ほとんどのエンドポイント)
* * 443 *：httpsで始まるエンドポイントURI（ほとんどのエンドポイント）
* *9092 *：httpまたはhttpsで始まるエンドポイントURIの場合（Kafkaエンドポイントのみ）


エンドポイントの作成や編集を行う際に、テナントで別のポートを指定できます。


NOTE: StorageGRID 環境が CloudMirror レプリケーションのデスティネーションとして使用されている場合は、ポート 80 または 443 以外のポートにレプリケーションメッセージが送信される可能性があります。デスティネーション StorageGRID 環境で S3 に使用されているポートがエンドポイントで指定されていることを確認してください。

非透過型プロキシサーバを使用する場合は、インターネット上のエンドポイントなどの外部エンドポイントへのメッセージの送信も許可する必要がありますlink:configuring-storage-proxy-settings.html["ストレージプロキシを設定します"]。

.関連情報
link:../tenant/index.html["テナントアカウントを使用する"]
