---
permalink: admin/signing-in-to-grid-manager.html 
sidebar: sidebar 
keywords: grid manager, sign in, log in 
summary: Grid Manager のサインインページにアクセスするには、サポートされている Web ブラウザのアドレスバーに管理ノードの完全修飾ドメイン名（ FQDN ）または IP アドレスを入力します。 
---
= Grid Manager にサインインします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Grid Manager のサインインページにアクセスするには、サポートされている Web ブラウザのアドレスバーに管理ノードの完全修飾ドメイン名（ FQDN ）または IP アドレスを入力します。

各 StorageGRID システムには、 1 つのプライマリ管理ノードと、任意の数のプライマリ以外の管理ノードが含まれています。任意の管理ノードでグリッドマネージャにサインインして、 StorageGRID システムを管理できます。ただし、一部のメンテナンス手順はプライマリ管理ノードからしか実行できません。



=== HAグループに接続します

管理ノードがハイアベイラビリティ（ HA ）グループに含まれている場合は、 HA グループの仮想 IP アドレスまたは仮想 IP アドレスにマッピングされる完全修飾ドメイン名を使用して接続します。プライマリ管理ノードが使用できない場合を除いてプライマリ管理ノード上のグリッド Manager にアクセスするよう、プライマリ管理ノードをグループのプライマリインターフェイスとして選択する必要があります。を参照して link:managing-high-availability-groups.html["ハイアベイラビリティグループを管理します"]



=== SSOを使用します

の場合、サインイン手順は少し異なりlink:how-sso-works.html["シングルサインオン（SSO）が設定されている"]ます。



== 最初の管理ノードでGrid Managerにサインインします

.開始する前に
* ログインクレデンシャルが必要です。
* を使用しているlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* Web ブラウザでクッキーが有効になっている必要があります。
* 少なくとも1つの権限が割り当てられたユーザグループに属している必要があります。
* Grid ManagerのURLが必要です。
+
`https://_FQDN_or_Admin_Node_IP_/`

+
完全修飾ドメイン名、管理ノードのIPアドレス、または管理ノードのHAグループの仮想IPアドレスを使用できます。

+
HTTPSのデフォルトのポート（443）以外のポートでGrid Managerにアクセスするには、URLにポート番号を追加します。

+
`https://_FQDN_or_Admin_Node_IP:port_/`

+

NOTE: SSOは制限されたGrid Managerポートでは使用できません。ポート 443 を使用する必要があります。



.手順
. サポートされている Web ブラウザを起動します。
. ブラウザのアドレスバーに、Grid ManagerのURLを入力します。
. セキュリティアラートが表示された場合は、ブラウザのインストールウィザードを使用して証明書をインストールします。を参照して link:using-storagegrid-security-certificates.html["セキュリティ証明書を管理する"]
. Grid Manager にサインインします。
+
表示されるサインイン画面は、StorageGRID 用にシングルサインオン（SSO）が設定されているかどうかによって異なります。

+
[role="tabbed-block"]
====
.SSOを使用しない
--
.. Grid Manager のユーザ名とパスワードを入力します。
.. 「サインイン」を選択します。


--
.SSOを使用する
--
** StorageGRID がSSOを使用しており、このブラウザで初めてURLにアクセスした場合は、次の手順を実行します。
+
... 「サインイン」を選択します。[Account]フィールドに0を入力したままにしておくことができます。
... 組織の SSO サインインページで標準の SSO クレデンシャルを入力します。例：


** StorageGRID でSSOを使用しており、Grid Managerまたはテナントアカウントに以前にアクセスしたことがある場合は、次の手順を実行します。
+
... 0 *（Grid ManagerのアカウントID）を入力するか、最近のアカウントのリストに表示されている場合は* Grid Manager *を選択します。
... 「サインイン」を選択します。
... 組織の SSO サインインページで通常使用している SSO クレデンシャルを使用してサインインします。




--
====


サインインすると、ダッシュボードを含むGrid Managerのホームページが表示されます。提供される情報については、を参照してくださいlink:../monitor/viewing-dashboard.html["ダッシュボードを表示および管理します"]。



== 別の管理ノードにサインインします

次の手順に従って、別の管理ノードにサインインします。

[role="tabbed-block"]
====
.SSOを使用しない
--
.手順
. ブラウザのアドレスバーに、他の管理ノードの完全修飾ドメイン名または IP アドレスを入力します。必要に応じてポート番号を追加します。
. Grid Manager のユーザ名とパスワードを入力します。
. 「サインイン」を選択します。


--
.SSOを使用する
--
SSOを使用しているStorageGRID で1つの管理ノードにサインインしている場合は、再度サインインしなくても他の管理ノードにアクセスできます。

.手順
. ブラウザのアドレスバーに、もう一方の管理ノードの完全修飾ドメイン名またはIPアドレスを入力します。
. SSOセッションの有効期限が切れている場合は、クレデンシャルを再度入力します。


--
====