---
permalink: admin/summary-ip-addresses-and-ports-for-client-connections.html 
sidebar: sidebar 
keywords: ip addresses for client, how to connect to storagegrid, ports, vip 
summary: S3クライアントアプリケーションは、オブジェクトの格納や読み出しを行うために、すべての管理ノードおよびゲートウェイノードに含まれるロードバランササービスまたはすべてのストレージノードに含まれるLocal Distribution Router（LDR）サービスに接続します。 
---
= Summary ：クライアント接続の IP アドレスとポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3クライアントアプリケーションは、オブジェクトの格納や読み出しを行うために、すべての管理ノードおよびゲートウェイノードに含まれるロードバランササービスまたはすべてのストレージノードに含まれるLocal Distribution Router（LDR）サービスに接続します。

クライアントアプリケーションは、グリッドノードのIPアドレスとそのノード上のサービスのポート番号を使用してStorageGRID に接続できます。必要に応じて、ロードバランシングノードのハイアベイラビリティ（HA）グループを作成して、仮想IP（VIP）アドレスを使用する可用性の高い接続を確立できます。IPアドレスまたはVIPアドレスの代わりに完全修飾ドメイン名（FQDN）を使用してStorageGRID に接続する場合は、DNSエントリを設定できます。

次の表に、クライアントが StorageGRID に接続できるさまざまな方法、および接続のタイプごとに使用される IP アドレスとポートを示します。ロードバランサエンドポイントとハイアベイラビリティ（HA）グループを作成済みの場合は、を参照してGrid Managerでこれらの値を確認してください<<IPアドレスの検索場所>>。

[cols="1a,1a,1a,1a"]
|===
| 接続が確立される場所 | クライアントが接続するサービス | IPアドレス | ポート 


 a| 
HAグループ
 a| 
ロードバランサ
 a| 
HA グループの仮想 IP アドレス
 a| 
ロードバランサエンドポイントに割り当てられたポート



 a| 
管理ノード
 a| 
ロードバランサ
 a| 
管理ノードの IP アドレス
 a| 
ロードバランサエンドポイントに割り当てられたポート



 a| 
ゲートウェイノード
 a| 
ロードバランサ
 a| 
ゲートウェイノードの IP アドレス
 a| 
ロードバランサエンドポイントに割り当てられたポート



 a| 
ストレージノード
 a| 
LDR
 a| 
ストレージノードの IP アドレス
 a| 
デフォルトの S3 ポート：

* HTTPS：18082
* HTTP：18084


|===


== URLの例

クライアントアプリケーションをゲートウェイノードのHAグループのロードバランサエンドポイントに接続するには、次の構造のURLを使用します。

`https://_VIP-of-HA-group:LB-endpoint-port_`

たとえば、HAグループの仮想IPアドレスが192.0.2.5で、ロードバランサエンドポイントのポート番号が10443の場合、アプリケーションは次のURLを使用してStorageGRID に接続できます。

`\https://192.0.2.5:10443`



== IPアドレスの検索場所

. を使用してGrid Managerにサインインしlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]ます。
. グリッドノードの IP アドレスを確認するには、次の手順を実行します。
+
.. [* nodes （ノード） ] を選択します
.. 接続する管理ノード、ゲートウェイノード、またはストレージノードを選択します。
.. [* Overview * （概要 * ） ] タブを選択します。
.. Node Information セクションで、ノードの IP アドレスを確認します。
.. IPv6 アドレスとインターフェイスマッピングを表示するには、 * Show More * を選択します。
+
クライアントアプリケーションから、リスト内の任意の IP アドレスへの接続を確立できます。

+
*** * eth0 ： * グリッドネットワーク
*** * eth1 ： * 管理ネットワーク（オプション）
*** * eth2 ： * クライアントネットワーク（オプション）
+

NOTE: 表示されている管理ノードまたはゲートウェイノードがハイアベイラビリティグループのアクティブノードである場合は、 HA グループの仮想 IP アドレスが eth2 に表示されます。





. ハイアベイラビリティグループの仮想 IP アドレスを検索するには、次の手順を実行します。
+
.. 構成 * > * ネットワーク * > * ハイアベイラビリティグループ * を選択します。
.. HA グループの仮想 IP アドレスを表で確認します。


. ロードバランサエンドポイントのポート番号を確認するには、次の手順を実行します。
+
.. [ * configuration * > * Network * > * Load Balancer Endpoints * ] を選択します。
.. 使用するエンドポイントのポート番号をメモします。
+

NOTE: ポート番号が80または443の場合、エンドポイントはゲートウェイノードでのみ設定されます。これらのポートは管理ノードで予約されているためです。それ以外のポートはすべて、ゲートウェイノードと管理ノードの両方に設定されます。

.. テーブルからエンドポイントの名前を選択します。
.. [Client type]*（S3）がエンドポイントを使用するクライアントアプリケーションと一致していることを確認します。



