---
permalink: admin/use-s3-setup-wizard.html 
sidebar: sidebar 
keywords: S3, S3 setup wizard 
summary: S3セットアップウィザードを使用して、StorageGRID をS3アプリケーションのオブジェクトストレージシステムとして設定できます。 
---
= S3セットアップウィザードの「考慮事項と要件」を使用します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3セットアップウィザードを使用して、StorageGRID をS3アプリケーションのオブジェクトストレージシステムとして設定できます。



== S3セットアップウィザードを使用するタイミング

S3セットアップウィザードの手順に従って、S3アプリケーションで使用するStorageGRID を設定します。ウィザードを完了すると、ファイルをダウンロードしてS3アプリケーションに値を入力します。ウィザードを使用すると、システムをより迅速に設定し、設定がStorageGRID のベストプラクティスに準拠していることを確認できます。

を使用している場合link:admin-group-permissions.html["rootアクセス権限"]は、StorageGRIDグリッドマネージャの使用を開始したときにS3セットアップウィザードを完了することができます。また、ウィザードにアクセスしてあとから完了することもできます。要件に応じて、必要な項目の一部またはすべてを手動で設定し、ウィザードを使用してS3アプリケーションで必要な値をアセンブルすることもできます。



== ウィザードを使用する前に

ウィザードを使用する前に、これらの前提条件を満たしていることを確認してください。

IPアドレスを取得し、VLANインターフェイスを設定します:: ハイアベイラビリティ（HA）グループを設定する場合は、S3アプリケーションが接続するノードと使用するStorageGRID ネットワークを確認しておきます。また、サブネットCIDR、ゲートウェイIPアドレス、および仮想IP（VIP）アドレスに入力する値も確認しておきます。
+
--
仮想LANを使用してS3アプリケーションからトラフィックを分離する場合は、VLANインターフェイスがすでに設定されています。を参照して link:../admin/configure-vlan-interfaces.html["VLAN インターフェイスを設定します"]

--
アイデンティティフェデレーションとSSOを設定する:: StorageGRIDシステムで ID フェデレーションまたはシングル サインオン (SSO) を使用する予定の場合は、これらの機能が有効になっています。また、S3 アプリケーションが使用するテナント アカウントのルート アクセス権を持つフェデレーション グループも把握しています。見るlink:../admin/using-identity-federation.html["アイデンティティフェデレーションを使用する"]そしてlink:../admin/how-sso-works.html["シングルサインオンを設定します"]。
ドメイン名を取得して設定します:: StorageGRID に使用するFully Qualified Domain Name（FQDN；完全修飾ドメイン名）を確認しておきます。ドメインネームサーバ（DNS）のエントリによって、このFQDNが、ウィザードを使用して作成するHAグループの仮想IP（VIP）アドレスにマッピングされます。
+
--
S3仮想ホスト形式の要求を使用する場合は、をインストールしておく必要がありますlink:../admin/configuring-s3-api-endpoint-domain-names.html["S3エンドポイントのドメイン名が設定されました"]。仮想ホスト形式の要求を使用することを推奨します。

--
ロードバランサとセキュリティ証明書の要件を確認します:: StorageGRID ロードバランサを使用する場合は、ロードバランシングに関する一般的な考慮事項を確認しておきます。アップロードする証明書、または証明書の生成に必要な値を用意しておきます。
+
--
外部（サードパーティ）のロードバランサエンドポイントを使用する場合は、そのロードバランサの完全修飾ドメイン名（FQDN）、ポート、および証明書が必要です。

--
グリッドフェデレーション接続を設定します:: S3テナントがグリッドフェデレーション接続を使用してアカウントデータをクローニングし、バケットオブジェクトを別のグリッドにレプリケートできるようにする場合は、ウィザードを開始する前に次の点を確認してください。
+
--
* そうだな link:grid-federation-manage-connection.html["グリッドフェデレーション接続を設定しました"]
* 接続のステータスは*接続済み*です。
* Root Access 権限が割り当てられている。


--

