---
permalink: admin/viewing-network-traffic-metrics.html 
sidebar: sidebar 
keywords: network traffic, traffic classification policy, monitor traffic 
summary: トラフィック分類ポリシーページのグラフを表示して、ネットワークトラフィックを監視できます。 
---
= ネットワークトラフィックの指標を表示します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
トラフィック分類ポリシーページのグラフを表示して、ネットワークトラフィックを監視できます。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたはを持っていますlink:admin-group-permissions.html["rootアクセスまたはテナントアカウントの権限"]。


.タスクの内容
既存のトラフィック分類ポリシーについては、ロードバランササービスの指標を表示して、ポリシーがネットワーク全体のトラフィックを正常に制限しているかどうかを確認できます。グラフのデータは、ポリシーの調整が必要かどうかを判断するのに役立ちます。

トラフィック分類ポリシーに制限が設定されていない場合でも、メトリックが収集され、グラフにはトラフィックの傾向を把握するのに役立つ情報が表示されます。

.手順
. * configuration * > * Network * > * traffic classification * を選択します。
+
[Traffic Classification Policies]ページが表示され、既存のポリシーがテーブルに表示されます。

. 指標を表示するトラフィック分類ポリシーの名前を選択します。
. [Metrics]タブを選択します。
+
トラフィック分類ポリシーのグラフが表示されます。このグラフには、選択したポリシーに一致するトラフィックのメトリックだけが表示されます。

+
このページには次のグラフが表示されます。

+
** [Request rate]：このグラフには、すべてのロードバランサによって処理されたこのポリシーに一致する帯域幅の量が表示されます。受信したデータには、すべての要求の要求ヘッダーと、本文データを含む応答の本文データサイズが含まれます。Sentには、すべての要求の応答ヘッダーと、応答に本文データを含む要求の応答本文のデータサイズが含まれます。
+

NOTE: 要求が完了すると、このチャートには帯域幅の使用量のみが表示されます。低速なオブジェクト要求や大規模なオブジェクト要求では、実際の帯域幅はこのグラフに表示される値と異なる場合があります。

** エラー応答率：このグラフは、このポリシーに一致する要求がクライアントにエラー（HTTPステータスコード>=400）を返すおおよその速度を示します。
** Average request duration（non-error）：このグラフには、このポリシーに一致する成功したリクエストの平均期間が表示されます。
** Policy Bandwidth usage：このグラフには、すべてのロードバランサによって処理されたこのポリシーに一致する帯域幅の量が表示されます。受信したデータには、すべての要求の要求ヘッダーと、本文データを含む応答の本文データサイズが含まれます。Sentには、すべての要求の応答ヘッダーと、応答に本文データを含む要求の応答本文のデータサイズが含まれます。


. 折れ線グラフにカーソルを合わせると、グラフの特定の部分の値がポップアップで表示されます。
. [Metrics]タイトルのすぐ下にある* Grafanaダッシュボード*を選択すると、ポリシーのすべてのグラフが表示されます。[* Metrics]タブの4つのグラフに加えて、さらに2つのグラフを表示できます。
+
** Write request rate by object size：このポリシーに一致するPUT / POST / DELETE要求の速度。個 々 のセルに配置すると、1秒あたりのレートが表示されます。ホバービューに表示されるレートは整数に切り捨てられ、バケットに0以外の要求がある場合は0と報告されることがあります。
** Read request rate by object size：このポリシーに一致するGET / HEAD要求のレート。個 々 のセルに配置すると、1秒あたりのレートが表示されます。ホバービューに表示されるレートは整数に切り捨てられ、バケットに0以外の要求がある場合は0と報告されることがあります。


. または、 *support* メニューからグラフにアクセスします。
+
.. [*support*>] 、 [*Tools] 、 [*Metrics] の順に選択します。
.. [Grafana]セクションから*[Traffic Classification Policy]*を選択します。
.. ページ左上のメニューからポリシーを選択します。
.. グラフにカーソルを合わせると、サンプルの日時、カウントに集計されたオブジェクトサイズ、その期間の1秒あたりの要求数を示すポップアップが表示されます。
+
トラフィック分類ポリシーは、その ID によって識別されます。ポリシーIDは、トラフィック分類ポリシーページに表示されます。



. グラフを分析して、ポリシーがトラフィックを制限している頻度と、ポリシーを調整する必要があるかどうかを判断します。

