---
permalink: s3/complete-multipart-upload.html 
sidebar: sidebar 
keywords: multipart upload, object, object size 
summary: CompleteMultipartUpload処理は、以前にアップロードされたパートをアセンブルして、オブジェクトのマルチパートアップロードを完了します。 
---
= CompleteMultipartUpload
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CompleteMultipartUpload処理は、以前にアップロードされたパートをアセンブルして、オブジェクトのマルチパートアップロードを完了します。


NOTE: StorageGRIDでは、CompleteMultipartUploadで要求パラメータの連続しない値が昇順でサポートされます `partNumber`。パラメータは任意の値から開始できます。



== 競合を解決します

同じキーに書き込む 2 つのクライアントなど、競合するクライアント要求は、「 latest-wins 」ベースで解決されます。「 latest-wins 」評価は、 S3 クライアントが処理を開始するタイミングではなく、 StorageGRID システムが特定の要求を完了したタイミングで行われます。



== サポートされる要求ヘッダー

次の要求ヘッダーがサポートされています。

* `x-amz-checksum-sha256`
* `x-amz-storage-class`
+
ヘッダーは `x-amz-storage-class`、一致するILMルールでが指定されている場合にStorageGRIDで作成されるオブジェクトコピーの数に影響しますlink:../ilm/data-protection-options-for-ingest.html["デュアルコミットまたはBalanced取り込みオプション"]。

* `STANDARD`
+
（デフォルト） ILM ルールで Dual commit オプションが使用されている場合、または Balanced オプションによって中間コピーが作成される場合に、デュアルコミットの取り込み処理を指定します。

* `REDUCED_REDUNDANCY`
+
ILM ルールで Dual commit オプションが使用されている場合、または Balanced オプションによって中間コピーが作成される場合に、シングルコミットの取り込み処理を指定します。

+

NOTE: S3 Object Lockが有効なバケットにオブジェクトを取り込む場合、この `REDUCED_REDUNDANCY`オプションは無視されます。従来の準拠バケットにオブジェクトを取り込む場合、オプションを指定すると `REDUCED_REDUNDANCY`エラーが返されます。StorageGRID では、常にデュアルコミットの取り込みが実行され、コンプライアンス要件が満たされます。




CAUTION: マルチパートアップロードが 15 日以内に完了しないと、非アクティブな処理としてマークされ、関連するすべてのデータがシステムから削除されます。


NOTE:  `ETag`返される値はデータのMD5合計ではなく、Amazon S3 APIによるマルチパートオブジェクトの値の実装に従います `ETag`。



== サポートされない要求ヘッダーです

次の要求ヘッダーはサポートされていません。

* `x-amz-sdk-checksum-algorithm`
* `x-amz-trailer`




== バージョン管理

マルチパートアップロードは、この処理で完了します。バケットでバージョン管理が有効になっている場合は、マルチパートアップロードの完了後にオブジェクトのバージョンが作成されます。

バケットでバージョン管理が有効になっている場合は、格納されているオブジェクトのバージョンに対して一意のが `versionId`自動的に生成されます。これは `versionId`、応答ヘッダーを使用した応答でも返され `x-amz-version-id`ます。

バージョン管理が一時停止されている場合、オブジェクトのバージョンはnullで格納され `versionId`、nullのバージョンがすでに存在する場合は上書きされます。


NOTE: バケットでバージョン管理が有効になっているときは、同じオブジェクトキーで同時に複数のマルチパートアップロードが実行されている場合でも、マルチパートアップロードが完了するたびに常に新しいバージョンが作成されます。バケットでバージョン管理が有効になっていないときは、マルチパートアップロードの開始後に、同じオブジェクトキーで別のマルチパートアップロードが開始されて先に完了することがあります。バージョン管理が有効になっていないバケットでは、最後に完了したマルチパートアップロードが優先されます。



== レプリケーション、通知、またはメタデータ通知に失敗しました

マルチパートアップロードが行われるバケットでプラットフォームサービスが設定されている場合、関連するレプリケーション操作や通知操作が失敗してもマルチパートアップロードは正常に実行されます。

テナントでは、オブジェクトのメタデータまたはタグを更新することで、失敗したレプリケーションまたは通知をトリガーできます。テナントでは、既存の値を再送信し、不要な変更を回避できます。

を参照してください link:../admin/troubleshooting-platform-services.html["プラットフォームサービスのトラブルシューティングを行う"]。
