---
permalink: s3/get-object.html 
sidebar: sidebar 
keywords: get object 
summary: S3 GET Object 要求を使用して、 S3 バケットからオブジェクトを読み出すことができます。 
---
= GetObject
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 GetObject要求を使用すると、S3バケットからオブジェクトを読み出すことができます。



== GetObjectオブジェクトとマルチパートオブジェクト

要求パラメータを使用すると、マルチパートオブジェクトまたはセグメント化されたオブジェクトの特定の部分を読み出すことができます `partNumber`。 `x-amz-mp-parts-count`response要素は、オブジェクトに含まれるパーツの数を示します。

セグメント化されたオブジェクト/マルチパートオブジェクトとセグメント化されていないオブジェクト/マルチパート以外のオブジェクトの両方で1に設定できます `partNumber`。ただし、 `x-amz-mp-parts-count`応答要素はセグメント化されたオブジェクトまたはマルチパートオブジェクトの場合にのみ返されます。



== ユーザメタデータ内の UTF-8 文字

StorageGRID は、ユーザ定義メタデータ内のエスケープされた UTF-8 文字を解析も解釈もしません。ユーザ定義メタデータにエスケープされたUTF-8文字が含まれているオブジェクトに対するGET要求で、キーの名前または値に印刷不能文字が含まれている場合にヘッダーが返されません `x-amz-missing-meta`。



== サポートされる要求ヘッダー

次の要求ヘッダーがサポートされます。

* `x-amz-checksum-mode`:指定 `ENABLED`
+
 `Range`for GetObjectではヘッダーはサポートされていません `x-amz-checksum-mode`。enabledを指定して要求 `x-amz-checksum-mode`にを含める `Range`と、StorageGRIDは応答にチェックサム値を返しません。





== サポートされない要求ヘッダーです

次の要求ヘッダーはサポートされておらず、が返されます。 `XNotImplemented`

* `x-amz-website-redirect-location`




== バージョン管理

サブリソースを指定しない場合は `versionId`、バージョン管理されたバケット内のオブジェクトの最新バージョンが取得されます。オブジェクトの現在のバージョンが削除マーカーの場合は、「Not Found」ステータスが返され、 `x-amz-delete-marker`応答ヘッダーがに設定され `true`ます。



== ユーザ指定の暗号化キーによるサーバ側の暗号化（ SSE-C ）の要求ヘッダー

指定した一意のキーでオブジェクトが暗号化されている場合は、 3 つのヘッダーをすべて使用します。

* `x-amz-server-side-encryption-customer-algorithm`:指定します `AES256`。
* `x-amz-server-side-encryption-customer-key`：オブジェクトの暗号化キーを指定します。
* `x-amz-server-side-encryption-customer-key-MD5`:オブジェクトの暗号化キーのMD5ダイジェストを指定します。



CAUTION: 指定した暗号化キーが格納されることはありません。暗号化キーを紛失すると、対応するオブジェクトが失われます。ユーザ指定のキーを使用してオブジェクトデータを保護する前に、の考慮事項を確認してくださいlink:using-server-side-encryption.html["サーバ側の暗号化を使用します"]。



== クラウドストレージプールオブジェクトに対するGetObjectの動作

オブジェクトがに格納されている場合link:../ilm/what-cloud-storage-pool-is.html["クラウドストレージプール"]、GetObject要求の動作はオブジェクトの状態によって異なります。詳細については、を参照してくださいlink:head-object.html["ヘッドオブジェクト"]。


NOTE: オブジェクトがクラウドストレージプールに格納されていて、そのオブジェクトのコピーがグリッドに1つ以上存在する場合、GetObject要求はクラウドストレージプールからデータを読み出す前にグリッドからデータを読み出そうとします。

[cols="1a,1a"]
|===
| オブジェクトの状態 | GetObjectの動作 


 a| 
StorageGRID に取り込まれているがまだ ILM によって評価されていないオブジェクト、または従来のストレージプールに格納されているオブジェクト、またはイレイジャーコーディングを使用しているオブジェクト
 a| 
`200 OK`

オブジェクトのコピーが読み出されます。



 a| 
クラウドストレージプール内にあるが、まだ読み出し不可能な状態に移行していない
 a| 
`200 OK`

オブジェクトのコピーが読み出されます。



 a| 
オブジェクトを読み出し不可能な状態に移行した
 a| 
`403 Forbidden`、 `InvalidObjectState`

要求を使用しlink:post-object-restore.html["RestoreObject"]て、オブジェクトを読み出し可能な状態にリストアします。



 a| 
読み出し不可能な状態からリストア中である
 a| 
`403 Forbidden`、 `InvalidObjectState`

RestoreObject要求が完了するまで待ちます。



 a| 
クラウドストレージプールへのリストアが完了している
 a| 
`200 OK`

オブジェクトのコピーが読み出されます。

|===


=== クラウドストレージプール内のマルチパートオブジェクトまたはセグメント化されたオブジェクト

マルチパートオブジェクトをアップロードした場合や StorageGRID が大きなオブジェクトをセグメントに分割した場合、 StorageGRID はオブジェクトのパーツまたはセグメントのサブセットをサンプリングすることでクラウドストレージプール内のオブジェクトが使用可能かどうかを判断します。オブジェクトの一部がすでに読み出し不可能な状態に移行されている場合や、オブジェクトの一部がまだリストアされていない場合に、GetObject要求が誤って返されることがあります `200 OK`。

このような場合は、次のよう

* GetObject要求から一部のデータが返される場合がありますが、転送の途中で停止することがあります。
* 後続のGetObject要求が返されることがあります `403 Forbidden`。




== GetObjectとグリッド間レプリケーション

を使用していてlink:../tenant/grid-federation-manage-cross-grid-replication.html["グリッド間レプリケーション"]バケットで有効になっている場合link:../admin/grid-federation-overview.html["グリッドフェデレーション"]、S3クライアントはGetObject要求を発行してオブジェクトのレプリケーションステータスを確認できます。応答には、次のいずれかの値を持つStorageGRID固有の応答ヘッダーが含まれ `x-ntap-sg-cgr-replication-status`ます。

[cols="1a,2a"]
|===
| グリッド | レプリケーションのステータス 


 a| 
ソース
 a| 
* *完了*:レプリケーションは成功しました。
* * pending*：オブジェクトはまだレプリケートされていません。
* *failure*:レプリケーションが永続的なエラーで失敗しました。ユーザーはエラーを解決する必要があります。




 a| 
デスティネーション
 a| 
*replica*:オブジェクトはソースグリッドからレプリケートされました。

|===

NOTE: StorageGRIDはヘッダーをサポートしていません `x-amz-replication-status`。
