---
permalink: s3/initiate-multipart-upload.html 
sidebar: sidebar 
keywords: initiate multipart upload, CreateMultipartUpload, upload ID 
summary: CreateMultipartUpload処理を実行すると、オブジェクトのマルチパートアップロードが開始され、アップロードIDが返されます。 
---
= CreateMultipartUpload
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CreateMultipartUpload（以前のInitiate Multipart Upload）処理は、オブジェクトのマルチパートアップロードを開始し、アップロードIDを返します。

 `x-amz-storage-class`要求ヘッダーがサポートされます。で送信される値 `x-amz-storage-class`は、StorageGRIDによる取り込み時のオブジェクトデータの保護方法に影響し、StorageGRIDシステムに格納されるオブジェクトの永続的コピーの数（ILMで決定）には影響しません。

取り込まれたオブジェクトに一致するILMルールでStrictが使用されている場合、link:../ilm/data-protection-options-for-ingest.html["取り込みオプション"] `x-amz-storage-class`ヘッダーは無効です。

には次の値を使用でき `x-amz-storage-class`ます。

* `STANDARD`（デフォルト）
+
** * Dual commit *：ILMルールでDual commit取り込みオプションが指定されている場合は、オブジェクトが取り込まれるとすぐにそのオブジェクトの2つ目のコピーが作成されて別のストレージノードに分散されます（デュアルコミット）。ILMが評価されると、StorageGRID はこれらの初期中間コピーがルールの配置手順を満たしているかどうかを判断します。作成されていない場合は、新しいオブジェクトコピーを別の場所に作成し、最初の中間コピーを削除しなければならないことがあります。
** * Balanced *：ILMルールでBalancedオプションが指定されていて、ルールで指定されたすべてのコピーをStorageGRID がすぐに作成できない場合、StorageGRID は2つの中間コピーを別 々 のストレージノードに作成します。
+
ILMルールで指定されたすべてのオブジェクトコピーをStorageGRIDでただちに作成できる場合（同期配置）、 `x-amz-storage-class`ヘッダーは効果がありません。



* `REDUCED_REDUNDANCY`
+
** * Dual commit *：ILMルールでDual commitオプションが指定されている場合、StorageGRIDはオブジェクトの取り込み時に中間コピーを1つ作成します（シングルコミット）。
** * Balanced *：ILMルールでBalancedオプションが指定されている場合、StorageGRID は、ルールで指定されたすべてのコピーをただちに作成できない場合にのみ中間コピーを1つ作成します。StorageGRID で同期配置を実行できる場合、このヘッダーは効果がありません。 `REDUCED_REDUNDANCY`オブジェクトに一致するILMルールで単一のレプリケートコピーが作成される場合は、オプションの使用を推奨します。この場合、を使用する `REDUCED_REDUNDANCY`と、取り込み処理のたびに余分なオブジェクトコピーを不要に作成および削除する必要がなくなります。


+
それ以外の状況では、オプションの使用 `REDUCED_REDUNDANCY`は推奨されません。 `REDUCED_REDUNDANCY`取り込み中にオブジェクトデータが失われるリスクが高まります。たとえば、 ILM 評価の前にコピーが 1 つだけ格納されていたストレージノードに障害が発生すると、データが失われる可能性があります。




CAUTION: レプリケートコピーを一定期間に 1 つだけ作成すると、データが永続的に失われるリスクがあります。オブジェクトのレプリケートコピーが 1 つしかない場合、ストレージノードに障害が発生したり、重大なエラーが発生すると、そのオブジェクトは失われます。また、アップグレードなどのメンテナンス作業中は、オブジェクトへのアクセスが一時的に失われます。

を指定する `REDUCED_REDUNDANCY`と、オブジェクトを最初に取り込んだときに作成されるコピー数にのみ影響します。オブジェクトがアクティブなILMポリシーで評価される際に作成されるオブジェクトのコピー数には影響せず、StorageGRIDシステムでデータが格納される際の冗長性レベルが低下することもありません。


NOTE: S3 Object Lockが有効なバケットにオブジェクトを取り込む場合、この `REDUCED_REDUNDANCY`オプションは無視されます。従来の準拠バケットにオブジェクトを取り込む場合、オプションを指定すると `REDUCED_REDUNDANCY`エラーが返されます。StorageGRID では、常にデュアルコミットの取り込みが実行され、コンプライアンス要件が満たされます。



== サポートされる要求ヘッダー

次の要求ヘッダーがサポートされています。

* `Content-Type`
* `x-amz-checksum-algorithm`
+
現時点では、のSHA256値のみが `x-amz-checksum-algorithm`サポートされています。

* `x-amz-meta-`に続けて、ユーザ定義のメタデータを含む名前と値のペアを指定します。
+
ユーザ定義メタデータの名前と値のペアを指定する場合、一般的な形式は次のとおりです。

+
[listing]
----
x-amz-meta-_name_: `value`
----
+
ILMルールの参照時間に*[ユーザ定義の作成時間]*オプションを使用する場合は、オブジェクトの作成日時を記録するメタデータの名前にを使用する必要があります `creation-time`。例：

+
[listing]
----
x-amz-meta-creation-time: 1443399726
----
+
の値 `creation-time`は、1970年1月1日からの秒数として評価されます。

+

NOTE: 従来の準拠が有効になっているバケットにオブジェクトを追加する場合、ユーザ定義のメタデータとして追加すること `creation-time`はできません。エラーが返されます。

* S3 オブジェクトロック要求のヘッダー：
+
** `x-amz-object-lock-mode`
** `x-amz-object-lock-retain-until-date`
** `x-amz-object-lock-legal-hold`
+
これらのヘッダーがない状態で要求を送信した場合、バケットのデフォルトの保持設定を使用して、オブジェクトバージョンの retain-date が計算されます。

+
link:../s3/use-s3-api-for-s3-object-lock.html["S3 REST APIを使用してS3オブジェクトロックを設定します"]



* SSE 要求ヘッダー：
+
** `x-amz-server-side-encryption`
** `x-amz-server-side-encryption-customer-key-MD5`
** `x-amz-server-side-encryption-customer-key`
** `x-amz-server-side-encryption-customer-algorithm`
+
<<サーバ側の暗号化を行うための要求ヘッダー>>



+

NOTE: StorageGRIDでのUTF-8文字の処理方法については、を参照してくださいlink:put-object.html["PutObject"]。





== サーバ側の暗号化を行うための要求ヘッダー

マルチパートオブジェクトをサーバ側の暗号化で暗号化するには、次の要求ヘッダーを使用します。SSE オプションと SSE-C オプションを同時に指定することはできません。

* *SSE*: StorageGRIDによって管理される一意のキーでオブジェクトを暗号化する場合は、CreateMultipartUpload要求で次のヘッダーを使用します。UploadPart要求でこのヘッダーを指定しないでください。
+
** `x-amz-server-side-encryption`


* * SSE-C *：指定および管理する一意のキーでオブジェクトを暗号化する場合は、CreateMultipartUpload要求（および後続の各UploadPart要求）でこれら3つのヘッダーをすべて使用します。
+
** `x-amz-server-side-encryption-customer-algorithm`:指定します `AES256`。
** `x-amz-server-side-encryption-customer-key`：新しいオブジェクトの暗号化キーを指定します。
** `x-amz-server-side-encryption-customer-key-MD5`：新しいオブジェクトの暗号化キーのMD5ダイジェストを指定します。





CAUTION: 指定した暗号化キーが格納されることはありません。暗号化キーを紛失すると、対応するオブジェクトが失われます。ユーザ指定のキーを使用してオブジェクトデータを保護する前に、の考慮事項を確認してくださいlink:using-server-side-encryption.html["サーバ側の暗号化を使用する"]。



== サポートされない要求ヘッダーです

次の要求ヘッダーはサポートされていません。

* `x-amz-website-redirect-location`
+
 `x-amz-website-redirect-location`ヘッダーが返され `XNotImplemented`ます。





== バージョン管理

マルチパートアップロードは、アップロードの開始、アップロードのリストの表示、パートのアップロード、アップロードしたパートのアセンブル、およびアップロードの完了の個別の処理に分けられます。CompleteMultipartUpload処理が実行されると、オブジェクトが作成されます（該当する場合はバージョン管理されます）。
