---
permalink: s3/object-versioning.html 
sidebar: sidebar 
keywords: object version, object versioning 
summary: オブジェクトの複数のバージョンを保持する場合は、バケットのバージョン管理の状態を設定できます。バケットのバージョン管理を有効にすると、オブジェクトが誤って削除されないように保護したり、以前のバージョンのオブジェクトを読み出してリストアしたりできます。 
---
= オブジェクトのバージョン管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
各オブジェクトの複数のバージョンを保持する場合は、バケットのバージョン管理状態を設定できます。バケットのバージョン管理を有効にすると、オブジェクトが誤って削除されないように保護したり、以前のバージョンのオブジェクトを読み出してリストアしたりできます。

StorageGRID システムでは、バージョン管理のほとんどの機能をサポートしていますが、いくつかの制限事項があります。StorageGRIDでは、オブジェクトごとに最大10、000個のバージョンがサポートされます。

オブジェクトのバージョン管理は、 StorageGRID の情報ライフサイクル管理（ ILM ）または S3 バケットのライフサイクル設定と組み合わせることができます。バージョン管理はバケットごとに明示的に有効にする必要があります。バケットでバージョン管理を有効にすると、バケットに追加される各オブジェクトにバージョンIDが割り当てられ、このIDがStorageGRIDシステムによって生成されます。

MFA （多要素認証） Delete の使用はサポートされていません。


NOTE: バージョン管理は、 StorageGRID バージョン 10.3 以降で作成されたバケットでのみ有効にすることができます。



== ILM とバージョン管理

ILM ポリシーはオブジェクトの各バージョンに適用されます。ILM のスキャン処理では、すべてのオブジェクトが継続的にスキャンされ、現在の ILM ポリシーに照らして再評価されます。ILM ポリシーに対する変更は、それまでに取り込まれたすべてのオブジェクトに適用されます。バージョン管理が有効になっている場合は、それまでに取り込まれたバージョンも対象にILM のスキャン処理により、過去に取り込まれたオブジェクトに変更後の新しい ILM の内容が適用さ

バージョン管理が有効なバケット内のS3オブジェクトについては、バージョン管理のサポートにより、参照時間に「noncurrent time」を使用するILMルールを作成できます（の「Apply this rule to older object versions only？」という質問に対して* Yes *を選択しますlink:../ilm/create-ilm-rule-enter-details.html["ILMルール作成ウィザードのステップ1"]）。オブジェクトが更新されると、それまでのバージョンは noncurrent になります。「noncurrent time」フィルタを使用すると、以前のバージョンのオブジェクトによるストレージへの影響を軽減するポリシーを作成できます。


NOTE: マルチパートアップロード処理を使用してオブジェクトの新しいバージョンをアップロードすると、オブジェクトの元のバージョンの noncurrent の時間には、マルチパートアップロードの完了時ではなく、新しいバージョンのマルチパートアップロードが作成された時点が反映されます。ただし、オリジナルバージョンの最新でない時間は、現行バージョンの時間よりも数時間 ~ 数日早い場合があります。

.関連情報
* link:../ilm/how-objects-are-deleted.html#delete-s3-versioned-objects["S3 バージョン管理オブジェクトの削除方法"]
* link:../ilm/example-4-ilm-rules-and-policy-for-s3-versioned-objects.html["S3 バージョン管理オブジェクトの ILM ルールとポリシー（例 4 ）"]です。

