---
permalink: s3/operations-on-buckets.html 
sidebar: sidebar 
keywords: bucket, buckets, operations on buckets 
summary: StorageGRID システムは、S3 テナントアカウントごとに最大 20,000 個のバケットをサポートします。 
---
= StorageGRIDにおけるS3バケットの操作と実装の詳細
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システムは、S3 テナントアカウントごとに最大 20,000 個のバケットをサポートします。

各グリッドには、最大100,000個のバケットを含めることができます。

複数のテナントがそれぞれ最大5,000個のバケットを持つ場合、グリッド内の各ストレージノードは最低64 GBのRAMを搭載する必要があります。

バケット名の制限は AWS US Standard リージョンの制限に従いますが、S3 仮想ホスト型リクエストをサポートするために、さらに DNS 命名規則に基づいて制限する必要があります。

詳細については、以下を参照してください。

* https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html["Amazon Simple Storage Serviceユーザガイド：バケットのクォータ、制限事項"^]
* link:../admin/configuring-s3-api-endpoint-domain-names.html["S3エンドポイントのドメイン名を設定"]


ListObjects (GET Bucket) および ListObjectVersions (GET Bucket object versions) オペレーションはStorageGRIDをサポートしますlink:consistency.html["整合性の値"]。

個々のバケットについて、最終アクセス時刻の更新が有効になっているか無効になっているかを確認できます。link:get-bucket-last-access-time-request.html["GET Bucket last access time のように指定します"]を参照してください。

次の表に、 StorageGRID での S3 REST API バケット処理の実装方法を示します。これらの処理を実行するには、アカウントに必要なアクセスクレデンシャルが付与されている必要があります。

[cols="1a,3a"]
|===
| 操作 | インプリメンテーション 


 a| 
CreateBucket
 a| 
新しいバケットを作成します。バケットを作成すると、そのバケットの所有者になります。

*注*：S3ディレクトリバケットはサポートされていません。

* バケット名は次のルールを満たす必要があります。
+
** StorageGRID システム全体で（テナントアカウント内だけではなく）一意である必要があります。
** DNS に準拠している必要があります。
** 3文字以上63文字以下にする必要があります。
** 1 つ以上のラベルを連続して指定できます。隣接するラベルはピリオドで区切ります。各ラベルの先頭と末尾の文字は小文字のアルファベットか数字にする必要があり、使用できる文字は小文字のアルファベット、数字、ハイフンのみです。
** テキスト形式の IP アドレスのようにはできません。
** 仮想ホスト形式の要求でピリオドを使用しないでください。ピリオドを使用すると、サーバワイルドカード証明書の検証で原因 の問題が発生します。


* デフォルトではリージョン内にバケットが作成され `us-east-1`ますが、要求の本文のrequest要素を使用して別のリージョンを指定できます `LocationConstraint`。要素を使用する場合 `LocationConstraint`は、Grid Managerまたはグリッド管理APIを使用して定義されたリージョンの正確な名前を指定する必要があります。使用するリージョン名がわからない場合は、システム管理者にお問い合わせください。
+
*注*：CreateBucketリクエストで StorageGRID に定義されていないリージョンを使用すると、エラーが発生します。

*  `x-amz-bucket-object-lock-enabled`リクエストヘッダーを含めることで、S3 Object Lockを有効にしたバケットを作成できます。link:../s3/use-s3-api-for-s3-object-lock.html["S3 REST APIを使用してS3オブジェクトロックを設定します"]を参照してください。
+
S3オブジェクトロックにはバケットのバージョン管理が必要ですが、S3オブジェクトロックを有効にしてバケットを作成すると、自動的に有効になります。

+
S3オブジェクトロックは、バケット作成時または後から有効にすることができます。





 a| 
DeleteBucket
 a| 
バケットを削除します。



 a| 
DeleteBucketCors
 a| 
バケットのCORS設定を削除します。



 a| 
DeleteBucketEncryption
 a| 
バケットからデフォルトの暗号化を削除します。既存の暗号化オブジェクトは暗号化されたままですが、バケットに追加された新しいオブジェクトは暗号化されません。



 a| 
DeleteBucketLifecycle
 a| 
バケットからライフサイクル設定を削除します。link:create-s3-lifecycle-configuration.html["S3 ライフサイクル設定を作成する"]を参照してください。



 a| 
DeleteBucketPolicy
 a| 
バケットに関連付けられているポリシーを削除します。



 a| 
DeleteBucketReplication
 a| 
バケットに関連付けられているレプリケーション設定を削除します。



 a| 
DeleteBucketTagging
 a| 
サブリソースを使用し `tagging`てバケットからすべてのタグを削除します。

*注意*：このバケットにデフォルト以外の ILM ポリシータグが設定されている場合、値が割り当てられた `NTAP-SG-ILM-BUCKET-TAG`バケットタグが存在します。 `NTAP-SG-ILM-BUCKET-TAG`バケットタグが存在する場合は、DeleteBucketTaggingリクエストを発行しないでください。代わりに、 `NTAP-SG-ILM-BUCKET-TAG`タグとその割り当てられた値のみを指定してPutBucketTaggingリクエストを発行し、バケットから他のすべてのタグを削除してください。 `NTAP-SG-ILM-BUCKET-TAG`バケットタグを変更または削除しないでください。



 a| 
GetBucketAcl
 a| 
バケットの所有者にバケットへのフルアクセスがあることを示す応答が返され、所有者のID、表示名、および権限が表示されます。



 a| 
GetBucketCors
 a| 
バケットの設定を返し `cors`ます。



 a| 
GetBucketEncryptionの略
 a| 
バケットのデフォルトの暗号化設定を返します。



 a| 
GetBucketLifecycleConfiguration

（以前のGET Bucket lifecycle）
 a| 
バケットのライフサイクル構成を返します。link:create-s3-lifecycle-configuration.html["S3 ライフサイクル設定を作成する"]を参照してください。



 a| 
GetBucketLocation
 a| 
 `LocationConstraint`要素を使用して CreateBucket リクエストで設定されたリージョンを返します。バケットのリージョンが `us-east-1`（デフォルト）の場合、 `LocationConstraint`には空の値が返されます。



 a| 
GetBucketNotificationConfigurationを参照してください

（以前の名前のGET Bucket通知）
 a| 
バケットに関連付けられている通知設定を返します。



 a| 
GetBucketPolicy
 a| 
バケットに関連付けられているポリシーを返します。



 a| 
GetBucketReplicationの略
 a| 
バケットに関連付けられているレプリケーション設定を返します。



 a| 
GetBucketTagging
 a| 
サブリソースを使用し `tagging`てバケットのすべてのタグを返します。

*注意*：このバケットにデフォルト以外の ILM ポリシータグが設定されている場合、値が割り当てられた `NTAP-SG-ILM-BUCKET-TAG`バケットタグが存在します。このタグは変更または削除しないでください。



 a| 
GetBucketVersioning
 a| 
この実装では、サブリソースを使用して `versioning`バケットのバージョン管理の状態を返します。

* _blank_：バージョン管理が一度も有効になっていない（バケットは「バージョン管理されていない」）
* 有効：バージョン管理が有効になっています
* 中断：バージョン管理は以前有効になっていて、中断されています




 a| 
GetObjectLockConfigurationの略
 a| 
バケットのデフォルトの保持モードとデフォルトの保持期間（設定されている場合）を返します。

link:../s3/use-s3-api-for-s3-object-lock.html["S3 REST APIを使用してS3オブジェクトロックを設定します"]を参照してください。



 a| 
ヘッドバケット
 a| 
バケットが存在し、そのバケットにアクセスする権限があるかどうかを確認します。

この処理から返される情報は次の

* `x-ntap-sg-bucket-id`：バケットのUUID（UUID形式）。
* `x-ntap-sg-trace-id`：関連付けられた要求の一意のトレースID。




 a| 
listObjectsおよびListObjectsV2

（以前の名前はGET Bucket）
 a| 
バケット内のオブジェクトの一部またはすべて（最大1、000）を返します。オブジェクトのストレージクラスには、ストレージクラスオプションを使用してオブジェクトを取り込んだ場合でも、次の2つの値のいずれかが設定され `REDUCED_REDUNDANCY`ます。

* `STANDARD`オブジェクトがストレージノードで構成されるストレージプールに格納されていることを示します。
* `GLACIER`が表示されます。これは、クラウドストレージプールで指定された外部バケットにオブジェクトが移動されたことを示します。


バケットに同じプレフィックスの削除済みキーが大量に含まれている場合は、キーを含まないキーが応答に含まれることがあります `CommonPrefixes`。

HeadObject および ListObject リクエストの場合、 StorageGRID は異なる精度で LastModified タイムスタンプを返しますが、AWS は同じ精度でタイムスタンプを返します。次の例をご覧ください。

* StorageGRIDヘッドオブジェクト: "LastModified": "2024-09-26T16:43:24+00:00"
* StorageGRIDリストオブジェクト: "LastModified": "2024-09-26T16:43:24.931000+00:00"
* AWS ヘッドオブジェクト: "LastModified": "2023-10-17T00:19:54+00:00"
* AWS リストオブジェクト: "LastModified": "2023-10-17T00:19:54+00:00"




 a| 
ListObjectVersions

（以前のGET Bucket Object versions）
 a| 
バケットに対する読み取りアクセスが許可されている場合、サブリソースを指定してこの処理を実行すると、 `versions`バケット内のオブジェクトのすべてのバージョンのメタデータがリストされます。



 a| 
PutBucketCorsの略
 a| 
クロスオリジン要求を処理できるように、バケットのCORS設定を設定します。Cross-Origin Resource Sharing （ CORS ）は、あるドメインのクライアント Web アプリケーションが別のドメインのリソースにアクセスできるようにするセキュリティ機能です。たとえば、という名前のS3バケットを使用してグラフィックを格納するとし `images`ます。バケットのCORS設定を設定すると `images`、そのバケット内の画像をWebサイトに表示できるように `+http://www.example.com+`なります。



 a| 
PutBucketEncryptionの略
 a| 
既存のバケットのデフォルトの暗号化状態を設定します。バケットレベルの暗号化が有効な場合は、バケットに追加されたすべての新しいオブジェクトが暗号化されます。 StorageGRID では、 StorageGRID で管理されるキーによるサーバ側の暗号化がサポートされます。サーバ側の暗号化設定ルールを指定する場合は、パラメータをに `AES256`設定し `SSEAlgorithm`、パラメータは使用しないで `KMSMasterKeyID`ください。

オブジェクトのアップロード要求ですでに暗号化が指定されている場合（要求に要求ヘッダーが含まれている場合）は、バケットのデフォルトの暗号化設定は無視され `x-amz-server-side-encryption-*`ます。



 a| 
PutBucketLifecycleConfiguration

（以前のPUT Bucket lifecycle）
 a| 
バケットの新しいライフサイクル設定を作成するか、既存のライフサイクル設定と置き換えます。StorageGRID では、 1 つのライフサイクル設定で最大 1 、 000 個のライフサイクルルールがサポートされます。各ルールには、次の XML 要素を含めることができます。

* 有効期限（日数、日付、ExpiredObjectDeleteMarker）
* NoncurrentVersionExpiration（NewerNoncurrentVersions、NoncurrentDays）
* フィルタ（プレフィックス、タグ）
* ステータス
* ID


StorageGRID では、次のアクションはサポートされません。

* AbortIncompleteMultipartUpload
* 移行


link:create-s3-lifecycle-configuration.html["S3 ライフサイクル設定を作成する"]を参照してください。バケットライフサイクルの有効期限アクションがILM配置指示とどのように相互作用するかを理解するには、link:../ilm/how-ilm-operates-throughout-objects-life.html["オブジェクトのライフサイクル全体にわたる ILM の動作"]を参照してください。

* 注：バケットライフサイクル設定は S3 オブジェクトロックが有効なバケットで使用できますが、従来の準拠バケットではバケットライフサイクル設定がサポートされません。



 a| 
PutBucketNotificationConfigurationの略

（以前の名前のPUT Bucket通知）
 a| 
要求の本文に含まれる通知設定XMLを使用してバケットの通知を設定します。実装に関する次の詳細事項に注意してください。

* StorageGRID は、送信先として Amazon Simple Notification Service (Amazon SNS) トピック、Kafka トピック、または Webhook エンドポイントをサポートします。  Simple Queue Service (SQS) または AWS Lambda エンドポイントはサポートされていません。
* 通知のデスティネーションは、 StorageGRID エンドポイントの URN として指定する必要があります。エンドポイントは、 Tenant Manager またはテナント管理 API を使用して作成できます。
+
通知設定が機能するためには、エンドポイントが存在している必要があります。エンドポイントが存在しない場合は `400 Bad Request`、コードとともにエラーが返され `InvalidArgument`ます。

* 次のイベントタイプに対して通知を設定することはできません。これらのイベントタイプは * サポートされていません。
+
** `s3:ReducedRedundancyLostObject`
** `s3:ObjectRestore:Completed`


* StorageGRID から送信されるイベント通知は標準のJSON形式を使用しますが、次のリストに示すように、一部のキーが含まれず、他のキーには特定の値が使用されます。
+
** * eventSource*
+
`sgws:s3`

** * awsRegion *
+
含まれません

** * x-amz-id-2 *
+
含まれません

** * arn *
+
`urn:sgws:s3:::bucket_name`







 a| 
PutBucketPolicy
 a| 
バケットに適用されるポリシーを設定します。link:use-access-policies.html["バケットとグループのアクセスポリシーを使用"]を参照してください。



 a| 
PutBucketReplicationの略
 a| 
要求の本文に含まれるレプリケーション設定XMLを使用してバケットを設定しますlink:../tenant/understanding-cloudmirror-replication-service.html["StorageGRID CloudMirrorレプリケーション"]。CloudMirror レプリケーションについては、実装に関する次の詳細事項に注意してください。

* StorageGRID はレプリケーション構成の V1 のみをサポートしています。つまり、StorageGRID はルールに対して `Filter`要素の使用をサポートしておらず、オブジェクトバージョンの削除については V1 の規約に従います。詳細については、 https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication-add-config.html["Amazon Simple Storage Serviceユーザガイド：レプリケーションの設定"^]を参照してください。
* バケットレプリケーションは、バージョン管理されているバケットでもバージョン管理されていないバケットでも設定でき
* レプリケーション設定 XML の各ルールで異なるデスティネーションバケットを指定できます。1 つのソースバケットを複数のデスティネーションバケットにレプリケートできます。
* 宛先バケットは、Tenant Manager またはTenant Management APIで指定されているStorageGRIDエンドポイントのURNとして指定する必要があります。link:../tenant/configuring-cloudmirror-replication.html["CloudMirror レプリケーションを設定します"]を参照してください。
+
レプリケーション設定が機能するためには、エンドポイントが存在している必要があります。エンドポイントが存在しない場合、要求はとして失敗し `400 Bad Request`ます。次のエラーメッセージが表示されます。 `Unable to save the replication policy. The specified endpoint URN does not exist: _URN_.`

* 設定XMLでを指定する必要はありません `Role`。この値は StorageGRID では使用されず、送信されても無視されます。
* 設定XMLでストレージクラスを省略した場合、StorageGRIDではデフォルトでストレージクラスが使用され `STANDARD`ます。
* ソースバケットからオブジェクトを削除する場合、またはソースバケット自体を削除する場合、クロスリージョンレプリケーションは次のように動作します。
+
** レプリケートの前にオブジェクトまたはバケットを削除した場合、オブジェクトまたはバケットはレプリケートされず、通知も送信されません。
** レプリケートのあとにオブジェクトまたはバケットを削除すると、 StorageGRID は、 V1 のクロスリージョンレプリケーションに対する Amazon S3 の通常の削除動作に従います。






 a| 
PutBucketTaggingの略
 a| 
サブリソースを使用して、 `tagging`バケットの一連のタグを追加または更新します。バケットタグを追加する場合は、次の制限事項に注意してください。

* StorageGRID と Amazon S3 はどちらもバケットごとに最大 50 個のタグをサポートします。
* バケットに関連付けられているタグには、一意のタグキーが必要です。タグキーには Unicode 文字を 128 文字まで使用できます。
* タグ値には、 Unicode 文字を 256 文字以内で指定します。
* キーと値では大文字と小文字が区別されます。


*注意*：このバケットにデフォルト以外の ILM ポリシータグが設定されている場合、値が割り当てられた `NTAP-SG-ILM-BUCKET-TAG`バケットタグが存在します。 `NTAP-SG-ILM-BUCKET-TAG`バケットタグが、割り当てられた値とともにすべての PutBucketTagging リクエストに含まれていることを確認してください。このタグは変更または削除しないでください。

*注*：この処理を実行すると、バケットにすでに設定されている現在のタグが上書きされます。セットから既存のタグを省略すると、それらのタグはバケットから削除されます。



 a| 
PutBucketVersioning
 a| 
サブリソースを使用 `versioning`して、既存のバケットのバージョン管理状態を設定します。バージョン管理の状態は、次のいずれかの値に設定できます。

* Enabled ：バケット内のオブジェクトに対してバージョン管理を有効にします。バケットに追加されるすべてのオブジェクトに、一意のバージョン ID が割り当てられます。
* Suspended ：バケット内のオブジェクトに対してバージョン管理を無効にします。バケットに追加されたすべてのオブジェクトにバージョンIDが割り当てられ `null`ます。




 a| 
PutObjectLockConfiguration
 a| 
* バケットのデフォルトの保持モードとデフォルトの保持期間を設定または削除します。
* グリッド管理者が許可を与えている場合、既存のバケットに対してS3オブジェクトロックを有効にします。


デフォルトの保持期間が変更された場合、既存のオブジェクトバージョンの保持期限は変更されず、新しいデフォルトの保持期間を使用して再計算されることはありません。

詳細については、link:../s3/use-s3-api-for-s3-object-lock.html["S3 REST APIを使用してS3オブジェクトロックを設定します"]を参照してください。

|===