---
permalink: s3/recommendations-for-implementing-s3-rest-api.html 
sidebar: sidebar 
keywords: implement s3 rest api 
summary: StorageGRID で使用するために S3 REST API を実装する場合は、次の推奨事項を考慮してください。 
---
= S3 REST API を実装する際の推奨事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID で使用するために S3 REST API を実装する場合は、次の推奨事項を考慮してください。



== 存在しないオブジェクトに対する HEAD の推奨事項

アプリケーションが、オブジェクトが実際に存在するとは思わないパスにオブジェクトが存在するかどうかを定期的にチェックする場合は、「available」を使用する必要がありますlink:consistency.html["一貫性"]。たとえば、アプリケーションがPUTを実行する前に特定の場所に移動する場合は、「available」整合性を使用する必要があります。

そうしないと、同じサイトに複数のストレージノードが使用できない場合やリモートサイトに到達できない場合に、HEAD処理でオブジェクトが見つからないと「500 Internal Server Error」が大量に返されることがあります。

要求を使用して各バケットに「available」整合性を設定することlink:put-bucket-consistency-request.html["PUT Bucket consistency"]も、個 々 のAPI処理の要求ヘッダーで整合性を指定することもできます。



== オブジェクトキーの推奨事項

オブジェクトキー名については、バケットが最初に作成された日時に基づいて次の推奨事項に従ってください。

.StorageGRID 11.4以前で作成されたバケット
* オブジェクトキーの最初の4文字にランダムな値を使用しないでください。これは、 AWS が以前に推奨していたキープレフィックスの推奨事項とは異なります。代わりに、など、ランダムではなく一意ではないプレフィックスを使用します `image`。
* 以前のAWSの推奨事項に従ってキープレフィックスにランダムな一意の文字を使用する場合は、オブジェクトキーの前にディレクトリ名を付けます。つまり、次の形式を使用します。
+
`mybucket/mydir/f8e3-image3132.jpg`

+
次の形式は使用しないでください。

+
`mybucket/f8e3-image3132.jpg`



.StorageGRID 11.4以降で作成されたバケット
パフォーマンスのベストプラクティスに合わせてオブジェクトキー名を制限する必要はありません。ほとんどの場合、オブジェクトキー名の最初の4文字にはランダムな値を使用できます。


TIP: ただし、短期間ですべてのオブジェクトを継続的に削除するS3ワークロードは例外です。このユースケースのパフォーマンスへの影響を最小限に抑えるには、キー名の先頭部分を数千個のオブジェクトごとに、日付などの値を変更します。たとえば、S3クライアントが1秒あたり2、000個のオブジェクトを書き込むのが一般的で、ILMまたはバケットライフサイクルポリシーで3日後にすべてのオブジェクトが削除されるとします。パフォーマンスへの影響を最小限に抑えるには、次のようなパターンを使用してキーに名前を付けます。 `/mybucket/mydir/_yyyymmddhhmmss_-_random_UUID_.jpg`



== 「範囲読み取り」に関する推奨事項

が有効になっている場合link:../admin/configuring-stored-object-compression.html["格納オブジェクトを圧縮するグローバルオプション"]は、返されるバイト数の範囲を指定するGetObject処理をS3クライアントアプリケーションで実行しないでください。これらの「範囲読み取り」処理は効率的ではありません。StorageGRIDでは、要求されたバイトにアクセスするためにオブジェクトの圧縮を実質的に解除する必要があるためです。非常に大きなオブジェクトから小さい範囲のバイト数を要求するGetObject処理は特に非効率的です。たとえば、50GBの圧縮オブジェクトから10MBの範囲を読み取る処理は非効率的です。

圧縮オブジェクトから範囲を読み取ると、クライアント要求がタイムアウトする可能性があります。


NOTE: オブジェクトを圧縮する必要があり、クライアントアプリケーションが範囲読み取りを使用する必要がある場合は、アプリケーションの読み取りタイムアウトを増やしてください。
