---
permalink: monitor/access-snmp-mib.html 
sidebar: sidebar 
keywords: mib, snmp, monitoring 
summary: MIBファイルには、グリッド内のノードの管理対象リソースとサービスのプロパティの定義と情報が含まれています。StorageGRID のオブジェクトと通知を定義するMIBファイルにアクセスできます。これらのファイルは、グリッドの監視に役立ちます。 
---
= MIBファイルにアクセスします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MIBファイルには、グリッド内のノードの管理対象リソースとサービスのプロパティの定義と情報が含まれています。StorageGRID のオブジェクトと通知を定義するMIBファイルにアクセスできます。これらのファイルは、グリッドの監視に役立ちます。

SNMPおよびMIBファイルの詳細については、を参照してくださいlink:using-snmp-monitoring.html["SNMP による監視を使用する"]。



== MIBファイルにアクセスします

MIBファイルにアクセスする手順は、次のとおりです。

.手順
. *構成* > *監視* > *SNMP エージェント* を選択します。
. [SNMP agent]ページで、ダウンロードするファイルを選択します。
+
** * NETAPP-STORAGEGRID-MIB.txt *：すべての管理ノードでアクセス可能なアラートテーブルと通知（トラップ）を定義します。
** * ES-NetApp-06-MIB.mib *：Eシリーズベースのアプライアンスのオブジェクトと通知を定義します。
** * mib_1_10.zip *：BMCインターフェイスを使用するアプライアンスのオブジェクトと通知を定義します。
+

TIP: また、任意のStorageGRIDノードの次の場所にあるMIBファイルにアクセスすることもできます。 `/usr/share/snmp/mibs`



. MIBファイルからStorageGRID OIDを抽出するには、次の手順を実行します。
+
.. StorageGRID MIBのルートのOIDを取得します。
+
`root@user-adm1:~ # snmptranslate -On -IR storagegrid`

+
結果： `.1.3.6.1.4.1.789.28669` (`28669`は常にStorageGRIDのOID）

.. ツリー全体のStorageGRID OIDをgrepで指定します（を使用して `paste`行を結合）。
+
`root@user-adm1:~ # snmptranslate -Tso | paste -d " " - - | grep 28669`

+

TIP: この `snmptranslate`コマンドには、MIBの探索に役立つ多くのオプションがあります。このコマンドは、任意のStorageGRID ノードで使用できます。







== MIBファイルの内容

すべてのオブジェクトはStorageGRID OIDの下にあります。

[cols="1a,1a,2a"]
|===
| オブジェクト名 | オブジェクトID（OID） | 製品説明 


| .iso.org.dod.internet（英語）+private.enterprises。+ネットアップストレージグリッド | .1.3.6.1.4.1.789.28669  a| 
NetApp StorageGRIDエンティティ用のMIBモジュール。

|===


== MIBオフシエクト

[cols="1a,1a,1a,1a,1a,2a"]
|===
| オブジェクト名 | オブジェクトID（OID） | タイプ | アクセス | MIBモジュール | 製品説明 


| activeAlertCount | 1.3.6.1.4.1.+789.28669.1.3  a| 
整数32
 a| 
read-only
 a| 
NETAPP-STORAGEGRID-MIB
 a| 
activeAlertTable内のアクティブなアラートの数。



| activeAlertTableの略 | 1.3.6.1.4.1.+789.28669.1.4  a| 
ActiveAlertEntryのシーケンス
 a| 
アクセス不可
 a| 
NETAPP-STORAGEGRID-MIB
 a| 
StorageGRID のアクティブなアラートのテーブル。



| アクティブアラートエントリ | .1.3.6.1.4.1.  + 789.28669.1.4.1  a| 
順序
 a| 
アクセス不可
 a| 
NETAPP-STORAGEGRID-MIB
 a| 
アラート ID でインデックス付けされた単一のStorageGRIDアラート。



| activeAlertId | 1.3.6.1.4.1.+789.28669.1.4.1.1  a| 
オクテット文字列
 a| 
read-only
 a| 
NETAPP-STORAGEGRID-MIB
 a| 
アラートのID。現在アクティブなアラートのセット内でのみ一意です。



| activeAlertNameの略 | 1.3.6.1.4.1.+789.28669.1.4.1.2  a| 
オクテット文字列
 a| 
read-only
 a| 
NETAPP-STORAGEGRID-MIB
 a| 
アラートの名前。



| activeAlertInstanceの略 | 1.3.6.1.4.1.+789.28669.1.4.1.3  a| 
オクテット文字列
 a| 
read-only
 a| 
NETAPP-STORAGEGRID-MIB
 a| 
アラートを生成したエンティティの名前（通常はノード名）。



| activeAlertSeverityの略 | 1.3.6.1.4.1.+789.28669.1.4.1.4  a| 
オクテット文字列
 a| 
read-only
 a| 
NETAPP-STORAGEGRID-MIB
 a| 
アラートの重大度。



| activeAlertStartTimeの略 | 1.3.6.1.4.1.+789.28669.1.4.1.5  a| 
日時
 a| 
read-only
 a| 
NETAPP-STORAGEGRID-MIB
 a| 
アラートがトリガーされた時刻。

|===