---
permalink: monitor/alerts-reference.html 
sidebar: sidebar 
keywords: alerts reference 
summary: このリファレンスでは、Grid Managerに表示されるデフォルトアラートを示します。推奨される対処方法は、受信したアラートメッセージに記載されています。 
---
= アラート一覧
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このリファレンスでは、Grid Managerに表示されるデフォルトアラートを示します。推奨される対処方法は、受信したアラートメッセージに記載されています。

必要に応じて、システムの管理方法に合わせてカスタムのアラートルールを作成できます。

一部のデフォルトアラートではが使用されlink:commonly-used-prometheus-metrics.html["Prometheus 指標"]ます。



== アプライアンスのアラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
アプライアンスのバッテリの有効期間が終了し
 a| 
アプライアンスのストレージコントローラのバッテリの有効期間が終了しました。



 a| 
アプライアンスのバッテリに問題があります
 a| 
アプライアンスのストレージコントローラのバッテリに障害が発生しました。



 a| 
アプライアンスバッテリの学習容量が不足しています
 a| 
アプライアンスのストレージコントローラのバッテリで学習容量が不足しています。



 a| 
アプライアンスバッテリの有効期限が近づいています
 a| 
アプライアンスのストレージコントローラのバッテリの有効期限が近づいています。



 a| 
アプライアンスのバッテリが取り外されました
 a| 
アプライアンスのストレージコントローラのバッテリがありません。



 a| 
アプライアンスのバッテリが高温になっています
 a| 
アプライアンスのストレージコントローラのバッテリが過熱しています。



 a| 
アプライアンスの BMC 通信エラー
 a| 
ベースボード管理コントローラ（ BMC ）との通信が失われました。



 a| 
アプライアンスのブートデバイス障害が検出されました
 a| 
アプライアンスのブートデバイスで問題が検出されました。



 a| 
アプライアンスキャッシュバックアップデバイスに障害が発生しました
 a| 
永続的キャッシュバックアップデバイスで障害が発生しました。



 a| 
アプライアンスキャッシュバックアップデバイスに十分な容量がありません
 a| 
キャッシュバックアップデバイスに十分な容量がありません。



 a| 
アプライアンスのキャッシュ・バックアップ・デバイスの書き込み保護
 a| 
キャッシュバックアップデバイスは書き込み保護されています。



 a| 
アプライアンスのキャッシュメモリサイズが一致しません
 a| 
アプライアンスの 2 台のコントローラは、キャッシュサイズが異なります。



 a| 
アプライアンスCMOSバッテリ障害
 a| 
アプライアンスのCMOSバッテリで問題が検出されました。



 a| 
アプライアンスコンピューティングコントローラシャーシの温度が高すぎます
 a| 
StorageGRID アプライアンスのコンピューティングコントローラの温度が公称のしきい値を超えました。



 a| 
アプライアンスのコンピューティングコントローラの CPU 温度が高すぎます
 a| 
StorageGRID アプライアンスのコンピューティングコントローラの CPU 温度が公称のしきい値を超えました。



 a| 
アプライアンスのコンピューティングコントローラを確認する必要があります
 a| 
StorageGRID アプライアンスのコンピューティングコントローラでハードウェア障害が検出されました。



 a| 
アプライアンスコンピューティングコントローラの電源装置 A に問題があります
 a| 
コンピューティングコントローラの電源装置Aに問題があります。



 a| 
アプライアンスコンピューティングコントローラの電源装置 B に問題があります
 a| 
コンピューティングコントローラの電源装置 B に問題があります。



 a| 
アプライアンスコンピューティングハードウェアモニタのサービスが停止する
 a| 
ストレージハードウェアのステータスを監視するサービスが停止しました。



 a| 
アプライアンスのDASドライブが1日に書き込まれるデータの制限を超えています
 a| 
ドライブに毎日大量のデータが書き込まれているため、保証が無効になる可能性があります。



 a| 
アプライアンスのDASドライブ障害が検出されました
 a| 
アプライアンスの直接接続型ストレージ（DAS）ドライブで問題が検出されました。



 a| 
アプライアンスDASドライブが間違ったスロットまたはノードにあります
 a| 
直接接続ストレージ (DAS) ドライブが間違ったスロットまたはノードに挿入されています



 a| 
アプライアンスのDASドライブのロケーターライトが点灯
 a| 
アプライアンスストレージノード内の1つ以上の直接接続型ストレージ（DAS）ドライブのドライブロケーターライトが点灯しています。



 a| 
アプライアンスDASドライブのリビルド
 a| 
直接接続型ストレージ（DAS）ドライブのリビルド中。これは、最近交換または取り外し/再挿入された場合に想定される現象です。



 a| 
アプライアンスのファン障害が検出されました
 a| 
アプライアンスのファンユニットに問題が検出されました。



 a| 
アプライアンスのファイバ・チャネル障害が検出されました
 a| 
アプライアンスストレージコントローラとコンピューティングコントローラの間でFibre Channelリンクの問題が検出されました



 a| 
アプライアンスのファイバ・チャネル HBA ポート障害
 a| 
Fibre Channel HBA ポートで障害が発生しているか、障害が発生しています。



 a| 
アプライアンスのフラッシュキャッシュドライブが最適な状態でありません
 a| 
SSD キャッシュに使用されているドライブが最適な状態でありません。



 a| 
アプライアンスインターコネクト / バッテリキャニスターが取り外されました
 a| 
インターコネクト / バッテリキャニスターがありません。



 a| 
アプライアンスの LACP ポートがありません
 a| 
StorageGRID アプライアンスのポートが LACP ボンドに参加していません。



 a| 
アプライアンスNICの障害が検出されました
 a| 
アプライアンスのネットワークインターフェイスカード（NIC）に問題が検出されました。



 a| 
アプライアンス全体の電源装置がデグレード状態になりました
 a| 
StorageGRID アプライアンスの電源が、推奨される動作電圧から逸脱しています。



 a| 
アプライアンスSANtricity OSソフトウェアの更新が必要です
 a| 
SANtricityソフトウェア バージョンは、 StorageGRIDのこのリリースに推奨される最小バージョンよりも低いです。



 a| 
アプライアンスSSDの重大な警告です
 a| 
アプライアンスSSDから重大な警告が報告されています。



 a| 
アプライアンスストレージコントローラ A の障害
 a| 
StorageGRID アプライアンスのストレージコントローラ A で障害が発生した。



 a| 
アプライアンスストレージコントローラ B の障害
 a| 
StorageGRID アプライアンスのストレージコントローラ B で障害が発生した。



 a| 
アプライアンスストレージコントローラのドライブ障害
 a| 
StorageGRID アプライアンスの 1 つ以上のドライブで障害が発生しているか、または最適な状態でありません。



 a| 
アプライアンスストレージコントローラハードウェア問題
 a| 
SANtricity ソフトウェアから、 StorageGRID アプライアンスのコンポーネントについて「 Needs Attention 」が報告されます。



 a| 
アプライアンスストレージコントローラの電源装置 A に障害が発生しました
 a| 
StorageGRID アプライアンスの電源装置 A が、推奨される動作電圧から逸脱しています。



 a| 
アプライアンスストレージコントローラの電源装置 B に障害が発生しました
 a| 
StorageGRID アプライアンスの電源装置 B が、推奨される動作電圧から逸脱しています。



 a| 
アプライアンスストレージハードウェアモニタのサービスが停止する
 a| 
ストレージハードウェアのステータスを監視するサービスが停止しました。



 a| 
アプライアンスストレージシェルフがデグレード状態になります
 a| 
ストレージアプライアンスのストレージシェルフのいずれかのコンポーネントのステータスがデグレードになっています。



 a| 
アプライアンスの温度が超過しました
 a| 
アプライアンスのストレージコントローラの公称温度または最大温度を超えました。



 a| 
アプライアンスの温度センサーが取り外されました
 a| 
温度センサーが取り外されました。



 a| 
アプライアンスUEFIセキュアブートエラー
 a| 
アプライアンスが安全にブートされていません。



 a| 
ディスク I/O が非常に遅い
 a| 
ディスクI/Oが非常に遅い場合は、グリッドのパフォーマンスに影響する可能性があります。



 a| 
ストレージアプライアンスのファンで障害が検出されました
 a| 
アプライアンスのストレージコントローラのファンユニットで問題が検出されました。



 a| 
ストレージアプライアンスストレージの接続がデグレードされました
 a| 
コンピューティングコントローラとストレージコントローラの間の接続に問題があります。



 a| 
ストレージデバイスにアクセスできません
 a| 
ストレージデバイスにアクセスできません。

|===


== 監査およびsyslogアラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
監査ログをメモリ内キューに追加しています
 a| 
ノードからローカル syslog サーバにログを送信できず、メモリ内キューがいっぱいになっています。



 a| 
外部 syslog サーバの転送エラーです
 a| 
ノードから外部 syslog サーバにログを転送できません。



 a| 
大規模な監査キュー
 a| 
監査メッセージのディスク キューがいっぱいです。この状態に対処しないと、S3 操作が失敗する可能性があります。



 a| 
ログをディスク上キューに追加しています
 a| 
ノードから外部 syslog サーバにログを転送できず、ディスク上のキューがいっぱいになっています。

|===


== バケットアラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
FabricPool バケットにサポート対象外のバケット整合性設定があります
 a| 
FabricPoolバケットでは、availableまたはstrong-siteの整合性レベルが使用されますが、この整合性レベルはサポートされていません。



 a| 
FabricPoolバケットにサポートされていないバージョン管理設定があります
 a| 
FabricPoolバケットでバージョン管理またはS3オブジェクトロックが有効になっているが、これはサポートされていない。

|===


== Cassandraアラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
Cassandra 自動コンパクターエラーです
 a| 
Cassandra 自動コンパクターでエラーが発生しました。



 a| 
Cassandra 自動コンパクターメトリックが古くなっています
 a| 
Cassandra の自動圧縮機能を説明する指標が最新ではありません。



 a| 
Cassandra 通信エラー
 a| 
Cassandra サービスを実行するノード間の通信で問題が発生しています。



 a| 
Cassandra の圧縮処理が過負荷です
 a| 
Cassandra コンパクションプロセスが過負荷状態です。



 a| 
Cassandraオーバーサイズ書き込みエラー
 a| 
内部StorageGRID プロセスがCassandraに送信した書き込み要求が大きすぎます。



 a| 
Cassandra 修復指標が最新ではありません
 a| 
Cassandra 修復ジョブを説明する指標が最新ではありません。



 a| 
Cassandra の修復の進捗が遅い
 a| 
Cassandra データベースの修復の進捗状況が遅い。



 a| 
Cassandra 修復サービスを使用できません
 a| 
Cassandra 修復サービスは使用できません。



 a| 
Cassandra テーブルが破損しています
 a| 
Cassandra がテーブルの破損を検出しました。テーブルの破損が検出されると、 Cassandra が自動的に再起動します。

|===


== クラウドストレージプールのアラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
クラウドストレージプールの接続エラー
 a| 
クラウドストレージプールの健全性チェックで、新たなエラーが 1 つ以上検出されました。



 a| 
IAM Roles Anywhereエンドエンティティ証明書の有効期限
 a| 
IAM Roles Anywhereエンドエンティティ証明書の有効期限が近づいています。

|===


== グリッド間レプリケーションのアラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
クロスグリッドレプリケーションの永続的な障害
 a| 
ユーザの介入を必要とするグリッド間レプリケーションエラーが発生しました。



 a| 
グリッド間レプリケーションリソースを使用できません
 a| 
リソースを使用できないため、グリッド間レプリケーション要求が保留になっています。

|===


== DHCPアラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
DHCP リースの期限が切れました
 a| 
ネットワークインターフェイスの DHCP リースが期限切れです。



 a| 
DHCP リースがまもなく期限切れになります
 a| 
ネットワークインターフェイスの DHCP リースがまもなく期限切れになります。



 a| 
DHCP サーバが使用できません
 a| 
DHCP サーバが使用できない。

|===


== デバッグおよびトレースアラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
パフォーマンスへの影響をデバッグします
 a| 
デバッグモードを有効にすると、システムパフォーマンスに悪影響を及ぼす可能性があります。



 a| 
トレース設定が有効になりました
 a| 
トレース構成を有効にすると、システムパフォーマンスに悪影響を及ぼす可能性があります。

|===


== EメールアラートとAutoSupport アラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
AutoSupport メッセージの送信に失敗しました
 a| 
最新のAutoSupport メッセージの送信に失敗しました。



 a| 
ドメイン名解決エラー
 a| 
StorageGRIDノードがドメイン名を解決できませんでした。



 a| 
E メール通知のエラーです
 a| 
アラートの E メール通知を送信できませんでした。



 a| 
ログアーカイブ先のバケットが見つかりません
 a| 
ログのアーカイブ先バケットが見つからないため、ログを宛先バケットにアーカイブできません。



 a| 
SNMPインフォームエラー
 a| 
トラップ送信先へのSNMPインフォーム通知の送信時にエラーが発生しました。



 a| 
SSH外部アクセスが有効
 a| 
SSH 外部アクセスが 24 時間以上有効になっています。



 a| 
SSHまたはコンソールログインが検出されました
 a| 
過去24時間以内に、ユーザーがWebコンソールまたはSSHを使用してログインしました。

|===


== イレイジャーコーディング（EC）アラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
EC のリバランシングに失敗しました
 a| 
ECリバランシング手順 が失敗したか、停止しました。



 a| 
EC の修復エラー
 a| 
ECデータの修復ジョブが失敗したか停止しました。



 a| 
EC の修復が停止した
 a| 
ECデータの修復ジョブが停止しました。



 a| 
イレイジャーコーディングフラグメント検証エラー
 a| 
イレイジャーコーディングフラグメントは検証できなくなりました。破損したフラグメントは修復されない可能性があります。

|===


== 証明書の有効期限に関するアラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
管理プロキシCA証明書の有効期限
 a| 
管理プロキシサーバのCAバンドル内の1つ以上の証明書の有効期限が近づいています。



 a| 
クライアント証明書の有効期限
 a| 
1つ以上のクライアント証明書の有効期限が近づいています。



 a| 
S3 のグローバル サーバー証明書の有効期限
 a| 
S3 のグローバル サーバー証明書の有効期限が近づいています。



 a| 
ロードバランサエンドポイント証明書の有効期限
 a| 
1 つ以上のロードバランサエンドポイント証明書の有効期限が近づいています。



 a| 
管理インターフェイスのサーバ証明書の有効期限
 a| 
管理インターフェイスで使用されるサーバ証明書の有効期限が近づいています。



 a| 
外部 syslog CA 証明書の有効期限
 a| 
外部 syslog サーバ証明書への署名に使用される認証局（ CA ）証明書の有効期限が近づいています。



 a| 
外部 syslog クライアント証明書の有効期限
 a| 
外部 syslog サーバのクライアント証明書の有効期限が近づいています。



 a| 
外部 syslog サーバ証明書の有効期限
 a| 
外部 syslog サーバから提供されるサーバ証明書の有効期限が近づいています。

|===


== グリッドネットワークのアラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
Grid ネットワーク MTU が一致しません
 a| 
グリッドネットワークインターフェイス（eth0）のMTU設定は、グリッド内のノード間で大きく異なります。

|===


== グリッドフェデレーションアラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
グリッドフェデレーション証明書の有効期限
 a| 
1つ以上のグリッドフェデレーション証明書の有効期限が近づいています。



 a| 
グリッドフェデレーション接続に失敗しました
 a| 
ローカルグリッドとリモートグリッドの間のグリッドフェデレーション接続が機能していません。

|===


== 高使用率または高レイテンシのアラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
Java ヒープの使用率が高い
 a| 
Java ヒープ領域の使用率が高くなっています。



 a| 
メタデータクエリのレイテンシが高くなっています
 a| 
Cassandra メタデータクエリの平均時間が長すぎます。

|===


== アイデンティティフェデレーションアラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
アイデンティティフェデレーションの同期に失敗する
 a| 
アイデンティティソースからフェデレーテッドグループとフェデレーテッドユーザを同期できません。



 a| 
テナントのアイデンティティフェデレーションの同期が失敗する
 a| 
テナントで設定されたアイデンティティソースからフェデレーテッドグループとフェデレーテッドユーザを同期できない。

|===


== 情報ライフサイクル管理（ILM）のアラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
ILM 配置を実現できません
 a| 
特定のオブジェクトについては、 ILM ルールでの配置手順を実行できません。



 a| 
ILM のスキャン速度が低下しています
 a| 
ILM のスキャン速度は 100 オブジェクト / 秒未満に設定されます。

|===


== キー管理サーバ（KMS）のアラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
KMS CA 証明書の有効期限
 a| 
キー管理サーバ（ KMS ）証明書への署名に使用する CA 証明書の有効期限が近づいています。



 a| 
KMS クライアント証明書の有効期限
 a| 
キー管理サーバのクライアント証明書の有効期限が近づいています



 a| 
KMS の設定をロードできませんでした
 a| 
キー管理サーバの設定は存在しますが、ロードできませんでした。



 a| 
KMS 接続エラー
 a| 
アプライアンスノードがサイトのキー管理サーバに接続できませんでした。



 a| 
KMS 暗号化キー名が見つかりません
 a| 
設定されているキー管理サーバに、指定した名前と一致する暗号化キーがありません。



 a| 
KMS 暗号化キーのローテーションに失敗しました
 a| 
アプライアンスのボリュームはすべて復号化されましたが、1つ以上のボリュームを最新のキーにローテーションできませんでした。



 a| 
KMS は設定されていません
 a| 
このサイトにはキー管理サーバがありません。



 a| 
KMS キーでアプライアンスボリュームを復号化できませんでした
 a| 
ノード暗号化が有効になっているアプライアンス上の 1 つ以上のボリュームを、現在の KMS キーで復号化できませんでした。



 a| 
KMS サーバ証明書の有効期限
 a| 
キー管理サーバ（ KMS ）で使用されるサーバ証明書の有効期限が近づいています。



 a| 
KMSサーバの接続エラー
 a| 
アプライアンスノードが、そのサイトのキー管理サーバクラスタ内の1つ以上のサーバに接続できませんでした。

|===


== ロードバランサのアラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
昇格したゼロリクエストロードバランサ接続
 a| 
ロードバランサエンドポイントへの接続のうち、要求を実行せずに切断された接続の割合が高くなりました。

|===


== ローカルクロックオフセットアラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
ローカル・クロック・ラージ・タイム・オフセット
 a| 
ローカルクロックとネットワークタイムプロトコル（NTP）時間のオフセットが大きすぎます。

|===


== メモリ不足またはスペース不足のアラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
監査ログのディスク容量が不足しています
 a| 
監査ログに使用できるスペースが少なくなっています。この状態に対処しないと、S3 操作が失敗する可能性があります。



 a| 
利用可能なノードメモリが少なくなっています
 a| 
ノードの使用可能な RAM の容量が少なくなっています。



 a| 
ストレージプールの空き容量が不足しています
 a| 
ストレージノードにオブジェクトデータを格納できるスペースが少なくなっています。



 a| 
ノードメモリが不足しています
 a| 
ノードに搭載されているメモリの容量が少なくなっています。



 a| 
メタデータストレージが不足しています
 a| 
オブジェクトメタデータを格納できるスペースが少なくなっています。



 a| 
ディスク容量不足です
 a| 
指標データベースに使用できるスペースが少なくなっています。



 a| 
オブジェクトデータのストレージが少ない
 a| 
オブジェクトデータを格納できるスペースが少なくなっています。



 a| 
読み取り専用のローウォーターマークの上書き
 a| 
ストレージボリュームのソフト読み取り専用ウォーターマークの上書きが、ストレージノードで最適化された最小ウォーターマークを下回っています。



 a| 
ルートディスク容量が不足しています
 a| 
ルートディスクの使用可能なスペースが少なくなっています。



 a| 
システムのデータ容量が不足しています
 a| 
/var/local に使用可能なスペースが少なくなっています。この状態に対処しないと、S3 操作が失敗する可能性があります。



 a| 
tmp ディレクトリの空きスペースが不足しています
 a| 
/tmp ディレクトリのスペースが不足しています。

|===


== ノードまたはノードのネットワークアラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
ADC クォーラムが満たされていません
 a| 
ADC サービスを備えたストレージ ノードがオフラインです。  ADC クォーラムが復元されるまで、拡張および廃止操作はブロックされます。



 a| 
管理ネットワークの受信使用量
 a| 
管理ネットワークで受信の使用率が高くなっています。



 a| 
管理ネットワークの転送使用量
 a| 
管理ネットワークでの転送使用率が高くなっています。



 a| 
ファイアウォールの設定に失敗しました
 a| 
ファイアウォール設定を適用できませんでした。



 a| 
フォールバックモードの管理インターフェイスエンドポイント
 a| 
すべての管理インターフェイスエンドポイントがデフォルトポートに長時間フォールバックしています。



 a| 
ノードのネットワーク接続エラー
 a| 
ノード間でデータを転送中にエラーが発生しました。



 a| 
ノードネットワーク受信フレームエラー
 a| 
ノードで受信したネットワークフレームの割合が高いとエラーが発生していました。



 a| 
ノードが NTP サーバと同期されていません
 a| 
ノードがネットワークタイムプロトコル（NTP）サーバと同期されていません。



 a| 
NTP サーバでノードがロックされていません
 a| 
ノードがネットワークタイムプロトコル（ NTP ）サーバにロックされていません。



 a| 
非アプライアンスノードのネットワークが停止しています
 a| 
1 つ以上のネットワークデバイスが停止しているか切断されています。



 a| 
管理ネットワークでサービスアプライアンスのリンクが停止しています
 a| 
アプライアンスの管理ネットワーク（eth1）へのインターフェイスが停止しているか切断されています。



 a| 
管理ネットワークポート 1 のサービスアプライアンスリンクが停止しています
 a| 
アプライアンスの管理ネットワークポート 1 が停止しているか切断されています。



 a| 
クライアントネットワークでサービスアプライアンスのリンクが停止しています
 a| 
アプライアンスのクライアントネットワーク（eth2）へのインターフェイスが停止しているか切断されています。



 a| 
ネットワークポート1でサービスアプライアンスのリンクが停止しています
 a| 
アプライアンスのネットワークポート1が停止しているか切断されています。



 a| 
ネットワークポート2でサービスアプライアンスのリンクが停止しています
 a| 
アプライアンスのネットワークポート2が停止しているか切断されています。



 a| 
ネットワークポート3でサービスアプライアンスのリンクが停止しています
 a| 
アプライアンスのネットワークポート3が停止しているか切断されています。



 a| 
ネットワークポート4でサービスアプライアンスのリンクが停止しています
 a| 
アプライアンスのネットワークポート4が停止しているか切断されています。



 a| 
管理ネットワークでのストレージアプライアンスのリンクが停止しています
 a| 
アプライアンスの管理ネットワーク（eth1）へのインターフェイスが停止しているか切断されています。



 a| 
管理ネットワークポート 1 のストレージアプライアンスのリンクが停止しています
 a| 
アプライアンスの管理ネットワークポート 1 が停止しているか切断されています。



 a| 
クライアントネットワークでストレージアプライアンスのリンクが停止しています
 a| 
アプライアンスのクライアントネットワーク（eth2）へのインターフェイスが停止しているか切断されています。



 a| 
ネットワークポート1でストレージアプライアンスのリンクが停止しています
 a| 
アプライアンスのネットワークポート1が停止しているか切断されています。



 a| 
ネットワークポート2でストレージアプライアンスのリンクが停止しています
 a| 
アプライアンスのネットワークポート2が停止しているか切断されています。



 a| 
ネットワークポート3でストレージアプライアンスのリンクが停止しています
 a| 
アプライアンスのネットワークポート3が停止しているか切断されています。



 a| 
ネットワークポート4でストレージアプライアンスのリンクが停止しています
 a| 
アプライアンスのネットワークポート4が停止しているか切断されています。



 a| 
ストレージノードが目的のストレージ状態ではありません
 a| 
内部エラーまたはボリューム関連の問題が原因で、ストレージノードのLDRサービスを目的の状態に移行できない



 a| 
TCP接続の使用状況
 a| 
このノードのTCP接続数が追跡可能な最大数に近づいています。



 a| 
ノードと通信できません
 a| 
1 つ以上のサービスが応答していないか、ノードに到達できません。



 a| 
予期しないノードのリブートです
 a| 
過去 24 時間以内にノードが予期せずリブートされました。

|===


== オブジェクトアラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
オブジェクトの存在チェックに失敗しました
 a| 
オブジェクトの存在チェックジョブが失敗しました。



 a| 
オブジェクトの存在チェックが停止しました
 a| 
オブジェクトの存在チェックジョブが停止しました。



 a| 
紛失の可能性があるオブジェクト
 a| 
1 つ以上のオブジェクトがグリッドから失われる可能性があります。



 a| 
孤立したオブジェクトが検出されました
 a| 
孤立したオブジェクトが検出されました。



 a| 
S3 PUTオブジェクトサイズが大きすぎます
 a| 
クライアントがS3のサイズ制限を超えるPUT Object処理を試行しています。



 a| 
未識別の破損オブジェクトが検出されました
 a| 
レプリケートオブジェクトストレージにファイルが見つかりましたが、レプリケートオブジェクトとして識別できませんでした。

|===


== オブジェクト破損アラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
オブジェクトサイズの不一致
 a| 
オブジェクト存在チェック手順中に予期しないオブジェクト サイズが検出されました。

|===


== プラットフォームサービスのアラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
プラットフォームサービス保留中の要求容量が少なくなっています
 a| 
保留中のPlatform Servicesリクエストの数が上限に近づいています。



 a| 
プラットフォームサービスを利用できません
 a| 
実行中または利用可能な状態の、 RSM サービスを搭載したストレージノードがサイトで不足しています。

|===


== ストレージボリュームのアラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
ストレージボリュームで対応が必要です
 a| 
ストレージボリュームはオフラインで、対応が必要です。



 a| 
ストレージボリュームをリストアする必要があります
 a| 
ストレージボリュームがリカバリされたため、リストアが必要です。



 a| 
ストレージボリュームはオフラインです
 a| 
ストレージボリュームが5分以上オフラインになっている。



 a| 
ストレージボリュームの再マウントが試行されました
 a| 
ストレージボリュームがオフラインになり、自動再マウントがトリガーされました。ドライブの問題またはファイルシステムのエラーを示している可能性があります。



 a| 
ボリュームのリストアでレプリケートデータの修復を開始できませんでした
 a| 
修復されたボリュームのレプリケートデータの修復を自動的に開始できませんでした。

|===


== StorageGRID サービスのアラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
バックアップ構成を使用するnginxサービス
 a| 
nginxサービスの設定が無効です。以前の設定が使用されています。



 a| 
バックアップ設定を使用するnginx-gwサービス
 a| 
nginx-gwサービスの設定が無効です。以前の設定が使用されています。



 a| 
FIPSを無効にするにはリブートが必要です
 a| 
セキュリティ ポリシーでは FIPS モードは必要ありませんが、FIPS モジュールが使用されています。



 a| 
FIPSを有効にするにはリブートが必要です
 a| 
セキュリティ ポリシーでは FIPS モードが必要ですが、FIPS モジュールは使用されていません。



 a| 
バックアップ設定を使用したSSHサービス
 a| 
SSHサービスの設定が無効です。以前の設定が使用されています。

|===


== テナントアラート

[cols="1a,2a"]
|===
| アラート名 | 製品説明 


 a| 
テナントクォータの使用率が高い
 a| 
クォータスペースの使用率が高くなっています。通知の原因 が多すぎる可能性があるため、このルールはデフォルトで無効になっています。

|===