---
permalink: monitor/autosupport-package-failure-handling.html 
sidebar: sidebar 
keywords: troubleshoot autosupport, asup package 
summary: AutoSupportパッケージの送信試行が失敗した場合にStorageGRIDが実行するアクションのリストを確認します。 
---
= StorageGRID が AutoSupport パッケージの障害を処理する方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupportパッケージの送信試行が失敗した場合にStorageGRIDが実行するアクションのリストを確認します。

StorageGRID は、AutoSupport パッケージの種類に応じて異なる処理を実行します。AutoSupport パッケージのステータスを確認するには、*サポート* > *ツール* > *AutoSupport* > *結果* を選択します。

AutoSupportパッケージの送信に失敗すると、* AutoSupport *ページの* Results *タブに「Failed」と表示されます。


NOTE: プロキシ サーバを設定して AutoSupport パッケージを NetApp に転送するように構成した場合は、link:../admin/configuring-admin-proxy-settings.html["プロキシサーバの設定が正しいことを確認します。"]。



[[weekly-autosupport-package-failure]]
== 週次AutoSupportパッケージエラー

週次AutoSupportパッケージの送信に失敗した場合、StorageGRIDシステムは次の処理を実行します。

. 最新の結果属性を更新して再試行します。
. AutoSupportパッケージの再送信を4分ごとに15回、1時間試行します。
. 送信エラーが 1 時間発生した後、最新の結果属性を失敗に更新します。
. 次回のスケジュールされた時刻に、AutoSupportパッケージの送信を再試行します。
. NMSサービスが使用できないためにパッケージが失敗した場合や、7日前にパッケージが送信された場合は、AutoSupportの通常のスケジュールを維持します。
. 7日以上パッケージが送信されていない場合、NMSサービスが再び使用可能になると、はAutoSupportパッケージをすぐに送信します。




[[user-triggered-or-event-triggered-autosupport-package-failure]]
== ユーザトリガー型またはイベントトリガー型のAutoSupportパッケージエラー

ユーザトリガー型またはイベントトリガー型のAutoSupportパッケージの送信に失敗した場合、StorageGRIDシステムは次の処理を実行します。

. 既知のエラーの場合は、エラーメッセージが表示されます。たとえば、ユーザが正しいEメール設定を指定せずにSMTPプロトコルを選択すると、次のエラーが表示されます。 `AutoSupport packages cannot be sent using SMTP protocol due to incorrect settings on the E-mail Server page.`
. パッケージの再送信は試行されません。
. にエラーを記録し `nms.log`ます。


障害が発生し、SMTPが選択されているプロトコルである場合、AutoSupportページに次のエラーメッセージが表示される場合があります： `AutoSupport packages cannot be sent using SMTP protocol due to incorrect settings on the E-mail Server page.`

方法をご確認くださいlink:../monitor/email-alert-notifications.html["Eメールサーバを設定します"]。



[[correct-an-autosupport-package-failure]]
== AutoSupportパッケージの障害を修正する

障害が発生し、SMTPが選択されているプロトコルである場合は、StorageGRIDシステムのメールサーバーが正しく設定されており、メールサーバーが稼働していることを確認してください。次のエラーメッセージがAutoSupportページに表示される場合があります：AutoSupportパッケージは、メールサーバーページの設定が正しくないため、SMTPプロトコルを使用して送信できません。
