---
permalink: monitor/collecting-log-files-and-system-data.html 
sidebar: sidebar 
keywords: how to collect system data, how to collect logs 
summary: StorageGRIDのログファイルとシステムデータ（設定データを含む）を取得して、テクニカルサポートに送信できます。 
---
= ログファイルとシステムデータを収集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRIDのログファイルとシステムデータ（設定データを含む）を取得して、テクニカルサポートに送信できます。

.開始する前に
* を使用してプライマリ管理ノードでGrid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* そうだな link:../admin/admin-group-permissions.html["特定のアクセス権限"]
* プロビジョニングパスフレーズを用意します。


.タスクの内容
Grid Managerを使用して、link:logs-files-reference.html["ログファイル"]選択した期間のグリッドノードから、システムデータ、および設定データを収集します。収集されたデータはファイルにアーカイブされ `.tar.gz`、ローカルコンピュータにダウンロードしたり、テクニカルサポートに送信したりできます。

必要に応じて、監査ログのデスティネーションを変更したり、監査情報を外部 syslog サーバに送信したりできます。外部 syslog サーバが設定されても、監査レコードのローカルログは引き続き生成および格納されます。を参照して link:../monitor/configure-audit-messages.html["監査メッセージと外部syslogサーバの設定"]

.手順
. [ * support * > * Tools * > * Logs * ] を選択します。ノードのテーブルが表示されます。
. ログファイルを収集するグリッドノードを選択します。
+
ノード名、サイト、およびノードタイプでソートできます。[Site]列と[Node type]列には、個 々 のサイトとノードタイプで選択するためのフィルタが含まれています。

. 「 * Continue * 」を選択します。
. ログファイルに含めるデータの日時範囲を選択します。
+
非常に長い期間を選択したり、大規模なグリッド内のすべてのノードからログを収集したりすると、ログアーカイブが大きくなりすぎてノードに格納できなくなったり、ダウンロード用にプライマリ管理ノードに保存できなくなったりすることがあります。いずれかの状況が発生した場合は、より小さなデータセットを使用してログ収集を再開します。

. 収集するログのタイプを選択します。
+
** *アプリケーションログ*：テクニカルサポートがトラブルシューティングに最も頻繁に使用するアプリケーション固有のログ。収集されるログは、使用可能なアプリケーションログの一部です。
** *監査ログ*：通常のシステム運用中に生成された監査メッセージを含むログ。
** *ネットワークトレース*：ネットワークデバッグに使用されるログ。
** * Prometheus database *：すべてのノード上のサービスの時系列の指標。


. 必要に応じて、* Notes *テキストボックスを使用して、収集するログファイルに関するメモを入力します。
+
このメモを使用して、ログファイルを収集する原因となった問題に関するテクニカルサポート情報を入力できます。メモは、ログファイルの収集に関するその他の情報とともにというファイルに追加され `info.txt`ます。 `info.txt`ファイルはログファイルのアーカイブパッケージに保存されます。

. [プロビジョニングパスフレーズ]*テキストボックスに、StorageGRIDシステムのプロビジョニングパスフレーズを入力します。
. [ログの収集]*を選択します。
+
ログページを使用して、各グリッドノードのログファイル収集の進捗状況を監視できます。

+
ログサイズに関するエラーメッセージが表示された場合は、ログを収集する期間を短縮するか、またはノードの数を減らしてください。

. ログ収集に失敗した場合：
+
** 「Log collection failed」というメッセージが表示された場合は、ログ収集を再試行するか、再試行せずにセッションを終了できます。
** 「Log collection partially failed」というメッセージが表示された場合は、ログ収集を再試行するか、セッションを終了するか、部分ログファイルをダウンロードするか、または部分ログファイルをAutoSupportに送信できます。


. ログファイルの収集が完了したら：
+
** [ダウンロード]*を選択してファイルをダウンロードし `.tar.gz`ます。
** [Send to（AutoSupportに送信）]*を選択して、テクニカルサポートにファイルを送信し `.tar.gz`ます。
+
 `.tar.gz`ファイルには、ログ収集が成功したすべてのグリッドノードのすべてのログファイルが含まれています。組み合わせた `.tar.gz`ファイルには、グリッドノードごとに1つのログファイルアーカイブが格納されます。

+
AutoSupportパッケージの件名はです `USER_TRIGGERED_SUPPORT_BUNDLE`。



. [ 完了 ] を選択します。
+

CAUTION:  `.tar.gz`[完了]*を選択すると、ファイルが削除されます。最初にファイルをダウンロードまたは送信してください。


