---
permalink: monitor/collecting-log-files-and-system-data.html 
sidebar: sidebar 
keywords: how to collect system data, how to collect logs 
summary: 'StorageGRIDログ ファイルとシステム データ (構成データを含む) を取得し、テクニカル サポートに送信できます。' 
---
= ログファイルとシステムデータを収集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRIDログ ファイルとシステム データ (構成データを含む) を取得し、テクニカル サポートに送信できます。

.開始する前に
* いずれかの管理ノードでグリッドマネージャにサインインしている。link:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"] 。
* そうだな link:../admin/admin-group-permissions.html["特定のアクセス権限"]
* プロビジョニングパスフレーズを用意します。


.タスクの内容
グリッドマネージャーを使用して収集するlink:logs-files-reference.html["ログファイル"]選択した期間の任意のグリッド ノードからのシステム データおよび構成データを取得します。データは収集され、 `.tar.gz`このファイルは、ローカル コンピュータにダウンロードしたり、テクニカル サポートに送信したりできます。

必要に応じて、監査ログの送信先を変更し、監査情報を外部の syslog サーバーに送信することもできます。外部 Syslog サーバーが構成されている場合、監査レコードのローカル ログは引き続き生成され、保存されます。見るlink:../monitor/configure-log-management.html["ログ管理と外部Syslogサーバーを構成する"] 。

.手順
. *サポート* > *ツール* > *ログ収集*を選択します。ノードのテーブルが表示されます。
. ログファイルを収集するグリッドノードを選択します。
+
ノード名、サイト、ノード タイプで並べ替えることができます。サイトとノードのタイプの列には、個々のサイトとノードのタイプで選択するためのフィルターが含まれています。

. 「 * Continue * 」を選択します。
. ログ ファイルに含めるデータの日付と時刻の範囲を選択します。
+
非常に長い期間を選択した場合、または大規模なグリッド内のすべてのノードからログを収集した場合、ログ アーカイブが大きくなりすぎてノードに保存できなくなったり、管理ノードで収集してダウンロードできなくなったりする可能性があります。どちらかのシナリオが発生した場合は、より小さいデータ セットでログ収集を再開します。

. 収集するログのタイプを選択します。
+
** *アプリケーション ログ*: テクニカル サポートがトラブルシューティングに最も頻繁に使用するアプリケーション固有のログ。収集されるログは、利用可能なアプリケーション ログのサブセットです。
** *監査ログ*: 通常のシステム操作中に生成された監査メッセージを含むログ。
** *ネットワーク トレース*: ネットワークのデバッグに使用されるログ。
** *Prometheus データベース*: すべてのノード上のサービスからの時系列メトリック。


. オプションで、「*Notes*」テキスト ボックスを使用して、収集するログ ファイルに関するメモを入力します。
+
このメモを使用して、ログファイルを収集する原因となった問題に関するテクニカルサポート情報を入力できます。メモは、ログファイルの収集に関するその他の情報とともにというファイルに追加され `info.txt`ます。 `info.txt`ファイルはログファイルのアーカイブパッケージに保存されます。

. *プロビジョニング パスフレーズ* テキスト ボックスに、 StorageGRIDシステムのプロビジョニング パスフレーズを入力します。
. *ログを収集*を選択します。
+
ログ収集ページを使用して、各グリッド ノードのログ ファイル収集の進行状況を監視できます。

+
ログサイズに関するエラーメッセージが表示された場合は、ログを収集する期間を短縮するか、またはノードの数を減らしてください。

. ログ収集に失敗した場合:
+
** 「ログ収集に失敗しました」というメッセージが表示された場合は、ログ収集を再試行するか、再試行せずにセッションを終了することができます。
** 「ログ収集が部分的に失敗しました」というメッセージが表示された場合は、ログ収集を再試行するか、セッションを終了するか、部分的なログ ファイルをダウンロードするか、部分的なログ ファイルをAutoSupportに送信することができます。


. ログファイルの収集が完了したら:
+
** ダウンロードするには*ダウンロード*を選択してください `.tar.gz`ファイル。
** * AutoSupportに送信*を選択して送信します `.tar.gz`ファイルをテクニカル サポートに送信します。
+
その `.tar.gz`ファイルには、ログ収集が成功したすべてのグリッド ノードからのすべてのログ ファイルが含まれます。組み合わせた `.tar.gz`ファイルには、グリッド ノードごとに 1 つのログ ファイル アーカイブが含まれます。

+
AutoSupportパッケージの対象は `USER_TRIGGERED_SUPPORT_BUNDLE`。



. [ 完了 ] を選択します。
+

CAUTION: その `.tar.gz`*完了*を選択するとファイルは削除されます。必ず最初にファイルをダウンロードまたは送信してください。


