---
permalink: monitor/configure-audit-messages.html 
sidebar: sidebar 
keywords: audit messages, audit level, external syslog server, log destinations 
summary: 監査メッセージに関連するいくつかの設定を行うことができます。記録する監査メッセージの数の調整、クライアントの読み取り/書き込み監査メッセージに含めるHTTP要求ヘッダーの定義、外部syslogサーバの設定、監査ログ、セキュリティイベントログ、およびStorageGRIDソフトウェアログの送信先の指定を行うことができます。 
---
= 監査メッセージと外部syslogサーバの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
監査メッセージに関連するいくつかの設定を行うことができます。記録する監査メッセージの数の調整、クライアントの読み取り/書き込み監査メッセージに含めるHTTP要求ヘッダーの定義、外部syslogサーバの設定、監査ログ、セキュリティイベントログ、およびStorageGRIDソフトウェアログの送信先の指定を行うことができます。

監査メッセージとログには、システムのアクティビティとセキュリティイベントが記録され、監視とトラブルシューティングに不可欠なツールです。すべての StorageGRID ノードで監査メッセージとログが生成され、システムアクティビティとイベントが追跡されます。

必要に応じて、監査情報をリモートで保存するように外部syslogサーバを設定できます。外部サーバを使用すると、監査データの完全性を損なうことなく、監査メッセージロギングによるパフォーマンスへの影響を最小限に抑えることができます。外部のsyslogサーバは、大規模なグリッドを使用する場合、複数のタイプのS3アプリケーションを使用する場合、またはすべての監査データを保持する場合に特に役立ちます。詳細は、を参照してください link:../monitor/considerations-for-external-syslog-server.html["監査メッセージと外部syslogサーバの設定"] 。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたはを持っていますlink:../admin/admin-group-permissions.html["Maintenance権限またはRoot Access権限"]。
* 外部syslogサーバを設定する場合は、を確認し、ログファイルを受信して保存するための十分な容量がサーバにあることを確認しておきlink:../monitor/considerations-for-external-syslog-server.html["外部syslogサーバを使用する場合の考慮事項"]ます。
* TLSまたはRELP/TLSプロトコルを使用して外部syslogサーバを設定する場合は、必要なサーバCAとクライアント証明書、およびクライアント秘密鍵が必要です。




== 監査メッセージレベルの変更

監査ログでは、次のカテゴリのメッセージごとに異なる監査レベルを設定できます。

[cols="1a,1a,1a"]
|===
| 監査カテゴリ | デフォルト設定 | 詳細情報 


 a| 
システム
 a| 
標準
 a| 
link:../audit/system-audit-messages.html["システム監査メッセージ"]



 a| 
ストレージ
 a| 
エラー
 a| 
link:../audit/object-storage-audit-messages.html["オブジェクトストレージ監査メッセージ"]



 a| 
管理
 a| 
標準
 a| 
link:../audit/management-audit-message.html["管理監査メッセージ"]



 a| 
クライアント読み取り
 a| 
標準
 a| 
link:../audit/client-read-audit-messages.html["クライアント読み取り監査メッセージ"]



 a| 
クライアントからの書き込み
 a| 
標準
 a| 
link:../audit/client-write-audit-messages.html["クライアント書き込み監査メッセージ"]



 a| 
ILM
 a| 
標準
 a| 
link:../audit/ilm-audit-messages.html["ILM監査メッセージ"]



 a| 
グリッド間レプリケーション
 a| 
エラー
 a| 
link:../audit/cgrr-cross-grid-replication-request.html["CGRR：クロスグリッドレプリケーション要求"]

|===

NOTE: これらのデフォルト値は、 StorageGRID 10.3 以降を最初にインストールした場合に適用されます。以前のバージョンのStorageGRIDを最初に使用した場合、すべてのカテゴリのデフォルトは[標準]に設定されます。


NOTE: アップグレード中は、監査レベルの設定はすぐには有効になりません。

.手順
. * configuration * > * Monitoring * > * Audit and syslog server * を選択します。
. 監査メッセージのカテゴリごとに、ドロップダウンリストから監査レベルを選択します。
+
[cols="1a,3a"]
|===
| 監査レベル | 製品説明 


 a| 
オフ
 a| 
このカテゴリの監査メッセージはログに記録されません。



 a| 
エラー
 a| 
エラーメッセージのみが記録されます。結果コードが「successful」（SUCS）ではなかった監査メッセージです。



 a| 
標準
 a| 
標準のトランザクション・メッセージはログに記録されますこのメッセージは ' カテゴリに関する次の手順に記載されています



 a| 
デバッグ
 a| 
非推奨です。このレベルの動作は Normal 監査レベルと同じです。

|===
+
特定のレベルに含まれるメッセージには、上位レベルでロギングされるメッセージも含まれます。たとえば、 Normal レベルには Error レベルのメッセージがすべて含まれます。

+

NOTE: S3アプリケーションに対するクライアント読み取り処理の詳細なレコードを確認する必要がない場合は、必要に応じて* Client Reads *設定を* Error *に変更して、監査ログに記録される監査メッセージの数を減らします。

. [ 保存（ Save ） ] を選択します。
+
緑色のバナーは、設定が保存されたことを示します。





== HTTP要求ヘッダーの定義

必要に応じて、クライアントの読み取り/書き込み監査メッセージに含めるHTTP要求ヘッダーを定義できます。これらのプロトコルヘッダーはS3要求にのみ適用されます。

.手順
. [Audit protocol headers]セクションで、クライアントの読み取り/書き込み監査メッセージに含めるHTTP要求ヘッダーを定義します。
+
0 個以上の文字に一致させるには、ワイルドカードとしてアスタリスク（ \* ）を使用します。リテラルアスタリスクに一致させるには、エスケープシーケンス（ \ * ）を使用します。

. 必要に応じて、「 * 別のヘッダーを追加」を選択して追加のヘッダーを作成します。
+
要求に HTTP ヘッダーが含まれている場合、 HTTP ヘッダーは HTRH フィールドの下の監査メッセージに含まれます。

+

NOTE: 監査プロトコル要求ヘッダーは、* Client Reads *または* Client Writes *の監査レベルが* Off *でない場合にのみ記録されます。

. [ 保存（ Save ） ] を選択します
+
緑色のバナーは、設定が保存されたことを示します。





== [use-external-syslog-server]]外部syslogサーバを使用する

必要に応じて、監査ログ、アプリケーションログ、およびセキュリティイベントログをグリッドの外部の場所に保存するように外部のsyslogサーバを設定できます。


NOTE: 外部syslogサーバを使用しない場合は、この手順を省略してに進みます<<select-audit-information-destinations,監査情報の送信先を選択します>>。


TIP: この手順で使用できる構成オプションが要件を満たすほど柔軟性がない場合は、のプライベートAPIセクションにあるエンドポイントを使用して追加の構成オプションを適用できます `audit-destinations`。link:../admin/using-grid-management-api.html["Grid 管理 API"]たとえば、ノードのグループごとに異なるsyslogサーバを使用する場合は、APIを使用できます。



=== syslog情報の入力

外部syslogサーバの設定ウィザードにアクセスし、StorageGRIDが外部syslogサーバにアクセスするために必要な情報を入力します。

.手順
. 監査および syslog サーバページで、 * 外部 syslog サーバの設定 * を選択します。または、以前に外部syslogサーバを設定した場合は、*[外部syslogサーバの編集]*を選択します。
+
Configure external syslog serverウィザードが表示されます。

. ウィザードの* syslog情報の入力*ステップで、* Host *フィールドに外部syslogサーバの有効な完全修飾ドメイン名またはIPv4またはIPv6アドレスを入力します。
. 外部 syslog サーバのデスティネーションポートを入力します（ 1~65535 の整数で指定する必要があります）。デフォルトのポートは514です。
. 外部 syslog サーバへの監査情報の送信に使用するプロトコルを選択します。
+
TLS *または* RELP/TLS *を使用することを推奨します。これらのいずれかのオプションを使用するには、サーバ証明書をアップロードする必要があります。証明書を使用して、グリッドと外部 syslog サーバの間の接続を保護できます。詳細については、を参照してください link:../admin/using-storagegrid-security-certificates.html["セキュリティ証明書を管理する"]。

+
すべてのプロトコルオプションで、外部 syslog サーバによるサポートおよび設定が必要です。外部 syslog サーバと互換性のあるオプションを選択する必要があります。

+

NOTE: Reliable Event Logging Protocol (RELP) は、 syslog プロトコルの機能を拡張し、信頼性の高いイベントメッセージ配信を実現します。RELP を使用すると、外部 syslog サーバを再起動する必要がある場合に監査情報が失われないようにすることができます。

. 「 * Continue * 」を選択します。
. [[attach-certificate]* TLS *または* RELP/TLS *を選択した場合は、サーバCA証明書、クライアント証明書、およびクライアント秘密鍵をアップロードします。
+
.. 使用する証明書またはキーの [* 参照 ] を選択します。
.. 証明書またはキーファイルを選択します。
.. ファイルをアップロードするには、 * 開く * を選択します。
+
証明書またはキーファイル名の横に緑のチェックマークが表示され、正常にアップロードされたことを通知します。



. 「 * Continue * 」を選択します。




=== syslog の内容を管理します

外部syslogサーバに送信する情報を選択できます。

.手順
. ウィザードの* syslogコンテンツの管理*ステップで、外部syslogサーバに送信する監査情報の種類をそれぞれ選択します。
+
** *監査ログの送信*：StorageGRID イベントとシステムアクティビティを送信します
** *セキュリティイベントの送信*:許可されていないユーザーがサインインしようとしたときや、ユーザーがrootとしてサインインしようとしたときなど、セキュリティイベントを送信します
** *アプリケーションログを送信*：次のようなトラブルシューティングに役立つ情報を送信しますlink:../monitor/storagegrid-software-logs.html["StorageGRIDソフトウェアのログファイル"]。
+
*** `bycast-err.log`
*** `bycast.log`
*** `jaeger.log`
*** `nms.log`（管理ノードのみ）
*** `prometheus.log`
*** `raft.log`
*** `hagroups.log`


** *アクセスログを送信*：外部要求に対するHTTPアクセスログをGrid Manager、Tenant Manger、設定されているロードバランサエンドポイント、およびリモートシステムからのグリッドフェデレーション要求に送信します。


. ドロップダウンメニューを使用して、送信する監査情報のカテゴリごとに重大度とファシリティ（メッセージのタイプ）を選択します。
+
重大度とファシリティの値を設定すると、ログをカスタマイズ可能な方法で集約して分析を容易にすることができます。

+
.. [Severity]*では、*[Passthrough]*を選択するか、重大度値を0~7で選択します。
+
値を選択すると、選択した値がこのタイプのすべてのメッセージに適用されます。固定値で重大度を上書きすると、異なる重大度に関する情報が失われます。

+
[cols="1a,3a"]
|===
| 重大度 | 製品説明 


 a| 
パススルー
 a| 
外部syslogに送信される各メッセージの重大度は、ノードにローカルにログインしたときと同じになります。

*** 監査ログの場合、重大度は「info」です。
*** セキュリティイベントの場合、重大度の値はノード上のLinuxディストリビューションによって生成されます。
*** アプリケーションログの重大度は、問題の内容に応じて「info」と「notice」の間で異なります。たとえば、NTPサーバを追加してHAグループを設定すると値が「info」になり、SSMサービスまたはRSMサービスを意図的に停止すると値が「notice」になります。
*** アクセスログの場合、重大度は「info」です。




 a| 
0
 a| 
EMERGENCY ：システムが使用できない



 a| 
1
 a| 
ALERT ：早急に対処が必要です



 a| 
2
 a| 
Critical ：クリティカルな状態です



 a| 
3
 a| 
Error ：エラー状態



 a| 
4
 a| 
Warning ：警告状態です



 a| 
5
 a| 
通知：通常の状態だが重要な状態



 a| 
6
 a| 
INFORMATIONAL ：情報メッセージです



 a| 
7
 a| 
DEBUG ：デバッグレベルのメッセージ

|===
.. *Facilty*では、*Passthrough*を選択するか、0～23のファシリティ値を選択します。
+
値を選択すると、このタイプのすべてのメッセージに適用されます。固定値でファシリティを上書きすると、さまざまなファシリティに関する情報が失われます。

+
[cols="1a,3a"]
|===
| ファシリティ | 製品説明 


 a| 
パススルー
 a| 
外部syslogに送信される各メッセージのファシリティ値は、ノードにローカルにログインしたときと同じです。

*** 監査ログの場合、外部syslogサーバに送信されるファシリティは「local7」です。
*** セキュリティイベントの場合、ファシリティ値はノード上のLinuxディストリビューションによって生成されます。
*** アプリケーションログの場合、外部syslogサーバに送信されるアプリケーションログのファシリティ値は次のとおりです。
+
**** `bycast.log`:ユーザーまたはデーモン
**** `bycast-err.log`：user、daemon、local3、またはlocal4
**** `jaeger.log`：local2
**** `nms.log`: local3
**** `prometheus.log`：local4
**** `raft.log`: local5
**** `hagroups.log`：local6


*** アクセスログの場合、外部syslogサーバに送信されるファシリティは「local0」です。




 a| 
0
 a| 
kern （カーネルメッセージ）



 a| 
1
 a| 
ユーザ（ユーザレベルのメッセージ）



 a| 
2
 a| 
メール



 a| 
3
 a| 
デーモン（システムデーモン）



 a| 
4
 a| 
AUTH （セキュリティ / 認証メッセージ）



 a| 
5
 a| 
syslog （ syslogd で内部的に生成されるメッセージ）



 a| 
6
 a| 
LPR （ラインプリンタサブシステム）



 a| 
7
 a| 
News （ネットワークニュースサブシステム）



 a| 
8
 a| 
UUCP



 a| 
9
 a| 
cron クロックデーモン



 a| 
10
 a| 
セキュリティ（セキュリティ / 認可メッセージ）



 a| 
11
 a| 
FTP



 a| 
12
 a| 
NTP



 a| 
13
 a| 
logaudit （ログ監査）



 a| 
14
 a| 
logalert （ログアラート）



 a| 
15
 a| 
clock （ clock デーモン）



 a| 
16
 a| 
ローカル0



 a| 
17
 a| 
local1



 a| 
18
 a| 
local2



 a| 
19
 a| 
local3



 a| 
20
 a| 
local4



 a| 
21
 a| 
local5



 a| 
22
 a| 
local6



 a| 
23
 a| 
local7

|===


. 「 * Continue * 」を選択します。




=== テストメッセージを送信します

外部 syslog サーバの使用を開始する前に、グリッド内のすべてのノードが外部 syslog サーバにテストメッセージを送信するように要求する必要があります。外部 syslog サーバへのデータ送信にコミットする前に、これらのテストメッセージを使用してログ収集インフラ全体を検証する必要があります。


CAUTION: 外部syslogサーバがグリッド内の各ノードからテストメッセージを受信し、メッセージが想定どおりに処理されたことを確認するまでは、外部syslogサーバの設定を使用しないでください。

.手順
. 外部syslogサーバが適切に設定され、グリッド内のすべてのノードから監査情報を受信できることが確実であるためにテストメッセージを送信しない場合は、*[スキップして終了]*を選択します。
+
緑色のバナーは、設定が保存されたことを示します。

. それ以外の場合は、*テストメッセージを送信*（推奨）を選択します。
+
テスト結果は、テストを停止するまでページに継続的に表示されます。テストの実行中も、以前に設定した送信先に監査メッセージが引き続き送信されます。

. エラーが発生した場合は、修正して、もう一度 [ テストメッセージを送信する *] を選択します。
+
エラーの解決方法については、を参照してくださいlink:../troubleshoot/troubleshooting-syslog-server.html["外部 syslog サーバのトラブルシューティングを行います"]。

. すべてのノードがテストに合格したことを示す緑のバナーが表示されるまで待ちます。
. syslog サーバを調べて、テストメッセージが正常に受信および処理されているかどうかを確認します。
+

NOTE: UDP を使用している場合は、ログ収集インフラストラクチャ全体を確認します。UDPプロトコルでは、他のプロトコルほど厳密なエラー検出は許可されていません。

. 「 * ストップ & フィニッシュ * 」を選択します。
+
監査および syslog サーバ * ページに戻ります。緑色のバナーは、syslogサーバの設定が保存されたことを示します。

+

NOTE: 外部syslogサーバを含む送信先を選択するまで、StorageGRID監査情報は外部syslogサーバに送信されません。





== 監査情報の送信先を選択します

監査ログ、セキュリティイベントログ、およびの送信先を指定できますlink:../monitor/storagegrid-software-logs.html["StorageGRID ソフトウェアのログ"]。

[NOTE]
====
StorageGRIDはデフォルトでローカルノードの監査先に設定され、監査情報をに格納します `/var/local/log/localaudit.log`。

を使用する `/var/local/log/localaudit.log`と、Grid ManagerとTenant Managerの監査ログエントリがストレージノードに送信されることがあります。最新のエントリがあるノードを確認するには、コマンドを使用し `run-each-node --parallel "zgrep MGAU /var/local/log/localaudit.log | tail"`ます。

一部の送信先は、外部syslogサーバを設定した場合にのみ使用できます。

====
.手順
. [Audit and syslog server]ページで、監査情報の保存先を選択します。
+

TIP: *ローカルノードのみ*および*外部syslogサーバ*の方が一般的にパフォーマンスが向上します。

+
[cols="1a,2a"]
|===
| オプション | 製品説明 


 a| 
ローカルノードのみ（デフォルト）
 a| 
監査メッセージ、セキュリティイベントログ、およびアプリケーションログは管理ノードに送信されません。代わりに、それらはそれらを生成したノード（「ローカルノード」）にのみ保存されます。すべてのローカルノードで生成された監査情報はに格納されます `/var/local/log/localaudit.log`。

*注*：StorageGRIDは定期的にローカルログをローテーションで削除し、スペースを解放します。ノードのログファイルが 1GB に達すると、既存のファイルが保存され、新しいログファイルが開始されます。ログのローテーションの上限は 21 ファイルです。ログファイルの 22 番目のバージョンが作成されると、最も古いログファイルが削除されます。各ノードには平均約 20GB のログデータが格納されます。



 a| 
管理ノード/ローカルノード
 a| 
監査メッセージは管理ノード上の監査ログに送信され、セキュリティイベントログとアプリケーションログはそれらを生成したノードに格納されます。監査情報は次のファイルに格納されます。

** 管理ノード（プライマリおよび非プライマリ）： `/var/local/audit/export/audit.log`
** All nodes（すべてのノード）： `/var/local/log/localaudit.log`通常、ファイルが空であるか欠落しています。一部のメッセージの追加コピーなど、セカンダリ情報が含まれている場合があります。




 a| 
外部 syslog サーバ
 a| 
監査情報は外部syslogサーバに送信され、ローカルノードに保存され(`/var/local/log/localaudit.log`ます）。送信される情報の種類は、外部 syslog サーバの設定方法によって異なります。このオプションは、外部 syslog サーバを設定した場合にのみ有効になります。



 a| 
管理ノードと外部 syslog サーバ
 a| 
監査メッセージは(`/var/local/audit/export/audit.log`管理ノード上の監査ログに送信され、監査情報は外部syslogサーバに送信されてローカルノードに保存され(`/var/local/log/localaudit.log`ます）。送信される情報の種類は、外部 syslog サーバの設定方法によって異なります。このオプションは、外部 syslog サーバを設定した場合にのみ有効になります。

|===
. [ 保存（ Save ） ] を選択します。
+
警告メッセージが表示されます。

. [OK]*を選択して、監査情報の保存先を変更することを確認します。
+
緑色のバナーは、監査設定が保存されたことを示します。

+
選択した送信先に新しいログが送信されます。既存のログは現在の場所に残ります。


