---
permalink: monitor/configure-email-server.html 
sidebar: sidebar 
keywords: notifications, email, system events, technical support 
summary: StorageGRID 管理者として、システムイベントや問題についてご自身、他の管理者、およびテクニカルサポートに通知する StorageGRID のアラートおよび監視システムから通知を送信するために、メールサーバを設定する必要があります。 
---
= メールサーバーの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 管理者として、システムイベントや問題についてご自身、他の管理者、およびテクニカルサポートに通知する StorageGRID のアラートおよび監視システムから通知を送信するために、メールサーバを設定する必要があります。

通知にメールサーバーを使用する StorageGRID の機能には、アラート、AutoSupport、および複数管理者認証（MAV）があります。すべての通知に同じメールサーバーを使用できます。

.開始する前に
* あなたはを持っていますlink:../admin/admin-group-permissions.html["rootアクセス権限"]。
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。


.手順
. *設定* ＞ *監視* ＞ *メールサーバー* を選択します。
+
メールサーバーのページが表示されます。

. プルダウンメニュー「メールサーバーが必要となる可能性のある機能を表示する」を選択します。機能のメール通知を設定するための詳細と必要な情報を確認するには、「表示」を選択します。
+
グリッドマネージャー内の該当機能の設定ページに移動します。各機能の設定ページには、メール通知を送信するにはメールサーバーが必要であることを示す通知が表示されます。

. メールサーバーページからメールサーバーを設定するには：
+
.. メールサーバーのIPアドレスまたはFQDNを入力してください。
.. メールサーバーが使用するポート番号を選択してください。デフォルト値は25です。
.. 認証を必須にするには、*認証を使用する*を選択し、ユーザー名とパスワードを入力してください。
.. SMTPサーバーのIDの確認を必須にするには、「トランスポート層セキュリティ（TLS）を使用する」を選択します。次に：
+
... CAバンドルを提供してください。
... SMTPメールサーバーが、メール送信者に認証用のクライアント証明書の提供を要求する場合は、*クライアント証明書を送信*を選択してください。次に、クライアント証明書と秘密鍵を指定してください。


.. メール設定が正しいことを確認するには、送信者と受信者を入力してテストメールを送信してください。「送信」を選択します。
+
テスト用 E メールが送信されたことを示す確認メッセージが表示されます。

.. すべての E メール受信者の受信ボックスを調べて、テスト用 E メールが受信されたことを確認します。
+

NOTE: 数分以内に電子メールが受信されない場合、または * 電子メール通知エラー * アラートがトリガーされた場合は、設定を確認してから再試行してください。

.. 他の管理ノードにサインインし、テスト用 E メールを送信してすべてのサイトからの接続を確認します。
+

NOTE: アラート通知をテストするときは、すべての管理ノードにサインインして接続を確認する必要があります。これは、すべての管理ノードがテストEメールを送信するAutoSupportパッケージのテストとは対照的です。



. [ 保存（ Save ） ] を選択します。
+
テストメールを送信しても、設定は保存されません。「保存」を選択してください。

+
E メール設定が保存されます。

. メールサーバーを使用する機能の設定ページに移動し、メール通知の設定を完了してください。
+
** link:../monitor/email-alert-notifications.html["アラート"]。アラートについては、link:../monitor/snmp-alert-notifications.html["SNMP通知を設定する"]。
** link:../monitor/configure-autosupport-grid-manager.html["AutoSupport"]。AutoSupport パッケージは、電子メール、HTTPS、または HTTP で送信できます（HTTP は推奨されません）。
** link:../admin/configure-multi-admin-verify.html["マルチ管理者認証（MAV）"]。



