---
permalink: monitor/configuring-snmp-agent.html 
sidebar: sidebar 
keywords: snmp agent, mib, trap, inform 
summary: 読み取り専用のMIBアクセスと通知にサードパーティ製のSNMP管理システムを使用するように、StorageGRID SNMPエージェントを設定できます。 
---
= SNMP エージェントを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
読み取り専用のMIBアクセスと通知にサードパーティ製のSNMP管理システムを使用するように、StorageGRID SNMPエージェントを設定できます。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたはを持っていますlink:../admin/admin-group-permissions.html["rootアクセス権限"]。


.タスクの内容
StorageGRIDのSNMPエージェントは、SNMPv1、SNMPv2c、およびSNMPv3をサポートしています。エージェントは 1 つ以上のバージョンに設定できます。SNMPv3では、ユーザセキュリティモデル（USM）認証のみがサポートされます。

グリッド内のすべてのノードが同じSNMP設定を使用します。



== 基本設定の指定

最初の手順として、StorageGRID SMNPエージェントを有効にし、基本情報を提供します。

.手順
. * configuration * > * Monitoring * > * SNMP agent * を選択します。
+
[SNMP agent]ページが表示されます。

. すべてのグリッドノードでSNMPエージェントを有効にするには、*[SNMPを有効にする]*チェックボックスを選択します。
. [Basic configuration]セクションに次の情報を入力します。
+
[cols="1a,2a"]
|===
| フィールド | 製品説明 


 a| 
システムの連絡先
 a| 
オプション。StorageGRIDシステムのプライマリ連絡先。SNMPメッセージでsysContactとして返されます。

システムの連絡先は通常、Eメールアドレスです。この値は、StorageGRIDシステム内のすべてのノードを環境に設定します。*システム連絡先*は最大255文字です。



 a| 
システムの場所
 a| 
オプション。StorageGRIDシステムの場所。SNMPメッセージでsysLocationとして返されます。

システムの場所には、StorageGRIDシステムの場所を特定するのに役立つ任意の情報を指定できます。たとえば、施設の住所を使用できます。この値は、StorageGRIDシステム内のすべてのノードを環境に設定します。*システムの場所*の最大文字数は255文字です。



 a| 
SNMPエージェント通知の有効化
 a| 
** 選択すると、StorageGRID SNMPエージェントはトラップおよびインフォーム通知を送信します。
** 選択しない場合、SNMPエージェントは読み取り専用MIBアクセスをサポートしますが、SNMP通知は送信しません。




 a| 
認証トラップを有効にする
 a| 
このオプションを選択すると、不適切に認証されたプロトコルメッセージを受信すると、StorageGRID SNMPエージェントは認証トラップを送信します。

|===




== コミュニティストリングの入力

SNMPv1またはSNMPv2cを使用する場合は、[Community Strings]セクションに情報を入力します。

管理システムが StorageGRID MIB を照会すると、コミュニティストリングが送信されます。コミュニティストリングがここで指定した値のいずれかと一致すると、 SNMP エージェントは管理システムに応答を送信します。

.手順
. 読み取り専用コミュニティ*には、必要に応じてコミュニティストリングを入力し、IPv4およびIPv6エージェントアドレスでの読み取り専用MIBアクセスを許可します。
+

TIP: StorageGRIDシステムのセキュリティを確保するために、コミュニティストリングとして「public」を使用しないでください。このフィールドを空白のままにすると、StorageGRIDシステムのグリッドIDがコミュニティストリングとして使用されます。

+
各コミュニティストリングの最大文字数は32文字で、空白文字は使用できません。

. [別のコミュニティ文字列を追加する]*を選択して、文字列を追加します。
+
最大 5 つの文字列を指定できます。





== [[select_trap_destination]]トラップ送信先の作成

[Other configurations]セクションの[Trap destinations]タブを使用して、StorageGRIDトラップまたはインフォーム通知の送信先を1つ以上定義します。SNMPエージェントを有効にして*[保存]*を選択すると、アラートがトリガーされたときにStorageGRIDから定義された各送信先に通知が送信されます。標準通知は、サポートされている MIB-II エンティティ（ ifdown や coldStart など）についても送信されます。

.手順
. [Default trap community]フィールドに、SNMPv1またはSNMPv2トラップの送信先に使用するデフォルトのコミュニティストリングをオプションで入力します。
+
特定のトラップ送信先を定義するときは、必要に応じて別の（「カスタム」）コミュニティストリングを指定できます。

+
*デフォルトのトラップコミュニティ*は最大32文字で、空白文字は使用できません。

. トラップ送信先を追加するには、*[作成]*を選択します。
. このトラップ送信先に使用するSNMPのバージョンを選択します。
. [トラップ送信先の作成]フォームに、選択したバージョンの情報を入力します。
+
[role="tabbed-block"]
====
.SNMPv1
--
バージョンとしてSNMPv1を選択した場合は、これらのフィールドに値を入力します。

[cols="1a,2a"]
|===
| フィールド | 製品説明 


 a| 
タイプ
 a| 
SNMPv1のトラップである必要があります。



 a| 
ホスト
 a| 
トラップを受信するIPv4またはIPv6アドレス、または完全修飾ドメイン名（FQDN）。



 a| 
ポート
 a| 
別の値を使用する必要がないかぎり、SNMPトラップの標準ポートである162を使用します。



 a| 
プロトコル
 a| 
TCPを使用する必要がないかぎり、標準のSNMPトラッププロトコルであるUDPを使用します。



 a| 
コミュニティストリング
 a| 
デフォルトのトラップコミュニティ（指定されている場合）を使用するか、このトラップ送信先のカスタムコミュニティストリングを入力します。

カスタムコミュニティストリングの最大文字数は32文字で、空白は使用できません。

|===
--
.SNMPv2c
--
バージョンとしてSNMPv2cを選択した場合は、これらのフィールドに値を入力します。

[cols="1a,2a"]
|===
| フィールド | 製品説明 


 a| 
タイプ
 a| 
送信先をトラップまたはインフォームのどちらに使用するか。



 a| 
ホスト
 a| 
トラップを受信するIPv4、IPv6アドレス、またはFQDN。



 a| 
ポート
 a| 
別の値を使用する必要がないかぎり、SNMPトラップの標準ポートである162を使用します。



 a| 
プロトコル
 a| 
TCPを使用する必要がないかぎり、標準のSNMPトラッププロトコルであるUDPを使用します。



 a| 
コミュニティストリング
 a| 
デフォルトのトラップコミュニティ（指定されている場合）を使用するか、このトラップ送信先のカスタムコミュニティストリングを入力します。

カスタムコミュニティストリングの最大文字数は32文字で、空白は使用できません。

|===
--
.SNMPv3
--
バージョンとしてSNMPv3を選択した場合は、これらのフィールドに値を入力します。

[cols="1a,2a"]
|===
| フィールド | 製品説明 


 a| 
タイプ
 a| 
送信先をトラップまたはインフォームのどちらに使用するか。



 a| 
ホスト
 a| 
トラップを受信するIPv4、IPv6アドレス、またはFQDN。



 a| 
ポート
 a| 
別の値を使用する必要がないかぎり、SNMPトラップの標準ポートである162を使用します。



 a| 
プロトコル
 a| 
TCPを使用する必要がないかぎり、標準のSNMPトラッププロトコルであるUDPを使用します。



 a| 
USMユーザ
 a| 
認証に使用するUSMユーザ。

** [*Trap] を選択した場合は、権限のあるエンジン ID を持たない USM ユーザだけが表示されます。
** *INFORM を選択した場合は、権限のあるエンジン ID を持つ USM ユーザのみが表示されます。
** ユーザが表示されない場合：
+
... トラップ送信先を作成して保存します。
... に移動<<create-usm-users,USMユーザの作成>>してユーザを作成します。
... [トラップ送信先]タブに戻り、テーブルから保存先を選択して*[編集]*を選択します。
... ユーザを選択します。




|===
--
====
. 「 * Create * 」を選択します。
+
トラップの送信先が作成され、テーブルに追加されます。





== エージェントアドレスの作成

必要に応じて、[その他の設定]セクションの[エージェントアドレス]タブを使用して、1つ以上の「リスニングアドレス」を指定します。SNMPエージェントがクエリを受信できるStorageGRIDアドレスです。

エージェントアドレスを設定しない場合、デフォルトのリスニングアドレスはすべてのStorageGRID ネットワークのUDPポート161です。

.手順
. 「 * Create * 」を選択します。
. 次の情報を入力します。
+
[cols="1a,2a"]
|===
| フィールド | 製品説明 


 a| 
インターネットプロトコル
 a| 
このアドレスでIPv4とIPv6のどちらを使用するか。

デフォルトでは、 SNMP は IPv4 を使用します。



 a| 
転送プロトコル
 a| 
このアドレスがUDPとTCPのどちらを使用するか。

デフォルトでは、 SNMP は UDP を使用します。



 a| 
StorageGRIDネットワーク
 a| 
エージェントがリッスンするStorageGRIDネットワーク。

** グリッドネットワーク、管理ネットワーク、クライアントネットワーク：SNMPエージェントは3つのネットワークすべてでクエリをリスンします。
** グリッドネットワーク
** 管理ネットワーク
** クライアントネットワーク
+
*注*：セキュアでないデータにクライアントネットワークを使用し、クライアントネットワークのエージェントアドレスを作成する場合は、SNMPトラフィックもセキュアではないことに注意してください。





 a| 
ポート
 a| 
必要に応じて、SNMPエージェントがリスンするポート番号。

SNMP エージェントのデフォルトの UDP ポートは 161 ですが、未使用のポート番号は任意に入力できます。

*注*：SNMPエージェントを保存すると、StorageGRIDは内部ファイアウォールのエージェントアドレスポートを自動的に開きます。これらのポートへのアクセスが外部ファイアウォールで許可されていることを確認してください。

|===
. 「 * Create * 」を選択します。
+
エージェントアドレスが作成され、テーブルに追加されます。





== [[create-usm-users]] USMユーザの作成

SNMPv3を使用している場合は、[Other configurations]セクションの[USM Users]タブを使用して、MIBの照会やトラップとインフォームの受信を許可するUSMユーザを定義します。


NOTE: SNMPv3_inform_destinationsには、エンジンIDを持つユーザが必要です。SNMPv3_trap_destinationには、エンジンIDを持つユーザを指定できません。

これらの手順は、SNMPv1またはSNMPv2cのみを使用している場合は適用されません。

.手順
. 「 * Create * 」を選択します。
. 次の情報を入力します。
+
[cols="1a,2a"]
|===
| フィールド | 製品説明 


 a| 
ユーザ名
 a| 
このUSMユーザの一意の名前。

ユーザ名の最大文字数は32文字で、空白文字は使用できません。ユーザの作成後にユーザ名を変更することはできません。



 a| 
読み取り専用MIBアクセス
 a| 
選択した場合、このユーザにはMIBへの読み取り専用アクセス権が必要です。



 a| 
信頼できるエンジンID
 a| 
このユーザをインフォーム送信先で使用する場合は、このユーザの信頼できるエンジンID。

10～64の16進数（5～32バイト）をスペースなしで入力します。この値は、インフォームのトラップ送信先で選択されるUSMユーザに必要です。トラップのトラップ送信先で選択されるUSMユーザにはこの値を指定できません。

*注*：*読み取り専用MIBアクセス*を選択した場合、このフィールドは表示されません。これは、読み取り専用MIBアクセスを持つUSMユーザにはエンジンIDを設定できないためです。



 a| 
セキュリティレベル
 a| 
USMユーザのセキュリティレベル：

** * authPriv * ：認証とプライバシー（暗号化）と通信します。認証プロトコルとパスワード、およびプライバシープロトコルとパスワードを指定する必要があります。
** * authNoPriv * ：このユーザは認証と通信し、プライバシーはありません（暗号化なし）。認証プロトコルとパスワードを指定する必要があります。




 a| 
認証プロトコル
 a| 
常に、サポートされている唯一のプロトコル（HMAC-SHA-96）であるSHAに設定します。



 a| 
パスワード
 a| 
このユーザが認証に使用するパスワード。



 a| 
プライバシープロトコル
 a| 
* authPriv *を選択し、常にAES（サポートされている唯一のプライバシープロトコル）に設定されている場合にのみ表示されます。



 a| 
パスワード
 a| 
「* authPriv *」を選択した場合にのみ表示されます。このユーザがプライバシーのために使用するパスワード。

|===
. 「 * Create * 」を選択します。
+
USM ユーザが作成され、テーブルに追加されます。

. SNMPエージェントの設定が完了したら、*[保存]*を選択します。
+
新しい SNMP エージェント設定がアクティブになります。


