---
permalink: monitor/disabling-alert-rules.html 
sidebar: sidebar 
keywords: how to disable alert rules, how to remove a custom alert rule 
summary: デフォルトまたはカスタムのアラートルールの有効 / 無効の状態を変更できます。 
---
= アラートルールを無効化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
デフォルトまたはカスタムのアラートルールの有効 / 無効の状態を変更できます。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたはを持っていますlink:../admin/admin-group-permissions.html["アラートまたはRoot Access権限を管理します。"]。


.タスクの内容
アラートルールを無効にすると、ルールの式は評価されず、アラートはトリガーされません。


CAUTION: 通常は、デフォルトのアラートルールを無効にすることは推奨されません。アラートルールが無効になっている場合は、重大な処理を完了できなくなるまで、根本的な問題が検出されない可能性があります。

.手順
. [* alerts] * > [* Rules] を選択します。
+
[Alert Rules] ページが表示されます。

. 無効または有効にするアラートルールのラジオボタンを選択します。
. [ * ルールの編集 * ] を選択します。
+
Edit Rule ダイアログボックスが表示されます。

. [有効]*チェックボックスをオンまたはオフにして、このアラートルールが現在有効になっているかどうかを確認します。
+
アラートルールを無効にすると、ルールの式は評価されず、アラートはトリガーされません。

+

NOTE: 現在のアラートのアラートルールを無効にした場合は、アラートがアクティブなアラートとして表示されなくなるまで数分待つ必要があります。

. [ 保存（ Save ） ] を選択します。
+
* 無効 * は、 * ステータス * 列に表示されます。


