---
permalink: monitor/manage-io-prioritization.html 
sidebar: sidebar 
keywords: ec repair priority, ec purge priority 
summary: '入出力 (I/O) の優先順位付けにより、グリッド上の I/O 操作の相対的な優先順位を変更できます。' 
---
= I/Oの優先順位を変更する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
入出力 (I/O) の優先順位付けにより、グリッド上の I/O 操作の相対的な優先順位を変更できます。

デフォルトでは、クライアントの PUT および GET I/O トラフィックには、消失訂正符号化 (EC) データの消去や EC 修復などのバックグラウンド アクティビティよりも最高の優先順位が与えられます。消失訂正符号化 (EC) データの消去と EC 修復アクティビティの優先度を上げると、これらのタスクをより早く完了できる可能性があります。  I/O 優先順位の変更の有効性は、クライアント要求のレート、ネットワーク トラフィックの変動、その他の進行中のネットワーク タスクによって影響を受けます。

.開始する前に
* I/O 優先順位付けページを確認し、どのオプションがグリッドに影響を与える可能性があるかを判断します。
* 進行中のクライアント トラフィックが、より長い待機時間やクライアント タイムアウトを安全に処理できるかどうかを評価します。
* 優先順位の変更による影響を監視し、必要に応じて調整する準備をしてください。これらの変更はすぐに実装されますが、その効果が目に見えるようになるまでには数時間かかる場合があります。


.手順
. *サポート* > *I/O 優先順位* を選択します。
. (オプション) EC データを消去するバックグラウンド操作の EC パージおよび修復の優先度をデフォルト値から変更します。
+

NOTE: RAID ベースのノードを持つグリッドには、デフォルトの低い EC パージおよび修復優先度を使用します。

. [ 保存（ Save ） ] を選択します。
. 監視するlink:../monitor/commonly-used-prometheus-metrics.html#where-are-prometheus-metrics-used["指標"]優先順位の変更による影響を評価するため。

