---
permalink: monitor/monitoring-information-lifecycle-management.html 
sidebar: sidebar 
keywords: lifecycle management, lifecycle, monitoring, ILM, information lifecycle management 
summary: 情報ライフサイクル管理（ ILM ）システムは、グリッドに格納されているすべてのオブジェクトのデータ管理を提供します。グリッドが現在の負荷に対応できるかどうか、またはリソースの追加が必要かどうかを判断するには、ILM処理を監視する必要があります。 
---
= 情報ライフサイクル管理を監視
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Information Lifecycle Management （ ILM ；情報ライフサイクル管理）システムは、グリッドに格納されているすべてのオブジェクトのデータ管理を提供します。グリッドが現在の負荷に対応できるかどうか、またはリソースの追加が必要かどうかを判断するには、ILM処理を監視する必要があります。

.タスクの内容
StorageGRIDシステムは、アクティブなILMポリシーを適用することでオブジェクトを管理します。ILMポリシーと関連するILMルールによって、作成するコピーの数、作成するコピーのタイプ、配置場所、各コピーの保持期間が決まります。

オブジェクトの取り込みやその他のオブジェクト関連アクティビティは、StorageGRID によるILMの評価速度を超える可能性があります。そのため、ILMの配置手順をほぼリアルタイムで実行できないオブジェクトがキューに登録されます。StorageGRIDがクライアント操作に対応しているかどうかを監視する必要があります。



== Grid Managerのダッシュボードタブを使用する

.手順
Grid Managerのダッシュボードの[ILM]タブを使用して、ILMの処理を監視します。

. Grid Manager にサインインします。
. ダッシュボードで[ILM]タブを選択し、ILMキュー（オブジェクト）カードとILM評価レートカードの値をメモします。
+
ダッシュボードのILMキュー（オブジェクト）カードが一時的に急増することが想定されます。ただし、キューが増え続けて減少することがない場合、グリッドが効率的に動作するには、ストレージノードを追加するか、ILMポリシーにオブジェクトがリモートサイトに配置されている場合はネットワーク帯域幅を増やす必要があります。





== [Nodes]ページを使用

.手順
さらに、* nodes *ページを使用してILMキューを調査します。


NOTE: StorageGRIDの今後のリリースで、* nodes *ページのチャートは対応するダッシュボードカードに置き換えられる予定です。

. [* nodes （ノード） ] を選択します
. *_grid name_*>*ilm * を選択します。
. ILMキューのグラフにカーソルを合わせると、ある時点における次の属性の値が表示されます。
+
** * Objects queued （ from client operations ） * ：クライアント処理（取り込みなど）のために ILM による評価を待機しているオブジェクトの総数。
** * Objects queued （ from all operations ） * ： ILM による評価を待機しているオブジェクトの総数。
** * Scan rate （ objects/sec ） * ：グリッドのオブジェクトがスキャンされて ILM のキューに登録される速度。
** * 評価速度（オブジェクト数 / 秒） * ：グリッド内の ILM ポリシーに照らしてオブジェクトが評価されている現在の速度。


. ILM キューセクションで、次の属性を確認します。
+

NOTE: [ILM queue]セクションはグリッド専用です。この情報は、サイトまたはストレージノードの ILM タブには表示されません。

+
** * Scan Period - Estimated *：ILMによるすべてのオブジェクトのフルスキャンが完了するまでの推定時間。
+

NOTE: フルスキャンが完了しても、 ILM がすべてのオブジェクトに適用されるとは限りません。

** * Repairs Attempted *：レプリケートデータに対して試行されたオブジェクト修復処理の総数。この数は、ストレージノードがハイリスクオブジェクトの修復を試みるたびに増分します。グリッドがビジー状態になった場合は、リスクの高い ILM の修復が優先されます。
+

NOTE: 修復後にレプリケーションに失敗した場合は、同じオブジェクトの修復で再び増分される可能性があります。



+
これらの属性は、ストレージノードのボリュームリカバリの進捗状況を監視する場合に役立ちます。試行された修理の回数が増えなくなり、フルスキャンが完了した場合は、修理が完了している可能性があります。


