---
permalink: monitor/monitoring-load-balancing-operations.html 
sidebar: sidebar 
keywords: load balancing, monitoring 
summary: ロードバランサを使用して StorageGRID へのクライアント接続を管理している場合は、システムを最初に設定したあとと、設定を変更したり拡張を行ったあとに、ロードバランシング処理を監視する必要があります。 
---
= ロードバランシング処理を監視する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ロードバランサを使用して StorageGRID へのクライアント接続を管理している場合は、システムを最初に設定したあとと、設定を変更したり拡張を行ったあとに、ロードバランシング処理を監視する必要があります。

.タスクの内容
管理ノードまたはゲートウェイノード上のロードバランササービス、または外部の他社製ロードバランサを使用して、複数のストレージノードにクライアント要求を分散できます。

ロードバランシングを設定したら、オブジェクトの取り込みと読み出しの処理がストレージノード間で均等に分散されていることを確認する必要があります。要求が均等に分散されるため、 StorageGRID は負荷がかかっているクライアント要求への応答性を維持し、クライアントのパフォーマンスを維持できます。

ゲートウェイノードまたは管理ノードのハイアベイラビリティ（ HA ）グループをアクティブ / バックアップモードで設定した場合、グループ内の 1 つのノードだけがクライアント要求をアクティブに分散します。

詳細については、を参照してください link:../admin/configuring-client-connections.html["S3クライアント接続の設定"]。

.手順
. S3クライアントがロードバランササービスを使用して接続する場合は、管理ノードまたはゲートウェイノードが想定どおりにトラフィックをアクティブに分散していることを確認します。
+
.. [* nodes （ノード） ] を選択します
.. ゲートウェイノードまたは管理ノードを選択します。
.. [概要]*タブで、ノードインターフェイスがHAグループに含まれているかどうか、およびノードインターフェイスのロールがプライマリであるかどうかを確認します。
+
プライマリの役割を持つノードとHAグループに属していないノードは、クライアントに要求をアクティブに分散している必要があります。

.. クライアント要求をアクティブに分散する必要がある各ノードについて、を選択しますlink:viewing-load-balancer-tab.html["[Load Balancer]タブ"]。
.. 過去 1 週間のロードバランサ要求トラフィックのチャートを確認して、ノードが要求をアクティブに分散していることを確認します。
+
アクティブ / バックアップ HA グループのノードでは、 Backup ロールが随時割り当てられる場合があります。この間、ノードはクライアント要求を分散しません。

.. ノードのオブジェクトスループットを確認するには、過去 1 週間のロードバランサの受信要求速度のグラフを確認します。
.. StorageGRID システムの管理ノードまたはゲートウェイノードごとに上記の手順を繰り返します。
.. 必要に応じて、トラフィック分類ポリシーを使用して、ロードバランササービスで処理されているトラフィックのより詳細な分析を表示します。


. これらの要求がストレージノードに均等に分散されていることを確認します。
+
.. 「 * _ ストレージノード _ * > * LDR * > * HTTP * 」を選択します。
.. 現在確立されている受信セッション数 * を確認します。
.. グリッド内のストレージノードごとにこの手順を繰り返します。
+
セッションの数はすべてのストレージノードでほぼ同じにします。




