---
permalink: monitor/monitoring-put-and-get-performance.html 
sidebar: sidebar 
keywords: put, get, performance 
summary: オブジェクトストアや読み出しなどの特定の処理のパフォーマンスを監視して、詳しい調査が必要な変更を特定することができます。 
---
= PUT / GET パフォーマンスを監視
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
オブジェクトストアや読み出しなどの特定の処理のパフォーマンスを監視して、詳しい調査が必要な変更を特定することができます。

.タスクの内容
PUTおよびGETのパフォーマンスを監視するには、S3コマンドをワークステーションから直接実行するか、オープンソースのS3testerアプリケーションを使用します。これらの方法を使用すると、クライアントアプリケーションの問題や外部ネットワークの問題など、 StorageGRID の外部にある要因とは関係なくパフォーマンスを評価できます。

PUT 処理と GET 処理のテストを実行するときは、次のガイドラインに従ってください。

* グリッドに通常取り込むオブジェクトと同等のサイズのオブジェクトを使用します。
* ローカルサイトとリモートサイトの両方に対して処理を実行します。


のメッセージにはlink:../audit/index.html["監査ログ"]、特定の処理の実行に必要な合計時間が示されます。たとえば、 S3 GET 要求に対する合計処理時間を確認するには、 SGET 監査メッセージの TIME 属性の値を確認します。また、DELETE、GET、HEAD、Metadata Updated、POST、PUTの各S3処理の監査メッセージでTIME属性を確認することもできます。

結果を分析する際には、要求を満たすために必要な平均時間と、達成可能な全体的なスループットを確認します。同じテストを定期的に繰り返し、結果を記録して、調査が必要な傾向を特定できるようにします。

* できます https://github.com/s3tester["github から S3tester をダウンロードします"^]。

