---
permalink: monitor/reviewing-audit-messages.html 
sidebar: sidebar 
keywords: how to review audit messages, how to view audit messages 
summary: 監査メッセージは、 StorageGRID システムの詳細な運用状況を的確に把握するために役立ちます。監査ログを使用して、問題のトラブルシューティングやパフォーマンスの評価を行うことができます。 
---
= 監査メッセージを確認します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
監査メッセージは、 StorageGRID システムの詳細な運用状況を的確に把握するために役立ちます。監査ログを使用して、問題のトラブルシューティングやパフォーマンスの評価を行うことができます。

通常のシステム運用中、すべての StorageGRID サービスは次の監査メッセージを生成します。

* システム監査メッセージは、監査システム自体、グリッドノードの状態、システム全体のタスクアクティビティ、およびサービスバックアップ処理に関連します。
* オブジェクトストレージの監査メッセージは、オブジェクトの格納と読み出し、グリッドノードからグリッドノードへの転送、検証など、 StorageGRID 内のオブジェクトの格納と管理に関連します。
* クライアントの読み取り/書き込み監査メッセージは、S3クライアントアプリケーションがオブジェクトの作成、変更、または読み出しを要求するときに記録されます。
* 管理監査メッセージには、管理 API に対するユーザ要求が記録されます。


各管理ノードで、監査メッセージがテキストファイルに保存されます。監査共有には、アクティブファイル（ audit.log ）と、圧縮された過去の監査ログが含まれています。グリッド内の各ノードには、ノードで生成された監査情報のコピーも格納されます。

監査ログファイルには、管理ノードのコマンドラインから直接アクセスできます。

StorageGRIDでは、デフォルトで監査情報を送信することも、送信先を変更することもできます。

* StorageGRIDはデフォルトでローカルノードの監査デスティネーションに設定されます。
* Grid ManagerおよびTenant Managerの監査ログエントリがストレージノードに送信されることがあります。
* 必要に応じて、監査ログのデスティネーションを変更したり、監査情報を外部 syslog サーバに送信したりできます。外部 syslog サーバが設定されても、監査レコードのローカルログは引き続き生成および格納されます。
* link:../monitor/configure-log-management.html["ログ管理の構成について学ぶ"] 。


監査ログファイル、監査メッセージの形式、監査メッセージのタイプ、および監査メッセージの分析に使用できるツールの詳細については、を参照してくださいlink:../audit/index.html["監査ログを確認します"]。
