---
permalink: monitor/updating-snmp-agent.html 
sidebar: sidebar 
keywords: how to update the SNMP agent 
summary: SNMP通知を無効にしたり、コミュニティストリングを更新したり、エージェントアドレス、USMユーザ、トラップ送信先を追加または削除したりできます。 
---
= SNMP エージェントを更新します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SNMP通知を無効にしたり、コミュニティストリングを更新したり、エージェントアドレス、USMユーザ、トラップ送信先を追加または削除したりできます。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたはを持っていますlink:../admin/admin-group-permissions.html["rootアクセス権限"]。


.タスクの内容
SNMPエージェントページの各フィールドの詳細については、を参照してくださいlink:configuring-snmp-agent.html["SNMP エージェントを設定します"]。各タブで行った変更をコミットするには、ページの下部にある*[保存]*を選択する必要があります。

.手順
. * configuration * > * Monitoring * > * SNMP agent * を選択します。
+
[SNMP agent]ページが表示されます。

. すべてのグリッドノードでSNMPエージェントを無効にするには、*[Enable SNMP]*チェックボックスをオフにし、*[Save]*を選択します。
+
SNMPエージェントを再度有効にすると、以前のSNMP設定がすべて保持されます。

. 必要に応じて、[Basic configuration]セクションの情報を更新します。
+
.. 必要に応じて、*システムの連絡先*と*システムの場所*を更新します。
.. 必要に応じて、[SNMPエージェント通知を有効にする]*チェックボックスをオンまたはオフにして、StorageGRID SNMPエージェントがトラップおよびインフォーム通知を送信するかどうかを制御します。
+
このチェックボックスをオフにすると、SNMPエージェントは読み取り専用のMIBアクセスをサポートしますが、SNMP通知は送信しません。

.. 必要に応じて、*[認証トラップを有効にする]*チェックボックスをオンまたはオフにして、不適切に認証されたプロトコルメッセージを受信したときにStorageGRID SNMPエージェントが認証トラップを送信するかどうかを制御します。


. SNMPv1またはSNMPv2cを使用する場合は、必要に応じて[コミュニティストリング]セクションで*読み取り専用コミュニティ*を更新または追加します。
. トラップ送信先を更新するには、[Other configurations]セクションの[Trap destinations]タブを選択します。
+
このタブを使用して、StorageGRIDトラップまたはインフォーム通知の送信先を定義します。SNMPエージェントを有効にして*[保存]*を選択すると、アラートがトリガーされたときにStorageGRIDから定義された各送信先に通知が送信されます。標準通知は、サポートされている MIB-II エンティティ（ ifdown や coldStart など）についても送信されます。

+
入力する項目の詳細については、を参照してくださいlink:../monitor/configuring-snmp-agent.html#create-trap-destinations["トラップ送信先の作成"]。

+
** 必要に応じて、デフォルトのトラップコミュニティを更新または削除します。
+
デフォルトのトラップコミュニティを削除する場合は、既存のトラップ送信先でカスタムのコミュニティストリングが使用されていることを最初に確認する必要があります。

** トラップ送信先を追加するには、*[作成]*を選択します。
** トラップ送信先を編集するには、ラジオボタンを選択し、*[編集]*を選択します。
** トラップ送信先を削除するには、ラジオボタンを選択して*[削除]*を選択します。
** 変更をコミットするには、ページの下部にある*[保存]*を選択します。


. エージェントアドレスを更新するには、[その他の設定]セクションの[エージェントアドレス]タブを選択します。
+
このタブを使用して、1つまたは複数の「リスニングアドレス」を指定します。SNMPエージェントがクエリを受信できるStorageGRIDアドレスです。

+
入力する項目の詳細については、を参照してくださいlink:../monitor/configuring-snmp-agent.html#create-agent-addresses["エージェントアドレスの作成"]。

+
** エージェントアドレスを追加するには、*[作成]*を選択します。
** エージェントアドレスを編集するには、ラジオボタンを選択し、*[編集]*を選択します。
** エージェントアドレスを削除するには、ラジオボタンを選択し、*[削除]*を選択します。
** 変更をコミットするには、ページの下部にある*[保存]*を選択します。


. USMユーザを更新するには、[Other configurations]セクションで[USM Users]タブを選択します。
+
このタブを使用して、 MIB の照会またはトラップおよびインフォームの受信を許可されている USM ユーザを定義します。

+
入力する項目の詳細については、を参照してくださいlink:../monitor/configuring-snmp-agent.html#create-usm-users["USMユーザの作成"]。

+
** USMユーザを追加するには、*[作成]*を選択します。
** USMユーザを編集するには、ラジオボタンを選択し、*[編集]*を選択します。
+
既存のUSMユーザのユーザ名は変更できません。ユーザ名を変更する必要がある場合は、ユーザを削除して新しいユーザを作成する必要があります。

+

NOTE: ユーザーの権限のあるエンジンIDを追加または削除し、そのユーザーが宛先に対して現在選択されている場合は、宛先を編集または削除する必要があります。そうしないと、 SNMP エージェント設定を保存したときに検証エラーが発生します。

** USMユーザを削除するには、ラジオボタンを選択し、*[削除]*を選択します。
+

NOTE: 削除したユーザがトラップ送信先として選択されている場合は、送信先を編集または削除する必要があります。そうしないと、 SNMP エージェント設定を保存したときに検証エラーが発生します。

** 変更をコミットするには、ページの下部にある*[保存]*を選択します。


. SNMPエージェントの設定を更新したら、*[保存]*を選択します。

