---
permalink: monitor/using-snmp-monitoring.html 
sidebar: sidebar 
keywords: snmp, monitoring 
summary: 簡易ネットワーク管理プロトコル \ （ SNMP\ ）を使用して StorageGRID を監視する場合は、 StorageGRID に含まれる SNMP エージェントを設定する必要があります。 
---
= SNMP による監視を使用する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
簡易ネットワーク管理プロトコル（ SNMP ）を使用して StorageGRID を監視する場合は、 StorageGRID に含まれる SNMP エージェントを設定する必要があります。

* link:configuring-snmp-agent.html["SNMP エージェントを設定します"]
* link:updating-snmp-agent.html["SNMP エージェントを更新します"]




== 機能

各StorageGRID ノードは、MIBを提供するSNMPエージェント（デーモン）を実行します。StorageGRID MIBには、アラートのテーブルと通知の定義が含まれています。この MIB には、各ノードのプラットフォームやモデル番号など、システムの概要 情報も含まれています。各 StorageGRID ノードは MIB-II オブジェクトのサブセットもサポートしています。


NOTE: グリッドノードにMIBファイルをダウンロードするかどうかを確認しますlink:access-snmp-mib.html["MIBファイルにアクセスします"]。

最初は、すべてのノードで SNMP が無効になっています。SNMP エージェントを設定すると、すべての StorageGRID ノードに同じ設定が適用されます。

StorageGRID SNMP エージェントは、 3 つのバージョンの SNMP プロトコルをすべてサポートします。クエリに読み取り専用 MIB アクセスを提供し、次の 2 種類のイベントベース通知を管理システムに送信できます。

トラップ:: トラップはSNMPエージェントによって送信される通知で、管理システムによる確認応答は必要ありません。トラップは、アラートがトリガーされているなど、 StorageGRID 内で何らかの問題が発生したことを管理システムに通知するために使用されます。
+
--
トラップは、 SNMP の 3 つのバージョンすべてでサポートされています。

--
情報:: 通知はトラップと似ていますが、管理システムによる確認応答が必要です。SNMPエージェントは、一定の時間内に確認応答を受信しなかった場合、確認応答を受信するか、最大再試行値に達するまで、インフォームを再送信します。
+
--
インフォームは SNMPv2c および SNMPv3 でサポートされます。

--


トラップ通知およびインフォーム通知は、次の場合に送信されます。

* デフォルトまたはカスタムのアラートはいずれかの重大度レベルでトリガーされます。アラートのSNMP通知を停止するには、アラートを指定する必要がありますlink:silencing-alert-notifications.html["サイレンスの設定"]。アラート通知はから送信されますlink:../primer/what-admin-node-is.html["優先送信者管理ノード"]。
+
各アラートは、アラートの重大度レベルに基づいて、 activeMinorAlert 、 activeMagajorAlert 、および activeCriticalAlert の 3 つのトラップタイプのいずれかにマッピングされます。これらのトラップをトリガーできるアラートのリストについては、を参照してくださいlink:alerts-reference.html["アラート一覧"]。





== SNMP バージョンサポート

次の表に、各 SNMP バージョンでサポートされる内容の概要を示します。

[cols="1a,2a,2a,2a"]
|===
|  | SNMPv1 | SNMPv2c | SNMPv3 


 a| 
クエリ

（GETおよびGETNEXT）
 a| 
読み取り専用 MIB クエリ
 a| 
読み取り専用 MIB クエリ
 a| 
読み取り専用 MIB クエリ



 a| 
クエリ認証
 a| 
コミュニティストリング
 a| 
コミュニティストリング
 a| 
ユーザベースのセキュリティモデル（ USM ）ユーザ



 a| 
通知

（トラップと通知）
 a| 
トラップのみ
 a| 
トラップおよびインフォーム
 a| 
トラップおよびインフォーム



 a| 
通知認証
 a| 
トラップの送信先ごとに、デフォルトのトラップコミュニティまたはカスタムのコミュニティストリングを指定します
 a| 
トラップの送信先ごとに、デフォルトのトラップコミュニティまたはカスタムのコミュニティストリングを指定します
 a| 
トラップの送信先ごとの USM ユーザ

|===


== 制限事項

* StorageGRID は、読み取り専用 MIB アクセスをサポートしています。読み取り / 書き込みアクセスはサポートされていません。
* グリッド内のすべてのノードが同じ設定を受信します。
* SNMPv3 ： StorageGRID は TSM （ Transport Support Mode ）をサポートしていません。
* SNMPv3 ： SHA （ HMAC-SHA-96 ）だけがサポートされています。
* SNMPv3 ： AES のみがサポートされています。

