---
permalink: maintain/configuring-ip-addresses.html 
sidebar: sidebar 
keywords: configure ip address, change IP tool, ethernet, dhcp, ha group 
summary: IP 変更ツールを使用してグリッドノードの IP アドレスを設定することで、ネットワーク設定を実行できます。 
---
= IPアドレスのガイドライン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IP 変更ツールを使用してグリッドノードの IP アドレスを設定することで、ネットワーク設定を実行できます。

グリッドの導入時に設定されたネットワーク設定を変更するには、ほとんどの場合、 IP 変更ツールを使用する必要があります。標準の Linux ネットワークコマンドおよびファイルを使用して手動で変更すると、すべての StorageGRID サービスに変更が反映されなかったり、アップグレード、リブート、ノードリカバリ手順の実行後に変更が失われたりすることがあります。


NOTE: IP 変更手順 は、停止を伴う手順 の可能性があります。グリッドの一部は、新しい設定が適用されるまで使用できない場合があります。


NOTE: グリッドネットワークサブネットリストのみを変更する場合は、グリッドマネージャを使用してネットワーク設定の追加または変更を行います。グリッドネットワーク設定問題 が原因でグリッドマネージャにアクセスできない場合、またはグリッドネットワークルーティングの変更とその他のネットワーク変更を同時に実行する場合は、 IP 変更ツールを使用します。


TIP: グリッド内のすべてのノードのグリッドネットワークIPアドレスを変更する場合は、を使用しlink:changing-ip-addresses-and-mtu-values-for-all-nodes-in-grid.html["グリッド全体で変更される特殊な手順"]ます。



== イーサネットインターフェイス

eth0 に割り当てられる IP アドレスは、常にグリッドノードのグリッドネットワーク IP アドレスになります。eth1 に割り当てられている IP アドレスは、常にグリッドノードの管理ネットワーク IP アドレスです。eth2 に割り当てられている IP アドレスは、常にグリッドノードのクライアントネットワーク IP アドレスです。

StorageGRID アプライアンスなどの一部のプラットフォームでは、 eth0 、 eth1 、 eth2 が、下位のブリッジで構成されるアグリゲートインターフェイスや物理 / VLAN インターフェイスのボンドである場合があります。これらのプラットフォームでは、 * ssm* > * Resources * タブに、 eth0 、 eth1 、 eth2 に加えて、他のインターフェイスに割り当てられているグリッドネットワーク、管理ネットワーク、およびクライアントネットワークの IP アドレスが表示されることがあります。



== DHCP

DHCP は導入フェーズでのみ設定できます。設定中にDHCPを設定することはできません。グリッドノードの IP アドレス、サブネットマスク、およびデフォルトゲートウェイを変更する場合は、 IP アドレス変更手順を使用する必要があります。IP 変更ツールを使用すると、原因 の DHCP アドレスが静的アドレスになります。



== ハイアベイラビリティ（HA）グループ

* クライアントネットワークインターフェイスがHAグループに含まれている場合、そのインターフェイスのクライアントネットワークIPアドレスを、HAグループに設定されているサブネット外のアドレスに変更することはできません。
* クライアントネットワークのIPアドレスを、クライアントネットワークインターフェイスで設定されたHAグループに割り当てられている既存の仮想IPアドレスの値に変更することはできません。
* グリッドネットワークインターフェイスがHAグループに含まれている場合、そのインターフェイスのグリッドネットワークIPアドレスをHAグループに設定されているサブネット外のアドレスに変更することはできません。
* グリッドネットワークのIPアドレスを、グリッドネットワークインターフェイスに設定されたHAグループに割り当てられている既存の仮想IPアドレスの値に変更することはできません。

