---
permalink: maintain/configuring-ntp-servers.html 
sidebar: sidebar 
keywords: storagegrid, ntp, ntp server, configure ntp, configuring ntp 
summary: ネットワークタイムプロトコル（NTP\）サーバを追加、更新、または削除することで、StorageGRID システム内のグリッドノード間でデータが正確に同期されるようにすることができます。 
---
= NTPサーバを管理します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ネットワークタイムプロトコル（NTP）サーバを追加、更新、または削除して、StorageGRID システムのグリッドノード間でデータが正確に同期されるようにすることができます。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたはを持っていますlink:../admin/admin-group-permissions.html["Maintenance権限またはRoot Access権限"]。
* プロビジョニングパスフレーズを用意します。
* 設定するNTPサーバのIPv4アドレスを確認しておきます。




== StorageGRID でのNTPの使用方法

StorageGRID システムは、ネットワークタイムプロトコル（NTP）を使用して、グリッド内のすべてのグリッドノード間で時間を同期します。

各サイトでは、 StorageGRID システムの少なくとも 2 つのノードにプライマリ NTP ロールが割り当てられます。推奨される最低 4 つ、最大 6 つの外部時間ソース、および相互に同期します。StorageGRID システムのプライマリ NTP ノード以外のノードは、すべて NTP クライアントとして機能し、プライマリ NTP ノードと同期されます。

外部NTPサーバは、以前にプライマリNTPロールを割り当てたノードに接続します。このため、プライマリNTPロールを持つノードを少なくとも2つ指定することを推奨します。



== NTPサーバのガイドライン

タイミングの問題から保護するには、次の注意事項に従ってください。

* 外部NTPサーバは、以前にプライマリNTPロールを割り当てたノードに接続します。このため、プライマリNTPロールを持つノードを少なくとも2つ指定することを推奨します。
* 各サイトの少なくとも2つのノードが、少なくとも4つの外部NTPソースにアクセスできることを確認します。NTP ソースにアクセスできるノードがサイトに 1 つしかないと、そのノードがダウンした場合にタイミングの問題が生じます。また、各サイトで 2 つのノードをプライマリ NTP ソースとして指定することにより、サイトがグリッドの他の部分から分離されても、正確なタイミングが保証されます。
* 指定する外部 NTP サーバは、 NTP プロトコルを使用している必要があります。時間のずれに伴う問題を防ぐには、 Stratum 3 以上の NTP サーバ参照を指定する必要があります。



NOTE: 本番レベルのStorageGRID インストール用に外部NTPソースを指定する場合は、Windows Server 2016より前のバージョンのWindowsでWindows Time (W32Time)サービスを使用しないでください。以前のバージョンのWindowsのタイムサービスは精度が十分ではなく、StorageGRID などの高精度な環境での使用はMicrosoftでサポートされていません。詳細については、を参照してください https://support.microsoft.com/en-us/help/939322/support-boundary-to-configure-the-windows-time-service-for-high-accura["高精度環境用に Windows タイムサービスを構成するためのサポート境界"^]。



== NTPサーバの設定

NTPサーバを追加、更新、または削除する手順は、次のとおりです。

.手順
. [* maintenance * （メンテナンス） ] > [* Network * （ * ネットワーク * ） ] > [* NTP servers * （ * NTP サーバー
. [Servers]セクションで、必要に応じてNTPサーバエントリを追加、更新、または削除します。
+
NTPサーバは少なくとも4つ含める必要があり、最大6つまで指定できます。

. StorageGRID システムのプロビジョニングパスフレーズを入力し、*[保存]*を選択します。
+
設定の更新が完了するまで、ページは無効になります。

+

NOTE: 新しいNTPサーバを保存した後に、すべてのNTPサーバが接続テストに失敗した場合は、続行しないでください。テクニカルサポートにお問い合わせください。





== NTPサーバの問題を解決します

インストール時に指定した最初の NTP サーバの安定性や可用性に問題が生じた場合は、サーバの追加や既存のサーバの更新や削除を行って、 StorageGRID システムが使用する外部 NTP ソースのリストを更新できます。
