---
permalink: maintain/considerations-for-decommissioning-storage-nodes.html 
sidebar: sidebar 
keywords: storage node decommission, considerations, appliance node clone 
summary: ストレージノードの運用を停止する前に、ノードをクローニングできるかどうかを検討してください。その後、ノードの運用を停止する場合は、手順の運用停止時にStorageGRIDがオブジェクトとメタデータをどのように管理するかを確認します。 
---
= ストレージノードの運用停止に関する考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージノードの運用を停止する前に、ノードをクローニングできるかどうかを検討してください。その後、ノードの運用を停止する場合は、手順の運用停止時にStorageGRIDがオブジェクトとメタデータをどのように管理するかを確認します。



== ノードの運用停止ではなくクローンを作成するタイミング

古いアプライアンスストレージノードを新しいアプライアンス以上のアプライアンスに交換する場合は、拡張で新しいアプライアンスを追加してから古いアプライアンスの運用を停止するのではなく、アプライアンスノードをクローニングすることを検討してください。

アプライアンスノードのクローニングを使用すると、同じStorageGRIDサイトにある既存のアプライアンスノードを互換性のあるアプライアンスと簡単に交換できます。クローニングプロセスでは、すべてのデータが新しいアプライアンスに転送され、新しいアプライアンスが稼働状態になり、古いアプライアンスはインストール前の状態のままになります。

アプライアンスノードは、次の処理が必要な場合にクローニングできます。

* 寿命に達しているアプライアンスを交換します。
* 既存のノードをアップグレードして、強化されたアプライアンステクノロジを活用します。
* StorageGRID システム内のストレージノードの数を変更することなく、グリッドのストレージ容量を拡張できます。
* RAIDモードの変更などにより、ストレージ効率が向上します。


詳細は、を参照してください https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/how-appliance-node-cloning-works.html["アプライアンスノードのクローニング"^]。



== 接続されているストレージノードに関する考慮事項

接続されているストレージノードの運用停止に関する考慮事項を確認します。

* 1 つのノードの運用停止手順 では、 10 個を超えるストレージノードの運用を停止しないでください。
* アクティブなやなどの運用要件を満たす十分な数のストレージノードが常にシステムに搭載されている必要がありますlink:understanding-adc-service-quorum.html["ADCクォーラム"]link:reviewing-ilm-policy-and-storage-configuration.html["ILMポリシー"]。この要件を満たすために、拡張処理で新しいストレージノードを追加してから既存のストレージノードの運用を停止することが必要になる場合があります。
+
ソフトウェアベースのメタデータのみのノードを含むグリッド内のストレージノードの運用を停止する場合は注意が必要です。store_both_objectsとmetadataに設定されているすべてのノードの運用を停止すると、オブジェクトを格納する機能がグリッドから削除されます。メタデータ専用ストレージノードの詳細については、を参照してくださいlink:../primer/what-storage-node-is.html#types-of-storage-nodes["ストレージノードのタイプ"]。

* ストレージノードを削除すると、大量のオブジェクトデータがネットワーク経由で転送されます。この転送が通常のシステム処理に影響することはありませんが、StorageGRIDシステムが消費するネットワーク帯域幅の総量に影響する可能性があります。
* ストレージノードの運用停止に関連するタスクは、通常のシステム処理に関連するタスクよりも優先度が低くなっています。つまり、運用停止処理が StorageGRID の通常のシステム処理を妨げることはなく、システムがアクティブでない期間に運用停止処理をスケジュールする必要もありません。運用停止処理はバックグラウンドで実行されるため、プロセスの所要時間を見積もることは困難です。一般に、システムがビジー状態でないとき、または一度に 1 つのストレージノードのみを削除するときは、運用停止処理が迅速に終了します。
* ストレージノードの運用停止には、数日から数週間かかることがあります。それに応じてこの手順 を計画してください運用停止プロセスはシステム処理に影響しないように設計されていますが、他の手順が制限される可能性があります。一般に、システムのアップグレードや拡張を計画している場合は、グリッドノードを削除する前に実行する必要があります。
* ストレージノードの削除中に別のメンテナンス手順を実行する必要がある場合は、別の手順の完了後に再開できますlink:pausing-and-resuming-decommission-process-for-storage-nodes.html["運用停止手順を一時停止します。"]。
+

NOTE: * Pause * ボタンは、 ILM 評価またはイレイジャーコーディングデータの運用停止ステージに達したときにのみ有効になります。ただし、 ILM 評価（データ移行）はバックグラウンドで継続して実行されます。

* 運用停止タスクの実行中は、どのグリッドノードでもデータ修復処理を実行できません。
* ストレージノードの運用停止中は、ILMポリシーに変更を加えないでください。
* データを完全かつ安全に削除するには、運用停止手順の完了後にストレージノードのドライブを消去する必要があります。




== 切断されているストレージノードに関する考慮事項

切断されているストレージノードの運用停止に関する考慮事項を確認してください。

* 切断されているノードは、オンラインにしたりリカバリしたりできないことが確実である場合を除き、運用停止しないでください。
+

CAUTION: ノードからオブジェクトデータをリカバリできる可能性がある場合は、この手順 を実行しないでください。代わりに、テクニカルサポートに問い合わせて、ノードのリカバリが可能かどうかを確認してください。

* 切断されているストレージノードの運用を停止すると、StorageGRIDは他のストレージノードのデータを使用して、切断されているノード上にあったオブジェクトデータとメタデータを再構築します。
* 切断されている複数のストレージノードの運用を停止すると、データが失われる可能性があります。十分な数のオブジェクトコピー、イレイジャーコーディングフラグメント、またはオブジェクトメタデータが残っていると、システムがデータを再構築できない場合があります。ソフトウェアベースのメタデータ専用ノードがあるグリッド内のストレージノードの運用を停止する場合は、オブジェクトとメタデータの両方を格納するように設定されたすべてのノードの運用を停止すると、グリッドからすべてのオブジェクトストレージが削除されます。メタデータ専用ストレージノードの詳細については、を参照してくださいlink:../primer/what-storage-node-is.html#types-of-storage-nodes["ストレージノードのタイプ"]。
+

CAUTION: 切断されていてリカバリできないストレージノードが複数ある場合は、テクニカルサポートに連絡して、最適な対処方法を確認してください。

* 切断されているストレージノードの運用を停止すると、 StorageGRID は運用停止手順の終了時にデータ修復ジョブを開始します。これらのジョブは、切断されているノードに格納されていたオブジェクトデータとメタデータの再構築を試みます。
* 切断されているストレージノードの運用を停止する場合、手順 の運用停止は比較的短時間で完了します。ただし、データ修復ジョブは実行に数日から数週間かかることがあり、運用停止手順 によって監視されません。これらのジョブは手動で監視し、必要に応じて再開してください。を参照して link:checking-data-repair-jobs.html["データ修復ジョブを確認します"]
* オブジェクトの唯一のコピーを含む切断されているストレージノードの運用を停止すると、そのオブジェクトは失われます。データ修復ジョブは、現在接続されているストレージノードに、 1 つ以上のレプリケートコピーまたは十分なイレイジャーコーディングフラグメントが含まれている場合のみ、オブジェクトを再構築してリカバリできます。

