---
permalink: maintain/copying-audit-logs-from-failed-non-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, audit log, copy audit log, copying audit log, non-primary admin node, non primary admin node 
summary: 障害が発生した管理ノードから監査ログをコピーできる場合は、グリッドのシステムアクティビティと使用状況のレコードを維持するために監査ログを保存します。リカバリした非プライマリ管理ノードが起動したら、保存しておいた監査ログをそのノードにリストアします。 
---
= 障害が発生した非プライマリ管理ノードから監査ログをコピーする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
障害が発生した管理ノードから監査ログをコピーできる場合は、グリッドのシステムアクティビティと使用状況のレコードを維持するために監査ログを保存します。リカバリした非プライマリ管理ノードが起動したら、保存しておいた監査ログをそのノードにリストアします。

この手順 は、障害が発生した管理ノードの監査ログファイルを別のグリッドノードの一時的な場所にコピーします。保存した監査ログは、交換用管理ノードにコピーできます。新しい管理ノードには監査ログが自動的にコピーされません。

障害の種類によっては、障害が発生した管理ノードから監査ログをコピーできない場合があります。管理ノードが 1 つしかない環境の場合、リカバリした管理ノードで新しい空のファイルの監査ログへのイベントの記録が開始され、以前に記録されたデータは失われます。管理ノードが複数ある環境の場合は、別の管理ノードから監査ログをリカバリできます。


NOTE: 現時点では障害管理ノードで監査ログにアクセスできない場合は、あとから（ホストのリカバリ後などに）アクセスできる可能性があります。

. 可能であれば、障害管理ノードにログインします。できない場合は、プライマリ管理ノードまたは別の管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@grid_node_IP`
.. ファイルに記載されているパスワードを入力し `Passwords.txt`ます。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. ファイルに記載されているパスワードを入力し `Passwords.txt`ます。


+
rootとしてログインすると、プロンプトがからに `#`変わります `$`。

. AMSサービスを停止して新しいログファイルが作成されないようにします。``service ams stop``
. 監査エクスポートディレクトリに移動します。
+
`cd /var/local/audit/export/`

. ソースaudit.logファイルの名前を一意の番号付きファイル名に変更します。たとえば、audit.logファイルの名前をに変更し `2023-10-25.txt.1`ます。
+
[listing]
----
ls -l
mv audit.log 2023-10-25.txt.1
----
. AMSサービスを再起動します。 `service ams start`
. すべての監査ログファイルを別のグリッドノードの一時的な場所にコピーするためのディレクトリを作成します。 `ssh admin@grid_node_IP mkdir -p /var/local/tmp/saved-audit-logs`
+
プロンプトが表示されたら、 admin のパスワードを入力します。

. すべての監査ログファイルを一時的な場所にコピーします。 `scp -p * admin@grid_node_IP:/var/local/tmp/saved-audit-logs`
+
プロンプトが表示されたら、 admin のパスワードを入力します。

. rootとしてログアウトします。 `exit`

