---
permalink: maintain/downloading-hotfix-file.html 
sidebar: sidebar 
keywords: storagegrid, hotfix, download 
summary: ホットフィックスを適用する前に、ホットフィックスファイルをダウンロードする必要があります。 
---
= ホットフィックスファイルをダウンロードします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホットフィックスを適用する前に、ホットフィックスファイルをダウンロードする必要があります。

.手順
. に進みます https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetAppのダウンロード：StorageGRID"^]。
. [ 利用可能なソフトウェア ] の下にある下矢印をクリックすると、ダウンロード可能なホットフィックスのリストが表示されます。
+

NOTE: ホットフィックスファイルのバージョンの形式は 11.4_.x.y__ です。

. 更新に含まれている変更を確認します。
+

NOTE: がインストールされていてホットフィックスを適用する必要がある場合はlink:configuring-replacement-primary-admin-node.html["プライマリ管理ノードをリカバリしました"]、他のグリッドノードにインストールされている同じバージョンのホットフィックスを選択します。

+
.. ダウンロードするホットフィックスのバージョンを選択し、 * Go * を選択します。
.. NetAppアカウントのユーザ名とパスワードを使用してサインインします。
.. エンドユーザライセンス契約を読んで同意します。
+
選択したバージョンのダウンロードページが表示されます。

.. ホットフィックスファイルをダウンロードし `readme.txt`て、ホットフィックスに含まれる変更の概要を確認します。


. ホットフィックスのダウンロードボタンを選択してファイルを保存します。
+

NOTE: このファイルの名前は変更しないでください。

+

NOTE: macOSデバイスを使用している場合は、ホットフィックスファイルが自動的にファイルとして保存されることがあります `.txt`。その場合は、拡張子を付けずにファイルの名前を変更する必要があり `.txt`ます。

. ダウンロードする場所を選択し、「 * 保存 * 」を選択します。

