---
permalink: maintain/downloading-recovery-package.html 
sidebar: sidebar 
keywords: storagegrid, recovery package 
summary: リカバリパッケージファイルを使用すると、障害が発生した場合にStorageGRIDシステムをリストアできます。 
---
= リカバリパッケージをダウンロード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リカバリパッケージファイルを使用すると、障害が発生した場合にStorageGRIDシステムをリストアできます。

.開始する前に
* プライマリ管理ノードから、を使用してGrid Managerにサインインしlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]ます。
* プロビジョニングパスフレーズを用意します。
* そうだな link:../admin/admin-group-permissions.html["特定のアクセス権限"]


StorageGRIDシステムでグリッドトポロジを変更する前、またはソフトウェアをアップグレードする前に、現在のリカバリパッケージファイルをダウンロードします。次に、グリッドトポロジを変更したあと、またはソフトウェアをアップグレードしたあとに、リカバリパッケージの新しいコピーをダウンロードします。

.手順
. [* maintenance * （メンテナンス） ] > [* System * （システム * ） ] > [* Recovery packツケ （リカバリパッケージ * ）
. プロビジョニングパスフレーズを入力し、*[ダウンロードの開始]*を選択します。
+
ダウンロードがすぐに開始されます。

. ダウンロードが完了したら、ファイルを開き `.zip`、ファイルを含むコンテンツにアクセスできることを確認し `Passwords.txt`ます。
. ダウンロードしたリカバリパッケージファイル(`.zip`）を、安全でセキュアな2つの別 々 の場所にコピーします。
+

CAUTION: リカバリパッケージファイルにはStorageGRID システムからデータを取得するための暗号キーとパスワードが含まれているため、安全に保管する必要があります。


