---
permalink: maintain/grid-node-procedures.html 
sidebar: sidebar 
keywords: storagegrid, grid node procedure 
summary: 特定のグリッドノードまたはノードサービスに関連したメンテナンス手順の実行が必要になる場合があります。 
---
= ノードのメンテナンス手順
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
特定のグリッドノードまたはノードサービスに関連したメンテナンス手順の実行が必要になる場合があります。

ADC の移動:: そのlink:../maintain/understanding-adc-service-quorum.html["ADCサービス"]一部のストレージ ノード上に存在します。特定の廃止およびノード変換の状況では、ADC サービスを同じサイト上の別のストレージ ノードに移動する必要があります。
ストレージノードをデータ専用ノードに変換する:: ADC サービスが含まれていないストレージ ノードをデータ専用のストレージ ノードに変換できます。
ノードの再起動、シャットダウン、電源:: 次の手順を使用して、1つ以上のノードをリブートしたり、ノードをシャットダウンして再起動したり、ノードの電源をオフにして再度オンにしたりします。
ポートの再マップ:: ポートの再マッピング手順を使用して、ノードからポートの再マッピングを削除できます。たとえば、以前に再マッピングされたポートを使用してロードバランサエンドポイントを設定する場合などです。
サーバーマネージャー:: Server Manager はすべてのグリッドノード上で実行されてサービスの開始と停止を管理し、 StorageGRID システムでサービスが正常に開始および終了するようにします。また、すべてのグリッドノードのサービスを監視し、エラーが報告された場合は自動的に再開を試みます。
+
--
サーバー マネージャーの手順を実行するには、通常、ノードのコマンド ラインにアクセスする必要があります。


CAUTION: Server Manager には、テクニカルサポートから指示があった場合にのみアクセスしてください。

--

