---
permalink: maintain/how-your-system-is-affected-when-you-apply-hotfix.html 
sidebar: sidebar 
keywords: storagegrid, hotfix 
summary: ホットフィックスを適用したときに、 StorageGRID システムにどのような影響が生じるのかを理解しておく必要があります。 
---
= ホットフィックス適用時のシステムへの影響
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホットフィックスを適用したときに、 StorageGRID システムにどのような影響が生じるのかを理解しておく必要があります。



== StorageGRIDのホットフィックスはシステム停止を伴わない

StorageGRIDシステムは、ホットフィックス適用プロセス全体を通じてクライアントアプリケーションからデータを取り込み、読み出すことができます。同じタイプのすべてのノード（ストレージノードなど）をホットフィックスに承認すると、ノードが一度に1つずつ停止されるため、すべてのグリッドノードまたは特定のタイプのすべてのグリッドノードが使用できなくなることはありません。

継続的な可用性を確保するには、各オブジェクトの複数のコピーを格納するように指定するルールをILMポリシーに含めるようにしてください。また、すべての外部S3クライアントが次のいずれかに要求を送信するように設定されていることを確認する必要があります。

* ハイアベイラビリティ（HA）グループの仮想IPアドレス
* 高可用性を備えたサードパーティ製ロードバランサ
* 各クライアントに複数のゲートウェイノードが必要
* クライアントごとに複数のストレージノード




== クライアントアプリケーションが短時間中断される可能性があります

StorageGRID システムは、ホットフィックス適用プロセス中もクライアントアプリケーションからデータを取り込み、読み出すことができますが、ホットフィックスが個々のゲートウェイノードまたはストレージノードのサービスを再開する必要がある場合は、それらのノードへのクライアント接続が一時的に中断されることがあります。接続はホットフィックスの適用終了後に再開され、個々のノードのサービスも再開されます。

接続の中断が短時間でも許容されない場合は、ホットフィックス適用時のダウンタイムをスケジュールする必要があります。特定のノードが更新されるタイミングをスケジュールするには、選択的な承認を使用できます。


NOTE: 複数のゲートウェイとハイアベイラビリティ（ HA ）グループを使用すると、ホットフィックス適用プロセス中に自動フェイルオーバーを実行できます。の手順を参照してくださいlink:../admin/configure-high-availability-group.html["ハイアベイラビリティグループを設定する"]。



== アラートおよび SNMP 通知がトリガーされる可能性があります

サービスが再起動されたとき、および StorageGRID システムを複数バージョンが混在した環境で使用している場合（一部のグリッドノードで以前のバージョンを実行し、その他のノードはより新しいバージョンにアップグレードしている場合）には、アラートと SNMP 通知がトリガーされることがあります。通常、これらのアラートと通知はホットフィックスが完了するとクリアされます。



== 設定の変更は制限されています

StorageGRID にホットフィックスを適用する際は、次の点に注意

* ホットフィックスがすべてのノードに適用されるまで、グリッド設定の変更（グリッドネットワークサブネットの指定や保留中のグリッドノードの承認など）は行わないでください。
* ホットフィックスがすべてのノードに適用されるまで、ILM設定を更新しないでください。

