---
permalink: maintain/monitor-repairs.html 
sidebar: sidebar 
keywords: restore replicated data, restore erasure-coded data, recover appliance storage node, recover storage volume 
summary: 'コマンドラインからスクリプトを使用して、修復ジョブのステータスを監視できます `repair-data`。' 
---
= repair-dataジョブを監視します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コマンドラインからスクリプトを使用して、修復ジョブのステータスを監視できます `repair-data`。

これには、ユーザが手動で開始したジョブや、運用停止手順 の一環としてStorageGRID によって自動的に開始されたジョブが含まれます。


NOTE: 代わりに、ボリュームリストアジョブを実行している場合link:../maintain/restoring-volume.html["Grid Managerで進捗状況を監視し、それらのジョブの履歴を表示します"]。

使用しているデータが*レプリケートデータ*、*イレイジャーコーディング（EC）データ*、またはその両方に基づいてジョブのステータスを監視します `repair-data`。

[role="tabbed-block"]
====
.レプリケートデータ
--
* レプリケートされた修復の完了率を推定するには、repair-dataコマンドにオプションを追加し `show-replicated-repair-status`ます。
+
`repair-data show-replicated-repair-status`

* 修理が完了しているかどうかを確認するには、次
+
.. *ノード* > *_修復中のストレージノード_* > *ILM* を選択します。
.. 「評価」セクションの属性を確認します。修理が完了すると、 *Awaiting - All * 属性は 0 個のオブジェクトを示します。


* 修理を詳細に監視するには、次の手順を実行します。
+
.. *ノード*を選択します。
.. *_grid name_*>*ilm * を選択します。
.. ILM キュー グラフの上にカーソルを置くと、*スキャン レート (オブジェクト/秒)* 属性の値が表示されます。これは、グリッド内のオブジェクトがスキャンされ、ILM のキューに入れられるレートです。
.. ILM キュー セクションで、次の属性を確認します。
+
*** * Scan Period - Estimated *：ILMによるすべてのオブジェクトのフルスキャンが完了するまでの推定時間。
+
完全スキャンでは、すべてのオブジェクトに ILM が適用されていることが保証されません。

*** *試行された修復*: 高リスクと見なされる複製されたデータに対して試行されたオブジェクト修復操作の合計数。高リスク オブジェクトとは、ILM ポリシーによって指定されているか、コピーの損失の結果として、コピーが 1 つ残っているオブジェクトのことです。このカウントは、ストレージ ノードが高リスクのオブジェクトの修復を試みるたびに増加します。グリッドが混雑している場合は、リスクの高い ILM 修復が優先されます。
+
修復後にレプリケーションが失敗した場合、同じオブジェクトの修復が再度増加する可能性があります。 + これらの属性は、ストレージ ノード ボリュームのリカバリの進行状況を監視するときに役立ちます。修復の試行回数の増加が止まり、完全スキャンが完了した場合、修復は完了したと考えられます。



.. あるいは、Prometheusクエリを送信して `storagegrid_ilm_scan_period_estimated_minutes`そして `storagegrid_ilm_repairs_attempted`。




--
.イレイジャーコーディング（EC）データ
--
イレイジャーコーディングデータの修復を監視し、失敗した可能性のある要求を再試行するには、次の手順を実行します。

. イレイジャーコーディングデータの修復ステータスを確認します。
+
** 現在のジョブの完了までの推定時間と完了率を表示するには、[サポート] > [ツール] > [メトリック] を選択します。次に、Grafana セクションで *EC 概要* を選択します。  *グリッド EC ジョブの完了推定時間*ダッシュボードと*グリッド EC ジョブの完了率*ダッシュボードを確認します。
** 特定の処理のステータスを表示するには、次のコマンドを使用し `repair-data`ます。
+
`repair-data show-ec-repair-status --repair-id repair ID`

** すべての修復処理を表示するには、次のコマンドを使用します
+
`repair-data show-ec-repair-status`

+
出力には、以前に実行されていた修復と現在実行中の修復の情報などが表示され `repair ID`ます。



. 失敗した修復処理が出力された場合は、オプションを使用し `--repair-id`て修復を再試行します。
+
次のコマンドは、修復ID 6949309319275667690を使用して、障害が発生したノードの修復を再試行します。

+
`repair-data start-ec-node-repair --repair-id 6949309319275667690`

+
次のコマンドは、修復ID 6949309319275667690を使用して、障害が発生したボリュームの修復を再試行します。

+
`repair-data start-ec-volume-repair --repair-id 6949309319275667690`



--
====