---
permalink: maintain/monitoring-storagegrid-appliance-installation-sn.html 
sidebar: sidebar 
keywords: storagegrid, recover, appliance 
summary: StorageGRID アプライアンスインストーラでは、インストールが完了するまでステータスが提供されます。ソフトウェアのインストールが完了すると、アプライアンスがリブートされます。 
---
= StorageGRID アプライアンスの設置を監視する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID アプライアンスインストーラでは、インストールが完了するまでステータスが提供されます。ソフトウェアのインストールが完了すると、アプライアンスがリブートされます。

.手順
. インストールの進行状況を監視するには、メニューバーの * インストールの監視 * をクリックします。
+
Monitor Installation ページにインストールの進行状況が表示されます。

+
青色のステータスバーは、現在進行中のタスクを示します。緑のステータスバーは、正常に完了したタスクを示します。

+

NOTE: インストーラは、以前のインストールで完了したタスクが再実行されないようにします。インストールを再実行している場合、再実行する必要のないタスクはすべて緑色のステータスバーと「スキップ済み」のステータスで表示されます。

. インストールの最初の 2 つのステージの進行状況を確認します。
+
** *1.ストレージの構成 *
+
インストーラがストレージコントローラに接続し、既存の設定があれば消去し、SANtricity OSと通信してボリュームを設定し、ホストを設定します。

** *2.OS * をインストールします
+
インストーラが StorageGRID のベースとなるオペレーティングシステムイメージをアプライアンスにコピーします。



. インストールの進行状況の監視を続けて、組み込みのコンソールに「 Install StorageGRID * 」ステージが一時停止し、グリッドマネージャを使用して管理ノード上でこのノードを承認するように求めるメッセージが表示されるまで待ちます。
. にアクセスします。

