---
permalink: maintain/monitor-repairs.html 
sidebar: sidebar 
keywords: restore replicated data, restore erasure-coded data, recover appliance storage node, recover storage volume 
summary: 'コマンドラインからスクリプトを使用して、修復ジョブのステータスを監視できます `repair-data`。' 
---
= repair-dataジョブを監視します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コマンドラインからスクリプトを使用して、修復ジョブのステータスを監視できます `repair-data`。

これには、ユーザが手動で開始したジョブや、運用停止手順 の一環としてStorageGRID によって自動的に開始されたジョブが含まれます。


NOTE: 代わりに、ボリュームリストアジョブを実行している場合link:../maintain/restoring-volume.html["Grid Managerで進捗状況を監視し、それらのジョブの履歴を表示します"]。

使用しているデータが*レプリケートデータ*、*イレイジャーコーディング（EC）データ*、またはその両方に基づいてジョブのステータスを監視します `repair-data`。

[role="tabbed-block"]
====
.レプリケートデータ
--
* レプリケートされた修復の完了率を推定するには、repair-dataコマンドにオプションを追加し `show-replicated-repair-status`ます。
+
`repair-data show-replicated-repair-status`

* 修理が完了しているかどうかを確認するには、次
+
.. ノードを選択 * > * _ 修復中のストレージノード _ * > * ILM * を選択します。
.. 「評価」セクションの属性を確認します。修理が完了すると、 *Awaiting - All * 属性は 0 個のオブジェクトを示します。


* 修理を詳細に監視するには、次の手順を実行します。
+
.. サポート * > * ツール * > * グリッドトポロジ * を選択します。
.. 「 * _grid_* > * _ Storage Node being repaired _ * > * LDR * > * Data Store * 」を選択します。
.. 次の属性を組み合わせて、レプリケートデータの修復が完了したかどうかを可能なかぎり判別します。
+

NOTE: Cassandraに不整合がある可能性があり、失敗した修復は追跡されません。

+
*** * Repairs Attempted （ XRPA ） * ：レプリケートデータの修復の進行状況を追跡します。この属性は、ストレージノードがハイリスクオブジェクトの修復を試みるたびに値が増分します。この属性の値が現在のスキャン期間（ * Scan Period - - Estimated * 属性で指定）よりも長い期間にわたって上昇しない場合、 ILM スキャンはすべてのノードで修復が必要なハイリスクオブジェクトを検出していません。
+

NOTE: ハイリスクオブジェクトとは、完全に失われる危険があるオブジェクトです。ILM設定を満たさないオブジェクトは含まれません。

*** * スキャン期間 - 推定（ XSCM ） * ：この属性を使用して、以前に取り込まれたオブジェクトにポリシー変更が適用されるタイミングを見積もります。「 * Repairs Attempted * 」属性が現在のスキャン期間よりも長くなっていない場合は、複製修復が実行されている可能性があります。スキャン期間は変わる可能性があるので注意してください。* Scan Period - - Estimated （ XSCM ） * 属性は、グリッド全体の環境 を示します。これは、すべてのノードのスキャン期間の最大値です。グリッドの * Scan Period - - Estimated * 属性履歴を照会して、適切な期間を判断できます。






--
.イレイジャーコーディング（EC）データ
--
イレイジャーコーディングデータの修復を監視し、失敗した可能性のある要求を再試行するには、次の手順を実行します。

. イレイジャーコーディングデータの修復ステータスを確認します。
+
** サポート * > * Tools * > * Metrics * を選択して、現在のジョブの完了までの推定時間と完了率を表示します。次に、 Grafana のセクションで * EC Overview * を選択します。グリッド EC ジョブの完了予想時間 * ダッシュボードと * グリッド EC ジョブの完了率 * ダッシュボードを確認します。
** 特定の処理のステータスを表示するには、次のコマンドを使用し `repair-data`ます。
+
`repair-data show-ec-repair-status --repair-id repair ID`

** すべての修復処理を表示するには、次のコマンドを使用します
+
`repair-data show-ec-repair-status`

+
出力には、以前に実行されていた修復と現在実行中の修復の情報などが表示され `repair ID`ます。



. 失敗した修復処理が出力された場合は、オプションを使用し `--repair-id`て修復を再試行します。
+
次のコマンドは、修復ID 6949309319275667690を使用して、障害が発生したノードの修復を再試行します。

+
`repair-data start-ec-node-repair --repair-id 6949309319275667690`

+
次のコマンドは、修復ID 6949309319275667690を使用して、障害が発生したボリュームの修復を再試行します。

+
`repair-data start-ec-volume-repair --repair-id 6949309319275667690`



--
====