---
permalink: maintain/move-adc-service.html 
sidebar: sidebar 
keywords: storagegrid, move adc, adc quorum 
summary: ADCサービスを同じサイトの別のストレージノードに移動できます。 
---
= ADCサービスの移動
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ADCサービスを同じサイトの別のストレージノードに移動できます。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* そうだな link:admin-group-permissions.html["Maintenance権限またはRoot Access権限"]
* ソースノードにADCサービスが含まれている。
* ターゲットノードにADCサービスが含まれていません。
* ターゲットノードは、メタデータのみのノードか、メタデータとオブジェクトデータを組み合わせたノードのどちらかです。
* ソースノードとターゲットノードが同じサイトにある。


.タスクの内容
次の場合は、[Move ADC（ADCの移動）]手順を使用します。

* ADCサービスを含むストレージノードの運用を停止する
* ADCノードをデータ専用ノードに変換する
* ADC関連のタスクを実行するノードを追加します。


ストレージノードまたはの運用を停止する場合はlink:../maintain/convert-to-data-only-node.html["ストレージノードをデータ専用ノードに変換する"]、まず[Move ADC]手順を使用しなければならないことがあります。を確認する必要がありlink:../maintain/understanding-adc-service-quorum.html["ADCクォーラムが維持される"]ます。

この手順では、ADC、IDNT、acct、およびRSMの各サービスを同じサイトのストレージノードから別のストレージノードに移動します。RSMサービスとacctサービスはADCサービスに依存しているため、ADCサービスを移動すると自動的に移動します。

.手順
. ソースノードとターゲットノードのノードIDを記録します。
+
グリッド管理APIでは、ソースノードIDがと呼ばれます `sourceNodeId`。ターゲットノードIDはと呼ばれ `targetNodeId`ます。

. Grid Managerの上部でヘルプアイコンを選択し、*[API documentation]*を選択します。
. [Go to private API documentation]*を選択します。
. 処理を選択します `POST /private/move-adc/start`。詳細については、を参照してください link:../admin/using-grid-management-api.html#issue-api-requests["問題 API 要求"] 。
+
手順の実行中に各ノードがリブートします。

. を使用して手順を監視できます `GET /private/move-adc`。エラーが発生した場合は、を選択し `POST /private/move-adc/retry`て手順を再試行します。
. link:../maintain/downloading-recovery-package.html["リカバリパッケージをダウンロードする"]この手順が完了したら、

