---
permalink: maintain/move-adc-service.html 
sidebar: sidebar 
keywords: storagegrid, move adc, adc quorum 
summary: ADC サービスを同じサイト上の別のストレージ ノードに移動できます。 
---
= ADCサービスを移動する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ADC サービスを同じサイト上の別のストレージ ノードに移動できます。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたが持っているlink:../admin/admin-group-permissions.html["Maintenance権限またはRoot Access権限"]。
* ソース ノードには ADC サービスが含まれています。
* ターゲット ノードに ADC サービスが含まれていません。
* ターゲット ノードは、メタデータのみのノード、または結合された (メタデータとオブジェクト データ) ノードのいずれかです。
* ソース ノードとターゲット ノードは同じサイトにあります。


.タスクの内容
次の場合に、Move ADC 手順を使用します。

* ADC サービスをホストするストレージノードを廃止する
* ADC サービスをホストするストレージ ノードをデータ専用のストレージ ノードに変換する


ストレージノードを廃止する場合、またはlink:../maintain/convert-to-data-only-node.html["ストレージノードをデータ専用ノードに変換する"]最初に、Move ADC 手順を使用する必要がある場合があります。以下の点を確認する必要があります。link:../maintain/understanding-adc-service-quorum.html["ADCクォーラムが維持される"] 。

この手順では、ADC、IDNT、ACCT、および RSM サービスを、同じサイト上の 1 つのストレージ ノードから別のストレージ ノードに移動します。  RSM、IDNT、および ACCT サービスは ADC サービスに依存しているため、ADC サービスが移動すると自動的に移動します。

.手順
. ソース ノードとターゲット ノードのノード ID を記録します。
+
グリッド管理APIでは、ソースノードIDは次のように呼ばれます。 `sourceNodeId` 。ターゲットノードIDは `targetNodeId`。

. Grid Managerの上部でヘルプアイコンを選択し、*[API documentation]*を選択します。
. [Go to private API documentation]*を選択します。
. 選択してください `POST /private/move-adc/start`手術。参照link:../admin/using-grid-management-api.html#issue-api-requests["問題 API 要求"]詳細についてはこちらをご覧ください。
+
手順中、2 つのノードが順番に再起動します。最初にソース ノードが再起動し、次にターゲット ノードが再起動します。

. 使用できます `GET /private/move-adc`手順を監視します。エラーが発生した場合は、 `POST /private/move-adc/retry`手順を再試行します。
. link:../maintain/downloading-recovery-package.html["リカバリパッケージをダウンロードする"]この手順を完了した後。

