---
permalink: maintain/obtaining-required-materials-for-hotfix.html 
sidebar: sidebar 
keywords: storagegrid, hotfix 
summary: ホットフィックスを適用する前に、必要な項目をすべて用意する必要があります。 
---
= ホットフィックスに必要な項目を用意します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホットフィックスを適用する前に、必要な項目をすべて用意する必要があります。

[cols="1a,2a"]
|===
| 項目 | 脚注 


 a| 
StorageGRID ホットフィックスファイル
 a| 
StorageGRID ホットフィックスファイルをダウンロードする必要があります。



 a| 
* ネットワークポート
* link:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]
* SSH クライアント（ PuTTY など）

 a| 



 a| 
リカハリPackage）(`.zip`フアイル
 a| 
ホットフィックスの適用前に、ホットフィックスの適用link:downloading-recovery-package.html["最新のリカバリパッケージファイルをダウンロードします"]中に問題が発生した場合に備えておく必要があります。その後、ホットフィックスが適用されたら、リカバリパッケージファイルの新しいコピーをダウンロードして安全な場所に保存します。更新されたリカバリパッケージファイルは、障害発生時のシステムのリストアに使用できます。



| Passwords.txt ファイル  a| 
任意。 SSH クライアントを使用してホットフィックスを手動で適用する場合にのみ使用します。 `Passwords.txt`ファイルはリカバリパッケージファイルに含まれ `.zip`ています。



 a| 
プロビジョニングパスフレーズ
 a| 
このパスフレーズは、 StorageGRID システムが最初にインストールされるときに作成されて文書化されます。プロビジョニングパスフレーズはファイルに含まれていません `Passwords.txt`。



 a| 
関連ドキュメント
 a| 
`readme.txt`ファイル（ホットフィックス用）。このファイルは、ホットフィックスのダウンロードページにあります。ホットフィックスを適用する前に、ファイルをよく確認して `readme`ください。

|===