---
permalink: maintain/obtaining-required-materials-for-hotfix.html 
sidebar: sidebar 
keywords: storagegrid, hotfix 
summary: ホットフィックスを適用する前に、必要な項目をすべて用意する必要があります。 
---
= ホットフィックスに必要な項目を用意します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホットフィックスを適用する前に、必要な項目をすべて用意する必要があります。

[cols="1a,2a"]
|===
| 項目 | 脚注 


 a| 
StorageGRID ホットフィックスファイル
 a| 
StorageGRID ホットフィックスファイルをダウンロードする必要があります。



 a| 
* ネットワークポート
* link:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]
* SSH クライアント（ PuTTY など）

 a| 



 a| 
回復パッケージ(`.zip`） ファイル
 a| 
修正プログラムを適用する前に、link:downloading-recovery-package.html["最新のリカバリパッケージファイルをダウンロードする"]ホットフィックス中に問題が発生した場合に備えて。次に、修正プログラムを適用した後、回復パッケージ ファイルの新しいコピーをダウンロードし、安全な場所に保存します。更新されたリカバリ パッケージ ファイルを使用すると、障害が発生した場合にシステムを復元できます。



| Passwords.txt ファイル  a| 
オプションであり、SSH クライアントを使用して手動で修正プログラムを適用する場合にのみ使用されます。その `Passwords.txt`ファイルは回復パッケージの一部です `.zip`ファイル。



 a| 
プロビジョニングパスフレーズ
 a| 
このパスフレーズは、 StorageGRID システムが最初にインストールされるときに作成されて文書化されます。プロビジョニングパスフレーズはファイルに含まれていません `Passwords.txt`。



 a| 
関連ドキュメント
 a| 
`readme.txt`ファイル（ホットフィックス用）。このファイルは、ホットフィックスのダウンロードページにあります。ホットフィックスを適用する前に、ファイルをよく確認して `readme`ください。

|===