---
permalink: maintain/obtaining-required-materials-for-hotfix.html 
sidebar: sidebar 
keywords: storagegrid, hotfix 
summary: ホットフィックスを適用する前に、必要な項目をすべて用意する必要があります。 
---
= ホットフィックスに必要な項目を用意します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホットフィックスを適用する前に、必要な項目をすべて用意する必要があります。

[cols="1a,2a"]
|===
| 項目 | 脚注 


 a| 
StorageGRID ホットフィックスファイル
 a| 
StorageGRID ホットフィックスファイルをダウンロードする必要があります。



 a| 
* ネットワークポート
* link:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]
* SSH クライアント（ PuTTY など）

 a| 



 a| 
リカハリハツケエシノ(`.zip`フアイル
 a| 
ホットフィックスの適用前に、ホットフィックスの適用link:downloading-recovery-package.html["最新のリカバリパッケージファイルをダウンロードする"]中に問題が発生した場合に備えておく必要があります。次に、ホットフィックスが適用されたら、リカバリパッケージファイルの新しいコピーをダウンロードして安全な場所に保存します。更新されたリカバリパッケージファイルを使用すると、障害が発生した場合にシステムをリストアできます。



| Passwords.txt ファイル  a| 
任意。 SSH クライアントを使用してホットフィックスを手動で適用する場合にのみ使用します。 `Passwords.txt`ファイルはリカバリパッケージファイルに含まれてい `.zip`ます。



 a| 
プロビジョニングパスフレーズ
 a| 
このパスフレーズは、 StorageGRID システムが最初にインストールされるときに作成されて文書化されます。プロビジョニングパスフレーズはファイルに含まれていません `Passwords.txt`。



 a| 
関連ドキュメント
 a| 
`readme.txt`ファイル（ホットフィックス用）。このファイルは、ホットフィックスのダウンロードページにあります。ホットフィックスを適用する前に、ファイルをよく確認して `readme`ください。

|===