---
permalink: maintain/powering-off-and-on-all-nodes-in-grid.html 
sidebar: sidebar 
keywords: storagegrid, recover, power nodes, power on nodes, power off nodes, power down nodes 
summary: データセンターの移行などで、 StorageGRID システム全体のシャットダウンが必要になる場合があります。ここでは、通常の方法でシャットダウンと起動を実行する場合の推奨手順について、その概要を記載します。 
---
= グリッド内のすべてのノードの電源をオフにしてオンにします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データセンターの移行などで、 StorageGRID システム全体のシャットダウンが必要になる場合があります。ここでは、通常の方法でシャットダウンと起動を実行する場合の推奨手順について、その概要を記載します。

サイトまたはグリッド内のすべてのノードの電源をオフにすると、ストレージノードがオフラインの間は、取り込んだオブジェクトにアクセスできなくなります。



== サービスを停止し、グリッドノードをシャットダウンします

StorageGRID システムの電源をオフにするには、各グリッドノードで実行されているすべてのサービスを停止してから、すべての VMware 仮想マシン、コンテナエンジン、および StorageGRID アプライアンスをシャットダウンする必要があります。

.タスクの内容
最初に管理ノードとゲートウェイノードのサービスを停止してから、ストレージノードのサービスを停止します。

この方法なら、プライマリ管理ノードを使用して他のグリッドノードのステータスをできるだけ長く監視できます。


NOTE: 単一のホストに複数のグリッドノードが含まれている場合は、そのホスト上のすべてのノードを停止するまでホストをシャットダウンしないでください。ホストにプライマリ管理ノードが含まれている場合は、そのホストを最後にシャットダウンします。


NOTE: 必要に応じて、グリッドの機能や可用性に影響を与えることなくホストのメンテナンスを実行できますlink:linux-migrating-grid-node-to-new-host.html["Linux ホスト間でのノードの移行"]。

.手順
. デフォルトでは外部 SSH アクセスはブロックされます。必要に応じて、link:../admin/manage-external-ssh-access.html["一時的にアクセスを許可する"] 。
. すべてのクライアントアプリケーションからグリッドへのアクセスを停止します。
. [[log_in_on_gn] ][ 各ゲートウェイノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
.. ファイルに記載されているパスワードを入力し `Passwords.txt`ます。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. ファイルに記載されているパスワードを入力し `Passwords.txt`ます。


+
rootとしてログインすると、プロンプトがからに `#`変わります `$`。

. [[stop_all_services]]ノードで実行されているすべてのサービスを停止します。 `service servermanager stop`
+
サービスのシャットダウンには最大 15 分かかる場合があります。リモートからシステムにログインしてシャットダウンプロセスを監視することもできます。

. 前の2つの手順を繰り返して、すべてのストレージノードと非プライマリ管理ノードのサービスを停止します。
+
これらのノードのサービスは、どの順序で停止してもかまいません。

+

NOTE: コマンドを実行してアプライアンスストレージノードのサービスを停止する場合 `service servermanager stop`は、アプライアンスの電源を再投入してノードを再起動する必要があります。

. プライマリ管理ノードに対して、およびについての手順を繰り返します<<log_in_to_gn,ノードにログインします>><<stop_all_services,ノードのすべてのサービスを停止しています>>。
. Linux ホストで実行されているノードの場合：
+
.. ホストオペレーティングシステムにログインします。
.. ノードを停止します。 `storagegrid node stop`
.. ホストオペレーティングシステムをシャットダウンします。


. VMware仮想マシンで実行されているノードとアプライアンスストレージノードの場合は、shutdownコマンドを実行します。 `shutdown -h now`
+
この手順は、コマンドの結果に関係なく実行し `service servermanager stop`ます。

+
アプライアンスの場合、このコマンドはコンピューティングコントローラをシャットダウンしますが、アプライアンスの電源はオンになったままです。次の手順を実行する必要があります。

. アプライアンスノードがある場合は、アプライアンスに応じた手順を実行します。
+
[role="tabbed-block"]
====
.SG110またはSG1100
--
.. アプライアンスの電源をオフにします。
.. 青色の電源 LED が消灯するまで待ちます。


--
.SG100またはSG1000
--
.. アプライアンスの電源をオフにします。
.. 青色の電源 LED が消灯するまで待ちます。


--
.SG6160
--
.. SG6100-CNストレージコントローラの電源をオフにします。
.. SG6100-CNストレージコントローラの青色の電源LEDが消灯するまで待ちます。


--
.SGF6112
--
.. アプライアンスの電源をオフにします。
.. 青色の電源 LED が消灯するまで待ちます。


--
.SG6000
--
.. ストレージコントローラの背面にある緑のキャッシュアクティブ LED が消灯するまで待ちます。
+
この LED は、キャッシュデータをドライブに書き込む必要があるときに点灯します。この LED が消灯するのを待ってから、電源をオフにする必要があります。

.. アプライアンスの電源をオフにし、青色の電源 LED が消灯するまで待ちます。


--
.SG5800
--
.. ストレージコントローラの背面にある緑のキャッシュアクティブ LED が消灯するまで待ちます。
+
この LED は、キャッシュデータをドライブに書き込む必要があるときに点灯します。この LED が消灯するのを待ってから、電源をオフにする必要があります。

.. SANtricity システムマネージャのホームページで、「 * 進行中の処理を表示」を選択します。
.. すべての処理が完了したことを確認してから、次の手順に進みます。
.. コントローラシェルフの両方の電源スイッチをオフにし、コントローラシェルフのすべてのLEDが消灯するまで待ちます。


--
.SG5700
--
.. ストレージコントローラの背面にある緑のキャッシュアクティブ LED が消灯するまで待ちます。
+
この LED は、キャッシュデータをドライブに書き込む必要があるときに点灯します。この LED が消灯するのを待ってから、電源をオフにする必要があります。

.. アプライアンスの電源をオフにし、すべての LED とデジタル表示ディスプレイの動作が停止するまで待ちます。


--
====
. 必要に応じて、コマンドシェルからログアウトします。 `exit`
+
これで、 StorageGRID グリッドのシャットダウンは完了です。

. 外部SSHアクセスを許可している場合は、link:../admin/manage-external-ssh-access.html["アクセスをブロックする"]ノードのシャットダウンが完了したら。




== グリッドノードを起動します


CAUTION: グリッド全体が 15 日以上シャットダウンされている場合は、グリッドノードを起動する前にテクニカルサポートに連絡する必要があります。Cassandraデータを再構築するリカバリ手順は実行しないでください。データが失われる可能性があります。

可能であれば、次の順序でグリッドノードの電源をオンにします。

* 最初に管理ノードの電源をオンにします。
* 最後にゲートウェイノードの電源をオンにします。



NOTE: ホストに複数のグリッドノードが含まれている場合は、ホストの電源をオンにすると各ノードが自動的にオンライン状態に戻ります。

.手順
. プライマリ管理ノードと非プライマリ管理ノードのホストの電源をオンにします。
+

NOTE: ストレージノードの再起動が完了するまで、管理ノードにログインすることはできません。

. すべてのストレージノードのホストの電源をオンにします。
+
これらのノードは、どの順序で電源をオンにしてもかまいません。

. すべてのゲートウェイノードのホストの電源をオンにします。
. Grid Manager にサインインします。
. *ノード*を選択し、グリッド ノードのステータスを監視します。ノード名の横に警告アイコンがないことを確認します。


.関連情報
* https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/index.html["SGF6112およびSG6160ストレージアプライアンス"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg110-1100/index.html["SG110およびSG1100サービスアプライアンス"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg100-1000/index.html["SG100およびSG1000サービス アプライアンス"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg6000/index.html["SG6000ストレージアプライアンス"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg5800/index.html["SG5800ストレージアプライアンス"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg5700/index.html["SG5700ストレージアプライアンス"^]

