---
permalink: maintain/preparing-appliance-for-reinstallation-platform-replacement-only.html 
sidebar: sidebar 
keywords: storagegrid, recover, appliance, reinstallation appliance, reinstall appliance 
summary: サービスアプライアンスでホストされていたグリッドノードをリカバリする場合は、最初に StorageGRID ソフトウェアを再インストールするアプライアンスを準備する必要があります。 
---
= 再インストールのためのアプライアンスの準備（プラットフォームの交換のみ）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
サービスアプライアンスでホストされていたグリッドノードをリカバリする場合は、最初に StorageGRID ソフトウェアを再インストールするアプライアンスを準備する必要があります。

この手順 は、サービスアプライアンスでホストされていた障害ノードを交換する場合にのみ実行してください。障害ノードが元 々 VMwareまたはLinuxホストでホストされていた場合は、次の手順を実行しないでください。

.手順
. 障害が発生したグリッドノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
.. ファイルに記載されているパスワードを入力し `Passwords.txt`ます。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. ファイルに記載されているパスワードを入力し `Passwords.txt`ます。


+
rootとしてログインすると、プロンプトがからに `#`変わります `$`。

. StorageGRID ソフトウェアをアプライアンスにインストールする準備をします。入力： `sgareinstall`
. 続行するかどうかを確認するメッセージが表示されたら、 `y`
+
アプライアンスがリブートされ、 SSH セッションが終了します。通常は 5 分程度で StorageGRID アプライアンスインストーラが使用可能になりますが、場合によっては最大で 30 分待つ必要があります。

+
サービスアプライアンスがリセットされ、グリッドノード上のデータにアクセスできなくなります。元のインストールプロセスで設定した IP アドレスはそのまま使用する必要がありますが、手順 の完了時に確認しておくことを推奨します。

+
コマンドの実行後、 `sgareinstall`StorageGRIDでプロビジョニングされたアカウント、パスワード、およびSSHキーがすべて削除され、新しいホストキーが生成されます。


