---
permalink: maintain/rebooting-grid-node-from-grid-manager.html 
sidebar: sidebar 
keywords: reboot grid node, tasks tab 
summary: 'グリッドノードは、[Nodes]ページの[Tasks]タブで個別にリブートできます。' 
---
= [Tasks]タブからのグリッドノードのリブート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッドノードは、[Nodes]ページの[Tasks]タブで個別にリブートできます。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたはを持っていますlink:../admin/admin-group-permissions.html["Maintenance権限またはRoot Access権限"]。
* プロビジョニングパスフレーズを用意します。
* プライマリ管理ノードまたはストレージノードをリブートする場合は、次の考慮事項を確認しておく必要があります。
+
** プライマリ管理ノードをリブートすると、ブラウザからGrid Managerに一時的にアクセスできなくなります。
** 特定のサイトで複数のストレージノードをリブートすると、リブート中は特定のオブジェクトにアクセスできない場合があります。この問題は、いずれかのILMルールで* Dual commit *取り込みオプションが使用されている（またはルールで* Balanced *が指定されており、必要なすべてのコピーをただちに作成できない）場合に発生する可能性があります。この場合StorageGRID、新しく取り込まれたオブジェクトは同じサイト上の2つのストレージノードにコミットされ、あとでILMが評価されます。
** ストレージノードのリブート中もすべてのオブジェクトにアクセスできるようにするには、ノードをリブートする前に、サイトでのオブジェクトの取り込みを約 1 時間停止します。




.タスクの内容
StorageGRIDがグリッドノードをリブートすると、そのノードでコマンドが実行され `reboot`、ノードがシャットダウンされて再起動されます。すべてのサービスが自動的に再開されます。

* VMwareノードをリブートすると、仮想マシンがリブートされます。
* Linuxノードをリブートすると、コンテナがリブートされます。
* StorageGRIDアプライアンスノードをリブートすると、コンピューティングコントローラがリブートされます。



TIP: 複数のノードをリブートする必要がある場合は、を使用できますlink:../maintain/rolling-reboot-procedure.html["ローリングリブート手順"]。

.手順
. [* nodes （ノード） ] を選択します
. リブートするグリッドノードを選択します。
. [* タスク * （ Tasks * ） ] タブを選択します。
. [Reboot] を選択します。
+
確認のダイアログボックスが表示されます。プライマリ管理ノードをリブートすると、サービスの停止中はブラウザと Grid Manager の接続が一時的に失われることを知らせる確認ダイアログボックスが表示されます。

. プロビジョニングパスフレーズを入力し、「 * OK 」を選択します。
. ノードがリブートするまで待ちます。
+
サービスがシャットダウンするまでに時間がかかる場合があります。

+
ノードのリブート中は、[Nodes]ページにそのノードのグレーの（Administratively Down）アイコンが表示されます。すべてのサービスが再開され、ノードがグリッドに正常に接続されると、[Nodes]ページに通常ステータス（ノード名の左側にアイコンはありません）が表示され、アクティブなアラートがなく、ノードがグリッドに接続されていることが示されます。


