---
permalink: maintain/recovering-from-storage-node-failures.html 
sidebar: sidebar 
keywords: recover, storage node failure, Reaper 
summary: 障害ストレージノードをリカバリする手順 は、障害のタイプおよび障害が発生したストレージノードのタイプによって異なります。 
---
= StorageGRIDストレージノードの障害から回復する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
障害ストレージノードをリカバリする手順 は、障害のタイプおよび障害が発生したストレージノードのタイプによって異なります。

次の表を参照して、障害が発生したストレージノードのリカバリ手順 を選択してください。

[cols="1a,1a,1a"]
|===
| 問題 | アクション | 脚注 


 a| 
複数のストレージノードで障害が発生した。
 a| 
テクニカルサポートにお問い合わせください。
 a| 
複数のストレージノードが故障した場合、データ損失につながる可能性のある Cassandra データベースの不整合を防ぐため、技術サポートによる復旧支援が必要です。サイト復旧手順が必要になる場合があります。

テクニカルサポートは、2つ目のストレージノードの復旧を開始しても安全な時期を判断できます。

*注*：1つのサイトでADCサービスを含むストレージノードが複数障害を起こした場合、そのサイトに対する保留中のプラットフォームサービスリクエストはすべて失われます。



 a| 
サイトの複数のストレージノードで障害が発生したか、サイト全体で障害が発生した。
 a| 
テクニカルサポートにお問い合わせください。サイトリカバリ手順 の実行が必要になる場合があります。
 a| 
テクニカルサポートは、お客様の状況を評価し、リカバリプランを作成します。を参照して link:how-site-recovery-is-performed-by-technical-support.html["テクニカルサポートによるサイトのリカバリ方法"]



 a| 
アプライアンスストレージノードで障害が発生した。
 a| 
link:recovering-storagegrid-appliance-storage-node.html["アプライアンスストレージノードをリカバリします"]
 a| 
アプライアンスストレージノードのリカバリ手順 は、すべての障害で同じです。



 a| 
ストレージボリュームで障害が発生したが、システムドライブには損傷がない
 a| 
link:reviewing-warnings-about-storage-volume-recovery.html["システムドライブに損傷がない場合は、ストレージボリューム障害からリカバリします"]
 a| 
この手順 はソフトウェアベースのストレージノードに使用されます。



 a| 
システムドライブで障害が発生した。
 a| 
link:reviewing-warnings-for-system-drive-recovery.html["システムドライブ障害からリカバリします"]
 a| 
ノード交換用手順 は、導入プラットフォーム、およびストレージボリュームに障害が発生しているかどうかによって異なります。

|===

NOTE: 一部の StorageGRID リカバリ手順では、 Reaper を使用して Cassandra の修復を処理します。関連サービスまたは必要なサービスが開始されるとすぐに修理が自動的に行われます。スクリプトの出力に「reaper」または「cassandra repair」と記載されていることがあります。修復が失敗したことを示すエラーメッセージが表示された場合は、エラーメッセージに示されているコマンドを実行します。
