---
permalink: maintain/recovering-from-storage-volume-failure-where-system-drive-is-intact.html 
sidebar: sidebar 
keywords: storagegrid, recover, storage volume failure, volume failure, system drive intact 
summary: ストレージノードで 1 個以上のストレージボリュームに障害が発生したものの、システムドライブに損傷がない場合は、一連のタスクを実行してソフトウェアベースのストレージノードをリカバリする必要があります。ストレージボリュームだけで障害が発生した場合は、ストレージノードを引き続き StorageGRID システムで使用できます。 
---
= システムドライブに損傷がない場合は、ストレージボリューム障害からリカバリします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージノードで 1 個以上のストレージボリュームに障害が発生したものの、システムドライブに損傷がない場合は、一連のタスクを実行してソフトウェアベースのストレージノードをリカバリする必要があります。ストレージボリュームだけで障害が発生した場合は、ストレージノードを引き続き StorageGRID システムで使用できます。


NOTE: このリカバリ用 手順 環境 ソフトウェアベースのストレージノードのみ。アプライアンスストレージノードのストレージボリュームで障害が発生した場合は、の代わりにアプライアンスの手順を使用してください。link:recovering-storagegrid-appliance-storage-node.html["アプライアンスストレージノードをリカバリします"]

このリカバリ手順には、次のタスクが含まれます。

* link:reviewing-warnings-about-storage-volume-recovery.html["ストレージボリュームのリカバリに関する警告の確認"]
* link:identifying-and-unmounting-failed-storage-volumes.html["障害ストレージボリュームを特定してアンマウントします"]
* link:recovering-failed-storage-volumes-and-rebuilding-cassandra-database.html["ボリュームをリカバリしてCassandraデータベースを再構築"]
* link:restoring-object-data-to-storage-volume-where-system-drive-is-intact.html["オブジェクトデータをリストア"]
* link:checking-storage-state-after-recovering-storage-volumes.html["ストレージの状態の確認"]

