---
permalink: maintain/removing-port-remaps.html 
sidebar: sidebar 
keywords: storagegrid, recover, remove port remap, removing port remap, port remap 
summary: ロードバランササービスのエンドポイントを設定する場合、ポートの再マッピングのマッピング先ポートとしてすでに設定されているポートを使用するには、まず既存のポートの再マッピングを削除する必要があります。そうしないと、エンドポイントが有効になりません。ノードのすべてのポートの再マッピングを削除するには、再マッピングされたポートが競合している各管理ノードおよびゲートウェイノードでスクリプトを実行する必要があります。 
---
= ポートの再マッピングを削除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ロードバランササービスのエンドポイントを設定する場合、ポートの再マッピングのマッピング先ポートとしてすでに設定されているポートを使用するには、まず既存のポートの再マッピングを削除する必要があります。そうしないと、エンドポイントが有効になりません。ノードのすべてのポートの再マッピングを削除するには、再マッピングされたポートが競合している各管理ノードおよびゲートウェイノードでスクリプトを実行する必要があります。

.タスクの内容
この手順 は、ポートの再マッピングをすべて削除します。一部の再マッピングを保持する必要がある場合は、テクニカルサポートにお問い合わせください。

ロードバランサエンドポイントの設定については、を参照してくださいlink:../admin/configuring-load-balancer-endpoints.html["ロードバランサエンドポイントの設定"]。


NOTE: ポートの再マッピングでクライアントアクセスが可能な場合は、サービスの中断を回避するために、別のポートをロードバランサエンドポイントとして使用するようにクライアントを再設定します。そうしないと、ポートマッピングを削除するとクライアントアクセスが失われるため、適切にスケジュールを設定する必要があります。


NOTE: この手順 は、ベアメタルホスト上のコンテナとして導入した StorageGRID システムでは機能しません。の手順を参照してくださいlink:removing-port-remaps-on-bare-metal-hosts.html["ベアメタルホストでのポートの再マッピングの削除"]。

.手順
. ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh -p 8022 admin@node_IP`
+
ポート 8022 はベース OS の SSH ポートで、ポート 22 は StorageGRID を実行しているコンテナエンジンの SSH ポートです。

.. ファイルに記載されているパスワードを入力し `Passwords.txt`ます。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. ファイルに記載されているパスワードを入力し `Passwords.txt`ます。
+
rootとしてログインすると、プロンプトがからに `#`変わります `$`。



. 次のスクリプトを実行します。 `remove-port-remap.sh`
. ノードをリブートします。 `reboot`
. コマンドシェルからログアウトします。 `exit`
. 再マッピングされたポートが競合している管理ノードおよびゲートウェイノードごとに上記の手順を繰り返します。

