---
permalink: maintain/rename-grid-site-node-overview.html 
sidebar: sidebar 
keywords: rename grid, rename site, rename node, display name, system name 
summary: 必要に応じて、グリッド全体、各サイト、および各ノードについて、Grid Managerで表示される表示名を変更できます。表示名は、必要なときに安全に更新できます。 
---
= 名前変更手順の使用
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
必要に応じて、グリッド全体、各サイト、および各ノードについて、Grid Managerで表示される表示名を変更できます。表示名は、必要なときに安全に更新できます。



== 手順 の名前変更とは何ですか。

StorageGRID を最初にインストールするときは、グリッド、各サイト、および各ノードの名前を指定します。これらの初期名は_システム名_と呼ばれ、StorageGRID 全体で最初に表示される名前です。

システム名は内部StorageGRID 処理に必要であり、変更することはできません。ただし、名前変更手順 を使用して、グリッド、各サイト、および各ノードのnew_display names_を定義できます。これらの表示名は、基になるシステム名の代わりに（場合によっては、それに加えて）StorageGRID のさまざまな場所に表示されます。

入力ミスを修正する場合、別の命名規則を実装する場合、またはサイトとそのすべてのノードが再配置されたことを示す場合は、名前変更手順 を使用します。システム名とは異なり、表示名は必要に応じていつでも更新でき、StorageGRID の処理には影響しません。



== システム名と表示名はどこに表示されますか？

次の表は、StorageGRID ユーザー・インターフェイスおよびStorageGRID ファイルでシステム名と表示名が表示される場所をまとめたものです。

[cols="1a,1a,3a"]
|===
| 場所 | システム名 | 表示名 


 a| 
Grid Managerのページ
 a| 
項目の名前が変更されない限り表示されます
 a| 
項目の名前が変更された場合は、システム名の代わりに次の場所に表示されます。

* ダッシュボード
* [Nodes]ページ
* ハイアベイラビリティグループ、ロードバランサエンドポイント、VLANインターフェイス、キー管理サーバ、グリッドパスワード、 ファイアウォール制御
* アラート
* ストレージプールの定義
* オブジェクトメタデータの検索ページ
* メンテナンス手順に関するページ（アップグレード、ホットフィックス、SANtricity OSのアップグレード、運用停止、 拡張、リカバリ、およびオブジェクトの存在のチェック
* サポートページ（ログと診断）
* シングルサインオンページ。テーブルで管理ノードのホスト名の横に表示され、管理ノードの詳細を確認できます




 a| 
*ノード* > ノードの *概要* タブ
 a| 
常に表示されます
 a| 
項目の名前が変更された場合にのみ表示されます



 a| 
* node-health * API
 a| 
常に返されます
 a| 
項目の名前が変更された場合にのみ返されます



 a| 
SSHを使用してノードにアクセスするときにプロンプトを表示します
 a| 
項目の名前が変更されていない場合は、プライマリ名として表示されます。

`admin@SYSTEM-NAME: ~ $`

項目の名前が変更されたときにかっこで囲まれます。

`admin@DISPLAY-NAME(SYSTEM-NAME):~ $`
 a| 
項目の名前が変更されたときにプライマリ名として表示されます。

`admin@DISPLAY-NAME(SYSTEM-NAME):~ $`



 a| 
`Passwords.txt`リカバリパッケージ内のファイル
 a| 
表示形式 `Server Name`
 a| 
表示形式 `Display Name`



 a| 
`/etc/hosts`すべてのノード上のファイル

例：

`10.96.99.128 SYSTEM-NAME 28989c59-a2c3-4d30-bb09-6879adf2437f DISPLAY-NAME localhost-grid # storagegrid-gen-host`
 a| 
常に2番目の列に表示されます
 a| 
項目の名前が変更されると、4番目の列に表示されます



 a| 
`topology-display-names.json`、AutoSupportデータに付属
 a| 
含まれません
 a| 
項目の名前が変更されていない場合は空です。名前が変更されていない場合は、グリッド、サイト、およびノードのIDが表示名にマッピングされます。

|===


== 表示名の要件

この手順 を使用する前に、表示名の要件を確認してください。



=== ノードの表示名

ノードの表示名は次のルールに従う必要があります。

* StorageGRID システム全体で一意である必要があります。
* StorageGRID システム内の他の項目のシステム名と同じにすることはできません。
* 1文字以上32文字以下にする必要があります。
* 数字、ハイフン（-）、大文字と小文字を含めることができます。
* 先頭または末尾にはアルファベットまたは数字を使用できますが、先頭または末尾にハイフンを使用することはできません。
* すべての数字を指定することはできません。
* 大文字と小文字は区別されません。たとえば `DC1-ADM`、と `dc1-adm`は重複しているとみなされます。


以前に別のノードで使用されていた表示名を使用してノードの名前を変更できます。ただし、表示名やシステム名が重複しないようにする必要があります。



=== グリッドとサイトの表示名

グリッドとサイトの表示名は同じルールに従いますが、次の例外があります。

* スペースを含めることができます。
* 次の特殊文字を含めることができます。 `= - _ : , . @ !`
* 先頭と末尾にハイフンを含む特殊文字を使用できます。
* すべての数字または特殊文字を使用できます。




== 表示名のベストプラクティス

複数の項目の名前を変更する場合は、この手順 を使用する前に一般的な命名規則を文書化してください。名前が一目で一意で一貫性があり、わかりやすいシステムを考えてみましょう。

組織の要件に合わせて任意の命名規則を使用できます。次のような基本的な提案を検討してください。

* *サイトインジケータ*：複数のサイトがある場合は、各ノード名にサイトコードを追加します。
* *ノードタイプ*：通常、ノード名はノードのタイプを示します。、 `adm`、 `gw`などの省略形を使用できます（ `s`ストレージノード、管理ノード、ゲートウェイノード）。
* *ノード番号*：サイトに特定のタイプのノードが複数含まれている場合は、各ノードの名前に一意の番号を追加します。


時間の経過とともに変更される可能性のある名前に特定の詳細を追加する前に、よく考えてください。たとえば、ノード名にIPアドレスを含めないでください。これらのアドレスは変更可能です。同様に、機器を移動したりハードウェアをアップグレードしたりすると、ラックの場所やアプライアンスのモデル番号が変わることがあります。



=== 表示名の例

StorageGRID システムに3つのデータセンターがあり、各データセンターに異なるタイプのノードがあるとします。表示名は次のように簡単になります。

* *グリッド*： `StorageGRID Deployment`
* *最初のサイト*： `Data Center 1`
+
** `dc1-adm1`
** `dc1-s1`
** `dc1-s2`
** `dc1-s3`
** `dc1-gw1`


* *セカンドサイト*： `Data Center 2`
+
** `dc2-adm2`
** `dc2-s1`
** `dc2-s2`
** `dc2-s3`


* * 3番目のサイト*： `Data Center 3`
+
** `dc3-s1`
** `dc3-s2`
** `dc3-s3`



