---
permalink: maintain/replacing-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, replace primary admin node, replacing primary admin node, primary admin node 
summary: プライマリ管理ノードをリカバリするには、まず物理または仮想ハードウェアの交換が必要です。 
---
= プライマリ管理ノードを交換
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プライマリ管理ノードをリカバリするには、まず物理または仮想ハードウェアの交換が必要です。

障害が発生したプライマリ管理ノードを同じプラットフォームで実行されているプライマリ管理ノードと交換することも、 VMware または Linux ホストで実行されているプライマリ管理ノードをサービスアプライアンスでホストされているプライマリ管理ノードと交換することもできます。

ノードに対して選択した交換用プラットフォームに一致する手順 を使用します。（すべてのノードタイプに適した）ノード交換手順 を完了すると、プライマリ管理ノードのリカバリに関する次のステップが手順 から表示されます。

[cols="1a,2a"]
|===
| 交換用プラットフォーム | 手順 


 a| 
VMware
 a| 
link:all-node-types-replacing-vmware-node.html["VMware ノードを交換"]



 a| 
Linux
 a| 
link:all-node-types-replacing-linux-node.html["Linux ノードを交換"]



 a| 
サービスアプライアンス
 a| 
link:replacing-failed-node-with-services-appliance.html["サービスアプライアンスを交換します"]



 a| 
OpenStack
 a| 
リカバリ処理を対象とした OpenStack 用の仮想マシンディスクファイルおよびスクリプトは、現在は提供されていません。OpenStack 環境で実行されているノードのリカバリが必要な場合は、使用している Linux オペレーティングシステム用のファイルをダウンロードしてください。次に、の手順に従いますlink:all-node-types-replacing-linux-node.html["Linuxノードの交換"]。

|===