---
permalink: maintain/reviewing-ilm-policy-and-storage-configuration.html 
sidebar: sidebar 
keywords: storagegrid, restore, ilm policy, storage configuration 
summary: ストレージノードの運用を停止する場合は、運用停止プロセスを開始する前に、 StorageGRID システムの ILM ポリシーを確認してください。 
---
= ILM ポリシーとストレージ構成を確認します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージノードの運用を停止する場合は、運用停止プロセスを開始する前に StorageGRID システムの ILM ポリシーを確認してください。

運用停止時に、運用停止されたストレージノードのすべてのオブジェクトデータが他のストレージノードに移行されます。


NOTE: 運用停止中の ILM ポリシーは、運用停止後のポリシーとして使用されます。運用停止を開始する前と運用停止の完了後に、このポリシーがデータの要件を満たしていることを確認する必要があります。

各のルールを確認して、ストレージノードの運用停止に対応できるように、StorageGRIDシステムの容量が適切な場所に適切なタイプの十分な容量を引き続き確保する必要がありlink:../ilm/creating-ilm-policy.html["アクティブなILMポリシー"]ます。

次の点を考慮してください。

* ILM 評価サービスで ILM ルールを満たすようにオブジェクトデータをコピーすることは可能か。
* 運用停止処理の進行中にサイトが一時的に使用不能になった場合は、どうなりますか？追加のコピーを別の場所に作成できるか。
* 運用停止プロセスは、コンテンツの最終的な配信にどのように影響しますか。で説明されているようにlink:consolidating-storage-nodes.html["ストレージノードを統合します"]、古いシステムの運用を停止する前に実行する必要がありますlink:../expand/index.html["新しいストレージノードを追加します"]。小さいストレージノードの運用を停止してから、交換用に大きいストレージノードを追加すると、以前からあるストレージノードが容量の限界に近づき、新しいストレージノードにはほとんどコンテンツが存在しない状態になる可能性があります。新しいオブジェクトデータの書き込み処理のほとんどは新しいストレージノードに送信されるため、システム処理の全体的な効率が低下します。
* アクティブなILMポリシーを満たす十分な数のストレージノードが常にシステムに含まれているか。
+

NOTE: ILMポリシーを満たすことができないと、バックログやアラートが発生し、StorageGRIDシステムの運用が停止する可能性があります。



次の表に示す領域を評価して、運用停止プロセスの結果として提示される推奨トポロジがILMポリシーを満たしていることを確認します。

[cols="1a,2a"]
|===
| 評価する領域 | 考慮事項 


 a| 
使用可能容量
 a| 
StorageGRIDシステムに格納されているすべてのオブジェクトデータ（運用を停止するストレージノードに現在格納されているオブジェクトデータの永続的なコピーを含む）を格納できるだけの十分なストレージ容量を確保できるか。

運用停止処理が完了してから妥当な期間にわたって格納されるオブジェクトデータの予測される増加に対応できるだけの十分な容量を確保できるか。



 a| 
ストレージの場所
 a| 
StorageGRID システム全体に十分な容量が残っている場合、 StorageGRID システムのビジネスルールを満たす適切な場所に容量が配置されているか。



 a| 
ストレージタイプ
 a| 
運用停止処理が完了したあとに、適切なタイプのストレージを十分に確保できるか。

たとえば、コンテンツが古くなったときに、ILMルールによってあるタイプのストレージから別のタイプのストレージにコンテンツが移動されることがあります。この場合、StorageGRIDシステムの最終構成で、適切なタイプのストレージが十分に確保されていることを確認する必要があります。

|===