---
permalink: maintain/reviewing-warnings-about-storage-volume-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, volume warning 
summary: ストレージノードの障害ストレージボリュームをリカバリする前に、次の警告を確認する必要があります。 
---
= ストレージボリュームのリカバリに関する警告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージノードの障害ストレージボリュームをリカバリする前に、次の警告を確認してください。

ストレージノード内のストレージボリューム（ rangedb ）は、ボリューム ID と呼ばれる 16 進数で識別されます。たとえば、 0000 は最初のボリューム、 000F は 16 番目のボリュームです。各ストレージノードの最初のオブジェクトストア（ボリューム 0 ）は、オブジェクトメタデータと Cassandra データベースの処理に最大 4TB のスペースを使用します。このボリュームの残りのスペースはオブジェクトデータに使用されます。他のすべてのストレージボリュームは、オブジェクトデータ専用のボリュームです。

ボリューム 0 で障害が発生してリカバリが必要な場合は、ボリュームリカバリ手順 の一部として Cassandra データベースの再構築が必要になることがあります。次の状況でも、 Cassandra が再構築されることがあります。

* ストレージノードが 15 日以上オフラインになったあと、オンラインに戻ります。
* システムドライブと 1 つ以上のストレージボリュームで障害が発生し、リカバリされた。


Cassandra の再構築時、システムは他のストレージノードからの情報を使用します。オフラインのストレージノードが多すぎると、一部の Cassandra データを使用できない可能性があります。最近 Cassandra が再構築された場合は、 Cassandra データの一貫性がまだグリッド全体で確保されていないことがあります。オフラインのストレージノードが多すぎる場合や複数のストレージノードが 15 日以内に再構築されている場合は、データ損失が発生する可能性があります。


CAUTION: 複数のストレージノードで障害が発生した場合（またはオフラインの場合）は、テクニカルサポートにお問い合わせください。次の回復手順 を実行しないでください。データが失われる可能性があります。


CAUTION: ストレージノードの障害またはリカバリ後 15 日以内に 2 つ目のストレージノードの障害が発生した場合は、テクニカルサポートにお問い合わせください。15 日以内に複数のストレージノードで Cassandra を再構築すると、データが失われることがあります。


NOTE: サイトの複数のストレージノードで障害が発生した場合は、サイトリカバリ手順 が必要になる可能性があります。を参照して link:how-site-recovery-is-performed-by-technical-support.html["テクニカルサポートによるサイトのリカバリ方法"]


CAUTION: レプリケートコピーを 1 つだけ保存するように ILM ルールを設定している場合に、そのコピーがあるストレージボリュームで障害が発生すると、オブジェクトをリカバリできません。

.関連情報
link:warnings-and-considerations-for-grid-node-recovery.html["グリッドノードのリカバリに関する警告と考慮事項"]
