---
permalink: maintain/reviewing-warnings-for-system-drive-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, system drive warning, storage node 
summary: ストレージノードの障害システムドライブをリカバリする前に、グリッドノードのリカバリに関する一般的な警告と考慮事項、および次の固有の警告を確認してください。 
---
= ストレージノードのシステムドライブのリカバリに関する警告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージノードの障害システムドライブをリカバリする前に、一般的な警告と以下の固有の警告を確認してくださいlink:warnings-and-considerations-for-grid-node-recovery.html["グリッドノードのリカバリに関する警告と考慮事項"]。

ストレージ ノードには、オブジェクト メタデータを含む Cassandra データベースがあります。次の場合には、Cassandra データベースが再構築される可能性があります。

* ストレージ ボリュームに障害が発生し、回復しました。
* システムドライブと 1 つ以上のストレージボリュームで障害が発生し、リカバリされた。


Cassandra が再構築されると、システムは他のストレージ ノードからの情報を使用します。 Cassandra が最近再構築された場合、Cassandra データはグリッド全体でまだ一貫していない可能性があります。オフラインのストレージノードが多すぎる場合:

* 一部の Cassandra データは利用できない可能性があります。
* データが失われる可能性があります。



CAUTION: 複数のストレージ ノードに障害が発生した場合 (またはオフラインの場合) は、テクニカル サポートにお問い合わせください。次の回復手順を実行しないでください。データが失われる可能性があります。詳細については、 link:how-site-recovery-is-performed-by-technical-support.html["テクニカルサポートによるサイトのリカバリ方法"] 。


CAUTION: このストレージノードが、障害ストレージボリュームがある別のストレージノードにオブジェクトを読み出せるように読み取り専用メンテナンスモードになっている場合は、障害ストレージボリュームがあるそのストレージノードでボリュームをリカバリしてから、この障害ストレージノードをリカバリします。の手順を参照してくださいlink:recovering-from-storage-volume-failure-where-system-drive-is-intact.html["システムドライブに損傷がない場合は、ストレージボリューム障害からリカバリします"]。


CAUTION: レプリケートコピーを 1 つだけ保存するように ILM ルールを設定している場合に、そのコピーがあるストレージボリュームで障害が発生すると、オブジェクトをリカバリできません。
