---
permalink: maintain/reviewing-warnings-for-system-drive-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, system drive warning, storage node 
summary: ストレージノードの障害システムドライブをリカバリする前に、グリッドノードのリカバリに関する一般的な警告と考慮事項、および次の固有の警告を確認してください。 
---
= ストレージノードのシステムドライブのリカバリに関する警告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージノードの障害システムドライブをリカバリする前に、一般的な警告と以下の固有の警告を確認してくださいlink:warnings-and-considerations-for-grid-node-recovery.html["グリッドノードのリカバリに関する警告と考慮事項"]。

ストレージノードには、オブジェクトメタデータを含む Cassandra データベースがあります。次の状況では、 Cassandra データベースが再構築されることがあります。

* ストレージノードが 15 日以上オフラインになったあと、オンラインに戻ります。
* ストレージボリュームで障害が発生し、リカバリされた。
* システムドライブと 1 つ以上のストレージボリュームで障害が発生し、リカバリされた。


Cassandra の再構築時、システムは他のストレージノードからの情報を使用します。オフラインのストレージノードが多すぎると、一部の Cassandra データを使用できない可能性があります。最近 Cassandra が再構築された場合は、 Cassandra データの一貫性がまだグリッド全体で確保されていないことがあります。オフラインのストレージノードが多すぎる場合や複数のストレージノードが 15 日以内に再構築されている場合は、データ損失が発生する可能性があります。


CAUTION: 複数のストレージノードで障害が発生した場合（またはオフラインの場合）は、テクニカルサポートにお問い合わせください。次の回復手順 を実行しないでください。データが失われる可能性があります。


CAUTION: ストレージノードの障害またはリカバリ後 15 日以内に 2 つ目のストレージノードの障害が発生した場合は、テクニカルサポートにお問い合わせください。15 日以内に複数のストレージノードで Cassandra を再構築すると、データが失われることがあります。


NOTE: サイトの複数のストレージノードで障害が発生した場合は、サイトリカバリ手順 が必要になる可能性があります。を参照して link:how-site-recovery-is-performed-by-technical-support.html["テクニカルサポートによるサイトのリカバリ方法"]


CAUTION: このストレージノードが、障害ストレージボリュームがある別のストレージノードにオブジェクトを読み出せるように読み取り専用メンテナンスモードになっている場合は、障害ストレージボリュームがあるそのストレージノードでボリュームをリカバリしてから、この障害ストレージノードをリカバリします。の手順を参照してくださいlink:recovering-from-storage-volume-failure-where-system-drive-is-intact.html["システムドライブに損傷がない場合は、ストレージボリューム障害からリカバリします"]。


CAUTION: レプリケートコピーを 1 つだけ保存するように ILM ルールを設定している場合に、そのコピーがあるストレージボリュームで障害が発生すると、オブジェクトをリカバリできません。
