---
permalink: maintain/reviewing-warnings-about-storage-volume-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, volume warning 
summary: ストレージノードの障害ストレージボリュームをリカバリする前に、次の警告を確認する必要があります。 
---
= ストレージボリュームのリカバリに関する警告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージノードの障害ストレージボリュームをリカバリする前に、次の警告を確認してください。

ストレージノード内のストレージボリューム（ rangedb ）は、ボリューム ID と呼ばれる 16 進数で識別されます。たとえば、 0000 は最初のボリューム、 000F は 16 番目のボリュームです。各ストレージノードの最初のオブジェクトストア（ボリューム 0 ）は、オブジェクトメタデータと Cassandra データベースの処理に最大 4TB のスペースを使用します。このボリュームの残りのスペースはオブジェクトデータに使用されます。他のすべてのストレージボリュームは、オブジェクトデータ専用のボリュームです。

次の場合、ボリューム回復手順の一環として Cassandra データベースが再構築される可能性があります。

* ボリューム 0 に障害が発生し、回復されました。
* システムドライブと 1 つ以上のストレージボリュームで障害が発生し、リカバリされた。


Cassandra が再構築されると、システムは他のストレージ ノードからの情報を使用します。 Cassandra が最近再構築された場合、Cassandra データはグリッド全体でまだ一貫していない可能性があります。オフラインのストレージノードが多すぎる場合:

* 一部の Cassandra データは利用できない可能性があります。
* データが失われる可能性があります。



CAUTION: 複数のストレージ ノードに障害が発生した場合 (またはオフラインの場合) は、テクニカル サポートにお問い合わせください。次の回復手順は実行しないでください。データが失われる可能性があります。詳細については、 link:how-site-recovery-is-performed-by-technical-support.html["テクニカルサポートによるサイトのリカバリ方法"] 。


CAUTION: ILM ルールが複製されたコピーを 1 つだけ保存するように構成されていて、そのコピーが障害が発生したストレージ ボリューム上に存在する場合、オブジェクトを回復することはできません。

.関連情報
link:warnings-and-considerations-for-grid-node-recovery.html["グリッドノードのリカバリに関する警告と考慮事項"]
