---
permalink: maintain/reviewing-warnings-about-storage-volume-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, volume warning 
summary: ストレージノードの障害ストレージボリュームをリカバリする前に、次の警告を確認する必要があります。 
---
= ストレージボリュームのリカバリに関する警告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージノードの障害ストレージボリュームをリカバリする前に、次の警告を確認してください。

ストレージノード内のストレージボリューム（ rangedb ）は、ボリューム ID と呼ばれる 16 進数で識別されます。たとえば、 0000 は最初のボリューム、 000F は 16 番目のボリュームです。各ストレージノードの最初のオブジェクトストア（ボリューム 0 ）は、オブジェクトメタデータと Cassandra データベースの処理に最大 4TB のスペースを使用します。このボリュームの残りのスペースはオブジェクトデータに使用されます。他のすべてのストレージボリュームは、オブジェクトデータ専用のボリュームです。

次の場合、ボリュームのリカバリ手順の一環としてCassandraデータベースが再構築されることがあります。

* ボリューム0に障害が発生し、リカバリされます。
* システムドライブと 1 つ以上のストレージボリュームで障害が発生し、リカバリされた。


Cassandra の再構築時、システムは他のストレージノードからの情報を使用します。最近 Cassandra が再構築された場合は、 Cassandra データの一貫性がまだグリッド全体で確保されていないことがあります。オフラインのストレージノードが多すぎる場合：

* 一部のCassandraデータを使用できない可能性があります。
* データが失われる可能性があります。



CAUTION: 複数のストレージノードで障害が発生した場合（またはオフラインの場合）は、テクニカルサポートにお問い合わせください。次のリカバリ手順 は実行しないでください。データが失われる可能性があります。詳細については、を参照してください link:how-site-recovery-is-performed-by-technical-support.html["テクニカルサポートによるサイトのリカバリ方法"]。


CAUTION: レプリケートコピーを1つだけ格納するようにILMルールを設定している場合に、そのコピーがあるストレージボリュームで障害が発生すると、オブジェクトをリカバリできません。

.関連情報
link:warnings-and-considerations-for-grid-node-recovery.html["グリッドノードのリカバリに関する警告と考慮事項"]
