---
permalink: maintain/selecting-node-recovery-procedure.html 
sidebar: sidebar 
keywords: storagegrid, recover, procedure 
summary: 障害が発生したノードの種類に応じて、適切な復旧手順を選択してください。 
---
= StorageGRIDノード復旧手順を選択
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
障害が発生したノードの種類に応じて、適切な復旧手順を選択してください。

[cols="1a,2a"]
|===
| Grid ノード | Recovery 手順 の略 


 a| 
ストレージノード
 a| 
ストレージノードの復旧手順は、障害の種類によって異なります。

link:recovering-from-storage-node-failures.html["ストレージノードの障害からリカバリします"]



 a| 
管理ノード
 a| 
管理ノードの手順 は、プライマリ管理ノードと非プライマリ管理ノードのどちらをリカバリする必要があるかによって異なります。

link:recovering-from-admin-node-failures.html["管理ノードの障害からリカバリ"]



 a| 
ゲートウェイノード
 a| 
link:replacing-gateway-node.html["ゲートウェイノードの障害からリカバリします"]



 a| 
アーカイブノード
 a| 
https://docs.netapp.com/us-en/storagegrid-118/maintain/recovering-from-archive-node-failures.html["アーカイブノードの障害からのリカバリ（StorageGRID 11.8ドキュメントサイト）"^]

|===

NOTE: 複数のグリッドノードをホストしているサーバーが故障した場合、ノードは任意の順序で復旧できます。ただし、障害が発生したサーバーがプライマリ管理ノードをホストしており、プライマリ以外の管理ノードが存在しない場合は、まずプライマリ管理ノードを復旧する必要があります。プライマリ管理ノードを最初に復旧することで、他のノードの復旧がプライマリ管理ノードへの接続を試みる際に停止するのを防ぐことができます。プライマリ以外の管理ノードが利用可能な場合は、それを使用して他のノードを復旧することもできます。これにより、プライマリ管理ノードに接続することなく復旧処理を進めることができます。
