---
permalink: maintain/starting-software-installation-on-services-appliance-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, services appliance, start software installation 
summary: ゲートウェイノードまたは管理ノードをサービスアプライアンスにインストールするには、アプライアンスに含まれているStorageGRIDアプライアンスインストーラを使用します。 
---
= サービスアプライアンスでStorageGRIDソフトウェアのインストールを開始する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ゲートウェイノードまたは管理ノードをサービスアプライアンスにインストールするには、アプライアンスに含まれているStorageGRIDアプライアンスインストーラを使用します。

.開始する前に
* アプライアンスをラックに設置し、ネットワークに接続して電源をオンにします。
* StorageGRID アプライアンスインストーラを使用して、アプライアンスのネットワークリンクとIPアドレスを設定します。
* ゲートウェイノードまたはプライマリ以外の管理ノードをインストールする場合は、以下のいずれかの管理ノードの IP アドレスを把握している必要があります。
+
** StorageGRID グリッドのプライマリ管理ノード
** プライマリ以外の管理ノードが利用可能で、ノードの復旧に使用されている場合


* プライマリ管理ノード以外の管理ノードを使用してノード（プライマリ管理ノードを含む）を復旧する場合、その管理ノードのIPアドレスを指定できます。
* StorageGRID アプライアンスインストーラの[IP Configuration]ページにリストされているすべてのグリッドネットワークサブネットは、プライマリ管理ノードのグリッドネットワークサブネットリストで定義されます。
+
を参照してください https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/index.html["ハードウェア設置のクイックスタート"^]

* を使用しているlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* アプライアンスに割り当てられたIPアドレスのいずれかを確認しておきます。管理ネットワーク、グリッドネットワーク、またはクライアントネットワークの IP アドレスを使用できます。
* プライマリ管理ノードをインストールする場合は、このバージョンの StorageGRID 用の Ubuntu または Debian のインストールファイルが必要です。
+

NOTE: 最新バージョンの StorageGRID ソフトウェアは、製造時にサービスアプライアンスにプリロードされています。プリロードされたソフトウェアのバージョンがStorageGRID 環境で使用されているバージョンと一致する場合は、インストールファイルは必要ありません。



.タスクの内容
サービスアプライアンスにStorageGRIDソフトウェアをインストールするには、次の手順を実行します。

* プライマリ管理ノードの場合、ノード名を指定し、必要に応じて適切なソフトウェアパッケージをアップロードします。プライマリ管理ノードを復旧する場合で、グリッド内にプライマリ以外の管理ノードが存在する場合は、プライマリ以外の管理ノードを使用してノードを復旧し、その管理ノードのIPアドレスを指定するか、現在の構成を使用してノードをインストールまたは復旧するかのいずれかを選択できます。
* 非プライマリ管理ノードまたはゲートウェイノードの場合は、プライマリ管理ノードの IP アドレスとノードの名前を指定または確認します。
* インストールを開始し、ボリュームの設定とソフトウェアのインストールが行われている間待機します。
* プロセスの途中でインストールが一時停止します。インストールを再開するには、 Grid Manager にサインインして、保留状態のノードを障害ノードの代わりとして設定する必要があります。
* ノードを設定すると、アプライアンスのインストールプロセスが完了してアプライアンスがリブートされます。


.手順
. ブラウザを開き、サービスアプライアンスのいずれかのIPアドレスを入力します。
+
`https://_Controller_IP_:8443`

+
StorageGRID アプライアンスインストーラのホームページが表示されます。

. プライマリ管理ノードをインストールするには:
+
.. このノードセクションで、 * ノードタイプ * に * プライマリ管理者 * を選択します。
.. *ノード名*フィールドに、復旧対象のノードに使用されていた名前と同じ名前を入力し、*保存*を選択します。
.. インストールモードのセクションで利用可能な2つのモードから、適切なモードを選択してください。「ノードをインストールするか、現在の構成を使用してこのノードを復旧する」方法、または「プライマリ以外の管理ノードを使用してこのノードを復旧する」方法のいずれかを選択できます。
+
[role="tabbed-block"]
====
.現在の構成方法
--
現在の構成を使用して、ノードをインストールするか、このノードを復旧してください。

... インストールセクションで、「現在の状態」に表示されているソフトウェアのバージョンを確認してください。インストール準備が整ったソフトウェアのバージョンが正しい場合は、<<installation_section_step,インストール手順>>に進んでください。
... 別のバージョンのソフトウェアをアップロードする必要がある場合は、*詳細設定*メニューで*StorageGRID ソフトウェアのアップロード*を選択してください。「StorageGRID ソフトウェアのアップロード」ページが表示されます。
... 「参照」を選択して、StorageGRID ソフトウェアの「ソフトウェアパッケージ」と「チェックサムファイル」をアップロードします。ファイルを選択すると、自動的にアップロードされます。
... 「ホーム」を選択して、StorageGRID アプライアンスインストーラのホームページに戻ります。


--
.非プライマリ管理者ノード方式
--
プライマリ以外の管理ノードを使用して、このノードを復旧してください。

... 「非プライマリ管理ノードIP」フィールドに、復旧に使用する非プライマリ管理ノードのグリッドネットワークIPアドレスを入力し、*保存*を選択します。
... インストールする準備ができたソフトウェアのバージョンが正しい場合は、に進みます<<installation_section_step,インストール手順>>。


--
====


. ゲートウェイ ノードまたは非プライマリ管理ノードをインストールするには:
+
.. このノードセクションで、 * ノードタイプ * には、リストアするノードのタイプに応じて * ゲートウェイ * または * 非プライマリ管理 * を選択します。
.. *ノード名*フィールドに、復旧対象のノードに使用されていた名前と同じ名前を入力し、*保存*を選択します。
.. プライマリ管理ノードの接続セクションで、プライマリ管理ノードの IP アドレスを指定する必要があるかどうかを確認します。
+
プライマリ管理ノードまたは ADMIN_IP が設定された少なくとも 1 つのグリッドノードが同じサブネットにある場合は、 StorageGRID アプライアンスインストーラがこの IP アドレスを自動的に検出します。

.. この IP アドレスが表示されない場合、または変更する必要がある場合は、アドレスを指定します。


+
[cols="1a,2a"]
|===
| オプション | 製品説明 


 a| 
IP を手動で入力します
 a| 
.. [管理ノードの検出を有効にする]*チェックボックスをオフにします。
.. IPアドレスを手動で入力します。
.. [ 保存（ Save ） ] を選択します。
.. 新しいIPアドレスの接続状態が「READY」になるまで待ちます。




 a| 
接続されたすべてのプライマリ管理ノードの自動検出
 a| 
.. [管理ノードの検出を有効にする]*チェックボックスを選択します。
.. 検出された IP アドレスのリストから、このサービスアプライアンスを導入するグリッドのプライマリ管理ノードを選択します。
.. [ 保存（ Save ） ] を選択します。
.. 新しいIPアドレスの接続状態が「READY」になるまで待ちます。


|===
. [[installation_section_step]] インストールセクションで、現在の状態がノード名のインストールを開始する準備ができていること、および * インストールの開始 * ボタンが有効になっていることを確認します。
+
*インストールの開始*ボタンが有効になっていない場合は、ネットワーク構成またはポート設定を変更する必要がある可能性があります。アプライアンスのメンテナンス手順を参照してください。

. StorageGRID アプライアンスインストーラーのホームページで、「インストールの開始」を選択します。
+
現在の状態が「インストール中です」に変わり、モニターのインストールページが表示されます。

+

NOTE: モニターのインストールページに手動でアクセスする必要がある場合は、メニューバーから「Monitor installation」を選択してください。


