---
permalink: maintain/starting-storagegrid-appliance-installation.html 
sidebar: sidebar 
keywords: storagegrid, recover, appliance, appliance install 
summary: StorageGRID をアプライアンスストレージノードにインストールするには、アプライアンスに含まれている StorageGRID アプライアンスインストーラを使用します。 
---
= StorageGRID アプライアンスのインストールを開始します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID をアプライアンスストレージノードにインストールするには、アプライアンスに含まれている StorageGRID アプライアンスインストーラを使用します。

.開始する前に
* アプライアンスをラックに設置し、ネットワークに接続し、電源を投入しておきます。
* StorageGRID アプライアンスインストーラを使用してアプライアンスのネットワークリンクと IP アドレスを設定しておきます。
* 以下のいずれかの管理ノードの IP アドレスを把握しています。
+
** StorageGRID グリッドのプライマリ管理ノード
** プライマリ以外の管理ノード（利用可能な場合）


* StorageGRID アプライアンスインストーラの IP 設定ページに表示されるすべてのグリッドネットワークサブネットが、プライマリ管理ノードのグリッドネットワークサブネットリストで定義されている。
* これらの必要な準備作業を完了しておくには、ストレージアプライアンスのインストール手順に従ってください。を参照してください https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/index.html["ハードウェア設置のクイックスタート"^]
* を使用しているlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* アプライアンスのコンピューティングコントローラに割り当てられている IP アドレスのいずれかを確認しておきます。管理ネットワーク（コントローラの管理ポート 1 ）、グリッドネットワーク、またはクライアントネットワークの IP アドレスを使用できます。


.タスクの内容
StorageGRID をアプライアンスストレージノードにインストールするには、次の手順を実行します。

* プライマリ管理ノードのIPアドレスを指定します。プライマリ管理ノードが利用できない場合は、利用可能であれば、プライマリ以外の管理ノードのIPアドレスを指定します。また、ノードのホスト名（システム名）を確認します。
* インストールを開始し、ボリュームの設定とソフトウェアのインストールが行われている間待機します。
+

NOTE: アプライアンス ストレージ ノードを回復する場合は、元のアプライアンスと同じストレージ タイプ (結合、メタデータのみ、またはデータのみ) で再インストールします。異なるストレージ タイプを指定した場合、リカバリは失敗し、正しいストレージ タイプを指定してアプライアンスを再インストールする必要があります。

* プロセスの途中でインストールが一時停止します。インストールを再開するには、 Grid Manager にサインインして、保留状態のストレージノードを障害ノードの代わりとして設定する必要があります。
* ノードを設定すると、アプライアンスのインストールプロセスが完了してアプライアンスがリブートされます。


.手順
. ブラウザを開き、コンピューティングコントローラの IP アドレスのいずれかを入力します。
+
`https://_Controller_IP_:8443`

+
StorageGRID アプライアンスインストーラのホームページが表示されます。

. プライマリ管理ノードの接続セクションで、プライマリ管理ノードの IP アドレスを指定する必要があるかどうかを確認します。
+
プライマリ管理ノードまたは ADMIN_IP が設定された少なくとも 1 つのグリッドノードが同じサブネットにある場合は、 StorageGRID アプライアンスインストーラがこの IP アドレスを自動的に検出します。

. この IP アドレスが表示されない場合や変更する必要がある場合は、アドレスを指定します。
+
[cols="1a,2a"]
|===
| オプション | 手順 


 a| 
IP を手動で入力します
 a| 
.. [管理ノードの検出を有効にする]*チェックボックスをオフにします。
.. IP アドレスを手動で入力します。


*注*: インストールの場合、ノードのインストールに使用する管理ノードの IP アドレスを手動で入力します。リカバリの場合、プライマリ管理ノードの IP が使用可能な場合はそれを使用し、そうでない場合は非プライマリ管理ノードの IP を使用します。

.. [ 保存（ Save ） ] を選択します。
.. 新しいIPアドレスの接続状態が「READY」になるまで待ちます。




 a| 
接続されたすべてのプライマリ管理ノードの自動検出
 a| 
.. [管理ノードの検出を有効にする]*チェックボックスを選択します。
.. 検出された IP アドレスのリストから、このアプライアンス ストレージ ノードがデプロイされるグリッドの管理ノードを選択します。


*注*: リカバリの場合、プライマリ管理ノードの IP が使用可能な場合はそれを使用し、そうでない場合は非プライマリ管理ノードの IP を使用します。

.. [ 保存（ Save ） ] を選択します。
.. 新しいIPアドレスの接続状態が「READY」になるまで待ちます。


|===


. 「ノード名」フィールドに、復旧対象のノードで使用されていたホスト名（システム名）と同じものを入力し、「保存」を選択します。
. 「インストール」セクションで、現在の状態が「 `_node name_`をプライマリ管理ノード `_admin_ip_` を持つグリッドにインストールする準備ができています」であることと、*インストールの開始*ボタンが有効になっていることを確認します。
+
[Start Installation* （インストールの開始） ] ボタンが有効になっていない場合は、ネットワーク設定またはポート設定の変更が必要になることがあります。手順については、アプライアンスのメンテナンス手順を参照してください。

. StorageGRID アプライアンスインストーラーのホームページで、「インストールの開始」を選択します。
+
現在の状態が「インストール中です」に変わり、モニターのインストールページが表示されます。

+

NOTE: モニターのインストールページに手動でアクセスする必要がある場合は、メニューバーから「モニターのインストール」を選択してください。参照してください https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/monitoring-appliance-installation.html["アプライアンスの設置を監視する"^]。


