---
permalink: maintain/step-3-revise-ilm-policy.html 
sidebar: sidebar 
keywords: storagegrid, recover, revise ilm policies 
summary: '[Decommission Site]ウィザードの手順3\（[Revise ILM Policies]）では、サイトがILMポリシーで参照されているかどうかを確認できます。' 
---
= 手順3：ILMポリシーを改訂する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[Decommission Site]ウィザードの[Step 3（Revise ILM Policies]）では、サイトがILMポリシーで参照されているかどうかを確認できます。

.開始する前に
あなたは方法を十分に理解していlink:../ilm/index.html["ILMによるオブジェクトの管理"]ます。ストレージプールとILMルールの作成、およびILMポリシーのシミュレートとアクティブ化について十分に理解している。

.タスクの内容
ポリシー（アクティブまたは非アクティブ）に含まれるILMルールがそのサイトを参照している場合、StorageGRIDはサイトの運用を停止できません。

運用を停止するサイトを参照しているILMポリシーがある場合は、それらのポリシーを削除するか、次の要件を満たすように編集する必要があります。

* すべてのオブジェクトデータを完全に保護
* 廃止するサイトを参照しないでください。
* サイトを参照するストレージプールを使用したり、[すべてのサイト]オプションを使用したりしないでください。
* サイトを参照するイレイジャーコーディングプロファイルは使用しないでください。
* StorageGRID 11.6以前のインストールでは、Make 2 Copiesルールは使用しないでください。



CAUTION: サイトの削除に対応するためにシングルコピーの ILM ルールを作成しないでください。ある期間にレプリケートコピーを 1 つしか作成しない ILM ルールには、データが永続的に失われるリスクがあります。オブジェクトのレプリケートコピーが 1 つしかない場合、ストレージノードに障害が発生したり、重大なエラーが発生すると、そのオブジェクトは失われます。また、アップグレードなどのメンテナンス作業中は、オブジェクトへのアクセスが一時的に失われます。


TIP: _connectedサイトの運用停止_を実行する場合は、削除するサイトの現在のオブジェクトデータをStorageGRIDがどのように管理するかを検討する必要があります。データ保護の要件に応じて、新しいルールで既存のオブジェクトデータを別のサイトに移動したり、不要になった余分なオブジェクトコピーを削除したりできます。

新しいポリシーの設計についてサポートが必要な場合は、テクニカルサポートにお問い合わせください。

.手順
. 手順3（[Revise ILM Policies]）で、運用停止対象として選択したサイトを参照するILMポリシーがないかどうかを確認します。
. ポリシーが表示されない場合は、*[次へ]*を選択してに進みますlink:step-4-remove-ilm-references.html["手順 4 ： ILM 参照を削除する"]。
. 1つ以上の_active_ILMポリシーが表示された場合は、既存の各ポリシーをクローニングするか、運用停止するサイトを参照しない新しいポリシーを作成します。
+
.. [Policy Name]列でポリシーのリンクを選択します。
+
ブラウザの新しいタブに、ポリシーのILMポリシーの詳細ページが表示されます。[Decommission Site] ページは、 [other] タブに表示されたままになります。

.. 必要に応じて、次のガイドラインと手順に従ってください。
+
*** ILMルールの操作：
+
**** link:../ilm/creating-storage-pool.html["1つ以上のストレージプールを作成する"]サイトを参照していません
**** link:../ilm/working-with-ilm-rules-and-ilm-policies.html["ルールの編集または置換"]サイトを参照しています。
+

NOTE: このルールでは* All Storage Nodes *ストレージプールを使用しているため、* Make 2 Copies *ルールは選択しないでください。このルールは許可されていません。



*** ILMポリシーの操作：
+
**** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#clone-ilm-policy["既存のILMポリシーをクローニングする"] または link:../ilm/creating-ilm-policy.html["新しいILMポリシーを作成します"]。
**** デフォルトのルールやその他のルールがサイトを参照していないことを確認します。
+

CAUTION: ILM ルールの順序が正しいことを確認してください。ポリシーをアクティブ化すると、新規および既存のオブジェクトがリスト内の順にルールによって評価されます。





.. テストオブジェクトを取り込み、ポリシーをシミュレートして、正しいルールが適用されることを確認します。
+

CAUTION: 原因 ポリシーにエラーがあると、回復不能なデータ損失が発生する可能性があります。ポリシーをアクティブ化する前によく確認およびシミュレートし、想定どおりに機能することを確認してください。

+

CAUTION: 新しい ILM ポリシーをアクティブ化すると、 StorageGRID は、そのポリシーを使用して、既存のオブジェクトと新たに取り込まれたオブジェクトを含むすべてのオブジェクトを管理します。新しい ILM ポリシーをアクティブ化する前に、既存のレプリケートオブジェクトとイレイジャーコーディングオブジェクトの配置に対する変更を確認してください。既存のオブジェクトの場所を変更すると、新しい配置が評価されて実装される際に一時的なリソースの問題が発生する可能性があります。

.. 新しいポリシーをアクティブ化し、古いポリシーが非アクティブになったことを確認します。
+
複数のポリシーをアクティブ化する場合は、link:../ilm/creating-ilm-policy.html#activate-ilm-policy["手順に従ってILMポリシータグを作成します。"]を参照してください。

+
接続さ StorageGRID れたサイトの運用停止手順を実行すると、新しい ILM ポリシーをアクティブ化した時点で、選択したサイトからオブジェクトデータの削除が開始されます。すべてのオブジェクトコピーの移動または削除には数週間かかることがあります。サイトにオブジェクトデータが残っている間もサイトの運用停止を安全に開始できますが、実際の運用停止手順 を開始する前にデータをサイトから移動することが許可されている場合は、運用停止手順 の処理がより迅速になり、システム停止やパフォーマンスへの影響も少なくなります （ウィザードの手順 5 で「 * 分解を開始」を選択）。



. EACH_INACTIVE_POLICYについては、前の手順で説明したように、最初に各ポリシーのリンクを選択して編集または削除します。
+
** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#edit-ilm-policy["ポリシーを編集します。"]そのため、廃棄されるサイトを参照していません。
** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#remove-ilm-policy["ポリシーを削除します。"]です。


. ILMルールとポリシーの変更が完了したら、手順3（[Revise ILM Policies]）に記載されたポリシーは削除されます。「 * 次へ * 」を選択します。
+
手順 4 （ Remove ILM References ）が表示されます。


