---
permalink: maintain/stopping-services-and-shutting-down-grid-nodes.html 
sidebar: sidebar 
keywords: recover, stop services, shut down nodes, node shutdown 
summary: StorageGRID システムの電源をオフにするには、各グリッドノードで実行されているすべてのサービスを停止してから、すべての VMware 仮想マシン、コンテナエンジン、および StorageGRID アプライアンスをシャットダウンする必要があります。 
---
= サービスを停止し、グリッドノードをシャットダウンします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システムの電源をオフにするには、各グリッドノードで実行されているすべてのサービスを停止してから、すべての VMware 仮想マシン、コンテナエンジン、および StorageGRID アプライアンスをシャットダウンする必要があります。

.タスクの内容
最初に管理ノードとゲートウェイノードのサービスを停止してから、ストレージノードのサービスを停止します。

この方法なら、プライマリ管理ノードを使用して他のグリッドノードのステータスをできるだけ長く監視できます。


NOTE: 単一のホストに複数のグリッドノードが含まれている場合は、そのホスト上のすべてのノードを停止するまでホストをシャットダウンしないでください。ホストにプライマリ管理ノードが含まれている場合は、そのホストを最後にシャットダウンします。


NOTE: 必要に応じて、グリッドの機能や可用性に影響を与えることなくホストのメンテナンスを実行できますlink:linux-migrating-grid-node-to-new-host.html["Linux ホスト間でのノードの移行"]。

.手順
. すべてのクライアントアプリケーションからグリッドへのアクセスを停止します。
. [[log_in_on_gn] ][ 各ゲートウェイノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
.. ファイルに記載されているパスワードを入力し `Passwords.txt`ます。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. ファイルに記載されているパスワードを入力し `Passwords.txt`ます。
+
rootとしてログインすると、プロンプトがからに `#`変わります `$`。



. [[stop_all_services]]ノードで実行されているすべてのサービスを停止します。 `service servermanager stop`
+
サービスのシャットダウンには最大 15 分かかる場合があります。リモートからシステムにログインしてシャットダウンプロセスを監視することもできます。



. 前の2つの手順を繰り返して、すべてのストレージノードと非プライマリ管理ノードのサービスを停止します。
+
これらのノードのサービスは、どの順序で停止してもかまいません。

+

NOTE: コマンドを実行してアプライアンスストレージノードのサービスを停止する場合 `service servermanager stop`は、アプライアンスの電源を再投入してノードを再起動する必要があります。

. プライマリ管理ノードに対して、およびについての手順を繰り返します<<log_in_to_gn,ノードにログインします>><<stop_all_services,ノードのすべてのサービスを停止しています>>。
. Linux ホストで実行されているノードの場合：
+
.. ホストオペレーティングシステムにログインします。
.. ノードを停止します。 `storagegrid node stop`
.. ホストオペレーティングシステムをシャットダウンします。


. VMware仮想マシンで実行されているノードとアプライアンスストレージノードの場合は、shutdownコマンドを実行します。 `shutdown -h now`
+
この手順は、コマンドの結果に関係なく実行し `service servermanager stop`ます。

+
アプライアンスの場合、このコマンドはコンピューティングコントローラをシャットダウンしますが、アプライアンスの電源はオンになったままです。次の手順を実行する必要があります。

. アプライアンスノードがある場合：
+
** サービスアプライアンスまたはSGF6112アプライアンス
+
... アプライアンスの電源をオフにします。
... 青色の電源 LED が消灯するまで待ちます。


** SG6160アプライアンスの場合
+
... SG6100-CNストレージコントローラの電源をオフにします。
... SG6100-CNストレージコントローラの青色の電源LEDが消灯するまで待ちます。


** SG6000アプライアンスの場合
+
... ストレージコントローラの背面にある緑のキャッシュアクティブ LED が消灯するまで待ちます。
+
この LED は、キャッシュデータをドライブに書き込む必要があるときに点灯します。この LED が消灯するのを待ってから、電源をオフにする必要があります。

... アプライアンスの電源をオフにし、青色の電源 LED が消灯するまで待ちます。


** SG5800アプライアンスの場合
+
... ストレージコントローラの背面にある緑のキャッシュアクティブ LED が消灯するまで待ちます。
+
この LED は、キャッシュデータをドライブに書き込む必要があるときに点灯します。この LED が消灯するのを待ってから、電源をオフにする必要があります。

... SANtricity システムマネージャのホームページで、「 * 進行中の処理を表示」を選択します。
... すべての処理が完了したことを確認してから、次の手順に進みます。
... コントローラシェルフの両方の電源スイッチをオフにし、コントローラシェルフのすべてのLEDが消灯するまで待ちます。


** SG5700アプライアンスの場合
+
... ストレージコントローラの背面にある緑のキャッシュアクティブ LED が消灯するまで待ちます。
+
この LED は、キャッシュデータをドライブに書き込む必要があるときに点灯します。この LED が消灯するのを待ってから、電源をオフにする必要があります。

... アプライアンスの電源をオフにし、すべての LED とデジタル表示ディスプレイの動作が停止するまで待ちます。




. 必要に応じて、コマンドシェルからログアウトします。 `exit`
+
これで、 StorageGRID グリッドのシャットダウンは完了です。



.関連情報
* link:https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/index.html["SGF6112およびSG6160ストレージアプライアンス"^]
* link:https://docs.netapp.com/us-en/storagegrid-appliances/sg6000/index.html["SG6000ストレージアプライアンス"^]
* link:https://docs.netapp.com/us-en/storagegrid-appliances/sg5800/index.html["SG5800ストレージアプライアンス"^]
* link:https://docs.netapp.com/us-en/storagegrid-appliances/sg5700/index.html["SG5700ストレージアプライアンス"^]
* link:https://docs.netapp.com/us-en/storagegrid-appliances/sg110-1100/index.html["SG110およびSG1100サービスアプライアンス"^]
* link:https://docs.netapp.com/us-en/storagegrid-appliances/sg100-1000/index.html["SG100およびSG1000サービス アプライアンス"^]

