---
permalink: maintain/storagegrid-hotfix-procedure.html 
sidebar: sidebar 
keywords: apply hotfix, install hotfix, replace primary admin node 
summary: ソフトウェアの問題が検出され、次の機能リリースの前に解決された場合は、 StorageGRID システムへのホットフィックスの適用が必要になる場合があります。 
---
= StorageGRID ホットフィックス手順
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ソフトウェアの問題が検出され、次の機能リリースの前に解決された場合は、 StorageGRID システムへのホットフィックスの適用が必要になる場合があります。

StorageGRID のホットフィックスには、フィーチャーパックまたはフィーチャーパックに含まれないソフトウェアの変更が含まれます。今後のリリースにも同じ変更が含まれます。さらに、各ホットフィックスリリースには、その機能またはパッチリリースに含まれる以前のすべてのホットフィックスがまとめて含まれています。



== ホットフィックスの適用に関する考慮事項

別のメンテナンス手順 が実行されているときは、StorageGRID ホットフィックスを適用できません。たとえば、運用停止、拡張、またはリカバリ手順 の実行中はホットフィックスを適用できません。


NOTE: ノードまたはサイトの運用停止手順 が一時停止されている場合、ホットフィックスを安全に適用できます。また、 StorageGRID アップグレード手順 の最終段階でホットフィックスを適用できる場合があります。詳細については、 StorageGRID ソフトウェアのアップグレード手順を参照してください。

Grid Manager でホットフィックスをアップロードすると、ホットフィックスはプライマリ管理ノードに自動的に適用されます。その後、 StorageGRID システム内の残りのノードへのホットフィックスの適用を承認できます。

1 つ以上のノードへのホットフィックスの適用に失敗した場合は、ホットフィックスの進捗状況テーブルの Details 列に障害の理由が表示されます。エラーの原因となった問題を解決してから、プロセス全体を再試行する必要があります。ホットフィックスの適用に成功していたノードは、以降のアプリケーションではスキップされます。必要に応じて、すべてのノードが更新されるまで、ホットフィックスの適用を何度でも安全に再試行できます。アプリケーションを完了するには、すべてのグリッドノードにホットフィックスが正常にインストールされている必要があります。

新しいバージョンのホットフィックスによってグリッドノードが更新されますが、ホットフィックスの実際の変更内容が、特定のタイプのノードの特定のサービスにしか影響しない場合があります。たとえば、あるホットフィックスが、ストレージノード上の LDR サービスにしか影響しない場合があります。



== リカバリと拡張のためのホットフィックスの適用方法

ホットフィックスがグリッドに適用されると、プライマリ管理ノードは、リカバリ処理でリストアされたすべてのノード、または拡張時に追加されたすべてのノードに、同じバージョンのホットフィックスを自動的にインストールします。

ただし、プライマリ管理ノードのリカバリが必要な場合は、適切な StorageGRID リリースを手動でインストールしてからホットフィックスを適用する必要があります。プライマリ管理ノードの最終 StorageGRID バージョンがグリッド内の他のノードと同じである必要があります。

次の例は、プライマリ管理ノードをリカバリする際にホットフィックスを適用する方法を示しています。

. グリッドで StorageGRID 11._A.B_VERSION が実行されており、最新のホットフィックスが適用されているとします。「グリッドバージョン」は11._A.B.y_です。
. プライマリ管理ノードに障害が発生した場合。
. プライマリ管理ノードを StorageGRID 11._A.B__ を使用して再導入し、リカバリ手順 を実行します。
+

NOTE: グリッドのバージョンと一致する必要がある場合は、ノードの導入時にマイナーリリースを使用できます。メジャーリリースを先に導入する必要はありません。

. 次に、プライマリ管理ノードにホットフィックス 11._A.B.C._ を適用します。


詳細については、を参照してください link:configuring-replacement-primary-admin-node.html["交換用プライマリ管理ノードを設定"]。
