---
permalink: maintain/understanding-adc-service-quorum.html 
sidebar: sidebar 
keywords: storagegrid, recover, adc, adc quorum 
summary: 運用停止後に残るAdministrative Domain Controller（ADC\）サービスの数が少なすぎる場合は、サイトの特定のストレージノードの運用を停止できないことがあります。 
---
= ADCクォーラムとは何ですか。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
運用停止後に残るAdministrative Domain Controller（ADC；管理ドメインコントローラ）サービスが少なすぎる場合は、サイトの一部のストレージノードの運用を停止できないことがあります。

一部のストレージノードにあるADCサービスは、グリッドトポロジ情報を管理し、設定サービスをグリッドに提供します。StorageGRID システムでは、各サイトで ADC サービスのクォーラムが常に利用可能である必要があります。

ノードを削除すると原因 ADCクォーラムが満たされなくなる場合は、ストレージノードの運用を停止できません。運用停止中にADCクォーラムを満たすには、各サイトで少なくとも3つのストレージノードにADCサービスが必要です。ADCサービスを使用するストレージノードがサイトに3つ以上ある場合は、運用停止後もそれらのノードの過半数が利用可能な状態のままである必要があります。 `((0.5 * _Storage Nodes with ADC_) + 1)`


CAUTION: ソフトウェアベースのメタデータのみのノードを含むグリッド内のストレージノードの運用を停止する場合は注意が必要です。store_both_objectsとmetadataに設定されているすべてのノードの運用を停止すると、オブジェクトを格納する機能がグリッドから削除されます。メタデータ専用ストレージノードの詳細については、を参照してくださいlink:../primer/what-storage-node-is.html#types-of-storage-nodes["ストレージノードのタイプ"]。

たとえば、ADCサービスがあるストレージノードが6つあるサイトにあり、3つのストレージノードの運用を停止するとします。ADC クォーラムの要件により、次の 2 つの運用停止手順を実行する必要があります。

* 最初の運用停止手順では、ADCサービスを使用する4つのストレージノードを引き続き使用できるようにする必要があります。 `((0.5 * 6) + 1)`そのため、最初に運用停止できるのは、 2 つのストレージノードのみです。
* 2つ目の運用停止手順では、3つ目のストレージノードを削除できます。これは、ADCクォーラムに必要なADCサービスが3つしか残っていないためです。 `((0.5 * 4) + 1)`


ストレージノードの運用を停止する必要がある場合は、に新しいストレージノードを追加してADCサービスを配置するようlink:../expand/index.html["拡張"]に指定することで、ADCクォーラムの要件を引き続き満たすことができます。link:../upgrade/changes-to-grid-management-api.html#new-private-endpoints-for-move-adc["同じサイトの別のストレージノードへのADCサービスの移動"]その後、クォーラムに影響を与えることなく、既存のストレージノードの運用を停止できます。
