---
permalink: maintain/understanding-adc-service-quorum.html 
sidebar: sidebar 
keywords: storagegrid, recover, adc, adc quorum 
summary: ADCクォーラムは、各サイトで最低限の数の管理ドメインコントローラー（ADC）サービスが利用可能であることを保証します。StorageGRIDは、必要に応じて廃止措置時にADCサービスを自動的に移動します。 
---
= StorageGRID ADC定足数とは何ですか？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ADCクォーラムは、各サイトで最低限の数の管理ドメインコントローラー（ADC）サービスが利用可能であることを保証します。StorageGRIDは、必要に応じて廃止措置時にADCサービスを自動的に移動します。

一部のストレージノードにあるADCサービスは、グリッドトポロジ情報を管理し、設定サービスをグリッドに提供します。StorageGRID システムでは、各サイトで ADC サービスのクォーラムが常に利用可能である必要があります。

ノードを削除すると原因 ADCクォーラムが満たされなくなる場合は、ストレージノードの運用を停止できません。運用停止中にADCクォーラムを満たすには、各サイトで少なくとも3つのストレージノードにADCサービスが必要です。ADCサービスを使用するストレージノードがサイトに3つ以上ある場合は、運用停止後もそれらのノードの過半数が利用可能な状態のままである必要があります。 `((0.5 * _Storage Nodes with ADC_) + 1)`


CAUTION: ソフトウェアベースのメタデータのみのノードを含むグリッド内のストレージノードの運用を停止する場合は注意が必要です。store_both_objectsとmetadataに設定されているすべてのノードの運用を停止すると、オブジェクトを格納する機能がグリッドから削除されます。メタデータ専用ストレージノードの詳細については、を参照してくださいlink:../primer/what-storage-node-is.html#types-of-storage-nodes["ストレージノードのタイプ"]。

たとえば、ADCサービスがあるストレージノードが6つあるサイトにあり、3つのストレージノードの運用を停止するとします。ADC クォーラムの要件により、次の 2 つの運用停止手順を実行する必要があります。

* 最初の運用停止手順では、ADCサービスを使用する4つのストレージノードを引き続き使用できるようにする必要があります。 `((0.5 * 6) + 1)`そのため、最初に運用停止できるのは、 2 つのストレージノードのみです。
* 2 番目の廃止手順では、ADC クォーラムで使用可能な状態を保つために必要な ADC サービスが 3 つだけになったため、3 番目のストレージ ノードを削除できます。 `((0.5 * 4) + 1)` 。


ADCサービスを持つストレージノードを廃止する場合、廃止によってサイトのADC数がクォーラムを下回るときは、StorageGRIDはADCサービスを同じサイト内の別のストレージノードに自動的に移動します。自動移動を実行するには、グリッド内のすべてのノードが接続されていること、およびサービスを受信するために同じサイトにADC以外のストレージノードが利用可能であることが必要です。廃止手順では、サイトごとに最低3台のADCストレージノードを維持します。例えば、あるサイトで4つまたは6つのADCノードを廃止した場合、同じサイトに利用可能な非ADCノードが存在すると仮定すると、手順完了後には3つのADCストレージノードが残ります。

ADCサービスを自動的に移動できない場合は、link:move-adc-service.html["ADCサービスを手動で移動する"]同じサイト内の別のストレージノードへ移動するか、またはlink:../expand/index.html["拡張時に新しいストレージノードを追加する"]ADCサービスを備えるように指定することができます。そうすれば、クォーラムに影響を与えることなく、既存のストレージノードを廃止できます。
