---
permalink: primer/nodes-and-services.html 
sidebar: sidebar 
keywords: services, grid nodes, primary admin, storage, gateway 
summary: StorageGRID システムの基本的なビルディングブロックはグリッドノードです。ノードはサービスを備えています。サービスは、グリッドノードに一連の機能を提供するソフトウェアモジュールです。 
---
= グリッドノードおよびサービス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システムの基本的なビルディングブロックはグリッドノードです。ノードはサービスを備えています。サービスは、グリッドノードに一連の機能を提供するソフトウェアモジュールです。



== グリッドノードのタイプ

StorageGRID システムは、次の 4 種類のグリッドノードを使用します。

管理ノード:: システム構成、監視、ロギングなどの管理サービスを提供します。Grid Manager にサインインすると、管理ノードに接続されます。各グリッドにはプライマリ管理ノードが 1 つ必要であり、冗長性を確保するために非プライマリ管理ノードを追加で配置できます。どの管理ノードにも接続が可能で、各管理ノードに表示される StorageGRID システムのビューもほぼ同じです。ただし、メンテナンス手順はプライマリ管理ノードを使用して実行する必要があります。
+
--
管理ノードを使用して、S3クライアントトラフィックの負荷を分散することもできます。

を参照し link:what-admin-node-is.html["管理ノードとは"]

--
ストレージノード:: オブジェクトデータとメタデータを管理、格納StorageGRIDシステムの各サイトには、少なくとも3つのストレージノードが必要です。
+
--
を参照し link:what-storage-node-is.html["ストレージノードとは"]

--
ゲートウェイノード（オプション）:: クライアントアプリケーションがStorageGRIDへの接続に使用できるロードバランシングインターフェイスを提供します。ロードバランサによってクライアントが最適なストレージノードにシームレスに転送されるため、ノードやサイト全体の障害が透過的に処理されます。
+
--
を参照し link:what-gateway-node-is.html["ゲートウェイノードとは"]

--




== ハードウェアノードとソフトウェアノード

StorageGRIDノードは、StorageGRIDアプライアンスノードまたはソフトウェアベースのノードとして導入できます。



=== StorageGRID アプライアンスノード

StorageGRID ハードウェアアプライアンスは、 StorageGRID システム専用に設計されています。一部のアプライアンスはストレージノードとして使用できます。その他のアプライアンスは、管理ノードまたはゲートウェイノードとして使用できます。アプライアンスノードをソフトウェアベースのノードと組み合わせることができます。あるいは、外部のハイパーバイザー、ストレージ、コンピューティングハードウェアに依存しない、専用のアプライアンスのみで構成されたグリッドを導入することもできます。

使用可能なアプライアンスの詳細については、以下を参照してください。

* https://docs.netapp.com/us-en/storagegrid-appliances/["StorageGRIDアプライアンスのマニュアル"^]
* https://hwu.netapp.com["NetApp Hardware Universe"^]




=== ソフトウェアベースのノード

ソフトウェアベースのグリッドノードは、VMware仮想マシンとして導入することも、Linuxホスト上のコンテナエンジン内に導入することもできます。

* VMware vSphereの仮想マシン（VM）：を参照してください。link:../vmware/index.html["VMwareへのStorageGRIDのインストール"]
* Red Hat Enterprise Linux上のコンテナエンジン内：を参照してください。link:../rhel/index.html["Red Hat Enterprise LinuxへのStorageGRIDのインストール"]
* UbuntuまたはDebianのコンテナエンジン内：を参照してください。link:../ubuntu/index.html["UbuntuまたはDebianへのStorageGRIDのインストール"]


を使用して、 https://imt.netapp.com/matrix/#welcome["NetApp Interoperability Matrix Tool（IMT）"^]サポートされているバージョンを確認します。

新しいソフトウェアベースのストレージノードの初回インストール時に、そのノードのみを使用するように指定できますlink:../primer/what-storage-node-is.html#types-of-storage-nodes["メタデータの保存"]。



== StorageGRID サービス

StorageGRID サービスの一覧を以下に示します。

[cols="2a,3a,2a"]
|===
| サービス | 製品説明 | 場所 


 a| 
アカウントサービスフォワーダ
 a| 
ロードバランササービスがリモートホスト上のアカウントサービスを照会するためのインターフェイスを提供し、ロードバランサエンドポイントの設定変更をロードバランササービスに通知します。
 a| 
管理ノードおよびゲートウェイノード上のロードバランササービス



 a| 
ADC（Administrative Domain Controller）
 a| 
トポロジ情報を管理し、認証サービスを提供するとともに、 LDR サービスおよび CMN サービスから送られるクエリに応答します。
 a| 
各サイトにADCサービスを含むストレージノードが少なくとも3つ



 a| 
AMS（監査管理システム）
 a| 
監査対象のすべてのシステムイベントとトランザクションを監視し、テキストログファイルに記録します。
 a| 
管理ノード



 a| 
Apache Tomcat
 a| 
Javaベースのアプリケーション用のWebサーバー。
 a| 
管理ノード



 a| 
アバヒデーモン
 a| 
ローカルネットワーク内で名前解決とサービス検出に使用されるmDNSを処理します。
 a| 
すべてのノード



 a| 
キャッシュサービス
 a| 
ロードバランサ（ゲートウェイ）ノードで実行され、オブジェクトコンテンツのローカルキャッシュを管理します。
 a| 
ゲートウェイノード



 a| 
Cassandra
 a| 
オブジェクトメタデータ用の分散データベースを管理します。
 a| 
ストレージノード（データ専用を除く）



 a| 
Cassandra Reaper
 a| 
オブジェクトメタデータの自動修復を実行します。
 a| 
ストレージノード



 a| 
チャンクサービス
 a| 
イレイジャーコーディングされたデータフラグメントとパリティフラグメントを管理します。
 a| 
ストレージノード



 a| 
CMN（Configuration Management Node）
 a| 
システム全体の設定とグリッドタスクを管理します。各グリッドには1つのCMNサービスがあります。
 a| 
プライマリ管理ノード



 a| 
DDS（Distributed Data Store）
 a| 
Cassandra データベースとのインターフェイスを提供してオブジェクトメタデータを管理します。
 a| 
ストレージノード



 a| 
DMV（Data Mover）
 a| 
データをクラウドエンドポイントに移動します。
 a| 
ストレージノード



 a| 
動的IP（dynip）
 a| 
IP の動的な変更がないかグリッドを監視し、ローカル設定を更新します。
 a| 
すべてのノード



 a| 
グラファーナ
 a| 
Grid Manager に表示される指標に使用されます。
 a| 
管理ノード



 a| 
高可用性
 a| 
[High Availability Groups]ページで設定されたノードのハイアベイラビリティ仮想IPを管理します。このサービスはキープアライブサービスとも呼ばれます。
 a| 
管理ノードとゲートウェイノード



 a| 
ID （ idnt ）
 a| 
ローカルユーザとローカルグループの管理、認証の管理、LDAPおよびActive DirectoryからのユーザIDのフェデレーションを行います。
 a| 
ADCサービスを使用するストレージノード



 a| 
ラムダ・アービトレーター
 a| 
S3 Select SelectObjectContent 要求を管理します。
 a| 
すべてのノード



 a| 
ロードバランサ（nginx-gw）
 a| 
クライアントからストレージノードへのS3トラフィックのロードバランシングを提供します。ロードバランサエンドポイントの設定ページで設定できます。このサービスは nginx-gw サービスとも呼ばれます。
 a| 
管理ノードとゲートウェイノード



 a| 
LDR（Local Distribution Router）
 a| 
グリッド内のコンテンツの格納と転送を管理します。
 a| 
ストレージノード



 a| 
MISCd Information Service Controlデーモン
 a| 
他のノード上のサービスの照会と管理、およびノードの環境設定の管理（他のノードで実行されているサービスの状態の照会など）を行うためのインターフェイスを提供します。
 a| 
すべてのノード



 a| 
nginx
 a| 
は、各種のグリッドサービス（ Prometheus や動的 IP など）が HTTPS API を介して他のノード上のサービスと通信できるようにするための、認証およびセキュアな通信のメカニズムとして機能します。
 a| 
すべてのノード



 a| 
nginx-gwロードバランサ
 a| 
クライアントからストレージノードへのS3トラフィックのロードバランシングを提供します。ロードバランサエンドポイントの設定ページで設定できます。このサービスは nginx-gw サービスとも呼ばれます。
 a| 
管理ノードとゲートウェイノード



 a| 
NMS（ネットワーク管理システム）
 a| 
Grid Manager を介して表示される監視、レポート、および設定のオプションを強化します。
 a| 
管理ノード



 a| 
Node Exporter（Prometheusデータ収集）
 a| 
Prometheus時系列の指標収集のシステムレベルの統計を公開します。
 a| 
すべてのノード



 a| 
NTP
 a| 
Network Time Protocol（NTP；ネットワークタイムプロトコル）サービス。
 a| 
すべてのノード



 a| 
永続性
 a| 
リブート後も維持する必要があるルートディスク上のファイルを管理します。
 a| 
すべてのノード



 a| 
Prometheus
 a| 
すべてのノードのサービスから時系列の指標を収集します。
 a| 
管理ノード



 a| 
RSM（Replicated State Machine）
 a| 
プラットフォームサービス要求がそれぞれのエンドポイントに送信されるようにします。
 a| 
ADCサービスを使用するストレージノード



 a| 
SSM（Server Status Monitor）
 a| 
ハードウェアの状態を監視して NMS サービスに報告します。
 a| 
インスタンスがすべてのグリッドノードに存在する



 a| 
サーバーマネージャ
 a| 
StorageGRIDサービスを管理します。
 a| 
すべてのノード



 a| 
SNMPエージェント
 a| 
SNMP要求に応答します。
 a| 
管理ノード



 a| 
SNMPポート管理サービス
 a| 
SNMPポートの動的管理を処理します。
 a| 
すべてのノード



 a| 
Secure Shell（SSH；セキュアシェル）
 a| 
セキュアなアクセスとリモートシステム管理を処理します。
 a| 
すべてのノード



 a| 
SSM（システムステータスモニタ）
 a| 
ハードウェアの状態を監視して NMS サービスに報告します。
 a| 
すべてのノード



 a| 
統計
 a| 
S3バケットに関連するその他の指標を記録します。
 a| 
ストレージノード



 a| 
トレースエージェント（Jaeger-agent）
 a| 
トレースコレクタ（Jaeger-collector）によって送信されたトレース情報を受信して処理します。
 a| 
すべてのノード



 a| 
トレースコレクタ（Jaeger-collector）
 a| 
トレース収集を実行し、テクニカルサポートが使用する情報を収集します。トレースコレクタサービスは、オープンソースのJaegerソフトウェアを使用しています。
 a| 
管理ノード

|===