---
permalink: primer/nodes-and-services.html 
sidebar: sidebar 
keywords: services, grid nodes, primary admin, storage, gateway 
summary: StorageGRID システムの基本的なビルディングブロックはグリッドノードです。ノードはサービスを備えています。サービスは、グリッドノードに一連の機能を提供するソフトウェアモジュールです。 
---
= グリッドノードおよびサービス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システムの基本的なビルディングブロックはグリッドノードです。ノードはサービスを備えています。サービスは、グリッドノードに一連の機能を提供するソフトウェアモジュールです。



== グリッドノードのタイプ

StorageGRIDシステムは、次の 3 種類のグリッド ノードを使用します。

管理ノード:: システム構成、監視、ロギングなどの管理サービスを提供します。Grid Manager にサインインすると、管理ノードに接続されます。各グリッドにはプライマリ管理ノードが 1 つ必要であり、冗長性を確保するために非プライマリ管理ノードを追加で配置できます。どの管理ノードにも接続が可能で、各管理ノードに表示される StorageGRID システムのビューもほぼ同じです。ただし、メンテナンス手順はプライマリ管理ノードを使用して実行する必要があります。
+
--
管理ノードを使用して、S3クライアントトラフィックの負荷を分散することもできます。

を参照し link:what-admin-node-is.html["管理ノードとは"]

--
ストレージノード:: オブジェクトデータとメタデータを管理、格納StorageGRIDシステムの各サイトには、少なくとも3つのストレージノードが必要です。
+
--
新しいストレージノードの初期インストール時に、次の目的にのみ使用するように指定できます。link:../primer/what-storage-node-is.html#types-of-storage-nodes["メタデータの保存"] 。

を参照し link:what-storage-node-is.html["ストレージノードとは"]

--
ゲートウェイノード（オプション）:: クライアントアプリケーションがStorageGRIDへの接続に使用できるロードバランシングインターフェイスを提供します。ロードバランサによってクライアントが最適なストレージノードにシームレスに転送されるため、ノードやサイト全体の障害が透過的に処理されます。
+
--
を参照し link:what-gateway-node-is.html["ゲートウェイノードとは"]

--




== ハードウェアノードとソフトウェアノード

StorageGRIDノードは、 StorageGRIDアプライアンス ノードまたはソフトウェア ベースのノードとして展開できます。システムあたりのノードの最大数 (すべてのノード タイプを含む) は 220 です。



=== StorageGRID アプライアンスノード

StorageGRID ハードウェアアプライアンスは、 StorageGRID システム専用に設計されています。一部のアプライアンスはストレージノードとして使用できます。その他のアプライアンスは、管理ノードまたはゲートウェイノードとして使用できます。アプライアンスノードをソフトウェアベースのノードと組み合わせることができます。あるいは、外部のハイパーバイザー、ストレージ、コンピューティングハードウェアに依存しない、専用のアプライアンスのみで構成されたグリッドを導入することもできます。

使用可能なアプライアンスの詳細については、以下を参照してください。

* https://docs.netapp.com/us-en/storagegrid-appliances/["StorageGRIDアプライアンスのマニュアル"^]
* https://hwu.netapp.com["NetApp Hardware Universe"^]




=== ソフトウェアベースのノード

ソフトウェア ベースのグリッド ノードは、VMware 仮想マシンとして、または Linux ホスト上のコンテナー エンジン内に展開できます。見るlink:../swnodes/index.html["ソフトウェアベースのノードにStorageGRIDをインストールする"] 。

を使用して、 https://imt.netapp.com/matrix/#welcome["NetApp Interoperability Matrix Tool（IMT）"^]サポートされているバージョンを確認します。



== StorageGRID サービス

StorageGRID サービスの一覧を以下に示します。

[cols="2a,3a,2a"]
|===
| サービス | 製品説明 | 場所 


 a| 
アカウントサービスフォワーダ
 a| 
ロードバランササービスがリモートホスト上のアカウントサービスを照会するためのインターフェイスを提供し、ロードバランサエンドポイントの設定変更をロードバランササービスに通知します。
 a| 
管理ノードおよびゲートウェイノード上のロードバランササービス



 a| 
ADC（Administrative Domain Controller）
 a| 
トポロジ情報を管理し、認証サービスを提供するとともに、 LDR サービスおよび CMN サービスから送られるクエリに応答します。
 a| 
各サイトにADCサービスを含むストレージノードが少なくとも3つ



 a| 
AMS（監査管理システム）
 a| 
監査対象のすべてのシステムイベントとトランザクションを監視し、テキストログファイルに記録します。
 a| 
管理ノード



 a| 
Apache Tomcat
 a| 
Java ベースのアプリケーション用の Web サーバー。
 a| 
管理ノード



 a| 
アヴァヒ・デーモン
 a| 
ローカル ネットワーク内の名前解決とサービス検出に使用される mDNS を処理します。
 a| 
すべてのノード



 a| 
キャッシュサービス
 a| 
ロード バランサー (ゲートウェイ) ノード上で実行され、オブジェクト コンテンツのローカル キャッシュを管理します。
 a| 
ゲートウェイノード



 a| 
Cassandra
 a| 
オブジェクト メタデータの分散データベースを管理します。
 a| 
ストレージノード（データ専用を除く）



 a| 
Cassandra Reaper
 a| 
オブジェクトメタデータの自動修復を実行します。
 a| 
ストレージノード



 a| 
チャンクサービス
 a| 
イレイジャーコーディングされたデータフラグメントとパリティフラグメントを管理します。
 a| 
ストレージノード



 a| 
CMN（Configuration Management Node）
 a| 
システム全体の設定とグリッドタスクを管理します。各グリッドには1つのCMNサービスがあります。
 a| 
プライマリ管理ノード



 a| 
DDS（Distributed Data Store）
 a| 
Cassandra データベースとのインターフェイスを提供してオブジェクトメタデータを管理します。
 a| 
ストレージノード



 a| 
DMV（Data Mover）
 a| 
データをクラウドエンドポイントに移動します。
 a| 
ストレージノード



 a| 
動的IP（dynip）
 a| 
IP の動的な変更がないかグリッドを監視し、ローカル設定を更新します。
 a| 
すべてのノード



 a| 
グラファーナ
 a| 
Grid Manager に表示される指標に使用されます。
 a| 
管理ノード



 a| 
高可用性
 a| 
[High Availability Groups]ページで設定されたノードのハイアベイラビリティ仮想IPを管理します。このサービスはキープアライブサービスとも呼ばれます。
 a| 
管理ノードとゲートウェイノード



 a| 
ID （ idnt ）
 a| 
ローカル ユーザーとグループ、認証を管理し、LDAP および Active Directory からのユーザー ID を統合します。
 a| 
ADCサービスを使用するストレージノード



 a| 
ラムダ・アービトレーター
 a| 
S3 Select SelectObjectContent 要求を管理します。
 a| 
すべてのノード



 a| 
ロードバランサ（nginx-gw）
 a| 
クライアントからストレージノードへのS3トラフィックのロードバランシングを提供します。ロードバランサエンドポイントの設定ページで設定できます。このサービスは nginx-gw サービスとも呼ばれます。
 a| 
管理ノードとゲートウェイノード



 a| 
LDR（Local Distribution Router）
 a| 
グリッド内のコンテンツの格納と転送を管理します。
 a| 
ストレージノード



 a| 
MISCd Information Service Controlデーモン
 a| 
他のノード上のサービスの照会と管理、およびノードの環境設定の管理（他のノードで実行されているサービスの状態の照会など）を行うためのインターフェイスを提供します。
 a| 
すべてのノード



 a| 
nginx
 a| 
は、各種のグリッドサービス（ Prometheus や動的 IP など）が HTTPS API を介して他のノード上のサービスと通信できるようにするための、認証およびセキュアな通信のメカニズムとして機能します。
 a| 
すべてのノード



 a| 
nginx-gw ロードバランサー
 a| 
クライアントからストレージノードへのS3トラフィックのロードバランシングを提供します。ロードバランサエンドポイントの設定ページで設定できます。このサービスは nginx-gw サービスとも呼ばれます。
 a| 
管理ノードとゲートウェイノード



 a| 
NMS（ネットワーク管理システム）
 a| 
Grid Manager を介して表示される監視、レポート、および設定のオプションを強化します。
 a| 
管理ノード



 a| 
ノードエクスポーター（Prometheusデータ収集）
 a| 
Prometheus 時系列メトリック収集のシステムレベルの統計を公開します。
 a| 
すべてのノード



 a| 
NTP
 a| 
ネットワーク タイム プロトコル (NTP) サービス。
 a| 
すべてのノード



 a| 
永続性
 a| 
リブート後も維持する必要があるルートディスク上のファイルを管理します。
 a| 
すべてのノード



 a| 
Prometheus
 a| 
すべてのノードのサービスから時系列の指標を収集します。
 a| 
管理ノード



 a| 
RSM（Replicated State Machine）
 a| 
プラットフォームサービス要求がそれぞれのエンドポイントに送信されるようにします。
 a| 
ADCサービスを使用するストレージノード



 a| 
SSM（Server Status Monitor）
 a| 
ハードウェアの状態を監視して NMS サービスに報告します。
 a| 
インスタンスがすべてのグリッドノードに存在する



 a| 
サーバーマネージャー
 a| 
StorageGRIDサービスを管理します。
 a| 
すべてのノード



 a| 
SNMPエージェント
 a| 
SNMP 要求に応答します。
 a| 
管理ノード



 a| 
SNMP ポート管理サービス
 a| 
SNMP ポートの動的管理を処理します。
 a| 
すべてのノード



 a| 
SSH（セキュアシェル）
 a| 
安全なアクセスとリモート システム管理を処理します。
 a| 
すべてのノード



 a| 
SSM (システム ステータス モニター)
 a| 
ハードウェアの状態を監視して NMS サービスに報告します。
 a| 
すべてのノード



 a| 
統計
 a| 
S3 バケットに関連する追加のメトリクスを記録します。
 a| 
ストレージノード



 a| 
トレースエージェント（jaeger-agent）
 a| 
トレース コレクター (jaeger-collector) によって送信されたトレース情報を受信して処理します。
 a| 
すべてのノード



 a| 
トレースコレクター (jaeger-collector)
 a| 
トレース収集を実行し、テクニカルサポートが使用する情報を収集します。トレースコレクタサービスは、オープンソースのJaegerソフトウェアを使用しています。
 a| 
管理ノード

|===