---
permalink: primer/what-gateway-node-is.html 
sidebar: sidebar 
keywords: gateway nodes, api gateway 
summary: ゲートウェイノードは、S3クライアントアプリケーションがStorageGRIDへの接続に使用できる専用のロードバランシングインターフェイスを提供します。ロードバランシングは、複数のストレージノードにワークロードを分散することで、速度と接続容量を最大化します。ゲートウェイノードはオプションです。 
---
= ゲートウェイノードとは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ゲートウェイノードは、S3クライアントアプリケーションがStorageGRIDへの接続に使用できる専用のロードバランシングインターフェイスを提供します。ロードバランシングは、複数のストレージノードにワークロードを分散することで、速度と接続容量を最大化します。ゲートウェイノードはオプションです。

StorageGRIDロードバランササービスは、すべての管理ノードとすべてのゲートウェイノードに提供されます。クライアント要求の Transport Layer Security （ TLS ）終了を実行し、要求を検査し、ストレージノードへの新しいセキュアな接続を確立します。ロードバランササービスは、クライアントを最適なストレージノードにシームレスに転送するため、ノードやサイト全体の障害が透過的に発生します。

1つ以上のロードバランサエンドポイントを設定して、ゲートウェイノードおよび管理ノード上のロードバランササービスへのアクセスに送受信クライアント要求が使用するポートとネットワークプロトコル（HTTPSまたはHTTP）を定義します。ロードバランサエンドポイントでは、クライアントタイプ（S3）、バインドモード、および必要に応じて許可またはブロックされたテナントのリストも定義されます。を参照して link:../admin/managing-load-balancing.html["ロードバランシングに関する考慮事項"]

必要に応じて、複数のゲートウェイノードと管理ノードのネットワークインターフェイスをハイアベイラビリティ（HA）グループにグループ化できます。HAグループのアクティブインターフェイスで障害が発生した場合は、バックアップインターフェイスでクライアントアプリケーションのワークロードを管理できます。を参照して link:../admin/managing-high-availability-groups.html["ハイアベイラビリティ（HA）グループを管理します"]



== ゲートウェイノードのプライマリサービス

次の表に、ゲートウェイノードのプライマリサービスを示します。ただし、この表にはすべてのノードサービスが表示されるわけではありません。

[cols="1a,2a"]
|===
| サービス | キー機能 


 a| 
高可用性
 a| 
管理ノードとゲートウェイノードのグループのハイアベイラビリティ仮想 IP アドレスを管理します。

* 注： * このサービスは管理ノードにも搭載されています。



 a| 
ロードバランサ
 a| 
クライアントからストレージノードへのS3トラフィックのレイヤ7のロードバランシングを提供します。これは推奨されるロードバランシングメカニズムです。

* 注： * このサービスは管理ノードにも搭載されています。



 a| 
SSM （サーバステータスモニタ）
 a| 
オペレーティングシステムと基盤のハードウェアを監視します。

|===