---
permalink: primer/what-admin-node-is.html 
sidebar: sidebar 
keywords: admin nodes 
summary: 管理ノードは、システムの設定、監視、ロギングなどの管理サービスを提供します。管理ノードを使用して、S3クライアントトラフィックの負荷を分散することもできます。各グリッドにはプライマリ管理ノードが 1 つ必要で、冗長性を確保するために任意の数の非プライマリ管理ノードを設定できます。 
---
= 管理ノードとは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理ノードは、システムの設定、監視、ロギングなどの管理サービスを提供します。管理ノードを使用して、S3クライアントトラフィックの負荷を分散することもできます。各グリッドにはプライマリ管理ノードが 1 つ必要で、冗長性を確保するために任意の数の非プライマリ管理ノードを設定できます。



== プライマリ管理ノードと非プライマリ管理ノードの違い

Grid Manager または Tenant Manager にサインインすると、管理ノードに接続されます。どの管理ノードにも接続が可能で、各管理ノードに表示される StorageGRID システムのビューもほぼ同じです。ただし、プライマリ管理ノードは非プライマリ管理ノードよりも多くの機能を提供します。たとえば、ほとんどのメンテナンス手順はプライマリ管理ノードから実行する必要があります。

次の表は、プライマリ管理ノードと非プライマリ管理ノードの機能をまとめたものです。

[cols="2a,1a,1a"]
|===
| 機能 | プライマリ管理ノード | 非プライマリ管理ノード 


 a| 
サービスを含む<<ams,AMS>>
 a| 
はい
 a| 
はい



 a| 
サービスを含む<<cmn,CMN>>
 a| 
はい
 a| 
いいえ



 a| 
サービスを含む<<nms,NMS>>
 a| 
はい
 a| 
はい



 a| 
サービスを含む<<prometheus,Prometheus>>
 a| 
はい
 a| 
はい



 a| 
サービスを含む<<ssm,SSM>>
 a| 
はい
 a| 
はい



 a| 
サービスと<<high-availability,高可用性>>サービスが含まれます。<<load-balancer,ロードバランサ>>
 a| 
はい
 a| 
はい



 a| 
（mgmt-api）をサポートします。<<mgmt-api,管理アプリケーションプログラムインターフェイス>>
 a| 
はい
 a| 
はい



 a| 
IPアドレスの変更やNTPサーバの更新など、ネットワーク関連のすべてのメンテナンスタスクに使用できる
 a| 
はい
 a| 
いいえ



 a| 
ストレージノードの拡張後にECのリバランシングを実行可能
 a| 
はい
 a| 
いいえ



 a| 
ボリュームのリストア手順に使用できます。
 a| 
はい
 a| 
はい



 a| 
1つ以上のノードからログファイルとシステムデータを収集可能
 a| 
はい
 a| 
いいえ



 a| 
アラート通知、AutoSupportパッケージ、SNMPトラップと通知を送信
 a| 
はい。として機能し<<preferred-sender,優先送信者>>ます。
 a| 
はい。スタンバイ送信者として機能します。

|===


== [[preferred-sender]]優先送信者管理ノード

StorageGRID環境に複数の管理ノードが含まれている場合は、プライマリ管理ノードがアラート通知、AutoSupportパッケージ、SNMPトラップおよびインフォームの優先送信者となります。

通常のシステム運用では、優先送信者のみが通知を送信します。ただし、他のすべての管理ノードで優先送信者を監視します。問題が検出された場合、他の管理ノードは_standby senders_として動作します。

次の場合、複数の通知が送信されることがあります。

* 管理ノードどうしが「孤立」すると、優先送信者とスタンバイ送信者の両方が通知の送信を試み、通知のコピーが複数受信される可能性があります。
* スタンバイ送信者が優先送信者に関する問題を検出して通知の送信を開始すると、優先送信者は通知を再び送信できるようになることがあります。この場合、重複する通知が送信される可能性があります。優先送信者に関するエラーが検出されなくなると、スタンバイ送信者は通知の送信を停止します。
+

NOTE: AutoSupportパッケージのテスト時には、すべての管理ノードからテストが送信されます。アラート通知をテストするときは、すべての管理ノードにサインインして接続を確認する必要があります。





== 管理ノードのプライマリサービス

次の表に、管理ノードのプライマリサービスを示します。ただし、この表にはすべてのノードサービスが表示されるわけではありません。

[cols="1a,2a"]
|===
| サービス | キー機能 


 a| 
[[AMS]]監査管理システム（AMS）
 a| 
システムアクティビティとイベントを追跡します。



 a| 
[[CMN]]構成管理ノード（CMN）
 a| 
システム全体の設定を管理します。



 a| 
[[high-availability]]ハイアベイラビリティ
 a| 
管理ノードとゲートウェイノードのグループのハイアベイラビリティ仮想 IP アドレスを管理します。

* 注： * このサービスはゲートウェイノードにも搭載されています。



 a| 
[[load-balancer]]ロードバランサ
 a| 
クライアントからストレージノードへのS3トラフィックのロードバランシングを提供します。

* 注： * このサービスはゲートウェイノードにも搭載されています。



 a| 
[[mgmt-api]]管理アプリケーションプログラムインターフェイス（mgmt-api）
 a| 
グリッド管理 API とテナント管理 API からの要求を処理します。



 a| 
[[NMS]]ネットワーク管理システム（NMS）
 a| 
Grid Manager の機能を提供します。



 a| 
[[Prometheus]] Prometheus
 a| 
すべてのノードのサービスから時系列の指標を収集して格納します。



 a| 
[[SSM]]サーバステータスモニタ（SSM）
 a| 
オペレーティングシステムと基盤のハードウェアを監視します。

|===