---
permalink: primer/what-storage-node-is.html 
sidebar: sidebar 
keywords: what is a storage node, how many storage nodes 
summary: ストレージノードは、オブジェクトデータとメタデータを管理および格納します。ストレージノードには、ディスク上のオブジェクトデータとメタデータを格納、移動、検証、読み出すために必要なサービスとプロセスが含まれています。 
---
= ストレージノードとは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージノードは、オブジェクトデータとメタデータを管理および格納します。ストレージノードには、ディスク上のオブジェクトデータとメタデータを格納、移動、検証、読み出すために必要なサービスとプロセスが含まれています。

StorageGRIDシステムの各サイトには、少なくとも3つのストレージノードが必要です。



== ストレージノードのタイプ

インストール時に、インストールするストレージノードのタイプを選択できます。これらのタイプは、ソフトウェアベースのストレージノードおよびこの機能をサポートするアプライアンスベースのストレージノードで使用できます。

* データとメタデータを統合したストレージノード
* メタデータのみのストレージノード
* データ専用ストレージノード


ストレージノードタイプは次の状況で選択できます。

* ストレージノードの初回インストール時
* StorageGRIDシステムの拡張時にストレージノードを追加した場合



NOTE: ストレージノードのインストールが完了したあとにタイプを変更することはできません。

データとメタデータのストレージノード（組み合わせ）:: デフォルトでは、すべての新しいストレージノードにオブジェクトデータとメタデータの両方が格納されます。このタイプのストレージノードは_combined_storage Nodeと呼ばれます。
メタデータのみのストレージノード:: グリッドに非常に多数の小さなオブジェクトが格納されている場合は、メタデータ専用のストレージノードを使用すると効果的です。専用のメタデータ容量をインストールすると、非常に多数の小さなオブジェクトに必要なスペースと、それらのオブジェクトのメタデータに必要なスペースのバランスが向上します。また、メタデータのみのストレージノードをハイパフォーマンスアプライアンスでホストすることで、パフォーマンスを向上させることができます。


メタデータ専用ノードをインストールする場合は、グリッドにデータストレージ用のノードも最小限必要です。

* 単一サイトのグリッドの場合は、組み合わせたストレージノードまたはデータ専用ストレージノードを少なくとも2つ設定します。
* マルチサイトグリッドの場合は、少なくとも1つの組み合わせたストレージノードまたはデータ専用ストレージノードをサイトごとに設定します。



NOTE: メタデータのみのストレージノードにはが含まれており<<ldr-service,LDRサアヒス>>、S3クライアント要求を処理できますが、StorageGRIDのパフォーマンスが向上しない場合があります。

データ専用ストレージノード:: ストレージノードのパフォーマンス特性が異なる場合は、データ専用のストレージノードを使用するのが理にかなっています。たとえば、パフォーマンスを潜在的に向上させるために、データ専用で大容量の回転式ディスクストレージノードと、メタデータ専用のハイパフォーマンスストレージノードを組み合わせることができます。


データ専用ノードをインストールする場合は、グリッドに次のものが含まれている必要があります。

* グリッドあたり最低2つの統合ストレージノードまたはデータ専用ストレージノード_
* サイトごとに少なくとも1つの統合ストレージノードまたはデータ専用ストレージノード_
* サイトごとに最低3つの統合ストレージノードまたはメタデータのみのストレージノード_




== ストレージノードのプライマリサービス

次の表は、ストレージノードのプライマリサービスを示しています。ただし、この表にはすべてのノードサービスが含まれているわけではありません。


NOTE: ADC サービスや RSM サービスのように、通常は各サイトの 3 つのストレージノードにしか存在しないサービスもあります。

[cols="1a,3a"]
|===
| サービス | キー機能 


 a| 
アカウント（ acct ）
 a| 
テナントアカウントを管理します。



 a| 
Administrative Domain Controller （ ADC ；管理ドメインコントローラ）
 a| 
トポロジとグリッド全体の構成を管理します。

*注*：データ専用ストレージノードはADCサービスをホストしません。

.詳細
[%collapsible]
====
Administrative Domain Controller （ ADC ）サービスは、グリッドノードとその相互接続を認証します。ADCサービスは、サイトにある少なくとも3つのストレージノードでホストされます。

ADC サービスは、サービスの場所や可用性などのトポロジ情報を管理します。あるグリッドノードが別のグリッドノードからの情報を必要とする場合や、別のグリッドノードによる処理を必要とする場合、そのグリッドノードは ADC サービスにアクセスして要求に最適なグリッドノードを見つけます。また、ADCサービスはStorageGRID環境の設定バンドルのコピーを保持し、すべてのグリッドノードが現在の設定情報を取得できるようにします。

分散された処理および孤立した処理に対応するため、各 ADC サービスは、証明書、設定バンドル、およびサービスやトポロジに関する情報を、 StorageGRID システム内の他の ADC サービスと同期します。

一般に、すべてのグリッドノードは少なくとも 1 つの ADC サービスへの接続を維持し、これにより、グリッドノードは常に最新情報にアクセスします。グリッドノードに接続すると、他のグリッドノードの証明書がキャッシュされるため、ADCサービスを使用できない場合でも既知のグリッドノードで引き続き機能できます。新しいグリッドノードが接続を確立するためには、 ADC サービスを使用する必要があります。

ADC サービスは接続された各グリッドノードからトポロジ情報を収集します。このグリッドノード情報には、 CPU 負荷、使用可能なディスクスペース（ストレージがある場合）、サポートされているサービス、およびグリッドノードのサイト ID が含まれます。その他のサービスは、トポロジクエリを介して ADC サービスにトポロジ情報を要求します。ADC サービスは、 StorageGRID システムから受信した最新情報で各クエリに応答します。

====


 a| 
Cassandra
 a| 
オブジェクトメタデータを格納し、保護します。

*注*：データ専用ストレージノードはCassandraサービスをホストしません。



 a| 
Cassandra Reaper
 a| 
オブジェクトメタデータの自動修復を実行します。

*注*：データ専用ストレージノードはCassandra Reaperサービスをホストしません。



 a| 
チャンク
 a| 
イレイジャーコーディングされたデータフラグメントとパリティフラグメントを管理します。



 a| 
Data Mover （ DMV ）
 a| 
クラウドストレージプールにデータを移動します。



 a| 
Distributed Data Store （ DDS ）
 a| 
オブジェクトメタデータストレージを監視します。

.詳細
[%collapsible]
====
各ストレージノードにはDistributed Data Store（DDS）サービスが含まれています。このサービスは、Cassandraデータベースと連携して、StorageGRIDシステムに格納されているオブジェクトメタデータに対してバックグラウンドタスクを実行します。

DDSサービスは、StorageGRIDシステムに取り込まれたオブジェクトの合計数と、システムでサポートされている各インターフェイス（S3）を使用して取り込まれたオブジェクトの合計数を追跡します。

====


 a| 
ID （ idnt ）
 a| 
LDAP および Active Directory から取得したユーザ ID を統合する



 a| 
[LDR-SERVICE]Local Distribution Router（LDR）
 a| 
オブジェクトストレージプロトコル要求を処理し、ディスク上のオブジェクトデータを管理します。

.詳細
[%collapsible]
====
各_combined_、_data-only_、および_metadata-only_Storage Nodeには、Local Distribution Router（LDR；ローカル分散ルータ）サービスが含まれています。このサービスは、データストレージ、ルーティング、要求処理などのコンテンツ転送機能を処理します。LDRサービスは、データ転送の負荷とデータトラフィック機能を処理することで、StorageGRID システムのハードワークのほとんどを実行します。

LDR サービスは次のタスクを処理します。

* クエリ
* 情報ライフサイクル管理（ ILM ）のアクティビティ
* オブジェクトの削除
* オブジェクトデータのストレージ
* 別の LDR サービス（ストレージノード）からのオブジェクトデータの転送
* データストレージ管理
* S3プロトコルインターフェイス


また、LDRサービスは各S3オブジェクトを一意のUUIDにマッピングします。

オブジェクトストア:: LDR サービスの基盤となるデータストレージは、一定数のオブジェクトストア（ストレージボリュームとも呼ばれます）に分割されます。各オブジェクトストアは個別のマウントポイントです。
+
--
ストレージノード内のオブジェクトストアは、ボリューム ID と呼ばれる 0000 ~ 002F の 16 進数で識別されます。最初のオブジェクトストア（ボリューム 0 ）では、 Cassandra データベースのオブジェクトメタデータ用にスペースがリザーブされます。このボリュームの残りのスペースはオブジェクトデータに使用されます。他のすべてのオブジェクトストアはオブジェクトデータ専用です。オブジェクトデータにはレプリケートコピーとイレイジャーコーディングフラグメントがあります。

レプリケートコピーのスペース使用量を均等にするために、特定のオブジェクトのオブジェクトデータは、使用可能なストレージスペースに基づいて 1 つのオブジェクトストアに格納されます。オブジェクトストアの容量がいっぱいになると、ストレージノード上のスペースがなくなるまで、残りのオブジェクトストアに引き続きオブジェクトが格納されます。

--
メタデータの保護:: StorageGRID は Cassandra データベースにオブジェクトメタデータを格納します。 Cassandra データベースは LDR サービスと連携します。
+
--
冗長性を確保してオブジェクトメタデータを損失から保護するために、各サイトでオブジェクトメタデータのコピーが 3 つ保持されます。このレプリケーションは設定できず、自動的に実行されます。詳細については、を参照してください link:../admin/managing-object-metadata-storage.html["オブジェクトメタデータストレージを管理する"]。

--


====


 a| 
Replicated State Machine （ RSM ）
 a| 
S3プラットフォームサービス要求がそれぞれのエンドポイントに送信されるようにします。



 a| 
SSM （サーバステータスモニタ）
 a| 
オペレーティングシステムと基盤のハードウェアを監視します。

|===