---
permalink: expand/adding-storage-capacity-for-replicated-objects.html 
sidebar: sidebar 
keywords: replication, replicated, copies, capacity, storage nodes, expand, expansion, StorageGRID 
summary: 環境の情報ライフサイクル管理ポリシーにオブジェクトのレプリケートコピーを作成するルールが含まれている場合は、追加するストレージの量と新しいストレージボリュームまたはストレージノードの追加先を検討する必要があります。 
---
= StorageGRIDにおける複製データの拡張計画
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
環境の情報ライフサイクル管理（ ILM ）ポリシーに、オブジェクトのレプリケートコピーを作成するルールが含まれている場合は、追加するストレージの量と、新しいストレージボリュームまたはストレージノードの追加先を検討する必要があります。

ストレージを追加する場所については、レプリケートコピーを作成する ILM ルールを確認してください。ILM ルールで複数のオブジェクトコピーが作成される場合は、オブジェクトコピーが作成されるそれぞれの場所にストレージを追加することを検討してください。簡単な例として、2サイトのグリッドがあり、各サイトにオブジェクトコピーを1つ作成するILMルールがある場合は、各サイトに移動してグリッドの全体的なオブジェクト容量を増やす必要がありますlink:../expand/adding-storage-volumes-to-storage-nodes.html["ストレージを追加します"]。オブジェクトレプリケーションの詳細については、を参照してくださいlink:../ilm/what-replication-is.html["レプリケーションとは"]。

パフォーマンス上の理由から、サイト間でストレージ容量と処理能力のバランスを維持することをお勧めします。そのため、この例では、各サイトに同じ数のストレージノードを追加するか、各サイトにストレージボリュームを追加する必要があります。

より複雑な ILM ポリシーで、バケット名などの条件に基づいてオブジェクトを別々の場所に配置するルールや、オブジェクトの場所を一定期間変更するルールが含まれている場合は、拡張に必要なストレージについての分析も似ていますが、より複雑です。

全体的なストレージ容量がどれだけ早く消費されるかを記録しておくと、拡張に必要なストレージ容量や、追加のストレージ容量が必要になる時期を把握するのに役立ちます。Grid Managerを使用して、次link:../monitor/monitoring-storage-capacity.html["ストレージ容量を監視してグラフ化"]の操作を実行できます。

拡張のタイミングを計画するときは、追加のストレージの調達とインストールにどれくらいの時間がかかるかを考慮する必要があります。拡張計画を簡素化するには、既存のストレージ ノードの容量が 70% に達したときにストレージ ノードを追加することを検討してください。
