---
permalink: expand/adding-new-site.html 
sidebar: sidebar 
keywords: expand, expansion, new site, add site, guidelines, StorageGRID 
summary: 新しいサイトを追加して StorageGRID システムを拡張することができます。 
---
= StorageGRIDに新しいサイトを追加するためのガイドライン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新しいサイトを追加して StorageGRID システムを拡張することができます。



[[guidelines-for-adding-a-site]]
== サイトの追加に関するガイドライン

サイトを追加する前に、次の要件および制限事項を確認してください。

* 拡張処理で追加できるサイトは 1 つだけです。
* 拡張時に既存のサイトにグリッドノードを追加することはできません。
* すべてのサイトには、少なくとも3つのストレージノードが含まれている必要があります。これらは、複合型ストレージノードとメタデータ専用ストレージノードの任意の組み合わせで構成できます。ストレージノードが3つを超える場合、3つのADCサービスが利用可能であれば、複合型、メタデータ専用、データ専用ストレージノードの任意の組み合わせを使用できます。詳細については、link:../primer/what-storage-node-is.html#required-storage-nodes-per-grid-and-per-site["グリッドごとおよびサイトごとの必要なストレージノード"]を参照してください。
* 新しいサイトを追加しても、保存できるオブジェクトの数は自動的に増えるわけではありません。グリッド全体のオブジェクト容量は、利用可能なストレージ容量、ILMポリシー、および各サイトのメタデータ容量によって決まります。
* 新しいサイトのサイジングを行うときは、十分なメタデータ容量が確保されている必要があります。
+
StorageGRID は、すべてのオブジェクトのメタデータのコピーを各サイトに保持します。新しいサイトを追加する際は、既存のオブジェクトメタデータに必要なメタデータ容量と、将来の拡張に対応できるメタデータ容量の両方が確保されていることを確認してください。

+
詳細については、次の資料を参照してください。

+
** link:../admin/managing-object-metadata-storage.html["オブジェクトメタデータストレージを管理する"]
** link:../monitor/monitoring-storage-capacity.html#monitor-object-metadata-capacity-for-each-storage-node["各ストレージノードのオブジェクトメタデータ容量を監視します"]


* サイト間の使用可能なネットワーク帯域幅およびネットワークレイテンシのレベルを考慮する必要があります。すべてのオブジェクトが取り込まれたサイトにのみ格納されている場合でも、メタデータの更新はサイト間で継続的にレプリケートされます。
+
遅延によるパフォーマンス低下を回避するために：

+
** 遅延時間が100ミリ秒を超えるサイト間では、イレイジャーコーディングは推奨されません。
** StorageGRID システムのサイトは、複数の大陸にまたがるような広範囲な地理的距離に及ぶべきではありません。


* StorageGRID システムは拡張時も動作し続けるため、拡張手順 を開始する前に ILM ルールを確認し、拡張手順 が完了するまで、オブジェクトコピーが新しいサイトに格納されないようにする必要があります。
+
例えば、拡張を開始する前に、デフォルトのストレージプール（すべてのストレージノード）を使用するルールがないか確認してください。該当するルールがある場合は、既存のストレージノードを使用して新しいストレージプールを作成し、ILMルールを更新して新しいストレージプールを使用するようにしてください。それ以外の場合は、そのサイトの最初のノードがアクティブになるとすぐに、オブジェクトが新しいサイトにコピーされます。

+
新しいサイトを追加する際に ILM ポリシーを変更する方法の詳細については、link:../ilm/example-6-changing-ilm-policy.html["ILMポリシーの変更例"]を参照してください。


