---
permalink: expand/adding-storage-capacity-for-erasure-coded-objects.html 
sidebar: sidebar 
keywords: erasure coding, capacity, storage nodes, ec, expand, expansion, StorageGRID 
summary: イレイジャーコーディングコピーを作成するルールが ILM ポリシーに含まれている場合は、新しいストレージの追加場所と新しいストレージを追加するタイミングを計画する必要があります。追加するストレージの量と追加のタイミングは、グリッドの使用可能なストレージ容量に影響を与える可能性があります。 
---
= StorageGRIDにおける消失訂正符号化（EC）データの拡張計画
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
イレイジャーコーディングコピーを作成するルールが ILM ポリシーに含まれている場合は、新しいストレージの追加場所と新しいストレージを追加するタイミングを計画する必要があります。追加するストレージの量や追加のタイミングによって、グリッドの使用可能なストレージ容量が左右される場合があります。

ストレージ拡張を計画するための最初の手順は、イレイジャーコーディングオブジェクトを作成する ILM ポリシーのルールを調べることです。StorageGRID はイレイジャーコーディングされた各オブジェクト用に _k+m_fragments を作成して各フラグメントを別のストレージノードに格納するため、拡張後にイレイジャーコーディングされた新しいデータ用のスペースを少なくとも -k +m_Storage ノードに確保する必要があります。イレイジャーコーディングプロファイルでサイト障害から保護されている場合は、各サイトにストレージを追加する必要があります。イレイジャーコーディングプロファイルの詳細については、を参照してくださいlink:../ilm/what-erasure-coding-schemes-are.html["イレイジャーコーディングスキームとは"]。

追加する必要があるノードの数は、拡張を実施する時点での既存のノードの使用状況によっても異なります。



== イレイジャーコーディングオブジェクト用のストレージ容量の追加に関する一般的な推奨事項

詳細な計算を行わない場合は、既存のストレージノードの容量が 70% に達した時点で各サイトに 2 つのストレージノードを追加できます。

この一般的な推奨事項は、単一サイトのグリッドとイレイジャーコーディングによってサイト障害から保護されるグリッドの両方で、広範なイレイジャーコーディングスキームに渡って合理的な結果を提供します。

この推奨事項につながった要因をよりよく理解したり、サイトのより正確な計画を作成したりするには、を参照してくださいlink:considerations-for-rebalancing-erasure-coded-data.html["イレイジャーコーディングデータのリバランシングに関する考慮事項"]。お客様の状況に合わせてカスタマイズした推奨事項については、ネットアッププロフェッショナルサービスのコンサルタントにお問い合わせください。
