---
permalink: expand/copying-audit-logs.html 
sidebar: sidebar 
keywords: copy audit log, Admin Node expansion, 
summary: 拡張手順 を使用して新しい管理ノードを追加した場合、その AMS サービスでログに記録されるのは、システムへの追加後に発生したイベントと処理のみになります。必要に応じて、先にインストールされていた管理ノードから新しい拡張管理ノードに監査ログをコピーして、残りの StorageGRID システムと同期されるようにすることができます。 
---
= 監査ログをコピーする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
拡張手順 を使用して新しい管理ノードを追加した場合、その AMS サービスでログに記録されるのは、システムへの追加後に発生したイベントと処理のみになります。必要に応じて、先にインストールされていた管理ノードから新しい拡張管理ノードに監査ログをコピーして、残りの StorageGRID システムと同期されるようにすることができます。

.開始する前に
* 管理ノードを追加する拡張手順が完了している必要があります。
* あなたはファイルを持ってい `Passwords.txt`ます。


.タスクの内容
新しい管理ノードで監査メッセージの履歴を確認できるようにするには、既存の管理ノードから拡張管理ノードに監査ログファイルを手動でコピーする必要があります。

[NOTE]
====
デフォルトでは、監査情報は管理ノードの監査ログに送信されます。次のいずれかに該当する場合は、これらの手順をスキップしてかまいません。

* 外部 syslog サーバを設定し、管理ノードではなく syslog サーバに監査ログを送信するようになりました。
* 監査メッセージを生成したローカルノードにのみ保存するように明示的に指定します。


詳細は、を参照してください link:../monitor/configure-audit-messages.html["監査メッセージと外部syslogサーバの設定"] 。

====
.手順
. プライマリ管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh _admin@_primary_Admin_Node_IP_`
.. ファイルに記載されているパスワードを入力し `Passwords.txt`ます。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. ファイルに記載されているパスワードを入力し `Passwords.txt`ます。
+
rootとしてログインすると、プロンプトがからに `#`変わります `$`。



. AMSサービスを停止して新しいファイルが作成されないようにします。 `service ams stop`
. 監査エクスポートディレクトリに移動します。
+
`cd /var/local/log`

. ソースファイルの名前を変更し `audit.log`て、コピー先の拡張管理ノードでファイルが上書きされないようにします。
+
[listing]
----
ls -l
mv audit.log _new_name_.txt
----
. すべての監査ログファイルを拡張管理ノードのデスティネーションの場所にコピーします。
+
`scp -p * _IP_address_:/var/local/log`

. のパスフレーズの入力を求められたら `/root/.ssh/id_rsa`、ファイルに含まれているプライマリ管理ノードのSSHアクセスパスワードを入力し `Passwords.txt`ます。
. 元のファイルを復元し `audit.log`ます。
+
`mv _new_name_.txt audit.log`

. AMS サービスを開始します。
+
`service ams start`

. サーバからログアウトします。
+
`exit`

. 拡張管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_expansion_Admin_Node_IP_`
.. ファイルに記載されているパスワードを入力し `Passwords.txt`ます。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. ファイルに記載されているパスワードを入力し `Passwords.txt`ます。
+
rootとしてログインすると、プロンプトがからに `#`変わります `$`。



. 監査ログファイルのユーザとグループの設定を更新します。
+
`cd /var/local/log`

+
`chown ams-user:bycast *`

. サーバからログアウトします。
+
`exit`


