---
permalink: expand/copying-admin-node-database.html 
sidebar: sidebar 
keywords: copy Admin Node database, alert history, Admin Node expansion 
summary: 拡張手順 を使用して管理ノードを追加する場合は、必要に応じてプライマリ管理ノードから新しい管理ノードにデータベースをコピーできます。データベースをコピーすると、属性、アラート、およびアラートに関する履歴情報を保持できます。 
---
= 管理ノードデータベースをコピーする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
拡張手順 を使用して管理ノードを追加する場合は、必要に応じてプライマリ管理ノードから新しい管理ノードにデータベースをコピーできます。データベースをコピーすると、属性、アラート、およびアラートに関する履歴情報を保持できます。

.開始する前に
* 管理ノードを追加する拡張手順が完了している必要があります。
* あなたはファイルを持ってい `Passwords.txt`ます。
* プロビジョニングパスフレーズを用意します。


.タスクの内容
拡張管理ノードには、 StorageGRID ソフトウェアのアクティブ化プロセスによって NMS サービス用の空のデータベースが作成されます。拡張管理ノードで NMS サービスが開始されると、システムに現在追加されているか以降に追加されたサーバとサービスに関する情報が記録されます。この管理ノードデータベースには次の情報が含まれています。

* アラートの履歴
* 属性の履歴データ（[Nodes]ページの従来のグラフで使用）


ノード間で管理ノードデータベースの整合性を確保するには、プライマリ管理ノードから拡張管理ノードにデータベースをコピーします。


NOTE: プライマリ管理ノード（ __ ソース管理ノード __ ）から拡張管理ノードへのデータベースのコピーは、完了までに数時間かかる場合があります。この間は Grid Manager にアクセスできません。

次の手順に従って、プライマリ管理ノードと拡張管理ノードの両方で MI サービスと管理 API サービスを停止してからデータベースをコピーします。

.手順
. プライマリ管理ノードで次の手順を実行します。
+
.. 管理ノードにログインします。
+
... 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
... ファイルに記載されているパスワードを入力し `Passwords.txt`ます。
... 次のコマンドを入力してrootに切り替えます。 `su -`
... ファイルに記載されているパスワードを入力し `Passwords.txt`ます。


.. 次のコマンドを実行します。 `recover-access-points`
.. プロビジョニングパスフレーズを入力します。
.. MIサービスを停止します。 `service mi stop`
.. 管理アプリケーションプログラムインターフェイス（mgmt-api）サービスを停止します。 `service mgmt-api stop`


. 拡張管理ノードで次の手順を実行します。
+
.. 拡張管理ノードにログインします。
+
... 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
... ファイルに記載されているパスワードを入力し `Passwords.txt`ます。
... 次のコマンドを入力してrootに切り替えます。 `su -`
... ファイルに記載されているパスワードを入力し `Passwords.txt`ます。


.. MIサービスを停止します。 `service mi stop`
.. mgmt-apiサービスを停止します。 `service mgmt-api stop`
.. SSH エージェントに SSH 秘密鍵を追加します。入力：``ssh-add``
.. ファイルに記載されているSSHアクセスパスワードを入力し `Passwords.txt`ます。
.. ソース管理ノードのデータベースを拡張管理ノードにコピーします。 `/usr/local/mi/bin/mi-clone-db.sh _Source_Admin_Node_IP_`
.. プロンプトが表示されたら、拡張管理ノードで MI データベースを上書きすることを確定します。
+
データベースとその履歴データが拡張管理ノードにコピーされます。コピー処理が完了すると、拡張管理ノードがスクリプトによって起動されます。

.. 他のサーバにパスワードなしでアクセスする必要がなくなった場合は、 SSH エージェントから秘密鍵を削除します。入力：``ssh-add -D``


. プライマリ管理ノードでサービスを再起動します。 `service servermanager start`

