---
sidebar: sidebar 
permalink: expand/copying-audit-logs.html 
keywords: copy audit log, Admin Node expansion, 
summary: 拡張手順を通じて新しい管理ノードを追加すると、その AMS サービスは、その管理ノードがシステムに参加した後に発生するイベントとアクションのみをログに記録します。必要に応じて、以前にインストールした管理ノードから新しい拡張管理ノードに監査ログをコピーして、 StorageGRIDシステムの残りの部分と同期させることができます。 
---
= 監査ログをコピーする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
拡張手順を通じて新しい管理ノードを追加すると、その AMS サービスは、その管理ノードがシステムに参加した後に発生するイベントとアクションのみをログに記録します。必要に応じて、以前にインストールした管理ノードから新しい拡張管理ノードに監査ログをコピーして、 StorageGRIDシステムの残りの部分と同期させることができます。

.開始する前に
* 管理ノードを追加する拡張手順が完了している必要があります。
* あなたはファイルを持ってい `Passwords.txt`ます。


.タスクの内容
新しい管理ノードで監査メッセージの履歴を確認できるようにするには、既存の管理ノードから拡張管理ノードに監査ログファイルを手動でコピーする必要があります。

[NOTE]
====
デフォルトでは、監査情報は `localaudit`各ノードにログオンします。この手順を使用するには、管理ノードを監査先として次のように設定しておく必要があります。

* ログの送信先として*管理ノード/ローカル ノード*を設定しました。
* ログの保存先として*管理ノードと外部 syslog サーバー*を設定しました。


参照link:../monitor/configure-audit-messages.html["監査メッセージと外部syslogサーバの設定"]詳細については。

====
.手順
. プライマリ管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh _admin@_primary_Admin_Node_IP_`
.. ファイルに記載されているパスワードを入力し `Passwords.txt`ます。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. ファイルに記載されているパスワードを入力し `Passwords.txt`ます。
+
rootとしてログインすると、プロンプトがからに `#`変わります `$`。



. AMSサービスを停止して新しいファイルが作成されないようにします。 `service ams stop`
. 監査エクスポートディレクトリに移動します。
+
`cd /var/local/audit/export/`

. ソースの名前を変更する `audit.log`ファイルをコピーして、コピー先の拡張管理ノード上のファイルを上書きしないようにします。
+
[listing]
----
ls -l
mv audit.log _new_name_.txt
----
. すべての監査ログファイルを拡張管理ノードのデスティネーションの場所にコピーします。
+
`scp -p * _IP_address_:/var/local/audit/export/`

. のパスフレーズの入力を求められたら `/root/.ssh/id_rsa`、ファイルに含まれているプライマリ管理ノードのSSHアクセスパスワードを入力し `Passwords.txt`ます。
. 元のファイルを復元し `audit.log`ます。
+
`mv _new_name_.txt audit.log`

. AMS サービスを開始します。
+
`service ams start`

. サーバからログアウトします。
+
`exit`

. 拡張管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_expansion_Admin_Node_IP_`
.. ファイルに記載されているパスワードを入力し `Passwords.txt`ます。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. ファイルに記載されているパスワードを入力し `Passwords.txt`ます。
+
rootとしてログインすると、プロンプトがからに `#`変わります `$`。



. 監査ログファイルのユーザとグループの設定を更新します。
+
`cd /var/local/audit/export/`

+
`chown ams-user:bycast *`

. サーバからログアウトします。
+
`exit`


