---
permalink: expand/deploying-new-grid-nodes.html 
sidebar: sidebar 
keywords: expansion, add nodes 
summary: 拡張時に新しいグリッドノードを導入する手順は、グリッドを最初にインストールしたときに使用した手順と同じです。拡張を実行する前に、すべての新しいグリッドノードの導入が完了している必要があります。 
---
= 新しいグリッドノードの導入
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
拡張時に新しいグリッドノードを導入する手順は、グリッドを最初にインストールしたときに使用した手順と同じです。拡張を実行する前に、すべての新しいグリッドノードの導入が完了している必要があります。

グリッドを拡張する場合、追加するノードが既存のノードタイプと一致している必要はありません。VMware ノード、 Linux コンテナベースのノード、またはアプライアンスノードを追加できます。



== VMware ：グリッドノードを導入する

拡張で追加する VMware ノードごとに、 VMware vSphere で仮想マシンを導入する必要があります。

.手順
. link:../swnodes/deploying-storagegrid-node-as-virtual-machine.html["新しいノードを仮想マシンとして導入"]1 つ以上のStorageGRIDネットワークに接続します。
+
ノードを導入する際には、必要に応じてノードポートを再マッピングしたり、 CPU やメモリの設定を増やしたりできます。

. 新しいVMwareノードをすべて導入したら、をlink:performing-expansion.html["拡張手順 を実行します"]参照してください。




== Linux ：グリッドノードを導入します

グリッドノードは、新規の Linux ホストにも既存の Linux ホストにも導入できます。グリッドに追加する StorageGRID ノードの CPU 、 RAM 、およびストレージの要件に対応するために追加の Linux ホストが必要な場合は、最初にインストールしたときと同じ方法で準備します。その後、インストール時のグリッドノードと同じ方法で拡張ノードを導入します。

.開始する前に
* Linuxのバージョンに応じてStorageGRIDをインストールするための手順があり、link:../swnodes/index.html["ハードウェアとストレージの要件"] 。
* 既存のホストに新しいグリッドノードを導入する場合は、既存のホストが追加のノードに対応する十分な CPU 、 RAM 、ストレージ容量を備えていることを確認しておきます。
* 障害ドメインを最小限に抑えるための計画が必要です。たとえば、すべてのゲートウェイノードを 1 つの物理ホストに導入することは避けてください。
+

CAUTION: 本番環境では、1つの物理ホストまたは仮想ホストで複数のストレージノードを実行しないでください。各ストレージノードに専用のホストを使用すると、分離された障害ドメインが提供されます。

* StorageGRID ノードがNetApp ONTAP システムから割り当てられたストレージを使用している場合は、ボリュームでFabricPool 階層化ポリシーが有効になっていないことを確認してください。StorageGRIDノードで使用するボリュームでFabricPool階層化を無効にすると、トラブルシューティングとストレージの処理が簡単になります。


.手順
. ホストを新規に追加する場合は、 StorageGRID ノードの導入に関するインストール手順を参照します。
. 新しいホストを導入するには、ホストの準備手順に従います。
. ノード構成ファイルを作成し、 StorageGRID の設定を検証するには、グリッドノードの導入手順に従います。
. 新しい Linux ホストにノードを追加する場合は、 StorageGRID ホストサービスを開始します。
. 既存のLinuxホストにノードを追加する場合は、StorageGRIDホストサービスCLIを使用して新しいノードを起動します。``sudo storagegrid node start [<node name\>]``


.終了後
すべての新しいグリッドノードの導入が完了したら、実行できますlink:performing-expansion.html["拡張を実行"]。



== アプライアンス：ストレージノード、ゲートウェイノード、または非プライマリ管理ノードの導入

アプライアンスノードに StorageGRID ソフトウェアをインストールするには、アプライアンスに含まれている StorageGRID アプライアンスインストーラを使用します。拡張時、各ストレージアプライアンスは単一のストレージノードとして機能し、各サービスアプライアンスは単一のゲートウェイノードまたは非プライマリ管理ノードとして機能します。すべてのアプライアンスは、グリッドネットワーク、管理ネットワーク、およびクライアントネットワークに接続できます。

.開始する前に
* アプライアンスをラックまたはキャビネットに設置し、ネットワークに接続し、電源を投入しておきます。
* これで手順は完了 https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/configuring-hardware.html["ハードウェアをセットアップする"^]です。
+
アプライアンスハードウェアのセットアップには、StorageGRID 接続（ネットワークリンクとIPアドレス）の設定に必要な手順のほか、ノード暗号化の有効化、RAIDモードの変更、ネットワークポートの再マッピングのオプションの手順が含まれます。

* StorageGRID アプライアンスインストーラの IP 設定ページに表示されるすべてのグリッドネットワークサブネットが、プライマリ管理ノードのグリッドネットワークサブネットリストで定義されている。
* 交換用アプライアンスの StorageGRID アプライアンスインストーラファームウェアは、グリッドで現在実行されている StorageGRID ソフトウェアのバージョンと互換性があります。互換性がない場合は、StorageGRID アプライアンスインストーラのファームウェアをアップグレードする必要があります。
* を搭載したサービスラップトップを用意しておきlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]ます。
* アプライアンスのコンピューティングコントローラに割り当てられている IP アドレスのいずれかを確認しておきます。接続されているどの StorageGRID ネットワークの IP アドレスでも使用できます。


.タスクの内容
アプライアンスノードに StorageGRID をインストールするプロセスには、次のフェーズがあります。

* プライマリ管理ノードの IP アドレスおよびアプライアンスノードの名前を指定または確認します。
* インストールを開始し、ボリュームの設定とソフトウェアのインストールが行われている間待機します。
+
アプライアンスインストールタスクの途中で、インストールが一時停止します。インストールを再開するには、 Grid Manager にサインインし、グリッドノードをすべて承認し、 StorageGRID のインストールプロセスを完了します。

+

NOTE: 一度に複数のアプライアンスノードを導入する必要がある場合は、アプライアンスインストールスクリプトを使用してインストールプロセスを自動化できます `configure-sga.py`。



.手順
. ブラウザを開き、アプライアンスのコンピューティングコントローラの IP アドレスのいずれかを入力します。
+
`https://_Controller_IP_:8443`

+
StorageGRID アプライアンスインストーラのホームページが表示されます。

. 「 * プライマリ管理ノード * 接続」セクションで、プライマリ管理ノードの IP アドレスを指定する必要があるかどうかを確認します。
+
このデータセンターに他のノードがすでにインストールされている場合は、プライマリ管理ノードまたは ADMIN_IP が設定された少なくとも 1 つのグリッドノードが同じサブネットにあるという想定で、 StorageGRID アプライアンスインストーラがこの IP アドレスを自動的に検出します。

. この IP アドレスが表示されない場合や変更する必要がある場合は、アドレスを指定します。
+
[cols="1a,2a"]
|===
| オプション | 製品説明 


 a| 
IP を手動で入力します
 a| 
.. [管理ノードの検出を有効にする]*チェックボックスをオフにします。
.. IPアドレスを手動で入力します。
.. [ 保存（ Save ） ] をクリックします。
.. 新しい IP アドレスの接続状態が READY になるまで待ちます。




 a| 
接続されたすべてのプライマリ管理ノードの自動検出
 a| 
.. [管理ノードの検出を有効にする]*チェックボックスを選択します。
.. 検出された IP アドレスのリストが表示されるまで待ちます。
.. このアプライアンスストレージノードを導入するグリッドのプライマリ管理ノードを選択します。
.. [ 保存（ Save ） ] をクリックします。
.. 新しい IP アドレスの接続状態が READY になるまで待ちます。


|===
. [ * ノード名 * ] フィールドに、このアプライアンス・ノードに使用する名前を入力し、 [ * 保存 * ] を選択します。
+
このノード名は、 StorageGRID システムでこのアプライアンスノードに割り当てられ、このタブは、 Grid Manager のノードページ（概要タブ）に表示されます。ノードを承認するときに、必要に応じて、この名前を変更できます。

. [Installation *]セクションで、現在の状態が「Ready to start installation of _node name_ into grid with primary Admin Node_admin_IP_」であり、*[Start Installation]*ボタンが有効になっていることを確認します。
+
[Start Installation* （インストールの開始） ] ボタンが有効になっていない場合は、ネットワーク設定またはポート設定の変更が必要になることがあります。手順については、アプライアンスのメンテナンス手順を参照してください。

. StorageGRID アプライアンスインストーラのホームページで、「インストールの開始」を選択します。
+
現在の状態が「Installation is in progress」に変わり、[Monitor Installation]ページが表示されます。

. 拡張に複数のアプライアンスノードが含まれている場合は、アプライアンスごとに上記の手順を繰り返します。
+

NOTE: 一度に複数のアプライアンスストレージノードを導入する必要がある場合は、 configure-sga.py アプライアンスインストールスクリプトを使用してインストールプロセスを自動化できます。

. モニタのインストールページに手動でアクセスする必要がある場合は、メニューバーから * モニタのインストール * を選択します。
+
Monitor Installation ページにインストールの進行状況が表示されます。

+
青色のステータスバーは、現在進行中のタスクを示します。緑のステータスバーは、正常に完了したタスクを示します。

+

NOTE: インストーラは、以前のインストールで完了したタスクが再実行されないようにします。インストールを再実行している場合、再実行する必要のないタスクはすべて緑色のステータスバーと「スキップ済み」のステータスで表示されます。

. インストールの最初の 2 つのステージの進行状況を確認します。
+
*1.アプライアンスを設定 *

+
この段階では、次のいずれかのプロセスが実行されます。

+
** ストレージアプライアンスの場合、インストーラはストレージコントローラに接続し、既存の設定があれば消去し、SANtricity OSと通信してボリュームを設定し、ホストを設定します。
** サービスアプライアンスの場合、既存の設定があればインストーラがコンピューティングコントローラのドライブから消去し、ホストを設定します。
+
*2.OS * をインストールします

+
インストーラが StorageGRID のベースとなるオペレーティングシステムイメージをアプライアンスにコピーします。



. コンソールウィンドウにメッセージが表示され、 Grid Manager を使用してノードを承認するように求めるメッセージが表示されるまで、インストールの進行状況の監視を続けます。
+

NOTE: この拡張で追加したすべてのノードが承認できる状態になるまでは、 Grid Manager でノードを承認しないでください。


