---
permalink: expand/gather-required-materials.html 
sidebar: sidebar 
keywords: expand, expansion, planning, storagegrid files, StorageGRID 
summary: 拡張処理を実行する前に、機器を揃え、新しいハードウェアとネットワークの設置と設定を行ってください。 
---
= StorageGRIDシステムの拡張準備
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
拡張処理を実行する前に、機器を揃え、新しいハードウェアとネットワークの設置と設定を行ってください。

[cols="1a,2a"]
|===
| 項目 | 脚注 


 a| 
StorageGRID インストールアーカイブ
 a| 
新しいグリッドノードや新しいサイトを追加する場合は、 StorageGRID インストールアーカイブをダウンロードして展開する必要があります。グリッドで現在実行されているバージョンと同じバージョンを使用する必要があります。

詳細については、の手順を参照してください<<download-and-extract-install-files,StorageGRID インストールファイルのダウンロードと展開>>。

*注：*既存のストレージノードに新しいストレージボリュームを追加する場合や新しいStorageGRID アプライアンスをインストールする場合は、ファイルをダウンロードする必要はありません。



 a| 
サービスラップトップ
 a| 
サービスラップトップには次のものがあります。

* ネットワークポート
* SSH クライアント（ PuTTY など）
* link:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]




 a| 
`Passwords.txt`ファイル
 a| 
コマンド ラインでグリッド ノードにアクセスするために必要なパスワードが含まれます。リカバリパッケージに含まれています。



 a| 
プロビジョニングパスフレーズ
 a| 
このパスフレーズは、 StorageGRID システムが最初にインストールされるときに作成されて文書化されます。プロビジョニングパスフレーズがファイルに含まれていません `Passwords.txt`。



 a| 
StorageGRID のドキュメント
 a| 
* link:../admin/index.html["StorageGRID の管理"]
* link:../release-notes/index.html["リリースノート"]
* link:../swnodes/index.html["使用しているプラットフォームに対応したインストール手順"]




 a| 
ご使用のプラットフォームの最新ドキュメント
 a| 
サポートされているバージョンについては、を参照してください https://imt.netapp.com/matrix/#welcome["Interoperability Matrix Tool（IMT）"^]。

|===


== StorageGRID インストールファイルをダウンロードして展開します

.[[download-dextract-install-files]]
新しいグリッドノードや新しいサイトを追加する前に、適切な StorageGRID インストールアーカイブをダウンロードし、ファイルを展開する必要があります。

.タスクの内容
拡張処理は、グリッドで現在実行されているバージョンの StorageGRID を使用して実行する必要があります。

.手順
. に進みます https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetAppのダウンロード：StorageGRID"^]。
. グリッドで現在実行されている StorageGRID のバージョンを選択します。
. ネットアップアカウントのユーザ名とパスワードを使用してサインインします。
. [End User License Agreement]を読み、チェックボックスをオンにして、*[Accept & Continue]*を選択します。
. ダウンロードページの* Install StorageGRID *列で、使用しているプラットフォームに対応するファイルまたは `.zip`ファイルを選択し `.tgz`ます。
+
インストールアーカイブファイルに表示されるバージョンは、現在インストールされているソフトウェアのバージョンと一致している必要があります。

+
サービスラップトップでWindowsを実行している場合は、ファイルを使用し `.zip`ます。

+
[cols="1a,2a"]
|===
| プラットフォーム | インストールアーカイブ 


 a| 
RHEL
| `StorageGRID-Webscale-_version_-RPM-_uniqueID_.zip` 
`StorageGRID-Webscale-_version_-RPM-_uniqueID_.tgz` 


 a| 
Ubuntu 、 Debian 、またはアプライアンス
| `StorageGRID-Webscale-_version_-DEB-_uniqueID_.zip` 
`StorageGRID-Webscale-_version_-DEB-_uniqueID_.tgz` 


 a| 
VMware
| `StorageGRID-Webscale-_version_-VMware-_uniqueID_.zip` 
`StorageGRID-Webscale-_version_-VMware-_uniqueID_.tgz` 


 a| 
OpenStack / その他のハイパーバイザー
 a| 
OpenStack の既存の環境を拡張する場合は、上記のサポートされている Linux ディストリビューションのいずれかを実行する仮想マシンを導入し、 Linux に関する適切な手順に従う必要があります。

|===
. アーカイブファイルをダウンロードして展開します。
. プラットフォームに応じた手順に従って、プラットフォーム、計画したグリッドトポロジ、および StorageGRID システムの拡張方法に基づいて、必要なファイルを選択します。
+
各プラットフォームの手順に記載されているパスは、アーカイブファイルによってインストールされた最上位ディレクトリに対する相対パスです。

. RHEL システムを拡張する場合は、適切なファイルを選択します。


[cols="1a,1a"]
|===
| パスとファイル名 | 製品説明 


| ./rps/README  a| 
StorageGRID ダウンロードファイルに含まれているすべてのファイルについて説明するテキストファイル。



| ./rps/NLF000000.txt  a| 
製品サポートのない無償ライセンス。



| ./rps/StorageGRID-Webscale-Images-_version_-SHA.rpm  a| 
RHELホストにStorageGRIDノードイメージをインストールするためのRPMパッケージ。



| ./rps/StorageGRID-Webscale-Service-_version_-SHA.rpm  a| 
RHELホストにStorageGRIDホストサービスをインストールするためのRPMパッケージ。



| 導入スクリプトツール | 製品説明 


| ./rps/configure-storagegrid.py  a| 
StorageGRID システムの設定を自動化するための Python スクリプト。



| ./rps/configure-sga.py  a| 
StorageGRID アプライアンスの設定を自動化するための Python スクリプト。



| ./rpms/configure -storagegrid-sample.json  a| 
スクリプトで使用する構成ファイルの例 `configure-storagegrid.py`。



| ./rps/storagegrid-ssoauth.py  a| 
シングルサインオンが有効な場合にグリッド管理 API にサインインするために使用できる Python スクリプトの例。このスクリプトは、Pingフェデレーション統合にも使用できます。



| ./rpms/configure -storagegridBlank.json （ StorageGRID を構成する  a| 
スクリプトで使用する空の構成ファイル `configure-storagegrid.py`。



| ./rps/extra/Ansible と入力します  a| 
StorageGRIDコンテナ導入用のRHELホストを設定するためのサンプルのAnsibleのロールとプレイブック。必要に応じて、ロールまたはプレイブックをカスタマイズできます。



| ./rpms/ storagegrid-ssoauth-azure.pyを参照してください  a| 
Active DirectoryまたはPingフェデレーションを使用してシングルサインオン（SSO）が有効になっている場合にグリッド管理APIにサインインするために使用できるPythonスクリプトの例。



| ./rpms/storagegrid-ssoauth-azure.js  a| 
関連するPythonスクリプトによって呼び出され、AzureとのSSO対話を実行するヘルパースクリプト `storagegrid-ssoauth-azure.py`。



| ./rpms/extra/api-schemas  a| 
StorageGRID の API スキーマ

*注*：アップグレードを実行する前に、これらのスキーマを使用して、アップグレード互換性テスト用の非本番環境のStorageGRID 環境がない場合、StorageGRID 管理APIを使用するように記述したコードが新しいStorageGRID リリースと互換性があることを確認できます。

|===
. Ubuntu または Debian システムを拡張する場合は、適切なファイルを選択します。


[cols="1a,1a"]
|===
| パスとファイル名 | 製品説明 


| ./debs/README  a| 
StorageGRID ダウンロードファイルに含まれているすべてのファイルについて説明するテキストファイル。



| ./debs/NLF000000.txt  a| 
テスト環境やコンセプトの実証環境に使用できる、非本番環境のNetAppライセンスファイル。



| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
Ubuntu ホストまたは Debian ホストに StorageGRID ノードイメージをインストールするための DEB パッケージ。



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
ファイルのMD5チェックサム `/debs/storagegrid-webscale-images-version-SHA.deb`。



| ./debs/storagegrid-webscale-service-version-SHA.deb  a| 
Ubuntu ホストまたは Debian ホストに StorageGRID ホストサービスをインストールするための DEB パッケージ。



| 導入スクリプトツール | 製品説明 


| ./debs/configure-storagegrid.py  a| 
StorageGRID システムの設定を自動化するための Python スクリプト。



| ./debs/configure-sga.py  a| 
StorageGRID アプライアンスの設定を自動化するための Python スクリプト。



| ./debs/storagegrid-ssoauth.py  a| 
シングルサインオンが有効な場合にグリッド管理 API にサインインするために使用できる Python スクリプトの例。このスクリプトは、Pingフェデレーション統合にも使用できます。



| ./debs/configure -storagegrid-sample.json という形式で指定します  a| 
スクリプトで使用する構成ファイルの例 `configure-storagegrid.py`。



| ./debs/configure -storagegrid-bank.json という形式で実行します  a| 
スクリプトで使用する空の構成ファイル `configure-storagegrid.py`。



| ./debs/extras /Ansible を実行します  a| 
StorageGRID コンテナ導入用の Ubuntu ホストまたは Debian ホストを設定するためのサンプルの Ansible のロールとプレイブック。必要に応じて、ロールまたはプレイブックをカスタマイズできます。



| ./debs/ storagegrid-ssoauth-azure.py  a| 
Active DirectoryまたはPingフェデレーションを使用してシングルサインオン（SSO）が有効になっている場合にグリッド管理APIにサインインするために使用できるPythonスクリプトの例。



| ./debs/storagegrid-ssoauth-azure.js  a| 
関連するPythonスクリプトによって呼び出され、AzureとのSSO対話を実行するヘルパースクリプト `storagegrid-ssoauth-azure.py`。



| ./debs/extra/api-schemas  a| 
StorageGRID の API スキーマ

*注*：アップグレードを実行する前に、これらのスキーマを使用して、アップグレード互換性テスト用の非本番環境のStorageGRID 環境がない場合、StorageGRID 管理APIを使用するように記述したコードが新しいStorageGRID リリースと互換性があることを確認できます。

|===
. VMware システムを拡張する場合は、適切なファイルを選択します。


[cols="1a,1a"]
|===
| パスとファイル名 | 製品説明 


| ./vsphere/README （ ./vsphere/README  a| 
StorageGRID ダウンロードファイルに含まれているすべてのファイルについて説明するテキストファイル。



| ./vsphere/NLF000000.txt にアクセスします  a| 
製品サポートのない無償ライセンス。



| ./vsphere/NetApp-SG-version-sha.vmdk  a| 
グリッドノード仮想マシンを作成するためのテンプレートとして使用される仮想マシンディスクファイル。



| ./vsphere/vsphere-primary-admin.ovf ./vsphere-primary-admin.mf  a| 
(`.mf`プライマリ管理ノードを導入するためのOpen Virtualization Formatテンプレートファイル）(`.ovf`とマニフェストファイル



| ./vsphere/vsphere-non-primary-admin.ovf ./vsphere/vsphere-non-primary-admin.mf  a| 
テンプレートファイル(`.ovf`）とマニフェストファイル(`.mf`）。非プライマリ管理ノードを導入するためのものです。



| ./vsphere/vsphere-gateway.ovf ./vsphere/vsphere-gateway.mf  a| 
テンプレートファイル(`.ovf`）とマニフェストファイル(`.mf`）を使用してゲートウェイノードを導入します。



| ./vsphere/vsphere-storage.OVF ./vsphere/vsphere-storage.mf  a| 
(`.mf`仮想マシンベースのストレージノードを導入するためのテンプレートファイル(`.ovf`とマニフェストファイル）



| 導入スクリプトツール | 製品説明 


| ./vsphere/deploy-vsphere-ovftool.sh にアクセスします  a| 
仮想グリッドノードの導入を自動化するための Bash シェルスクリプト。



| ./vsphere/deploy-vsphere-ovftool-sample.ini にアクセスします  a| 
スクリプトで使用する構成ファイルの例 `deploy-vsphere-ovftool.sh`。



| ./vsphere/configure-storagegrid.py にアクセスします  a| 
StorageGRID システムの設定を自動化するための Python スクリプト。



| ./vsphere/configure-sga.py にアクセスします  a| 
StorageGRID アプライアンスの設定を自動化するための Python スクリプト。



| ./vsphere/storagegrid-ssoauth.py にアクセスします  a| 
シングルサインオン（SSO）が有効な場合にグリッド管理APIにサインインするために使用できるPythonスクリプトの例。このスクリプトは、Pingフェデレーション統合にも使用できます。



| ./vsphere/configure -storagegrid-sample.json という形式で実行します  a| 
スクリプトで使用する構成ファイルの例 `configure-storagegrid.py`。



| ./vsphere/configure -storagegrid-bank.json （ページ構成  a| 
スクリプトで使用する空の構成ファイル `configure-storagegrid.py`。



| ./vsphere/storagegrid-ssoauth-azure.pyを参照してください  a| 
Active DirectoryまたはPingフェデレーションを使用してシングルサインオン（SSO）が有効になっている場合にグリッド管理APIにサインインするために使用できるPythonスクリプトの例。



| ./vsphere/storagegrid-ssoauth-azure.js  a| 
関連するPythonスクリプトによって呼び出され、AzureとのSSO対話を実行するヘルパースクリプト `storagegrid-ssoauth-azure.py`。



| ./vsphere/extra/api-schemas  a| 
StorageGRID の API スキーマ

*注*：アップグレードを実行する前に、これらのスキーマを使用して、アップグレード互換性テスト用の非本番環境のStorageGRID 環境がない場合、StorageGRID 管理APIを使用するように記述したコードが新しいStorageGRID リリースと互換性があることを確認できます。

|===
. StorageGRID アプライアンスベースのシステムを拡張する場合は、該当するファイルを選択してください。



NOTE: アプライアンスのインストールでは、ネットワーク トラフィックを回避する必要がある場合にのみこれらのファイルが必要です。アプライアンスは、リカバリ手順を実行する管理ノードから必要なファイルをダウンロードできます。

[cols="1a,1a"]
|===
| パスとファイル名 | 製品説明 


| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
アプライアンスに StorageGRID ノードイメージをインストールするための DEB パッケージ。



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
ファイルのMD5チェックサム `/debs/storagegridwebscale-
images-version-SHA.deb`。

|===


== ハードウェアとネットワークの確認

StorageGRID システムの拡張を開始する前に、次の点を確認してください。

* 新しいグリッドノードまたは新しいサイトをサポートするために必要なハードウェアを設置して設定しておきます。
* すべての新しいノードに、既存および新規のすべてのノードへの双方向通信パスがある（グリッドネットワークの要件）。特に、拡張で追加する新しいノードとプライマリ管理ノードの間で次のTCPポートが開いていることを確認します。
+
** 1055
** 7443
** 8011
** 10342


+
を参照して link:../network/internal-grid-node-communications.html["内部でのグリッドノードの通信"]

* プライマリ管理ノードは、 StorageGRID システムをホストするすべての拡張サーバと通信できます。
* 新しいノードのいずれかに、以前に使用していないサブネットのグリッドネットワークIPアドレスが設定されている場合は、グリッドネットワークサブネットリストがすでに設定されてlink:updating-subnets-for-grid-network.html["新しいサブネットが追加されました"]います。それ以外の場合は、拡張をキャンセルし、新しいサブネットを追加してから、手順 をもう一度開始する必要があります。
* グリッドノード間またはStorageGRID サイト間のグリッドネットワークでNetwork Address Translation（NAT；ネットワークアドレス変換）を使用していない。グリッドネットワークにプライベート IPv4 アドレスを使用する場合は、使用するアドレスに各サイトのすべてのグリッドノードから直接ルーティングできる必要があります。NAT を使用してパブリックネットワークセグメント全体にグリッドネットワークをブリッジする方法は、グリッド内のすべてのノードに対して透過的なトンネリングアプリケーションを使用する場合、つまりグリッドノードがパブリック IP アドレスを認識する必要がない場合にのみサポートされます。
+
この NAT の制限は、グリッドノードとグリッドネットワークに固有のものです。必要に応じて、ゲートウェイノードにパブリック IP アドレスを指定する場合など、外部クライアントとグリッドノードの間で NAT を使用できます。


