---
permalink: expand/guidelines-for-adding-object-capacity.html 
sidebar: sidebar 
keywords: adding storage capacity, guidelines, storage volumes, expansion 
summary: StorageGRID システムのオブジェクトストレージ容量を拡張するには、既存のストレージノードにストレージボリュームを追加するか、または既存のサイトに新しいストレージノードを追加します。情報ライフサイクル管理（ ILM ）ポリシーの要件を満たす方法でストレージ容量を追加する必要があります。 
---
= オブジェクト容量を追加する場合のガイドラインを次に示します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システムのオブジェクトストレージ容量を拡張するには、既存のストレージノードにストレージボリュームを追加するか、または既存のサイトに新しいストレージノードを追加します。情報ライフサイクル管理（ ILM ）ポリシーの要件を満たす方法でストレージ容量を追加する必要があります。



== ストレージボリュームの追加に関するガイドラインを次に示します

既存のストレージノードにストレージボリュームを追加する前に、次のガイドラインと制限事項を確認してください。

* 現在のILMルールを調べて、またはで使用可能なストレージを拡張するlink:../ilm/what-replication-is.html["レプリケートされたオブジェクト"]場所とタイミングを決定する必要がありますlink:../expand/adding-storage-volumes-to-storage-nodes.html["ストレージボリュームを追加します"]link:../ilm/what-erasure-coding-schemes-are.html["イレイジャーコーディングオブジェクト"]。
* オブジェクトメタデータはボリューム0にのみ格納されるため、ストレージボリュームを追加してもシステムのメタデータ容量を増やすことはできません。
* 各ソフトウェアベースのストレージノードでサポートされるストレージボリュームは最大 48 個です。それよりも多くの容量が必要な場合は、新しいストレージノードを追加する必要があります。
* 各SG6060アプライアンスには、1台または2台の拡張シェルフを追加できます。各拡張シェルフに16個のストレージボリュームが追加されます。両方の拡張シェルフを設置した場合、SG6060では合計48個のストレージボリュームをサポートできます。
* 各SG6160アプライアンスには、1台または2台の拡張シェルフを追加できます。各拡張シェルフに60個のストレージボリュームが追加されます。両方の拡張シェルフを設置した場合、SG6160では合計180個のストレージボリュームをサポートできます。
* 他のストレージアプライアンスにストレージボリュームを追加することはできません。
* 既存のストレージボリュームのサイズは拡張できません。
* ストレージノードへのストレージボリュームの追加は、システムのアップグレード、リカバリ処理、またはその他の拡張と同時に実行することはできません。


ストレージボリュームを追加することにし、 ILM ポリシーを満たすために拡張する必要があるストレージノードを決めたら、該当するタイプのストレージノードの手順に従います。

* SG6060ストレージアプライアンスに拡張シェルフを1台または2台追加する場合は、に進みます https://docs.netapp.com/us-en/storagegrid-appliances/sg6000/adding-expansion-shelf-to-deployed-sg6060.html["導入したSG6060に拡張シェルフを追加"^]。
* SG6160ストレージアプライアンスに拡張シェルフを1台または2台追加する場合は、に進みます。 https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/adding-expansion-shelf-to-deployed-sg6160.html["導入したSG6160に拡張シェルフを追加"^]
* ソフトウェアベースのノードの場合は、の手順に従いますlink:adding-storage-volumes-to-storage-nodes.html["ストレージノードへのストレージボリュームの追加"]。




== ストレージノードの追加に関するガイドラインを次に示します

既存のサイトにストレージノードを追加する前に、次のガイドラインと制限事項を確認してください。

* 現在のILMルールを確認して、またはで使用可能なストレージを増やすためにストレージノードをいつどこに追加するかを決定する必要がありますlink:../ilm/what-replication-is.html["レプリケートされたオブジェクト"]link:../ilm/what-erasure-coding-schemes-are.html["イレイジャーコーディングオブジェクト"]。
* 1 つの拡張手順 に追加できるストレージノードは 10 個までです。
* 単一の拡張手順 で複数のサイトにストレージノードを追加することができます。
* 1 つの拡張手順 で、ストレージノードとその他のタイプのノードを追加できます。
* 拡張手順 を開始する前に、リカバリの一環として実行されるデータ修復処理がすべて完了したことを確認する必要があります。を参照して link:../maintain/checking-data-repair-jobs.html["データ修復ジョブを確認します"]
* 拡張の実行前または実行後にストレージノードを削除する必要がある場合は、 1 つの運用停止ノード手順 の 10 個を超えるストレージノードの運用を停止しないでください。
* 基盤となるストレージの I/O パフォーマンスを維持するために十分なストレージ ノードを追加します。書き込み操作は、使用可能なストレージ容量に基づいてストレージ ノード間で分散されます。拡張されたストレージ ノードに使用可能なストレージ容量が大幅に増えると、それらのノードは大幅に多くの書き込みを受け取ることになります。特に、既存のストレージ ノードがほぼいっぱいになると、新しい書き込みは拡張されたストレージ ノードのみに依存します。読み取りおよび削除操作は、特定のワークロードに応じて処理されます。




== ストレージノード上の ADC サービスに関するガイドライン

拡張を設定する場合は、新しい各ストレージノードに Administrative Domain Controller （ ADC ）サービスを含めるかどうかを選択する必要があります。ADC サービスは、グリッドサービスの場所と可用性を追跡します。

* あなたは link:../maintain/move-adc-service.html["ADC サービスを同じサイト内の 1 つのストレージ ノードから別のストレージ ノードに移動する"]。
* StorageGRIDシステムでは、各サイトで常にを使用できる必要がありlink:../maintain/understanding-adc-service-quorum.html["ADC サービスのクォーラム"]ます。
* 各サイトで少なくとも 3 つのストレージノードに ADC サービスが含まれている必要があります。
* すべてのストレージノードに ADC サービスを追加することは推奨されません。ノード間の通信量が増加しているため、 ADC サービスが多すぎると原因 の速度が低下する可能性があります。
* 1 つのグリッドに ADC サービスがあるストレージノードが 48 個を超えないようにします。各サイトに ADC サービスが 3 つある 16 のサイトに相当します。
* 通常、新しいノードに対して *ADC サービス* 設定を選択する場合は、 *自動* を選択する必要があります。新しいノードが ADC サービスを含む別のストレージ ノードを置き換える場合にのみ、[はい] を選択します。残っている ADC サービスが少なすぎる場合はストレージ ノードを廃止できないため、[はい] を選択すると、古いサービスが削除される前に新しい ADC サービスが利用可能になります。

