---
permalink: expand/rebalancing-erasure-coded-data-after-adding-storage-nodes.html 
sidebar: sidebar 
keywords: erasure coding, EC, rebalancing, site rebalance procedure 
summary: ストレージノードを追加したら、イレイジャーコーディングのリバランシング手順を使用して、既存および新規のストレージノードにイレイジャーコーディングフラグメントを再配置できます。 
---
= ストレージノードの追加後にイレイジャーコーディングデータをリバランシングします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージノードを追加したら、イレイジャーコーディング（EC）のリバランシング手順を使用して、既存のストレージノードと新しいストレージノードにイレイジャーコーディングフラグメントを再配置できます。

.開始する前に
* 新しいストレージノードを追加する拡張手順が完了している。
* を確認しておきますlink:considerations-for-rebalancing-erasure-coded-data.html["イレイジャーコーディングデータのリバランシングに関する考慮事項"]。
* この手順では複製されたオブジェクト データは移動されず、EC 再バランス手順では複製されたデータは移動されないことを理解します。ただし、EC データを移動する場所を決定する際には、複製されたデータが考慮されます。
* あなたはファイルを持ってい `Passwords.txt`ます。


.この手順 が実行されたときの動作
手順 を起動する前に、次の点に注意してください。

* 1つ以上のボリュームがオフラインの（アンマウントされた）場合、またはオンラインの（マウントされた）ボリュームがエラー状態の場合、ECリバランシング手順 は開始されません。
* EC のリバランシングによって、手順 が一時的に大量のストレージをリザーブします。ストレージアラートがトリガーされる場合がありますが、リバランシングが完了すると解決します。予約に十分なストレージがない場合、 EC のリバランシング手順 は失敗します。ストレージ予約は、手順 が失敗したか成功したかに関係なく、 EC のリバランシング手順 が完了したときに解放されます。
* ECのリバランシング手順の処理中にボリュームがオフラインになると、リバランシング手順は終了します。移動済みのデータフラグメントは新しい場所に残り、データが失われることはありません。
+
すべてのボリュームがオンラインに戻ったら、手順を再実行できます。

* ECリバランシング手順の実行中は、ILM処理とS3クライアント処理のパフォーマンスに影響する可能性があります。
+

NOTE: オブジェクト（またはオブジェクトパーツ）をアップロードするS3 API処理は、ECのリバランシング手順の実行中に24時間以上かかると失敗することがあります。該当するILMルールで取り込み時にBalanced配置またはStrict配置が使用されている場合、長時間のPUT処理は失敗します。次のエラーが報告されます。 `500 Internal Server Error`

* *ジョブ完了条件*。ECのリバランシング手順は、次のいずれかに該当する場合は完了したとみなされます。
+
** イレイジャーコーディングされたデータをこれ以上移動することはできません。
** すべてのノードのデータがターゲットデータパーティションの5%の偏差内にある。
** 手順は30日間実行されています。




.手順
. [[review_object_storage] ] リバランシングするサイトの現在のオブジェクトストレージの詳細を確認します。
+
.. *ノード*を選択します。
.. サイトで最初のストレージノードを選択します。
.. [ * ストレージ * ] タブを選択します。
.. [Storage Used - Object Data]グラフにカーソルを合わせ、ストレージノード上のレプリケートデータとイレイジャーコーディングデータの現在の量を確認します。
.. 同じ手順を繰り返して、サイトの他のストレージノードを表示します。


. プライマリ管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_primary_Admin_Node_IP_`
.. ファイルに記載されているパスワードを入力し `Passwords.txt`ます。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. ファイルに記載されているパスワードを入力し `Passwords.txt`ます。
+
rootとしてログインすると、プロンプトがからに `#`変わります `$`。



. 手順 を起動します。
+
`rebalance-data start -- site "_site-name_"

+
「_site-name_」には、新しいストレージノードを最初に追加したサイトを指定します。引用符で囲み `site-name`ます。

+
EC Rebalance 手順 が開始され、ジョブ ID が返されます。

. ジョブ ID をコピーします。
. [[view-status]] EC再バランス手順のステータスを監視します。
+
** 単一の EC Rebalance 手順 のステータスを表示するには、次の手順を実行します
+
`rebalance-data status --job-id _job-id_`

+
には `_job-id_`、手順の開始時に返されたIDを指定します。

** 現在の EC Rebalance 手順 と、以前に完了した手順のステータスを表示するには、次の手順を実行します。
+
`rebalance-data status`

+
[NOTE]
====
rebalance -dataコマンド のヘルプを表示するには、次の手順を実行します。

`rebalance-data --help`

====


. 返されたステータスに基づいて、追加の手順を実行します。
+
** がの `In progress`場合、 `State`ECリバランシング処理は引き続き実行されています。手順 は、完了するまで定期的に監視する必要があります。
+
サイト内のストレージ ノード間のデータ分散を評価するには、[ノード] ページに移動します。

+
ECのリバランシングジョブは完了したとみなされ、すべてのノードのデータがターゲットデータパーティションの誤差5%以内になると停止します。

** がの `Success`場合は `State`、必要に応じて<<review_object_storage,オブジェクトストレージを確認する>>サイトの更新された詳細を表示します。
+
イレイジャーコーディングされたデータをサイトのストレージノード間でより均等に配置します。

** が `Failure`次の場合 `State`：
+
... サイトのすべてのストレージノードがグリッドに接続されていることを確認します。
... これらのストレージノードに影響している可能性があるアラートがないかどうかを確認し、解決してください。
... ECリバランシング手順 を再起動します。
+
`rebalance-data start –-job-id _job-id_`

... <<view-status,ステータスの表示>>新しい手順の。がまだの `Failure`場合は `State`、テクニカルサポートにお問い合わせください。




. EC Rebalance 手順 によって大量の負荷が生成されている（取り込み処理に影響があるなど）場合は、手順 を一時停止します。
+
`rebalance-data pause --job-id _job-id_`

. EC のリバランシング手順 を終了する必要がある場合（ StorageGRID ソフトウェアのアップグレードを実行できるようにする場合など）は、次のように入力します。
+
`rebalance-data terminate --job-id _job-id_`

+

NOTE: ECのリバランシング手順を終了すると、移動済みのデータフラグメントは新しい場所に残ります。データは元の場所に戻されません。

. 複数のサイトでイレイジャーコーディングを使用している場合は、影響を受ける他のすべてのサイトに対してこの手順 を実行します。

