---
permalink: expand/updating-subnets-for-grid-network.html 
sidebar: sidebar 
keywords: expand, expansion, add subnets, Grid Network 
summary: グリッドノードまたは新しいサイトを追加した場合は、サブネットの更新、またはグリッドネットワークへのサブネットの追加が必要になることがあります。 
---
= Grid ネットワークのサブネットを更新します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッドノードまたは新しいサイトを追加した場合は、サブネットの更新、またはグリッドネットワークへのサブネットの追加が必要になることがあります。

StorageGRID は、グリッドネットワーク（ eth0 ）上のグリッドノード間の通信に使用されるネットワークサブネットのリストを管理します。このエントリには、 StorageGRID システムの各サイトでグリッドネットワークに使用されているサブネット、およびグリッドネットワークゲートウェイ経由でアクセスされる NTP 、 DNS 、 LDAP 、またはその他の外部サーバに使用されるサブネットが含まれます。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたはを持っていますlink:../admin/admin-group-permissions.html["Maintenance権限またはRoot Access権限"]。
* プロビジョニングパスフレーズを用意します。
* 設定するサブネットのネットワークアドレスを CIDR 表記で指定しておきます。


.タスクの内容
グリッドネットワークの IP アドレスが使用されていないサブネットに新しいノードがある場合は、拡張を開始する前にグリッドネットワークのサブネットリストに新しいサブネットを追加する必要があります。それ以外の場合は、拡張をキャンセルし、新しいサブネットを追加してから、手順 をもう一度開始する必要があります。

.手順
. [* maintenance * （メンテナンス * ） ] > [* Network * （ネットワーク * ） ] > [* Grid Network （グリッドネットワーク * ）
. CIDR表記で新しいサブネットを追加する場合は、*[別のサブネットを追加]*を選択します。
+
たとえば、と入力し `10.96.104.0/22`ます。

. プロビジョニングパスフレーズを入力し、 * Save * を選択します。
. 変更が適用されるまで待ってから、新しいリカバリパッケージをダウンロードします。
+
.. [* maintenance * （メンテナンス） ] > [* System * （システム * ） ] > [* Recovery packツケ （リカバリパッケージ * ）
.. プロビジョニングパスフレーズ * を入力します。
+

CAUTION: リカバリパッケージファイルにはStorageGRID システムからデータを取得するための暗号キーとパスワードが含まれているため、安全に保管する必要があります。プライマリ管理ノードのリカバリにも使用されます。





指定したサブネットが、 StorageGRID システムに対して自動的に設定されます。
