---
permalink: expand/vmware-adding-storage-volumes-to-storage-node.html 
sidebar: sidebar 
keywords: expand, expansion, storage node, add storage volumes, VMware 
summary: ストレージノードのストレージボリュームが 16 個より少ない場合は、 VMware vSphere を使用してボリュームを追加することで容量を増やすことができます。 
---
= VMware ：ストレージノードにストレージボリュームを追加
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージノードのストレージボリュームが 16 個より少ない場合は、 VMware vSphere を使用してボリュームを追加することで容量を増やすことができます。

.開始する前に
* StorageGRID for VMware 環境のインストール手順を参照できる必要があります。
+
** link:../vmware/index.html["VMwareへのStorageGRIDのインストール"]


* あなたはファイルを持ってい `Passwords.txt`ます。
* そうだな link:../admin/admin-group-permissions.html["特定のアクセス権限"]



CAUTION: ソフトウェアのアップグレード、リカバリ手順 、または別の拡張手順 がアクティブな間は、ストレージノードにストレージボリュームを追加しないでください。

.タスクの内容
ストレージボリュームを追加するときは、ストレージノードが一時的に使用できない状態になっています。クライアント向けのグリッドサービスへの影響を回避するために、この手順 は一度に 1 つのストレージノードでのみ実行してください。

.手順
. 必要に応じて、新しいストレージハードウェアを設置し、新しい VMware データストアを作成します。
. ストレージとして使用する仮想マシン（オブジェクトストア）に 1 つ以上のハードディスクを追加します。
+
.. VMware vSphere Client を開きます。
.. 仮想マシンの設定を編集して、 1 つ以上のハードディスクを追加します。


+
通常、ハードディスクは仮想マシンディスク（ VMDK ）として設定されます。VMDKは一般的に使用され、管理も簡単です。一方、RDMは、より大きなオブジェクトサイズ（100MBを超えるなど）を使用するワークロードのパフォーマンスに優れている場合があります。仮想マシンへのハードディスクの追加の詳細については、VMware vSphereのドキュメントを参照してください。

. VMware vSphere Clientで* Restart Guest OS *オプションを使用するか、仮想マシンへのsshセッションで次のコマンドを入力して、仮想マシンを再起動します。``sudo reboot``
+

NOTE: 仮想マシンの再起動に*パワーオフ*または*リセット*を使用しないでください。

. ストレージノードで使用する新しいストレージを設定します。
+
.. グリッドノードにログインします。
+
... 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
... ファイルに記載されているパスワードを入力し `Passwords.txt`ます。
... 次のコマンドを入力してrootに切り替えます。 `su -`
... ファイルに記載されているパスワードを入力し `Passwords.txt`ます。rootとしてログインすると、プロンプトがからに `#`変わります `$`。


.. 新しいストレージボリュームを設定します。
+
`sudo add_rangedbs.rb`

+
新しいストレージボリュームがすべて検出され、それらをフォーマットするように求められます。

.. 「 * y * 」と入力して、フォーマットを確定します。
.. 以前にフォーマットされたボリュームがある場合は、それらを再フォーマットするかどうかを決めます。
+
*** 再フォーマットするには「 * y * 」と入力します。
*** 再フォーマットをスキップするには「 * n * 」と入力します。




+
 `setup_rangedbs.sh`スクリプトが自動的に実行されます。

. サービスが正しく開始されることを確認します。
+
.. サーバ上のすべてのサービスのステータスのリストを表示します。
+
`sudo storagegrid-status`

+
ステータスは自動的に更新されます。

.. すべてのサービスが「 Running 」または「 Verified 」になるまで待ちます。
.. ステータス画面を終了します。
+
`Ctrl+C`



. ストレージノードがオンラインであることを確認します。
+
.. を使用してGrid Managerにサインインしlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]ます。
.. nodes *>*_ Storage Node_*>* Tasks *を選択します。
.. [ストレージの状態]ドロップダウンリストが[読み取り専用]または[オフライン]に設定されている場合は、*[オンライン]*を選択します。
.. [ 保存（ Save ） ] を選択します。


. 新しいオブジェクトストアを確認するには、*[ストレージ]*を選択します。
. [ボリューム]*テーブルで詳細を確認します。


.結果
拡張したストレージノードの容量をオブジェクトデータの保存に使用できます。
