---
permalink: troubleshoot/investigating-potentially-lost-objects.html 
sidebar: sidebar 
keywords: lost objects, investigating, objects 
summary: *オブジェクトが失われる可能性がある*アラートがトリガーされた場合は、すぐに調査する必要があります。影響を受けるオブジェクトに関する情報を収集し、テクニカル サポートに連絡してください。 
---
= 紛失した可能性のある物品を調査する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
*オブジェクトが失われる可能性がある*アラートがトリガーされた場合は、すぐに調査する必要があります。影響を受けるオブジェクトに関する情報を収集し、テクニカル サポートに連絡してください。

.開始する前に
* Grid Managerにサインインする必要がありますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* そうだな link:../admin/admin-group-permissions.html["特定のアクセス権限"]
* ファイルが必要 `Passwords.txt`です。


.タスクの内容
*オブジェクトが失われている可能性がある* アラートは、 StorageGRIDで利用可能な情報によると、グリッド内にオブジェクトのコピーが存在しないことを示します。データは永久に失われた可能性があります。

損失オブジェクトのアラートをただちに調査してください。これ以上のデータ損失を防ぐための対処が必要になる場合があります。迅速に対処すれば、損失オブジェクトをリストアできる場合があります。


CAUTION: 10 個を超えるオブジェクトの損失が報告された場合は、テクニカル サポートにお問い合わせください。この手順を自分で実行しないでください。

.手順
. *ノード*を選択します。
. [*_Storage Node_*>* Objects*] を選択します。
. オブジェクト数の表に表示された損失オブジェクトの数を確認します。
+
この数値は、 StorageGRID システム全体で欠落していることがグリッドノードで検出されたオブジェクトの合計数を示します。この値は、 LDR サービスと DDS サービスに含まれるデータストアコンポーネントの損失オブジェクトカウンタの合計です。

. 管理ノードから、link:../audit/accessing-audit-log-file.html["監査ログにアクセスします"] *オブジェクトが失われる可能性がある*アラートをトリガーしたオブジェクトの一意の識別子 (UUID) を決定します。
+
.. グリッドノードにログインします。
+
... 次のコマンドを入力します。 `ssh admin@grid_node_IP`
... ファイルに記載されているパスワードを入力し `Passwords.txt`ます。
... 次のコマンドを入力してrootに切り替えます。 `su -`
... ファイルに記載されているパスワードを入力し `Passwords.txt`ます。rootとしてログインすると、プロンプトがからに `#`変わります `$`。


.. 監査ログが格納されているディレクトリに移動します。
+
--
監査ログディレクトリおよび該当するノードは、監査デスティネーションの設定によって異なります。

[cols="1a,2a"]
|===
| オプション | デスティネーション 


 a| 
ローカルノード（デフォルト）
 a| 
`/var/local/log/localaudit.log`



 a| 
管理ノード/ローカルノード
 a| 
*** 管理ノード (プライマリおよび非プライマリ): `/var/local/audit/export/audit.log`
*** All nodes（すべてのノード）： `/var/local/log/localaudit.log`通常、このモードではファイルが空か欠落しています。




 a| 
外部 syslog サーバ
 a| 
`/var/local/log/localaudit.log`

|===
監査先の設定に応じて、次のように入力します。 `cd /var/local/log`または `/var/local/audit/export/`

詳細については、link:../monitor/configure-log-management.html#select-log-location["ログの場所を選択"] 。

--
.. grep を使用して Object Lost （ OLST ）監査メッセージを抽出します。入力： `grep OLST audit_file_name`
.. メッセージに含まれている UUID の値をメモします。
+
[listing]
----
Admin: # grep OLST audit.log
2020-02-12T19:18:54.780426 [AUDT:[CBID(UI64):0x38186FE53E3C49A5][UUID(CSTR):"926026C4-00A4-449B-AC72-BCCA72DD1311"]
[PATH(CSTR):"source/cats"][NOID(UI32):12288733][VOLI(UI64):3222345986][RSLT(FC32):NONE][AVER(UI32):10]
[ATIM(UI64):1581535134780426][ATYP(FC32):OLST][ANID(UI32):12448208][AMID(FC32):ILMX][ATID(UI64):7729403978647354233]]
----


. UUIDを使用して損失オブジェクトのメタデータを検索します。
+
.. ILM * > * Object metadata lookup * を選択します。
.. UUIDを入力し、*[検索]*を選択します。
.. メタデータ内の場所を確認し、該当する処理を実行します。
+
[cols="2a,4a"]
|===
| メタデータ | まとめ 


 a| 
オブジェクト<object_identifier>が見つかりません
 a| 
オブジェクトが見つからない場合は、メッセージ「ERROR":""」が返されます。

オブジェクトが見つからない場合は、<<reset-lost-obj-count,紛失の可能性のあるオブジェクトのカウンターをリセットする>>アラートをクリアします。オブジェクトがない場合は、オブジェクトが意図的に削除されたことを示します。



 a| 
場所が 0 より大きい
 a| 
出力に場所がリストされている場合、「オブジェクトが失われる可能性がある」アラートは誤検知である可能性があります。

オブジェクトが存在することを確認します。出力に表示されたノード ID とファイルパスを使用して、オブジェクトファイルがリストされた場所にあることを確認します。

オブジェクトが存在する場合、<<reset-lost-obj-count,紛失の可能性のあるオブジェクトのカウンターをリセットする>>アラートをクリアします。



 a| 
場所 = 0
 a| 
出力に場所がリストされていない場合は、オブジェクトが欠落している可能性があります。テクニカル サポートにお問い合わせください。

テクニカルサポートに問い合わせた際に、実行中のストレージリカバリ手順 がないかどうかを確認するように求められることがあります。およびの情報を参照してくださいlink:../maintain/restoring-volume.html["Grid Managerを使用したオブジェクトデータのリストア"]link:../maintain/restoring-object-data-to-storage-volume.html["ストレージボリュームへのオブジェクトデータのリストア"]。

|===


. [[reset-lost-obj-count]]紛失したオブジェクトの問題を解決した後、アラートが誤検知にならないように、紛失した可能性のあるオブジェクトのカウンターをリセットします。
+
.. *ノード*を選択します。
.. *_ストレージノード_* > *タスク*を選択します。
.. 潜在的に失われたオブジェクトのカウンターをリセットするセクションで、[リセット] を選択します。



