---
permalink: troubleshoot/troubleshooting-lost-and-missing-object-data.html 
sidebar: sidebar 
keywords: how to troubleshoot lost object data, how to troubleshoot missing object data 
summary: オブジェクトはさまざまな理由で読み出されます。たとえば、クライアントアプリケーションからの読み取り要求、レプリケートされたオブジェクトデータのバックグラウンド検証、 ILM ルールによる再評価、ストレージノードのリカバリ時のオブジェクトデータのリストアなどの目的で行われます。 
---
= 失われたオブジェクトデータと欠落しているオブジェクトデータのトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
オブジェクトはさまざまな理由で読み出されます。たとえば、クライアントアプリケーションからの読み取り要求、レプリケートされたオブジェクトデータのバックグラウンド検証、 ILM ルールによる再評価、ストレージノードのリカバリ時のオブジェクトデータのリストアなどの目的で行われます。

StorageGRID システムは、オブジェクトのメタデータに記載された場所の情報を使用して、オブジェクトの読み出し元の場所を特定します。想定される場所でオブジェクトのコピーが見つからない場合、システムは ILM ポリシーにオブジェクトのコピーを複数保持するルールが含まれているものとして、システム内の他の場所から別のコピーを読み出そうとします。

この読み出しに成功すると、欠落しているオブジェクトのコピーが StorageGRID システムによって置き換えられます。それ以外の場合は、 * Objects lost * アラートが次のようにトリガーされます。

* レプリケートコピーについては、別のコピーを読み出せない場合、オブジェクトが失われたとみなされてアラートがトリガーされます。
* イレイジャーコーディングコピーの場合、想定される場所からコピーを読み出せない場合は、別の場所からの読み出しが試行される前に、Corrupt Copies Detected（ECOR）属性の値が1つ増分されます。他のコピーが見つからない場合は、アラートがトリガーされます。


すぐに* Objects lost *アラートをすべて調査して損失の根本原因を特定し、オフラインなどの何らかの理由で現在使用できないストレージノードにオブジェクトが残っていないかどうかを確認する必要があります。を参照して link:../troubleshoot/investigating-lost-objects.html["損失オブジェクトを調査する"]

コピーがないオブジェクトデータが失われた場合、リカバリ解決策 はありません。ただし、損失オブジェクトカウンタをリセットして、既知の損失オブジェクトが新しい損失オブジェクトをマスキングしないようにする必要があります。を参照して link:resetting-lost-and-missing-object-counts.html["損失オブジェクトと欠落オブジェクトのカウントをリセットします"]
