---
permalink: troubleshoot/troubleshooting-lost-and-missing-object-data.html 
sidebar: sidebar 
keywords: how to troubleshoot lost object data, how to troubleshoot missing object data 
summary: オブジェクトはさまざまな理由で読み出されます。たとえば、クライアントアプリケーションからの読み取り要求、レプリケートされたオブジェクトデータのバックグラウンド検証、 ILM ルールによる再評価、ストレージノードのリカバリ時のオブジェクトデータのリストアなどの目的で行われます。 
---
= 失われたオブジェクトデータと欠落しているオブジェクトデータのトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
オブジェクトはさまざまな理由で読み出されます。たとえば、クライアントアプリケーションからの読み取り要求、レプリケートされたオブジェクトデータのバックグラウンド検証、 ILM ルールによる再評価、ストレージノードのリカバリ時のオブジェクトデータのリストアなどの目的で行われます。

StorageGRIDシステムは、オブジェクトのメタデータ内の場所情報を使用して、オブジェクトを取得する場所を決定します。オブジェクトのコピーが予期された場所に見つからない場合、システムは、ILM ポリシーにオブジェクトのコピーを 2 つ以上作成するルールが含まれていると想定して、システム内の他の場所からオブジェクトの別のコピーを取得しようとします。

この取得が成功すると、 StorageGRIDシステムはオブジェクトの失われたコピーを置き換えます。それ以外の場合は、次のように「オブジェクトが失われる可能性がある」というアラートがトリガーされます。

* レプリケートコピーについては、別のコピーを読み出せない場合、オブジェクトが失われたとみなされてアラートがトリガーされます。
* イレイジャーコーディングコピーの場合、想定される場所からコピーを読み出せない場合は、別の場所からの読み出しが試行される前に、Corrupt Copies Detected（ECOR）属性の値が1つ増分されます。他のコピーが見つからない場合は、アラートがトリガーされます。


すべての「オブジェクトが失われる可能性がある」アラートをただちに調査し、損失の根本原因を特定し、オブジェクトがオフラインまたは現在利用できないストレージ ノードにまだ存在する可能性があるかどうかを判断する必要があります。見るlink:../troubleshoot/investigating-potentially-lost-objects.html["紛失した可能性のある物品を調査する"] 。紛失物アラートは、注意を怠ると誤ってトリガーされる可能性があります。

コピーのないオブジェクト データが失われた場合、回復ソリューションはありません。しかし、あなたはlink:../troubleshoot/investigating-potentially-lost-objects.html#reset-lost-obj-count["紛失の可能性のあるオブジェクトのカウンターをリセットする"]既知の紛失オブジェクトが新たな紛失オブジェクトを覆い隠してしまうことを防ぐためです。
