---
permalink: troubleshoot/troubleshooting-network-hardware-and-platform-issues.html 
sidebar: sidebar 
keywords: how to troubleshoot network, how to troubleshoot hardware, how to troubleshoot platform 
summary: ここでは、 StorageGRID ネットワーク、ハードウェア、およびプラットフォームの問題に関連する問題の原因を特定するのに役立ついくつかのタスクを紹介します。 
---
= ネットワーク、ハードウェア、およびプラットフォームの問題をトラブルシューティングする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ここでは、 StorageGRID ネットワーク、ハードウェア、およびプラットフォームの問題に関連する問題の原因を特定するのに役立ついくつかのタスクを紹介します。



== "422: Unprocessable Entity"エラー

エラー422: Unprocessable Entityは、さまざまな理由で発生する可能性があります。エラーメッセージを調べて、問題 の原因を特定します。

表示されたいずれかのエラーメッセージが表示された場合は、推奨される対処方法を実行してください。

[cols="2a,3a"]
|===
| エラーメッセージ | ルート原因 および対処方法 


 a| 
[listing]
----
422: Unprocessable Entity

Validation failed. Please check
the values you entered for
errors. Test connection failed.
Please verify your
configuration. Unable to
authenticate, please verify
your username and password:
LDAP Result Code 8 "Strong
Auth Required": 00002028:
LdapErr: DSID-0C090256,
comment: The server requires
binds to turn on integrity
checking if SSL\TLS are not
already active on the
connection, data 0, v3839
---- a| 
このメッセージは、 Windows Active Directory （ AD ）を使用してアイデンティティフェデレーションを設定するときに、 Transport Layer Security （ TLS ）で「 TLS を使用しない」オプションを選択した場合に表示されることがあります。

LDAP 署名を強制する AD サーバでは、「 TLS を使用しない」オプションの使用はサポートされていません。STARTTLS を使用する * オプションまたは TLS に LDAPS * を使用するオプションのいずれかを選択する必要があります。



 a| 
[listing]
----
422: Unprocessable Entity

Validation failed. Please check
the values you entered for
errors. Test connection failed.
Please verify your
configuration.Unable to
begin TLS, verify your
certificate and TLS
configuration: LDAP Result
Code 200 "Network Error":
TLS handshake failed
    (EOF)
---- a| 
このメッセージは、サポートされない暗号を使用して、 StorageGRID からフェデレーションまたはクラウドストレージプールの識別に使用する外部システムへの Transport Layer Security （ TLS ）接続を試みた場合に表示されます。

外部システムで提供されている暗号を確認します。StorageGRIDの管理手順に従って、発信TLS接続にはのいずれかを使用する必要がありますlink:../admin/supported-ciphers-for-outgoing-tls-connections.html["StorageGRID でサポートされている暗号"]。

|===


== [[Troubleshoot_MTU_alert]]グリッドネットワークMTU mismatchアラート

グリッドネットワークインターフェイス（ eth0 ）の最大伝送ユニット（ MTU ）設定がグリッド内のノード間で大きく異なる場合に、 * Grid Network MTU mismatch * アラートがトリガーされます。

.タスクの内容
MTU 設定の違いから、 eth0 ネットワークの一部がジャンボフレーム用に設定されているが、すべてではないことがわかります。MTU サイズが 1000 を超えると、原因 のネットワークパフォーマンスの問題が発生する可能性があります。

.手順
. デフォルトでは外部 SSH アクセスはブロックされます。必要に応じて、link:../admin/manage-external-ssh-access.html["一時的にアクセスを許可する"] 。
. すべてのノードの eth0 についての MTU 設定を表示します。
+
** Grid Manager に用意されているクエリを使用する。
** に移動し `_primary Admin Node IP address_/metrics/graph`て次のクエリを入力します。 `node_network_mtu_bytes{device="eth0"}`


. https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/changing-mtu-setting.html["MTUの設定を変更します。"^]必要に応じて、すべてのノードのグリッドネットワークインターフェイス（eth0）で同じにする必要があります。
+
** LinuxベースおよびVMwareベースのノードの場合は、次のコマンドを使用します。 `+/usr/sbin/change-ip.py [-h] [-n node] mtu network [network...]+`
+
*例*： `change-ip.py -n node 1500 grid admin`

+
*注*：Linuxベースのノードでは、コンテナ内のネットワークに必要なMTU値がホストインターフェイスにすでに設定されている値を超える場合は、まずホストインターフェイスのMTU値を適切なMTU値に設定してから、スクリプトを使用してコンテナ内のネットワークのMTU値を変更する必要があります `change-ip.py`。

+
Linux または VMware ベースのノードで MTU を変更するには、次の引数を使用します。

+
[cols="1a,2a"]
|===
| 位置指定引数 | 製品説明 


 a| 
`mtu`
 a| 
設定する MTU 。1280 ～ 9216 の範囲内にある必要があります。



 a| 
`network`
 a| 
MTU を適用するネットワーク。次のネットワークタイプを 1 つ以上指定します。

*** グリッド（ Grid ）
*** 管理者
*** クライアント


|===
+
[cols="2a,2a"]
|===
| オプションの引数 | 製品説明 


 a| 
`-h, – help`
 a| 
ヘルプメッセージを表示して終了します。



 a| 
`-n node, --node node`
 a| 
ノード。デフォルトはローカルノードです。

|===


. 外部SSHアクセスを許可している場合は、link:../admin/manage-external-ssh-access.html["アクセスをブロックする"]タスクが完了したら。




== Node network reception frame errorアラート

*ノードネットワーク受信フレームエラー*アラートは、StorageGRIDとネットワークハードウェア間の接続の問題が原因で発生する場合があります。このアラートは、原因となっている問題に対処すると自動的にクリアされます。

.タスクの内容
*ノードネットワーク受信フレームエラー*アラートは、StorageGRIDに接続するネットワークハードウェアの次の問題が原因で発生する可能性があります。

* Forward Error Correction （ FEC; 前方誤り訂正）が必要で、使用されていません
* スイッチポートと NIC の MTU が一致しません
* リンクエラー率が高くなっています
* NIC リングバッファオーバーラン


.手順
. ネットワーク構成に応じて、このアラートのすべての潜在的な原因についてトラブルシューティング手順を実行します。
. エラーの原因 に応じて、次の手順を実行します。
+
[role="tabbed-block"]
====
.FECが一致しません
--

NOTE: これらの手順は、StorageGRIDアプライアンスでFECの不一致が原因の*ノードネットワーク受信フレームエラー*アラートにのみ該当します。

.. StorageGRID アプライアンスに接続されているスイッチのポートの FEC ステータスを確認します。
.. アプライアンスからスイッチへのケーブルの物理的な整合性をチェックしてください。
.. アラートを解決するためにFEC設定を変更する場合は、まずStorageGRIDアプライアンスインストーラの[Link Configuration]ページで、アプライアンスが* Auto *モードに設定されていることを確認します（使用しているアプライアンスの手順を参照してください。
+
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/changing-link-configuration-of-sgf6112-appliance.html["SG6160"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/changing-link-configuration-of-sgf6112-appliance.html["SGF6112"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg6000/changing-link-configuration-of-sg6000-cn-controller.html["SG6000"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg5800/changing-link-configuration-of-sg5800-controller.html["SG5800"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg5700/changing-link-configuration-of-e5700sg-controller.html["SG5700"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg110-1100/changing-link-configuration-of-sg110-and-sg1100-appliance.html["SG110およびSG1100"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg100-1000/changing-link-configuration-of-services-appliance.html["SG100およびSG1000"^]


.. スイッチポートのFEC設定を変更します。StorageGRID アプライアンスのポートは、可能であれば、 FEC 設定を調整して一致させます。
+
StorageGRID アプライアンスではFECを設定できません。アプライアンスは、接続先のスイッチポートで FEC 設定を検出し、ミラーリングしようとします。リンクが 25GbE または 100GbE のネットワーク速度に強制的に設定されている場合、スイッチと NIC が共通の FEC 設定をネゴシエートできない可能性があります。共通のFEC設定がない場合、ネットワークは「no-FEC」モードに戻ります。FECが有効になっていない場合、接続は電気的ノイズによるエラーの影響を受けやすくなります。

+

NOTE: StorageGRID アプライアンスは、NO FECに加えて、Firecode（FC）FECとReed Solomon（RS）FECをサポートしています。



--
.スイッチポートと NIC の MTU が一致しません
--
スイッチポートとNICのMTUの不一致がアラートの原因である場合は、ノードに設定されているMTUサイズがスイッチポートのMTU設定と同じであることを確認します。

ノードに設定されている MTU サイズは、そのノードが接続されているスイッチポートの設定よりも小さい場合があります。この構成で可能なStorageGRIDノードのMTUよりも大きいイーサネットフレームを受信すると、* Node network reception frame error *アラートが報告されることがあります。このような状況が発生していると思われる場合は、スイッチポートの MTU を StorageGRID ネットワークインターフェイスの MTU に一致するように変更するか、 StorageGRID ネットワークインターフェイスの MTU をスイッチポートに合わせて変更します。 MTU の目的または要件に応じて変更します。


NOTE: ネットワークのパフォーマンスを最大限に高めるには、すべてのノードのグリッドネットワークインターフェイスで MTU 値がほぼ同じになるように設定する必要があります。個々のノードのグリッドネットワークの MTU 設定に大きな違いがある場合は、 * Grid Network MTU mismatch * アラートがトリガーされます。MTU値はすべてのネットワークタイプで同じである必要はありません。詳細については、を参照してください <<troubleshoot_MTU_alert,Grid Network MTU mismatch アラートのトラブルシューティングを行います>> 。


NOTE: も参照してください https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/changing-mtu-setting.html["MTU 設定を変更します"^]。

--
.リンクエラー率が高くなっています
--
.. まだイネーブルになっていない場合は、 FEC をイネーブル
.. ネットワークケーブルの品質が良好で、損傷や不適切な接続がないことを確認します。
.. ケーブルに問題がない場合は、テクニカルサポートにお問い合わせください。
+

NOTE: 電気的ノイズが大きい環境では、エラー率が高くなることがあります。



--
.NIC リングバッファオーバーラン
--
エラーが NIC リングのバッファオーバーランである場合は、テクニカルサポートに連絡してください。

StorageGRID システムが過負荷になっていて、ネットワークイベントをタイムリーに処理できない場合、リングバッファがオーバーランする可能性があります。

--
====
. 問題を監視し、アラートが解決しない場合はテクニカルサポートにお問い合わせください。




== 時刻同期エラー

グリッドで時刻の同期に関する問題が発生する可能性があります。

時刻の同期の問題が発生する場合は、少なくとも 4 つの外部 NTP ソースが指定されており、それぞれ Stratum 3 以上であることを確認します。それらのすべての外部 NTP ソースが正常に動作しており、 StorageGRID のノードからアクセスできることを確認する必要があります。


NOTE: 本番レベルのStorageGRIDインストールの場合link:../maintain/configuring-ntp-servers.html["外部NTPソースの指定"]は、Windows Server 2016より前のバージョンのWindowsでWindows Time (W32Time)サービスを使用しないでください。以前のバージョンの Windows のタイムサービスは精度が十分でないため、 StorageGRID などの高精度環境での使用は Microsoft でサポートされていません。



== Linux ：ネットワーク接続の問題

LinuxホストでホストされているStorageGRIDノードのネットワーク接続に問題が発生する可能性があります。



=== MAC アドレスのクローニング

場合によっては、MAC アドレスの複製を使用することでネットワークの問題を解決できます。仮想ホストを使用している場合は、ノード構成ファイルで各ネットワークの MAC アドレス複製キーの値を「true」に設定します。この設定により、 StorageGRIDコンテナの MAC アドレスはホストの MAC アドレスを使用するようになります。指示を参照してくださいlink:../swnodes/creating-node-configuration-files.html["ノード構成ファイルを作成する"]。


NOTE: Linux ホスト OS で使用する個別の仮想ネットワークインターフェイスを作成します。Linux ホスト OS 原因 と StorageGRID コンテナに同じネットワークインターフェイスを使用すると、ハイパーバイザーでプロミスキャスモードが有効になっていない場合、ホスト OS が到達不能になることがあります。

詳細については、link:../swnodes/configuring-host-network.html["MACクローニングを有効にする"] 。



=== プロミスキャスモードです

MACアドレスクローニングを使用せず、ハイパーバイザーによって割り当てられたMACアドレス以外のMACアドレスのデータをすべてのインターフェイスで送受信できるようにする場合は、 [Promiscuous Mode]、[MAC Address Changes]、および[Forged Transmits]で、仮想スイッチおよびポートグループレベルのセキュリティプロパティが[Accept]に設定されていることを確認します。仮想スイッチに設定された値は、ポートグループレベルの値によって上書きできるため、両方のレベルで設定が同じであることを確認してください。

プロミスキャスモードの使用に関する詳細は、link:../swnodes/configuring-host-network.html["ホストネットワークを構成する方法"] 。



== Linux：ノードのステータスが「orphaned」になっている

orphaned 状態の Linux ノードは、通常、 StorageGRID サービスまたはノードのコンテナを制御している StorageGRID ノードデーモンが予期せず停止したことを示しています。

.タスクの内容
Linux ノードが orphaned 状態になった場合は、次のように対応策を実行してください。

* ログでエラーとメッセージを確認します。
* ノードを再起動してみます。
* 必要に応じて、コンテナエンジンのコマンドを使用して既存のノードコンテナを停止します。
* ノードを再起動します。


.手順
. サービスデーモンと orphaned 状態のノードの両方のログを調べ、明らかなエラーや予期しない終了に関するメッセージがないか確認します。
. ホストに root としてログインするか、 sudo 権限を持つアカウントを使ってログインします。
. 次のコマンドを実行して、ノードの再起動を試行します。 `$ sudo storagegrid node start node-name`
+
 $ sudo storagegrid node start DC1-S1-172-16-1-172
+
ノードが孤立している場合、応答はになります

+
[listing]
----
Not starting ORPHANED node DC1-S1-172-16-1-172
----
. Linux から、コンテナエンジンおよび StorageGRID ノードを制御しているすべてのプロセスを停止します。例：``sudo docker stop --time secondscontainer-name``
+
に `seconds`、コンテナの停止を待機する秒数を入力します（通常は15分以内）。例：

+
[listing]
----
sudo docker stop --time 900 storagegrid-DC1-S1-172-16-1-172
----
. ノードを再起動します。 `storagegrid node start node-name`
+
[listing]
----
storagegrid node start DC1-S1-172-16-1-172
----




== Linux ： IPv6 サポートのトラブルシューティングを行います

Linux ホストに StorageGRID ノードをインストールしていて、 IPv6 アドレスが想定どおりにノードコンテナに割り当てられていない場合は、カーネルでの IPv6 サポートの有効化が必要となることがあります。

.タスクの内容
グリッドノードに割り当てられているIPv6アドレスを表示するには、次の手順を実行します。

. *ノード*を選択し、ノードを選択します。
. [概要]タブの*[IPアドレス]*の横にある*[追加のIPアドレスを表示]*を選択します。


IPv6 アドレスが表示されず、ノードが Linux ホストにインストールされている場合は、次の手順に従ってカーネルで IPv6 サポートを有効にします。

.手順
. ホストに root としてログインするか、 sudo 権限を持つアカウントを使ってログインします。
. 次のコマンドを実行します。 `sysctl net.ipv6.conf.all.disable_ipv6`
+
[listing]
----
root@SG:~ # sysctl net.ipv6.conf.all.disable_ipv6
----
+
結果は0になるはずです。

+
[listing]
----
net.ipv6.conf.all.disable_ipv6 = 0
----
+

NOTE: 結果が0でない場合は、オペレーティングシステムのマニュアルで設定の変更方法を参照してください `sysctl`。次に進む前に、値を 0 に変更します。

. StorageGRIDノードコンテナを入力します。 `storagegrid node enter node-name`
. 次のコマンドを実行します。 `sysctl net.ipv6.conf.all.disable_ipv6`
+
[listing]
----
root@DC1-S1:~ # sysctl net.ipv6.conf.all.disable_ipv6
----
+
結果は1になるはずです。

+
[listing]
----
net.ipv6.conf.all.disable_ipv6 = 1
----
+

NOTE: 結果が 1 でない場合、この手順 は適用されません。テクニカルサポートにお問い合わせください。

. コンテナを終了します。 `exit`
+
[listing]
----
root@DC1-S1:~ # exit
----
. rootとして、次のファイルを編集します。 `/var/lib/storagegrid/settings/sysctl.d/net.conf`
+
[listing]
----
sudo vi /var/lib/storagegrid/settings/sysctl.d/net.conf
----
. 次の 2 行を探して、コメントタグを削除します。次に、ファイルを保存して閉じます。
+
[listing]
----
net.ipv6.conf.all.disable_ipv6 = 0
----
+
[listing]
----
net.ipv6.conf.default.disable_ipv6 = 0
----
. 次のコマンドを実行して、 StorageGRID コンテナを再起動します。
+
[listing]
----
storagegrid node stop node-name
----
+
[listing]
----
storagegrid node start node-name
----

