---
permalink: troubleshoot/troubleshooting-load-balancer-caching.html 
sidebar: sidebar 
keywords: how to troubleshoot load balancer caching 
summary: ロードバランサーのキャッシュで発生する可能性のある問題とそのトラブルシューティング方法について説明します。 
---
= ロードバランサのキャッシュのトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ロードバランサーのキャッシュで発生する可能性のある問題とそのトラブルシューティング方法について説明します。



== リクエストがキャッシュヒットであったかどうかを判断する

* X-Cache ヘッダーは、キャッシュ サービスによって処理される要求への応答に設定されます。可能なコード:
+
** `HIT`: オブジェクトはキャッシュから提供されました
** `PARTIAL-HIT`: バケット/キーのレコードはキャッシュ内にありましたが、要求された範囲のすべてをキャッシュから提供することはできませんでした
** `STALE`: バケット/キーにはキャッシュ内にレコードがありましたが、オブジェクトは最後にキャッシュから提供されてから更新されました。
** `MISS`: オブジェクトはキャッシュ内にありませんでした


* その `nginx-gw/endpoint-access.log.gz`リクエストのレコードには、キャッシュによって処理されるリクエストの「unix:/run/cache-svc/cache-svc.sock」が含まれます。
* その `cache-svc/cache-svc.log`「リクエスト 320390: 正常に完了しました (キャッシュ ヒット)」または「リクエスト 320375: 正常に完了しました (キャッシュ ミス)」などのメッセージを報告します。同じ「Request _<number>_」文字列を持つ他のレコードを検索して、要求されたパスを見つけます。




== キャッシュヒット率が低い

* 新しいワークロードが追加されたり、ワークロードによってアクセスされるワーキング セットが変更されたりすると、キャッシュ ヒット率が低下することが予想されます。このような状況では、時間の経過とともにヒット率が増加すると予想されます。
* 複数のワークロードがキャッシュを使用している場合は、トラフィック分類ポリシーを追加して、キャッシュによって処理されるワークロードの一部を分離することを検討してください。キャッシュヒット率メトリックは、トラフィック分類ポリシーごとに利用できます。一部のワークロードでキャッシュ ヒット率が低下している場合は、そのワークロードをキャッシュが有効になっていない他のエンドポイントに移動することを検討してください。
* キャッシュ削除率を評価します。キャッシュが小さすぎてワーキング セットに収まらない場合は、高い削除率が発生し、ヒット率が低下する可能性があります。
* FPVR では、特定のワークロードのヒット率を向上させるオプションが利用できる場合があります。




== パフォーマンスが低い

* キャッシュヒット率を評価します。キャッシュヒット率が低いと、全体的なパフォーマンスが低下する可能性があります。
* キャッシュ削除率を評価します。削除中、一部のストレージ リソースはディスクから既存のオブジェクトを削除するために使用されます。削除プロセスが新しいオブジェクトへのアクセスに対応できない場合、システムはハード ウォーターマークしきい値に達し、キャッシュのバイパスを開始する可能性があります。
* 「ネットワーク インターフェイスの受信使用量」および「ネットワーク インターフェイスの送信使用量」診断を使用して、ネットワーク制限を確認します。

