---
permalink: troubleshoot/troubleshooting-syslog-server.html 
sidebar: sidebar 
keywords: how to troubleshoot the external syslog server 
summary: 次の表に、を使用した外部syslogサーバに関するエラーメッセージと対処方法を示します。 
---
= 外部 syslog サーバのトラブルシューティングを行います
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
次の表に、を使用した外部syslogサーバに関するエラーメッセージと対処方法を示します。

外部syslogサーバへの監査情報の送信の詳細については、次の項を参照してください。

* link:../monitor/considerations-for-external-syslog-server.html["外部syslogサーバを使用する場合の考慮事項"]
* link:../monitor/configure-log-management.html["ログ管理と外部Syslogサーバーを構成する"]


[cols="1a,3a"]
|===
| エラーメッセージ | 概要 および推奨される対処方法 


 a| 
ホスト名を解決できません
 a| 
syslog サーバに対して入力した FQDN を IP アドレスに解決できませんでした。

. 入力したホスト名を確認します。IPアドレスを入力した場合は、W.X.Y.Z（ドット付き10進数）表記の有効なIPアドレスであることを確認してください。
. DNS サーバが正しく設定されていることを確認します。
. 各ノードから DNS サーバの IP アドレスにアクセスできることを確認します。




 a| 
接続が拒否されました
 a| 
syslog サーバへの TCP または TLS 接続が拒否されました。ホストの TCP ポートまたは TLS ポートをリスンしているサービスがないか、ファイアウォールがアクセスをブロックしている可能性があります。

. 入力した syslog サーバの FQDN または IP アドレス、ポート、およびプロトコルが正しいことを確認してください。
. syslog サービスのホストが、指定したポートをリスンしている syslog デーモンを実行していることを確認します。
. ファイアウォールがノードから syslog サーバの IP およびポートへの TCP / TLS 接続へのアクセスをブロックしていないことを確認します。




 a| 
ネットワークに到達できません
 a| 
syslog サーバは直接接続されたサブネット上にはありません。ルータが、リストされたノードから syslog サーバにテストメッセージを転送できなかったことを示す ICMP 障害メッセージを返しました。

. syslog サーバの正しい FQDN または IP アドレスが入力されていることを確認してください。
. 表示された各ノードについて、グリッドネットワークサブネットリスト、管理ネットワークサブネットリスト、およびクライアントネットワークゲートウェイを確認します。想定されるネットワークインターフェイスとゲートウェイ（グリッド、管理、またはクライアント）を介してトラフィックが syslog サーバにルーティングされるように設定されていることを確認します。




 a| 
ホストに到達できません
 a| 
syslog サーバは直接接続されたサブネット上にあります（表示されたノードのグリッド IP 、管理 IP 、またはクライアント IP アドレスに使用されるサブネット）。ノードはテストメッセージを送信しようとしましたが、 syslog サーバの MAC アドレスに対する ARP 要求への応答を受信しませんでした。

. syslog サーバの正しい FQDN または IP アドレスが入力されていることを確認してください。
. syslog サービスを実行しているホストが稼働していることを確認します。




 a| 
接続がタイムアウトしました
 a| 
TCP / TLS 接続が試行されましたが、 syslog サーバからの応答が長時間受信されませんでした。ルーティングが正しく設定されていないか、ファイアウォールが応答を送信せずにトラフィックをドロップしている可能性があります（一般的な設定）。

. syslog サーバの正しい FQDN または IP アドレスが入力されていることを確認してください。
. 表示された各ノードについて、グリッドネットワークサブネットリスト、管理ネットワークサブネットリスト、およびクライアントネットワークゲートウェイを確認します。syslogサーバに到達する予定のネットワークインターフェイスおよびゲートウェイ（グリッド、管理、またはクライアント）を使用して、トラフィックがsyslogサーバにルーティングされるように設定されていることを確認します。
. ファイアウォールによって syslog サーバの IP とポートにリストされているノードからの TCP / TLS 接続へのアクセスがブロックされていないことを確認します。




 a| 
パートナーによる接続が切断されました
 a| 
syslog サーバへの TCP 接続は正常に確立されましたが、その後閉じられました。これには次のような理由があります。

* syslog サーバが再起動またはリブートされた可能性があります。
* ノードと syslog サーバで TCP / TLS 設定が異なる場合があります。
* 中間ファイアウォールがアイドル状態の TCP 接続を閉じている可能性があります。
* syslog サーバのポートをリスンしている非 syslog サーバが接続を閉じた可能性があります。


この問題を解決するには：

. 入力した syslog サーバの FQDN または IP アドレス、ポート、およびプロトコルが正しいことを確認してください。
. TLS を使用している場合は、 syslog サーバも TLS を使用していることを確認します。TCP を使用している場合は、 syslog サーバも TCP を使用していることを確認します。
. アイドル状態の TCP 接続を閉じるように中間ファイアウォールが設定されていないことを確認します。




 a| 
TLS 証明書エラーです
 a| 
syslog サーバから受信したサーバ証明書が、指定した CA 証明書バンドルおよびクライアント証明書と互換性がありませんでした。

. CA 証明書バンドルおよびクライアント証明書（存在する場合）が syslog サーバ上のサーバ証明書と互換性があることを確認します。
. syslog サーバのサーバ証明書に想定される IP 値または FQDN 値が含まれていることを確認します。




 a| 
転送が中断されました
 a| 
syslog レコードが syslog サーバに転送されなくなり、 StorageGRID が原因を検出できなくなりました。

このエラーが表示されたデバッグログを確認して、ルート原因 を特定します。



 a| 
TLS セッションが終了しました
 a| 
syslog サーバが TLS セッションを終了し、 StorageGRID が原因を検出できません。

. このエラーが表示されたデバッグログを確認して、ルート原因 を特定します。
. 入力した syslog サーバの FQDN または IP アドレス、ポート、およびプロトコルが正しいことを確認してください。
. TLS を使用している場合は、 syslog サーバも TLS を使用していることを確認します。TCP を使用している場合は、 syslog サーバも TCP を使用していることを確認します。
. CA 証明書バンドルおよびクライアント証明書（存在する場合）が syslog サーバのサーバ証明書と互換性があることを確認します。
. syslog サーバのサーバ証明書に想定される IP 値または FQDN 値が含まれていることを確認します。




 a| 
結果の照会に失敗しました
 a| 
syslog サーバの設定およびテストに使用されている管理ノードが、表示されているノードにテスト結果を要求できません。1 つ以上のノードが停止している可能性があります。

. 標準的なトラブルシューティング手順に従って、ノードがオンラインで、必要なすべてのサービスが実行されていることを確認します。
. 表示されたノードで miscd サービスを再起動します。


|===