---
permalink: troubleshoot/verifying-object-integrity.html 
sidebar: sidebar 
keywords: how to verify object integrity, object existence check, background verification 
summary: StorageGRID システムは、ストレージノード上のオブジェクトデータの整合性を検証し、オブジェクトの破損や欠落の有無を確認します。 
---
= オブジェクトの整合性を検証
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システムは、ストレージノード上のオブジェクトデータの整合性を検証し、オブジェクトの破損や欠落の有無を確認します。

検証プロセスには、バックグラウンド検証とオブジェクトの存在チェック（旧称フォアグラウンド検証）の 2 つがあります。データの整合性を確保するために連携して機能します。バックグラウンド検証は、オブジェクトデータの正確性を継続的にチェックするために自動的に実行されます。オブジェクトの存在チェックは、オブジェクトの有無（正確性ではなく）をより迅速に確認するためにユーザによってトリガーされることがあります。



== バックグラウンド検証とは何ですか？

バックグラウンド検証プロセスは、ストレージノードにオブジェクトデータの破損したコピーがないかどうかを自動的かつ継続的にチェックし、問題が見つかった場合は自動的に修復を試みます。

バックグラウンド検証は、レプリケートオブジェクトとイレイジャーコーディングオブジェクトの整合性を次の方法でチェックします。

* * レプリケートオブジェクト * ：バックグラウンド検証プロセスで破損したレプリケートオブジェクトが検出された場合、破損したコピーはその場所から削除され、ストレージノード上の他の場所に隔離されます。その後、アクティブなILMポリシーに従って新しい破損していないコピーが生成されて配置されます。新しいコピーは、元のコピーに使用されていたストレージノードに配置されるとはかぎりません。



NOTE: 破損したオブジェクトデータは、引き続きアクセスできるように、システムから削除されるのではなく隔離されます。隔離されたオブジェクトデータへのアクセスの詳細については、テクニカルサポートにお問い合わせください。

* * イレイジャーコーディングオブジェクト * ：バックグラウンド検証プロセスでイレイジャーコーディングオブジェクトのフラグメントの破損が検出された場合、 StorageGRID は自動的に残りのデータとパリティフラグメントを使用して同じストレージノード上に欠落フラグメントの再構築を試みます。破損したフラグメントを再構築できない場合は、オブジェクトの別のコピーを取得しようとします。読み出しに成功すると、 ILM 評価が実行されて、イレイジャーコーディングオブジェクトの置き換え用のコピーが作成されます。
+
バックグラウンド検証プロセスでは、ストレージノード上のオブジェクトのみチェックされます。クラウドストレージプール内のオブジェクトはチェックされません。バックグラウンド検証を実行するには、 4 日以上経過したオブジェクトが必要です。



バックグラウンド検証は、通常のシステムアクティビティを妨げないように設定された間隔で継続的に実行されます。バックグラウンド検証を停止することはできません。ただし、問題があると疑われる場合は、バックグラウンド検証の回数を増やして、ストレージノードの内容をより迅速に検証することができます。



== バックグラウンド検証に関連するアラート

破損したオブジェクトが検出され、自動的に修正できない場合（破損によってオブジェクトを特定できないため）は、* Unidentified corrupt object detected *アラートがトリガーされます。

バックグラウンド検証で別のコピーが見つからないために破損したオブジェクトを置き換えることができない場合は、「オブジェクトが失われている可能性があります」というアラートがトリガーされます。



== オブジェクトの存在チェックとは何ですか？

オブジェクトの存在チェックでは、オブジェクトとイレイジャーコーディングフラグメントの想定されるレプリケートコピーがすべてストレージノードに存在するかどうかが検証されます。オブジェクトの存在チェックでは、オブジェクトデータ自体は検証されません（バックグラウンド検証で検証されます）。代わりに、ストレージデバイスの整合性を検証する方法が提供されます。特に、最新のハードウェア問題 がデータの整合性に影響を与える可能性がある場合に役立ちます。

自動的に実行されるバックグラウンド検証とは異なり、オブジェクト存在チェックジョブは手動で開始する必要があります。

オブジェクトの存在チェックでは、 StorageGRID に格納されているすべてのオブジェクトのメタデータが読み取られ、レプリケートされたオブジェクトコピーとイレイジャーコーディングされたオブジェクトフラグメントの両方の存在が検証されます。不足しているデータは次のように処理されます。

* * Replicated Copies * ：レプリケートオブジェクトデータのコピーが見つからない場合、 StorageGRID はシステム内の別の場所に格納されているコピーからコピーを自動的に置き換えます。ストレージノードは既存のコピーに対して ILM を評価します。これにより、別のコピーがないために、このオブジェクトに関して現在の ILM ポリシーは満たされていないという結果となります。システムのアクティブなILMポリシーに従って新しいコピーが生成されて配置されます。この新しいコピーは、欠落したコピーが格納されていた場所に配置されるとはかぎりません。
* * イレイジャーコーディングされたフラグメント * ：イレイジャーコーディングされたオブジェクトのフラグメントが欠落している場合、 StorageGRID は自動的に残りのフラグメントを使用して同じストレージノード上に欠落フラグメントの再構築を試みます。失われたフラグメントが多すぎるために欠落フラグメントを再構築できない場合、ILMはオブジェクトの別のコピーを探し、このコピーを使用して新しいイレイジャーコーディングフラグメントを生成します。




== オブジェクトの存在チェックを実行します

オブジェクト存在チェックジョブは、一度に 1 つずつ作成して実行します。ジョブを作成するときに、検証するストレージノードとボリュームを選択します。また、ジョブの整合性も選択します。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたはを持っていますlink:../admin/admin-group-permissions.html["Maintenance権限またはRoot Access権限"]。
* 確認するストレージ ノードがオンラインであることを確認しました。ノードのテーブルを表示するには、「*ノード*」を選択します。確認するノードのノード名の横にアラート アイコンが表示されていないことを確認します。
* チェックするノードで次の手順が * 実行されていないことを確認します。
+
** Grid の拡張：ストレージノードを追加
** ストレージノードの運用停止
** 障害ストレージボリュームのリカバリ
** 障害システムドライブがあるストレージノードのリカバリ
** EC のリバランシング
** アプライアンスノードのクローン




これらの手順の実行中は、オブジェクトの存在チェックで有用な情報が得られません。

.タスクの内容
オブジェクトの存在確認ジョブは、グリッド内のオブジェクトの数、選択したストレージノードとボリューム、選択した整合性によって、完了するまでに数日から数週間かかることがあります。一度に実行できるジョブは 1 つだけですが、同時に複数のストレージノードとボリュームを選択することもできます。

.手順
. *メンテナンス* > *タスク* > *オブジェクト存在チェック*を選択します。
. 「 * ジョブの作成 * 」を選択します。Create an object existence check job ウィザードが表示されます。
. 検証するボリュームが含まれているノードを選択します。オンラインノードをすべて選択するには、列ヘッダーの*[ノード名]*チェックボックスをオンにします。
+
ノード名またはサイトで検索できます。

+
グリッドに接続されていないノードは選択できません。

. 「 * Continue * 」を選択します。
. リスト内のノードごとに 1 つ以上のボリュームを選択します。ストレージボリューム番号またはノード名を使用してボリュームを検索できます。
+
選択した各ノードですべてのボリュームを選択するには、列ヘッダーの*[ストレージボリューム]*チェックボックスを選択します。

. 「 * Continue * 」を選択します。
. ジョブの整合性を選択します。
+
整合性によって、オブジェクトの存在チェックに使用されるオブジェクトメタデータのコピーの数が決まります。

+
** * strong-site * ：単一のサイトにおけるメタデータのコピーが 2 つ
** * strong-global * ：各サイトにおけるメタデータのコピーが 2 つ
** * all * （デフォルト）：各サイトに 3 つのメタデータのすべてのコピーを格納します。
+
整合性の詳細については、ウィザードの説明を参照してください。



. 「 * Continue * 」を選択します。
. 選択内容を確認します。「 * Previous * 」を選択すると、ウィザードの前の手順に進み、選択内容を更新できます。
+
オブジェクト存在チェックジョブが生成され、次のいずれかが実行されるまで実行されます。

+
** ジョブが完了します。
** ジョブを一時停止またはキャンセルした場合。一時停止したジョブは再開できますが、キャンセルしたジョブは再開できません。
** ジョブが停止します。Object existence check has ストール * アラートがトリガーされます。アラートに対して指定された対処方法に従います。
** ジョブが失敗します。* Object existence check has failed * というアラートがトリガーされます。アラートに対して指定された対処方法に従います。
** 「Service Unavailable」または「Internal server error」というメッセージが表示されます。1 分後にページを更新して、ジョブの監視を続行します。
+

NOTE: 必要に応じて、 [ オブジェクトの有無 ] チェックページから移動して、ジョブの監視を続行することができます。



. ジョブの実行中に、「 * Active job * 」タブを表示して、検出されたオブジェクトコピーが欠落していることを確認します。
+
この値は、レプリケートオブジェクトとイレイジャーコーディングオブジェクトの欠落コピーのうち、 1 つ以上のフラグメントが欠落しているものの合計数を表します。

+
検出された欠落オブジェクトのコピー数が 100 を超える場合、ストレージ ノードのストレージに問題がある可能性があります。

. ジョブが完了したら、さらに必要なアクションを実行します。
+
** 欠落オブジェクトコピーが 0 であることが検出された場合、問題は見つかりませんでした。対処は不要です。
** 検出された欠落オブジェクトのコピー数がゼロより大きく、*潜在的に失われたオブジェクト*アラートがトリガーされていない場合、すべての欠落コピーはシステムによって修復されています。オブジェクトのコピーが将来損傷するのを防ぐために、ハードウェアの問題が修正されていることを確認します。
** 検出されたオブジェクトのコピーの不足数がゼロより大きく、*オブジェクトが失われている可能性がある*アラートがトリガーされた場合、データの整合性が影響を受ける可能性があります。テクニカル サポートにお問い合わせください。
** grep を使用して LLST 監査メッセージを抽出することで、潜在的に失われたオブジェクトのコピーを調査できます。 `grep LLST audit_file_name` 。
+
この手順は、link:../troubleshoot/investigating-potentially-lost-objects.html["紛失した可能性のある物品の調査"]ただし、オブジェクトのコピーを検索する場合は、 `LLST`の代わりに `OLST`。



. ジョブでstrong-site整合性またはstrong-global整合性を選択した場合は、メタデータの整合性が確保されるまで約3週間待ってから、同じボリュームに対してジョブを再実行します。
+
ジョブに含まれるノードとボリュームでメタデータの整合性を維持するための時間がかかっていた場合、誤って報告された欠落オブジェクトコピーまたは原因 を見逃していたオブジェクトコピーをジョブで再実行することで解決できます。 StorageGRID

+
.. *メンテナンス* > *オブジェクト存在チェック* > *ジョブ履歴*を選択します。
.. 再実行する準備ができているジョブを特定します。
+
... 3 週間以上前に実行されたジョブを特定するには、「 * End time * 」列を参照してください。
... これらのジョブについては、コンシステンシコントロール列をスキャンして、強サイトまたは強グローバルを確認します。


.. 再実行する各ジョブのチェックボックスをオンにして、*再実行*を選択します。
.. ジョブの再実行ウィザードで、選択したノードとボリューム、および整合性を確認します。
.. ジョブを再実行する準備ができたら、 * 再実行 * を選択します。




[ アクティブジョブ ] タブが表示されます。選択したすべてのジョブは、strong-siteの一貫性のある1つのジョブとして再実行されます。[ 詳細 ] セクションの [ 関連ジョブ ] フィールドには、元のジョブのジョブ ID が一覧表示されます。
