---
permalink: ilm/advantages-disadvantages-and-requirements-for-ec.html 
sidebar: sidebar 
keywords: erasure coding advantages, disadvantages, EC requirements 
summary: レプリケーションとイレイジャーコーディングのどちらを使用してオブジェクトデータを損失から保護するかを決定する前に、イレイジャーコーディングのメリット、デメリット、および要件を理解しておく必要があります。 
---
= イレイジャーコーディングのメリット、デメリット、および要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
レプリケーションとイレイジャーコーディングのどちらを使用してオブジェクトデータを損失から保護するかを決定する前に、イレイジャーコーディングのメリット、デメリット、および要件を理解しておく必要があります。



== イレイジャーコーディングのメリット

イレイジャーコーディングは、レプリケーションに比べて信頼性、可用性、ストレージ効率に優れています。

* *信頼性*：データ損失なしに持続可能な同時障害の数で測定されます。
+
** レプリケーション：複数の同一のオブジェクトコピーが、異なるノードおよびサイト間に格納されます。
** イレイジャーコーディング：オブジェクトはデータフラグメントとパリティフラグメントにエンコードされ、多数のノードとサイトに分散されます。この分散によってサイトとノード両方の障害からの保護を提供します。


* *可用性*：ストレージノードに障害が発生した場合やストレージノードにアクセスできなくなった場合にオブジェクトを取得できる機能。イレイジャーコーディングは、同等のストレージコストでレプリケーションよりも優れた可用性を提供します。
* * Storage Efficiency *：同等の可用性と信頼性を実現するために、イレイジャーコーディングオブジェクトはレプリケートオブジェクトよりも少ないディスクスペースを使用します。たとえば、10MBのオブジェクトを2つのサイトにレプリケートするとディスクスペースが20MB（コピーが2つ）消費されますが、6+3のイレイジャーコーディングスキームを使用して3つのサイトにイレイジャーコーディングされたオブジェクトが消費するディスクスペースは15MBだけです。
+

NOTE: イレイジャーコーディングオブジェクトのディスクスペースは、オブジェクトサイズにストレージオーバーヘッドを加えたものです。ストレージオーバーヘッドの割合は、パリティフラグメント数をデータフラグメント数で割って算出します。





== イレイジャーコーディングのデメリット

レプリケーションと比較した場合のイレイジャーコーディングのデメリットは次のとおりです。

* イレイジャーコーディングスキームに応じて、ストレージノードとサイトの数を増やすことを推奨します。一方、オブジェクトデータをレプリケートする場合、コピーごとに必要なストレージノードは1つだけです。およびを参照してくださいlink:what-erasure-coding-schemes-are.html#erasure-coding-schemes-for-storage-pools-containing-three-or-more-sites["3 つ以上のサイトを含むストレージプールのイレイジャーコーディングスキーム"]link:what-erasure-coding-schemes-are.html#erasure-coding-schemes-for-one-site-storage-pools["1 サイトのストレージプールのイレイジャーコーディングスキーム"]。
* ストレージの拡張にかかるコストと複雑さが増大します。レプリケーションを使用する環境を拡張するには、オブジェクトコピーを作成するすべての場所にストレージ容量を追加します。イレイジャーコーディングを使用する環境を拡張する場合は、使用中のイレイジャーコーディングスキームと、既存のストレージノードの使用率の両方を考慮する必要があります。たとえば、既存のノードの使用率が100%になるまで待つ場合は、少なくともストレージノードを追加する必要があります `k+m`が、既存のノードの使用率が70%になって拡張する場合は、サイトごとにノードを2つ追加しても、使用可能なストレージ容量を最大化できます。詳細については、を参照してください link:../expand/adding-storage-capacity-for-erasure-coded-objects.html["イレイジャーコーディングオブジェクトのストレージ容量を追加します"]。
* 地理的に分散したサイトでイレイジャーコーディングを使用する場合は、読み出しのレイテンシが上昇します。イレイジャーコーディングされてリモートサイトに分散されたオブジェクトのオブジェクトフラグメントをWAN接続経由で読み出すには、レプリケートされてローカル（クライアントの接続先と同じサイト）で使用可能なオブジェクトよりも時間がかかります。
* 地理的に分散したサイトでイレイジャーコーディングを使用する場合は、特に WAN ネットワーク接続経由でオブジェクトを頻繁に読み出したり修復したりするケースでは読み出しと修復の WAN ネットワークトラフィックが増大します。
* サイト間でイレイジャーコーディングを使用する場合は、サイト間のネットワークレイテンシの上昇に伴ってオブジェクトの最大スループットが大幅に低下します。これはTCPネットワークのスループットが低下した結果であり、StorageGRIDシステムでのオブジェクトフラグメントの格納と読み出しの速度に影響します。
* コンピューティングリソースの利用率が向上します。




== イレイジャーコーディングを使用する状況

イレイジャーコーディングは次の要件に応じて使用します。

* 1MB 超のオブジェクト
+

NOTE: イレイジャーコーディングは 1MB を超えるオブジェクトに適しています。非常に小さいイレイジャーコーディングフラグメントを管理するオーバーヘッドを回避するために、200KB未満のオブジェクトにはイレイジャーコーディングを使用しないでください。

* 頻繁に読み出されないコンテンツの長期保存またはコールドストレージ。
* 高いデータ可用性と信頼性。
* サイトやノードの障害に対する保護
* Storage Efficiency：
* 複数のレプリケートコピーではなく 1 つのイレイジャーコーディングコピーのみを使用して効率的にデータを保護する必要のある単一サイト環境
* サイト間レイテンシが 100 ミリ秒未満の複数サイト環境

