---
permalink: ilm/comparing-cloud-storage-pools-to-cloudmirror-replication.html 
sidebar: sidebar 
keywords: cloud storage pools, cloudmirror replication 
summary: クラウドストレージプールの使用を開始するにあたって、クラウドストレージプールと StorageGRID CloudMirror レプリケーションサービスの類似点と相違点を理解しておくと役立ちます。 
---
= クラウドストレージプールと CloudMirror レプリケーションを比較してください
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラウドストレージプールの使用を開始するにあたって、クラウドストレージプールと StorageGRID CloudMirror レプリケーションサービスの類似点と相違点を理解しておくと役立ちます。

[cols="1a,3a,3a"]
|===
|  | クラウドストレージプール | CloudMirror レプリケーションサービス 


 a| 
主な目的は何ですか？
 a| 
アーカイブターゲットとして機能します。クラウドストレージプール内のオブジェクトコピーは、オブジェクトの唯一のコピーにすることも、追加のコピーにすることもできます。つまり、2つのコピーをオンサイトに保持する代わりに、1つのコピーをStorageGRID 内に保持してクラウドストレージプールに送信できます。
 a| 
テナントで、StorageGRID （ソース）内のバケットから外部のS3バケット（デスティネーション）にオブジェクトを自動的にレプリケートできます。独立したS3インフラにオブジェクトの独立したコピーを作成します。



 a| 
セットアップ方法は？
 a| 
Grid Managerまたはグリッド管理APIを使用して、ストレージプールと同じ方法で定義されます。ILMルールで配置場所として選択できます。ストレージプールはストレージノードのグループで構成されますが、クラウドストレージプールはリモートの S3 または Azure エンドポイント（ IP アドレス、クレデンシャルなど）を使用して定義されます。
 a| 
テナントユーザlink:../tenant/configuring-cloudmirror-replication.html["CloudMirror レプリケーションを設定します"]。Tenant ManagerまたはS3 APIを使用してCloudMirrorエンドポイント（IPアドレス、クレデンシャルなど）を定義します。CloudMirror エンドポイントのセットアップ後、そのテナントアカウントが所有するバケットは、 CloudMirror エンドポイントを参照するように設定できます。



 a| 
設定は誰が担当しますか？
 a| 
通常はグリッド管理者
 a| 
通常はテナントユーザ



 a| 
デスティネーションは何ですか？
 a| 
* 互換性のある任意の S3 インフラ（ Amazon S3 を含む）
* Azure BLOB アーカイブ層
* Google Cloud Platform（GCP）

 a| 
* 互換性のある任意の S3 インフラ（ Amazon S3 を含む）
* Google Cloud Platform（GCP）




 a| 
オブジェクトをデスティネーションに移動する原因は何ですか？
 a| 
アクティブなILMポリシー内の1つ以上のILMルール。ILM ルールは、 StorageGRID がクラウドストレージプールに移動するオブジェクトとオブジェクトを移動するタイミングを定義します。
 a| 
CloudMirrorエンドポイントで設定されたソースバケットに新しいオブジェクトを取り込む処理。CloudMirrorエンドポイントを設定する前にソースバケットに存在していたオブジェクトは、変更しないかぎりレプリケートされません。



 a| 
オブジェクトの読み出し方法
 a| 
アプリケーションは、クラウドストレージプールに移動されたオブジェクトを読み出すために、 StorageGRID への要求を行う必要があります。オブジェクトの唯一のコピーがアーカイブストレージに移行された場合、 StorageGRID はオブジェクトのリストアプロセスを管理して読み出し可能にします。
 a| 
デスティネーションバケット内のミラーコピーは独立したコピーであるため、アプリケーションは、 StorageGRID または S3 デスティネーションに要求を行うことでオブジェクトを読み出すことができます。たとえば、 CloudMirror レプリケーションを使用してパートナー組織にオブジェクトをミラーリングするとします。パートナーは、独自のアプリケーションを使用して、 S3 デスティネーションからオブジェクトを直接読み取ったり更新したりできます。StorageGRID を使用する必要はありません。



 a| 
デスティネーションから直接読み取ることはできますか。
 a| 
いいえ。クラウドストレージプールに移動されたオブジェクトは、StorageGRIDによって管理されます。読み取り要求は StorageGRID に転送する必要があります（ StorageGRID がクラウドストレージプールからの読み出しを実行します）。
 a| 
はい。ミラーコピーは独立したコピーであるためです。



 a| 
オブジェクトがソースから削除された場合はどうなりますか？
 a| 
オブジェクトもクラウドストレージプールから削除されます。
 a| 
削除操作は複製されません。削除したオブジェクトは StorageGRID バケットには存在しなくなりますが、デスティネーションバケットには引き続き存在します。同様に、デスティネーションバケット内のオブジェクトもソースに影響を与えることなく削除できます。



 a| 
災害後（ StorageGRID システムが動作していない）にどのようにしてオブジェクトにアクセスしますか。
 a| 
障害が発生した StorageGRID ノードをリカバリする必要があります。このプロセスでは、レプリケートされたオブジェクトのコピーをクラウドストレージプールのコピーを使用してリストアすることができます。
 a| 
CloudMirror デスティネーション内のオブジェクトコピーは StorageGRID から独立しているため、 StorageGRID ノードがリカバリされる前に直接アクセスできます。

|===