---
permalink: ilm/considerations-for-cloud-storage-pools.html 
sidebar: sidebar 
keywords: what is a cloud storage pool, considerations for a cloud storage pool 
summary: クラウドストレージプールを使用して StorageGRID システムからオブジェクトを移動する場合は、クラウドストレージプールの設定と使用に関する考慮事項を確認しておく必要があります。 
---
= クラウドストレージプールに関する考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラウドストレージプールを使用して StorageGRID システムからオブジェクトを移動する場合は、クラウドストレージプールの設定と使用に関する考慮事項を確認しておく必要があります。



== 一般的な考慮事項

* 一般に、 Amazon S3 Glacier や Azure BLOB ストレージなどのクラウドアーカイブストレージにはオブジェクトデータを低コストで格納することができます。ただし、クラウドアーカイブストレージからデータを読み出すコストは比較的高くなります。全体的なコストを最小限に抑えるには、クラウドストレージプール内のオブジェクトにアクセスするタイミングと頻度を考慮する必要があります。クラウドストレージプールの使用は、アクセス頻度の低いコンテンツにのみ推奨されます。
* クラウドストレージプールターゲットからオブジェクトを読み出すレイテンシが増加しているため、 FabricPool でクラウドストレージプールを使用することはサポートされていません。
* S3オブジェクトロックが有効になっているオブジェクトをクラウドストレージプールに配置することはできません。
* クラウドストレージプールのデスティネーションS3バケットでS3オブジェクトロックが有効になっている場合、バケットのレプリケーションを設定する処理（PutBucketReplication）はAccessDeniedエラーで失敗します。
* S3オブジェクトロックを使用した次のプラットフォーム、認証、およびプロトコルの組み合わせは、クラウドストレージプールではサポートされていません。
+
** *プラットフォーム*：Google Cloud PlatformとAzure
** *認証タイプ*: IAMロールの場所と匿名アクセス
** *プロトコル*：HTTP






== クラウドストレージプールに使用するポートに関する考慮事項

指定したクラウドストレージプールとの間でオブジェクトを ILM ルールによって移動できるようにするには、システムのストレージノードが含まれるネットワークを設定する必要があります。次のポートがクラウドストレージプールと通信できることを確認してください。

デフォルトでは、クラウドストレージプールは次のポートを使用します。

* *80* ：エンドポイント URI が http で始まる場合
* *442* ： https で始まるエンドポイント URI の場合


クラウドストレージプールを作成または編集するときに、別のポートを指定できます。

非透過型プロキシサーバを使用する場合は、インターネット上のエンドポイントなどの外部エンドポイントへのメッセージの送信も許可する必要がありますlink:../admin/configuring-storage-proxy-settings.html["ストレージプロキシを設定する"]。



== コストに関する考慮事項

クラウドストレージプールを使用してクラウド内のストレージにアクセスするには、クラウドへのネットワーク接続が必要です。クラウドストレージプールを使用して StorageGRID とクラウドの間で移動するデータ量の予測に基づいて、クラウドへのアクセスに使用するネットワークインフラのコストを考慮し、適切にプロビジョニングする必要があります。

StorageGRID が外部のクラウドストレージプールエンドポイントに接続すると、さまざまな要求を実行して接続を監視し、必要な処理を確実に実行できるようにします。これらの要求には追加コストが伴いますが、クラウドストレージプールの監視にかかるコストは、 S3 または Azure にオブジェクトを格納する場合の全体的なコストのごくわずかです。

外部クラウドストレージプールのエンドポイントから StorageGRID にオブジェクトを戻す必要がある場合、より大きなコストが発生する可能性があります。次のいずれかの場合、オブジェクトが StorageGRID に戻ることがあります。

* オブジェクトの唯一のコピーがクラウドストレージプールにあり、オブジェクトを StorageGRID に格納することにした場合。この場合は、ILMルールとポリシーを再設定します。ILM 評価が実行されると、 StorageGRID はクラウドストレージプールからオブジェクトを読み出す要求を複数実行します。次に、 StorageGRID は指定された数のレプリケートコピーまたはイレイジャーコーディングコピーをローカルに作成します。オブジェクトが StorageGRID に戻ると、クラウドストレージプール内のコピーは削除されます。
* ストレージノードの障害が原因でオブジェクトが失われた場合。オブジェクトのコピーがクラウドストレージプールにしか残っていない場合、 StorageGRID はオブジェクトを一時的にリストアして、リカバリされたストレージノードに新しいコピーを作成します。



NOTE: オブジェクトがクラウドストレージプールから StorageGRID に戻ると、 StorageGRID は各オブジェクトに対してクラウドストレージプールエンドポイントに対して複数の要求を実行します。大量のオブジェクトを移動する場合は、事前にテクニカルサポートに問い合わせて、期間と関連コストの見積もりを依頼してください。



== S3 ：クラウドストレージプールバケットに必要な権限

クラウドストレージプールに使用される外部のS3バケットのポリシーで、バケットへのオブジェクトの移動、オブジェクトのステータスの取得、Glacierストレージからのオブジェクトのリストア（必要な場合）などを行う権限をStorageGRIDに付与する必要があります。StorageGRIDにバケットへのフルコントロールアクセスを許可する(`s3:*`のが理想的です）。ただし、許可できない場合は、バケットポリシーでStorageGRIDに次のS3権限を付与する必要があります。

* `s3:AbortMultipartUpload`
* `s3:DeleteObject`
* `s3:GetObject`
* `s3:ListBucket`
* `s3:ListBucketMultipartUploads`
* `s3:ListMultipartUploadParts`
* `s3:PutObject`
* `s3:RestoreObject`




== S3：外部バケットのライフサイクルに関する考慮事項

StorageGRIDとクラウドストレージプールに指定された外部のS3バケットとの間のオブジェクトの移動は、StorageGRIDのILMルールとアクティブなILMポリシーによって制御されます。一方、クラウドストレージプールに指定された外部の S3 バケットから Amazon S3 Glacier または S3 Glacier Deep Archive （あるいは Glacier ストレージクラスを実装するストレージ解決策 ）へのオブジェクトの移行は、そのバケットのライフサイクル設定によって制御されます。

クラウドストレージプールからオブジェクトを移行する場合は、外部のS3バケットに適切なライフサイクル設定を作成する必要があります。また、Glacierストレージクラスを実装し、S3 RestoreObject APIをサポートするストレージ解決策を使用する必要があります。

たとえば、 StorageGRID からクラウドストレージプールに移動されたすべてのオブジェクトをすぐに Amazon S3 Glacier ストレージに移行するとします。この場合、単一のアクション（ * Transition * ）を指定する外部の S3 バケットでライフサイクル設定を次のように作成します。

[listing]
----
<LifecycleConfiguration>
  <Rule>
    <ID>Transition Rule</ID>
    <Filter>
       <Prefix></Prefix>
    </Filter>
    <Status>Enabled</Status>
    <Transition>
      <Days>0</Days>
      <StorageClass>GLACIER</StorageClass>
    </Transition>
  </Rule>
</LifecycleConfiguration>
----
このルールは、すべてのバケットオブジェクトを作成された日（ StorageGRID からクラウドストレージプールに移動された日）に Amazon S3 Glacier に移行します。


CAUTION: 外部バケットのライフサイクルを設定する場合、 * Expiration * アクションを使用してオブジェクトの期限を定義しないでください。Expiration アクション期限切れのオブジェクトを削除するために、外部ストレージシステムを原因 します。期限切れのオブジェクトにあとで StorageGRID からアクセスしようとしても、削除されたオブジェクトは見つかりません。

クラウドストレージプール内のオブジェクトを（Amazon S3 Glacierではなく）S3 Glacier Deep Archiveに移行する場合は、バケットライフサイクルでを指定します `<StorageClass>DEEP_ARCHIVE</StorageClass>`。ただし、この階層を使用してS3 Glacier Deep Archiveからオブジェクトをリストアすることはできません `Expedited`。



== Azure ：アクセス層に関する考慮事項

Azure ストレージアカウントを設定する場合は、デフォルトのアクセス層をホットまたはクールに設定できます。クラウドストレージプールで使用するストレージアカウントを作成する場合は、デフォルト階層としてホット階層を使用する必要があります。StorageGRID はオブジェクトをクラウドストレージプールに移動するとすぐに階層をアーカイブに設定しますが、デフォルト設定をホットにしておくことで、最低期間の 30 日前にクール階層から削除されたオブジェクトに対する早期削除料金が発生しません。



== Azure ：ライフサイクル管理はサポートされていません

クラウドストレージプールで使用されるコンテナには、Azure BLOBのストレージライフサイクル管理を使用しないでください。ライフサイクル処理が Cloud Storage Pool の処理の妨げになることがあります。

.関連情報
link:creating-cloud-storage-pool.html["クラウドストレージプールを作成"]
