---
permalink: ilm/creating-cloud-storage-pool.html 
sidebar: sidebar 
keywords: how to create cloud storage pool 
summary: クラウドストレージプールは、単一の外部Amazon S3バケット、その他のS3互換プロバイダ、またはAzure BLOBストレージコンテナを指定します。 
---
= クラウドストレージプールを作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラウドストレージプールは、単一の外部Amazon S3バケット、その他のS3互換プロバイダ、またはAzure BLOBストレージコンテナを指定します。

クラウドストレージプールを作成するときは、StorageGRID がオブジェクトの格納に使用する外部バケットまたはコンテナの名前と場所、クラウドプロバイダのタイプ（Amazon S3 / GCPまたはAzure BLOBストレージ）、および外部バケットまたはコンテナにアクセスするためにStorageGRID が必要とする情報を指定します。

クラウドストレージプールは保存後すぐに StorageGRID で検証されます。そのため、クラウドストレージプールに指定されたバケットまたはコンテナが存在し、アクセス可能であることを確認しておく必要があります。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたはを持っていますlink:../admin/admin-group-permissions.html["必要なアクセス権限"]。
* を確認しておきますlink:considerations-for-cloud-storage-pools.html["クラウドストレージプールに関する考慮事項"]。
* クラウドストレージプールによって参照される外部のバケットまたはコンテナがすでに存在し、を用意しておき<<service-endpoint-info,サービスエンドポイント情報>>ます。
* バケットまたはコンテナにアクセスするには、を<<authentication-account-info,認証タイプのアカウント情報>>選択します。


.手順
. ILM *>* Storage pools *>* Cloud Storage Pools *を選択します。
. [作成]*を選択し、次の情報を入力します。
+
[cols="1a,3a"]
|===
| フィールド | 製品説明 


 a| 
クラウドストレージプールの名前
 a| 
クラウドストレージプールとその目的を簡単に説明する名前。ILM ルールを設定するときに識別しやすい名前を使用してください。



 a| 
プロバイダタイプ
 a| 
このクラウドストレージプールに使用するクラウドプロバイダ：

** * Amazon S3 / GCP *：Amazon S3、Commercial Cloud Services（C2S）S3、Google Cloud Platform（GCP）、またはその他のS3互換プロバイダの場合は、このオプションを選択します。
** * Azure Blob Storage *




 a| 
バケットまたはコンテナ
 a| 
外部のS3バケットまたはAzureコンテナの名前。クラウドストレージプールの保存後にこの値を変更することはできません。

|===
. [[service-endpoint-info]]プロバイダタイプの選択に基づいて、サービスエンドポイント情報を入力します。
+
[role="tabbed-block"]
====
.Amazon S3 / GCP
--
.. プロトコルに対して、[HTTPS]または[HTTP]を選択します。
+

NOTE: 機密データにHTTP接続を使用しないでください。

.. ホスト名を入力します。例：
+
`s3-_aws-region_.amazonaws.com`

.. URLスタイルを選択します。
+
[cols="1a,3a"]
|===
| オプション | 製品説明 


 a| 
自動検出
 a| 
指定された情報に基づいて、使用する URL スタイルを自動的に検出します。たとえば、 IP アドレスを指定すると、 StorageGRID はパス形式の URL を使用します。使用するスタイルがわからない場合にのみ、このオプションを選択してください。



 a| 
virtual-hosted-styleの略
 a| 
仮想ホスト形式のURLを使用してバケットにアクセスします。仮想ホスト形式のURLでは、ドメイン名の一部にバケット名が含まれます。例： `+https://bucket-name.s3.company.com/key-name+`



 a| 
パス形式
 a| 
パス形式の URL を使用してバケットにアクセスします。パス形式のURLの末尾にはバケット名が含まれます例： `+https://s3.company.com/bucket-name/key-name+`

*注：*パス形式のURLオプションは推奨されておらず、StorageGRID の今後のリリースで廃止される予定です。

|===
.. 必要に応じて、ポート番号を入力するか、デフォルトのポート（HTTPSの場合は443、HTTPの場合は80）を使用します。


--
.Azure Blobストレージ
--
.. 次のいずれかの形式を使用して、サービスエンドポイントのURIを入力します。
+
*** `+https://host:port+`
*** `+http://host:port+`




例： `https://_myaccount_.blob.core.windows.net:443`

ポートを指定しない場合、HTTPSにはデフォルトでポート443が使用され、HTTPにはポート80が使用されます。

--
====


. [[authentication-account-info]]*[続行]*を選択します。次に、認証タイプを選択し、クラウドストレージプールエンドポイントに必要な情報を入力します。
+
[role="tabbed-block"]
====
.アクセスキー
--
_Amazon S3 / GCPまたはその他のS3互換プロバイダの場合_

.. * Access key ID *：外部バケットを所有するアカウントのアクセスキーIDを入力します。
.. *シークレットアクセスキー*：シークレットアクセスキーを入力します。


--
.IAMのあらゆる場所での役割
--
_ AWS IAMロールAnywhereサービスの場合_

StorageGRIDは、AWSセキュリティトークンサービス（STS）を使用して、AWSリソースにアクセスするための短期間のトークンを動的に生成します。

.. * AWS IAM Roles Anywhereリージョン*：クラウドストレージプールのリージョンを選択します。たとえば、 `us-east-1`です。
.. *トラストアンカーURN *：短期間のSTSクレデンシャルの要求を検証するトラストアンカーのURNを入力します。ルートCAまたは中間CAを指定できます。
.. *プロファイルURN *：IAM Roles AnywhereプロファイルのURNを入力します。このプロファイルには、信頼できるユーザのロールが表示されます。
.. * Role URN *：信頼されたすべてのユーザに想定されるIAMロールのURNを入力します。
.. *セッション期間*：一時的なセキュリティクレデンシャルとロールセッションの期間を入力します。15分以上12時間以下を入力してください。
.. *サーバCA証明書*（オプション）：IAM Roles Anywhereサーバを検証するための、PEM形式の1つ以上の信頼されたCA証明書。省略すると、サーバは検証されません。
.. *エンドエンティティ証明書*：信頼アンカーによって署名されたX509証明書のPEM形式の公開キー。AWS IAMロールAnywhereは、このキーを使用してSTSトークンを発行します。
.. *エンドエンティティ秘密鍵*：エンドエンティティ証明書の秘密鍵。


--
.CAP（C2Sアクセスポータル）
--
_ Commercial Cloud Services（C2S）S3サービス_

.. *一時的なクレデンシャルURL *：StorageGRIDがCAPサーバから一時的なクレデンシャルを取得するために使用する完全なURLを入力します。これには、C2Sアカウントに割り当てられた必須およびオプションのAPIパラメータがすべて含まれます。
.. *サーバCA証明書*：*[参照]*を選択し、StorageGRIDがCAPサーバの検証に使用するCA証明書をアップロードします。証明書はPEMでエンコードされ、適切な政府認証局（CA）によって発行されている必要があります。
.. *クライアント証明書*：*[参照]*を選択し、StorageGRIDがCAPサーバに自身を識別するために使用する証明書をアップロードします。クライアント証明書はPEMでエンコードされ、適切な政府認証局（CA）によって発行され、C2Sアカウントへのアクセスが許可されている必要があります。
.. *クライアント秘密鍵*：*[参照]*を選択し、クライアント証明書用のPEMでエンコードされた秘密鍵をアップロードします。
.. クライアントの秘密鍵が暗号化されている場合は、クライアントの秘密鍵を復号化するためのパスフレーズを入力します。それ以外の場合は、* Client private key passphrase *フィールドを空白のままにします。



NOTE: クライアント証明書が暗号化される場合は、暗号化に従来の形式を使用します。PKCS#8暗号化形式はサポートされていません。

--
.Azure Blobストレージ
--
Azure Blob Storage、共有キーのみ_

.. *アカウント名*：外部コンテナを所有するストレージアカウントの名前を入力します。
.. *アカウントキー*：ストレージアカウントのシークレットキーを入力します。


これらの値は Azure portal を使用して確認できます。

--
.匿名
--
追加情報 は必要ありません。

--
====
. 「 * Continue * 」を選択します。次に、使用するサーバ検証のタイプを選択します。
+
[cols="1a,2a"]
|===
| オプション | 製品説明 


 a| 
ストレージノードOSでルートCA証明書を使用する
 a| 
オペレーティングシステムにインストールされているグリッド CA 証明書を使用して接続を保護します。



 a| 
カスタム CA 証明書を使用する
 a| 
カスタム CA 証明書を使用する。[Browse]*を選択し、PEMでエンコードされた証明書をアップロードします。



 a| 
証明書を検証しないでください
 a| 
このオプションを選択すると、クラウドストレージプールへのTLS接続はセキュアではありません。

|===
. [ 保存（ Save ） ] を選択します。
+
クラウドストレージプールを保存すると、 StorageGRID では次の処理が実行されます。

+
** バケットまたはコンテナとサービスエンドポイントが存在し、指定したクレデンシャルを使用してアクセスできることを検証します。
** クラウドストレージプールとして識別するために、バケットまたはコンテナにマーカーファイルを書き込みます。このファイルは削除しないでください（という名前） `x-ntap-sgws-cloud-pool-uuid`。
+
クラウドストレージプールの検証に失敗すると、その理由を記載したエラーメッセージが表示されます。たとえば、証明書エラーが発生した場合や、指定したバケットまたはコンテナが存在しない場合にエラーが報告されることがあります。



. エラーが発生した場合は、を参照しlink:troubleshooting-cloud-storage-pools.html["クラウドストレージプールのトラブルシューティング手順"]、問題を解決してから、クラウドストレージプールの保存を再試行してください。

