---
permalink: ilm/editing-cloud-storage-pool.html 
sidebar: sidebar 
keywords: edit cloud storage pool 
summary: クラウドストレージプールを編集して、名前、サービスエンドポイント、またはその他の詳細を変更できます。ただし、クラウドストレージプールの S3 バケットまたは Azure コンテナを変更することはできません。 
---
= クラウドストレージプールを編集します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラウドストレージプールを編集して、名前、サービスエンドポイント、またはその他の詳細を変更できます。ただし、クラウドストレージプールのS3バケットまたはAzureコンテナを変更することはできません。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* そうだな link:../admin/admin-group-permissions.html["特定のアクセス権限"]
* を確認しておきますlink:considerations-for-cloud-storage-pools.html["クラウドストレージプールに関する考慮事項"]。


.手順
. ILM *>* Storage pools *>* Cloud Storage Pools *を選択します。
+
Cloud Storage Pools テーブルには、既存のクラウドストレージプールが表示されます。

. 編集するクラウドストレージプールのチェックボックスを選択し、*[操作]*>*[編集]*を選択します。
+
または、クラウドストレージプールの名前を選択し、*[編集]*を選択します。

. 必要に応じて、クラウドストレージプール名、サービスエンドポイント、認証クレデンシャル、または証明書の検証方法を変更します。
+

NOTE: クラウドストレージプールのプロバイダタイプ、S3バケット、Azureコンテナは変更できません。

+
以前にサーバ証明書またはクライアント証明書をアップロードした場合は、*[証明書の詳細]*アコーディオンを展開して、現在使用中の証明書を確認できます。

. [ 保存（ Save ） ] を選択します。
+
クラウドストレージプールを保存すると、バケットまたはコンテナとサービスエンドポイントが存在し、指定したクレデンシャルでそれらにアクセスできることが StorageGRID によって検証されます。

+
クラウドストレージプールの検証が失敗すると、エラーメッセージが表示されます。たとえば、証明書エラーが発生した場合はエラーが報告されます。

+
の手順を参照しlink:troubleshooting-cloud-storage-pools.html["クラウドストレージプールのトラブルシューティング"]、問題を解決してから、クラウドストレージプールの保存を再試行してください。


