---
permalink: ilm/editing-storage-pool.html 
sidebar: sidebar 
keywords: edit storage pool 
summary: ストレージプールを編集して、名前を変更したり、サイトやストレージグレードを更新したりできます。 
---
= ストレージプールを編集します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージプールを編集して、名前を変更したり、サイトやストレージグレードを更新したりできます。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* そうだな link:../admin/admin-group-permissions.html["特定のアクセス権限"]
* を確認しておきますlink:guidelines-for-creating-storage-pools.html["ストレージプールの作成に関するガイドライン"]。
* アクティブな ILM ポリシーのルールで使用されているストレージプールを編集する場合は、変更がオブジェクトデータの配置にどのように影響するかを検討しておく必要があります。


.タスクの内容
アクティブなILMポリシーで使用されているストレージプールに新しいサイトまたはストレージグレードを追加する場合は、新しいサイトまたはストレージグレードのストレージノードは自動的に使用されないことに注意してください。StorageGRID で新しいサイトまたはストレージグレードを強制的に使用するには、編集したストレージプールを保存したあとに新しいILMポリシーをアクティブ化する必要があります。

.手順
. ILM * > * Storage pools * を選択します
. 編集するストレージプールのチェックボックスを選択します。
+
All Storage Nodesストレージプール（StorageGRID 11.6以前）は編集できません。

. 「 * 編集 * 」を選択します。
. 必要に応じて、ストレージプール名を変更します。
. 必要に応じて、他のサイトとストレージグレードを選択します。
+
ストレージプールがイレイジャーコーディングプロファイルで使用されていて、その変更によって原因イレイジャーコーディングスキームが無効になる場合は、サイトまたはストレージグレードを変更できません。たとえば、イレイジャーコーディングプロファイルで使用されているストレージプールにサイトが1つしかないストレージグレードが含まれている場合、サイトが2つのストレージグレードを使用することはできません。これは、変更を行うとイレイジャーコーディングスキームが無効になるためです。

+

CAUTION: 既存のストレージプールに対してサイトを追加または削除しても、既存のイレイジャーコーディングデータは移動されません。サイトから既存のデータを移動する場合は、新しいストレージプールとECプロファイルを作成してデータを再エンコードする必要があります。

. [ 保存（ Save ） ] を選択します。


.終了後
アクティブなILMポリシーで使用されているストレージプールに新しいサイトまたはストレージグレードを追加した場合は、新しいILMポリシーをアクティブ化して、StorageGRID で新しいサイトまたはストレージグレードを使用するように強制します。たとえば、既存の ILM ポリシーのクローンを作成し、そのクローンをアクティブ化します。を参照して link:working-with-ilm-rules-and-ilm-policies.html["ILM ルールおよび ILM ポリシーの操作"]
