---
permalink: ilm/enabling-s3-object-lock-globally.html 
sidebar: sidebar 
keywords: enable s3 object lock, object lock 
summary: オブジェクトデータの保存時に S3 テナントアカウントが規制要件に準拠する必要がある場合は、 StorageGRID システム全体で S3 オブジェクトのロックを有効にする必要があります。グローバルな S3 オブジェクトのロック設定を有効にすると、 S3 テナントユーザは S3 オブジェクトのロックでバケットとオブジェクトを作成および管理できるようになります。 
---
= S3 オブジェクトのロックをグローバルに有効にします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
オブジェクトデータの保存時に S3 テナントアカウントが規制要件に準拠する必要がある場合は、 StorageGRID システム全体で S3 オブジェクトのロックを有効にする必要があります。グローバルな S3 オブジェクトのロック設定を有効にすると、 S3 テナントユーザは S3 オブジェクトのロックでバケットとオブジェクトを作成および管理できるようになります。

.開始する前に
* あなたはを持っていますlink:../admin/admin-group-permissions.html["rootアクセス権限"]。
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* S3オブジェクトロックのワークフローを確認し、考慮事項を理解しておきます。
* アクティブなILMポリシーのデフォルトルールが準拠していることを確認しました。詳細は、を参照してください link:creating-default-ilm-rule.html["デフォルトの ILM ルールを作成します"] 。


.タスクの内容
テナントユーザが S3 オブジェクトのロックを有効にした新しいバケットを作成できるようにするには、グリッド管理者がグローバルな S3 オブジェクトロック設定を有効にする必要があります。この設定を有効にすると、無効にすることはできません。

S3オブジェクトロックのグローバル設定を有効にしたら、既存のテナントの準拠設定を確認します。この設定を有効にすると、S3オブジェクトロックのテナント単位の設定は、テナント作成時のStorageGRIDリリースによって異なります。


NOTE: グローバル準拠設定は廃止されました。以前のバージョンのStorageGRID を使用してこの設定を有効にした場合、S3オブジェクトロック設定は自動的に有効になります。既存の準拠バケットの設定は引き続きStorageGRID を使用して管理できますが、新しい準拠バケットを作成することはできません。詳細については、を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["ネットアップのナレッジベース： StorageGRID 11.5 でレガシー準拠バケットを管理する方法"^]。

.手順
. *構成* > *システム* > *S3 オブジェクト ロック* を選択します。
+
S3 Object Lock Settings （ S3 オブジェクトロック設定）ページが表示されます。

. S3 オブジェクトロックを有効にする * を選択します。
. * 適用 * を選択します。
+
確認のダイアログボックスが表示され、S3オブジェクトロックを有効にすると無効にできないことを示すメッセージが表示されます。

. システム全体に対して S3 オブジェクトロックを永続的に有効にしてもよろしいですか？ * OK * を選択します。
+
「 * OK * 」を選択した場合：

+
** アクティブなILMポリシーのデフォルトルールが準拠ルールの場合、S3オブジェクトロックはグリッド全体で有効になり、無効にすることはできません。
** デフォルトルールが準拠していない場合は、エラーが表示されます。準拠ルールをデフォルトルールとして含む新しいILMポリシーを作成してアクティブ化する必要があります。「* OK *」を選択します。次に、新しいポリシーを作成してシミュレートし、アクティブ化します。手順については'を参照して link:creating-ilm-policy.html["ILM ポリシーを作成する"] ください



