---
permalink: ilm/example-9-delete-noncurrent-versions-and-expired-delete-markers.html 
sidebar: sidebar 
keywords: retention priority, example S3 bucket lifecycle, example ILM policy 
summary: オブジェクトはライフサイクル設定に応じて、S3バケットライフサイクルまたはILMポリシーの保持設定に従います。 
---
= StorageGRID で最新でないバージョンと期限切れの削除マーカーを削除する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バケットのバージョン管理を一時停止する場合、バケットのライフサイクルを設定して、最新ではないバージョンや期限切れの null バージョン付き削除マーカーを処理する必要があります。

非現行バージョンと期限切れの削除マーカーを処理するバケットライフサイクル構成の例:: これらの手順は、有効なILMポリシーが設定されているバケットに対して実行されます。
+
--
. バージョン管理を有効にする。同じ名前のオブジェクトが取り込まれると、以前のバージョンは非現行バージョンとして残り、削除要求によって削除マーカーが作成されます。非現行バージョンにはアクセス可能ですが、ストレージ容量を消費します。
. 望ましい構成は、1つのバージョンのみを保持し、旧バージョンが使用しているストレージ容量を解放することであるため、バージョン管理を一時停止します。これは次のステップで設定します。
. バケットのライフサイクルを設定して、バージョン管理が停止した後に残る現在のバージョンではないバージョンと削除マーカーを処理します。


--
ILMポリシー::
+
--
取り込み時の参照に基づくルール（デフォルト）：0日目にX個のコピーを無期限に保持

--
バケットライフサイクル::
+
--
`"Filter": {}, "Expiration": {"ExpiredObjectDeleteMarker": true}, "NoncurrentVersionExpiration": {"NoncurrentDays": 1}`

--
結果:: バケットのライフサイクルは、最新ではないバージョンと期限切れの削除マーカーを処理するように構成されています。
+
--
. 最新でなくなってから1日以上経過したバージョンは削除されます。現在のバージョンのみが永久に残ります。
.  `draftdoc`という名前のオブジェクトが取り込まれ、バージョンID `NULL`が付与されます。
. 同じ名前の別のオブジェクトが取り込まれた場合(`draftdoc`）、null バージョンを上書きして置き換え、以前のバージョンを即座に削除します。
. バージョンIDを指定せずに `draftdoc`に削除リクエストが行われた場合、nullバージョンの削除マーカーが作成され、nullバージョンのオブジェクトが置き換えられて削除されます。
. nullバージョンの削除マーカーは、非現行バージョンが存在しないため期限切れです。
. その後まもなく、期限切れのnullバージョンの削除マーカーが削除されます。


--

