---
permalink: ilm/guidelines-for-creating-storage-pools.html 
sidebar: sidebar 
keywords: storage pool guidelines 
summary: ストレージプールを構成して使用し、複数のサイトにデータを分散することでデータ損失からデータを保護します。レプリケートコピーとイレイジャーコーディングコピーには、異なるストレージプール構成が必要です。 
---
= ストレージプールの作成に関するガイドラインを次に示します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージプールを構成して使用し、複数のサイトにデータを分散することでデータ損失からデータを保護します。レプリケートコピーとイレイジャーコーディングコピーには、異なるストレージプール構成が必要です。

を参照して link:using-multiple-storage-pools-for-cross-site-replication.html["レプリケーションとイレイジャーコーディングを使用したサイト障害からの保護の有効化例"]



== すべてのストレージプールのガイドライン

* ストレージプールの設定は可能なかぎりシンプルにします。必要以上にストレージプールを作成しないでください。
* できるだけ多くのノードを含むストレージプールを作成します。各ストレージプールには 2 つ以上のノードを含める必要があります。ノードが不十分なストレージプールでは、ノードが使用できなくなった場合に原因 ILM バックログが発生する可能性があります。
* 重複する（ 1 つ以上の同じノードを含む）ストレージプールを作成または使用することは避けてください。ストレージプールが重複していると、オブジェクトデータの複数のコピーが同じノードに保存される可能性があります。
* 通常は、All Storage Nodesストレージプール（StorageGRID 11.6以前）やAll Sitesサイトは使用しないでください。これらの項目は自動的に更新され、拡張に追加する新しいサイトが含まれるようになります。これは想定した動作ではない可能性があります。




== レプリケートコピーに使用するストレージプールのガイドライン

* を使用したサイト障害からの保護のlink:what-replication-is.html["レプリケーション"]場合は、でサイト固有のストレージプールを1つ以上指定しますlink:create-ilm-rule-define-placements.html["各ILMルールの配置手順"]。
+
StorageGRID のインストール時に、サイトごとに1つのストレージプールが自動的に作成されます。

+
各サイトにストレージプールを使用すると、レプリケートされたオブジェクトコピーが想定どおりに配置されるようになります（たとえば、サイト障害から保護するために、各サイトのすべてのオブジェクトのコピーが 1 つずつ）。

* 拡張時にサイトを追加する場合は、新しいサイトのみを含む新しいストレージプールを作成します。次に、link:working-with-ilm-rules-and-ilm-policies.html#edit-an-ilm-rule["ILMルールを更新"]新しいサイトに格納するオブジェクトを制御します。
* コピーの数がストレージプールの数より少ない場合は、プール間のディスク使用量のバランスを取るためにコピーが分散されます。
* ストレージプールが重複している（同じストレージノードを含んでいる）場合は、オブジェクトのすべてのコピーが 1 つのサイトにのみ保存される可能性があります。選択したストレージプールに同じストレージノードが含まれていないことを確認する必要があります。




== イレイジャーコーディングされたコピーに使用するストレージプールのガイドラインを次に示します

* を使用してサイト障害から保護するにlink:what-erasure-coding-is.html["イレイジャーコーディング"]は、3つ以上のサイトで構成されるストレージプールを作成します。ストレージプールにサイトが2つしかない場合、そのストレージプールをイレイジャーコーディングに使用することはできません。2 つのサイトを含むストレージプールではイレイジャーコーディングスキームを使用できません。
* ストレージプールに含まれるストレージノードとサイトの数によって、使用可能なノードとサイトが決まりますlink:what-erasure-coding-schemes-are.html["イレイジャーコーディングスキーム"]。
* 可能であれば、選択するイレイジャーコーディングスキームに必要な最小数よりも多くのストレージノードをストレージプールに含めてください。たとえば、 6+3 のイレイジャーコーディングスキームを使用する場合は、 9 個以上のストレージノードが必要です。ただし、サイトごとに少なくとも 1 つのストレージノードを追加することを推奨します。
* ストレージノードはサイト間にできるだけ均等に分散します。たとえば、 6+3 のイレイジャーコーディングスキームをサポートするには、 3 つのサイトにそれぞれ 1 つ以上のストレージノードを含むストレージプールを設定します。
* スループット要件が高い場合、サイト間のネットワークレイテンシが100ミリ秒を超える場合は、複数のサイトを含むストレージプールを使用することは推奨されません。レイテンシが上昇すると TCP ネットワークのスループットが低下するため、 StorageGRID がオブジェクトフラグメントを作成、配置、読み出す速度は大幅に低下します。
+
スループットの低下は、達成可能なオブジェクトの最大取り込み速度と読み出し速度に影響するか（取り込み動作として[Balanced]または[Strict]が選択されている場合）、ILMキューのバックログが発生する可能性があります（取り込み動作として[Dual commit]が選択されている場合）。を参照して link:what-ilm-rule-is.html#ilm-rule-ingest-behavior["ILMルールの取り込み動作"]

+

NOTE: グリッドにサイトが1つしかない場合は、イレイジャーコーディングプロファイルでAll Storage Nodesストレージプール（StorageGRID 11.6以前）またはAll Sitesサイトを使用できません。これにより、2つ目のサイトが追加された場合にプロファイルが無効になるのを防ぐことができます。


