---
permalink: ilm/index.html 
sidebar: sidebar 
keywords: information lifecycle management overview, about information lifecycle management, ilm overview, about ilm 
summary: ILMポリシーの情報ライフサイクル管理（ILM\）ルールは、オブジェクトデータのコピーを作成および分散し、それらのコピーを一定の期間にわたって管理する方法をStorageGRIDに指示します。 
---
= ILM を使用してオブジェクトを管理する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ILMポリシーの情報ライフサイクル管理（ILM）ルールは、オブジェクトデータのコピーを作成および分散する方法と、それらのコピーを一定の期間にわたって管理する方法をStorageGRIDに指示します。



== これらの手順について

ILMルールとポリシーを設計、実装するには慎重な計画が必要です。運用要件、 StorageGRID システムのトポロジ、オブジェクト保護のニーズ、使用可能なストレージタイプについて理解しておく必要があります。次に、さまざまなタイプのオブジェクトをどのようにコピー、分散、および格納するかを決定する必要があります。

次の手順に従って、次の操作を行います

* を含むStorageGRID ILMについて説明します。link:how-ilm-operates-throughout-objects-life.html["オブジェクトのライフサイクル全体にわたるILMの動作"]
* link:what-storage-pool-is.html["ストレージプール"]、link:what-cloud-storage-pool-is.html["クラウドストレージプール"]、を構成する方法について説明します。link:what-ilm-rule-is.html["ILM ルール"]
* これで1つ以上のサイトのオブジェクトデータを保護する方法について説明します。link:creating-ilm-policy.html["ILMポリシーを作成、シミュレート、アクティブ化します"]
* link:managing-objects-with-s3-object-lock.html["S3オブジェクトロックを使用してオブジェクトを管理します"]特定のS3バケット内のオブジェクトが指定した期間削除または上書きされないようにする方法について説明します。




== 詳細

詳細については、次のビデオをご覧ください。

.ILMルールの概要
video::9872d38f-80b3-4ad4-9f79-b1ff008760c7[panopto]
.ILMポリシーの概要
video::e768d4da-da88-413c-bbaa-b1ff00874d10[panopto]