---
permalink: ilm/lifecycle-of-cloud-storage-pool-object.html 
sidebar: sidebar 
keywords: lifecycle of cloud storage pool object 
summary: クラウドストレージプールを実装する前に、クラウドストレージプールのタイプごとに格納されているオブジェクトのライフサイクルを確認してください。 
---
= StorageGRID におけるクラウドストレージプールオブジェクトのライフサイクル
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラウドストレージプールを実装する前に、クラウドストレージプールのタイプごとに格納されているオブジェクトのライフサイクルを確認してください。



[[s3-lifecycle-of-a-cloud-storage-pool-object]]
== S3 ：クラウドストレージプールオブジェクトのライフサイクル

S3クラウドストレージプールに格納されるオブジェクトのライフサイクルステージについて説明します。


NOTE: 「Glacier」は、GlacierストレージクラスとGlacier Deep Archiveストレージクラスの両方を表します。例外が1つあります。Glacier Deep Archiveストレージクラスでは、Expeditedリストア階層はサポートされません。Bulk または Standard のみがサポートされます。


NOTE: Google Cloud Platform （ GCP ）では、 POST Restore 処理を実行しなくても、長期保存からのオブジェクトの読み出しがサポートされます。

. * StorageGRID * に格納されているオブジェクト
+
ライフサイクルを開始するために、クライアントアプリケーションがオブジェクトを StorageGRID に格納します。

. * オブジェクトを S3 クラウドストレージプールに移動 *
+
** S3 クラウドストレージプールを配置場所として使用する ILM ルールにオブジェクトが一致した場合、 StorageGRID はクラウドストレージプールで指定された外部の S3 バケットにオブジェクトを移動します。
** オブジェクトがS3クラウドストレージプールに移動されると、クライアントアプリケーションは、オブジェクトがGlacierストレージに移行されていないかぎり、StorageGRIDからS3 GetObject要求を使用してオブジェクトを読み出すことができます。


. * オブジェクトを Glacier に移行（読み出し不可の状態） *
+
** 必要に応じて、オブジェクトを Glacier ストレージに移行できます。たとえば外部の S3 バケットが、ライフサイクル設定を使用してオブジェクトを即座または数日後に Glacier ストレージに移行できます。
+

NOTE: オブジェクトを移行する場合は、外部のS3バケットのライフサイクル設定を作成する必要があります。また、Glacierストレージクラスを実装し、S3 RestoreObject APIをサポートするストレージ解決策を使用する必要があります。

** 移行中、クライアントアプリケーションはS3 HeadObject要求を使用してオブジェクトのステータスを監視できます。


. * Glacier ストレージからオブジェクトをリストア *
+
オブジェクトがGlacierストレージに移行されている場合、クライアントアプリケーションはS3 RestoreObject要求を問題して、読み出し可能なコピーをS3クラウドストレージプールにリストアできます。要求では、クラウドストレージプールでコピーを利用できる日数と、リストア処理に使用するデータアクセス階層（ Expedited 、 Standard 、 Bulk ）を指定します。読み出し可能なコピーの有効期限に達すると、コピーは自動的に読み出し不可能な状態に戻ります。

+

NOTE: StorageGRID内のストレージノードにもオブジェクトのコピーが存在する場合は、RestoreObject要求を実行してGlacierからオブジェクトをリストアする必要はありません。代わりに、GetObject要求を使用してローカルコピーを直接取得できます。

. * オブジェクトが取得されました *
+
オブジェクトがリストアされると、クライアントアプリケーションはGetObject要求を問題して、リストアされたオブジェクトを読み出すことができます。





[[azure-lifecycle-of-a-cloud-storage-pool-object]]
== Azure ：クラウドストレージプールオブジェクトのライフサイクル

Azureクラウドストレージプールに格納されるオブジェクトのライフサイクルステージについて説明します。

. * StorageGRID * に格納されているオブジェクト
+
ライフサイクルを開始するために、クライアントアプリケーションがオブジェクトを StorageGRID に格納します。

. * オブジェクトを Azure クラウドストレージプールに移動 *
+
オブジェクトが、配置場所として Azure クラウド ストレージ プールを使用する ILM ルールに一致する場合、StorageGRID はオブジェクトを、クラウド ストレージ プールで指定された外部の Azure Blob Storage コンテナーに移動します。

. * オブジェクトをアーカイブ層に移行（読み出し不可の状態） *
+
オブジェクトを Azure クラウド ストレージ プールに移動した直後、StorageGRID はオブジェクトを自動的に Azure Blob Storage アーカイブ層に移行します。

. * アーカイブ層からオブジェクトを復元 *
+
オブジェクトがアーカイブ層に移行されている場合、クライアントアプリケーションはS3 RestoreObject要求を問題して、読み出し可能なコピーをAzureクラウドストレージプールにリストアできます。

+
StorageGRID が RestoreObject を受信すると、オブジェクトは一時的に Azure Blob Storage Cool ティアに移行されます。RestoreObject リクエストの有効期限に達すると、StorageGRID はオブジェクトをアーカイブ階層に戻します。

+

NOTE: StorageGRID内のストレージノードにもオブジェクトのコピーが1つ以上存在する場合は、RestoreObject要求を実行してアーカイブアクセス層からオブジェクトをリストアする必要はありません。代わりに、GetObject要求を使用してローカルコピーを直接取得できます。

. * オブジェクトが取得されました *
+
オブジェクトがAzureクラウドストレージプールにリストアされると、クライアントアプリケーションはGetObject要求を問題して、リストアされたオブジェクトを読み出すことができます。



.関連情報
link:../s3/index.html["S3 REST APIを使用する"]
