---
permalink: ilm/manage-ilm-policy-tags.html 
sidebar: sidebar 
keywords: ILM policy tag 
summary: ILMポリシータグの詳細を表示したり、タグを編集したり、タグを削除したりできます。 
---
= ILMポリシータグを管理します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ILMポリシータグの詳細を表示したり、タグを編集したり、タグを削除したりできます。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたはを持っていますlink:../admin/admin-group-permissions.html["必要なアクセス権限"]。




== ILMポリシータグの詳細の表示

タグの詳細を表示するには：

. [ILM]*>*[Policy tags]*を選択します。
. テーブルからポリシーの名前を選択します。タグの詳細ページが表示されます。
. 詳細ページで、割り当てられたポリシーの過去の履歴を表示します。
. ポリシーを選択して表示します。




== ILMポリシータグを編集


NOTE: タグの名前と説明はテナントに表示されます。バケットに割り当てるポリシータグをテナントが選択する際に十分な情報に基づいて決定するのに役立つ値を選択してください。たとえば、割り当てられているポリシーによって一定の期間が経過したあとにオブジェクトが削除される場合は、概要でその旨を通知できます。これらのフィールドには機密情報を含めないでください。

既存のタグの概要を編集するには、次の手順を実行します。

. [ILM]*>*[Policy tags]*を選択します。
. タグのチェックボックスをオンにして、*[編集]*を選択します。
+
または、タグの名前を選択します。タグの詳細ページが表示され、そのページで*編集*を選択できます。

. 必要に応じてタグ概要を変更します。
. [ 保存（ Save ） ] を選択します。




== ILMポリシータグを削除します。

ポリシータグを削除すると、そのタグが割り当てられているバケットにはデフォルトのポリシーが適用されます。

タグを削除するには：

. [ILM]*>*[Policy tags]*を選択します。
. タグのチェックボックスをオンにして、*[削除]*を選択します。確認のダイアログボックスが表示されます。
+
または、タグの名前を選択します。タグの詳細ページが表示され、そのページで*[削除]*を選択できます。

. [はい]*を選択してタグを削除します。


.関連情報
link:creating-ilm-policy.html#activate-ilm-policy["ILMポリシータグの作成について学ぶ"]
