---
permalink: ilm/managing-objects-with-s3-object-lock.html 
sidebar: sidebar 
keywords: s3 object lock, manage objects with object lock 
summary: グリッド管理者は、 StorageGRID システムで S3 オブジェクトロックを有効にし、準拠 ILM ポリシーを実装して、特定の S3 バケット内のオブジェクトが指定した期間にわたって削除または上書きされないようにすることができます。 
---
= S3 オブジェクトロックでオブジェクトを管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッド管理者は、StorageGRID システムでS3オブジェクトロックを有効にし、準拠ILMポリシーを実装して、特定のS3バケット内のオブジェクトが一定期間削除または上書きされないようにすることができます。



== S3 オブジェクトのロックとは何ですか？

StorageGRID S3 オブジェクトロック機能は、 Amazon Simple Storage Service （ Amazon S3 ）での S3 オブジェクトロックに相当するオブジェクト保護解決策 です。

StorageGRIDシステムでS3オブジェクトロックのグローバル設定が有効になっている場合、S3テナントアカウントはS3オブジェクトロックを有効にしても有効にしなくてもバケットを作成できます。バケットでS3オブジェクトロックが有効になっている場合は、バケットのバージョン管理が必要であり、自動的に有効になります。

* S3オブジェクトロック*が設定されていないバケットには、保持設定が指定されていないオブジェクトのみを含めることができます。保持設定は取り込まれたオブジェクトには適用されません。

* S3 Object Lock *が設定されたバケットには、S3クライアントアプリケーションで保持設定の有無に関係なくオブジェクトを含めることができます。取り込まれた一部のオブジェクトには保持設定が設定されます。

* S3オブジェクトロックでデフォルトの保持が設定されたバケット*では、保持設定を指定したオブジェクトをアップロードし、保持設定を指定せずに新しいオブジェクトをアップロードできます。保持設定がオブジェクトレベルで設定されていないため、新しいオブジェクトではデフォルト設定が使用されます。

デフォルトの保持が設定されている場合、新しく取り込まれたすべてのオブジェクトに保持設定が適用されます。オブジェクト保持設定のない既存のオブジェクトは影響を受けません。



=== 保持モード

StorageGRID S3オブジェクトロック機能は、2つの保持モードをサポートしており、さまざまなレベルの保護をオブジェクトに適用できます。これらのモードは、Amazon S3の保持モードに相当します。

* コンプライアンスモードの場合：
+
** retain-until-dateに達するまで、オブジェクトを削除できません。
** オブジェクトのretain-until-dateは増やすことはできますが、減らすことはできません。
** オブジェクトのretain-until-dateは、その日付に達するまで削除できません。


* ガバナンスモードの場合：
+
** 特別な権限を持つユーザは、要求でバイパスヘッダーを使用して、特定の保持設定を変更できます。
** これらのユーザは、retain-until-dateに達する前にオブジェクトバージョンを削除できます。
** これらのユーザは、オブジェクトのretain-until-dateを増減、または削除できます。






=== オブジェクトバージョンの保持設定

S3オブジェクトロックを有効にしてバケットを作成した場合、ユーザはS3クライアントアプリケーションを使用して、バケットに追加される各オブジェクトに次の保持設定を必要に応じて指定できます。

* *保持モード*：コンプライアンスまたはガバナンスのいずれか。
* * Retain-until-date *：オブジェクトバージョンのretain-until-dateが将来の日付の場合、オブジェクトは読み出すことはできますが、削除することはできません。
* * リーガルホールド * ：オブジェクトバージョンにリーガルホールドを適用すると、そのオブジェクトがただちにロックされます。たとえば、調査または法的紛争に関連するオブジェクトにリーガルホールドを設定する必要がある場合があります。リーガルホールドには有効期限はありませんが、明示的に削除されるまで保持されます。リーガルホールドは、それまでの保持期間とは関係ありません。
+

NOTE: オブジェクトがリーガルホールドの対象である場合、保持モードに関係なく、誰もオブジェクトを削除できません。

+
オブジェクト設定の詳細については、を参照してくださいlink:../s3/use-s3-api-for-s3-object-lock.html["S3 REST APIを使用してS3オブジェクトロックを設定します"]。





=== バケットのデフォルトの保持設定

S3オブジェクトロックを有効にしてバケットを作成した場合は、必要に応じて次のバケットのデフォルト設定を指定できます。

* *デフォルトの保持モード*：コンプライアンスまたはガバナンスのいずれか。
* *デフォルトの保持期間*：このバケットに追加された新しいオブジェクトバージョンを、追加された日から保持する期間。


デフォルトのバケット設定は、独自の保持設定がない新しいオブジェクトにのみ適用されます。これらのデフォルト設定を追加または変更しても、既存のバケットオブジェクトには影響しません。

およびを参照してくださいlink:../tenant/creating-s3-bucket.html["S3 バケットを作成します。"]link:../tenant/update-default-retention-settings.html["S3オブジェクトロックのデフォルトの保持期間を更新します"]。



== S3 オブジェクトロックと従来の準拠の比較

S3 オブジェクトロックは、以前のバージョンの StorageGRID で使用されていた準拠機能に代わる機能です。S3オブジェクトロック機能はAmazon S3の要件に準拠しているため、独自のStorageGRIDコンプライアンス機能（現在は「レガシーコンプライアンス」と呼ばれています）は廃止されました。


NOTE: グローバル準拠設定は廃止されました。以前のバージョンのStorageGRID を使用してこの設定を有効にした場合、S3オブジェクトロック設定は自動的に有効になります。既存の準拠バケットの設定は引き続きStorageGRID を使用して管理できますが、新しい準拠バケットを作成することはできません。詳細については、を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["ネットアップのナレッジベース： StorageGRID 11.5 でレガシー準拠バケットを管理する方法"^]。

以前のバージョンの StorageGRID で従来の準拠機能を使用していた場合、次の表を参照して、 StorageGRID の S3 オブジェクトロック機能と比較する方法を確認してください。

[cols="1a,1a,1a"]
|===
|  | S3 オブジェクトのロック | コンプライアンス（レガシー） 


 a| 
この機能はグローバルにどのように有効になりますか。
 a| 
Grid Manager から * configuration * > * System * > * S3 Object Lock * を選択します。
 a| 
サポートは終了しました。



 a| 
バケットで機能を有効にするにはどうすればよいですか？
 a| 
Tenant Manager 、テナント管理 API 、または S3 REST API を使用して新しいバケットを作成するときは、 S3 オブジェクトロックを有効にする必要があります。
 a| 
サポートは終了しました。



 a| 
バケットのバージョン管理はサポートされているか
 a| 
はい。バケットのバージョン管理は必須であり、バケットで S3 オブジェクトのロックが有効になっている場合は自動的に有効になります。
 a| 
いいえ。



 a| 
オブジェクト保持はどのように設定されますか。
 a| 
retain-until-dateはオブジェクトバージョンごとに設定することも、バケットごとにデフォルトの保持期間を設定することもできます。
 a| 
ユーザはバケット全体の保持期間を設定する必要があります。保持期間を指定すると、バケット内のすべてのオブジェクトが環境 で保持されます。



 a| 
保持期間は変更できますか。
 a| 
* コンプライアンスモードでは、オブジェクトバージョンのretain-until-dateは増やすことができますが、減らすことはできません。
* ガバナンスモードでは、特別な権限を持つユーザは、オブジェクトの保持設定を変更したり削除したりできます。

 a| 
バケットの保持期間は延長できますが、短縮することはできません。



 a| 
リーガルホールドはどこで制御されますか？
 a| 
バケット内のオブジェクトバージョンにリーガルホールドを適用したり、リーガルホールドを解除したりできます。
 a| 
リーガルホールドはバケットに適用され、バケット内のすべてのオブジェクトに適用されます。



 a| 
オブジェクトを削除できるのはいつですか。
 a| 
* 準拠モードでは、オブジェクトがリーガルホールドの対象でない場合、retain-until-dateに達したあとにオブジェクトバージョンを削除できます。
* ガバナンスモードでは、特別な権限を持つユーザは、オブジェクトがリーガルホールドの対象でない場合、retain-until-dateに達する前にオブジェクトを削除できます。

 a| 
バケットがリーガルホールドの対象でない場合は、保持期間が過ぎたあとにオブジェクトを削除できます。オブジェクトは自動または手動で削除できます。



 a| 
バケットライフサイクル設定はサポートされていますか。
 a| 
はい
 a| 
いいえ

|===