---
permalink: ilm/removing-cloud-storage-pool.html 
sidebar: sidebar 
keywords: remove cloud storage pool 
summary: ILMルールで使用されておらず、オブジェクトデータが含まれていないクラウドストレージプールは削除できます。 
---
= クラウドストレージプールを削除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ILMルールで使用されておらず、オブジェクトデータが含まれていないクラウドストレージプールは削除できます。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたはを持っていますlink:../admin/admin-group-permissions.html["必要なアクセス権限"]。




== 必要に応じて、ILMを使用してオブジェクトデータを移動します

削除するクラウドストレージプールにオブジェクトデータが含まれている場合は、ILMを使用してデータを別の場所に移動する必要があります。たとえば、グリッド上のストレージノードや別のクラウドストレージプールにデータを移動できます。

.手順
. ILM *>* Storage pools *>* Cloud Storage Pools *を選択します。
. テーブルの[ILM usage]列で、クラウドストレージプールを削除できるかどうかを確認します。
+
ILMルールまたはイレイジャーコーディングプロファイルで使用されているクラウドストレージプールは削除できません。

. クラウドストレージプールを使用している場合は、*_ cloud storage pool name_*>* ILM usage *を選択します。
. link:working-with-ilm-rules-and-ilm-policies.html["各ILMルールをクローニングします"]削除するクラウドストレージプールにオブジェクトが現在配置されています。
. クローニングした各ルールで管理されている既存のオブジェクトの移動先を決定します。
+
1つ以上のストレージプール、または別のクラウドストレージプールを使用できます。

. クローニングした各ルールを編集します。
+
Create ILM Ruleウィザードのステップ2で、* Copies at *フィールドから新しい場所を選択します。

. link:creating-ilm-policy.html["新しいILMポリシーを作成する"]古いルールを複製したルールに置き換えます。
. 新しいポリシーをアクティブ化します。
. ILMによってクラウドストレージプールからオブジェクトが削除され、新しい場所に配置されるまで待ちます。




== クラウドストレージプールを削除

クラウドストレージプールが空でILMルールで使用されていない場合は削除できます。

.開始する前に
* プールを使用している可能性があるILMルールを削除しておきます。
* S3 バケットまたは Azure コンテナにオブジェクトが含まれていないことを確認します。
+
クラウドストレージプールにオブジェクトが含まれている場合、そのストレージプールを削除しようとするとエラーが発生します。を参照して link:troubleshooting-cloud-storage-pools.html["クラウドストレージプールのトラブルシューティング"]

+

NOTE: クラウドストレージプールを作成すると、 StorageGRID はバケットまたはコンテナにマーカーファイルを書き込み、クラウドストレージプールとして識別します。という名前のファイルは削除しないで `x-ntap-sgws-cloud-pool-uuid`ください。



.手順
. ILM *>* Storage pools *>* Cloud Storage Pools *を選択します。
. [ILM usage]列にクラウドストレージプールが使用されていないことが示されている場合は、チェックボックスをオンにします。
. * アクション * > * 削除 * を選択します。
. 「* OK *」を選択します。

