---
permalink: ilm/requirements-for-s3-object-lock.html 
sidebar: sidebar 
keywords: requirements, s3 object lock, compliant ilm rule, compliant ilm policy 
summary: グローバルな S3 オブジェクトのロック設定を有効にするための要件、準拠 ILM ルールおよび ILM ポリシーを作成するための要件、および StorageGRID が S3 オブジェクトロックを使用するバケットとオブジェクトに適用する制限事項を確認しておく必要があります。 
---
= S3 オブジェクトのロックの要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グローバルな S3 オブジェクトのロック設定を有効にするための要件、準拠 ILM ルールおよび ILM ポリシーを作成するための要件、および StorageGRID が S3 オブジェクトロックを使用するバケットとオブジェクトに適用する制限事項を確認しておく必要があります。



== グローバルな S3 オブジェクトロック設定を使用するための要件

* S3 テナントが S3 オブジェクトロックを有効にしてバケットを作成できるようにするには、 Grid Manager またはグリッド管理 API を使用してグローバルな S3 オブジェクトロック設定を有効にする必要があります。
* グローバルな S3 オブジェクトのロック設定を有効にすると、すべての S3 テナントアカウントで S3 オブジェクトのロックを有効にしてバケットを作成できるようになります。
* S3オブジェクトロックのグローバル設定を有効にしたあとで、設定を無効にすることはできません。
* すべてのアクティブなILMポリシーのデフォルトルールが_compliant_である（つまり、デフォルトルールはS3 Object Lockが有効なバケットの要件に準拠している必要がある）場合を除き、グローバルS3オブジェクトロックを有効にすることはできません。
* S3オブジェクトロックのグローバル設定が有効になっている場合は、ポリシーのデフォルトルールが準拠していないかぎり、新しいILMポリシーを作成したり既存のILMポリシーをアクティブ化したりすることはできません。グローバルなS3オブジェクトロック設定が有効になると、ILMルールとILMポリシーのページに、どのILMルールが準拠しているかが表示されます。




== 準拠 ILM ルールの要件

S3オブジェクトロックのグローバル設定を有効にする場合は、すべてのアクティブなILMポリシーのデフォルトルールが準拠していることを確認する必要があります。準拠ルールは、 S3 オブジェクトのロックが有効になっているバケットと従来の準拠が有効になっている既存のバケットの両方の要件を満たします。

* 2 つ以上のレプリケートオブジェクトコピーまたは 1 つのイレイジャーコーディングコピーを作成する。
* これらのコピーが、配置手順の各ラインの間、ストレージノード上に存在している必要があります。
* オブジェクトコピーをクラウドストレージプールに保存することはできません。
* 配置手順の少なくとも1行は、参照時間として*取り込み時間*を使用して、0日目から開始する必要があります。
* 配置手順の少なくとも1行は「forever」にする必要があります。




== ILMポリシーの要件

グローバルなS3オブジェクトロック設定が有効になっている場合は、アクティブと非アクティブのILMポリシーに準拠ルールと非準拠ルールの両方を含めることができます。

* アクティブまたは非アクティブのILMポリシーのデフォルトルールは準拠ルールである必要があります。
* 非準拠ルールは、S3オブジェクトロックが有効になっていないバケット内のオブジェクト、または従来の準拠機能が有効になっていないバケット内のオブジェクトにのみ適用されます。
* 準拠ルールは任意のバケット内のオブジェクトに適用できます。 S3 オブジェクトのロックや従来の準拠を有効にする必要はありません。


link:example-7-compliant-ilm-policy-for-s3-object-lock.html["S3オブジェクトロックの準拠ILMポリシーの例"]



== S3 オブジェクトのロックを有効にした場合のバケットの要件

* StorageGRID システムでグローバルな S3 オブジェクトロック設定が有効になっている場合は、テナントマネージャ、テナント管理 API 、または S3 REST API を使用して、 S3 オブジェクトロックを有効にしたバケットを作成できます。
* S3 オブジェクトのロックを使用する場合は、バケットの作成時に S3 オブジェクトのロックを有効にする必要があります。既存のバケットでS3オブジェクトロックを有効にすることはできません。
* バケットで S3 オブジェクトのロックが有効になっている場合は、そのバケットのバージョン管理が StorageGRID で自動的に有効になります。バケットのS3オブジェクトロックを無効にしたり、バージョン管理を一時停止したりすることはできません。
* 必要に応じて、Tenant Manager、テナント管理API、またはS3 REST APIを使用して、各バケットのデフォルトの保持モードと保持期間を指定できます。バケットのデフォルトの保持設定は、バケットに追加された新しいオブジェクトのうち、独自の保持設定がないオブジェクトにのみ適用されます。これらのデフォルト設定は、アップロード時にオブジェクトバージョンごとに保持モードとretain-until-dateを指定することで上書きできます。
* バケットライフサイクル設定は、S3オブジェクトロックが有効なバケットでサポートされます。
* CloudMirror レプリケーションは、 S3 オブジェクトロックが有効になっているバケットではサポートされません。




== S3 オブジェクトのロックが有効になっているバケット内のオブジェクトの要件

* オブジェクトバージョンを保護するには、バケットのデフォルトの保持設定を指定するか、オブジェクトバージョンごとに保持設定を指定します。オブジェクトレベルの保持設定は、S3クライアントアプリケーションまたはS3 REST APIを使用して指定できます。
* 保持設定はオブジェクトのバージョンごとに適用されます。オブジェクトバージョンには、 retain-until date 設定とリーガルホールド設定の両方を設定できます。ただし、オブジェクトバージョンを保持することはできません。また、どちらも保持することはできません。オブジェクトの retain-une-date 設定またはリーガルホールド設定を指定すると、要求で指定されたバージョンのみが保護されます。オブジェクトの以前のバージョンはロックされたまま、オブジェクトの新しいバージョンを作成できます。




== S3 オブジェクトのロックが有効なバケット内のオブジェクトのライフサイクル

S3オブジェクトロックが有効なバケットに保存された各オブジェクトは、次の段階を経ます。

. * オブジェクトの取り込み *
+
S3オブジェクトロックが有効になっているバケットにオブジェクトバージョンを追加すると、保持設定は次のように適用されます。

+
** オブジェクトに保持設定が指定されている場合は、オブジェクトレベルの設定が適用されます。デフォルトのバケット設定は無視されます。
** オブジェクトに保持設定が指定されていない場合は、デフォルトのバケット設定が適用されます（存在する場合）。
** オブジェクトまたはバケットに保持設定が指定されていない場合、オブジェクトはS3オブジェクトロックによって保護されません。


+
保持設定が適用されている場合は、オブジェクトとS3ユーザ定義メタデータの両方が保護されます。

. *オブジェクトの保持と削除*
+
指定した保持期間中、各保護オブジェクトの複数のコピーがStorageGRID によって格納されます。オブジェクトコピーの正確な数、タイプ、格納場所は、アクティブなILMポリシーの準拠ルールによって決まります。retain-until-dateに達する前に保護オブジェクトを削除できるかどうかは、保持モードによって異なります。

+
** オブジェクトがリーガルホールドの対象である場合、保持モードに関係なく、誰もオブジェクトを削除できません。




.関連情報
* link:../tenant/creating-s3-bucket.html["S3 バケットを作成します。"]
* link:../tenant/update-default-retention-settings.html["S3オブジェクトロックのデフォルトの保持期間を更新します"]
* link:../s3/use-s3-api-for-s3-object-lock.html["S3 REST APIを使用してS3オブジェクトロックを設定します"]
* link:example-7-compliant-ilm-policy-for-s3-object-lock.html["例 7 ： S3 オブジェクトロックの準拠 ILM ポリシー"]

