---
permalink: ilm/troubleshooting-cloud-storage-pools.html 
sidebar: sidebar 
keywords: cloud storage pool, troubleshoot 
summary: 以下のトラブルシューティング手順を使用して、クラウドストレージプールを作成、編集、または削除するときに発生する可能性があるエラーを解決します。 
---
= クラウドストレージプールのトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
以下のトラブルシューティング手順を使用して、クラウドストレージプールを作成、編集、または削除するときに発生する可能性があるエラーを解決します。



== エラーが発生したかどうかを確認します

StorageGRIDは、既知のオブジェクトを読み取り、すべてのクラウドストレージプールで簡単な健全性チェックを実行して、 `x-ntap-sgws-cloud-pool-uuid`クラウドストレージプールにアクセスできることと、正常に機能していることを確認します。エンドポイントでエラーが発生すると、StorageGRIDは各ストレージノードから1分ごとに健全性チェックを実行します。エラーが解決されると、健全性チェックは停止します。健全性チェックで問題が検出されると、[Storage pools]ページの[Cloud Storage Pools]テーブルの[Last error]列にメッセージが表示されます。

次の表は、各クラウドストレージプールで検出された最新のエラーと、エラーが発生してからの時間を示しています。

また、過去 5 分以内に新しいクラウドストレージプールのエラーが発生したことが健全性チェックで検出されると、 * クラウドストレージプール接続エラー * アラートがトリガーされます。このアラートのEメール通知を受信した場合は、[ストレージプール]ページ（* ILM *>* Storage pools *を選択）に移動し、[最後のエラー]列のエラーメッセージを確認して、以下のトラブルシューティングのガイドラインを参照してください。



== エラーが解決されたかどうかを確認します

エラーの原因となっている問題を解決したら、エラーが解決されたかどうかを確認できます。[クラウドストレージプール]ページで、エンドポイントを選択し、*[エラーのクリア]*を選択します。StorageGRID がクラウドストレージプールのエラーをクリアしたことを示す確認メッセージが表示されます。

原因となっている問題が解決されると、エラーメッセージは表示されなくなります。ただし、根本的な問題が解決されていない場合（または別のエラーが発生した場合）は、数分以内に[Last error]列にエラーメッセージが表示されます。



== エラー：健全性チェックに失敗しました。エンドポイントからのエラーです

このエラーは、Amazon S3バケットでこのバケットをクラウドストレージプールで使用し始めたあとに、Amazon S3バケットに対してデフォルトの保持期間でS3オブジェクトロックを有効にした場合に発生することがあります。このエラーは、PUT処理になどのペイロードチェックサム値を含むHTTPヘッダーがない場合に発生します `Content-MD5`。このヘッダー値は、S3 Object Lockが有効なバケットへのPUT処理でAWSが必要になります。

この問題を解決するには、変更を加えずにの手順を実行しlink:editing-cloud-storage-pool.html["クラウドストレージプールを編集します"]ます。このアクションにより、クラウドストレージプール構成の検証がトリガーされ、クラウドストレージプールエンドポイント構成のS3オブジェクトロックフラグが自動的に検出されて更新されます。



== エラー：このクラウドストレージプールには予期しないコンテンツが含まれています

クラウドストレージプールを作成、編集、または削除しようとすると、このエラーが発生する場合があります。このエラーは、バケットまたはコンテナにマーカーファイルが含まれているが、想定されるUUIDのメタデータフィールドがファイルにない場合に発生し `x-ntap-sgws-cloud-pool-uuid`ます。

通常、このエラーが表示されるのは、新しいクラウドストレージプールを作成していて、 StorageGRID の別のインスタンスがすでに同じクラウドストレージプールを使用している場合のみです。

この問題を解決するには、次のいずれかの手順を実行します。

* 新しいクラウドストレージプールを設定する場合に、次の例に示すように、ファイルと追加のオブジェクトキーがバケットに含まれている場合 `x-ntap-sgws-cloud-pool-uuid`は、新しいバケットを作成し、この新しいバケットを使用します。
+
追加のオブジェクトキーの例： `my-bucket.3E64CF2C-B74D-4B7D-AFE7-AD28BC18B2F6.1727326606730410`

* ファイルがバケット内の唯一のオブジェクトである場合 `x-ntap-sgws-cloud-pool-uuid`は、このファイルを削除します。


これらの手順がシナリオに当てはまらない場合は、サポートにお問い合わせください。



== エラー：クラウドストレージプールを作成または更新できませんでした。エンドポイントからのエラーです

このエラーは、次の状況で発生することがあります。

* クラウドストレージプールを作成または編集するとき。
* 新しいクラウドストレージプールの構成時に、サポートされていないプラットフォーム、認証、またはプロトコルの組み合わせをS3オブジェクトロックと選択した場合。を参照して link:../ilm/considerations-for-cloud-storage-pools.html["クラウドストレージプールに関する考慮事項"]


このエラーは、接続または構成の問題が原因でStorageGRIDがクラウドストレージプールに書き込めないことを示しています。

問題 を修正するには、エンドポイントからのエラーメッセージを確認します。

* エラーメッセージにが含まれている場合 `Get _url_: EOF`は、クラウドストレージプールに使用されるサービスエンドポイントで、HTTPSを必要とするコンテナまたはバケットにHTTPが使用されていないことを確認します。
* エラーメッセージにが含まれている場合は `Get _url_: net/http: request canceled while waiting for connection`、クラウドストレージプールに使用されるサービスエンドポイントへのストレージノードのアクセスがネットワーク構成で許可されていることを確認します。
* サポートされていないプラットフォーム、認証、またはプロトコルが原因でエラーが発生した場合は、S3オブジェクトロックを使用してサポートされている構成に変更し、新しいクラウドストレージプールをもう一度保存してください。
* その他のすべてのエンドポイントエラーメッセージについては、次のいずれか、または複数の操作を試してください。
+
** クラウドストレージプール用に入力した名前と同じ名前の外部コンテナまたはバケットを作成して、新しいクラウドストレージプールを再度保存します。
** クラウドストレージプール用に指定したコンテナまたはバケット名を修正して、新しいクラウドストレージプールを再度保存します。






== エラー： CA 証明書を解析できませんでした

クラウドストレージプールを作成または編集しようとすると、このエラーが発生する場合があります。このエラーは、クラウドストレージプールの設定時に入力した証明書を StorageGRID が解析できなかった場合に発生します。

問題 を修正するには、指定した CA 証明書に問題がないかどうかを確認します。



== エラー：この ID のクラウドストレージプールが見つかりませんでした

クラウドストレージプールを編集または削除しようとすると、このエラーが発生する場合があります。このエラーは、次のいずれかの理由でエンドポイントが 404 応答を返した場合に発生します。

* クラウドストレージプールに使用されるクレデンシャルにバケットの読み取り権限がありません。
* クラウドストレージプールに使用されるバケットにマーカーファイルが含まれてい `x-ntap-sgws-cloud-pool-uuid`ません。


問題 を修正するには、次の手順をいくつか実行します。

* 設定したアクセスキーに関連付けられているユーザに必要な権限があることを確認します。
* 必要な権限があるクレデンシャルを使用してクラウドストレージプールを編集します。
* 権限が正しい場合は、サポートにお問い合わせください。




== エラー：クラウドストレージプールの内容を確認できませんでした。エンドポイントからのエラーです

クラウドストレージプールを削除しようとすると、このエラーが発生する場合があります。このエラーは、何らかの接続または設定問題 が原因で、 StorageGRID がクラウドストレージプールバケットのコンテンツを読み取れないことを示しています。

問題 を修正するには、エンドポイントからのエラーメッセージを確認します。



== エラー： Objects have already been placed in this bucket

クラウドストレージプールを削除しようとすると、このエラーが発生する場合があります。ILMによって移動されたデータ、クラウドストレージプールの設定前にバケットにあったデータ、またはクラウドストレージプールの作成後に他のソースによってバケットに配置されたデータが含まれているクラウドストレージプールは削除できません。

問題 を修正するには、次の手順をいくつか実行します。

* 「クラウドストレージプールオブジェクトのライフサイクル」の手順に従って、オブジェクトをStorageGRIDに戻します。
* 残りのオブジェクトが ILM によってクラウドストレージプールに配置されていないことが確実な場合は、バケットからオブジェクトを手動で削除します。
+

NOTE: ILM によって配置された可能性のあるクラウドストレージプールからは、オブジェクトを手動で削除しないでください。手動で削除したオブジェクトにあとで StorageGRID からアクセスしようとしても、削除したオブジェクトは見つかりません。





== エラー：クラウドストレージプールにアクセスしようとして、プロキシで外部エラーが発生しました

このエラーは、ストレージノードとクラウドストレージプールに使用される外部のS3エンドポイントの間に非透過型ストレージプロキシを設定した場合に発生することがあります。このエラーは、外部プロキシサーバがCloud Storage Poolエンドポイントにアクセスできない場合に発生します。たとえば、 DNS サーバがホスト名を解決できない場合や、外部ネットワークの問題 が存在する場合があります。

問題 を修正するには、次の手順をいくつか実行します。

* クラウドストレージプール（ * ILM * > * ストレージプール * ）の設定を確認します。
* ストレージプロキシサーバのネットワーク設定を確認します。




== エラー：X.509証明書が有効期間外です

クラウドストレージプールを削除しようとすると、このエラーが発生する場合があります。このエラーは、クラウドストレージプール構成を削除する前に、正しい外部クラウドストレージプールが検証され、外部プールが空であることを確認するために、認証にX.509証明書が必要な場合に発生します。

問題 を修正するには、次の手順を実行します。

* 認証用に設定された証明書をクラウドストレージプールに更新します。
* このクラウドストレージプールに対する証明書の有効期限に関するアラートが解決されていることを確認してください。


.関連情報
link:lifecycle-of-cloud-storage-pool-object.html["クラウドストレージプールオブジェクトのライフサイクル"]
