---
permalink: ilm/using-last-access-time-in-ilm-rules.html 
sidebar: sidebar 
keywords: last access time, ilm rule reference time 
summary: 最終アクセス時間をILMルールの参照時間として使用できます。たとえば、過去 3 カ月間に表示されたオブジェクトをローカルストレージノードに残しておき、最近表示されていないオブジェクトをオフサイトの場所に移動することができます。特定の日付に最後にアクセスされたオブジェクトにのみILMルールを適用する場合は、最終アクセス時間を高度なフィルタとして使用することもできます。 
---
= ILMルールで最終アクセス時間を使用
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
最終アクセス時間をILMルールの参照時間として使用できます。たとえば、過去 3 カ月間に表示されたオブジェクトをローカルストレージノードに残しておき、最近表示されていないオブジェクトをオフサイトの場所に移動することができます。特定の日付に最後にアクセスされたオブジェクトにのみILMルールを適用する場合は、最終アクセス時間を高度なフィルタとして使用することもできます。

.タスクの内容
ILMルールで最終アクセス時間を使用する前に、次の考慮事項を確認してください。

* 参照時間として最終アクセス時間を使用する場合は、オブジェクトの最終アクセス時間を変更してもILM評価はすぐにはトリガーされないことに注意してください。オブジェクトの配置が評価され、バックグラウンド ILM がオブジェクトを評価したときに必要に応じてオブジェクトが移動されます。この処理には、オブジェクトがアクセスされてから 2 週間以上かかる場合があります。
+
最終アクセス時間に基づいてILMルールを作成する場合は、このレイテンシを考慮し、短期間（1カ月未満）を使用する配置は避けてください。

* 高度なフィルタまたは参照時間として最終アクセス時間を使用する場合は、S3バケットに対して最終アクセス時間の更新を有効にする必要があります。またはを使用できますlink:../tenant/enabling-or-disabling-last-access-time-updates.html["テナントマネージャ"]link:../s3/put-bucket-last-access-time-request.html["テナント管理 API"]。
+

NOTE: 最終アクセス時間の更新は、S3バケットに対してはデフォルトで無効になっています。

+

NOTE: 最終アクセス時間の更新を有効にすると、特に小さなオブジェクトを含むシステムのパフォーマンスが低下する可能性があります。これは、オブジェクトが読み出されるたびに StorageGRID が新しいタイムスタンプでオブジェクトを更新する必要があるためです。



次の表に、バケット内のすべてのオブジェクトについて、最終アクセス時間が更新されるかどうかを要求のタイプ別にまとめます。

[cols="1a,1a,1a"]
|===
| 要求のタイプ | 最終アクセス時間の更新が無効になっている場合に最終アクセス時間を更新するかどうか | 最終アクセス時間の更新が有効になっている場合に最終アクセス時間を更新するかどうか 


 a| 
オブジェクト、そのアクセス制御リスト、またはメタデータの読み出し要求
 a| 
いいえ
 a| 
はい



 a| 
オブジェクトメタデータの更新要求
 a| 
はい
 a| 
はい



 a| 
バケット間でのオブジェクトのコピー要求
 a| 
* ソースコピーに対しては、「いいえ」と指定します
* デスティネーションコピーについては、はい

 a| 
* ソースコピーについては、はい
* デスティネーションコピーについては、はい




 a| 
マルチパートアップロードの完了要求
 a| 
はい、アセンブルされたオブジェクトの場合
 a| 
はい、アセンブルされたオブジェクトの場合

|===