---
permalink: ilm/viewing-storage-pool-details.html 
sidebar: sidebar 
keywords: storage pool, view details 
summary: ストレージプールの詳細を表示して、ストレージプールの使用場所を確認したり、含まれているノードやストレージグレードを確認したりできます。 
---
= ストレージプールの詳細を表示します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージプールの詳細を表示して、ストレージプールの使用場所を確認したり、含まれているノードやストレージグレードを確認したりできます。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* そうだな link:../admin/admin-group-permissions.html["特定のアクセス権限"]


.手順
. ILM * > * Storage pools * を選択します
+
[Storage Pools]テーブルには、ストレージノードを含む各ストレージプールに関する次の情報が表示されます。

+
** * Name * ：ストレージプールの一意の表示名。
** *ノード数*：ストレージプール内のノードの数。
** *ストレージ使用量*：このノードでオブジェクトデータに使用されている合計使用可能スペースの割合。この値にはオブジェクトメタデータは含まれません。
** *合計容量*：ストレージプールのサイズ。ストレージプール内のすべてのノードでオブジェクトデータに使用可能なスペースの合計に相当します。
** * ILM usage *：ストレージプールの現在の使用状況。ストレージプールは、使用されていない場合や、1つ以上のILMルール、イレイジャーコーディングプロファイル、またはその両方で使用されている場合があります。


. 特定のストレージプールの詳細を表示するには、そのストレージプールの名前を選択します。
+
ストレージプールの詳細ページが表示されます。

. ストレージプールに含まれるストレージノードの詳細については、*[ノード]*タブを表示します。
+
この表には、ノードごとに次の情報が記載されています。

+
** ノード名
** サイト名
** ストレージグレード
** Storage usage：オブジェクトデータに使用可能な合計スペースのうち、ストレージノードで使用されているスペースの割合。
+

NOTE: 同じストレージ使用量 (%) の値は、各ストレージ ノードの「使用済みストレージ - オブジェクト データ」チャートにも表示されます ([ノード] > [ストレージ ノード] > [ストレージ] を選択)。



. ストレージプールがILMルールまたはイレイジャーコーディングプロファイルで現在使用されているかどうかを確認するには、*[ILM usage（ILM使用状況）]*タブを表示します。
. 必要に応じて、*[ILM rules]ページ*に移動し、ストレージプールを使用するルールの詳細と管理を確認します。
+
を参照してくださいlink:working-with-ilm-rules-and-ilm-policies.html["ILMルールの操作手順"]。


