---
permalink: ilm/what-erasure-coding-schemes-are.html 
sidebar: sidebar 
keywords: erasure-coding scheme 
summary: イレイジャーコーディングスキームは、各オブジェクト用に作成されるデータフラグメントとパリティフラグメントの数を制御します。 
---
= イレイジャーコーディングスキームとは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
イレイジャーコーディングスキームは、各オブジェクト用に作成されるデータフラグメントとパリティフラグメントの数を制御します。

ILMルールを作成または編集するときに、使用可能なイレイジャーコーディングスキームを選択します。StorageGRIDでは、使用するストレージプールを構成するストレージノードとサイトの数に基づいて、イレイジャーコーディングスキームが自動的に作成されます。



== データ保護

StorageGRID システムは、 Reed-Solomon イレイジャーコーディングアルゴリズムを使用します。このアルゴリズムは、オブジェクトを複数のデータフラグメントに分割 `k`し、パリティフラグメントを計算し `m`ます。

 `k + m = n`フラグメントはストレージノード全体に分散され、 `n`次のようにデータが保護されます。

* オブジェクトを読み出しまたは修復するには `k`、フラグメントが必要です。
* オブジェクトは失われたフラグメントまたは破損したフラグメントまで保持できます `m`。の値が大きいほど `m`、耐障害性が高くなります。


最適なデータ保護は、ストレージプール内のノードまたはボリュームの耐障害性が最も高いイレイジャーコーディングスキームによって実現されます。



== ストレージオーバーヘッド

イレイジャーコーディングスキームのストレージオーバーヘッドは(`m`、パリティフラグメント数をデータフラグメント数で割って計算され(`k`ます。ストレージオーバーヘッドを使用して、各イレイジャーコーディングオブジェクトに必要なディスクスペースを計算できます。

`_disk space_ = _object size_ + (_object size_ * _storage overhead_)`

たとえば、 4+2 スキームを使用して 10MB のオブジェクト（ストレージオーバーヘッドが 50% ）を格納すると、そのオブジェクトが消費するグリッドストレージは 15MB です。6+3 のストレージオーバーヘッドを含む 6+2 スキームを使用して同じ 10MB のオブジェクトを格納すると、オブジェクトが消費するサイズは約 13.3 MB になります。

ニーズに合ったイレイジャーコーディングスキームのうち、の合計値が最も小さいものを選択します `k+m`。フラグメント数が少ないイレイジャーコーディングスキームの方が計算効率が高い理由は次のとおりです。

* オブジェクトごとに作成、分散（読み出し）されるフラグメント数を削減
* フラグメントサイズが大きいため、パフォーマンスが向上します。
* ノードの追加に必要なノード数を減らすことができます。link:../expand/index.html["ストレージの追加が必要になった場合の拡張"]




== ストレージプールに関するガイドライン

イレイジャーコーディングコピーを作成するルールに使用するストレージプールを選択する場合は、ストレージプールについて次のガイドラインに従ってください。

* ストレージプールには 3 つ以上のサイト、または 1 つのサイトだけが含まれている必要があります。
+

NOTE: ストレージプールにサイトが2つ含まれている場合はイレイジャーコーディングを使用できません。

+
** <<3 つ以上のサイトを含むストレージプールのイレイジャーコーディングスキーム,3 つ以上のサイトを含むストレージプールのイレイジャーコーディングスキーム>>
** <<1 サイトのストレージプールのイレイジャーコーディングスキーム,1 サイトのストレージプールのイレイジャーコーディングスキーム>>


* All Sitesサイトを含むストレージプールは使用しないでください。
* ストレージプールには、オブジェクトデータを格納できるストレージノードが少なくとも含まれている必要があります `_k+m_ +1`。
+

NOTE: ストレージ ノードは、インストール時に、オブジェクト データとメタデータ (「結合された」ストレージ ノード)、オブジェクト メタデータのみ、またはオブジェクト データのみを含むように構成できます。詳細については、 link:../primer/what-storage-node-is.html#types-of-storage-nodes["ストレージノードのタイプ"] 。

+
必要なストレージノードの最小数はです `k+m`。ただし、必要なストレージノードが一時的に使用できない場合に、少なくとも 1 つのストレージノードを追加することで、取り込みエラーや ILM バックログが発生するのを防ぐことができます。





== 3 つ以上のサイトを含むストレージプールのイレイジャーコーディングスキーム

次の表に、 3 つ以上のサイトを含むストレージプールについて、 StorageGRID で現在サポートされているイレイジャーコーディングスキームを示します。これらのスキームはすべて、サイト障害からの保護を提供します。1 つのサイトが失われてもオブジェクトには引き続きアクセスできます。

サイト障害からの保護を提供するイレイジャーコーディングスキームの場合、各サイトに少なくとも3つのストレージノードが必要なため、ストレージプール内の推奨されるストレージノード数はよりも多くなります `_k+m_ +1`。

[cols="1a,1a,1a,1a,1a,1a"]
|===
| イレイジャーコーディングスキーム（ _k + m_） | サイトの最小数 | 各サイトで推奨されるストレージノードの数 | 推奨されるストレージノードの総数 | サイト障害からの保護 | ストレージオーバーヘッド 


 a| 
4+2
 a| 
3
 a| 
3
 a| 
9
 a| 
はい
 a| 
50%



 a| 
6+2
 a| 
4
 a| 
3
 a| 
12
 a| 
はい
 a| 
33%



 a| 
8+2
 a| 
5
 a| 
3
 a| 
15
 a| 
はい
 a| 
25%



 a| 
6+3
 a| 
3
 a| 
4
 a| 
12
 a| 
はい
 a| 
50%



 a| 
9+3
 a| 
4
 a| 
4
 a| 
16
 a| 
はい
 a| 
33%



 a| 
2+1
 a| 
3
 a| 
3
 a| 
9
 a| 
はい
 a| 
50%



 a| 
4+1
 a| 
5
 a| 
3
 a| 
15
 a| 
はい
 a| 
25%



 a| 
6+1
 a| 
7
 a| 
3
 a| 
21
 a| 
はい
 a| 
17%



 a| 
7+5
 a| 
3
 a| 
5
 a| 
15
 a| 
はい
 a| 
71%

|===

NOTE: StorageGRID では、サイトごとに少なくとも 3 つのストレージノードが必要です。7+5 スキームを使用するには、各サイトに少なくとも 4 つのストレージノードが必要。サイトごとに 5 つのストレージノードを使用することを推奨します。

サイト保護を提供するイレイジャーコーディングスキームを選択する場合は、次の要素の相対的な重要性を調整します。

* * フラグメント数 * ：フラグメントの総数が少ないほど、一般にパフォーマンスと拡張の柔軟性が向上します。
* *フォールトトレランス*：パリティセグメントの数が多い（の値が大きい）ことでフォールトトレランスが向上します `m`。
* *ネットワークトラフィック*：障害からリカバリする場合、フラグメントの数が多い（の合計数が多い）スキームを使用する `k+m`と、ネットワークトラフィックが増加します。
* * ストレージ・オーバーヘッド * ：オーバーヘッドの大きいスキームでは、オブジェクトごとにより多くのストレージ・スペースが必要です。


たとえば、 4+2 と 6+3 のどちらかのスキーム（どちらも 50% のストレージオーバーヘッドがある）を選ぶ場合、フォールトトレランスをさらに高める必要がある場合は 6+3 のスキームを選択します。ネットワークリソースが制限されている場合は、 4+2 のスキームを選択します。他のすべての要素が等しい場合は、フラグメントの合計数が少ないため、 4+2 を選択します。


NOTE: 使用するスキームが不明な場合は、 4+2 または 6+3 を選択するか、テクニカルサポートにお問い合わせください。



== 1 サイトのストレージプールのイレイジャーコーディングスキーム

1 サイトのストレージプールでは、サイトに十分な数のストレージノードがある場合、 3 つ以上のサイト用に定義されたすべてのイレイジャーコーディングスキームがサポートされます。

必要なストレージノードの最小数はです `k+m`が、ストレージノードを含むストレージプールを `k+m +1`推奨します。たとえば、 2+1 イレイジャーコーディングスキームには少なくとも 3 つのストレージノードからなるストレージプールが必要ですが、推奨されるストレージノード数は 4 つです。

[cols="1a,1a,1a,1a"]
|===
| イレイジャーコーディングスキーム（ _k + m_） | ストレージノードの最小数 | 推奨されるストレージノードの数 | ストレージオーバーヘッド 


 a| 
4+2
 a| 
6
 a| 
7
 a| 
50%



 a| 
6+2
 a| 
8
 a| 
9
 a| 
33%



 a| 
8+2
 a| 
10
 a| 
11
 a| 
25%



 a| 
6+3
 a| 
9
 a| 
10
 a| 
50%



 a| 
9+3
 a| 
12
 a| 
13
 a| 
33%



 a| 
2+1
 a| 
3
 a| 
4
 a| 
50%



 a| 
4+1
 a| 
5
 a| 
6
 a| 
25%



 a| 
6+1
 a| 
7
 a| 
8
 a| 
17%



 a| 
7+5
 a| 
12
 a| 
13
 a| 
71%

|===