---
permalink: ilm/what-cloud-storage-pool-is.html 
sidebar: sidebar 
keywords: what is a cloud storage pool 
summary: クラウドストレージプールでは、 ILM を使用して StorageGRID システムの外部にオブジェクトデータを移動できます。たとえば、アクセス頻度の低いオブジェクトを低コストのクラウドストレージ（Amazon S3 Glacier、S3 Glacier Deep Archive、Google Cloud、Microsoft Azure BLOBストレージのアーカイブアクセス層など）に移動できます。または、 StorageGRID オブジェクトのクラウドバックアップを保持して、ディザスタリカバリを強化することもできます。 
---
= クラウドストレージプールとは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラウドストレージプールでは、 ILM を使用して StorageGRID システムの外部にオブジェクトデータを移動できます。たとえば、アクセス頻度の低いオブジェクトを低コストのクラウドストレージ（Amazon S3 Glacier、S3 Glacier Deep Archive、Google Cloud、Microsoft Azure BLOBストレージのアーカイブアクセス層など）に移動できます。または、 StorageGRID オブジェクトのクラウドバックアップを保持して、ディザスタリカバリを強化することもできます。

ILM から見た場合、クラウドストレージプールはストレージプールに似ています。どちらの場所にオブジェクトを格納する場合も、 ILM ルールの配置手順の作成時にプールを選択します。ただし、ストレージプールはStorageGRIDシステム内のストレージノードで構成されますが、クラウドストレージプールは外部のバケット（S3）またはコンテナ（Azure BLOBストレージ）で構成されます。

次の表に、ストレージプールとクラウドストレージプールを比較し、類似点と相違点の概要を示します。

[cols="1a,2a,5a"]
|===
|  | ストレージプール | クラウドストレージプール 


 a| 
作成方法
 a| 
Grid Manager で * ILM * > * ストレージプール * オプションを使用している。
 a| 
Grid Managerで* ILM *>* Storage pools *>* Cloud Storage Pools *オプションを使用する。

クラウドストレージプールを作成する前に、外部のバケットまたはコンテナをセットアップする必要があります。



 a| 
作成できるプール数
 a| 
無制限。
 a| 
最大 10 個。



 a| 
オブジェクトの格納先
 a| 
StorageGRID内の1つ以上のストレージノード。
 a| 
Amazon S3バケット、Azure BLOBストレージコンテナ、またはStorageGRIDシステムの外部にあるGoogle Cloud。

クラウドストレージプールが Amazon S3 バケットの場合：

* 必要に応じて、 Amazon S3 Glacier や S3 Glacier Deep Archive などの低コストの長期保存用ストレージにオブジェクトを移行するようにバケットライフサイクルを設定できます。外部ストレージシステムでGlacierストレージクラスとS3 RestoreObject APIがサポートされている必要があります。
* AWS Commercial クラウド サービス （ C2S ）で使用するクラウドストレージプールを作成できます。 C2S は AWS Secret Region をサポートします。


クラウドストレージプールが Azure BLOB ストレージコンテナの場合、 StorageGRID はオブジェクトをアーカイブ層に移行します。

*注：*一般的に、クラウドストレージプールに使用するコンテナに対してAzure BLOBストレージのライフサイクル管理を構成しないでください。クラウドストレージプール内のオブジェクトに対するRestoreObject処理は、設定されたライフサイクルの影響を受ける可能性があります。



 a| 
オブジェクトの配置を制御する要素
 a| 
アクティブなILMポリシー内のILMルール。
 a| 
アクティブなILMポリシー内のILMルール。



 a| 
使用されるデータ保護方法はどれですか？
 a| 
レプリケーションまたはイレイジャーコーディング。
 a| 
レプリケーション：



 a| 
各オブジェクトに許可されるコピー数
 a| 
複数。
 a| 
クラウドストレージプールに 1 つ、また必要に応じて StorageGRID に 1 つ以上のコピーを作成します。

*注：* 1つのオブジェクトを複数のクラウドストレージプールに同時に格納することはできません。



 a| 
利点は何ですか？
 a| 
オブジェクトにいつでもすばやくアクセスできる。
 a| 
低コストのストレージ。

*注*：FabricPool データをクラウドストレージプールに階層化することはできません。

|===