---
permalink: ilm/when-to-use-cloud-storage-pools.html 
sidebar: sidebar 
keywords: use cloud storage pool, benefits of cloud storage pools 
summary: クラウドストレージプールを使用すると、データを外部の場所にバックアップまたは階層化できます。また、複数のクラウドにデータをバックアップまたは階層化することもできます。 
---
= クラウドストレージプールを使用する状況
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラウドストレージプールを使用すると、データを外部の場所にバックアップまたは階層化できます。また、複数のクラウドにデータをバックアップまたは階層化することもできます。



== StorageGRID データを外部の場所にバックアップします

クラウドストレージプールを使用して、 StorageGRID オブジェクトを外部の場所にバックアップできます。

StorageGRID 内のコピーにアクセスできない場合は、クラウドストレージプール内のオブジェクトデータを使用してクライアント要求を処理できます。ただし、クラウドストレージプール内のバックアップオブジェクトコピーにアクセスするには、問題S3 RestoreObject要求が必要になる場合があります。

クラウドストレージプール内のオブジェクトデータは、ストレージボリュームまたはストレージノードの障害が原因で失われたデータを StorageGRID からリカバリする場合にも使用できます。オブジェクトのコピーがクラウドストレージプールにしか残っていない場合、 StorageGRID はオブジェクトを一時的にリストアして、リカバリされたストレージノードに新しいコピーを作成します。

バックアップ解決策 を実装するには

. 単一のクラウドストレージプールを作成する。
. ストレージノードにオブジェクトコピーを（レプリケートコピーまたはイレイジャーコーディングコピーとして）同時に格納し、クラウドストレージプールにオブジェクトコピーを 1 つ格納する ILM ルールを設定します。
. ルールを ILM ポリシーに追加します。次に、ポリシーをシミュレートしてアクティブ化します。




== StorageGRID から外部の場所にデータを階層化します

クラウドストレージプールを使用して、 StorageGRID システムの外部にオブジェクトを格納できます。たとえば、保持する必要のあるオブジェクトが多数あり、それらのオブジェクトにアクセスすることはほとんどありません。クラウドストレージプールを使用してオブジェクトを低コストのストレージに階層化し、 StorageGRID のスペースを解放できます。

階層化解決策 を実装するには：

. 単一のクラウドストレージプールを作成する。
. 使用頻度の低いオブジェクトをストレージノードからクラウドストレージプールに移動する ILM ルールを設定します。
. ルールを ILM ポリシーに追加します。次に、ポリシーをシミュレートしてアクティブ化します。




== 複数のクラウドエンドポイントを維持する

オブジェクトデータを複数のクラウドに階層化またはバックアップする場合は、複数のクラウドストレージプールエンドポイントを設定できます。ILM ルールのフィルタを使用して、各クラウドストレージプールに格納するオブジェクトを指定できます。たとえば、一部のテナントやバケットのオブジェクトをAmazon S3 Glacierに格納し、その他のテナントやバケットのオブジェクトをAzure BLOBストレージに格納できます。または、 Amazon S3 Glacier と Azure BLOB ストレージ間でデータを移動することもできます。


NOTE: 複数のクラウドストレージプールエンドポイントを使用する場合は、オブジェクトを一度に1つのクラウドストレージプールにしか格納できないことに注意してください。

複数のクラウドエンドポイントを実装するには、次

. 最大 10 個のクラウドストレージプールを作成できます。
. 適切なタイミングで適切なオブジェクトデータを各クラウドストレージプールに格納する ILM ルールを設定します。たとえば、バケットAのオブジェクトをクラウドストレージプールAに格納し、バケットBのオブジェクトをクラウドストレージプールBに格納します。または、オブジェクトを一定の時間クラウドストレージプールAに格納してから、クラウドストレージプールBに移動します。
. ルールを ILM ポリシーに追加します。次に、ポリシーをシミュレートしてアクティブ化します。

