---
permalink: release-notes/changes-to-grid-management-api.html 
sidebar: sidebar 
keywords: grid management api, api, api version, swagger, rest api, usageCacheDuration 
summary: StorageGRID 12.1では、グリッド管理APIのバージョン4を使用しています。バージョン4はバージョン3を非推奨とします。ただし、バージョン1、2、3は引き続きサポートされています。 
---
= StorageGRID のGrid Management APIの変更点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.1では、グリッド管理APIのバージョン4を使用しています。バージョン4ではバージョン3は非推奨となりますが、バージョン1、2、3は引き続きサポートされます。


NOTE: 非推奨バージョンの管理 API は StorageGRID で引き続き使用できます。ただし、これらのバージョンの API のサポートは、今後の StorageGRID のリリースで削除される予定です。StorageGRID 12.0 以降にアップグレードした後、 `PUT /grid/config/management` API を使用して非推奨の API を無効化できます。

詳細については、を参照してくださいlink:../admin/using-grid-management-api.html["グリッド管理 API を使用します"]。



[[new-endpoints-for-changing-the-bmc-password-and-lan-ip-settings]]
== BMCパスワードとLAN IP設定を変更するための新しいエンドポイント

以下のエンドポイントが追加され、link:../harden/hardening-guidelines-for-storagegrid-nodes.html#change-appliance-bmc-password["アプライアンスの BMC パスワードを変更する"]できるようになりました。

`PUT /bmc-configuration/root-password`

以下のエンドポイントが追加され、link:../maintain/changing-nodes-network-configuration.html#change-appliance-node-bmc-lan-ip-settings["BMC LAN IP設定を変更または表示する"]できるようになりました。

`PUT /grid/bmc/{node-id}/lan-ip-config`

`GET /grid/bmc/{node-id}/lan-ip-config`
