---
permalink: release-notes/changes-to-s3-rest-api.html 
sidebar: sidebar 
keywords: s3 rest api, api, api version, rest api 
summary: StorageGRID で使用される S3 REST API は定期的に更新されます。 
---
= StorageGRID S3 REST API サポートの変更点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID で使用される S3 REST API は定期的に更新されます。

[cols="1a,4a"]
|===
| リリース | コメント 


 a| 
12.1.0
 a| 
* `If-Match`
+
 `If-Match`ヘッダーの動作は、StorageGRIDの構成によって異なります。このヘッダーを指定すると、エラーメッセージ（501 Not Implemented）が返される可能性があります。 `If-Match`ヘッダーが受け入れられたものの機能しない場合、より厳格な501 Not Implementedエラー動作を有効にするための手順を示すアラートが表示される可能性があります。

* `If-None-Match`
+
 `If-None-Match`ヘッダーの動作は、StorageGRIDの構成によって異なります。このヘッダーを指定すると、エラーメッセージ（501 Not Implemented）が返される可能性があります。 `If-None-Match`ヘッダーが受け入れられたものの機能しない場合、より厳格な501 Not Implementedエラー動作を有効にするための手順を示すアラートが表示される可能性があります。

* 以下のリクエストおよびサポートされているヘッダーに対して、事前計算されたチェックサム値のサポートを追加しました：
+
** CompleteMultipartUpload： `x-amz-checksum-crc32`、 `x-amz-checksum-crc32c`、および `x-amz-checksum-crc64nvme`
** CreateMultipartUpload： `CRC32`、 `CRC32C`、および `CRC64NVME`（ `x-amz-checksum-algorithm`用）
** CopyObject： `CRC32`、 `CRC32C`、 `CRC64NVME`、および `SHA256`（ `x-amz-checksum-algorithm`用）
** PutObject： `x-amz-checksum-crc32`、 `x-amz-checksum-crc32c`、および `x-amz-checksum-crc64nvme`
** UploadPart： `x-amz-checksum-crc32`、 `x-amz-checksum-crc32c`、および `x-amz-checksum-crc64nvme`


*  `x-amz-checksum-type`のCreateMultipartUploadおよびCompleteMultipartUploadのサポートを追加しました。
*  `s3:x-amz-copy-source`ポリシー条件キーのサポートが追加されました。
* 既存のバケットで S3 オブジェクトロックを有効にできるようにします。




 a| 
12.0
 a| 
* 管理インターフェースのクロスオリジン リソース共有 (CORS) のサポートが追加されました。これにより、別のドメインが管理 API を使用してStorageGRID内のデータにアクセスできるようになります。link:../admin/enable-cross-origin-resource-sharing-for-management-interface.html["詳細"] 。
* STS AssumeRole およびセッションポリシーのサポートを追加しました。link:../s3/example-session-policies.html["セッションポリシーの例"] を参照してください。テナントグループごとに AssumeRole を設定できます。




 a| 
11.9
 a| 
* 次の要求およびサポートされるヘッダーについて、事前に計算されたSHA-256チェックサム値のサポートが追加されました。この機能を使用して、アップロードされたオブジェクトの整合性を検証できます。
+
** CompleteMultipartUpload： `x-amz-checksum-sha256`
** CreateMultipartUpload： `x-amz-checksum-algorithm`
** GetObject： `x-amz-checksum-mode`
** HeadObject： `x-amz-checksum-mode`
** ListParts
** PutObject： `x-amz-checksum-sha256`
** アップロードパーツ： `x-amz-checksum-sha256`


* グリッド管理者がテナントレベルの保持期間と準拠設定を制御できるようになりました。これらの設定はS3オブジェクトロックの設定に影響します。
+
** バケットのデフォルトの保持モードとオブジェクトの保持モード：GovernanceまたはCompliance（グリッド管理者が許可している場合）。
** バケットのデフォルトの保持期間およびオブジェクトのRetain Until Date：グリッド管理者が設定した最大保持期間の許容値以下にする必要があります。


* コンテンツエンコーディングとストリーミング `x-amz-content-sha256`値のサポートが改善されました `aws-chunked`。制限事項：
+
** 存在する場合は `chunk-signature`オプションで、検証されていません。
** 存在する場合、 `x-amz-trailer`コンテンツは無視されます。






 a| 
11.8
 a| 
で使用されている名前に一致するようにS3処理の名前が更新されました http://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html["Amazon Web Services （ AWS ）ドキュメント：「 Amazon Simple Storage Service API Reference"^]。



 a| 
11.7
 a| 
* link:../s3/quick-reference-support-for-aws-apis.html["クイックリファレンス：サポートされるS3 API要求"]を追加しました。
* S3オブジェクトロックでのガバナンスモードの使用のサポートが追加されました。
* GET Object要求とHEAD Object要求のStorageGRID固有の応答ヘッダーのサポートが追加されました `x-ntap-sg-cgr-replication-status`。このヘッダーは、グリッド間レプリケーションのオブジェクトのレプリケーションステータスを示します。
* SelectObjectContent要求でParquetオブジェクトがサポートされるようになりました。




 a| 
11.6
 a| 
* GET Object要求とHEAD Object要求でrequestパラメータを使用できるようになりました `partNumber`。
* S3 オブジェクトロックのデフォルト保持モードとデフォルトの保持期間がバケットレベルでサポートされるようになりました。
* オブジェクトに許可される保持期間の範囲を設定するポリシー条件キーのサポートが追加されました `s3:object-lock-remaining-retention-days`。
* 単一のPUT Object処理のmaximum_recommended_sizeを5GiB（5、368、709、120バイト）に変更しました。5GB より大きいオブジェクトがある場合は、マルチパートアップロードを使用してください。




 a| 
11.5
 a| 
* バケットの暗号化の管理のサポートが追加されました。
* S3 オブジェクトのロックと廃止された従来の準拠要求のサポートを追加しました。
* バージョン管理されたバケットでの DELETE Multiple Objects の使用のサポートが追加されました。
*  `Content-MD5`要求ヘッダーが正しくサポートされるようになりました。




 a| 
11.4
 a| 
* DELETE Bucket tagging 、 GET Bucket tagging 、 PUT Bucket tagging のサポートが追加されました。コスト割り当てタグはサポートされていません。
* StorageGRID 11.4 で作成されたバケットでは、オブジェクトキー名がパフォーマンスのベストプラクティスに適合するように制限する必要はなくなりました。
* イベントタイプでのバケット通知のサポートが追加されました `s3:ObjectRestore:Post`。
* マルチパートの AWS サイズの上限が適用されるようになりました。マルチパートアップロードの各パートのサイズは 5MiB から 5GiB の間にする必要があります。最後の部分は 5MiB より小さくすることができます。
* TLS 1.3のサポートが追加されました




 a| 
11.3
 a| 
* ユーザ指定のキーによるオブジェクトデータのサーバ側暗号化（ SSE-C ）がサポートされるようになりました。
* DELETE Bucket lifecycle、GET Bucket lifecycle、PUT Bucket lifecycleの各処理（Expirationアクションのみ）と応答ヘッダーのサポートが追加されました `x-amz-expiration`。
* PUT Object 、 PUT Object - Copy 、 Multipart Upload が更新されて、取り込み時に同期配置を使用する ILM ルールの影響を受けるようになりました。
* TLS 1.1 暗号はサポートされなくなりました。




 a| 
11.2
 a| 
クラウドストレージプールで POST Object restore を使用できるようになりました。グループポリシーとバケットポリシーの ARN 、ポリシー条件キー、およびポリシー変数で AWS 構文を使用できるようになりました。StorageGRID 構文を使用する既存のグループポリシーとバケットポリシーは引き続きサポートされます。

* 注：カスタム StorageGRID 機能で使用される ARN やその他の構成 JSON / XML での使用に変更はありませんでした。



 a| 
11.1
 a| 
Cross-Origin Resource Sharing（CORS）、グリッドノードへのS3クライアント接続でのHTTP、バケットでの準拠設定のサポートが追加されました。



 a| 
11.0
 a| 
バケットでのプラットフォームサービス（ CloudMirror レプリケーション、通知、および Elasticsearch 検索統合）の設定がサポートされるようになりました。また、バケットに対するオブジェクトタギングの場所の制約と「available」の整合性がサポートされるようになりました。



 a| 
10.4
 a| 
ILM スキャンのバージョン管理、エンドポイントドメインの名前ページの更新、ポリシーの条件と変数、ポリシーの例、および PutOverwriteObject 権限の変更のサポートが追加されました。



 a| 
10.3
 a| 
バージョン管理のサポートが追加されました。



 a| 
10.2
 a| 
グループとバケットのアクセスポリシー、およびマルチパートコピー（ Upload Part - Copy ）のサポートが追加されました。



 a| 
10.1
 a| 
マルチパートアップロード、仮想ホスト型リクエスト、およびv4認証のサポートを追加しました。



 a| 
10.0
 a| 
StorageGRIDシステムによる S3 REST API の初期サポート。現在サポートされている _Simple Storage Service API リファレンス_ のバージョンは 2006-03-01 です。

|===
詳細については、link:../s3/index.html#supported-versions["S3 REST APIのサポートされているバージョンとアップデート"] を参照してください。
