---
permalink: release-notes/whats-new.html 
sidebar: sidebar 
keywords: what is new in StorageGRID 12.1 
summary: このリリースの StorageGRID では、以下の機能と機能変更が導入されています。 
---
= StorageGRID 12.1の新機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.1では、以下の機能と変更点が導入されます。

最近の StorageGRID 12.1 リリースにおける修正された問題と既知の問題の詳細については、 https://library.netapp.com/ecm/ecm_download_file/ECMLP3373065["StorageGRID 12.1 リリースノート"^]を参照してください。NetAppアカウントでサインインするか、アカウントを作成してリリースノートにアクセスする必要があります。



[[capacity]]
== 容量



[[ec-rebalance-now-uses-free-space]]
=== ECリバランスは空きスペースを使用するようになりました

ECリバランス機能は、使用済み領域ではなく空き領域を使用するようになりました。link:../expand/considerations-for-rebalancing-erasure-coded-data.html#what-is-ec-rebalancing["StorageGRIDの拡張後の EC 再バランス調整について学ぶ"]を参照してください。



[[metadata-allowed-space]]
=== メタデータ許容スペース

メタデータの最大許容容量を3.96 TBから7.92 TBに増やすことができるようになりました。link:../admin/managing-object-metadata-storage.html#allowed-metadata-space["許可されているメタデータスペースです"]を参照してください。



[[control-access]]
== アクセス制御



[[sso-using-oidc]]
=== OIDCを使用したSSO

これでlink:../admin/learn-about-setting-up-sso-oidc.html["OpenID Connect （OIDC）を使用して StorageGRID でシングル サインオン（SSO）を設定する"]できます。



[[federation]]
== フェデレーション



[[global-namespace]]
=== グローバル ネームスペース

テナントが複数の StorageGRID システムにまたがってバケットにアクセスできるように、グローバル名前空間を設定できるようになりました。link:../admin/learn-about-global-namespace.html["グローバルネームスペースについて"]を参照してください。



[[manageability]]
== 管理性



[[auto-move-adc-service]]
=== ADC サービスの自動移動

link:../maintain/understanding-adc-service-quorum.html["ADCの定足数を満たす必要がある場合"]、ADCサービスは、link:../maintain/convert-to-data-only-node.html["ストレージノードをデータ専用ノードに変換する"]またはlink:../maintain/considerations-for-decommissioning-storage-nodes.html["ストレージノードの廃止"]の際に自動的に移動されるようになりました。



[[primary-admin-node-recovery]]
=== プライマリ管理ノードの復旧

プライマリ以外の管理ノードから、任意のノードを復旧できるようになりました。link:../maintain/recovering-from-primary-admin-node-failures.html["プライマリ管理ノードの障害からの復旧"]を参照してください。



[[s3]]
== S3を使用したチャンク アップロード署名要求がサポートされるようになりました。



[[enable-s3-object-lock-on-existing-buckets]]
=== 既存のバケットでS3オブジェクトロックを有効にする

「既存バケットに対する S3 オブジェクトロックを許可する」設定が有効になっている場合、S3 テナントアカウントは既存バケットに対して S3 オブジェクトロックを有効にできるようになります。S3 テナントアカウントが既存のバケットに対して S3 オブジェクトロックを有効にすると、無効にすることはできません。



[[replication-allowed-for-s3-object-lock-enabled-buckets]]
=== S3オブジェクトロックが有効なバケットのレプリケーションが許可されました

S3 オブジェクトロックが有効なバケット内のオブジェクトを複製するために CloudMirror を使用できるようになりました。link:../tenant/considerations-for-platform-services.html["プラットフォームサービスについて"] を参照してください。



[[enable-cross-grid-replication-for-non-empty-buckets]]
=== 空でないバケットに対してクロスグリッドレプリケーションを有効にする

空でないバケットに対して、クロスグリッドレプリケーションを有効にできるようになりました。link:../admin/grid-federation-what-is-cross-grid-replication.html#requirements-for-cross-grid-replication["グリッド間レプリケーションの要件"]を参照してください。



[[s3-batch-operations-fpvr-only]]
=== S3 バッチ操作 （FPVR のみ）

S3バッチ操作を使用すると、クロスグリッドレプリケーション用に構成予定のバージョン管理が有効になっているバケット内の既存オブジェクトを複製できます。

この機能には StorageGRID 12.1 の FPVR 承認が必要です。この機能をご利用になるには、担当のアカウント担当者にお問い合わせください。



[[non-functional-s3-rest-api-headers]]
=== 機能しないS3 REST APIヘッダー

 `If-Match`および `If-None-Match`ヘッダーは受け入れられますが、S3 REST API link:../s3/put-object.html["PutObject"]、link:../s3/complete-multipart-upload.html["CompleteMultipartUpload"]、link:../s3/put-object-copy.html["CopyObject"]、およびlink:../s3/operations-on-objects.html["deleteObject"]では機能しません。

詳細については、link:../release-notes/changes-to-s3-rest-api.html["StorageGRID S3 REST API サポートの変更点"]を参照してください。



[[support-for-pre-calculated-checksum-values]]
=== 事前計算されたチェックサム値のサポート

S3 REST SPI は、事前計算されたチェックサム値と `x-amz-checksum-type`リクエストヘッダーをサポートするようになりました。link:../s3/index.html#updates-to-rest-api-support["REST API サポートの更新内容"]を参照してください。



[[security]]
== セキュリティ



[[multi-admin-verification]]
=== マルチ管理者認証

マルチ管理者検証 （MAV） は、StorageGRID システムへの偶発的または不正な変更を防ぐのに役立ちます。link:../admin/about-multi-admin-verify.html["StorageGRID マルチ管理者検証について"]を参照してください。



[[security-policy-updates-for-fips]]
=== FIPSに関するセキュリティポリシーの更新

FIPSの厳格なポリシー基準が更新されました。link:../admin/manage-tls-ssh-policy.html#select-a-security-policy["「TLSおよびSSHポリシーの管理」でセキュリティポリシーを選択します。"]を参照してください。



[[tenants]]
== テナント



[[account-sync]]
=== アカウント同期

「アカウントクローン」機能は、特定のテナントアカウント情報を一度だけ複製する機能を指すようになりました。

_アカウント同期_は、1つ以上のグリッドフェデレーション接続内のStorageGRIDシステム間で、テナントアカウント、テナントグループ、テナントユーザー、およびS3アクセスキーを自動的かつ継続的にレプリケートできる新機能です。link:../admin/grid-federation-what-is-account-sync.html["StorageGRID のアカウント同期について"]を参照してください。



[[kafka-endpoints-and-mtls-authentication]]
=== KafkaエンドポイントとmTLS認証

Kafkaエンドポイントで、相互トランスポート層セキュリティ（mTLS）がサポートされるようになりました。link:../tenant/configuring-platform-services-endpoints.html["プラットフォームサービスエンドポイントを設定する"]を参照してください。



[[maximum-number-of-buckets]]
=== バケットの最大数

StorageGRID システムは、S3 テナントアカウントごとに最大 20,000 個のバケットをサポートするようになりました。



[[upgrade]]
== Upgrade



[[time-to-enable-features-is-increased]]
=== 機能の有効化にかかる時間が長くなります

StorageGRID をバージョン 12.1 にアップグレードする際、機能の有効化にかかる時間が 5 分未満から 1 時間に増加しました。link:../upgrade/estimating-time-to-complete-upgrade.html#estimate-time-to-upgrade["StorageGRIDアップグレードの完了までの時間を見積もる"] を参照してください。



[[user-interface]]
== ユーザーインターフェース



[[bmc-settings-page]]
=== BMC設定ページ

Grid Manager のノードページに新しい BMC 設定タブが追加され、BMC パスワードのリセットおよび BMC LAN IP 設定の変更が可能になりました。link:../harden/hardening-guidelines-for-storagegrid-nodes.html["アプライアンスのBMCパスワードを変更する"] および link:../maintain/changing-nodes-network-configuration.html#change-appliance-node-bmc-lan-ip-settings["アプライアンスノードのBMC LAN IP設定を変更する"] を参照してください。これらの機能をサポートするために、新しい API エンドポイントも追加されました。link:../release-notes/changes-to-grid-management-api.html["BMCパスワードとLAN IP設定を変更するための新しいエンドポイント"] を参照してください。



[[email-notifications]]
=== メール通知

グリッドマネージャーには、アラート、AutoSupport、および複数管理者認証（MAV）のメール通知を設定および管理するための共通のメールページが追加されました。詳細については、link:../monitor/configure-email-server.html["メールサーバーの設定"]を参照してください。



[[link-cost-page-update]]
=== リンク費用ページ更新

StorageGRID 12.1では、より詳細なリンクコスト情報と設定が提供されます。link:../admin/manage-link-costs.html["リンクコストを管理します"]を参照してください。



[[usb-port-control]]
=== USBポート制御

Grid ManagerからUSBポートを有効または無効にできるようになりました。link:../harden/hardening-guidelines-for-storagegrid-nodes.html#control-remote-access-through-usb-ports["USBポート経由でリモートアクセスを制御する"]を参照してください。
