---
permalink: fabricpool/creating-load-balancer-endpoint-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, load balancer, endpoint, load balancing, create, creating, certificate 
summary: StorageGRID は、ロードバランサを使用して、FabricPool などのクライアントアプリケーションからワークロードを管理します。ロードバランシングは、複数のストレージノードにわたって速度と接続容量を最大化します。 
---
= FabricPool のロードバランサエンドポイントを作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID は、ロードバランサを使用して、FabricPool などのクライアントアプリケーションからワークロードを管理します。ロードバランシングは、複数のストレージノードにわたって速度と接続容量を最大化します。

FabricPool で使用するStorageGRID を設定する場合は、ロードバランサエンドポイントを設定し、ロードバランサエンドポイント証明書をアップロードまたは生成する必要があります。これは、ONTAP とStorageGRID の間の接続を保護するために使用します。

FabricPoolセットアップウィザードを使用してこのタスクを実行するには、に進みますlink:use-fabricpool-setup-wizard-steps.html["FabricPool セットアップウィザードにアクセスして完了します"]。

.開始する前に
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたはを持っていますlink:../admin/admin-group-permissions.html["rootアクセス権限"]。
* 一般およびを確認しておく必要link:best-practices-for-load-balancing.html["FabricPool のロードバランシングのベストプラクティス"]がありlink:../admin/managing-load-balancing.html["ロードバランシングに関する考慮事項"]ます。


.手順
. *構成* > *ネットワーク* > *ロードバランサーエンドポイント*を選択します。
. 「 * Create * 」を選択します。
. Enter endpoint details *ステップで、次のフィールドに値を入力します。
+
[cols="1a,2a"]
|===
| フィールド | 製品説明 


 a| 
名前
 a| 
エンドポイントのわかりやすい名前。



 a| 
ポート
 a| 
ロードバランシングに使用する StorageGRID ポート。最初に作成するエンドポイントのデフォルトは10433ですが、未使用の外部ポートを入力できます。80または443を入力すると、エンドポイントはゲートウェイノードでのみ設定されます。これらのポートは管理ノードで予約されています。

*注：*他のグリッドサービスで使用されるポートは許可されません。を参照してくださいlink:../network/internal-grid-node-communications.html["ネットワークポートのリファレンス"]。

この番号は、StorageGRID をFabricPool クラウド階層として接続するときにONTAP に指定します。



 a| 
クライアントタイプ
 a| 
S3 を選択します。



 a| 
ネットワークプロトコル
 a| 
「* HTTPS *」を選択します。

*注*：TLS暗号化なしでのStorageGRID との通信はサポートされていますが、推奨されません。

|===
. [結合モードの選択]ステップで、結合モードを指定します。バインドモードは、任意のIPアドレスまたは特定のIPアドレスとネットワークインターフェイスを使用してエンドポイントにアクセスする方法を制御します。
+
[cols="1a,3a"]
|===
| モード | 製品説明 


 a| 
グローバル（デフォルト）
 a| 
クライアントは、任意のゲートウェイノードまたは管理ノードのIPアドレス、任意のネットワーク上の任意のHAグループの仮想IP（VIP）アドレス、または対応するFQDNを使用して、エンドポイントにアクセスできます。

このエンドポイントのアクセスを制限する必要がある場合を除き、 * グローバル * 設定（デフォルト）を使用します。



 a| 
HA グループの仮想 IP
 a| 
クライアントがこのエンドポイントにアクセスするには、HAグループの仮想IPアドレス（または対応するFQDN）を使用する必要があります。

このバインドモードのエンドポイントでは、エンドポイント用に選択したHAグループが重複しないかぎり、すべて同じポート番号を使用できます。



 a| 
ノードインターフェイス
 a| 
クライアントがこのエンドポイントにアクセスするには、選択したノードインターフェイスのIPアドレス（または対応するFQDN）を使用する必要があります。



 a| 
ノードタイプ
 a| 
選択したノードのタイプに基づいて、クライアントがこのエンドポイントにアクセスするには、いずれかの管理ノードのIPアドレス（または対応するFQDN）か、いずれかのゲートウェイノードのIPアドレス（または対応するFQDN）を使用する必要があります。

|===
. [Tenant access]*ステップで、次のいずれかを選択します。
+
[cols="1a,2a"]
|===
| フィールド | 製品説明 


 a| 
Allow all tenants（デフォルト）
 a| 
すべてのテナントアカウントは、このエンドポイントを使用してバケットにアクセスできます。

*[Allow all tenants]*は、ほとんどの場合、FabricPool に使用するロードバランサエンドポイントに適したオプションです。

テナントアカウントをまだ作成していない場合は、このオプションを選択する必要があります。



 a| 
選択したテナントを許可します
 a| 
このエンドポイントを使用してバケットにアクセスできるのは、選択したテナントアカウントのみです。



 a| 
選択したテナントをブロックします
 a| 
選択したテナントアカウントは、このエンドポイントを使用してバケットにアクセスできません。他のすべてのテナントでこのエンドポイントを使用できます。

|===
. [証明書の添付]*ステップで、次のいずれかを選択します。
+
[cols="1a,2a"]
|===
| フィールド | 製品説明 


 a| 
証明書のアップロード（推奨）
 a| 
このオプションは、CA署名済みサーバ証明書、証明書秘密鍵、およびオプションのCAバンドルをアップロードする場合に使用します。



 a| 
証明書の生成
 a| 
このオプションは、自己署名証明書を生成する場合に使用します。入力する項目の詳細については、を参照してくださいlink:../admin/configuring-load-balancer-endpoints.html["ロードバランサエンドポイントを設定する"]。



 a| 
StorageGRID S3証明書を使用する
 a| 
このオプションは、StorageGRID グローバル証明書のカスタムバージョンをすでにアップロードまたは生成している場合にのみ使用できます。詳細は、を参照してください link:../admin/configuring-custom-server-certificate-for-storage-node.html["S3 API証明書の設定"] 。

|===
. 「 * Create * 」を選択します。



NOTE: エンドポイント証明書の変更がすべてのノードに適用されるまでに最大 15 分かかることがあります。
