---
permalink: fabricpool/creating-ha-group-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, StorageGRID, high availability group, HA group, create, creating, virtual IP, VIP, active interface, backup interface 
summary: FabricPool で使用するように StorageGRID を設定する場合は、必要に応じて 1 つ以上のハイアベイラビリティ（ HA ）グループを作成できます。HAグループは、それぞれにStorageGRID ロードバランササービスが含まれるノードの集まりです。HAグループには、ゲートウェイノード、管理ノード、またはその両方を含めることができます。 
---
= StorageGRIDでFabricPool用の高可用性（HA）グループを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool で使用するように StorageGRID を設定する場合は、必要に応じて 1 つ以上のハイアベイラビリティ（ HA ）グループを作成できます。HAグループは、それぞれにStorageGRID ロードバランササービスが含まれるノードの集まりです。HAグループには、ゲートウェイノード、管理ノード、またはその両方を含めることができます。

HAグループを使用すると、FabricPool データ接続の可用性を維持できます。HAグループは、仮想IPアドレス（VIP）を使用してロードバランササービスへの可用性の高いアクセスを提供します。HAグループのアクティブインターフェイスで障害が発生しても、バックアップインターフェイスでワークロードを管理できるため、FabricPool の処理への影響はほとんどありません。

このタスクの詳細については、を参照してくださいlink:../admin/managing-high-availability-groups.html["ハイアベイラビリティグループを管理します"]。FabricPoolセットアップウィザードを使用してこのタスクを実行するには、に進みますlink:use-fabricpool-setup-wizard-steps.html["FabricPool セットアップウィザードにアクセスして完了します"]。

.開始する前に
* を確認しておきますlink:best-practices-for-high-availability-groups.html["ハイアベイラビリティグループのベストプラクティス"]。
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたはを持っていますlink:../admin/admin-group-permissions.html["rootアクセス権限"]。
* VLAN を使用する場合は、 VLAN インターフェイスを作成しておきます。を参照して link:../admin/configure-vlan-interfaces.html["VLAN インターフェイスを設定します"]


.手順
. *構成* > *ネットワーク* > *高可用性グループ*を選択します。
. 「 * Create * 」を選択します。
. [詳細を入力]*ステップで、次のフィールドに値を入力します。
+
[cols="1a,2a"]
|===
| フィールド | 製品説明 


 a| 
HAグループ名
 a| 
このHAグループの一意の表示名。



 a| 
概要 （オプション）
 a| 
このHAグループの概要 。

|===
. [インターフェイスの追加]*手順で、このHAグループで使用するノードインターフェイスを選択します。
+
列ヘッダーを使用して行をソートするか、検索キーワードを入力してインターフェイスをより迅速に検索します。

+
ノードは1つ以上選択できますが、ノードごとに選択できるインターフェイスは1つだけです。

. [* prioritize interfaces]ステップでは、このHAグループのプライマリインターフェイスとバックアップインターフェイスを決定します。
+
行をドラッグして、*優先順位*列の値を変更します。

+
リストの最初のインターフェイスはプライマリインターフェイスです。プライマリインターフェイスは、障害が発生しないかぎり、アクティブインターフェイスです。

+
HAグループに複数のインターフェイスが含まれていて、アクティブインターフェイスで障害が発生した場合、仮想IP（VIP）アドレスは優先順位に従って最初のバックアップインターフェイスに移動します。そのインターフェイスに障害が発生すると、 VIP アドレスは次のバックアップインターフェイスに移動します。障害が解決されると、 VIP アドレスは利用可能な最優先インターフェイスに戻ります。

. [IPアドレスの入力]*ステップで、次のフィールドに値を入力します。
+
[cols="1a,2a"]
|===
| フィールド | 製品説明 


 a| 
サブネットCIDR
 a| 
VIPサブネットのアドレス（CIDR表記）。IPv4アドレス、スラッシュ、およびサブネットの長さ（0～32）。

ネットワークアドレスにホストビットを設定しないでください。たとえば、 `192.16.0.0/22`です。



 a| 
ゲートウェイIPアドレス（オプション）
 a| 
オプション。StorageGRID へのアクセスに使用するONTAP IPアドレスがStorageGRID VIPアドレスと同じサブネット上にない場合は、StorageGRID VIPローカルゲートウェイのIPアドレスを入力します。ローカルゲートウェイの IP アドレスは VIP サブネット内にある必要があります。



 a| 
仮想IPアドレス
 a| 
HAグループ内のアクティブインターフェイスのVIPアドレスを1つ以上10個以下で入力します。すべてのVIPアドレスがVIPサブネット内にある必要があります。

IPv4アドレスを少なくとも1つ指定する必要があります。必要に応じて、追加の IPv4 アドレスと IPv6 アドレスを指定できます。

|===
. HA グループの作成 * を選択し、完了 * を選択します。

