---
permalink: fabricpool/use-fabricpool-setup-wizard.html 
sidebar: sidebar 
keywords: fabricPool, FabricPool setup wizard, ontap system manager 
summary: FabricPool セットアップウィザードを使用して、StorageGRID をFabricPool クラウド階層用のオブジェクトストレージシステムとして設定できます。セットアップウィザードが完了したら、ONTAP システムマネージャに必要な詳細を入力できます。 
---
= FabricPool セットアップウィザードの使用：考慮事項と要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool セットアップウィザードを使用して、StorageGRID をFabricPool クラウド階層用のオブジェクトストレージシステムとして設定できます。セットアップウィザードが完了したら、ONTAP システムマネージャに必要な詳細を入力できます。



== FabricPool セットアップウィザードを使用するタイミング

FabricPool セットアップウィザードの手順に従って、FabricPool で使用するStorageGRID を設定し、ILMポリシーやトラフィック分類ポリシーなどの特定のエンティティを自動的に設定します。ウィザードを完了する際に、ONTAP システムマネージャに値を入力するためのファイルをダウンロードします。ウィザードを使用すると、システムをより迅速に設定し、設定がStorageGRID とFabricPool のベストプラクティスに準拠していることを確認できます。

Root Access権限がある場合は、StorageGRID グリッドマネージャの使用を開始したときにFabricPool セットアップウィザードを完了することも、ウィザードにアクセスして完了することもできます。要件に応じて、必要な項目の一部またはすべてを手動で設定し、ウィザードを使用してONTAP で必要な値を1つのファイルにまとめることもできます。


TIP: 特別な要件がある場合や、実装に大幅なカスタマイズが必要な場合を除き、FabricPool セットアップウィザードを使用します。



== ウィザードを使用する前に

必要な準備手順が完了していることを確認します。



=== ベストプラクティスを確認

* を理解しておく必要link:information-needed-to-attach-storagegrid-as-cloud-tier.html["StorageGRID をクラウド階層として接続するために必要な情報"]があります。
* 次の項目について、FabricPool のベストプラクティスを確認しておきます。
+
** link:best-practices-for-high-availability-groups.html["ハイアベイラビリティ（HA）グループ"]
** link:best-practices-for-load-balancing.html["ロードバランシング"]
** link:best-practices-ilm.html["ILMルールとポリシー"]






=== IPアドレスを取得し、VLANインターフェイスを設定します

HAグループを設定する場合は、ONTAP が接続するノードと使用するStorageGRID ネットワークを確認しておきます。また、サブネットCIDR、ゲートウェイIPアドレス、および仮想IP（VIP）アドレスに入力する値も確認しておきます。

仮想LANを使用してFabricPool トラフィックを分離する予定の場合は、VLANインターフェイスがすでに設定されています。を参照して link:../admin/configure-vlan-interfaces.html["VLAN インターフェイスを設定します"]



=== アイデンティティフェデレーションとSSOを設定する

StorageGRID システムでアイデンティティフェデレーションまたはシングルサインオン（SSO）を使用する場合は、これらの機能を有効にしておきます。また、ONTAP が使用するテナントアカウントへのルートアクセスが必要なフェデレーテッドグループも確認しておきます。およびを参照してくださいlink:../admin/using-identity-federation.html["アイデンティティフェデレーションを使用する"]link:../admin/how-sso-works.html["シングルサインオンを設定します"]。



=== ドメイン名を取得して設定します

* StorageGRID に使用するFully Qualified Domain Name（FQDN；完全修飾ドメイン名）を確認しておきます。ドメインネームサーバ（DNS）のエントリによって、このFQDNが、ウィザードを使用して作成するHAグループの仮想IP（VIP）アドレスにマッピングされます。を参照して link:../fabricpool/configure-dns-server.html["DNS サーバを設定します"]
* S3仮想ホスト形式の要求を使用する場合は、を準備しておきlink:../admin/configuring-s3-api-endpoint-domain-names.html["S3エンドポイントのドメイン名が設定されました"]ます。ONTAP はデフォルトでパス形式のURLを使用しますが、仮想ホスト形式の要求を使用することを推奨します。




=== ロードバランサとセキュリティ証明書の要件を確認します

StorageGRIDロードバランサを使用する場合は、全般を確認しておきます。link:../admin/managing-load-balancing.html["ロードバランシングに関する考慮事項"]アップロードする証明書、または証明書の生成に必要な値を用意しておきます。

外部（サードパーティ）のロードバランサエンドポイントを使用する場合は、そのロードバランサの完全修飾ドメイン名（FQDN）、ポート、および証明書が必要です。



=== ILMストレージプールの設定を確認する

StorageGRID 11.6以前を最初にインストールした場合は、使用するストレージプールがすでに設定されています。一般に、ONTAP データの格納に使用するStorageGRID サイトごとにストレージプールを作成する必要があります。


NOTE: この前提条件は、StorageGRID 11.7または11.8を最初にインストールした場合は適用されません。これらのバージョンのいずれかを最初にインストールすると、サイトごとにストレージプールが自動的に作成されます。



== ONTAP とStorageGRID クラウド階層の関係

FabricPool ウィザードの手順に従って、1つのStorageGRID クラウド階層を作成します。この階層には、1つのStorageGRID テナント、1セットのアクセスキー、1つのStorageGRID バケットが含まれます。このStorageGRID クラウド階層を1つ以上のONTAP ローカル階層に接続できます。

クラスタ内の複数のローカル階層に単一のクラウド階層を接続することを推奨します。ただし、要件に応じて、1つのクラスタ内のローカル階層に対して複数のバケットまたは複数のStorageGRID テナントを使用することもできます。異なるバケットやテナントを使用すると、ONTAP ローカル階層間でデータアクセスとデータアクセスを分離できますが、設定や管理はやや複雑です。

複数のクラスタにあるローカル階層に単一のクラウド階層を接続することは推奨されません。


NOTE: NetApp MetroCluster™およびFabricPoolミラーでStorageGRIDを使用する場合のベストプラクティスについては、を参照してください https://www.netapp.com/pdf.html?item=/media/17239-tr4598pdf.pdf["TR-4598：『FabricPool Best Practices in ONTAP 』"^]。



=== オプション：ローカル階層ごとに異なるバケットを使用します

ONTAP クラスタのローカル階層に複数のバケットを使用するには、ONTAP で複数のStorageGRID クラウド階層を追加します。各クラウド階層は、同じHAグループ、ロードバランサエンドポイント、テナント、アクセスキーを共有しますが、別 々 のコンテナ（StorageGRID バケット）を使用します。一般的な手順は次のとおりです。

. StorageGRID グリッドマネージャから、1つ目のクラウド階層に対してFabricPool セットアップウィザードを実行します。
. ONTAP System Managerで、クラウド階層を追加し、StorageGRID からダウンロードしたファイルを使用して必要な値を指定します。
. StorageGRID テナントマネージャから、ウィザードで作成されたテナントにサインインし、2つ目のバケットを作成します。
. FabricPool ウィザードをもう一度実行します。既存のHAグループ、ロードバランサエンドポイント、およびテナントを選択します。次に、手動で作成した新しいバケットを選択します。新しいバケット用の新しいILMルールを作成し、ILMポリシーをアクティブ化してそのルールを追加します。
. ONTAP で、新しいバケット名を指定して2つ目のクラウド階層を追加します。




=== オプション：ローカル階層ごとに異なるテナントとバケットを使用します

ONTAP クラスタ内のローカル階層に対して複数のテナントと異なるアクセスキーセットを使用するには、ONTAP で複数のStorageGRID クラウド階層を追加します。各クラウド階層は同じHAグループとロードバランサエンドポイントを共有しますが、使用するテナント、アクセスキー、コンテナ（StorageGRID バケット）は異なります。一般的な手順は次のとおりです。

. StorageGRID グリッドマネージャから、1つ目のクラウド階層に対してFabricPool セットアップウィザードを実行します。
. ONTAP System Managerで、クラウド階層を追加し、StorageGRID からダウンロードしたファイルを使用して必要な値を指定します。
. FabricPool ウィザードをもう一度実行します。既存のHAグループとロードバランサエンドポイントを選択します。新しいテナントとバケットを作成する。新しいバケット用の新しいILMルールを作成し、ILMポリシーをアクティブ化してそのルールを追加します。
. ONTAP で、新しいアクセスキー、シークレットキー、およびバケット名を指定して、2つ目のクラウド階層を追加します。

