---
permalink: fabricpool/using-storagegrid-ilm-with-fabricpool-data.html 
sidebar: sidebar 
keywords: FabricPool, requirements, ILM, information lifecycle management, ILM rule, ILM rules, ILM policy, erasure coding, replication, cloud storage pool, glacier 
summary: このシンプルなサンプルポリシーを、独自のILMルールとポリシーの出発点として使用できます。 
---
= FabricPool データ用のILMを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このシンプルなサンプルポリシーを、独自のILMルールとポリシーの出発点として使用できます。

この例では、コロラド州デンバーの 1 つのデータセンターに 4 つのストレージノードがある StorageGRID システムの ILM ルールと ILM ポリシーを設計していることを前提としています。この例のFabricPoolデータでは、というバケットを使用して `fabricpool-bucket`います。


CAUTION: 以下の ILM ルールとポリシーは一例にすぎません。ILM ルールを設定する方法は多数あります。新しいポリシーをアクティブ化する前に、ポリシーをシミュレートして、コンテンツを損失から保護するために意図したとおりに機能することを確認します。詳細については、を参照してくださいlink:../ilm/index.html["ILM を使用してオブジェクトを管理する"]。


CAUTION: データ損失を回避するために、FabricPoolクラウド階層のデータが期限切れになるILMルールを使用しないでください。FabricPoolオブジェクトがStorageGRID ILMによって削除されないようにするには、保持期間を* forever *に設定します。

.開始する前に
* を確認しておきますlink:best-practices-ilm.html["FabricPool データでILMを使用するためのベストプラクティス"]。
* Grid Managerにサインインしておきますlink:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* あなたはを持っていますlink:../admin/admin-group-permissions.html["ILMまたはRoot Access権限"]。
* 以前のバージョンのStorageGRIDからStorageGRID 11.9にアップグレードした場合は、使用するストレージプールが設定されています。一般に、データの格納に使用するStorageGRIDサイトごとにストレージプールを作成する必要があります。
+

NOTE: この前提条件は、StorageGRID 11.7または11.8を最初にインストールした場合は適用されません。これらのバージョンのいずれかを最初にインストールすると、サイトごとにストレージプールが自動的に作成されます。



.手順
. のデータにのみ適用するILMルールを作成し `fabricpool-bucket`ます。この例では、イレイジャーコーディングコピーを作成します。
+
[cols="1a,2a"]
|===
| ルール定義 | 値の例 


 a| 
ルール名
 a| 
2+1のイレイジャーコーディング（FabricPool データ用



 a| 
バケット名
 a| 
`fabricpool-bucket`

FabricPool テナントアカウントでフィルタリングすることもできます。



 a| 
高度なフィルタ
 a| 
オブジェクトサイズが0.2MBを超えています。

*注：* FabricPool は4MBのオブジェクトのみを書き込みますが、このルールではイレイジャーコーディングを使用するため、オブジェクトサイズフィルタを追加する必要があります。



 a| 
参照時間
 a| 
取り込み時間



 a| 
期間と配置
 a| 
From Day 0は永久に保存されます

デンバーで2+1 ECスキームを使用してイレイジャーコーディングしてオブジェクトを格納し、それらのオブジェクトをStorageGRIDに無期限に保持


CAUTION: データ損失を回避するために、FabricPoolクラウド階層のデータが期限切れになるILMルールを使用しないでください。



 a| 
取り込み動作
 a| 
バランス

|===
. 最初のルールに一致しないオブジェクトのレプリケートコピーを2つ作成するデフォルトのILMルールを作成します。基本フィルタ（テナントアカウントまたはバケット名）や高度なフィルタは選択しないでください。
+
[cols="1a,2a"]
|===
| ルール定義 | 値の例 


 a| 
ルール名
 a| 
2 つのレプリケートコピー



 a| 
バケット名
 a| 
_ なし _



 a| 
高度なフィルタ
 a| 
_ なし _



 a| 
参照時間
 a| 
取り込み時間



 a| 
期間と配置
 a| 
From Day 0は永久に保存されます

デンバーに2つのコピーをレプリケートしてオブジェクトを格納



 a| 
取り込み動作
 a| 
バランス

|===
. ILMポリシーを作成し、2つのルールを選択します。レプリケーションルールではフィルタを使用しないため、ポリシーのデフォルト（最後の）ルールを使用できます。
. テストオブジェクトをグリッドに取り込みます。
. ポリシーをテストオブジェクトでシミュレートして動作を確認します。
. ポリシーをアクティブ化する。


このポリシーをアクティブ化すると、 StorageGRID はオブジェクトデータを次のように配置します。

* のFabricPoolから階層化されたデータ `fabricpool-bucket`は、2+1イレイジャーコーディングスキームを使用してイレイジャーコーディングされます。2 つのデータフラグメントと 1 つのパリティフラグメントが 3 つの異なるストレージノードに配置されます。
* 他のすべてのバケット内のオブジェクトがレプリケートされます。2 つのコピーが作成され、 2 つの異なるストレージノードに配置されます。
* コピーはStorageGRIDで無期限に保持されます。StorageGRID ILMではこれらのオブジェクトは削除されません。

